### ISSUE TITLE
Bug of cupy.util.memoize() on cupy v2.4.0

### ISSUE THREAD

**Issue by leftthomas** [cupy/cupy#1009]
I updated cupy to v2.4.0, and I found the parameter name of `cupy.util.memoize()` is `bool for_each_device=False` now, before it is `for_each_device=False`, and the master cupy version also is `for_each_device=False`, so I think maybe it is a typo bug?

**Comment by kmaehashi** [comment]
Could you please point the exact line of source you are talking about?
Both master branch and v2.4.0 uses `bint for_each_device=False`:
https://github.com/cupy/cupy/blame/master/cupy/util.pyx#L14
https://github.com/cupy/cupy/blame/v2.4.0/cupy/util.pyx#L14

**Comment by leftthomas** [comment]
@kmaehashi, 
<img width="762" alt="qq20180309-155459 2x" src="https://user-images.githubusercontent.com/9991443/37196628-7e720c20-23b2-11e8-8edb-6bcaddbdfcbf.png">

**Comment by kmaehashi** [comment]
It seems that you're referring to the source file decompiled by PyCharm.

**Comment by kmaehashi** [comment]
If you have any further issues please reopen another case. Thanks!
