### ISSUE TITLE
array.cuh(138): error: no suitable constructor exists to convert from "float" to "__half"

### ISSUE THREAD

**Issue by maxisme** [cupy/cupy#1010]
I am trying to run `.dot()` on two arrays:
```
X = cp.array([[0,0], [0,1], [1,0], [1,1]])
w = cp.zeros(len(X[0]))
print cp.dot(X[0], w)
```
But I am getting the errors:

> /usr/local/lib/python2.7/dist-packages/cupy-4.0.0b4-py2.7-linux-x86_64.egg/cupy/linalg/product.pyc in dot(a, b, out)
>      32     """
>      33     # TODO(okuta): check type
> ---> 34     return a.dot(b, out)
>      35 
>      36 
> 
> cupy/core/core.pyx in cupy.core.core.ndarray.dot()
> 
> cupy/core/core.pyx in cupy.core.core.dot()
> 
> cupy/core/core.pyx in cupy.core.core.tensordot_core()
> 
> cupy/core/reduction.pxi in cupy.core.core.ReductionKernel.__call__()
> 
> cupy/util.pyx in cupy.util.memoize.decorator.ret()
> 
> cupy/core/reduction.pxi in cupy.core.core._get_reduction_kernel()
> 
> cupy/core/reduction.pxi in cupy.core.core._get_simple_reduction_kernel()
> 
> cupy/core/carray.pxi in cupy.core.core.compile_with_cache()
> 
> /usr/local/lib/python2.7/dist-packages/cupy-4.0.0b4-py2.7-linux-x86_64.egg/cupy/cuda/compiler.pyc in compile_with_cache(source, options, arch, cache_dir, extra_source)
>     150                 return mod
>     151 
> --> 152     ptx = compile_using_nvrtc(source, options, arch)
>     153     ls = function.LinkState()
>     154     ls.add_ptr_data(ptx, six.u('cupy.ptx'))
> 
> /usr/local/lib/python2.7/dist-packages/cupy-4.0.0b4-py2.7-linux-x86_64.egg/cupy/cuda/compiler.pyc in compile_using_nvrtc(source, options, arch)
>      68         prog = _NVRTCProgram(source, cu_path)
>      69         try:
> ---> 70             ptx = prog.compile(options)
>      71         except CompileException as e:
>      72             dump = _get_bool_env_variable(
> 
> /usr/local/lib/python2.7/dist-packages/cupy-4.0.0b4-py2.7-linux-x86_64.egg/cupy/cuda/compiler.pyc in compile(self, options)
>     231         except nvrtc.NVRTCError:
>     232             log = nvrtc.getProgramLog(self.ptr)
> --> 233             raise CompileException(log, self.src, self.name, options)
>     234 
>     235 
> 
> CompileException: /usr/local/lib/python2.7/dist-packages/cupy-4.0.0b4-py2.7-linux-x86_64.egg/cupy/core/include/cupy/carray.cuh(138): error: no suitable constructor exists to convert from "float" to "__half"

If I change to numpy everything works fine.

**Comment by kmaehashi** [comment]
What CUDA version are you using?
Could you please try using wheels to install CuPy?
https://docs-cupy.chainer.org/en/latest/install.html#install-cupy-using-wheel

**Comment by ykim104** [comment]
I am using CUDA9.0 and installed cupy with the wheel for my version of Cuda. I still get same error.

**Comment by kmaehashi** [comment]
I guess you have both CUDA 8.0 & 9.0 on your host and CUDA 8.0 is recognized at runtime.
Could you try setting `CUDA_PATH` environment variable? (e.g., `export CUDA_PATH=/usr/local/cuda-9.0`)

**Comment by maxisme** [comment]
Fixed. Thank you!
