### ISSUE TITLE
chainer.cuda.get_array_module get wrong gpu device cupy?

### ISSUE THREAD

**Issue by sharpstill** [cupy/cupy#1018]
I have 4 gpu in my machine, the following code justify my guess.
```
imgs.data.device
Out[43]: <CUDA Device 0>
cp = cuda.get_array_module(imgs.data)
xgpu= cp.array([1, 2, 3, 4, 5])
xgpu.data.device
Out[46]: <CUDA Device 2>

```

why imgs and xgpu are reside in two different gpu?

**Comment by kmaehashi** [comment]
Please see the document: https://docs-cupy.chainer.org/en/stable/tutorial/basic.html?highlight=Device#current-device
I'd suggest using StackOverflow instead of GitHub issues for general questions.
