### ISSUE TITLE
pip install error on ubuntu16.04

### ISSUE THREAD

**Issue by Lukeisme** [cupy/cupy#102]
I'm using pip to install this. but there is an error.

> Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-raeuoelt/cupy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yl91qc3r-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-raeuoelt/cupy/

Traceback
> Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/local/lib/python3.5/dist-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))

**Comment by sonots** [comment]
Did you see a message like:

```
    building 'cupy.cuda.thrust' extension
    error: unknown file type '.cu' (from 'cupy/cuda/cupy_thrust.cu')
```

just above the message you pasted?

Then, the problem is currently being worked to be fixed at https://github.com/cupy/cupy/pull/91.

**Comment by sonots** [comment]
A work around is to set PATH to nvcc command such as:

```
export PATH="/usr/local/cuda/bin:$PATH"
```

(cuda path depends on your environment)

**Comment by Lukeisme** [comment]
oh.It is because I using sudo with pip.  on the official site it said

> sudo CUDA_PATH=/opt/nvidia/cuda pip install cupy

but it is not working.thanks for you reply I try 

> sudo CUDA_PATH=/opt/nvidia/cuda PATH="/usr/local/cuda/bin:$PATH"  pip install cupy 

and it works.
