### ISSUE TITLE
You are running using the stub version of nvrtc error during runtime

### ISSUE THREAD

**Issue by IoDmitri** [cupy/cupy#1034]
The following code produces the following error:
```
>>> import cupy as cp
>>> z = cp.array([1,2,3,4])
>>> x = cp.array([2,3,4,5])
>>> x.dot(z)
```

For the full install log and generated messages, checkout the attached text file. 
[cupy_install.txt](https://github.com/cupy/cupy/files/1813285/cupy_install.txt)

**Comment by kmaehashi** [comment]
You have a strange CUDA setup.

```
    **************************************************
    *** WARNING: nvcc path != CUDA_PATH
    *** WARNING: nvcc path: /usr/local/cuda
    *** WARNING: CUDA_PATH: /usr/local/cuda-8.0
    **************************************************
```

I'd recommend using wheels instead of installing CuPy from source. https://docs-cupy.chainer.org/en/latest/install.html#install-cupy-using-wheel

**Comment by kmaehashi** [comment]
Feel free to reopen if you still have any issues. Thanks!
