### ISSUE TITLE
Some dtypes are not exported

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#1043]
NumPy has `numpy.intp`, `numpy.bool`, etc., whereas CuPy does not.
I think we should expose everything we support, as it is better to be a "drop-in replacement".

**Comment by niboshi** [comment]
FYI: https://github.com/numpy/numpy/blob/b7a2b6917a78f12c7bf8f816c234b81d7b46cd8e/numpy/__init__.py#L175
It seems they import built-in types intentionally, not by accident.
