### ISSUE TITLE
FFT function raises CuFftError: CUFFT_ALLOC_FAILED

### ISSUE THREAD

**Issue by not522** [cupy/cupy#1063]
The following code raises CuFftError, but GPU memory seems to be enough to run.
If I eliminate lines about `b`, it works correctly.
I use GTX 1080Ti; the size of arrays to reproduce the error may depend on the environment.
```
import cupy
a = cupy.arange(100000007, dtype=cupy.float32)
b = cupy.empty(2000000000, dtype=cupy.float32)
del b
cupy.fft.fft(a)
```
```
Exception ignored in: <bound method Plan1d.__del__ of <cupy.cuda.cufft.Plan1d object at 0x7fd030b0ec88>>
Traceback (most recent call last):
  File "cupy/cuda/cufft.pyx", line 101, in cupy.cuda.cufft.Plan1d.__del__
AttributeError: 'Plan1d' object has no attribute 'plan'
Traceback (most recent call last):
  File "bug.py", line 6, in <module>
    cupy.fft.fft(a)
  File "/home/not/cupy/cupy/fft/fft.py", line 155, in fft
    return _fft(a, (n,), (axis,), norm, cupy.cuda.cufft.CUFFT_FORWARD)
  File "/home/not/cupy/cupy/fft/fft.py", line 122, in _fft
    a = _fft_c2c(a, direction, norm, axes)
  File "/home/not/cupy/cupy/fft/fft.py", line 94, in _fft_c2c
    a = _exec_fft(a, direction, 'C2C', norm, axis)
  File "/home/not/cupy/cupy/fft/fft.py", line 73, in _exec_fft
    fft_type, a.size // a.shape[-1])
  File "cupy/cuda/cufft.pyx", line 90, in cupy.cuda.cufft.Plan1d.__init__
  File "cupy/cuda/cufft.pyx", line 73, in cupy.cuda.cufft.check_result
cupy.cuda.cufft.CuFftError: CUFFT_ALLOC_FAILED
```
I suspect `cufftMakePlan1d` allocates memory even if `cufftSetAutoAllocation` sets `false`.
The combination of the behavior and CuPy's memory pool may raise the reported error.
https://github.com/cupy/cupy/blob/846ba7983fa614080d12800af2e744981c29fba7/cupy/cuda/cufft.pyx#L77-L98

**Comment by kmaehashi** [comment]
Thanks for the report. I confirmed this error in my local environment too. (CUDA 9.0 / GeForce GTX TITAN X)

**Comment by kmaehashi** [comment]
@anaruse Is it possible to fully control memory allocation of `cufftMakePlan1d` when `cufftSetAutoAllocation(plan, 0)` is set? (this question is not urgent)

**Comment by kmaehashi** [comment]
FYI, such errors may occur also with other libraries like cuDNN.
For example `cupy.cuda.cudnn.create()` allocates approx. 80 MiB of out-of-mempool memory.

TensorFlow's memory pool uses heuristics to avoid such error by leaving 225 MiB unmanaged from memory pool. https://github.com/tensorflow/tensorflow/blob/v1.7.0/tensorflow/core/common_runtime/gpu/gpu_device.cc#L744-L777

**Comment by not522** [comment]
I note that the TensorFlow's heuristics cannot resolve this issue.
If input array size has large divisor, out-of-mempool memory can be huge.
In the following case, it is over 1500MiB.
https://gist.github.com/not522/6782112e94749d16353c4d9ec1a8b8ec

**Comment by kmaehashi** [comment]
Workaround added via #1219
