### ISSUE TITLE
Problem with CUDA 7.5?

### ISSUE THREAD

**Issue by edoRemelli** [cupy/cupy#1068]
The following minimal code doesn't work even if cupy installation seems to be fine

`
import cupy as cp
x_gpu = cp.array([1, 2, 3])
l2_gpu = cp.linalg.norm(x_gpu)
`
Error message:

> CompileException: nvrtc: error: invalid value for --gpu-architecture (-arch)

Note that I can successfully initialize the array on GPU, i.e. the code runs fine if I remove cp.linalg.norm.

Running the code on a  TITAN X (Pascal) GPU,
here is the output of `nvcc --version`

`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
`

Thank you in advance!

**Comment by kmaehashi** [comment]
Thank you for the report.
This issue is planned to be fixed in the next release. https://github.com/cupy/cupy/pull/1055
(Or, upgrading to CUDA 9.0 can also solve the issue)

**Comment by kmaehashi** [comment]
This issue has been fixed via #1055
