### ISSUE TITLE
Masking kernel dispatch latency?

### ISSUE THREAD

**Issue by brandondube** [cupy/cupy#1072]
Hello,

I would like to convert some numpy models to cupy models.  They use many tight operations, e.g. taking sin(x) on an array `128x128` of doubles.  The entire computation adds up to about 10ms on CPU.  On GPU, the latency of adding a kernel to the current warp (~20us) seems to be the source of my GPU version running in about 7ms.  If I increase my array size to, say, 512x512 the GPU can do the task in the same time as the CPU at 128x128, but I do not need this size.

Is it possible for cupy to more quickly dispatch kernels to the GPU, or fuse kernels?  If I do, e.g.
```
import numpy as np
import cupy as cu
from cupy.fft import fft2, ifftshift, fftshift

x = cu.linspace(-1, 1,128)
y = cu.linspace(-1, 1,128)
xx, yy = cu.meshgrid(x, y)
rho, phi = cu.sqrt(xx**2 + yy**2), cu.arctan2(yy, xx)

# repeat below here many many times
phase = cu.sin(phi) * rho ** 2
complex = cu.exp(1j * 2 * np.pi * phase)
prop = fftshift(fft2(ifftshift(complex)))
out = abs(prop) ** 2
```
The constituents of `phase` will be found by an optimizer, and this ensemble of kernels will be used a great many times.  To the best of my knowledge, the constituents of `phase` and the operation to create `complex` are all elementwise, so they can be fused.  The abs**2 for out can also be fused, but my use of a builtin instead of cu.abs here may prevent that.

Can cupy do these sort of things?  Or would I have to write native cuda code and hope nvcc can fuse these?

**Comment by brandondube** [comment]
Hey, thanks for the response!

Are fused functions composable?  In my own code [here](https://github.com/brandondube/prysm/blob/master/prysm/fringezernike.py#L71) I would like to fuse each function Z0..Z47, which are an orthogonal basis set.  Then I would like to fuse the dispatch that creates a sum of them.

Is complex support planned for the future, or is there too substantial a difficulty (I'm guessing cuda stores complex numbers in pairs, which makes the iteration incompatible with regular kernels?)

I use mostly 128x128 arrays, which for a large number of kernels is slower on CUDA than a decent CPU.  When for some projects I need 512 or 1024, CUDA would be much faster than the CPU.  Ideally I would like to get kernel dispatches to a low enough level where CUDA at least has parity speed-wise with the CPU.  Kernel fusion (and reduced kernel launch time!) would go a long way to helping this -- 24 to 15 kernels and a further 2x speedup would improve performance by ~3x for the CUDA implementation.

**Comment by kmaehashi** [comment]
> Are fused functions composable? In my own code here I would like to fuse each function Z0..Z47, which are an orthogonal basis set. Then I would like to fuse the dispatch that creates a sum of them.

Yes, you can compose functions inside a function decorated by `cupy.fuse`.

> Is complex support planned for the future, or is there too substantial a difficulty (I'm guessing cuda stores complex numbers in pairs, which makes the iteration incompatible with regular kernels?)

#1090 implements a feature to use of complex constants numbers in fusion function arguments, so I think it's not that difficult, if I don't miss something 😅

> I use mostly 128x128 arrays, which for a large number of kernels is slower on CUDA than a decent CPU. When for some projects I need 512 or 1024, CUDA would be much faster than the CPU. Ideally I would like to get kernel dispatches to a low enough level where CUDA at least has parity speed-wise with the CPU. Kernel fusion (and reduced kernel launch time!) would go a long way to helping this -- 24 to 15 kernels and a further 2x speedup would improve performance by ~3x for the CUDA implementation.

Please note that times in the above comment only displays a time taken for kernel launch API (does not include actual computation or other API calls).

> Out of curiosity, what are the 3 numbers from nvprof? Average kernel launch time, min kernel launch time, and max kernel launch time?

Yes.

**Comment by brandondube** [comment]
Cool, thanks!

**Comment by kmaehashi** [comment]
> e: to be clear, you mean that I can use one cp.fuse'd function inside another?

Ah, sorry I thought fused functions are composable but were not. I raised another issue for this topic. #1093
So far, maybe you'll need something like this and use `_Z0` from inside other fused functions:

```py
def _Z0(x, y):
    return x ** 2 + y
Z0 = cupy.fuse(_Z0)
```
