### ISSUE TITLE
cupy.asarray and numpy.asarray are not compatible when inputing list of array.

### ISSUE THREAD

**Issue by keisuke-umezawa** [cupy/cupy#1084]
```
import numpy as np
_x = [np.ones(10)]
print(_x)
_x = np.asarray(_x)
print(_x)
```

```
import cupy as cp
_x = [cp.ones(10)]
print(_x)
_x = cp.asarray(_x)
print(_x)

```
 The above codes results differently.

cupy version : cupy-4.0.0b3

<img width="836" alt="2018-04-03 21 51 40" src="https://user-images.githubusercontent.com/1277089/38250393-a01fd92a-3789-11e8-80f0-448df6605aa5.png">

**Comment by kmaehashi** [comment]
Thanks. This is currently by design but I'm planning to support this feature in #1030.

**Comment by keisuke-umezawa** [comment]
Thanks! I will wait for the pr.

**Comment by keisuke-umezawa** [comment]
it will be duplicated with #409. I closed this issue.
