### ISSUE TITLE
Issues on calling real/imag on non-complex array

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#1088]
Supporse `a` a non-complex `cupy.ndarray`.

As for `a.imag`:
* Currently it does not keep contiguity of the original array.
* Currently it returns a new writable array. It is better to document this behavior.
  (This is because it's difficult to mimic numpy's WRITEABLE flag with CUDA)

As for `cupy.real(a)`:
* It currently returns copy of `a`, but it should not.

```py
>>> x = np.ones(10)
>>> np.real(x) is x
True
>>> x = cp.ones(10)
>>> cp.real(x) is x
False
```

**Comment by okuta** [comment]
@kmaehashi Cloud you check #1504.

**Comment by okuta** [comment]
This PR has already been resolved.
