### ISSUE TITLE
How to calculate the gradient with Cupy?

### ISSUE THREAD

**Issue by Rabbey** [cupy/cupy#1099]
I'm rewriting a program which uses numpy originally, and I failed to find the gradient function in cupy.  Anyone knows how to calculate the gradient with Cupy?

**Comment by kmaehashi** [comment]
autograd is moving to support CuPy (but AFAIK it's not working for now).
https://github.com/HIPS/autograd/issues/353

**Comment by ericmjl** [comment]
@kmaehashi mostly correct! I have gotten first order derivatives working, but 2nd and higher order derivatives are not working at the moment. One limitation appears to be that CuPy doesn't convert array-like to CuPy arrays, so I'm trying to think of a workaround. 

I've contacted Autograd's creator, but I'd also love to hear ideas about how to get around this!

**Comment by ericmjl** [comment]
@kmaehashi more progress! Please see issue HIPS/autograd#353 :smile:

**Comment by kmaehashi** [comment]
Thanks for sharing the progress! I've subscribed that issue.

> One limitation appears to be that CuPy doesn't convert array-like to CuPy arrays, so I'm trying to think of a workaround.

You may have interest in #1030, which is my proposal of fixing `cupy.array` and `cupy.asarray` to accept (possibly nested) list/tuple of `cupy.ndarray`s and return a single contiguous `cupy.ndarray`. Note that this operations performs memory copy on GPU.

**Comment by ericmjl** [comment]
Having that feature would be awesome from a user-facing perspective! Thank you for alerting me to this. :smile:
