### ISSUE TITLE
Check if the argument contains numpy.ndarray

### ISSUE THREAD

**Issue by okuta** [cupy/cupy#1128]
Some functions accept `numpy.ndarray`. But, it is not correct behavior. I think that it is better to raise an exception for usability.

**Comment by kmaehashi** [comment]
https://github.com/cupy/cupy/pull/1124#issuecomment-384679098
> We decided that CuPy functions accepts array like object to improve compatibility with NumPy.

**Comment by okuta** [comment]
Yes you are right.
