### ISSUE TITLE
Traversal of 2D, 3D, ND arrays, and declaring/available functions within kernel

### ISSUE THREAD

**Issue by DTasev** [cupy/cupy#113]
Hi! I have been looking into this package and trying to implement simple image processing filters, like median filter, by writing the kernel for it. This is a test function for looping over the 2D array, it's not fully implemented median filter (the kernel parameter is ignored):
```
import cupy as cp
def loop2d(data, kernel=3):
    """
    This should be doing a row-major traversal.
    The data is broadcast into a 1D array when transferred to the device.
    """
    # allocate memory for the output parameter
    data_out = cp.zeros(data.shape, dtype=data.dtype)
    f = cp.ElementwiseKernel(
        in_params='raw T in, int32 width, int32 kernel, int32 kernel_width',
        out_params='raw T out',
        preamble=r"""
        #include <stdio.h> // for debug
        """,
        operation=r"""
        printf("index: %d\n", i);
        for(int j = 0; j < width; ++j){
            int pos = i * width + j;
            printf("value at %d: %d\n", pos, in[pos]);
            out[pos] = in[pos] + 3; // apply some operation
        }
        """,
        name='loop2d',
        options=('-std=c++11',),
        reduce_dims=False
    )
    if kernel <= 1:
        return data

    kernel_width = (kernel - 1) / 2
    # this is for the outer for loop, looping over the rows
    data_height = data.shape[1]
    # this is for the inner loop, looping over the columns
    data_width = data.shape[0]
    # we pass in data_out as the output parameter
    return f(data, data_width, kernel, kernel_width, data_out, size=data_height)

some_data = cp.full((10,10), 1, dtype=cp.int32)
loop2d(some_data)
```
I feel this is abusing the ElementwiseKernel, because it's operating row-wise, not element wise.

- I am curious to know if my traversal approach is correct? Is there another way to traverse a 2D array, without manually calculating the current position after being broadcast?  
  - Do you have any examples in the source code of having to do this?
  - Something else to consider - I will be looking to extend this to a 3D array traversal/processing.

- How can I find what functions I can use within the CUDA kernel declaration? I have been looking around random files in the source code that use kernels, and functions like `atomicAdd` that have been used in some of them can only be found within the source files. 

- Expanding on the previous Is there a way to define our own functions? A hack that works is to define the function within the `preamble='void myfunc(){};'`, but maybe there's a way to add it into cupy in a different way

Thank you very much for your time! I am very impressed with the work that you all have done on this package, so I can only say, keep up the good work!

**Comment by yuyu2172** [comment]
I will answer to some of your questions.

> I am curious to know if my traversal approach is correct? 

I briefly looked at your code, and `pos = i * width + j` looks fine.

> Is there another way to traverse a 2D array, without manually calculating the current position after being broadcast?

Basically, `ElemenwiseKernel` calls `cupy.cuda.Function.linear_launch` inside (https://github.com/cupy/cupy/blob/master/cupy/cuda/function.pyx#L134).
If you want to use CUDA's 2D or 3D block/grid configuration, you need to call`cupy.cuda.Function.__call__`.
To give you an example, here is a code where I used this functionality from CuPy when I wrote a kernel for non-maximum suppression of bounding boxes.
https://github.com/chainer/chainercv/blob/master/chainercv/utils/bbox/non_maximum_suppression.py#L124

By the way, I am not sure if this is the recommended style of writing kernels, so I would like to hear back from core dev team.

**Comment by yuyu2172** [comment]
I wrote a SGEMM example. It might be helpful to you.
https://github.com/cupy/cupy/pull/114

**Comment by DTasev** [comment]
I think you PR answers all of the questions I had, so I'll go ahead and close the issue. Thank you very much!
