### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by yangshao** [cupy/cupy#1147]
when i try to run cupy on an object detection model,  i come across this error:
from collections import namedtuple
faster_rcnn = FasterRCNNVGG16()
File "/home/yangshao/workspace/faster_rcnn/model/faster_rcnn_vgg16.py", line 51, in init
head = VGG16RoIHead(n_class=n_fg_class+1,roi_size=7, spatial_scale=1./self.feat_stride, classifier=classifier)
File "/home/yangshao/workspace/faster_rcnn/model/faster_rcnn_vgg16.py", line 29, in init
self.roi = RoIPooling2D(self.roi_size, self.roi_size, self.spatial_scale)
File "/home/yangshao/workspace/faster_rcnn/model/roi_module.py", line 86, in init
self.RoI = RoI(outh, outw, spatial_scale)
File "/home/yangshao/workspace/faster_rcnn/model/roi_module.py", line 35, in init
self.forward_fn = load_kernel('roi_forward', kernel_forward)
File "cupy/util.pyx", line 34, in cupy.util.memoize.decorator.ret
File "cupy/cuda/device.pyx", line 19, in cupy.cuda.device.get_device_id
File "cupy/cuda/runtime.pyx", line 164, in cupy.cuda.runtime.getDevice
File "cupy/cuda/runtime.pyx", line 136, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorNoDevice: no CUDA-capable device is detected

I installed cupy with command:
pip install cupy-cuda80

Is there anything wrong? Thanks!.

Best,
Shaohua Yang

**Comment by yangshao** [comment]
Just to add more information: i use ubuntu 14.04, cuda8.0, and i can run pytorch using gpu on other programs.

**Comment by OswinGuai** [comment]
@yangshao  Have solved this? I encountered the same problem.

**Comment by kmaehashi** [comment]
Could you paste the output of `cupy.show_config()`?

**Comment by OswinGuai** [comment]
<img width="313" alt="2018-05-26 2 36 32" src="https://user-images.githubusercontent.com/7878475/40573319-588fbc00-60f2-11e8-9ae2-847f90313f32.png">
Thanks!

**Comment by OswinGuai** [comment]
I tried cuda-8.0 and cuda-9.0. Both failed. Also tried cupy and cupy-cuda80 and cupy-cuda90. None of these works. T_T. 

Any help for this? @kmaehashi

**Comment by kmaehashi** [comment]
Hmm, the version seems OK. I guess this is an issue of CUDA on your system rather than a bug in  CuPy. The general advices I come up with are:

* Confirm `CUDA_VISIBLE_DEVICES` environment variable (OK if not set)
* Confirm `LD_LIBRARY_PATH` environment variable and `ldconfig -p` to check correct CUDA library is used
* Check output of `nvidia-smi`, `deviceQuery`, `dmesg` for errors
* Try other program that uses CUDA and see what happens
* Try reinstalling CUDA and reboot

**Comment by OswinGuai** [comment]
@kmaehashi Thank you for so many details. I finally found there is a param of gpu whose default value is setted as empty string. This fooled me more than one day. Really appreciate your attention.

**Comment by say2sarwar** [comment]
> @kmaehashi Thank you for so many details. I finally found there is a param of gpu whose default value is setted as empty string. This fooled me more than one day. Really appreciate your attention.

How did you solve this issue? i am facing the same issue. can you please post your solution.

**Comment by OswinGuai** [comment]
@say2sarwar My problem may be not your case. It was the unset parameter like gpu_id='', an empty string. So no device could be found.
