### ISSUE TITLE
Wrong indexing when using large sparse matrices

### ISSUE THREAD

**Issue by eduardovera** [cupy/cupy#1175]
Hi,

I've found an indexing problem when dealing with a large sparse matrix. The fact is, when initializing a coo_matrix, in `cupy/cupy/sparse/coo.py`, the indices are converted to a 32-bit integer array. I'm not sure if this avoids some problem but why not assert the type is a any bit-sized integer?

Lines 118-119 enforces 32-bit integer array cast:

`row = row.astype('i', copy=copy)`
`col = col.astype('i', copy=copy)`

**Comment by kmaehashi** [comment]
Closing as the discussion is ongoing in #3513.
