### ISSUE TITLE
On Windows, cupy.fft not found

### ISSUE THREAD

**Issue by richhend** [cupy/cupy#1185]
On Windows, I'm getting the error that cupy.fft cannot be found. 
Otherwise, cupy seems to work fine.

Using the following:
- Windows 10, 64 bit
- Anaconda Python, Python version 3.6.3
- CUDA toolkit 9.1.85 (and the patches 9.1.85.1, 9.1.85.2, 9.1.85.3)
- Microsoft Visual Studio 14.0
- Installed CuPy prebuilt binary from https://www.lfd.uci.edu/~gohlke/pythonlibs : 
cupy‑2.5.0+cuda9185‑cp36‑cp36m‑win_amd64.whl
with 
pip install cupy‑2.5.0+cuda9185‑cp36‑cp36m‑win_amd64.whl

**Comment by kmaehashi** [comment]
That unofficial binary seems CuPy v2.5.
FFT is a new feature added in CuPy v4.0.

**Comment by richhend** [comment]
Ah, I see. Thank you very much for letting me know!
Do you happen to know whether there are Windows binaries for newer CuPy versions available somewhere?
