### ISSUE TITLE
runtime interoperability of cupy and numpy without explicit cupy dependency?

### ISSUE THREAD

**Issue by brandondube** [cupy/cupy#1190]
Hello,

I maintain a scientific package that does a significant amount of numerical work.  I allow an optional dependency of numba to fuse CPU kernels and achieve very good performance on CPUs.  I would also like to develop GPU support via cupy.  The idea would be that if a user has just numpy, numpy will be used.  If they have numba, then they will get "numpy+" with better CPU performance.  If they have cupy installed and call something like `config.set_backend('cuda')`, then cupy would be used, and they can flip between CPU (via numpy+numba) and GPU (via cupy) at a whim.

I have a submodule/file that re-exports common functions (sin, cos, fft, etc) from numpy and import from this throughout my package.  It seems that a variable of type `function` has pass by value semantics when it comes to imports / is immutable.

For example, a test;
```python
# test_a.py
def _foo():
    print('foo')
    global testd
    testd['bar'] = 'foo'

def _bar():
    print('bar')

def chfoo():
    global foo
    foo = _bar

foo = _foo
testd = {'foo': 'bar'}
```
```python
#test_b.py
from test_a import foo, chfoo, testd

print(testd)
foo()
print(testd)
chfoo()
foo()
```
```
>>> python test_b.py
>>> {'foo': 'bar'}
>>> foo
>>> {'foo': 'bar', 'bar': 'foo'}
>>> foo
```
So this shows that:
1.  mutable types like dicts can be mutated after import, which allows things like shared config
2.  immutable types like functions cannot be reassigned after import

My prior usage of:
```python
# somewhere in my code
from .mathops import sin, cos, exp, pi

# do something with sin(x)
```

Could change to
```python
# somewhere in my code
from .mathops import mth

# do something with mth['sin'](x)
```

But most editors cannot follow this sort of thing to find docstrings and autocompletes, and the syntax is clunky.  I could use a class instead of a dict and have dot syntax, but this feels a bit like a hack.  I could also write out something like:
```python
import numpy as np
import cupy as cp

npmath = {}
cpmath = {}

npmath['sin'] = np.sin
cpmath['sin'] = cp.sin

def sin():  # missing some bits, but hopefully the idea communicates
    if config.backend == 'cuda':
        return cumath['sin']()
    else:
        return npmath['sin']()
```

But this will incur an extra logical comparison cost at runtime, and also involve an immense amount of boilerplate and care to match arguments (and possibly gloss over small API differences between cupy and numpy).

(how) does cupy handle this?

**Comment by brandondube** [comment]
Update, it seems that there is a slightly non preferred way:

```python
#test_a.py

def _foo():
    print('foo')

def _bar():
    print('bar')

def chfoo():
    global foo
    foo = _bar

foo = _foo
```

```python
# test_b.py
import test_a as a
a.foo()
a.chfoo()
a.foo()
```
prints "foo" and then "bar" as desired.

So I have to spend two characters and a little clarity with a bunch of, say, `m.sin()` calls instead of `sin()`.  Perhaps there is a hacky way to overcome this with monkey patching?

**Comment by kmaehashi** [comment]
Thanks for considering use of CuPy in your package.
I think you can do that like this:

```py
import numpy

try:
    import cupy
except ImportError:
    cupy = None

def get_xp(use_cupy_if_available=True):
    if use_cupy_if_available and cupy is not None:
        return cupy
    return numpy
```

Then you can use `get_xp()` (it may return `numpy` or `cupy` module) in other places:

```py
xp = get_xp()
xp.sin(...)
```
