### ISSUE TITLE
scipy.optimize

### ISSUE THREAD

**Issue by robotsorcerer** [cupy/cupy#1196]
Hi Guys,

Thanks for your great work.

Do you support  scipy optimizers such as lbfgs, linprog etc out of the box?

When I pass cupy arrays to default scipy optimizers, internally, scipy attempts to convert them to numpy arrays first. Are there plans to inmtegrate the scipy optyimizers to cupy in the near future?

**Comment by brandondube** [comment]
some optimizers, particularly L-BFGS-B from scipy, are written in C or Fortran, which makes them a pain for cupy to support.

If you want to do cuda-accelerated optimization, you should probably use the authors' other package, Chainer, which is built for machine learning and neural nets, but has an L-BFGS-B optimizer that I believe is cuda compatible (I have never used it).

**Comment by lakehanne** [comment]
Thanks for the clarification and pointer!

**Comment by kmaehashi** [comment]
Discussions continue in #6112.
