### ISSUE TITLE
"Upgrading setuptools" should be much more emphasized

### ISSUE THREAD

**Issue by soramichi** [cupy/cupy#120]
The current README asks to upgrade `setuptools` **if the user uses an old one**, but I would say this statement is too weak. Lazy users may (I mean, users are always lazy) just give a glance to this sentence and ignore it.

I guess a large portion of installation errors reported in Chainer v1 repository that say "cupy is not correctly installed" are due to an old `setuptools`.

I suggest to make the sentence much more strong, such as "You **MUST** upgrade setuptools before installing cupy", or maybe add a FAQ section (or a page?) to tell people that the very first thing to try after an installation failure is to upgrade it.

**Comment by kmaehashi** [comment]
Documented in https://docs.cupy.dev/en/latest/install.html
