### ISSUE TITLE
Could you provide cupy windows package

### ISSUE THREAD

**Issue by PaulaQin** [cupy/cupy#1221]
Hi, I am a cupy (and chainer) user, and I want to install cupy on my windows machine. So could you provide a windows version of cupy 4.0.0 package on PyPI?

Besides, could it run on Numpy 1.14.2 or 1.14.3 since the latest version of numpy is 1.1.4.3?

Thanks for your help!

**Comment by kmaehashi** [comment]
Thanks, we're currently preparing a wheel for Windows.

**Comment by kmaehashi** [comment]
We started to provide windows wheels in v5.0.0b1.
