### ISSUE TITLE
Add __array_ufunc__ protocol

### ISSUE THREAD

**Issue by mrocklin** [cupy/cupy#1230]
The Numpy [`__array_ufunc__`](https://docs.scipy.org/doc/numpy/reference/arrays.classes.html#numpy.class.__array_ufunc__) protocol allows projects to use many of the Numpy functions to drive their own data structures.  Here is a small example with [dask.array](http://dask.pydata.org/en/latest/array.html).

```python
In [1]: import dask.array as da

In [2]: x = da.arange(100, chunks=(10,))

In [3]: x
Out[3]: dask.array<arange, shape=(100,), dtype=int64, chunksize=(10,)>

In [4]: import numpy as np

In [5]: np.exp(x)  # note that this returns a dask array
Out[5]: dask.array<exp, shape=(100,), dtype=float64, chunksize=(10,)>

In [6]: np.sum(np.exp(x))
Out[6]: dask.array<sum-aggregate, shape=(), dtype=float64, chunksize=()>

In [7]: _.compute()
Out[7]: 1.5644215618731406e+43
```

This provides a protocol for downstream projects to write code that works independently of the choice of ndarray data structures, at least for a subset of the NumPy API.  The Numpy core team seems dedicated to increasing this subset in the near future.

It would be useful for CuPy to also implement this protocol to improve interoperation with the rest of the ecosystem.

**Comment by mrocklin** [comment]
Some examples of `__array_ufunc__` implementations

https://github.com/pydata/sparse/blob/3afd0e0e4ca609711c9e3586e4ad058e782f6368/sparse/coo/core.py#L1036-L1057

https://github.com/dask/dask/blob/7c419580037f552befc2650cb13967dd6bdef86a/dask/array/core.py#L1120-L1146

**Comment by mrocklin** [comment]
@ericmjl has a first early attempt at this here: https://github.com/ericmjl/cupy/commit/83ffb8a08dced98d8e3d0c25869a87e632b5c6fc

**Comment by ericmjl** [comment]
With thanks to @mrocklin for showing me the ropes!
