### ISSUE TITLE
Provide method to return CUDA source from user-defined kernels

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#1243]
Sometimes I want to see CUDA source generated by user-defined kernels.
It should help users to understand how to write custom kernels, especially when `preamble`, `loop_prep`, etc. is involved.

**Comment by leofang** [comment]
I think to address this, this [nice comment](https://github.com/cupy/cupy/issues/2575#issuecomment-546969540) can be documented somewhere? (I know the env var `CUPY_CACHE_SAVE_CUDA_SOURCE` is already listed in the reference, but perhaps a short tutorial or something could offer a better guidance.)

**Comment by kmaehashi** [comment]
I think it's nice to document it in https://docs-cupy.chainer.org/en/latest/tutorial/kernel.html
