### ISSUE TITLE
Reduction functions unintentionally accept NumPy arrays

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#1245]
```
>>> cupy.sum(numpy.ones((3, 2), 'f'))
6.0
```

This code should fail.

I think this is the same problem as #147. It has been resolved (#151) by fixing elementwise functions, but it missed reduction functions.

**Comment by kmaehashi** [comment]
Related discussion: #1206

**Comment by okuta** [comment]
CuPy will accept NumPy arrays.
