### ISSUE TITLE
Recommended way to develop a cupy wrapper for an original cuda kernel

### ISSUE THREAD

**Issue by fiarabbit** [cupy/cupy#1258]
I'm a NN developer who want to transport a pytorch Module (https://github.com/jonas-koehler/s2cnn) to chainer. 

The original Module uses a homemade kernel, wrapped by `pynvrtc` and `cupy.cuda.function.Module.get_function()`.

In searching information for the transportation, I found a PR which refer not to use pynvrtc in cupy.
https://github.com/cupy/cupy/pull/33#issuecomment-301306224

My question is which is the better to use `pynvrtc` or `cupy.cuda.compiler` to create an original kernel used for chainer.

**Comment by kmaehashi** [comment]
I'd recommend not using `pynvrtc` as it is currently not maintained very well, and on Windows it only supports CUDA 8.0. (It may work with other version of CUDA on platforms other than Windows, though.)
You can use `cupy.cuda.compiler.compile_with_cache` to compile `Function` for your kernel.

**Comment by fiarabbit** [comment]
@kmaehashi 
Thanks for your fast and kind reply.Is there any (official) documentation to develop an original kernel w/o ElementwiseKernel nor ReduceKernel?

**Comment by kmaehashi** [comment]
Currently these low-level APIs are undocumented as it is intended for private use in CuPy.
However it is a simple API that you only need to pass the CUDA code. You can find some examples in: https://github.com/cupy/cupy/blob/v5.0.0a1/cupy/core/core.pyx#L4339-L4356
If you have multiple GPUs with different compute capability, make sure to run compilation for each device.

**Comment by fiarabbit** [comment]
Thank you very much for your kind response. I'll try to use them!

**Comment by fiarabbit** [comment]
Thank you very much! That was really I hoped!
