### ISSUE TITLE
make cupy fuse have compatible API with numba jit/vectorize

### ISSUE THREAD

**Issue by brandondube** [cupy/cupy#1264]
`numba`'s [`vectorize`](https://numba.pydata.org/numba-doc/dev/reference/jit-compilation.html#numba.vectorize) function can be used for a purpose very similar to cupy's `fuse` function.

I have an ensemble of functions I would like to "compile" with either `numba`'s `vectorize` or cupy's `fuse`.  As-is, I do not think I can do this programmatically without wrapping each of those functions with another, or using the `ast` and `dis` modules to rebuild and wrap them.

currently I believe the only possible usage is

```
import cupy as cp

@cp.fuse
def foo(x):
    return x + x + x
```

I would like to be able to do:

```
foo2 = cp.fuse(foo)
```
Can the definition of `fuse` be modified to include allow something like `cp.fuse(func=foo`)`?

**Comment by kmaehashi** [comment]
@asi1024 Can you take a look?

**Comment by niboshi** [comment]
Currently this notation is allowed in CuPy fusion.
```
foo2 = cp.fuse(foo)
```

But this kwargs notation is not.
```
foo2 = cp.fuse(func=foo)
```

Do you think the kwargs variant is important? It seems `numba.jit` does not support it either.

**Comment by niboshi** [comment]
By the way, you can write like this: `cp.fuse()(f=foo)`.

**Comment by brandondube** [comment]
hmm, I did try `foo2 = cp.fuse(foo)` at first and something went wrong, but trying it again just now with `master` as of yesterday and it behaves as expected.  Perhaps there was an issue in the version I tried on (either v4, or v5a a few weeks ago).  It could also be user error.

I will close the PR -- I do not think having a kwarg version offers substantial improvement.

**Comment by niboshi** [comment]
Thanks!
