### ISSUE TITLE
implement cupy.gradient

### ISSUE THREAD

**Issue by brandondube** [cupy/cupy#1270]
`gradient` computes n-dimensional derivatives, and is not related to autograd/autodiff - See [numpy gradient](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.gradient.html).

This function is used in a number of scientific codes and is (I believe) missing in cupy.

**Comment by TudorAndrei** [comment]
I will work on this feature.

**Comment by jakirkham** [comment]
That would be great! Thanks for working on this Tudor. 😄

**Comment by grlee77** [comment]
Hi @TudorAndrei.  I made a CuPy-based implementation of gradient if you want to start from that for your PR. It is basically just a simple 1:1 translation of the NumPy code.

The function is in:
https://github.com/mritools/cupyimg/blob/master/cupyimg/numpy/lib/function_base.py

The main work that needs to be done for inclusion in CuPy is making some tests in the CuPy style. I have existing tests copied from NumPy in:
https://github.com/mritools/cupyimg/blob/master/cupyimg/numpy/lib/tests/test_function_base.py

However, these are not in the typical style used by CuPy. More often CuPy tests are parameterized and involve direct comparisons between NumPy and CuPy outputs. I don't have immediate plans to do this conversion for `gradient` myself and would appreciate it if you are interested!
