### ISSUE TITLE
implement cupy.searchsorted

### ISSUE THREAD

**Issue by brandondube** [cupy/cupy#1274]
Another function in numpy but not in cupy.  Due to how GPU parallelism works, I do not know if there is a performant way to do this on a GPU.

**Comment by liwt31** [comment]
On a CPU this is done by a binary search which seems to be complicated to implement on a GPU. 
For this kind of functions, maybe dispatching to NumPy is an acceptable workaround?
Of course, the behavior should be well-documented.

**Comment by jpivarski** [comment]
This seems to have been implemented between CuPy 6.0.0 (which I have on one machine) and CuPy 7.7.0 (on another).

Here's when it was added: PR #2726. The earliest tag associated with this is v7.0.0. It's in the [release notes](https://github.com/cupy/cupy/releases/tag/v7.0.0).

I think you can close this issue.

**Comment by chenzhekl** [comment]
We still a lack proper entry in the documentation, though.

**Comment by leofang** [comment]
Thanks, @chenzhekl. Pushed a PR #3908 to add the missing doc. The doc preview can be found here: https://cupy--3908.org.readthedocs.build/en/3908/reference/generated/cupy.searchsorted.html.
