### ISSUE TITLE
ufuncs for complex

### ISSUE THREAD

**Issue by unnonouno** [cupy/cupy#1281]
Some ufuncs does not support complex types or behave differently compared with NumPy.
- [x] rint (#1282)
- [x] log1p, expm1, log2 (#1283)
- [ ] logaddexp
- [x] fmin, fmax (#1285)
- [x] sign, square (#1284)

**Comment by niteya-shah** [comment]
Hello, I would like to on work on logaddexp for complex numbers.

**Comment by toslunar** [comment]
See https://github.com/cupy/cupy/pull/3113#issuecomment-591779449.

`logaddexp` does not support complex numbers.
```
>>> import numpy as np
>>> np.__version__
'1.18.1'
>>> np.logaddexp.types
['ee->e', 'ff->f', 'dd->d', 'gg->g']
```
