### ISSUE TITLE
How can I time cupy function and compare against numpy?

### ISSUE THREAD

**Issue by yxchng** [cupy/cupy#1317]
How can I time cupy function and compare against numpy?

In PyTorch, there is a torch.cuda.synchronize() function to wait for all cuda functions to complete before printing time. Is there similar function for cupy so that I can time the function properly?

**Comment by brandondube** [comment]
You can just use `timeit` -- cupy will block as soon as the same variables (underling arrays on the GPU) are accessed, in which case it behaves like numpy vis-a-vis synchronicity.

**Comment by kmaehashi** [comment]
The equivalent in CuPy is `cupy.cuda.stream.get_current_stream().synchronize()`.
