### ISSUE TITLE
cp.array([cp.arange(3), 0]) => ValueError: Unsupported dtype object

### ISSUE THREAD

**Issue by zer0mem** [cupy/cupy#1336]
in numpy I am easy doing this transformations on object, however it is slow, I wanted to move it to cupy however I encounter this issue :

ranges, ids = cp.array([(cp.arange(3), i) for i in range(10)]).T

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\qilin\Anaconda3\lib\site-packages\cupy\creation\from_data.py", line 40, in array
    return core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy\core\core.pyx", line 2008, in cupy.core.core.array
  File "cupy\core\core.pyx", line 2039, in cupy.core.core.array
ValueError: Unsupported dtype object

underlying problem, cupy seems does not allow mixing dtypes : cp.array([cp.arange(3), 0]) 

in numpy case it will results in ( which I wanted behavior ) : 
>>> ranges, ids = np.array([(cp.arange(3), i) for i in range(10)]).T
>>> ids
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=object)
>>> ranges
array([array([0, 1, 2]), array([0, 1, 2]), array([0, 1, 2]),
       array([0, 1, 2]), array([0, 1, 2]), array([0, 1, 2]),
       array([0, 1, 2]), array([0, 1, 2]), array([0, 1, 2]),
       array([0, 1, 2])], dtype=object)

is some way to achieve it in cupy ? ~ as I mention in numpy it becomes very slow doing it on CPU :\

**Comment by CupyUser** [comment]
Hi! I Love your library and would like to thank you for all the hard work you're doing.

I'd like to piggy-back off of this issue to suggest the functionality that this should implement. The above problem is related to the following example:
```
x = cupy.array(3)
y = cupy.array(3)
z = cupy.array([x, y])
Traceback (most recent call last):
...
  File "cupy/core/core.pyx", line 2002, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2033, in cupy.core.core.array
ValueError: Unsupported dtype object
```

In `numpy`, the supported behaviour is
```
x1 = numpy.array(3)
y1 = numpy.array(3)
z1 = numpy.array([x1, y1])
print(z1)
array([3, 3])
```
which I think is the intuitive way to implement this functionality. Keep up the good work!

**Comment by kmaehashi** [comment]
Closing as this now works:
```py
x = cupy.array(3)
y = cupy.array(3)
z = cupy.array([x, y])
```

**Comment by Ssssssssophia** [comment]
> Closing as this now works:
> 
> ```python
> x = cupy.array(3)
> y = cupy.array(3)
> z = cupy.array([x, y])
> ```

Hi, I'm a beginner of cupy. I tried to use "cupy.array('here is a list')", but it didn't work. Is it because the version of my cupy or cuda is too low?

**Comment by kmaehashi** [comment]
Could you share your code? @Ssssssssophia
