### ISSUE TITLE
matrix power is missing from cupy.linalg.

### ISSUE THREAD

**Issue by ericmjl** [cupy/cupy#1358]
There is a corresponding `numpy.linalg.matrix_power` in NumPy. Is there a reason why this has not made it into CuPy?

If it helps, I am willing to take a shot at this one, though I might need a bit of hand-holding as I've not much experience with Cython code.

**Comment by kmaehashi** [comment]
Thanks, I believe there's no specific reasons not to add it. (maybe it can be done without Cython)
https://github.com/cupy/cupy/blob/v5.0.0b1/cupy/linalg/product.py#L197

Generally, contribution of implementing the corresponding method of `numpy`/`scipy` is always welcomed 😉

**Comment by ericmjl** [comment]
WOOHOO!! I have a first implementation available! Essentially just copied over the `numpy` implementation, and tweaked it so that it somewhat follows CuPy coding conventions. 

Going to PR in, but I am sure I am going to need guidance on tests to write!
