### ISSUE TITLE
Document behavior of memory pools

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#1394]
Context: https://github.com/chainer/chainer/issues/4911

**Comment by fiarabbit** [comment]
May I make it more clear? The problematized points in chainer/chainer#4911 is actually not a "leak" of memory (unreachable allocation of memory) but an expected behavior that cupy internally occupies unused memory to decrease re-occupying time loss. Is my understanding true?

**Comment by kmaehashi** [comment]
Yes. To mitigate the situation, we introduced a workaround to increase "cache-hit ratio" in #1372.

**Comment by kmaehashi** [comment]
Added via #1871
