### ISSUE TITLE
How to do sparse-dense matrix multiplication?

### ISSUE THREAD

**Issue by ericmjl** [cupy/cupy#1406]
Is it possible to do the following with CuPy?

```python
cp.dot(sparse, dense)
```

**Comment by kmaehashi** [comment]
I think it's not supported by NumPy nor CuPy.
https://docs.scipy.org/doc/scipy/reference/sparse.html#matrix-vector-product

**Comment by ericmjl** [comment]
I should have remembered; I [wrote my own blog post](http://www.ericmjl.com/blog/2016/7/24/sparse-matrix-multiplication-in-python-3/) about it to document that behavior.

Thank you for responding!
