### ISSUE TITLE
Implement 'reflect' mode for cupy.pad

### ISSUE THREAD

**Issue by mori97** [cupy/cupy#1409]
I am trying to implement a Cycle-GAN(https://arxiv.org/pdf/1703.10593.pdf) with chainer.
In the origin paper, the input is padded with reflection padding but I cannot implement it with reflection padding because cupy.pad does not have a 'reflect' mode that numpy.pad has.

**Comment by not522** [comment]
It's already implemented in v5.0.0a1. Please use pre-release version.
