### ISSUE TITLE
How to leverage memory of multiple GPUs (with NCCL) using unified memory

### ISSUE THREAD

**Issue by khcs** [cupy/cupy#1429]
Using `set_allocator(MemoryPool(malloc_managed).malloc)`, the "unified memory" seems to allocate/use CPU and (one) GPU memory, not memory of multiple GPUs available.

How can I use memory of multiple GPUs available on the system, possibly with NCCL?
I have tested on a system with four P100 GPUs.

My use-case is - I have large 3D arrays that don't fit into single GPU memory, and I'd like to do some operations (e.g., FFT/IFFT) on these arrays. For example,
```python
import cupy as cp

...

# A and B are large 3D numpy arrays, e.g., 4096x4096x100
arrayA = cp.array(A)
arrayB = cp.array(B)

output = cp.fft.ifftn(cp.multiply(cp.fft.fft(arrayA), arrayB)).real
```

**Comment by okuta** [comment]
Sorry, current CuPy does not support such feature.

FYI, Can you NVLINK on your environment? If you use only PCI-ex, you can not get performance improvement.

**Comment by khcs** [comment]
Thanks for your reply, and sorry for my delay in getting back to you.
If I have NVLINK, then the above code should execute faster using (one) GPU and CPU memory?

Thank you

**Comment by okuta** [comment]
> If I have NVLINK, then the above code should execute faster using (one) GPU and CPU memory?
Maybe yes. Nvidia provides the unified memory and wide band width memory access on NVLINK environment.

**Comment by khcs** [comment]
Thank you for your comments!
