### ISSUE TITLE
Use curand device API

### ISSUE THREAD

**Issue by toslunar** [cupy/cupy#1431]
https://docs.nvidia.com/cuda/curand/device-api-overview.html

- #1356 added RNG kernel but it seems hard to maintain.
  - By the way, `self.rk_seed += size` might not have good properties....
- The performance of `randint` could be improved if out-of-range values are discarded as soon as generated in GPU.

**Comment by okuta** [comment]
NVRTC does not support cuRAND. We have to compile CUDA source code at setup.

**Comment by kmaehashi** [comment]
Use of cuRAND device API introduced in new Generator API, so I guess this can be closed?

For record,

> NVRTC does not support cuRAND. We have to compile CUDA source code at setup.

This is no longer true thanks to Jitify, but we use `nvcc` to build code using cuRAND during installation for HIP compatibility

**Comment by toslunar** [comment]
Yes!
