### ISSUE TITLE
Fix memory leak in Python 3.7

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#1461]
The tentative fix is made in #1457 for Python 3.7, but it leaks memory.

```py
import cupy
import gc

def func():
    try:
        a = cupy.ones((1000,1000)).reshape(1000,1000)
        raise RuntimeError
    except Exception as e:
        err = e


func()
print(cupy.get_default_memory_pool().used_bytes())
print(gc.collect())
print(cupy.get_default_memory_pool().used_bytes())
```

**Comment by okuta** [comment]
Python2.7
```
0
0
0
```

Python3.5
```
8000000
7
0

```

Python3.6
```
8000000
7
0
```

Python3.7
```
8000000
7
8000000

```

**Comment by kmaehashi** [comment]
![frame](https://user-images.githubusercontent.com/939877/42987420-39062e6a-8c34-11e8-83ca-2c528bb392b0.png)
I see, so this issue only occurs when circular reference is detected (note: frame holds local variable `a`). The order of `tp_clear` call for objects under the cycle is undetermined (and maybe it changed in Python 3.7).
