### ISSUE TITLE
Can not create matrix of 1,000,000 lines.

### ISSUE THREAD

**Issue by Qi2013** [cupy/cupy#1489]
I have a box with GeForce GTX 1070 and I5 CPU with 32GB memory.
When I try to create a big matrix, I got a CUDA OutOfMemoryError. I am not sure if it is the desired behavior.

When I try the following code:
 x = cp.random.uniform(size=1000000*300).reshape(1000000, 300).astype('f')

I got the following Error:
cupy/core/core.pyx in cupy.core.core.ndarray.__add__()

cupy/core/elementwise.pxi in cupy.core.core.ufunc.__call__()

cupy/core/elementwise.pxi in cupy.core.core._get_out_args()

cupy/core/core.pyx in cupy.core.core.ndarray.__init__()

cupy/cuda/memory.pyx in cupy.cuda.memory.alloc()

cupy/cuda/memory.pyx in cupy.cuda.memory.MemoryPool.malloc()

cupy/cuda/memory.pyx in cupy.cuda.memory.MemoryPool.malloc()

cupy/cuda/memory.pyx in cupy.cuda.memory.SingleDeviceMemoryPool.malloc()

cupy/cuda/memory.pyx in cupy.cuda.memory.SingleDeviceMemoryPool._malloc()

OutOfMemoryError: out of memory to allocate 1200000000 bytes (total 7204800000 bytes)

**Comment by kmaehashi** [comment]
Please make sure that there is enough free memory on GPU (you can use ``nvidia-smi``).

**Comment by Qi2013** [comment]
Hi kemaehashi,
I tried the following code and got the same error again. 
The nividia-smi.exe showed under "memory-Usage" ,  " 5759MiB /  8192MiB". I suppose that meant that I still had 5759MiB  on GPU.

Aprat from that, isn't it the idea , that if there is no enough memory on GPU then CP should fit it into the RAM and stream it onto the GPU, make the computation and stream back to the RAM?

In the following, I copy the code and the error message:
===================================================================
 matrix =  cp.random.uniform(size=1000000*300).reshape(1000000, 300).astype('f')

---------------------------------------------------------------------------  
CUDARuntimeError                          Traceback (most recent call last)  
cupy/cuda/memory.pyx in cupy.cuda.memory.SingleDeviceMemoryPool._malloc()    
                                                                             
cupy/cuda/memory.pyx in cupy.cuda.memory.SingleDeviceMemoryPool._alloc()     
                                                                             
cupy/cuda/memory.pyx in cupy.cuda.memory._malloc()                           
                                                                             
cupy/cuda/memory.pyx in cupy.cuda.memory._malloc()                           
                                                                             
cupy/cuda/memory.pyx in cupy.cuda.memory.Memory.__init__()                   
                                                                             
cupy/cuda/runtime.pyx in cupy.cuda.runtime.malloc()                          
                                                                             
cupy/cuda/runtime.pyx in cupy.cuda.runtime.check_status()                    
                                                                             
CUDARuntimeError: cudaErrorMemoryAllocation: out of memory                   
                                                                             
During handling of the above exception, another exception occurred:          
                                                                             
CUDARuntimeError                          Traceback (most recent call last)  
cupy/cuda/memory.pyx in cupy.cuda.memory.SingleDeviceMemoryPool._malloc()    
                                                                             
cupy/cuda/memory.pyx in cupy.cuda.memory.SingleDeviceMemoryPool._alloc()     
                                                                             
cupy/cuda/memory.pyx in cupy.cuda.memory._malloc()                           
                                                                             
cupy/cuda/memory.pyx in cupy.cuda.memory._malloc()                           
                                                                             
cupy/cuda/memory.pyx in cupy.cuda.memory.Memory.__init__()                   
                                                                             
cupy/cuda/runtime.pyx in cupy.cuda.runtime.malloc()                          
                                                                             
cupy/cuda/runtime.pyx in cupy.cuda.runtime.check_status()                    
    CUDARuntimeError                          Traceback (most recent call last)
cupy/cuda/memory.pyx in cupy.cuda.memory.SingleDeviceMemoryPool._malloc()

cupy/cuda/memory.pyx in cupy.cuda.memory.SingleDeviceMemoryPool._alloc()

cupy/cuda/memory.pyx in cupy.cuda.memory._malloc()

cupy/cuda/memory.pyx in cupy.cuda.memory._malloc()

cupy/cuda/memory.pyx in cupy.cuda.memory.Memory.__init__()

cupy/cuda/runtime.pyx in cupy.cuda.runtime.malloc()

cupy/cuda/runtime.pyx in cupy.cuda.runtime.check_status()

CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

During handling of the above exception, another exception occurred:

OutOfMemoryError                          Traceback (most recent call last)

**Comment by kmaehashi** [comment]
> The nividia-smi.exe showed under "memory-Usage" , " 5759MiB / 8192MiB". I suppose that meant that I still had 5759MiB on GPU.

This means 5759MiB is occupied (e.g., 2433 MiB free).

> matrix = cp.random.uniform(size=1000000*300).reshape(1000000, 300).astype('f')

This code roughly requires 3 GiB.
* `cp.random.uniform(size=1000000*300)` = 1000000*300*8 bytes (float64)
* `astype('f')`= 1000000*300*4 bytes (float32)
