### ISSUE TITLE
CUPY sparse matrix operations unstable/incorrect answer

### ISSUE THREAD

**Issue by DanMinhNguyen** [cupy/cupy#1527]
Hi all,
I was writing out an iterative optimization algorithm, and initially had found that, only with cupy sparse matrices, my objective value would initially decrease and then begin in increase again. After some digging in I found that numerically, some sparse operations would give an (very) poor approximate answer. You can observe this with simply the sum(axis=n) operation. The sum() operation without a specified axis is actually correct. Below is some code to reproduce the result. Not sure if this was already a known issue, but wanted to bring it up in case so it be patched up quickly.

I am showing the sum(axis=n) operation as an example, but the instability issue should be checked with the other operations, as I am not entirely sure how widespread this is. I do not actually use the sum(axis=n) during my iterative algorithm but noticed instability in the convergence anyways. For example, I use dot() quite a bit.

I am using CUDA 9.0 for reference. 

CODE:
```
import scipy as sp
import cupy as cp

A_cpu_sparse=sp.sparse.random(1000000,4,density=0.05,format='csr')
A_gpu_sparse=cp.sparse.csr_matrix(A_cpu_sparse)

print('summing the rows of the scipy sparse matrix x5')
for i in range(5):
    print(A_cpu_sparse.sum(axis=0))

print()
print('summing the rows of the cupy sparse matrix x5')
for i in range(5):
    print(A_gpu_sparse.sum(axis=0))

```

OUTPUT:
```
summing the rows of the scipy sparse matrix x5
[[24865.55518248 25016.69560176 24909.29570283 24906.80452163]]
[[24865.55518248 25016.69560176 24909.29570283 24906.80452163]]
[[24865.55518248 25016.69560176 24909.29570283 24906.80452163]]
[[24865.55518248 25016.69560176 24909.29570283 24906.80452163]]
[[24865.55518248 25016.69560176 24909.29570283 24906.80452163]]

summing the rows of the cupy sparse matrix x5
[[24879.74008114 25014.22246238 24884.32346184 24905.04780789]]
[[24887.73501406 25034.15557276 24917.14414775 24901.85586254]]
[[24875.54459418 25012.33884019 24893.45248958 24922.22282597]]
[[24889.75760974 25060.28799691 24882.21321479 24914.13871735]]
[[24884.91975934 25036.18994138 24890.58437747 24906.79427548]]
```

**Comment by fiarabbit** [comment]
I could reproduce with

- cupy==5.0.0b3
- scipy==1.1.0 (build with numpy==1.15.0)
- CUDA==9.2
- cuda-cusparse-9-2

**Comment by devmessias** [comment]
Same problem
cupy.__version__=6.3.0

**Comment by kmaehashi** [comment]
I've revisited this and it seems cuSparse that comes with CUDA 11.3 does not have this issue.

```
summing the rows of the scipy sparse matrix x5
[[24725.06292831 24913.15310066 24915.40784584 25211.67550689]]
[[24725.06292831 24913.15310066 24915.40784584 25211.67550689]]
[[24725.06292831 24913.15310066 24915.40784584 25211.67550689]]
[[24725.06292831 24913.15310066 24915.40784584 25211.67550689]]
[[24725.06292831 24913.15310066 24915.40784584 25211.67550689]]

summing the rows of the cupy sparse matrix x5
[[24725.06292831 24913.15310066 24915.40784584 25211.67550689]]
[[24725.06292831 24913.15310066 24915.40784584 25211.67550689]]
[[24725.06292831 24913.15310066 24915.40784584 25211.67550689]]
[[24725.06292831 24913.15310066 24915.40784584 25211.67550689]]
[[24725.06292831 24913.15310066 24915.40784584 25211.67550689]]
```
