### ISSUE TITLE
Cython CUDA BLAS missing dasum

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#1533]
There is an [`sasum`]( https://github.com/cupy/cupy/blob/655229d7fcf010d8c7933fbecb258b4a762ccb09/cupy/cuda/cublas.pxd#L85 ) in the Cython CUDA BLAS. However it appears that there is no `dasum`.

**Comment by anaruse** [comment]
@kmaehashi  Now that we have `dasum`, I think we can close this.

https://github.com/cupy/cupy/blob/b545c7bc67a7c9a2dc87c7a3a8b2ffeb2d45758c/cupy_backends/cuda/libs/cublas.pyx#L565-L570

**Comment by jakirkham** [comment]
Thanks Akira! 😄
