### ISSUE TITLE
`cupy.true_divide` produces wrong answer when `dtype=numpy.float64` supplied

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#1534]
Rel. https://github.com/chainer/chainer/pull/5211

`cupy.true_divice`, as well as `cupy.divide` in Py3, produces wrong answer when they are called with `dtype=numpy.float64` argument.

```
>>> numpy.true_divide(28.359679918034566, 39)
0.7271712799496043
>>> numpy.true_divide(28.359679918034566, 39, dtype=numpy.float64)
0.7271712799496043
>>> cupy.true_divide(28.359679918034566, 39)
array(0.72717128)
>>> cupy.true_divide(28.359679918034566, 39, dtype=numpy.float64)
array(0.71794872)
```

Its reason is that when `dtype=numpy.float64` is supplied, `cupy.true_divide` chooses the routine with the signiture of `bb->d`, not `dd->d`, where inputs are casted to `int8` before division, consequently comes to produce a wrong answer.

```
>>> cupy.true_divide.types
['bb->d', 'BB->d', 'hh->d', 'HH->d', 'ii->d', 'II->d', 'll->d', 'LL->d', 'qq->d', 'QQ->d', 'ee->e', 'ff->f', 'dd->d', 'FF->F', 'DD->D']
```

NumPy had ever had the same problem and seems to fix it in https://github.com/numpy/numpy/pull/9469 .

**Comment by hvy** [comment]
For the record, #2075 has been merged.

**Comment by okuta** [comment]
This issue has already been resolved.
```
In [1]: import numpy;import cupy

In [2]: numpy.true_divide(28.359679918034566, 39)
Out[2]: 0.7271712799496043

In [3]: numpy.true_divide(28.359679918034566, 39, dtype=numpy.float64)
Out[3]: 0.7271712799496043

In [4]: cupy.true_divide(28.359679918034566, 39)
Out[4]: array(0.72717128)

In [5]: cupy.true_divide(28.359679918034566, 39, dtype=numpy.float64)
Out[5]: array(0.72717128)
```
