### ISSUE TITLE
how to use CUDA vector types, e.g. float2/3/4 in cupy?

### ISSUE THREAD

**Issue by mingwugmail** [cupy/cupy#1535]
I think if the data's last dimension is 2/3/4, using these native CUDA vector types will simplify and speed up the code.

Is there any example on how to use these types in cupy? and custom defined kernels?

Thanks.

**Comment by okuta** [comment]
CuPy v5.0.0b3 supports raw kernel #1398.
Maybe you can cast raw `float *` to `float2 *` ( [this is original core](https://github.com/cupy/cupy/blob/master/tests/cupy_tests/core_tests/test_raw.py).
