### ISSUE TITLE
Error installing CuPy in Windows even with wheels (pip install cupy-cuda91)

### ISSUE THREAD

**Issue by vasselai** [cupy/cupy#1545]
I have been trying to install CuPy in my Windows 10 64bits machine, to use with Python 2.7 and Cuda 9.1.85:

`>nvcc --version`
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:08:12_Central_Daylight_Time_2017
Cuda compilation tools, release 9.1, V9.1.85`

My GPU also meets the requirements, since it is a GeForce GTX 960M [thus with 5.0 compute capability](https://en.wikipedia.org/wiki/CUDA).

When I try `pip install cupy` I get a few errors in the installation log (which you can find attached). Then when I try `pip install cupy-cuda91` I get:

`>pip install cupy-cuda91
Collecting cupy-cuda91
  Could not find a version that satisfies the requirement cupy-cuda91 (from versions: )
No matching distribution found for cupy-cuda91`

I wonder if I am missing any basic step here, or whether you can help me sort out what might be interfering with the installation since I seem to have all requirements met to easily install via wheels.

[cuda_install_log.txt](https://github.com/cupy/cupy/files/2299995/cuda_install_log.txt)

**Comment by kmaehashi** [comment]
Currently Windows wheels are available only for development releases (v5.x alpha/beta). You may need to use `--pre` option (e.g. `pip install --pre cupy-cuda91`) to install development releases.
We're planning to release Windows wheels also for stable releases (v4.x series).

If the option does not work for you, also make sure that you have the latest pip installed (`python -m pip install -U pip`). Some old `pip` command cannot install wheels.

**Comment by vasselai** [comment]
@kmaehashi Thanks for replying. So, I do have the most up-to-date `pip`:

`>python -m pip install -U pip`
`Requirement already up-to-date: pip in c:\python27\lib\site-packages (18.0)`

And I also updated CUDA to 9.2:

`>nvcc --version`
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:08:12_Central_Daylight_Time_2018
Cuda compilation tools, release 9.2, V9.2.148`

Unfortunately, `pip install --pre cupy-cuda92` resulted in the same message:

`Could not find a version that satisfies the requirement cupy-cuda92 (from versions: )
No matching distribution found for cupy-cuda92`

**Comment by kmaehashi** [comment]
Thanks for the followup @disktnk, I missed that point.

**Comment by vasselai** [comment]
> Python2.7 (compiling) requires Visual Studio9.0 (VS2008) but CUDA support from Visual Studio 2012~, so local build may also be difficult, I think.

Yeap, that seems to be the issue with `pip install cupy`, since the first error messages return error status 2 at Visual C++ for Python's cl.exe (see my attached log in the OP).

> On Windows OS, cupy wheel only supports Python3.6. ref: https://pypi.org/project/cupy-cuda91/5.0.0b3/#files

Very true. So, it seems that there is really no alternative for using CuPy in Windows with Python 2.7.

**Comment by vasselai** [comment]
Also @kmaehashi and @disktnk , for Windows users it seems that there is only a wheel for AMD CPUs available, is that right? If there are version of CuPY that would work in Windows with Interl CPUs let me know - even them require earlier CUDA versions and Python 3.6, I could install those to test and see if I can make CuPY work in my current system.

**Comment by kmaehashi** [comment]
The word `amd64` is just a synonym of `x86_64` used in Python. You can use it on Intel 64-bit arch CPUs.

**Comment by vasselai** [comment]
So, I did revert back to CUDA 9.1 and installed Python 3.6 as a new environment within my Anaconda installation:

`>python --version`
`Python 3.6.4 :: Anaconda, Inc.`

I also made sure I have the most recent pip version there too:
`>pip --version`
`pip 18.0 from c:\program files\anaconda2\envs\py3\lib\site-packages\pip (python 3.6)`

Then, I tried to install CuPY with `pip install --pre cupy-cuda91`. There is progress: now cupy-cuda91 is correctly collected. However, the installation fails. I send attached the error log. The first error seems to be that it "Failed building wheel for fastrlock".

[cupy-errorlog.txt](https://github.com/cupy/cupy/files/2313121/cupy-errorlog.txt)

**Comment by vasselai** [comment]
@kmaehashi I solved the issue and, to help others that might be in the same situation in the future, here's the solution: for some reason, pip and pip3 were being unable to call Visual Studio C++ command line compiler. Reinstalling Microsoft Visual C++ Build Tools 2017 did the trick.

While all my code is done with Python 2.7, now I have CuPY properly running with Python 3.6 in a separate Anaconda environment for some testing.

Consider my case closed :)
