### ISSUE TITLE
Doc links are broken

### ISSUE THREAD

**Issue by ClimbsRocks** [cupy/cupy#155]
It took me a lot of clicking to find the working docs just now. 

Clicking on the badge link in the README takes me to a page that throws this error:
![image](https://user-images.githubusercontent.com/7017045/27254737-02f51fae-5344-11e7-853c-70abdd1997ea.png)

Clicking the top Google search link gives me the same error:
https://docs.cupy.chainer.org/

I found a working link a few results further down:
http://docs.chainer.org/en/stable/_modules/chainer/cuda.html

But then when I click "Edit on GitHub" on those docs, that link takes me to a GitHub page that doesn't exist, or doesn't have public permissions:
https://github.com/pfnet/chainer/blob/2a452f331c6d2634a05a4e3d9bee6ba5dbdd21f6/docs/source/_modules/chainer/cuda.rst

Quite excited to check out this project in more depth at some point!

**Comment by okuta** [comment]
Thank you for your report.
We are working in #131 and #177.

**Comment by okuta** [comment]
This issue was fixed.
