### ISSUE TITLE
bug for 4.4.0 release. Can not working on multi threading.

### ISSUE THREAD

**Issue by BobLiu20** [cupy/cupy#1579]
This [merge](https://github.com/cupy/cupy/pull/1350/files) has bug when working on multi threading. 

![image](https://user-images.githubusercontent.com/6102702/44715413-55010700-aaea-11e8-8569-f6311ea7a632.png)

Appear this issue after upgrade to 4.4.0. I had to rollback my package to 4.3.0 now.

**Comment by kmaehashi** [comment]
We released a hot-fix for this issue. Thanks again for reporting!

https://github.com/cupy/cupy/releases/tag/v4.4.1

**Comment by BobLiu20** [comment]
Cool. Thank you for your quick response! Love CuPy.
