### ISSUE TITLE
scipy.signal.convolve like convolve op support

### ISSUE THREAD

**Issue by StrangerZhang** [cupy/cupy#1639]
scipy.signal.convolve like convolve op support

**Comment by jakirkham** [comment]
Some related discussion in issue ( https://github.com/cupy/cupy/issues/1639 ). Though this is thinking about the N-D `convolve` case (amongst other things).

**Comment by awthomp** [comment]
Though not in the CuPy codebase, we added Raw CuPy CUDA kernels for `correlate` and `convolve` in [cuSignal](https://github.com/rapidsai/cusignal). See @mnicely's merged PR here: https://github.com/rapidsai/cusignal/pull/62

Someone may be able to leverage this work in building out CuPy native support.

**Comment by mnicely** [comment]
To clarify, those implementation are only for 1D. You should be able to convolved2d and correlate2d for 2D inputs. Is there are strong need for 3D and higher?

**Comment by awthomp** [comment]
> To clarify, those implementation are only for 1D. You should be able to convolved2d and correlate2d for 2D inputs. Is there are strong need for 3D and higher?

`convolve2d` and `correlate2d` raw CuPy CUDA kernel implementations can be found here: https://github.com/rapidsai/cusignal/pull/49
