### ISSUE TITLE
Invalid value for --gpu-architecture (-arch)

### ISSUE THREAD

**Issue by swaroopchatterjee** [cupy/cupy#1651]
Hi 
I was trying to run the basic tutorial for cupy and ran into a compile error. 
GPU is GF108 [GeForce GT 730]
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

I am seeing

In [1]: import cupy as cp

In [2]: x_gpu = cp.array([1, 2, 3])

In [3]: l2_gpu = cp.linalg.norm(x_gpu)
NVRTC compilation error: nvrtc: error: invalid value for --gpu-architecture (-arch)

-----
Name: 
Options: -I/home/xxxxx/miniconda3/lib/python3.6/site-packages/cupy/core/include -I /usr/include -ftz=true -arch=compute_21
CUDA source:
1 
-----
---------------------------------------------------------------------------
NVRTCError                                Traceback (most recent call last)
~/miniconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py in compile(self, options)
    240         try:
--> 241             nvrtc.compileProgram(self.ptr, options)
    242             return nvrtc.getPTX(self.ptr)

cupy/cuda/nvrtc.pyx in cupy.cuda.nvrtc.compileProgram()

cupy/cuda/nvrtc.pyx in cupy.cuda.nvrtc.compileProgram()

cupy/cuda/nvrtc.pyx in cupy.cuda.nvrtc.check_status()

NVRTCError: NVRTC_ERROR_INVALID_OPTION (5)

During handling of the above exception, another exception occurred:

CompileException                          Traceback (most recent call last)
<ipython-input-3-0fe9cdef4d9e> in <module>()
----> 1 l2_gpu = cp.linalg.norm(x_gpu)

~/miniconda3/lib/python3.6/site-packages/cupy/linalg/norms.py in norm(x, ord, axis, keepdims)
     33     """
     34     if not issubclass(x.dtype.type, numpy.inexact):
---> 35         x = x.astype(float)
     36 
     37     # Immediately handle some default, simple, fast, and common cases.

cupy/core/core.pyx in cupy.core.core.ndarray.astype()

cupy/core/core.pyx in cupy.core.core.ndarray.astype()

cupy/core/elementwise.pxi in cupy.core.core.ufunc.__call__()

cupy/util.pyx in cupy.util.memoize.decorator.ret()

cupy/core/elementwise.pxi in cupy.core.core._get_ufunc_kernel()

cupy/core/elementwise.pxi in cupy.core.core._get_simple_elementwise_kernel()

cupy/core/carray.pxi in cupy.core.core.compile_with_cache()

~/miniconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py in compile_with_cache(source, options, arch, cache_dir, extra_source)
    133     if base is None:
    134         # This is checking of NVRTC compiler internal version
--> 135         base = _preprocess('', options, arch)
    136         _empty_file_preprocess_cache[env] = base
    137     key_src = '%s %s %s %s' % (env, base, source, extra_source)

~/miniconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py in _preprocess(source, options, arch)
     96     prog = _NVRTCProgram(source, '')
     97     try:
---> 98         result = prog.compile(options)
     99     except CompileException as e:
    100         dump = _get_bool_env_variable(

~/miniconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py in compile(self, options)
    243         except nvrtc.NVRTCError:
    244             log = nvrtc.getProgramLog(self.ptr)
--> 245             raise CompileException(log, self.src, self.name, options)
    246 
    247 

CompileException: nvrtc: error: invalid value for --gpu-architecture (-arch)

Thanks for your help.

**Comment by kmaehashi** [comment]
Please also note that compute capability < 3 is no longer supported (at least officially) in CuPy v4.0+.
http://docs-cupy.chainer.org/en/stable/upgrade.html#compute-capability
