### ISSUE TITLE
Add CUDA 10 support

### ISSUE THREAD

**Issue by mitmul** [cupy/cupy#1656]
ref: https://developer.nvidia.com/cuda-toolkit/whatsnew

**Comment by panovr** [comment]
Any plan for adding CUDA 10 support?

**Comment by mitmul** [comment]
@panovr It has been supported by this PR: #1824 !
It will be backported with #1826 to the current stable version too.

**Comment by kmaehashi** [comment]
FYI, there's no known issues in existing CuPy releases (v5.x and v6.x) using CUDA 10.
We will officially support CUDA 10 (and release wheels for CUDA 10 `cupy-cuda100`) in the next release planned next week.

**Comment by ivan-bilan** [comment]
> FYI, there's no known issues in existing CuPy releases (v5.x and v6.x) using CUDA 10.
> We will officially support CUDA 10 (and release wheels for CUDA 10 `cupy-cuda100`) in the next release planned next week.

Any update on the release?

**Comment by kmaehashi** [comment]
We have released CUDA 10 wheels for v5.1.0 & v6.0.0b1.
https://pypi.org/project/cupy-cuda100/#history

**Comment by panovr** [comment]
@mitmul @kmaehashi Thanks for adding CUDA 10 support! 👍

**Comment by fingoldo** [comment]
Would you then kindly update installation instructions here: https://docs-cupy.chainer.org/en/stable/install.html#install-cupy
To avoid confusion and extra googling.

**Comment by kmaehashi** [comment]
@fingoldo Thanks for pointing that out! Docs of the stable version will be updated after the next release planned on this month.
