### ISSUE TITLE
cupy[x].scatter_add vs numpy.add.at

### ISSUE THREAD

**Issue by arogozhnikov** [cupy/cupy#1658]
Discussion from https://github.com/cupy/cupy/pull/846

> I followed the convention of how cupy.scatter_add is exposed (scatter_add is cupy-specific and placed directly under cupy namespace), but as you pointed out, rsqrt seems to have relatively higher risk of future conflict than scatter_add.

Is there any difference between `numpy.add.at` and `cupyx.scatter_add`? If no, it can take it place to match numpy even better.

**Comment by kmaehashi** [comment]
There should be no difference between two.

I'm not sure why this is commented out. cc/ @okuta?
https://github.com/cupy/cupy/pull/1247/commits/915b1c285da5804e57040d144026682a1ee0ef77#diff-bebe923819e806ae22e9923de58e954cL1597

**Comment by okuta** [comment]
Maybe, we don't have test about `add.at` .
You can add test and comment out that lines.

**Comment by kmaehashi** [comment]
Implemented in #7077.
