### ISSUE TITLE
Need in-place and planned C2C & Z2Z FFT for better performance

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#1669]
Hello it's me again. I am migrating another set of codes to CuPy. This program heavily relies on C2C & Z2Z (complex-to-complex, single/double precision) FFT (we spend >50% of runtime in FFT), and I notice that CuPy's FFT wrapper always does an "out of place" transform; that is, all routines in the `cupy.fft` family allocate an additional buffer during FFT at this line https://github.com/cupy/cupy/blob/5e17c157faa60bedacd6d6cbdc51d63e7145c80d/cupy/fft/fft.py#L74
, causing highly redundant data movement in our code (nvprof shows ~25% of time spent here). 

However, according to the cuFFT doc it supports in-place C2C & Z2Z FFT, so it'd be nice if this feature can be added. Perhaps we can have an additional flag for users to make their own decision, or we can also compare the in and out buffers to decide if in-place or not under the hood, see for example scikit-cuda's implementation at https://github.com/lebedov/scikit-cuda/blob/87f34fbe09d45825b2214665d5aa8c4da9e2ffdb/skcuda/fft.py#L195 
(this may not be easy to achieve based on the current API design though).
If you do not have the bandwidth to support this in the near future, I might be able to create a PR. Let me know what you think.

Thank you very much.

**UPDATE on Feb 16, 2019**: See https://github.com/cupy/cupy/issues/1669#issuecomment-454488982 for a todo list.

**Comment by grlee77** [comment]
Hi @leofang 
I recently implemented this for `fftn` and `ifftn` and was planning to make a PR.  If you want to test it or collaborate on improvements, that would be welcome.

I am not sure exactly how it can best fit into `cupy` as it introduces a couple of keyword arguments that are not part of the NumPy API.

Specifically, if you want to try it you can use the following branch:
https://github.com/grlee77/cupy/tree/cufftn/
I have only modified `cupy.fft.fftn` and `cupy.fft.ifftn` to use n-dimensional plans and potential in-place operation. To try it, you need to set `plan_type='nd'` and pass in your preallocated array via the `out` kwarg.  The PR also allows precomputing and storing the plan via a new function `cupy.fft.get_cufft_plan_nd` which can also be passed in via the `plan` kwarg.
For the 2D and 3D FFTs I have been using, the n-d planning and preallocating the plan make a much bigger difference than the use of an in-place array.  I have seen an order of magnitude improvement in some situations.

**Comment by leofang** [comment]
Hello @grlee77, thanks a lot for your quick reply and for doing this! I'm glad that I'm not the only one who has this need, and that I asked here before rushing into duplicate effort!

I just quickly went over your implementation. In terms of API design I have no objection. I know it's going to be a little incompatible with that of Numpy, and I think keyword arguments should bring only minimal impact. If the cupy maintainers want, they can always rename your `fftn` to something else (`planed_fftn` maybe?) and keep the original `fftn` unchanged for better compatibility. 

It'd be nice if the following things can be supported:
1. Z2Z transform: in your `_fftn` only C2C was supported, but I see that elsewhere you included both C2C and Z2Z. Was this simply due to debugging reasons?
2. stream: it'd be nice if user-defined streams can be added (currently you detect the current stream)
3. batch: it'd be nice to allow customized FFT batch size to keep GPU busy.
4. in-place `ifftn`: the `out` argument is still missing in your `ifftn` implementation, while your commit message said otherwise. 

I agree with you that planning also makes a big difference, which was why we used scikit-cuda in the first place. I think this concept is borrowed from FFTW. So, ultimately it'd be great to put all these (plan, batch, and in-place) together in cupy.

I will be occupied in the next few weeks. I'll try to find some spare time to test your code, and keep you updated. Thanks again.

**Comment by grlee77** [comment]
The Z2Z support and adding the missing `out` kwarg for ifftn will be easy to fix. I can polish it up a little bit and make a PR.

> stream: it'd be nice if user-defined streams can be added (currently you detect the current stream)

I handled streams the same way as the existing cupy FFT routines, but I know a user-specified stream is supported in scikit-cuda. Not sure if there is a convention to allow user-specified streams elsewhere in cupy?

Another shortcoming of my current implementation is that it doesn't currently support transforms of different size than the data, but that can probably be added if needed.

> batch: it'd be nice to allow customized FFT batch size to keep GPU busy.

Do you have a concrete example for this (not sure I understand the intended use)?.  A batch is currently being used when not all axes are transformed to loop over the non-transformed axes.

**Comment by leofang** [comment]
>> stream: it'd be nice if user-defined streams can be added (currently you detect the current stream)
>
> I handled streams the same way as the existing cupy FFT routines, but I know a user-specified stream is supported in scikit-cuda. Not sure if there is a convention to allow user-specified streams elsewhere in cupy?

Let us not worry about this for now. Indeed there's no user-specified stream in most of cupy functions. In chainer they use streams in high-level functions. I suppose this makes better sense?

> Another shortcoming of my current implementation is that it doesn't currently support transforms of different size than the data, but that can probably be added if needed.

For our use we don't need this, so it's not a shortcoming to me 😄 

>> batch: it'd be nice to allow customized FFT batch size to keep GPU busy.
>
> Do you have a concrete example for this (not sure I understand the intended use)?. A batch is currently being used when not all axes are transformed to loop over the non-transformed axes.

You're right about its usage (to loop over the non-transformed axes). I don't know what I was thinking, sorry. 😛 

@grlee77, looks like you've taken serious consideration into this. GJ!

**Comment by not522** [comment]
How about implement `cupyx.scipy.fftpack`? SciPy's FFT functions have `overwrite_x` parameter, and if it is `True`, we can use in-place FFT.

**Comment by grlee77** [comment]
Using `overwrite_x` would be fine by me, but for my use cases, passing in a CUFFT plan is where the biggest gain comes from and I don't think there is a way to do that without adding an additional argument (unless one wanted to implement some sort of cache of CUFFT plans which might be problematic from a memory usage standpoint).  Here is a concrete example based on the code currently in my branch (on a GTX 1080 Ti GPU):

```python
import numpy as np
from numpy.fft import fftn
import cupy
from cupy.fft.fft import get_cufft_plan_nd

shape = (64, 64, 64)
axes = (0, 1, 2)
a = np.random.randn(*shape).astype(np.float32)
a = a + 1j*np.random.randn(*shape).astype(np.float32)
ca = cupy.asarray(a)
# preallocate a CUFFT plan for this transform
plan = get_cufft_plan_nd(ca.shape, cupy.cuda.cufft.CUFFT_C2C, axes=axes)
```
```python
# run using the existing, separable 1D API without preplanning
%timeit cupy.fft.fftn(ca, axes=axes, plan_type='1d')
```
**result**:  2.68 ms

```python
# run using a 3D plan, but without preplanning
`%timeit cupy.fft.fftn(ca, axes=axes, plan_type='nd')`
```
**result**:  0.811 ms 
~3 fold speedup just by using the n-dimensional planning, albeit at some cost in memory due to the increased workspace required by the n-d plan.

```python
# run using a 3D plan and the precomputed CUFFT plan
`%timeit cupy.fft.fftn(ca, axes=axes, plan_type='nd', plan=plan)`
```
**result**: 0.165 ms
large additional gain in speed by precomputing the plan

```python
# run using a 3D plan, the precomputed CUFFT plan and in-place operation
`%timeit cupy.fft.fftn(ca, axes=axes, plan_type='nd', plan=plan, out=ca)`
```
**result**: 0.125 ms
some additional improvement via in-place operation.

What I would like is some way to pass in a precomputed plan, which neither the numpy or scipy API has an equivalent for because neither `fftpack` (or `pocketfft` in upcoming NumPy) use FFTW-style plans.
I don't have a problem with this functionality living somewhere else like the `cupyx` module if you want to keep the content of `cupy.fft` strictly mirroring the NumPy API. I think given the huge potential gains in performance as shown in the example above, this would be of interest to users.

**Comment by grlee77** [comment]
> Of course, caching is not an easy way, but I think that it is possible to implement like a memory pool.

pyFFTW implements an (optional) cache of FFTW plans which expire after a user-defined time using the following class:
https://github.com/pyFFTW/pyFFTW/blob/master/pyfftw/interfaces/cache.py

with keys based on shape, stride, dtype, etc. set as in the following:
https://github.com/pyFFTW/pyFFTW/blob/701350df800b9440b8699d5860276e75effde626/pyfftw/interfaces/_utils.py#L99-L114

What do you think of adapting that approach to CUFFT? (the pyFFTW code linked above is under a BSD 3-clause license)

> And, We should note that reusing plans may cause troubles due to multithreading (#1109).

Noted. Perhaps the thread id as returned by `threading.get_ident()` could be included as part of the key in the cache dictionary? That should force each thread to generate its own plans.

**Comment by not522** [comment]
I recommend to delete plans when GPU memory is a shortage, but I'm not sure it is possible. I would like to ask opinions of core members.

For now, I started by implementing SciPy-compatible FFT functions to support in-place mode.

**Comment by leofang** [comment]
title changed to reflect the importance of planning as pointed out by @grlee77.

**Comment by leofang** [comment]
While #1746 is pending review, I'd like to continue the discussion in https://github.com/cupy/cupy/pull/1746/files#r241462216 There @grlee77 mentioned  
> I did not add overwrite_x to the numpy functions because that is not part of the numpy API, but I did add use of nD plans to the scipy.fftpack interfaces as well. 

when replying my question on `overwrite_x`. 

Now that I think about caching plans as discussed above, I have further questions: Do we have to mirror the API (of either numpy or scipy) exactly? I mean, for users don't care about cuFFT plans, doesn't the following signature
```python
cupy.fft.fftn(a, s=None, axes=None, norm=None, plan=None)
```
behave completely identical as if `plan` were not there (and thus the backward compatibility is preserved)? Similar for other functions in `cupy.fft` or `cupyx.scipy.fftpack`. May I ask the concerns of the core dev for having additional arguments defaulted to `None`, if any?

In @grlee77's planned implementation #1746, `cupyx.scipy.fftpack` supports both explicit in-place operation (via the `overwrite_x` argument) and implicit plans (via setting `cupy.fft.config.enable_nd_planning`). I would suggest, if no change is permitted to the numpy API, considering to add the `plan=None` argument to `cupyx.scipy.fftpack.fftn` and `ifftn` so that the plan becomes explicit. This will benefit a big class of apps like ours in which only one plan is needed throughout the computation. We can simply create the plan in the initialization phase and pass it to `fftn` and `ifftn` every time we call them. In this use case caching is done manually.

I will be more than happy to contribute on top of #1746 if @grlee77 is busy. Thanks.

**Comment by leofang** [comment]
@not522 @takagi Any comments on my latest reply (explicitly passing cuFFT plans)?

**Comment by leofang** [comment]
> Generally, additional arguments are acceptable. Considering the benefit of reusing plans, your suggestion makes sense. But, FFT Plan classes are undocumented (or in other words undefined) features, thus we need to define the interface. I think the current implementation is well, so we only need to document the features.

OK, so I'll start by adding a `plan` argument to the `cupyx.scipy.fftpack` family. I'll leave the `cupy.fft` family untouched unless you think it's OK to change it. In this way, the former will provide full interface for performance boosts, while the latter offers a simple, "ready-to-go" interface for easy prototyping. Sounds good? I may be able to contribute to the docs later.

> 
> By the way, @okuta suggests `lru_cache` help the performance of FFTs. This function is limited to Python 3, but in most use cases it will work well. Do you have any comments on `lru_cache`?

I don't mind a PY3-only feature since we've switched to it long ago, but I have one comment and two questions: 
1. For the use cases I have in mind, we do not need to cache the plan, just need to expose the interface to it and let users manage the plan themselves. So, cache can be added later (most likely in a separate PR).
2. @not522 You mentioned earlier in this issue
>> We should note that reusing plans may cause troubles due to multithreading (#1109).
Would the multithreading be a problem too for `lru_cache`? What's your experience with multithreading + `lru_cache`?
3. Has @okuta already experimented `lru_cache` with FFT, or he was simply suggesting a possibility? Would you like me to implement the plan cache as well?

Thanks!

**Comment by grlee77** [comment]
Regarding caching of plans:

Currently the FFT plans in CuPy always use the default auto-allocation of a work area for each plan. This work area is what accounts for the majority of the plan memory usage, but it should not be necessary to have a separate auto-allocated work area for each cached plan.  I think it should be possible to disable auto-allocation via `cufftSetAutoAllocation`, estimate plan sizes with (e.g. `cufftEstimateWorkAreaMany`) and then assign already available memory as the work area via `cufftSetWorkArea`. This could avoid much of the memory overhead involved in caching many separate Nd plans.  We could have a work area corresponding to the largest currently cached plan size or just not cache any work area at all and rely on the existing memory pool to obtain one at run time.  I haven't tried to do any of this yet, but it seems like something worth considering.

**Comment by grlee77** [comment]
I would think having separate PRs for adding the plan argument and the plan caching would be appropriate. The former should be fairly simple to implement and review while there are a wider range of possibilities for the caching.

**Comment by leofang** [comment]
@grlee77 Just curious, what if we don't disable auto allocation? Does the second cuFFT plan overwrite the memory of the first plan?

**Comment by grlee77** [comment]
> what if we don't disable auto allocation? Does the second cuFFT plan overwrite the memory of the first plan?

No, with auto-allocation, each plan allocates its own independent workspace array. However, I had forgotten that we already do disable auto allocation, but instead assign a workspace array allocated via the existing memory pool. This is done independently for each plan so the memory overhead as discussed in my comment above still applies.  The end effect is that each plan has its own independent workspace.

See:  
https://github.com/cupy/cupy/blob/6ab44f7cb7bfdc9f10c2420ed46c1a4f3243e69b/cupy/cuda/cufft.pyx#L88-L105

The current implementation is good from a computational performance perspective, but is suboptimal from a memory resources perspective in the case that mmultiple plans are cached.  If CuPy managed the workspaces dynamically, much of the memory overhead could be avoided, but this adds complexity in making sure that any plans sharing the same workspace are not run concurrently.

**Comment by leofang** [comment]
OK below I'm summarizing the work to be done related to this issue. See if I'm missing anything.

TODO:
- [ ] support explicit plans for 2D/3D FFT in `cupyx.scipy.fftpack` (#1942)
- [ ] support explicit plans for 1D FFT in `cupyx.scipy.fftpack` (I'll do this after PR #1942 is merged)
- [ ] support auto plans for C2R, R2C, D2Z and Z2D FFT in `cupy.fft.fft` (#1936) 
- [ ] support explicit plans for C2R, R2C, D2Z and Z2D FFT in `cupyx.scipy.fftpack`
- [ ] cache plans for FFT in `cupy.fft.fft` (further discussion needed)

**Comment by leofang** [comment]
Closing this issue since the main requests were implemented. Issues listed in https://github.com/cupy/cupy/issues/1669#issuecomment-454488982 should be opened as separate ones.
