### ISSUE TITLE
Device-to-host copy in `examples/stream/cupy_memcpy.py` is not asynchronous

### ISSUE THREAD

**Issue by grafi-tt** [cupy/cupy#1692]
I've interested in asynchronous memcpy for better performance. I checked the `cupy_memcpy.py` sample, and noticed that the last line `x_pinned_cpu = x_gpu.get()` [1] shouldn't work asynchronously. Unfortunately I don't know how to properly fix it.

One issue is trivial: this line re-binds the variable `x_pinned_cpu`, instead of updating the value bound to this variable.

But there is another more tricky problem. The function `cupy.ndarray.get` creates the new `numpy.ndarray` instance by calling `numpy.empty`, and passes the new host pointer to the `copy_to_host_async` function [2]. IIUC, as the new array not allocated in pinned memory, the copy couldn't be asynchronous with other computations at the GPU.

* [1] https://github.com/cupy/cupy/blob/v5.0.0rc1/examples/stream/cupy_memcpy.py#L24
* [2] https://github.com/cupy/cupy/blob/v5.0.0rc1/cupy/core/core.pyx#L1805

**Comment by kmaehashi** [comment]
> The function cupy.ndarray.get creates the new numpy.ndarray instance by calling numpy.empty, and passes the new host pointer to the copy_to_host_async function [2]. IIUC, as the new array not allocated in pinned memory, the copy couldn't be asynchronous with other computations at the GPU.

I thought that this is by design as it's not possible to construct numpy ndarray from pinned memory. `copy_to_host_async` is used just to run the memcpy on the user-specified stream.
@okuta do you have any follow up?

**Comment by grafi-tt** [comment]
`ndarray.get` improved by #1970, and rewrite of the example ongoing at #1999.
