### ISSUE TITLE
How to get concurrency from cupy Streams

### ISSUE THREAD

**Issue by mrocklin** [cupy/cupy#1695]
I'm looking at using Streams for concurrency, but am confused by how they operate.  This issue describes some simple experiments and asks for help.  If there is a better place to ask this sort of question please let me know.  I would be happy to move it.

Looking at the examples and documentation I believe that code placed within a stream context manager executes concurrently to code on other streams.  I tried to test this recently and was unable to get speedup.

### map_reduce.py example

First I tried running and modifying the map_reduce.py example in `cupy/examples/streams`.  I ran it normally, and also using a single stream with the following diff.

```diff
diff --git a/examples/stream/map_reduce.py b/examples/stream/map_reduce.py
index 365b67c..de59c7c 100644
--- a/examples/stream/map_reduce.py
+++ b/examples/stream/map_reduce.py
@@ -11,8 +11,9 @@ zs = []
 map_streams = []
 stop_events = []
 reduce_stream = cupy.cuda.stream.Stream()
-for i in range(n):
-    map_streams.append(cupy.cuda.stream.Stream())
+# for i in range(n):
+#     map_streams.append(cupy.cuda.stream.Stream())
+map_streams = [cupy.cuda.stream.Stream()] * n  # use one stream

 start_time = time.time()
```

I found that there was no difference in performance.  

### With threads

I was also surprised that calling code within a context manager allowed cupy to run it concurrently.  I thought that maybe it was necessary to call this code in another CPU thread to allow many concurrent calls down to the GPU.  

I tried a few approaches in this notebook and was unable to get a speedup: https://gist.github.com/mrocklin/d3b70cea6a555ae2387556e4f0808ac1

I suspect that I am doing something incorrectly here.  Perhaps I have not configured my environment correctly?  I apologize for my ignorance here.  Any help would be very welcome.

**Comment by bamartin125** [comment]
I am also having trouble with this. Creating Streams with `Stream(non_blocking=True)` doesn't seem to help either.

I tried this for the example at https://github.com/cupy/cupy/blob/v5/examples/stream/map_reduce.py with no success.

**Comment by mrocklin** [comment]
I am still curious about this issue.  Is my understanding above correct?  Or is there some way to get concurrency from using CuPy streams.  I'm happy with either answer, I'm just curious on how to proceed.  I would be happy to help find people to resolve this issue if it is indeed a bug.

**Comment by sudiptabiswas22** [comment]
I am facing the same issue. I am trying to parallelise memcpy using multiple streams. But the streams seem to run sequentially. Here is the nvvp profiler snippet.
![image](https://user-images.githubusercontent.com/25134017/49698324-4990a200-fbe8-11e8-8d8f-0e8b79047457.png)

**Comment by sudiptabiswas22** [comment]
The issue is highlighted here: https://stackoverflow.com/questions/53692278/how-would-you-run-two-streams-concurrently-in-cupy?noredirect=1#comment94241226_53692278

**Comment by sjperkins** [comment]
@sudiptabiswas22 Memory copies will probably be serialised even if they are issued in separate streams. CUDA devices generally only have one (for gaming card) or two (higher performance science cards) copy engines which handle transfers to and from the device.

**Comment by leofang** [comment]
@mrocklin I think you found a bug, see #2524. In this example, all operations were serialized, which is why you didn't see any performance gain.
