### ISSUE TITLE
CUDA constant memory management 

### ISSUE THREAD

**Issue by enry12** [cupy/cupy#1703]
Hi,

I haven't found any API concerning the creation and management of constant memory. Are you going to release it soon?

In my opinion this feature could be extremely useful due to the introduction of RawKernel API (v5.0.0rc1).

Thanks for your support

**Comment by kmaehashi** [comment]
Currently we have no plans about constant memory.
Do you have specific use-case that you want to use it?

**Comment by enry12** [comment]
I had to compute a kernel matrix from two lists of points several times,
thus I had written a CUDA kernel using RawKernel. One of these two lists is
always the same so I thought to store it in costant memory in order to
speed up the computation.

However, I'm currently computing this kernel matrix in matricial form so I
do not need this functionality anymore but maybe can be usefull in other
cases.


Il giorno gio 8 nov 2018 alle ore 08:58 Kenichi Maehashi <
notifications@github.com> ha scritto:

**Comment by zjw1990** [comment]
Hi, 
I have met the same situation. After I del variables, The GPU memory still occupied.

**Comment by kmaehashi** [comment]
@zjw1990 Your question is not related to this issue. See the docs proposed in https://github.com/cupy/cupy/pull/1871  for details.

**Comment by qwenger** [comment]
Hi,

Thank you for developing CuPy.

I met the same problem as OP. My use case is a 2D kernel involving a bunch of matrix multiplication-like operations, among which some of those matrices are constant (they are typically roughly the size of a block).

Fortunately, I found a workaround to use constant memory in CuPy, using the internal/undocumented/... API:

`import ctypes

import numpy as np
import cupy as cp


kernel_source = """
__constant__ double constant_array_name[10000];

extern "C" __global__ void kernel_fct_name(double* a)
{
    a[threadIdx.x] += constant_array_name[threadIdx.x];
}
"""

cst_array = np.array([[0.0, 1.0], [2.0, 3.0]])
dyn_array = cp.array([[3.0, 4.0], [5.0, 6.0]])

mod = cp.core.core.compile_with_cache(kernel_source, prepend_cupy_headers=False)
b = cp.core.core.memory_module.BaseMemory()
b.ptr = mod.get_global_var("constant_array_name")
p = cp.core.core.memory_module.MemoryPointer(b, 0)
# NOTE: seems that we could also use cst_array.ctypes._data, but avoid internal attributes if possible...
p.copy_from_host(cst_array.ctypes.data_as(ctypes.c_void_p), cst_array.nbytes)
kernel_fct = mod.get_function("kernel_fct_name")

kernel_fct((1,), (4,), dyn_array)

print(dyn_array)`

`[[3. 5.]
 [7. 9.]]`

The small trade-off here is that you get a very uninformative error message if trying to allocate too much constant memory:

`__constant__ double constant_array_name[10000];`

`Traceback (most recent call last):
  File "/.../test.py", line 19, in <module>
    mod = cp.core.core.compile_with_cache(kernel_source, prepend_cupy_headers=False)
  File "cupy/core/carray.pxi", line 125, in cupy.core.core.compile_with_cache
  File "cupy/core/carray.pxi", line 166, in cupy.core.core.compile_with_cache
  File "/.../.local/share/virtualenvs/.../lib/python3.7/site-packages/cupy/cuda/compiler.py", line 167, in compile_with_cache
    ls.add_ptr_data(ptx, u'cupy.ptx')
  File "cupy/cuda/function.pyx", line 212, in cupy.cuda.function.LinkState.add_ptr_data
  File "cupy/cuda/function.pyx", line 214, in cupy.cuda.function.LinkState.add_ptr_data
  File "cupy/cuda/driver.pyx", line 153, in cupy.cuda.driver.linkAddData
  File "cupy/cuda/driver.pyx", line 82, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed`

**Comment by wonghang** [comment]
I am a pycuda user and have my own CUDA kernel written in C code. If I want to port my code from pycuda to cupy, I will also need access to constant memory. 

My use case is that I have a constant memory (storing some floating points) in my code to control the behavior of all kernels so that I don't need to pass the configuration to each kernel every time.

I tested and I think the code is just as simple as:

```python
def cp_array_from_constant_memory(mod,name,shape,dtype):
    b = cp.core.core.memory_module.BaseMemory()
    b.ptr = mod.get_global_var(name)
    memptr = cp.cuda.MemoryPointer(b,0)
    return cp.ndarray(shape,dtype,memptr)

```
