### ISSUE TITLE
windows wheels for python 3.7 cuda 9.2

### ISSUE THREAD

**Issue by metya** [cupy/cupy#1719]
Are you support windows wheels for python 3.7 cuda 9.2?

I have cuda 9.1 and 9.2 and python 3.7 on anaconda 

so when I do 

```
pip install cupy-cuda92
```
i get 
``` 
Collecting cupy-cuda92
Could not find a version that satisfies the requirement cupy-cuda92 (from versions: )
No matching distribution found for cupy-cuda92
```

By the way, in anaconda cupy is 4.1 version. That's why I use pip. Are you going to update conda version?

**Comment by kmaehashi** [comment]
We're working forward to officially support Python 3.7 (#1464). Windows wheels for Py37 are also on the roadmap.

> By the way, in anaconda cupy is 4.1 version. That's why I use pip. Are you going to update conda version?

Thanks for letting us know. Let me check with anaconda maintainer.

**Comment by kmaehashi** [comment]
@metya We now provide Python 3.7 wheels, hope you enjoy!
