### ISSUE TITLE
Compatibility with DeviceNDArray from Numba

### ISSUE THREAD

**Issue by randyzwitch** [cupy/cupy#1720]
When using pygdf, there is a method `as_gpu_matrix()` which returns `numba.cuda.cudadrv.devicearray.DeviceNDArray`. As far as I can tell, DeviceNDArray can't be used directly in CuPy. 

Can this support be added? As it stands now, DeviceNDArray is pretty sparse in methods, being able to use CuPy without needing to do a roundtrip to the host would be super-helpful.

**Comment by kmaehashi** [comment]
Implemented in #1760.
