### ISSUE TITLE
Add einops to projects using cupy

### ISSUE THREAD

**Issue by arogozhnikov** [cupy/cupy#1800]
`einops` is a new way to manipulate tensors, flexible and powerful operations for readable and reliable code. 

<img src="http://arogozhnikov.github.io/images/einops/einops_video.gif" alt="einops package examples" width='600' />

Among its backends it supports `cupy` (full support), so could we add `einops` it to the list of software using cupy?

Link to the project: http://github.com/arogozhnikov/einops

I discovered zero bugs and zero problems when developing for cupy. Thanks for writing high-quality code!

**Comment by kmaehashi** [comment]
Thanks for using CuPy!
I've updated the list of projects using CuPy. https://github.com/cupy/cupy/wiki/Projects-using-CuPy
