### ISSUE TITLE
Using cuda textures with RawKernel

### ISSUE THREAD

**Issue by clemisch** [cupy/cupy#1811]
I want to use texture objects [1] and according fetchers [2] in my kernel (called with `cp.RawKernel`). 

Normally, one constructs the necessary data structures in the host C-code and passes them to the kernel. Is there a possibility to do this in pure `cupy`? (I'm using `cupy` to avoid writing intermediate C-code in the first place) 

[1] https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#texture-object-api
[2] https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#tex3d-object

**Comment by clemisch** [comment]
Dear cupy-team, is this not possible ATM or generally "impossible" to implement? I'm sorry if my first post sounded a bit impolite.

**Comment by kmaehashi** [comment]
Thanks for the request. Currently we use NVRTC to compile the code passed to RawKernel, which only accepts device code (unlike nvcc). So you can't call such APIs in RawKernel at the moment.
https://docs.nvidia.com/cuda/nvrtc/index.html#language

However I think such APIs can be exposed as a Python function by adding signatures in 
https://github.com/cupy/cupy/blob/master/cupy/cuda/runtime.pyx

**Comment by clemisch** [comment]
Thanks for the info @kmaehashi. I'll have a look at `runtime.pyx` and see what I can implement myself. I reckon this would be quite complicated?

**Comment by kmaehashi** [comment]
I think it's basically simple (add python-layer wrapper function for CUDA API), but you may need some knowledge of Cython.
