### ISSUE TITLE
easier way to query device attributes?

### ISSUE THREAD

**Issue by grlee77** [cupy/cupy#1867]
I was curious if there is interest in adding a more user-friendly way to retrieve device attributes such as MAX_THREADS_PER_BLOCK, MAX_GRID_DIM_X, etc. In CUDA 9.2/CUDA 10 there are 101 such attributes defined in `cuda.h`. 

It seems that these can already be retrieved via `cupy.cuda.runtime.deviceGetAttribute`, but one needs to know the appropriate enum value for each attribute of interest.

Is there any interest in adding a function that would return the values of all available attributes as a dict or other similar structure that is more user-friendly?

A basic solution I came up with was to copy enum values from `cuda.h` into one of the cython files like `runtime.pxd`.  If there is interest I can make a PR.

e.g.
```cython
cpdef enum:
    CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_BLOCK = 1              # Maximum number of threads per block
    CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_X = 2                    # Maximum block dimension X
    CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Y = 3                    # Maximum block dimension Y
    CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Z = 4                    # Maximum block dimension Z
    CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_X = 5                     # Maximum grid dimension X
    CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Y = 6                     # Maximum grid dimension Y
    CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Z = 7                     # Maximum grid dimension Z
    CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK = 8        # Maximum shared memory available per block in bytes
```
etc.

Then a convenience function similar to the following would create a `dict` with attribute names as the keys.
```python

def get_attributes_dict(device_id):
    """Return a dict containing all device attributes."""
    d = {}
    for k, v in runtime.__dict__.items():
        if 'CU_DEVICE_ATTRIBUTE' in k:
            try:
                name = k.replace('CU_DEVICE_ATTRIBUTE_', '')
                d[name] = runtime.deviceGetAttribute(v, device_id)
            except runtime.CUDARuntimeError:
                pass
    return d
```
(the except case is necessary to skip any attributes that were undefined in older CUDA versions)

The output of the function is a dict such as:
```python
{ 'MAX_THREADS_PER_BLOCK': 1024,
  'MAX_BLOCK_DIM_X': 1024,
  'MAX_BLOCK_DIM_Y': 1024,
  'MAX_BLOCK_DIM_Z': 64,
  'MAX_GRID_DIM_X': 2147483647,
  'MAX_GRID_DIM_Y': 65535,
  'MAX_GRID_DIM_Z': 65535,
  'MAX_SHARED_MEMORY_PER_BLOCK': 49152,
...

**Comment by kmaehashi** [comment]
> A basic solution I came up with was to copy enum values from cuda.h into one of the cython files like runtime.pxd. If there is interest I can make a PR.

Such PR is welcomed. Note that constant names should be in form of `devAttrMaxThreadsPerBlock` instead of `CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_BLOCK` as defined in Runtime API.
https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g49e2f8c2c0bd6fe264f2fc970912e5cd

As for the `get_attributes_dict`, I think it sounds make sense to add it to `cupy.cuda.Device` like this:

```
@property
def attributes(self):
    return get_attributes_dict(self.id)
```

(maybe it's better to memoize `get_attributes_dict`)
