### ISSUE TITLE
Incorrect result for complex matrix inversion

### ISSUE THREAD

**Issue by AgVeraneno** [cupy/cupy#1903]
I'm trying to use cupy for some complex matrix inversion, but it seems the function does not support complex number.

Conditions:
CuPy Version          : 5.1.0
CUDA Root             : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
CUDA Build Version    : 10000
CUDA Driver Version   : 10000
CUDA Runtime Version  : 10000
cuDNN Build Version   : None
cuDNN Version         : None
NCCL Build Version    : None

I just use some simple example for test such as,
`import cupy as cp; a = cp.array([[1,0],[0,1]]).astype(cp.float64); a_inv = cp.linalg.inv(a); print(a_inv)`
`>>> [[1., 0.],[0., 1.]]`
the output looks fine for float64 type, but when I change the type to complex128, the output goes wrong:
`import cupy as cp; a = cp.array([[1,0],[0,1]]).astype(cp.complex128); a_inv = cp.linalg.inv(a); print(a_inv)`
`>>> [[nan+nanj nan+nanj],[ 0. +0.j  1. +0.j]]`

Any suggestion?

**Comment by grlee77** [comment]
CuPy supports complex-valued arrays in many places, but it looks like `cp.linalg.inv` currently does not. It always calls either single or double precision real CUSOLVER routines.
see for example:
https://github.com/cupy/cupy/blob/master/cupy/linalg/solve.py#L206-L213

There are complex versions of the needed `getrf` and `getrs` routines [available in CUSOLVER](https://docs.nvidia.com/cuda/cusolver/index.html#cuds-lt-t-gt-getrf), so it shouldn't be too hard to add complex support in CuPy. The necessary functions would just need to be added alongside the real-valued ones here:
https://github.com/cupy/cupy/blob/master/cupy/cuda/cusolver.pyx#L48-L67
and then the python code in the first link above should add cases for complex floats well.

There is currently a similar limitation in dtype support for at least some of the other `linalg` functions as well.

**Comment by AgVeraneno** [comment]
Thanks for replying.
I think I can add the complex support manually.
Much appreciate.
