### ISSUE TITLE
Memo option on cupy.fuse

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#191]
I post this from https://github.com/cupy/cupy/pull/43#issuecomment-301677303.

It would be nice if there were a @fuse(cached=True) or @fuse_cached which enables the kernel generated by one call to the function to be reused for another call.

**Comment by asi1024** [comment]
@takagi `cupy.fuse` memoizes generated kernels as default now. Currently, the cache key is dtypes and ndims of given arguments.

**Comment by takagi** [comment]
Great! I close this issue.
