### ISSUE TITLE
pytest --strict fails when cupy is used in the test suite due to marker

### ISSUE THREAD

**Issue by stas00** [cupy/cupy#1917]
```
$ pip install cupy
$ cat tests/test_marker.py
import pytest, cupy
```

```
pytest --strict tests/test_marker.py
______ ERROR collecting tests/test_marker.py ___________
'cudnn' not a registered marker
```

it comes from https://github.com/cupy/cupy/blob/master/cupy/testing/attr.py#L31
```
cudnn = pytest.mark.cudnn
```

I tried to add the files/folders defining it to `collect_ignore` and `norecursedirs`, to no avail.

We have no control over `cupy` and currently are unable to use `--strict` because of it. 

The only workaround I found working is adding to `config.cfg`'s `pytest` section:
```
markers =
    cudnn: cupy's marker, ignore it
```

I thought something could have been done on the pytest side, so I filed:
https://github.com/pytest-dev/pytest/issues/4581
and their reply was that you need to fix it in cupy:

> We plan to make strict the default in future
> Cupy should declare a pytest plugin that uses addinilines to declare the marker

pytest-4.0.2, cupy-5.1.0

Thank you.

**Comment by kmaehashi** [comment]
Thanks, will be fixed in #2055.
