### ISSUE TITLE
How to write a cuda kernel function that performs a regression for each thread?

### ISSUE THREAD

**Issue by zengxiaoqing** [cupy/cupy#1919]
I have 1 million points, each with 30 samples and 2 features. I want to use the @cuda.jit function in numba to model the regression model for each point.

That is, using a least squares method at each point (each thread in cuda) to create a regression model,

The result returns one million regression model coefficients, two features with three coefficients (including constant terms)

I don't know if I can solve the above problem.

**Comment by fiarabbit** [comment]
According to the [contribution guide](https://docs-cupy.chainer.org/en/stable/contribution.html), any general question is preferred to be raised at the StackOverflow with a cupy tag.

```
Warning

If you have a question on usages of CuPy, it is highly recommended to send a post to CuPy User
Group instead of the issue tracker. The issue tracker is not a place to share knowledge on practices.
We may suggest these places and immediately close how-to question issues.
```

**Comment by fiarabbit** [comment]
This question is also raised in [StackOverflow](https://stackoverflow.com/questions/54038574/how-to-write-a-cuda-kernel-function-that-performs-a-regression-least-square-esti).
