### ISSUE TITLE
multiple outputs from ReductionKernel

### ISSUE THREAD

**Issue by kylemcdonald** [cupy/cupy#1924]
Hi! I would like to make a feature request for multiple outputs from ReductionKernel. Here is a simple but complete example:

```python
import cupy as cp
preamble = '''
struct min_max_st{
    T value;
    int index;
    __device__ min_max_st() : index(-1) { }
    __device__ min_max_st(T v) : value(v), index(0) { }
    __device__ min_max_st(T v, int i) : value(v), index(i) { }
};
__device__ min_max_st my_argmax(const min_max_st& a, const min_max_st& b) {
    if (a.index == -1) return b;
    if (b.index == -1) return a;
    return (a.value >= b.value) ? a : b;
}'''
argmax = cp.ReductionKernel(
    'T x',  # input params
    'int32 y, T z',  # output params
    'min_max_st(x, _J)',  # map
    'my_argmax(a, b)',  # reduce
    'y = a.index, z = a.value',  # post-reduction map
    '0',  # identity value
    'argmax',  # kernel name
    'min_max_st', # reduce type
    preamble=preamble
)
x = cp.asarray([[3,0,0,0],[0,4,0,0],[0,0,5,0]]).astype(cp.float32)
print(argmax(x, axis=1))
```

Right now the output is `array([0, 1, 2], dtype=int32)` but I wish there could be `(array([0, 1, 2], dtype=int32), array([3., 4., 5.], dtype=float32))`. Maybe this is already the plan for cupy, because the documentation says "Arrays are returned according to the ``out_params`` argument of the ``__init__`` method." This specific case above can be accomplished very quickly in other ways, but I have a very slow part of my code that would be faster if it was in a single kernel. It computes the argmax along each row, and the second largest argmax, and returns the index and the difference in value:

```python
def argmax_gamma(x):
	xi = x.argmax(axis=1)
	ii = cp.arange(len(x))
	max1 = cp.copy(x[ii, xi])
	x[ii, xi] -= 10000000
	max2 = x.max(axis=1)
	gamma = max1 - max2
	return max1, gamma
```

I tried to write my own kernel with RawKernel but I ran into some memory errors, so it would be amazing if I could just write this using ReductionKernel instead 🙏

**Comment by asi1024** [comment]
We won't support multiple outputs for ReductionKernel. Please use `cupyx.jit` instead with CUB reduction.
