### ISSUE TITLE
Avoid passing vectors by value

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#1932]
Many Cython functions in CuPy have pass-by-value `vector.vector[]` arguments, which could incur extra overhead of copy (not sure how significant though).
They can be simply replaced with `const vector.vector[]&`.

**Comment by kmaehashi** [comment]
Remainings: https://github.com/cupy/cupy/pull/2008#issue-250998035

**Comment by kmaehashi** [comment]
I think everything is now fixed.
