### ISSUE TITLE
[Feature Request]_fftn for R2C

### ISSUE THREAD

**Issue by fiarabbit** [cupy/cupy#1936]
I'm working on the implementation of STFT, and I think `cuFFTPlanMany` is a good API to implement it. Fortunately, in `cupy.cuda.cufft.PlanNd` is already implemented as the corresponding API, but in `cupy.fft.fft.get_cufft_plan_nd` only allows C2C and Z2Z.

Is there any reason for it? Thanks!

**Comment by grlee77** [comment]
I wrote the logic in that function for an application that only needed complex transforms, but agree that it would be nice to add support for C2R, R2C, D2Z and Z2D as well.  It looks like `cuFFTPlanMany` supports those transform types, so it should be possible.

The following table should have the necessary info to modify the stride calculations:
https://docs.nvidia.com/cuda/cufft/index.html#multi-dimensional

It may also be possible to reuse some of the logic from the 1D planning/transform routines that already support these variants.

Is this something you might be interested in working on?

**Comment by fiarabbit** [comment]
Yes, thank you very much. I will try to modify the function. Thanks again!

**Comment by leofang** [comment]
@fiarabbit If you're going to work on this, I suggest to reopen this issue and only close it until it has been addressed (ex: after a PR is merged).

**Comment by grlee77** [comment]
Hi @fiarabbit, just wanted to check if this is still something you are actively working on (or plan to make a PR for in the future)?

**Comment by fiarabbit** [comment]
@grlee77 I'm very sorry that I had to do other jobs. I have not yet begun to do anything...

**Comment by leofang** [comment]
See #3102.
