### ISSUE TITLE
Could ElementWise Kernel output an array of float32?

### ISSUE THREAD

**Issue by tim37021** [cupy/cupy#1954]
Is it possible to output float4 with ElementWise kernel?

inputs: float32 u, float32 v
output: float32 color[4]?
operations:
color[0] = 0  //B
color[1] = v  // G
color[2] = u  //R
color[3] = 1 //A

u = cp.asarray([800, 600, 1], dtype=cp.float32)
v = cp.asarray([800, 600, 1], dtype=cp.float32)

color = cp.asarray([800, 600, 4], dtype=cp.float32)

**Comment by tim37021** [comment]
It can be simply done by using raw kernel.
```python
shader = cp.RawKernel(r'''
extern "C" __global__
void shader(const float* u, const float* v, float* y) {
    int tid = blockDim.x * blockIdx.x + threadIdx.x;
    y[tid*3] = 0;
    y[tid*3+1] = v[tid];
    y[tid*3+2] = u[tid];
}
''', 'shader')
```
![image](https://user-images.githubusercontent.com/5507113/51099573-8dd91880-180c-11e9-9b9a-c5c68f3d66ff.png)

**Comment by fiarabbit** [comment]
According to the [contribution guide](https://docs-cupy.chainer.org/en/stable/contribution.html), any general question is preferred to be raised at the StackOverflow with a cupy tag.

```
Warning

If you have a question on usages of CuPy, it is highly recommended to send a post to CuPy User
Group instead of the issue tracker. The issue tracker is not a place to share knowledge on practices.
We may suggest these places and immediately close how-to question issues.
```

By the way, this could be done by `ElementwiseKernel` and even no any special kernels.
ElementwiseKernel version
```elementwise.py
import cupy as cp
from cupy import ElementwiseKernel


shader = ElementwiseKernel(
    in_params='raw float32 u, raw float32 v',
    out_params='raw float32 y',
    operation=\
    '''
    y[i] = 0;
    y[i * 3 + 1] = v[i];
    y[i * 3 + 2] = u[i];    
    ''',
    name='shader'
)
u = cp.arange(6, dtype=cp.float32)
v = cp.arange(6, dtype=cp.float32) * 2
y = cp.empty((18,), dtype=cp.float32)
shader(u, v, y, size=y.size)
print(y)
```

No special kernel version
```nospecial.py
u = cp.arange(6, dtype=cp.float32)
v = cp.arange(6, dtype=cp.float32) * 2
y = cp.vstack((cp.zeros(u.shape), v, u)).T.ravel()
print(y)
```

**Comment by kmaehashi** [comment]
@fiarabbit Thanks for the help!

@tim37021 Please comment if you need further help.
