### ISSUE TITLE
Support parallel compile in installing time

### ISSUE THREAD

**Issue by okuta** [cupy/cupy#1961]
Please read [this](https://stackoverflow.com/questions/38013863/how-to-perform-cython-files-compilation-in-parallel/40533012#40533012).

**Comment by leofang** [comment]
It'd be great to have this ability. Building CuPy from source takes so long and it's not good for both developers and CI infrastructures.

**Comment by kmaehashi** [comment]
It's worth trying, but the merit of parallelization may be limited by Thrust module.
In my environment, full build took 548.98s (thrust module = 373.36s, all the rest = 175.62s).

**Comment by leofang** [comment]
Both the Thrust and CUB modules will take the majority of time due to template instantiation...I wonder if we can assign two independent processes to handle them, or even apply some tricks to speed it up.

**Comment by kmaehashi** [comment]
I guess you are already aware of, but using `ccache` significantly improves build time.
https://docs-cupy.chainer.org/en/latest/contribution.html#how-to-run-tests

**Comment by leofang** [comment]
Just saw cython/cython#3187. It seems starting Cython 0.29.14 it is possible to build Cython modules in parallel, but I have not tested this capability yet.

**Comment by leofang** [comment]
> Just saw [cython/cython#3187](https://github.com/cython/cython/pull/3187). It seems starting Cython 0.29.14 it is possible to build Cython modules in parallel, but I have not tested this capability yet.

It seems Pandas tested this capability in their CI and found improvement: pandas-dev/pandas#30214.

**Comment by leofang** [comment]
The parallel build mentioned above is really fast! https://github.com/cupy/cupy/issues/3600#issuecomment-663702728
