### ISSUE TITLE
Memory layout of `cupy.cuda.runtime._PointerAttributes` struct is incorrect

### ISSUE THREAD

**Issue by asi1024** [cupy/cupy#1969]
Currently, The order of member variables of `cupy.cuda.runtime._PointerAttributes` is incorrect at least since CUDA 8.
Additionally, the definition of `cudaPointerAttributes` has changed from CUDA 10.0.

**Comment by leofang** [comment]
@asi1024 could you confirm if this is fixed? Last time I checked the struct (some time between v7.0.0b4 and v7.0.0rc1) it looked fine to me.

**Comment by asi1024** [comment]
I confirmed. Thanks!
