### ISSUE TITLE
The `overwrite_x` argument of FFT functions is deceptive in certain conditions

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#1988]
In the current master branch, several functions in `cupy.scipy.fftpack` support the argument `overwrite_x` as requested by me earlier (#1669). Ideally, one would expect that after executing the following line
```python
cupy.scipy.fftpack.fft(a, overwrite_x=True)
```
the input array `a` is correctly transformed **in place** (meaning `a=cupy.fft.fft(a)` but without extra allocation).

However, this expectation is not always true. Consider this example when `a` has more than 1 axis and we are transforming along an axis not the last one:
```python
a = cupy.random.random((10, 10)).astype(cupy.complex128)
cupy.scipy.fftpack.fft(a, axis=0, overwrite_x=True)
```
In this case, internally we do a swap followed by a copy (i.e. allocate a new array):
https://github.com/cupy/cupy/blob/f4acb4e86c64bf0239f8f25418bc301d63a92ead/cupy/fft/fft.py#L76-L80
So in the end with `overwrite_x=True` we return the reference to the new array, not the input array. This means that after the operation above `a` does not really hold the correctly transformed result (i.e. the result is not the same as `a=cupy.fft.fft(a, axis=0)` or its NumPy equivalent) because it's the copied array that got transformed.

I can think of two workarounds now. The first one is simpler but counter-intuitive: we just advocate the following usage
```python
a = cupy.scipy.fftpack.fft(a, axis=whatever, overwrite_x=True)
```
which will always be correct. The second one is to swap the pointers after copy:
```python 
if a.base is not None or not a.flags.c_contiguous: 
    b = a.copy() 
    if overwrite_x:
        temp = a.data
        a.data = b.data
        b.data = temp
    else:
        a = b
```
so that the expected usage can work. However, neither workarounds can truly avoid a copy, which could cause performance penalty and require extra memory merely for accommodating the intermediate step. 

If I remember it correctly, all FFT functions (1d, 2d, 3d) are affected, not just `cupy.scipy.fftpack.fft`, but I haven't looked into the call paths for other cases carefully.

**Comment by leofang** [comment]
@grlee77 @not522 would this be a real concern for you?

**Comment by leofang** [comment]
@not522 thanks for your reply. You're right, I found SciPy's references: https://github.com/scipy/scipy/issues/8500 and https://github.com/scipy/scipy/issues/2155. Clearly this is not at all documented and the SciPy people may update docstrings and whatnot in the future to reflect this subtlety.

However, from the GPU users' point of view I think we can do much better. There SciPy was limited by the way its internal and the underlying FFT library work (see the discussion in the links above). But we do *not* have such limitation: the way CuPy works could in principle make `x` always overwritten when `overwrite_x=True` (see my 2nd workaround above). Given that SciPy does not document this at all, I propose that we make `overwrite_x` work more intuitively on the CuPy side.

**Comment by not522** [comment]
Do you think "`x` can be destroyed" is not enough? This doesn't say the output is stored as `x`.  As a general practice as NumPy, parameter `out` is provided as preallocated output array.
https://docs.scipy.org/doc/scipy/reference/generated/scipy.fftpack.fft.html

**Comment by leofang** [comment]
@not522 While I agree with you about the general NumPy practice, I hope you don't mind me reminding you (and those who find this discussion later) that the motivation of introducing SciPy's `overwrite_x` to CuPy was because we (at least I 😄) needed ***in-place*** FFT for performance reasons (see #1669). By "in-place" it is clear that `overwrite_x` has to stick to its literal meaning, otherwise we do not really resolve that issue. So, yes, "`x` can be destroyed" is unfortunately not enough in this regard.

**Comment by grlee77** [comment]
I think I would just advocate for the user to always use. 
```python
a = cupy.scipy.fftpack.fft(a, axis=whatever, overwrite_x=True)
```

I think of `overwrite_x` as similar to the flag `FFTW_DESTROY_INPUT` in the FFTW library, which is also not equivalent to enforcing an in-place transform.

Isn't the above usage still doing the in-place transform you desire as long as the input has the correct contiguity and dimensions? The 2nd solution you propose still doesn't prevent a copy when those assumptions aren't met, so I don't see what the benefit is aside from allowing the user to exclude `a = `?

**Comment by leofang** [comment]
> Isn't the above usage still doing the in-place transform you desire as long as the input has the correct contiguity and dimensions? 

This is indeed correct. I didn't think in this way.

> The 2nd solution you propose still doesn't prevent a copy when those assumptions aren't met, so I don't see what the benefit is aside from allowing the user to exclude `a = `?

Allowing the user to *ignore* `a = ` (i.e. one can opt for `a = ` or don't, the results are identical) seems much more intuitive to me. The (SciPy) interpretation that "`overwrite_x` can (but not always) destroy `x`" is kinda confusing to users who don't know how the underlying FFT library works (see the linked SciPy issues). I don't mind deviating from SciPy if it can make the intended usage self-evident, although I also understand the desire to maintain a compatible API.

If you both think this is not a problem, I will just make a PR to document the advocated usage. Sounds good?
