### ISSUE TITLE
Support ncclGetVersion

### ISSUE THREAD

**Issue by kuenishi** [cupy/cupy#1994]
NCCL 2.3.4 added new function `ncclGetVersion` and the macro `NCCL_VERSION` has become a macro function in `nccl.h` since then. `cupy_nccl.h` should be updated and the macro in cupy should be removed.
c.f. https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/rel_2.3.4.html#rel_2.3.4

**Comment by kmaehashi** [comment]
https://github.com/cupy/cupy/pull/1985 implements this :)

**Comment by kuenishi** [comment]
Thanks~
