### ISSUE TITLE
Inconsistency between README and Installation Guide

### ISSUE THREAD

**Issue by delta2323** [cupy/cupy#200]
Both `README.md` and [Installation Guide](https://docs-cupy.chainer.org/en/stable/install.html) include how to install CuPy, but they are inconsistent in at least

* The latter mentions `CUDA_PATH`, whereas the former not.
* The former instructs to set `PATH` and `LD_LIBRARY_PATH` to enable CUDA, whereas the latter not.

**Comment by okuta** [comment]
What do you mean? Cloud you send PR?

**Comment by delta2323** [comment]
At the time I wrote this issue, `README.md` had another installation instruction, which has different information from the [installation guide](https://docs-cupy.chainer.org/en/stable/install.html). As the instruction in `README.md` has been removed by #334, there isn't inconsistency any longer. But I would like to check if we need not to add information originally in the README to the installation guide (e.g. setting of `PATH` and `LD_LIBRARY`).

**Comment by not522** [comment]
Currently, CuPy is recommended installing using wheel (e.g. `pip install cupy-cuda**`). How about following this in README and https://cupy.chainer.org?

**Comment by kmaehashi** [comment]
@not522 Sounds nice.

**Comment by kmaehashi** [comment]
Fixed via #1208.
