### ISSUE TITLE
Support for Nvidia Tesla T4

### ISSUE THREAD

**Issue by gautamkmr** [cupy/cupy#2002]
Feature request

Current Cupy build doesn't include Tesla T4. 
https://github.com/cupy/cupy/blob/master/cupy_setup_build.py#L633. It would be great if we have support for T4 as well. I believe this architecture is more for inference than training but still a good use case to consider.
I believe it has to accommodate Tesla T4 by supporting cuda compute ability 7.5

**Comment by bhavinthaker** [comment]
What is the expected date/release by which Nvidia Tesla T4 support will be added?

**Comment by kmaehashi** [comment]
@bhavinthaker It is planned to be included to the release in this month. Note that current versions of  `cupy-cuda100` should run on T4 (but it uses `compute_70`).
