### ISSUE TITLE
Update setup.py and related scripts for NVRTC support.

### ISSUE THREAD

**Issue by delta2323** [cupy/cupy#201]
Although we have switched from NVCC to NVRTC to compile kernels, CuPy searches for NVCC modules in its installation in `setup.py` and related scripts. We need to update them and corresponding [installation document](https://docs-cupy.chainer.org/en/stable/install.html#install-cupy-with-cuda).

**Comment by takagi** [comment]
NVCC is still in use for Thrust support. Setup scripts build `cupy.cuda.thrust` module in terms of NVCC.
