### ISSUE TITLE
using CuPy is slower than using NumPy

### ISSUE THREAD

**Issue by smajida** [cupy/cupy#2025]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
CuPy Version          : 4.1.0
CUDA Root             : /usr/local/cuda-9.0
CUDA Build Version    : 9000
CUDA Driver Version   : 9020
CUDA Runtime Version  : 9000
cuDNN Build Version   : 7104
cuDNN Version         : 7103
NCCL Build Version    : 1000

* Code to reproduce
import cupy as cp
import numpy as np
import time
from shapely.geometry import Polygon as shp
start = time.time()
polygon1 = shp(np.array([0, 0, 2, 0, 2, 1, 0, 1]).reshape(4, 2)).convex_hull
polygon2 = shp(np.array([0, 0, 1, 0, 1, 2, 0, 2]).reshape(4, 2)).convex_hull
inter_area =polygon1.intersection(polygon2).area
print("CPU implementation took: {}".format(time.time() - start))

start = time.time()
polygon1 = shp(cp.array([0, 0, 2, 0, 2, 1, 0, 1]).reshape(4, 2)).convex_hull
polygon2 = shp(cp.array([0, 0, 1, 0, 1, 2, 0, 2]).reshape(4, 2)).convex_hull
inter_area =polygon1.intersection(polygon2).area
print("GPU implementation took: {}".format(time.time() - start))

* Error messages, stack traces, or logs
CPU implementation took: 0.025589942932128906
GPU implementation took: 0.895662784576416

**Comment by kmaehashi** [comment]
GPU computations are *not always* guaranteed to be faster than CPU.
In your use-case I guess your dataset is too small and most of time is consumed by overhead of GPU use (CUDA initialization, memory transfer, kernel invocation, etc.).
