### ISSUE TITLE
duplicate declaration of cudaMalloc in runtime.pyx?

### ISSUE THREAD

**Issue by grlee77** [cupy/cupy#2027]
I happened to notice that `cudaMalloc` is declared twice in runtime.pyx.  Is this a mistake? (One of the declarations is `nogil` while the other is not). I am unclear on what the expected Cython behavior is in this case.

https://github.com/cupy/cupy/blob/bf9a82855147e213c525b4bfcb3297c2addf11c0/cupy/cuda/runtime.pyx#L71-L77

Should many of the other functions such as `cudaMallocManaged` in that section also be declared with `nogil`? Many are later called within a `with nogil:` context.

**Comment by grlee77** [comment]
To answer the second question, I just found the following in the Cython docs:

```Declaring a function with gil (i.e. as acquiring the GIL on entry) also implicitly makes its signature nogil.```

So, we could add `nogil` to the declarations for clarity, but it is not required. 

I assume we can just remove the duplicate cudaMalloc entry without consequence as well.

**Comment by grlee77** [comment]
actually I think I misread the Cython docs and it is still not entirely clear to me. Clearly the functions work without the gil as they are being used within `with nogil` blocks, but I'm not sure if that also implicitly add `nogil` to the declarations?

**Comment by kmaehashi** [comment]
Thanks for heads-up, the second declaration can be removed. Could you make a PR?

All CUDA APIs can be called without GIL, and is already marked as `nogil` here:
https://github.com/cupy/cupy/blob/bf9a82855147e213c525b4bfcb3297c2addf11c0/cupy/cuda/runtime.pyx#L41

**Comment by grlee77** [comment]
Thanks, I understand now where `nogil` is being set.  I have opened a PR to remove the duplicate.
