### ISSUE TITLE
Handling unimplemented methods from NumPy-like libraries

### ISSUE THREAD

**Issue by pentschev** [cupy/cupy#2030]
This is just to open the discussion on this topic. After NEP-18, Dask will be capable of working on arrays from NumPy-like libraries, e.g., CuPy. For such unimplemented methods, such as `argtopk()` and `take_along_axis()` (a dependency of the former), a TypeError will simply be emitted:

```python
TypeError: no implementation found for 'numpy.take_along_axis' on types that implement __array_function__: [<class 'cupy.core.core.ndarray'>]
```

I think a discussion on handling this case is important for the near future.

@mrocklin

**Comment by pentschev** [comment]
Mistakenly opened here by accident, this is part of Dask. My apologies.

**Comment by mrocklin** [comment]
This was moved to https://github.com/dask/dask/issues/4462

CuPy maintainers want to track that issue.   It is about Dask/CuPy interactions after NEP-18
