### ISSUE TITLE
cupy.random.gamma returns the same values.

### ISSUE THREAD

**Issue by yoshipon** [cupy/cupy#2032]
After the 2nd call of the `cupy.random.gamma` function, it always returns the same value as follows.
Does anyone know the reason why this happens?

* Code to reproduce
   ```
   import cupy as cp

   print(cp.random.gamma(1, 1)) 
   print(cp.random.gamma(1, 1)) 
   print(cp.random.gamma(1, 1)) 
   print(cp.random.gamma(1, 1)) 
   ```
   ```
   0.7588770516300537
   2.2603186238781365
   2.2603186238781365
   2.2603186238781365
   ```
   (Edited: I pasted the wrong results)
* Conditions:
  - CuPy version: 5.0.0
  - OS/Platform: Ubuntu 16.04, Python 3.7.0
  - CUDA version: 9.2

**Comment by crcrpar** [comment]
**This is not the answer.**

I checked this phenomenon also happened in my environment.
But I found this could be avoided by setting random seed.

```bash
Python 3.6.6 (default, Dec 20 2018, 14:31:26)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import cupy; print(cupy.__version__)
6.0.0b2

In [2]: cupy.random.gamma(1, 1)  # Reproduce the phenomenon you found.
Out[2]: array(2.18394268)

In [3]: cupy.random.gamma(1, 1)
Out[3]: array(0.35274883)

In [4]: cupy.random.gamma(1, 1)
Out[4]: array(0.35274883)

In [5]: cupy.random.gamma(1, 1)
Out[5]: array(0.35274883)

In [6]: cupy.random.gamma(1, 1)
Out[6]: array(0.35274883)

In [7]: cupy.random.seed(42)  # set random seed here

In [8]: cupy.random.gamma(1, 1)
Out[8]: array(0.05074151)

In [9]: cupy.random.gamma(1, 1)
Out[9]: array(0.51184208)

In [10]: cupy.random.gamma(1, 1)
Out[10]: array(0.12552692)

In [11]: cupy.random.gamma(1, 1)
Out[11]: array(3.36554147)

In [12]: cupy.random.gamma(1, 1)
Out[12]: array(3.20557046)
```

**Comment by fiarabbit** [comment]
This is very simple bug.

`cupy.random.generator.RandomState` internally has a seed (key) for a hash function as `.rk_seed`.

However, the initial value is set very huge `float64`, and `rk_seed` is refreshed by adding `1` (or the number of sample drawn), the `rk_seed` is not refreshed actually.
