### ISSUE TITLE
cupy.linalg.inv failed for Large Complex Matrix

### ISSUE THREAD

**Issue by jlapin1** [cupy/cupy#2071]
Hello cupy users and developers

I am currently attempting to write GPU compatible code that can find the exponential of a Complex matrix that is ~4000 x 4000, using the Pade algorithm. If I use the cupy.linalg.inv function on a cupy array of that size, it gets the wrong answer. The result is all zeros past index 500 in each of the two dimensions, so it would seem the algorithm is malfunctioning.

I noticed it works for real matrices of that size, and I have attempted to solve the problem by decomposing the complex matrix into its real and imaginary components. The final results are mixed since this method requires much more memory to be allocated on GPU, which I don't really have room for with matrices this size.

Can anyone help me find the solution to this problem of finding the exponential of a very large complex matrix?

Thank you in advance!
-Joel

**Comment by msakai** [comment]
It seems that `cupy.linalg.inv` does not support complex number types yet, as it uses only functions for float32 and float64.

https://github.com/cupy/cupy/blob/f85374d9ab3d404dc74e196e7791e8ed84c9ad9e/cupy/linalg/solve.py#L206-L214

But cuSOLVER provides complex number versions of these functions.
https://docs.nvidia.com/cuda/cusolver/index.html#cuds-lt-t-gt-getrf

So I guess that it is not difficult to extend `cupy.linalg.inv` to support complex number types.
