### ISSUE TITLE
`TestCholeskyDecomposition` often fails

### ISSUE THREAD

**Issue by toslunar** [cupy/cupy#2083]
In my environment, `TestCholeskyDecomposition` seems to fail with probability >1%.  I found this when I checked results of daily tests.

**Comment by chengts95** [comment]
I think there are 2 possible reasons, one is that the matrix is not positive definite, another is the difference between GPU and CPU algorithm.   I think the code cannot guarantee a positive definite test matrix. https://github.com/cupy/cupy/blob/2146ce2949c339126d2cdd8feb0af4da8313de5b/tests/cupy_tests/linalg_tests/test_decomposition.py#L28
