### ISSUE TITLE
`max` and `min` for float32 cupy array may be slow 

### ISSUE THREAD

**Issue by xu3kev** [cupy/cupy#2085]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version = commit 2146ce2949c339126d2cdd8feb0af4da8313de5b
  - OS/Platform = Ubuntu 16.04/ V100
  - CUDA version = 10.0
* Code to reproduce
```python
import cupy as cp
from contextlib import contextmanager

@contextmanager
def sync_time(name):
    start = cp.cuda.Event()
    end = cp.cuda.Event()
    start.record()
    start.synchronize()
    yield
    end.record()
    end.synchronize()
    t = cp.cuda.get_elapsed_time(start,end)
    print("{} : {} ms".format(name,t))

x = cp.random.normal(size=((400, 32, 28, 28))).astype(cp.float32)

with sync_time("cupy"):
    for i in range(1000):
        x.max()

x = cp.asnumpy(x) #move to cpu

with sync_time("numpy"):
    for i in range(1000):
        x.max()
```
*  Results
```
cupy : 8457.2451171875 ms
numpy : 3005.8154296875 ms
```
In this case, Cupy is slower then Numpy.

**Comment by anaruse** [comment]
"reduction" operations including "max" and "min" in cupy are currently implemented in rather general way and are not so optimized in terms of performance, as far as I know. You may be able to get better performance by using some reduction implementation in cuDNN, CUB or Thrust, though those are not used in cupy for now.

CuPy team:  Is anyone already working on performance improvement of "reduction" operations? I'm considering to speed up cupy reductions with CUB. Is there any concerns on use of CUB in cupy?

**Comment by samrere** [comment]
Hi, as of April/2022, cupy `max` is still much slower than numpy:
```
cupy : 8153.27001953125 ms
numpy : 2700.735595703125 ms
```
May I please get more information on what may be a workaround? Thanks
