### ISSUE TITLE
[BUG] DLPack implementation doesn't handle nullptr for strides

### ISSUE THREAD

**Issue by kkraus14** [cupy/cupy#2095]
According to DLPack spec if the strides attribute is NULL it indicates a dense tensor (https://github.com/dmlc/dlpack/blob/master/include/dlpack/dlpack.h#L142).

The current implementation in cupy will cause a segfault if `mem.dlm_tensor.dl_tensor.strides` is null as it will try to index into it (https://github.com/cupy/cupy/blob/v6.0.0b3/cupy/core/dlpack.pyx#L236).

**Comment by kmaehashi** [comment]
Thanks for pointing this out!
Just out of curiosity, do you know any framework that uses `strides == NULL`?

**Comment by kkraus14** [comment]
> Thanks for pointing this out!
> Just out of curiosity, do you know any framework that uses `strides == NULL`?

We recently added support for DLPack in https://github.com/rapidsai/cudf/pull/1159 and originally used null pointers for dense buffers which is what led to us discovering this issue. We switched it accordingly, but I imagine others implementing DLPack based on the spec could make the same issue.

**Comment by crcrpar** [comment]
Thank you for your response very much and kudos to 
> We switched it accordingly
