### ISSUE TITLE
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

### ISSUE THREAD

**Issue by ling-pan** [cupy/cupy#2100]
Hi, I am wondering why running with cupy encounters the following error:

> cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

The detail information of the error is as below:
>   File "cupy/core/core.pyx", line 1178, in cupy.core.core.ndarray.__setitem__
>   File "cupy/core/_routines_indexing.pyx", line 49, in cupy.core._routines_indexing._ndarray_setitem
>   File "cupy/core/_routines_indexing.pyx", line 739, in cupy.core._routines_indexing._scatter_op
>   File "cupy/core/_kernel.pyx", line 851, in cupy.core._kernel.ufunc.__call__
>   File "cupy/core/_kernel.pyx", line 863, in cupy.core._kernel.ufunc._get_ufunc_kernel
>   File "cupy/core/_kernel.pyx", line 625, in cupy.core._kernel._get_ufunc_kernel
>   File "cupy/core/_kernel.pyx", line 59, in cupy.core._kernel._get_simple_elementwise_kernel
>   File "cupy/core/carray.pxi", line 164, in cupy.core.core.compile_with_cache
>   File "******/anaconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 165, in compile_with_cache
>     ptx = compile_using_nvrtc(source, options, arch, name + '.cu')
>   File "******/anaconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 81, in compile_using_nvrtc
>     ptx = prog.compile(options)
>   File "******/anaconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 246, in compile
>     raise CompileException(log, self.src, self.name, options)
> cupy.cuda.compiler.CompileException: ******/anaconda3/lib/python3.6/site-packages/cupy/core/include/cupy/carray.cuh(281): warning: statement is unreachable
>           detected during instantiation of "void CIndexer<_ndim>::set(ptrdiff_t) [with _ndim=1]"
> /tmp/******.cubin.cu(11): here
> 
> /tmp/******.cubin.cu(14): error: no suitable conversion function from "const in0_type" to "out0_type" exists
> 
> 1 error detected in the compilation of "/tmp/******.cubin.cu".

My environment information are as below:

> CuPy Version          : 6.0.0b3
> CUDA Root             : /usr/local/cuda
> CUDA Build Version    : 8000
> CUDA Driver Version   : 10010
> CUDA Runtime Version  : 8000
> cuDNN Build Version   : 7102
> cuDNN Version         : 7102
> NCCL Build Version    : 2213
> NCCL Runtime Version  : (unknown)

**Comment by ling-pan** [comment]
I have tried setting the path for cuda in ~/.bashrc, but it does not work.

**Comment by fiarabbit** [comment]
Give me more information.
1. Where do you have an error in the following code?
```hoge.py
import cupy

x = cupy.array([1., 2., 3.])
y = cupy.arange(10)
```
2. What you set in your LD_LIBRARY_PATH?
```
$ echo $LD_LIBRARY_PATH
```
3. (optional) what would happen when you use a bundled-version of cupy?
```
$ pip freeze
$ pip uninstall cupy -y
$ pip install cupy-cuda80==v6.0.0b3
$ # and do 1. again
```

**Comment by fiarabbit** [comment]
I FAILED to reproduce your situation.
```o.sh
$ echo $LD_LIBRARY_PATH
/home/hashimoto/.local/cuda/cuda-8.0/lib64
$ pip freeze
cupy==6.0.0b3
Cython==0.29.6
fastrlock==0.4
numpy==1.16.2
pkg-resources==0.0.0
six==1.12.0
```
```i.py
import cupy, cupyx

x = cupy.array([1., 2., 3.])
y = cupy.arange(10)
print(cupyx.get_runtime_info())
```
```o.py
CuPy Version          : 6.0.0b3
CUDA Root             : /home/hashimoto/.local/cuda/cuda-8.0
CUDA Build Version    : 8000
CUDA Driver Version   : 10010
CUDA Runtime Version  : 8000
cuDNN Build Version   : 7103
cuDNN Version         : 7103
NCCL Build Version    : None
NCCL Runtime Version  : None
```

@ling-pan BTW, how did you obtained cuDNN7.1.2? I think there is no release of cuDNN 7.1.2 for CUDA 8.0.

**Comment by kmaehashi** [comment]
Could you try setting `LD_LIBRARY_PATH` and `CUDA_PATH`?
https://docs-cupy.chainer.org/en/latest/install.html#cupy-always-raises-cupy-cuda-compiler-compileexception

**Comment by hanqing1** [comment]
> I FAILED to reproduce your situation, although I setup CUDA10.1 for global installation and CUDA8.0 for local cupy, and used similar version of cuDNN.
> 
> ```shell
> $ echo $LD_LIBRARY_PATH
> /home/hashimoto/.local/cuda/cuda-8.0/lib64
> $ pip freeze
> cupy==6.0.0b3
> Cython==0.29.6
> fastrlock==0.4
> numpy==1.16.2
> pkg-resources==0.0.0
> six==1.12.0
> ```
> 
> ```python
> import cupy, cupyx
> 
> x = cupy.array([1., 2., 3.])
> y = cupy.arange(10)
> print(cupyx.get_runtime_info())
> ```
> 
> ```python
> CuPy Version          : 6.0.0b3
> CUDA Root             : /home/hashimoto/.local/cuda/cuda-8.0
> CUDA Build Version    : 8000
> CUDA Driver Version   : 10010
> CUDA Runtime Version  : 8000
> cuDNN Build Version   : 7103
> cuDNN Version         : 7103
> NCCL Build Version    : None
> NCCL Runtime Version  : None
> ```
> 
> @ling-pan BTW, how did you obtain cuDNN7.1.2? I think there is no release of cuDNN 7.1.2 for CUDA 8.0.

when I Input y = cupy.arange(10),I have the same question as that descripted above.please told me what did you do to deal with the question?Thank you!

**Comment by hanqing1** [comment]
@

> > I FAILED to reproduce your situation, although I setup CUDA10.1 for global installation and CUDA8.0 for local cupy, and used similar version of cuDNN.
> > ```shell
> > $ echo $LD_LIBRARY_PATH
> > /home/hashimoto/.local/cuda/cuda-8.0/lib64
> > $ pip freeze
> > cupy==6.0.0b3
> > Cython==0.29.6
> > fastrlock==0.4
> > numpy==1.16.2
> > pkg-resources==0.0.0
> > six==1.12.0
> > ```
> > 
> > 
> > ```python
> > import cupy, cupyx
> > 
> > x = cupy.array([1., 2., 3.])
> > y = cupy.arange(10)
> > print(cupyx.get_runtime_info())
> > ```
> > 
> > 
> > ```python
> > CuPy Version          : 6.0.0b3
> > CUDA Root             : /home/hashimoto/.local/cuda/cuda-8.0
> > CUDA Build Version    : 8000
> > CUDA Driver Version   : 10010
> > CUDA Runtime Version  : 8000
> > cuDNN Build Version   : 7103
> > cuDNN Version         : 7103
> > NCCL Build Version    : None
> > NCCL Runtime Version  : None
> > ```
> > 
> > 
> > @ling-pan BTW, how did you obtain cuDNN7.1.2? I think there is no release of cuDNN 7.1.2 for CUDA 8.0.
> 
> when I Input y = cupy.arange(10),I have the same question as that descripted above.please told me what did you do to deal with the question?Thank you!

@ling-pan @fiarabbit

**Comment by fiarabbit** [comment]
@hanqing1 Would you please raise another issue with your runtime information, because NVRTC error stuff usually densely relates to the runtime environment. Please note the output of `cupyx.get_runtime_info()`.

**Comment by cloudXia777** [comment]
> Give me more information.
> 
> 1. Where do you have an error in the following code?
> 
> ```python
> import cupy
> 
> x = cupy.array([1., 2., 3.])
> y = cupy.arange(10)
> ```
> 
> 1. What do you set in your LD_LIBRARY_PATH?
> 
> ```
> $ echo $LD_LIBRARY_PATH
> ```
> 
> 1. (optional) what would happen when you use a bundled-version of cupy?
> 
> ```
> $ pip freeze
> $ pip uninstall cupy -y
> $ pip install cupy-cuda80==v6.0.0b3
> $ # and do 1. again
> ```

Hey, Error (7) occurred when I ran "y  = cupy.arange(10)". Do you know why this error?

**Comment by GuHuangAI** [comment]
@hanqing1  hello,i missed the same issue.Could you tell me how to solve it?

**Comment by GuHuangAI** [comment]
@hanqing1 there is my info:
`cupy.array([1,2,3])
Out[12]: array([1, 2, 3])`
`y=cupy.arange(10)
NVRTCError: NVRTC_ERROR_COMPILATION (6)

CompileException: Catastrophic error: cannot open source file "C:\Users\榛刓AppData\Local\Temp\tmpg4c62iyd\7cb9cb82a45540883a7190c81ea23c5d_2.cubin.cu"

1 catastrophic error detected in the compilation of "C:\Users\黄\AppData\Local\Temp\tmpg4c62iyd\7cb9cb82a45540883a7190c81ea23c5d_2.cubin.cu".
Compilation terminated.`

`print(cupyx.get_runtime_info())
CuPy Version          : 7.5.0
CUDA Root             : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10201
cuFFT Version         : 10101
cuRAND Version        : 10101
cuSOLVER Version      : (10, 2, 0)
cuSPARSE Version      : 10300
NVRTC Version         : (10, 2)
cuDNN Build Version   : None
cuDNN Version         : None
NCCL Build Version    : None
NCCL Runtime Version  : None
CUB Version           : None
cuTENSOR Version      : None`

**Comment by GuHuangAI** [comment]
@hanqing1  i guess the reason is my path has chainese characters, but i'm afraid to change it that it'll lead to many problems in windows system.

**Comment by DAVID-Hown** [comment]
Hello, I have also encountered the same problem. This error occurred when I was running other people's demo examples. This problem has bothered me for many days.
error：
Number of threads used: 32
Loading models parameters...
./models/trained/disparity-estimation-no-mask.tar
Model disparity loaded succesfully.
./models/trained/disparity-refinement.tar
Model refine loaded succesfully.
./models/trained/inpainting-color.tar
Model inpaint loaded succesfully.
Traceback (most recent call last):
File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 681, in compile
nvrtc.compileProgram(self.ptr, options)
File "cupy_backends/cuda/libs/nvrtc.pyx", line 139, in cupy_backends.cuda.libs.nvrtc.compileProgram
File "cupy_backends/cuda/libs/nvrtc.pyx", line 151, in cupy_backends.cuda.libs.nvrtc.compileProgram
File "cupy_backends/cuda/libs/nvrtc.pyx", line 67, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/DATA/jupyter/share/haodawei/improved-kbe/kbe.py", line 182, in
ken_burn_pipe((tensorImage+1)/2, zoom_settings, output_path, pretrained_estim=pretrained_estim)
File "/DATA/jupyter/share/haodawei/improved-kbe/utils/pipeline.py", line 112, in call
numpyResult = process_kenburns({
File "/DATA/jupyter/share/haodawei/improved-kbe/utils/common.py", line 208, in process_kenburns
tensorRender, tensorExisting = render_pointcloud(objectCommon['tensorInpaPoints'] + tensorShift,
File "/DATA/jupyter/share/haodawei/improved-kbe/utils/common.py", line 435, in render_pointcloud
launch_kernel('kernel_pointrender_updateZee', preprocess_kernel('''
File "cupy/_util.pyx", line 67, in cupy._util.memoize.decorator.ret
File "/DATA/jupyter/share/haodawei/improved-kbe/utils/common.py", line 380, in launch_kernel
return cupy.cuda.compile_with_cache(strKernel, tuple([ '-I ' + os.environ['CUDA_HOME'], '-I ' + os.environ['CUDA_HOME'] + '/include' ])).get_function(strFunction)
File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 460, in compile_with_cache
return _compile_module_with_cache(*args, **kwargs)
File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 488, in _compile_module_with_cache
return _compile_with_cache_cuda(
File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 566, in _compile_with_cache_cuda
ptx, mapping = compile_using_nvrtc(
File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 317, in compile_using_nvrtc
return _compile(source, options, cu_path,
File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 301, in _compile
compiled_obj, mapping = prog.compile(options, log_stream)
File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 698, in compile
raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: /tmp/tmpl94lnfh3/6335edf91d36e122532b0e6f44001e82f777db6a.cubin.cu(2): catastrophic error: cannot open source file "/home/s182169/Master_thesis/GAN-Burns-effect/utils/helper_math.h"

1 catastrophic error detected in the compilation of "/tmp/tmpl94lnfh3/6335edf91d36e122532b0e6f44001e82f777db6a.cubin.cu".
Compilation terminated.
————————————————
my env:
OS : Linux-4.9.0-8-amd64-x86_64-with-glibc2.27
Python Version : 3.9.2
CuPy Version : 10.1.0
CuPy Platform : NVIDIA CUDA
NumPy Version : 1.20.1
SciPy Version : 1.6.1
Cython Build Version : 0.29.24
Cython Runtime Version : None
CUDA Root : /usr/local/cuda
nvcc PATH : /usr/local/cuda/bin/nvcc
CUDA Build Version : 10020
CUDA Driver Version : 10020
CUDA Runtime Version : 10020
cuBLAS Version : 10203
cuFFT Version : 10102
cuRAND Version : 10102
cuSOLVER Version : (10, 3, 0)
cuSPARSE Version : 10301
NVRTC Version : (10, 2)
Thrust Version : 100907
CUB Build Version : 100800
Jitify Build Version : 60e9e72
cuDNN Build Version : 8300
cuDNN Version : 8101
NCCL Build Version : 21104
NCCL Runtime Version : 2804
cuTENSOR Version : None
cuSPARSELt Build Version : None
Device 0 Name : Tesla V100-SXM2-32GB
Device 0 Compute Capability : 70
Device 0 PCI Bus ID : 0000:18:00.0
Device 1 Name : Tesla V100-SXM2-32GB
Device 1 Compute Capability : 70
Device 1 PCI Bus ID : 0000:3B:00.0
Device 2 Name : Tesla V100-SXM2-32GB
Device 2 Compute Capability : 70
Device 2 PCI Bus ID : 0000:AF:00.0

**Comment by cloudXia777** [comment]
This is an auto vacation reply. Hi, I am on my works and may not reply in time. I will reply to you soon when I'm online.

**Comment by kmaehashi** [comment]
@DAVID-Hown
The error is in your code:
> cupy.cuda.compiler.CompileException: /tmp/tmpl94lnfh3/6335edf91d36e122532b0e6f44001e82f777db6a.cubin.cu(2): catastrophic error: cannot open source file "/home/s182169/Master_thesis/GAN-Burns-effect/utils/helper_math.h"
