### ISSUE TITLE
bincount with complex weights

### ISSUE THREAD

**Issue by kartikayyer** [cupy/cupy#2107]
`bincount` is a useful way to average values in an array with variable length bins (another is `np.add.at`, but that is not implemented here). This is also described in the `numpy.bincount` manual (https://docs.scipy.org/doc/numpy/reference/generated/numpy.bincount.html).

However, if I give a complex64 array as the weights parameter, `cupy.bincount` fails with a NVRTCError/CompileException:
```
error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (float *, const T)
```

Can this be implemented?

Note that a similar issue and PR are there in the numpy repo as well:
http://numpy-discussion.10968.n7.nabble.com/Make-np-bincount-output-same-dtype-as-weights-td42658.html
https://github.com/numpy/numpy/pull/7464

**Comment by kmaehashi** [comment]
Basically we keep CuPy specification the same as how it is implemented in NumPy.
The current workaround would be to do bincount twice (with real/imaginary part of the weight).

**Comment by niboshi** [comment]
Closing as per the comment above.
