### ISSUE TITLE
Use complex number in cupy.RawKernel

### ISSUE THREAD

**Issue by we-taper** [cupy/cupy#2111]
Hi!

I wonder what is the native/suggested way to use complex numbers in Cupy.RawKernel?

I was using `#include<cuComplex.h>` until I got an error on my newly installed cupy on another computer. I scrambled through your code and it seems to me that the preferred way is to use `#include<cupy/complex/complex.h>`. Is this the preferred library to use for cupy?

**Comment by grlee77** [comment]
See #1866 for some discussion of this and an example

**Comment by we-taper** [comment]
@grlee77 Fantastic. Hope that PR got merged soon.
