### ISSUE TITLE
Understanding reduced_view

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#2114]
Saw some code in CuPy was leveraging `reduced_view`, but am still trying to wrap my head around it. The [documentation]( https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.ndarray.html#cupy.ndarray.reduced_view ) unfortunately didn't help me much.

> Returns a view of the array with minimum number of dimensions.

In particular the phrase "minimum number of dimensions" does not make much sense to me. Minimum in what sense? Subject to what?

Any help clarifying this would be much appreciated. 🙂

**Comment by fiarabbit** [comment]
If I'm correct, "minimum" means "0 or 1". Usually, reduced view is 1-dimensional if there are not less than 1 element in the array. However, there could be 0-dimensional array which holds 0 element and only meta-information about shape is held on.

**Comment by fiarabbit** [comment]
```hoge.py
>>> import cupy
>>> a = cupy.empty((3, 3))
>>> a.reduced_view()
array([0., 0., 0., 0., 0., 0., 0., 0., 0.])
>>> b = cupy.empty((3, 0))
>>> b.reduced_view()
array([], dtype=float64)
```

**Comment by kmaehashi** [comment]
Closing as the question of the author has been answered.
