### ISSUE TITLE
Windows version in conda lags behind, still at 4.1.0

### ISSUE THREAD

**Issue by t184256** [cupy/cupy#2136]
Not sure if this is a right place to report, but the Windows cupy version at conda is seriously lagging behind at 4.1.0 and other means of installing it are extremely inconvenient in comparison.

Is it related to: https://github.com/cupy/cupy/issues/2135#issuecomment-480016360?

**Comment by fiarabbit** [comment]
@t184256 It may relate to the fact that `cupy` does not (at least officially) support Mircrosoft Windows (https://docs-cupy.chainer.org/en/stable/install.html#recommended-environments).

**Comment by t184256** [comment]
I'm well aware of that fact, and I'm not demanding support or anything. I'm actually 1) wondering what's the blocker for having another unsupported build shipped with conda and how severe it is and 2) expressing the demand in a conveniently trackable formfor both the user's and the devs. Sorry if that's an inappropriate form of doing this.

**Comment by kmaehashi** [comment]
This is not related to #2135.
CuPy packages on Anaconda is maintained by Anaconda team, not by us. I'll contact them to update the package.

**Comment by leofang** [comment]
cc: @jakirkham This is related to our earlier discussion. Anaconda should make old packages inaccessible.

**Comment by leofang** [comment]
xref: https://groups.google.com/g/cupy/c/Qryl0j0K9uQ

**Comment by kmaehashi** [comment]
Closing as Anaconda now provides CuPy v8.3.0. https://anaconda.org/anaconda/cupy

For Linux, we recommend using conda-forge channel as documented in:
https://docs.cupy.dev/en/latest/install.html#installing-cupy-from-conda-forge

**Comment by leofang** [comment]
For this week's release, we can try to build for Windows on Conda-Forge.
