### ISSUE TITLE
Cannot install cupy on win10

### ISSUE THREAD

**Issue by Europium-152** [cupy/cupy#2137]
Hi! I'm running into some problems trying to install cupy on windows.

When I try the `pip install cupy-cuda101`, I get:

```cmd
Collecting cupy-cuda101
  Could not find a version that satisfies the requirement cupy-cuda101 (from versions: )
No matching distribution found for cupy-cuda101
```
When I try `pip install cupy`, I get:
```cmd
Collecting cupy
  Using cached https://files.pythonhosted.org/packages/cd/d6/532e5da87f3b513cd0b98bcbf9a58fb6758598039944c42cb93d13b71a5f/cupy-5.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}

    -------- Configuring Module: cuda --------
    Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************

    Build Environment:
      Include directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\include', 'C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\include']
      Library directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\lib\\x64', 'C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\lib\\x64']
      nvcc command       : ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin/nvcc.exe']

    Environment Variables:
      CFLAGS          : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include
      LDFLAGS         : (none)
      LIBRARY_PATH    : (none)
      CUDA_PATH       : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
      NVTOOLSEXT_PATH : C:\Program Files\NVIDIA Corporation\NvToolsExt\
      NVCC            : (none)

    Modules:
      cuda      : No
        -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
        -> Check your CFLAGS environment variable.

    ERROR: CUDA could not be found on your system.
    Please refer to the Installation Guide for details:
    https://docs-cupy.chainer.org/en/stable/install.html

    ************************************************************

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\danie\AppData\Local\Temp\pip-install-djalcd87\cupy\setup.py", line 120, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "C:\Users\danie\AppData\Local\Temp\pip-install-djalcd87\cupy\cupy_setup_build.py", line 588, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "C:\Users\danie\AppData\Local\Temp\pip-install-djalcd87\cupy\cupy_setup_build.py", line 384, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\danie\AppData\Local\Temp\pip-install-djalcd87\cupy\
```

*Note*: The environment variable CFLAGS was manually set by me to the directory of the missing .h files, but it did not solve the problem (it showed "none" before I set it).

I'm on Windows 10, using Python 3.7.3. I have installed CUDA toolkit 10.1

Best regards, Daniel

**Comment by kmaehashi** [comment]
Could you try `pip install cupy-cuda101 ` after updating `pip` and `setuptools` as suggested by Installation Guide? https://docs-cupy.chainer.org/en/stable/install.html#requirements

If the problem still occurs, could you paste the output of `pip -V`, `python -V` and `python -c 'import sys; print(sys.abiflags)'`?

**Comment by TanishSharrma** [comment]
"Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/"

Try installing the C++ Build Tools if you haven't already. That worked for me.

**Comment by Europium-152** [comment]
Sorry for the late answer and thank you for the feedback. I had two issues that I hadn't realized. I first tried with python2 which didn't work, then I realized I had to do it in python 3, but by mistake, I installed the 32-bit version (that's when I got the message I posted above). When I finally changed to python 3 64-bit everything worked great. And yes visual studio is required.

**Comment by mahdiabdollahpour** [comment]
> Could you try `pip install cupy-cuda101 ` after updating `pip` and `setuptools` as suggested by Installation Guide? https://docs-cupy.chainer.org/en/stable/install.html#requirements
> 
> If the problem still occurs, could you paste the output of `pip -V`, `python -V` and `python -c 'import sys; print(sys.abiflags)'`?

I have the same problem
Python 3.7.3
windows 10
pip 19.2.2 from c:\programdata\anaconda3\lib\site-packages\pip (python 3.7)

but :
when I run sys.abiflags in python sell I get
AttributeError: module 'sys' has no attribute 'abiflags'


How can I solve this?

**Comment by kmaehashi** [comment]
Could you paste the output from `pip` command?

> when I run sys.abiflags in python sell I get

Sorry, that was my mistake (`abiflags` is unavailable on Windows)

**Comment by 2541989802** [comment]
This solves my problem.
