### ISSUE TITLE
complex.cuh not found when running exe generated by pyinstaller

### ISSUE THREAD

**Issue by txuh** [cupy/cupy#2140]
I am using Pyinstaller to build a stand alone exe for my PYQT5 GUI with cupy computations. I created a spec file to specify the added data, pathes and hiddenimports. My program are fully working under Python complier. 

The exe are successfully built. The GUI window can be opened with running the generated exe. However, there was error message when running the software (I have push button at GUI for doing some Cupy computations). Please see below:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Skynet1\\AppData\\Local\\Temp\\_MEI89842\\cupy\\core\\include\\cupy/complex.cuh'

After checking. I found the error may happen at 
data0 = cupy.subtract(a, b) 
Where a and b are 2D numpy liked cupy arrays. 
I tried to add the cupy.core.include or cupy.core.include.cupy  into hiddenimports, but none of them working. I did not specify any system path at this location. No idea how to fix this and why this part will call "complex.cuh"

My hiddenimports in the spec file.
hiddenimports=['fastrlock', 'fastrlock.rlock', 'cupy.core.flags','cupy.core.carray','cupy.core','cupy.core._kernel','zmq.backend','cupy.core._scalar','cupy','cupy.cuda','cupy.cuda.memory_hooks','cupy.fft','cupy.lib','cupy.core.include'],

Can anyone give me some suggestion and advice?
Thank you

**Comment by kmaehashi** [comment]
CuPy refers to the header files under `cupy/core/include` at runtime to compile CUDA kernels.
I guess `hiddenimports` does not work as it is not a Python module. Refer to the comment below:
https://github.com/cupy/cupy/issues/1262#issuecomment-391316488

**Comment by jdgelb** [comment]
I had the same issue and the fix in that comment worked for me too! In order to build (*and* use) CuPy within a pyinstaller-built executable on my Windows 10 workstation, I needed to add the following to my spec file:
```
hiddenimports=['fastrlock',
			    'fastrlock.rlock',
			    'cupy.core.flags',
			    'cupy.core._routines_indexing',
			    'cupy.core._dtype',
			    'cupy.core._scalar',
			    'cupy.core._ufuncs',
			    'cupy.core._routines_sorting'
			   ],
```
and 
```
a.datas += Tree(venv_root + "\\\Lib\\site-packages\\cupy\\core\\include\\cupy", ".\\cupy\\core\\include\\cupy")
```
Adding the `hiddenimports` was necessary to get `import cupy as cp` to work, but anytime I tried to use some CuPy functionality the app would complain about complex.cuh. Copying over the missing library folders fixed that issue and now CuPy is working flawlessly in a beautiful, portable EXE. 😎
