### ISSUE TITLE
Missing curly brackets in Raw Kernel doc

### ISSUE THREAD

**Issue by tomstewart89** [cupy/cupy#2141]
First off thanks for a great library! It's made it really easy to optimise some numpy code I've been working on.

Anyway, there's two small errors in the docs for `cupy.RawKernel` ([these ones](https://github.com/cupy/cupy/blob/4a80efe88bb66e48896240f268b2b5e6178ea394/docs/source/tutorial/kernel.rst#raw-kernels)) that should be a pretty easy fix:

* change `cp.RawKernel` to `cupy.RawKernel`
* add curly brackets to the `extern "C"` declaration

Anyway thanks again!

**Comment by kmaehashi** [comment]
Thanks for raising an issue.

> change cp.RawKernel to cupy.RawKernel

`cp` is used as an abbreviation of cupy in the whole documentation.
https://docs-cupy.chainer.org/en/latest/tutorial/basic.html#basics-of-cupy-ndarray

So I think it's rather better to replace `cupy` with `cp`.

> add curly brackets to the extern "C" declaration

In this example code, curly bracket is not needed as `extern "C"` only qualifies the single function `my_add`.

**Comment by thomascent** [comment]
Ugh you're right, sorry my C++ is really rusty these days. And sure, numpy uses `np` throughout its docs so using `cp` here makes sense.

**Comment by tomstewart89** [comment]
Ugh you're right, sorry my C++ is really rusty these days. And sure, numpy uses np throughout its docs so using cp here makes sense.
