### ISSUE TITLE
Include argument type names to kernel names

### ISSUE THREAD

**Issue by gwtnb** [cupy/cupy#2149]
CuPy uses simple names for kernels (e.g. `cupy_add`), but these names do not tell types of their arguments as following output of nvvp.

![image](https://user-images.githubusercontent.com/4025819/56260697-2be1c500-6113-11e9-9f24-cf7af82f1320.png)

It seems inconvenient because the user cannot interpret what type is actually used from the output of nvvp.

**Comment by beam2d** [comment]
Type information has been added for ufunc kernels via #2151. The kernel name is now rendered like `cupy_add__float16_float32_float32` (for adding float16/float32 arrays).
