### ISSUE TITLE
Tensor Core is not used on the Turing GPU

### ISSUE THREAD

**Issue by samacoba** [cupy/cupy#2153]
The compute capability is 7.5 on the Turing GPU.
However, in the following Tensordot and Convolution code, the compute capability only supports 7.0.
So it seems that Tensor Core is not used on Turing GPU.

* Tensordot

https://github.com/cupy/cupy/blob/ba75ec09e33bd1b2aad4c564ed78389ceb09e0d2/cupy/core/core.pyx#L2288-L2290

* Convolution

https://github.com/cupy/cupy/blob/690997a6159ee84c0f6b41ae6c79d7974e358912/cupy/cudnn.pyx#L1198-L1201

**Comment by kmaehashi** [comment]
Thank you for pointing out this issue.

**Comment by asi1024** [comment]
This PR is once resolved in #2168 but reverted in #2197 because the tests failed due to a bug in cuDNN.

**Comment by kmaehashi** [comment]
Fixed in #2328
