### ISSUE TITLE
Support POWER8/POWER9

### ISSUE THREAD

**Issue by denfromufa** [cupy/cupy#2173]
It appears numpy already supports ppc64 architecture via Travis CI:

https://github.com/numpy/numpy/pull/12709

**Comment by denfromufa** [comment]
Also scipy is working on powerpc support:

https://github.com/scipy/scipy/pull/9684

**Comment by kmaehashi** [comment]
Thank you for raising an issue. Unfortunately Travis does not support GPU, so we cannot run tests on it; currently we use Travis only to verify that it can be compiled. To declare that CuPy supports POWER architecture, we need some CI infrastructure to run full CuPy unit tests.
Do you have specific use-case to use CuPy on POWER?

**Comment by denfromufa** [comment]
Actually my use case just cancelled, because cupy only supports limited subset of zoom method from scipy.ndimage.
I had issues with compiling cupy in PowerAI, but this resolved by switching to default compilers.
