### ISSUE TITLE
Document if Impossible to use CuPy with Python 2.7 in Windows

### ISSUE THREAD

**Issue by slate0** [cupy/cupy#2178]
I have spent a long time trying to get CuPy working with Python 2.7 in Windows.
It seems that experienced people have determined that this is impossible.

Is there a good place to document this information?  

Thank you!

> Python2.7 (compiling) requires Visual Studio9.0 (VS2008) but CUDA support from Visual Studio 2012~, so local build may also be difficult, I think.

Yeap, that seems to be the issue with `pip install cupy`, since the first error messages return error status 2 at Visual C++ for Python's cl.exe (see my attached log in the OP).

> On Windows OS, cupy wheel only supports Python3.6. ref: https://pypi.org/project/cupy-cuda91/5.0.0b3/#files

Very true. So, it seems that there is really no alternative for using CuPy in Windows with Python 2.7.

_Originally posted by @vasselai in https://github.com/cupy/cupy/issues/1545#issuecomment-414232931_

**Comment by kmaehashi** [comment]
Closing as CuPy no longer supports Python 2.

**Comment by danielcjacobs** [comment]
Does this mean I can't use CuPy with python 2 at all?

**Comment by kmaehashi** [comment]
@danielcjacobs  The last version supporting Python 2.7 is CuPy v6.7.0. https://docs.cupy.dev/en/v6.7.0/install.html

**Comment by danielcjacobs** [comment]
[This page](https://pypi.org/project/cupy/6.7.0/) seems to indicate that CuPy v6.7.0 isn't compatible with CUDA 10.2.

Does this mean I can't use CuPy for CUDA 10.2 with Python 2? (i.e. I either need to use Python 3 or CUDA 10.1)

**Comment by kmaehashi** [comment]
Basically, yes. You can try building from source instead of using binary wheels, but we haven't tested that configuration because CuPy v6.7.0 is released before CUDA 10.2.
