### ISSUE TITLE
cupy.arange() error

### ISSUE THREAD

**Issue by yanlongbinluck** [cupy/cupy#2180]
I have installed cupy by cupy-cuda100
why cupy.array([1,2,3]) is work , but cupy.arange([10]) does not work on my machine?
![image](https://user-images.githubusercontent.com/35165028/57592669-7f0c3380-756a-11e9-9aef-411b3cfa68db.png)

**Comment by kmaehashi** [comment]
Please refer to the FAQ section.
https://docs-cupy.chainer.org/en/latest/install.html#cupy-always-raises-cupy-cuda-compiler-compileexception
