### ISSUE TITLE
Add cuDNN attention

### ISSUE THREAD

**Issue by gwtnb** [cupy/cupy#2202]
Add support of
- [ ] cudnnMultiHeadAttnForward
- [ ] cudnnMultiHeadAttnBackwardData
- [ ] cudnnMultiHeadAttnBackwardWeights

**Comment by gwtnb** [comment]
There are a list of attention functions on the cuDNN 7.5.0 release note. https://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_750.html

**Comment by crcrpar** [comment]
I tried to support those functions but still in progress ([branch's comparison to cupy:master](https://github.com/cupy/cupy/compare/master...crcrpar:feature/attention) because I have no idea about the design of cupy/cudnn.pyx functions whom used by Chainer directly.

**Comment by kmaehashi** [comment]
Related to https://github.com/chainer/chainer/pull/7066.

> I have had no idea about the design of cupy/cudnn.pyx functions

Currently this module is undocumented and thus have no explicit policy regarding implementation (basically it should conceal cudnn specific states and descriptors). Do you have any specific concerns?

**Comment by crcrpar** [comment]
I have difficulty in understanding the cuDNN API documentations and I am
concerned about whether there is a limitation of shapes of query, key, and
value vectors.

**Comment by kmaehashi** [comment]
> I am concerned about whether there is a limitation of shapes of query, key, and value vectors.

It seems error code list of `cudnnSetAttnDescriptor` contains some restrictions regarding parameters. If you have some doubt, we can ask it to NVIDIA guys.

**Comment by kmaehashi** [comment]
See https://github.com/cupy/cupy/pull/2215#issuecomment-606593705
