### ISSUE TITLE
cp.mean over flat array returns array (unlike np.mean)

### ISSUE THREAD

**Issue by p3732** [cupy/cupy#2205]
Hi there!
I found that using `cp.mean()` as a drop-in replacement for `np.mean()` does not always work, since for calculating the mean of the flattened array (not specifing the `axis` parameter), cupy returns an array while numpy returns a single float value. Not sure if this is intentional, but I did not find any previously opened issues on this.

Code snippet:

```
import numpy as np
import cupy as cp

a=[23,4,356,2,45,3]

a_np = np.array(a)
a_cp = cp.array(a)

m_np = np.mean(a_np)
m_cp = cp.mean(a_cp)
print(type(m_np))
print(type(m_cp))
```

CuPy version 5.1.0, Python 3.7.3, Linux, CUDA 10

**Comment by kmaehashi** [comment]
Thanks for raising an issue! This behavior is by design of CuPy. Please refer to this docs for more details:
https://docs-cupy.chainer.org/en/latest/reference/difference.html#zero-dimensional-array

**Comment by p3732** [comment]
Ah yes, I thought something like this would be the case, but did not suspect to find it under that FAQ entry. Thanks for the explanation! Hopefully this issue will be found by other people wondering about this.
