### ISSUE TITLE
Proper way of handling scalar (np) v. 0-dimensional array (cp)

### ISSUE THREAD

**Issue by egoolish** [cupy/cupy#2212]
It's talked about in the documentation how CuPy returns 0-dimentional cupy.ndarrays rather than scalars, as in
```
np.array([np.sin(10)]*3)
# [-0.5440211108893698, -0.5440211108893698, -0.5440211108893698]
```
whereas
```
[cp.sin(10)]*3
# [array(-0.54402111), array(-0.54402111), array(-0.54402111)]
```
and thus calling
```
cp.array([cp.sin(10)]*3)
# Throws an error
```
A workaround is to explicitly cast the array:
```
cp.array([cp.sin(10)]*3, dtype = cp.float64)
# [-0.5440211108893698, -0.5440211108893698, -0.5440211108893698]
```
but I'm just curious if this is killing performance by forcing the GPU to sync with the CPU. Does there exist a protocol for handling this type of scenario (which also happens with reduction functions such as np.sum/cp.sum)?

**Comment by kmaehashi** [comment]
```py
cp.array([cp.sin(10)]*3)
```

`cp.array` will accept array of CuPy arrays in the next release (v7.0.0b1, #2081). In this case array concatenation will run on GPU.

**Comment by kmaehashi** [comment]
Feel free to reopen the issue if you need further discussions.
