### ISSUE TITLE
Hasattr returns True for attributes in 0-dimensional arrays

### ISSUE THREAD

**Issue by egoolish** [cupy/cupy#2213]
Behavior is somewhat expected, although counter-intuitive and unlike NumPy's. Elements of a cp.array are also cp.arrays rather than scalars, and thus hasattr returns true for attributes such as len. However, of course, calling len on an element throws an error. 
MWE:
```
x = cp.array([1])
# [1]
```
```
hasattr(x[0], "__len__")
# True
```
```
len(x[0])
# TypeError: len() of unsized object
```

**Comment by kmaehashi** [comment]
> Elements of a cp.array are also cp.arrays rather than scalars

By design of CuPy, it does not perform memory transfer between GPU/CPU automatically. Please refer to https://docs-cupy.chainer.org/en/latest/reference/difference.html#zero-dimensional-array for details.

> hasattr returns true for attributes such as len. However, of course, calling len on an element throws an error.

This behavior is the same as NumPy's 0-dim array.
