### ISSUE TITLE
Add cupy.nanargmin and cupy.nanargmax

### ISSUE THREAD

**Issue by Piyush-555** [cupy/cupy#2216]
I am interested in adding `cupy.nanargmin` and `cupy.nanargmax`. They will not be fully equivalent to numpy ones because, currently `cupy.array` does not support `subok=True`.

**Comment by harshalchaudhari35** [comment]
I have ran into the same requirement of nanargmin and nanargmax in cupy. I had to port from numpy without the subok parameter and conditional check for _object in _replace_nan() function. I would be interested to add further into this

**Comment by kmaehashi** [comment]
@harshalchaudhari35 It would be great if you can make a PR for this!

**Comment by harshalchaudhari35** [comment]
@kmaehashi Sure will do

**Comment by harshalchaudhari35** [comment]
Apologies for the messy PR earlier. Initial checks have passed now. Please review the PR.

**Comment by harshalchaudhari35** [comment]
I suppose this should be closed now? @asi1024
