### ISSUE TITLE
Write a document or a comment about cupy_cudnn.h

### ISSUE THREAD

**Issue by gwtnb** [cupy/cupy#2218]
Current [`cupy_cudnn.h`](https://github.com/cupy/cupy/blob/cbd9c30db2eff89f8d102684085779d75a7e6f5f/cupy/cuda/cupy_cudnn.h) is difficult to understand for developers who are not familiar with CuPy internals. The sources of difficulties may be:

- The purposes of `cupy_cudnn.h` are not written.
- `cupy_cudnn.h` has multiple purposes (i.e. building on readthedocs and supporting multiple version of cuDNN).

**Comment by leofang** [comment]
@kmaehashi My PR #4088 would resolve this confusion, see https://github.com/cupy/cupy/pull/4088#issuecomment-713310500.
