### ISSUE TITLE
Add CuPy extract

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#2223]
Would be useful to have an [`extract`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.extract.html#numpy.extract ) implementation for CuPy arrays.

**Comment by andy6975** [comment]
Is this issue open? I would like to work on this. Thanks!

**Comment by jakirkham** [comment]
Yes, please feel free 🙂

**Comment by Harshan01** [comment]
Hi, is the issue still open? I would like to work on `extract`, if it is open.

**Comment by jakirkham** [comment]
Yeah, that would be great if you could 🙂

**Comment by Harshan01** [comment]
I have made a PR for `extract`. #3109 
The details of the implementation are mentioned in the PR.
I would be happy to receive suggestions on improving it.

**Comment by jakirkham** [comment]
Awesome, thanks Harshan! 😀

**Comment by asi1024** [comment]
Merged #3109.
