### ISSUE TITLE
Slow program execution from device to host transfer

### ISSUE THREAD

**Issue by jchutrue** [cupy/cupy#2226]
I'm testing a simple inner product with cupy. When I copy the output to host memory, the actual data transfer rate is what I expect, but the total execution time of that code block is orders of magnitude higher. So I'd like to know whether this is a real issue or something expected. Thanks!

```python
import cupy as cp
import time
N = 10000
xp = cp.random.rand(N, N)
yp = cp.random.rand(N, N)

zp = cp.empty(xp.shape, xp.dtype)
xp.dot(yp, out=zp)

######################################
# Slow code block
start = time.time()
with cp.cuda.stream.Stream() as stream_dtoh:
    t0 = stream_dtoh.record()
    z = zp.get()
    stream_dtoh.synchronize()
    t1 = stream_dtoh.record()
end = time.time()
#####################################

print("Device to host time: {} sec".format(cp.cuda.get_elapsed_time(t0, t1)/1000))
print("Total device to host time: {} sec".format((end-start)))
```
Output:
```
Device to host time: 0.30891928100585936 sec
Total device to host time: 15.798194885253906 sec
```
Conditions:
```
CuPy Version          : 5.1.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 8000
CUDA Driver Version   : 9000
CUDA Runtime Version  : 8000
cuDNN Build Version   : 7103
cuDNN Version         : 7103
NCCL Build Version    : 1000
```

**Comment by kmaehashi** [comment]
@jchutrue This is because `Total device to host time` includes time to perform `xp.dot`, whereas `Device to host time` only measures the time of memory copy. CUDA operations are basically asynchronous (`xp.dot` launches the kernel and returns immedeately).

**Comment by jchutrue** [comment]
@kmaehashi Ahh, I see. I don't think I was measuring the time properly then. What's the correct way to wait until the kernel completes, and only then start timing so that I can measure the ```z = zp.get()``` memory copy accurately?

**Comment by kmaehashi** [comment]
@jchutrue In this code `xp.dot` runs on null (default) stream. You can use `cp.cuda.Stream.null.synchronize()` right after `xp.dot` to synchronize host/device (i.e. wait until `xp.dot` completes).
