### ISSUE TITLE
Adding Conda packages to conda-forge

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#2274]
It would be great to have packages for [Conda]( https://docs.conda.io/en/latest/ ). While there are [packages maintained by Anaconda]( https://anaconda.org/anaconda/cupy ), it would be great to have some community maintained packages in [conda-forge]( https://conda-forge.org ). This would allow us to update things more directly and provide us the option to publish RCs to get the latest changes out there. Not to mention [Anaconda reuses recipes from conda-forge]( https://github.com/AnacondaRecipes ) in their own builds. In this effort it would be great to have your help maintaining the package. Thoughts?

cc @pentschev

**Comment by jakirkham** [comment]
Have added PR ( https://github.com/conda-forge/staged-recipes/pull/8638 ) to get this started. It is still WIP.

**Comment by pentschev** [comment]
Thanks for the discussion on this topic today during the PFN-NVIDIA call.

Just to summarize it here, PFN is going to discuss this but are mostly willing to maintain CuPy's conda-forge package. For now, @jakirkham has sent an initial package recipe in https://github.com/conda-forge/staged-recipes/pull/8638 that may be used as an introductory recipe and CuPy could continue to maintain it afterwards. Also, @jakirkham and I will help PFN if they encounter any issues with the package in the future.

Among the advantages of having this package are the capabilities of having nightly/development builds of CuPy, as well as allowing packages for different version of dependencies. As an example, we have an immediate need of a CuPy package with NCCL 2.4, and the package on conda's main repository only supports NCCL 1.x, but this scenario could be extended to the various dependencies of CuPy.

Feel free to expand on this if I missed something.

**Comment by kmaehashi** [comment]
@pentschev Thank you for summarizing the discussion!

@jakirkham 
* Does conda-forge provides automated build infrastructure like DockerHub, or should we build and upload packages by ourselves for each release?
* Anaconda's main repo already hosts `cupy` package. Are there anything that we should take care of (e.g. conflicts between Anaconda's main repo and conda-forge repo)?

**Comment by jakirkham** [comment]
Thank @pentschev for discussing this with PFN. Also thanks for the thoughtful questions, @kmaehashi. Have added some info below.

> Does conda-forge provides automated build infrastructure like DockerHub, or should we build and upload packages by ourselves for each release?

conda-forge provides infrastructure for each feedstock to manage the build and upload of packages from a clean, reproducible environment. This infrastructure is maintained by the core group in conda-forge and a few service providers (like Anaconda and Azure), which we work with. In fact update PRs are largely automated as well. So this comes down to reviewing, possibly modifying, and merging [a PR like this one]( https://github.com/conda-forge/numpy-feedstock/pull/158 ). For manual changes, there is [a rough overview in the docs]( https://conda-forge.org/#update_recipe ).

> Anaconda's main repo already hosts cupy package. Are there anything that we should take care of (e.g. conflicts between Anaconda's main repo and conda-forge repo)?

Users of conda-forge are recommended to make the conda-forge channel higher priority as [noted here]( https://conda-forge.org/#about ). Additionally Anaconda's recipes are all downstream from conda-forge. Once the conda-forge feedstock is made, they will fork it and apply any changes they need on top of it. More generally conda-forge and Anaconda work together to keep their recipes in sync as much as possible. It's possible Anaconda will submit changes they recommend to the recipe, which may need review.

**Comment by jakirkham** [comment]
@kmaehashi, does that help answer your questions? Are there any other questions you have?

**Comment by kmaehashi** [comment]
@jakirkham Sorry for the late reply and thank you for the answer! We discussed in the team and agreed to publish `cupy` package on conda-forge (I'm assuming `nvcc` and `nccl` packages in the PR will be maintained by NVIDIA). Could you proceed to merge https://github.com/conda-forge/staged-recipes/pull/8638?

**Comment by jakirkham** [comment]
Thanks @kmaehashi! Sorry for being quiet here.

We've recently added the infrastructure to build GPU packages. This includes the necessary logic for conda-build to perform builds with `nvcc` and add the `cudatoolkit` libraries as a dependency. Added `nccl` recently. So `cupy`'s dependencies are in place.

Have replaced the aforementioned PR with this updated one ( https://github.com/conda-forge/staged-recipes/pull/9959 ). Would be great to hear from more CuPy developers on this PR. Please let us know if this looks reasonable. 😄

**Comment by pentschev** [comment]
Just a brief comment from our NVIDIA-PFN meeting today, the PFN team would like to maintain the package as a team. @jakirkham is it possible to add a group of people to be maintainers of conda-forge packages? If not, I think the primary maintainer would be @kmaehashi, could you confirm?

**Comment by kmaehashi** [comment]
Yes, I will be a primary maintainer.

**Comment by leofang** [comment]
> is it possible to add a group of people to be maintainers of conda-forge packages?

I think so. Give me a list of github ids. I can add them as the maintainers

**Comment by leofang** [comment]
For the discussion on the maintainers, please go to conda-forge/cupy-feedstock#7.

**Comment by jakirkham** [comment]
Thanks all! Going to close this as complete. 😄

We can follow up on anything else either as issues here on the feedstock as appropriate.

**Comment by pentschev** [comment]
Great to hear, thanks @jakirkham for the enormous effort on this!
