### ISSUE TITLE
CuPy texture support

### ISSUE THREAD

**Issue by the-lay** [cupy/cupy#2278]
I have a framework built on top of PyCUDA, and I'm looking into CuPy as a potentially better option for the framework "backend".
I'm very happy with what I see, except for texture support. The framework's one of the most important features is fast rotation on GPU. We use textures (specifically 3D) and custom interpolation, and I was wondering, does CuPy support textures?
Ideally, is there an example or maybe an example of combining CuPy with PyCUDA?

**Comment by beam2d** [comment]
We do not have any plan for introducing texture support to CuPy. We are interested in the interoperability with other libraries, though, and PyCUDA is not an exception. Again, we currently do not have any concrete plan for supporting PyCUDA interop support, but if there is a demand, we are willing to add support for it.

**Comment by leofang** [comment]
As a (former) PyCUDA user, one nice thing for better interoperability is to ask @inducer to support [`__cuda_array_interface__`](http://numba.pydata.org/numba-doc/latest/cuda/cuda_array_interface.html). Then, adding support for texture and beyond might become a bit easier.

**Comment by inducer** [comment]
I'm not a CuPy user myself, but I would be happy to consider a patch implementing this.
