### ISSUE TITLE
Empty code block in document

### ISSUE THREAD

**Issue by ir5** [cupy/cupy#228]
https://docs-cupy.chainer.org/en/stable/tutorial/basic.html
There is one empty code block blow the sentence ”””In the following code, cp is an abbreviation of cupy, as np is numpy as is customarily done:""". This is strange.
Further, I guess `cp`, `cupy`, etc. in the above sentence should be described with coding format, not a plain text.

**Comment by niboshi** [comment]
Thank you!
This problem has been solved in https://github.com/cupy/cupy/pull/93 and https://github.com/cupy/cupy/pull/106.
Please refer to "latest" build: https://docs-cupy.chainer.org/en/latest/tutorial/basic.html
Unfortunately it's not reflected in "stable" build yet....

**Comment by ir5** [comment]
Thank you for information. Then I will close this issue.
