### ISSUE TITLE
cupy TypeError while formatting cupy result to string

### ISSUE THREAD

**Issue by galipremsagar** [cupy/cupy#2281]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  CuPy Version          : 6.1.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10000
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10000
cuDNN Build Version   : 7500
cuDNN Version         : 7500
NCCL Build Version    : 2402
NCCL Runtime Version  : 2402
* Code to reproduce:
cupy is not able to handle floating string formatting, see the below code:
```python
"{:.1f}".format(cupy.sum(cupy.array([1,2])))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-200-546c2172e30c> in <module>
----> 1 "{:.1f}".format(cupy.sum(cupy.array([1,2])))

TypeError: unsupported format string passed to cupy.core.core.ndarray.__format__
```

In numpy it works:
```python
"{:.1f}".format(np.sum(np.array([1,2])))
'3.0'
```

**Comment by crcrpar** [comment]
How about cupy.sum(cupy.array([1,2])).item()` which is only available for ndarrays with only one element as a tentative workaround?

**Comment by kmaehashi** [comment]
This is (currently) the expected behavior (see https://docs-cupy.chainer.org/en/latest/reference/difference.html#reduction-methods for further descriptions). As @crcrpar suggested, you need to use `item()` to explicitly transfer the computation results from GPU to CPU:

```py
"{:.1f}".format(cupy.sum(cupy.array([1,2])).item())  # '3.0'
"{:.1f}".format(numpy.sum(numpy.array([1,2])).item())  # '3.0'
```

**Comment by galipremsagar** [comment]
> This is (currently) the expected behavior (see https://docs-cupy.chainer.org/en/latest/reference/difference.html#reduction-methods for further descriptions). As @crcrpar suggested, you need to use `item()` to explicitly transfer the computation results from GPU to CPU:
> 
> ```python
> "{:.1f}".format(cupy.sum(cupy.array([1,2])).item())  # '3.0'
> "{:.1f}".format(numpy.sum(numpy.array([1,2])).item())  # '3.0'
> ```

Cool, thanks. That helped.
