### ISSUE TITLE
Add interface for cusparseCsrmvEx

### ISSUE THREAD

**Issue by wonghang** [cupy/cupy#2283]
My original problem is here:
https://groups.google.com/forum/#!topic/cupy/63Vfyc00YH0

Because of the above issue, I want to add an interface to call the MERGE PATH SpMV algorithm in CUSPARSE.

The API is here:
https://docs.nvidia.com/cuda/cusparse/index.html#csrmvEx

Referring to the following slide:
http://images.nvidia.com/events/sc15/pdfs/sc15-Merge-Based-Parallel-Sparse-Matrix-Vector-Multiplication-merrill.pdf

When the row-length coefficient of variation is high, the performance of the naive csrmv algorithm would degrade rapidly as CUDA threads work on different row length.

My work is here https://github.com/wonghang/cupy/tree/cusparseCsrmvEx ([compare](https://github.com/cupy/cupy/compare/master...wonghang:cusparseCsrmvEx))

Note that CUSPARSE_ALG_MERGE_PATH only support CUSPARSE_OPERATION_NON_TRANSPOSE

> For alg CUSPARSE_ALG_MERGE_PATH: half-precision is not supported, only CUSPARSE_MATRIX_TYPE_GENERAL, CUSPARSE_OPERATION_NON_TRANSPOSE and CUSPARSE_INDEX_BASE_ZERO are supported. Input, output and execution types should be the same.

As a result, I didn't include transA parameter in the wrapper.
I expose the interface by adding matvec(.) and rmatvec(.) to csr_matix and csc_matrix respectively. Please advise if it is good enough. If everything is fine, I will fix the flake8 syntax, write docstring and then submit a pull request.

For the performance BEFORE using MERGE PATH algorithm. Please refer to the google group message.
For the performance AFTER using MERGE PATH algorithm: 

```
$ python3 test_cupy_csr_matrix.py
CuPy Version          : 7.0.0b1
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10000
CUDA Driver Version   : 10000
CUDA Runtime Version  : 10000
cuDNN Build Version   : 7301
cuDNN Version         : 7301
NCCL Build Version    : None
NCCL Runtime Version  : None
nnz=1918549, shape=(325509,54984)
A  row-length: min=1, max=6, sd=0.720263
At row-length: min=3, max=93516, sd=745.348
scipy matvec spent 2.660238s
scipy rmatvec spent 3.872705s
cupy matvec spent 0.170503s
cupy rmatvec spent 0.317017s

```
Using the following code

```python

import gzip
import pickle
import numpy as np
import cupy as cp
from scipy.sparse import csr_matrix
import timeit

def main():
    cp.show_config()
    
    with gzip.GzipFile("spmatrix.pkl.gz","rb") as fp:
        (nnz,indices,indptr,M,N) = pickle.load(fp)

    indices = np.asarray(indices,dtype=np.int32)
    indptr = np.asarray(indptr,dtype=np.int32)
    test_count = 1000
    
    print("nnz=%d, shape=(%d,%d)" % (nnz,M,N))
    v = np.random.rand(N)
    w = np.random.rand(M)
    
    data = np.ones((nnz,),dtype=np.float64)
    A = csr_matrix((data,indices,indptr),shape=(M,N),dtype=np.float64)
    At = A.transpose().tocsr()

    S = np.diff(A.indptr)
    print("A  row-length: min=%d, max=%d, sd=%g" % (np.min(S),np.max(S),np.std(S)))
    S = np.diff(At.indptr)
    print("At row-length: min=%d, max=%d, sd=%g" % (np.min(S),np.max(S),np.std(S)))

    scipy_r1 = A.dot(v)
    scipy_r2 = At.dot(w)
    
    d1 = timeit.timeit('A.dot(v)',globals=locals(),number=test_count)
    d2 = timeit.timeit('At.dot(w)',globals=locals(),number=test_count)
    print("scipy matvec spent %.6fs" % d1)
    print("scipy rmatvec spent %.6fs" % d2)

    v = cp.asarray(v)
    w = cp.asarray(w)
    
    data = cp.ones((nnz,),dtype=np.float64)
    indices = cp.asarray(indices)
    indptr = cp.asarray(indptr)
    A = cp.sparse.csr_matrix((data,indices,indptr),shape=(M,N),dtype=np.float64)
    At = A.transpose().tocsr()

    cupy_r1 = cp.asnumpy(A.matvec(v))
    cupy_r2 = cp.asnumpy(At.matvec(w))
    
    d1 = timeit.timeit('A.matvec(v)',globals=locals(),number=test_count)
    d2 = timeit.timeit('At.matvec(w)',globals=locals(),number=test_count)
    print("cupy matvec spent %.6fs" % d1)
    print("cupy rmatvec spent %.6fs" % d2)

    
    assert np.allclose(cupy_r1,scipy_r1)
    assert np.allclose(cupy_r2,scipy_r2)
    
if __name__ == "__main__":
    np.random.seed(12345)
    main()

```
The sparse matrix is here:
[spmatrix.pkl.gz](https://github.com/cupy/cupy/files/3343980/spmatrix.pkl.gz)

**Comment by beam2d** [comment]
As for the interface, if the added algorithm runs faster than the current implementation, it is better to just replace the current implementation of `dot` method for the matrix-vector product case instead of adding methods (matvec and rmatvec) not existing in scipy.sparse.

**Comment by wonghang** [comment]
Thank you for the reply. OK. Let me work it out and submit a PR.

`dot` implementation of `cupy.sparse.csr_matrix` and `cupy.sparse.csc_matrix`  are just calling `__mul__`

I want to emphasis that the merge path algorithm in cuSPARSE does not support transpose operation. As a result, csc_matrix will not benefit from the change.

For `matvec(.)` and `rmatvec(.)`, they are in https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.LinearOperator.html
cupy.sparse does not have it currently.

**Comment by beam2d** [comment]
Thank you for the information of `matvec` and `rmatvec` in scipy.sparse; I did not notice that!

I do not think they are the right places to provide optimized implementations, though. How about using the merge path algorithm in `csr_matrix.__mul__` when the argument is a vector?

**Comment by wonghang** [comment]
Yes. I think it is better way. I am working on it. Wait for my PR.
