### ISSUE TITLE
compile_with_cache location change

### ISSUE THREAD

**Issue by hongjuny** [cupy/cupy#2296]
Got error at `cupy/cuda/compiler.py`, line 145, in compile_with_cache.
I guess the error has occurred because it attempted to access $HOME/.cupy, presumably it is a cache location.
Is there a way to change the location? Because, in the HPC system I am using, the $HOME is read-only...

Thank you very much!

**Comment by kmaehashi** [comment]
You can use `CUPY_CACHE_DIR` environment variable to change the cache location.
https://docs-cupy.chainer.org/en/latest/reference/environment.html
