### ISSUE TITLE
Add cupy.median()

### ISSUE THREAD

**Issue by deltadu** [cupy/cupy#2305]
Hi,
it would be great if cupy.median() could be added

**Comment by andy6975** [comment]
Is this issue still open? I would like to work on this. Thanks!

**Comment by jakirkham** [comment]
That would be great. Please let us know if you need anything. 🙂

**Comment by andy6975** [comment]
I am starting to work on this issue. Could you please tell me what is the path to cupy source? Thanks!

**Comment by andy6975** [comment]
Hi, I wanted to know if there are functions for the following tasks in CuPy?

* Partition: like np.partition()
* Swapaxes: like np.swapaxes()

**Comment by Harshan01** [comment]
I hope this issue is still open. I have made an implementation of `cupy.median` #3134 . I would appreciate any suggestions to improve it.

**Comment by jakirkham** [comment]
Yep, [that's right]( https://github.com/cupy/cupy/blob/e032b27b79a76003f85d91364d122904a15990a7/cupy/statistics/meanvar.py#L8 ). Thanks for all of your work on CuPy, Harshan 😄

**Comment by Harshan01** [comment]
Thanks for your suggestion. I have moved `median` from `statistics.order` to `statistics.meanvar`.

**Comment by rjhuijsman** [comment]
It looks like `cupy.median()` was introduced in `v8.0.0b2` ([release notes](https://github.com/cupy/cupy/releases/tag/v8.0.0b2))! 🎉
Thank you @Harshan01 !
