### ISSUE TITLE
Pandas Support

### ISSUE THREAD

**Issue by r1b** [cupy/cupy#233]
First of all - thank you for this wonderful project!

I use [Pandas](http://pandas.pydata.org/) frequently in my work. I am curious:

* Are there efforts underway to use cupy with pandas?
* In any case, how could that be accomplished? What would the challenges be?

**Comment by niboshi** [comment]
I'm not faimiliar with Pandas, but how about simply converting to NumPy arrays and then use the library as normal?
(You can convert CuPy arrays to NumPy counterpart with `ndarray.get` method. See [documentation](https://docs-cupy.chainer.org/en/stable/reference/ndarray.html#conversion-to-from-numpy-arrays).)
