### ISSUE TITLE
[Feature Request] Equivalent of numpy.isin

### ISSUE THREAD

**Issue by beckernick** [cupy/cupy#2331]
As a user, I'd like to be able to quickly and easily do the equivalent of `numpy.isin` with cupy.

To quote the NumPy docs, "isin is an element-wise function version of the python keyword `in`. isin(a, b) is roughly equivalent to np.array([item in b for item in a]) if a and b are 1-D sequences."

The NumPy documentation can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.isin.html), and the source code [here](https://github.com/numpy/numpy/blob/v1.16.1/numpy/lib/arraysetops.py#L601-L697).

```python
import numpy as np
​
arr = np.array([0, 4, 5])
np.isin(arr, [0,3])
# array([ True, False, False])
​
arr = np.array([0, 4, 5])
other = [0, 3]
np.isin(arr, other)
# array([ True, False, False])
​
arr = np.array([[0, 4, 5],
                [12, 4, 3]])
np.isin(arr, [0,3])
# array([[ True, False, False],
#       [False, False,  True]])
```

**Comment by UmashankarTriforce** [comment]
I'll work on this
