### ISSUE TITLE
Support new random number generator in NumPy 1.17

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#2349]
https://docs.scipy.org/doc/numpy/release.html#new-features
https://docs.scipy.org/doc/numpy/reference/random/index.html#module-numpy.random

**Comment by niteya-shah** [comment]
I am interested to work on this for gsoc 2020 and have submitted a draft proposal. Can I get some suggestions as to how I can improve it ? 
https://drive.google.com/file/d/1LXLU31iCgrZrysRtEQ1766iC1hFPQ-dh/view?usp=sharing

**Comment by kmaehashi** [comment]
This feature was implemented in #4177 with a limited set of distributions. See also #4557.
