### ISSUE TITLE
Cannot convert a list of cupy arrays into another cupy array

### ISSUE THREAD

**Issue by GenevieveBuckley** [cupy/cupy#2354]
I excepted that if you can do this:
```python
import numpy
numpy.array([numpy.array([1]), numpy.array([2])])
```
or even this:
```python
import cupy
import numpy
cupy.array([numpy.array([1]), numpy.array([2])])
```
```
array([[1],
       [2]])
```
... then we should also be able to do this with cupy:
```python
import cupy
cupy.array([cupy.array([1]), cupy.array([2])])
```
but this raises a ValueError. Is this expected or unwanted behaviour?

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
CuPy Version          : 5.4.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10000
CUDA Driver Version   : 10000
CUDA Runtime Version  : 10000
cuDNN Build Version   : 7301
cuDNN Version         : 7301
NCCL Build Version    : 2402
NCCL Runtime Version  : 2402

* Code to reproduce
```python
import cupy
cupy.array([cupy.array([1]), cupy.array([2])])
```

* Error messages, stack traces, or logs
```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-f09e98c35a24> in <module>()
      1 import cupy
----> 2 cupy.array([cupy.array([1]), cupy.array([2])])

/usr/local/lib/python3.6/dist-packages/cupy/creation/from_data.py in array(obj, dtype, copy, order, subok, ndmin)
     39 
     40     """
---> 41     return core.array(obj, dtype, copy, order, subok, ndmin)
     42 
     43 

cupy/core/core.pyx in cupy.core.core.array()

cupy/core/core.pyx in cupy.core.core.array()

ValueError: Unsupported dtype object
```

**Comment by kmaehashi** [comment]
This feature is implemented in #2081 (v7.0.0b1); please consider using the latest beta version.

**Comment by GenevieveBuckley** [comment]
Ok, thanks!

**Comment by thomasaarholt** [comment]
Just in case anyone like me is a bit stuck with supporting cupy 6 due to `conda install cupy` being currently limited to version 6:

You can use `cp.stack((cp.array(1), cp.array(2)))` instead.
```python
A, B = np.random.random((2,5,5))
np.testing.assert_array_almost_equal(np.array([A, B]), np.stack([A, B]))
```
