### ISSUE TITLE
Possibility of making `cufft.Plan1d` and `cufft.PlanNd` be a context manager?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2356]
This discussion begins in PR #2355, in which a new module `scipy.fft` is introduced to work with new upstream changes. It seems that it is impossible to deviate from the SciPy's backend API, see https://github.com/cupy/cupy/pull/2355#issuecomment-517325388:
> You won't be able to pass a `plan` argument through `scipy.fft` unless the argument is added to `scipy` itself.

@grlee77 @peterbell10 @asi1024 this makes me wonder whether we should turn cuFFT plans into a context manager for the long run to deal with strict API policies from upstream (i.e., SciPy). Perhaps I can make the following snippet possible:
```python
import cupy
import cupyx.scipy.fft as cu_fft
import scipy.fft
from cupy.fft import get_fft_plan  # move get_fft_plan() to this module 

x = cupy.arange(10)
fftplan = get_fft_plan(x)

with scipy.fft.set_backend(cu_fft), fftplan:
    scipy.fft.fft(x)  # Calls into cupyx, use fftplan, and returns a cupy array
```
A small change to `cupy/cuda/cufft.pyx`, which backs `cupy.fft`, `cupyx.scipy.fftpack`, and now `cupyx.scipy.fft`, to pick up the current plan (or to generate one if none) should be sufficient. (To be clearer, I expect that this works by examining if a cuFFT plan pointer is stored under the hood, similar to choosing a device using `with cupy.cuda.Device(0).use()`.)  

Note that the support of passing explicit cuFFT plans to `cupyx.scipy.fftpack` functions (as well as `get_fft_plan()` itself) is a deviation from `scipy.fftpack` API and was intentionally marked "experimental", so I'm not particularly worrying about breaking backward compatibility for now.

**Comment by peterbell10** [comment]
We were actually considering adding a `plan` argument before in scipy/scipy#10302 but the issue was closed after an internal plan cache was added to our backend. It may take some work to add this to SciPy's own backend but I think it would be worthwhile.

**Comment by leofang** [comment]
Thanks for brining up the SciPy discussion, @peterbell10. Is it possible to just add `plan=None` in SciPy as a placeholder, and let backend providers like pyFFTW or CuPy to handle it? This would require only minimum code change everywhere.

**Comment by peterbell10** [comment]
The idea has been brought up before but it could be quite surprising to users that the plans don't do anything by default. I can always float the idea on the SciPy mailing list though.
