### ISSUE TITLE
Array indexing of sparse matrices

### ISSUE THREAD

**Issue by jamestwebber** [cupy/cupy#2360]
After talking to @quasiben I've been looking into using CuPy as a shim to support sparse matrices in PyTorch (the current support is [not great](https://github.com/pytorch/pytorch/issues/9674)).

The gist is that I can fit a sparse matrix into GPU memory but not a dense one. So, the idea is to use a CuPy sparse matrix and a custom DataLoader: I should be able to quickly train a model by indexing into the CuPy matrix, densifying a batch of data, and doing a zero-copy conversion to a tensor to feed into my model.

Unfortunately it appears that CuPy's sparse matrices don't support array indexing, which would be the natural way to do this (in the sense that PyTorch's DataLoader class returns a list of integers to index into your data). There's definitely a way to get this working with single indices and `vstack` but I thought I'd raise an issue because scipy does support this and it'd be a lot cleaner for me.

Thanks!

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
CuPy Version          : 6.2.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 9000
CUDA Driver Version   : 9000
CUDA Runtime Version  : 9000
cuDNN Build Version   : 7402
cuDNN Version         : 7402
NCCL Build Version    : 2307
NCCL Runtime Version  : 2307
* Code to reproduce
```python
scipy_sparse = scipy.sparse.random(100, 100).tocsr()
scipy_sparse[[0,1],:] # this works for csr matrices

cupy_sparse = cupy.sparse.csr_matrix(scipy_sparse)
cupy_sparse[[0,1],:] # error :(
```
* Error messages, stack traces, or logs
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-70-425afa4195a2> in <module>
      3 
      4 cupy_sparse = cupy.sparse.csr_matrix(scipy_sparse)
----> 5 cupy_sparse[[0,1],:]

/opt/conda/lib/python3.7/site-packages/cupyx/scipy/sparse/compressed.py in __getitem__(self, slices)
    247                 return self._get_major_slice(major)
    248 
--> 249         raise ValueError('unsupported indexing')
    250 
    251     def _get_single(self, major, minor):

ValueError: unsupported indexing
```

**Comment by jakirkham** [comment]
It might be possible with the changes in `master` to select individual indices and concatenate them together. For example one can do this with a development build of CuPy.

```python
cupyx.scipy.sparse.vstack([cupy_sparse[0, :], cupy_sparse[1, :]])
```

**Comment by jamestwebber** [comment]
> It might be possible with the changes in `master` to select individual indices and concatenate them together.

Yeah I mentioned that approach above, but realistically it's not two indexes it's hundreds or thousands. I could `vstack` a list comprehension of rows but I suspect that will copy a bunch of memory? Even if not it's kind of a hacky addition to something that was already going to be hacky...

**Comment by jakirkham** [comment]
Ah ok. Sorry for missing that.

At worst it seems like that would double memory usage to reserve space for the copy. I don't know how tight your workloads run on the memory side. Do you know?

Yep that's fair. It's definitely hacky. Just thinking about things we have at our disposal today that might unblock this 🙂

**Comment by jamestwebber** [comment]
It really depends on the specific project, but if the data is some multiple of GPU memory then that would halve your potential batch size. Which may not be a big deal, but nice to avoid if possible.

I wouldn't really call this a blocker at the moment since I'm not trying to do anything in this space right now, and when I does it just took longer than it might have.

It was more like "oh does this solve my problem easily? No? Okay maybe someday". The more hacky it gets, the harder it is to use because other parts of the methods are going to change and might require more hacks. Ideally the PyTorch folks would solve this themselves.

**Comment by rgommers** [comment]
> Ideally the PyTorch folks would solve this themselves.

@jamestwebber we're picking this up, currently @pearu is writing an RFC for major improvements needed in PyTorch sparse support. There's already https://github.com/pytorch/rfcs/pull/4, and the bigger-picture RFC will be submitted to that same repo. If you have particular pain points, your input is very welcome.

**Comment by jamestwebber** [comment]
Great to hear, I'll look at that RFC soon and if I have anything to add I'll be sure to mention it.

**Comment by jamestwebber** [comment]
@rgommers I guess if you're working on that I should really get back to working on that scipy issue I promised...

**Comment by jakirkham** [comment]
This is planned to be in CuPy 8.0.0.

**Comment by jamestwebber** [comment]
Thanks for fixing this, I started using it about a week ago. I see about 2.5x speed increase in training my model when I can keep it entirely in GPU memory and convert to dense tensors on demand.

I wrote up my (very simple) solution [in a gist](https://gist.github.com/jamestwebber/6df95d77a47c367e2c3e2c8431d48f66) in case anyone wants to use it.

**Comment by quasiben** [comment]
Thanks for testing this out @jamestwebber ! Now for distributed GPUs :)
