### ISSUE TITLE
Implement 'circular' or 'wrap' mode for cupy.pad

### ISSUE THREAD

**Issue by mnicely** [cupy/cupy#2367]
I'm working on 2D convolution problem but need circular (wrap) padding. Would that be hard implement a wrap mode like numpy? 

https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html

**Comment by grlee77** [comment]
This already exists via `cupy.pad` or am I misunderstanding what you are asking for?

**Comment by grlee77** [comment]
Nevermind, I had forgotten I had implemented this locally, but never made a PR for it.

**Comment by mnicely** [comment]
From what I can tell, pad is able to do expand with constant values with ‘constant’, replication with ‘edge’, and reflection with ‘reflect’. I need wrap, sometimes considered ‘circular’. As an example, if I were to expand the right side by one column, it would be the same as the first column on the left side of the matrix. This is for cyclic convolution.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by grlee77** [comment]
Here is a gist with an implementation of `pad` that I had been using locally. I never made a full set of tests or started a PR here for it, but it should work. It is nearly a 1:1 copy of numpy.pad from NumPy 1.17.
https://gist.github.com/grlee77/ea0c34f2b68cd376b4d1013b9cdcd06d

example (navigate to the folder containing `arraypad.py` from the gist above:
```Python
import cupy
pad(cupy.arange(6), 4, mode='wrap')
```
gives:
```array([2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3])```

If there is interest from the cupy devs, I can try to find time to finish a PR for this here.

**Comment by Crissman** [comment]
@grlee77 Yes, we're interested! Please do make a PR for this.

**Comment by grlee77** [comment]
@Crissman: Great, I have now opened a PR for this (#2399)
