### ISSUE TITLE
Incorrect behavior with empty arrays for `linalg.qr` and `linalg.svd`

### ISSUE THREAD

**Issue by IvanYashchuk** [cupy/cupy#2371]
`qr` and `svd` routines raise `CUSOLVERError: CUSOLVER_STATUS_INVALID_VALUE` for zero-sized input arrays.
NumPy supports this kind of input for `qr`, `svd` since 1.16
https://github.com/numpy/numpy/blob/master/doc/release/1.16.0-notes.rst#linalglstsq-linalgqr-and-linalgsvd-now-work-with-empty-arrays
The problem is that when calling cuSOLVER routines leading dimension is passed as `input.shape[0]` but it should be `max(1, input.shape[0])`.

**Comment by toslunar** [comment]
```
>>> for xp in (numpy, cupy):
...     print(f'{xp.__name__}: {[x.shape for x in xp.linalg.svd(xp.empty((0, 2)))]}')
...
numpy: [(0, 0), (0,), (2, 2)]
cupy: [(2, 2), (0,), (0, 0)]
```
