### ISSUE TITLE
Incorrect behavior of in-place operation between ndarrays share same memory space

### ISSUE THREAD

**Issue by asi1024** [cupy/cupy#2407]
Incorrect behavior of in-place operation between ndarrays which
- share same memory space and
- have different strides.

Test code:
```py
import numpy
import cupy

for xp in (numpy, cupy):
    x = xp.arange(10000).reshape(100, 100)
    x += x.T
    print(xp.__name__, ':', x.sum())  # Expected: 99990000 = 10000 * (10000 - 1)
```
Output:
```py
numpy : 99990000
cupy : 100026222
```

**Comment by leofang** [comment]
Looks like this is a different manifestation of the same problem #2405?

**Comment by asi1024** [comment]
To resolve this issue, we need to support `cupy.shares_memory` or `cupy.may_share_memory` and copy inputs before the operation.
