### ISSUE TITLE
import pytorch before cupy will make function 'sort' and 'argsort' not work properly

### ISSUE THREAD

**Issue by tinyalpha** [cupy/cupy#2409]
Hi, I am developing my project using pytorch and cupy. I find that just import pytorch before cupy will cause segments error (when calling `sort` or `argsort` for float array). But if I exchange the import order, it back to normal, which seems very strange. 

* Code to reproduce

```python
import torch
import cupy as cp

print( cp.argsort(cp.array([3,1,4], dtype=int)) )
print( cp.sort(cp.array([3,1,4], dtype=int)) )
print( cp.sort(cp.array([3,1,4], dtype=float)) )
print( cp.argsort(cp.array([3,1,4], dtype=float)) )

[1 0 2]
[1 3 4]
Segmentation fault (core dumped)
```

```python
import cupy as cp
import torch

print( cp.argsort(cp.array([3,1,4], dtype=int)) )
print( cp.sort(cp.array([3,1,4], dtype=int)) )
print( cp.sort(cp.array([3,1,4], dtype=float)) )
print( cp.argsort(cp.array([3,1,4], dtype=float)) )

[1 0 2]
[1 3 4]
[1. 3. 4.]
[1 0 2]
```

* Conditions 
CuPy Version          : 6.2.0
CUDA Root             : /usr
CUDA Build Version    : 10000
CUDA Driver Version   : 10000
CUDA Runtime Version  : 10000
cuDNN Build Version   : 7500
cuDNN Version         : 7500
NCCL Build Version    : 2402
NCCL Runtime Version  : 2402

**Comment by emcastillo** [comment]
I can't reproduce

Pytorch 1.1.0

```
  CuPy Version          : 6.2.0
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 10000
  CUDA Driver Version   : 10000
  CUDA Runtime Version  : 10000
  cuDNN Build Version   : 7500
  cuDNN Version         : 7500
  NCCL Build Version    : 2402
  NCCL Runtime Version  : 2402
```

Both codes worked fine.

Python version?

**Comment by tinyalpha** [comment]
Python 3.7.4
Pytorch 1.1.0

**Comment by kmaehashi** [comment]
Please feel free to reopen if it reproduce with the latest PyTorch.

**Comment by twmht** [comment]
@kmaehashi 

I can reproduce the error when playing both pytorch and cupy together.

my pytorch version is 1.8.1.

is it safe to compile cupy thrust with `-Xcompiler=-fno-gnu-unique`?
