### ISSUE TITLE
Missing error checks for cuSOLVER calls

### ISSUE THREAD

**Issue by IvanYashchuk** [cupy/cupy#2414]
Some linalg routines do not check the `dev_info` variable for errors after calling cuSOLVER.
If it is a negative number, then `linalg.LinAlgError` should be raised.

Missing checks:
`inv` https://github.com/cupy/cupy/blob/master/cupy/linalg/solve.py#L287-L295
`qr` https://github.com/cupy/cupy/blob/master/cupy/linalg/decomposition.py#L163-L176

**Comment by niboshi** [comment]
I rather feel we should not check the error because it incurs host-device synchronization.

**Comment by hvy** [comment]
Did you say we have other routines which incurred similar design choices (and where we choose not to check the status)?

**Comment by niboshi** [comment]
Yes, I think it was `cupy.nanargmin`.

**Comment by hvy** [comment]
So `cupy.nanargmin` returns an ndarray with `-1` instead of raising an error like NumPy. It's well behaved. We cannot really guarantee that with the cuSOLVER routines and have to leave it UB since it's not documented by the cuSOLVER documentation AFAIK and my concern is that this can make debugging a pain if you'd silently get wrong results.

**Comment by hvy** [comment]
Generalizing it beyond `inv` and `qr`, how about giving the user the possibility to control this behavior through some configuration, for instance under `cupy.linalg` (unless there's some existing configuration in CuPy that's already suitable). The default behavior would obviously still need to be discussed.

**Comment by niboshi** [comment]
Yes, that's exactly what I am thinking.
Not under `cupy.linalg`. It should be useful for the case of `cupy.nanargmin`.

**Comment by hvy** [comment]
@IvanYashchuk How about addressing this bug using some environment variable to allow the user to control whether to check `devInfo` or not? We need to discuss the default behavior but I'm feeling it's better to make it synchronous since errors are most likely difficult to spot.

Another slightly more demanding idea would be to queue the D2H transfer of the `devInfo` and allow the user to query it (or some smart wrapper of it) at a later time.

**Comment by hvy** [comment]
Introducing a configuration mechanism is a more proper approach, again expanding it beyond these two solver routines. It can be discussed here https://github.com/cupy/cupy/issues/2436

**Comment by niboshi** [comment]
Anyway that would be a temporary API (will taken over by #2436), so I think an environment variable is better than a function to query an error.

As for whether or not to make it default to synchronize, I think the default should be to skip the check and run asynchronously, as it's the current policy of CuPy to weigh performance over convenience.

**Comment by hvy** [comment]
I agree that an environment variable suffices. D2H would introduce more interfaces than needed and sounds a bit overkill.

You mean it's agains the policy? I'm okay with that as long as it's clearly documented, how it behaves by default and how one can control it.

**Comment by kmaehashi** [comment]
Another case that performs sync to retrieve `devInfo` to follow [NumPy spec](https://docs.scipy.org/doc/numpy-1.16.1/reference/generated/numpy.linalg.slogdet.html):
> If the determinant is zero, then `sign` will be 0 and `logdet` will be -Inf.

https://github.com/cupy/cupy/blob/97c72a3c729f63fe86bc2349fb9c4433bbd9eeab/cupy/linalg/norms.py#L246-L249

**Comment by niboshi** [comment]
@hvy Unfortunately it's not documented, but if my understanding is correct, it has been the central policy since the beginning of the development.

For example, many functions do not accept `numpy.ndarray`s because supporting that would expose users to unexpected synchronization that is difficult to even notice.

**Comment by hvy** [comment]
Okay that makes sense. I'll create a draft PR.

**Comment by hvy** [comment]
The draft is ready for review, #2437.

**Comment by anaruse** [comment]
Just FYI.  `_batched_inv` has error checks after cuSOLVER call.

https://github.com/cupy/cupy/blob/993ddc4ab60d1ad93836c2a7be66528a9eb78231/cupy/linalg/solve.py#L344-L356

**Comment by hvy** [comment]
I completely missed that. I should update the draft.

**Comment by anaruse** [comment]
I could be wrong but I think the default behavior of #2437, not to check the `devInfo`, is problematic..

**Comment by hvy** [comment]
Thanks for the input. The cuBLAS documentation is not too generous in explaining this device status code and would be grateful for any comments from an NVIDIA developer. Could you elaborate on the problem?

**Comment by hvy** [comment]
I also noticed that `_batched_inv` has error checks after cuBLAS calls and not cuSOLVER. This means that we might want to to introduce another flag in #2437 for controlling cuBLAS separately.

**Comment by hvy** [comment]
Okay so the problem was that the results could be wrong and that it can be difficult for a user to detect (discussed this in person with @anaruse). We may need to discuss the default behavior further.

**Comment by hvy** [comment]
To better understand the impact of aligning the checking of `dev_info` in various CuPy routines, I tried to list all `cupy.linalg.*` and `cupyx.scipy.linalg.*` that would be affected (somehow depends on a cuSOLVER call that involves `dev_info`).
 
- Currently checking `dev_info` (synchronizing): `lu_factor`, `lu_solve`, `det` (calls `slogdet`), `slogdet`, `matrix_rank` (calls `svd`), `solve`, `tensorsolve` (calls `solve`), `svd`, `cholesky`, `lstsq` (calls `svd`), `pinv` (calls `svd`).	
- Currently ignoring `dev_info` (asynchronous): `eigh`, `eigvalsh`, `inv`, `tensorinv` (calls `inv`), `matrix_power` (calls `inv`).
- Currently checking and ignoring `dev_info` (involves multiple calls in a single routine) (synchronizing): `qr`.

I wouldn't dare to comment on how frequently each of those routines are called in user code, but the numbers shows that we have more than twice as many routines that are synchronous.

**Comment by hvy** [comment]
People apparently call `cholesky` and check if it raises an error in order to find out if some matrix is positive definite or not. If users have written this kind of code with CuPy, it'd obviously break if aligned to not check `dev_info`. https://stackoverflow.com/a/16266736/11409592
