### ISSUE TITLE
Subclassing NumPy's RandomState object

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#2421]
Currently [CuPy's `RandomState` object]( https://github.com/cupy/cupy/blob/68eabf326482e29e266fa071a1cdf6a6cff7cbcc/cupy/random/generator.py#L22 ) simply subclasses `object`. However it would be helpful if it subclassed NumPy's `RandomState` object. This way users could be guaranteed the same API and could more easily drop-in a CuPy `RandomState` object where a NumPy `RandomState` object is expected.

**Comment by kmaehashi** [comment]
I think it is too aggressive to inherit NumPy's `RandomState` as the API is not completely compatible. Do you have any specific code/use-case that requires this?

**Comment by jakirkham** [comment]
Yeah other libraries (like scikit-learn) often allow users to supply their own `RandomState` objects. However they check to see if they are instances of NumPy's `RandomState`. So subclassing NumPy's `RandomState` would allow CuPy's `RandomState` to be used easily with these other libraries.

**Comment by jakirkham** [comment]
Given `RandomState` is part of the [legacy random generation API in NumPy]( https://numpy.org/doc/1.26/reference/random/legacy.html#legacy-random-generation ), think this doesn't make sense anymore. A better solution would be to use the new random generation API in NumPy & CuPy

As to the scikit-learn use case I mentioned, maybe a better solution will be found in issue ( https://github.com/scikit-learn/scikit-learn/issues/22352 ) or other related issues
