### ISSUE TITLE
Possibly redundant lines in `cupy.cuda.function._launch()`?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2439]
These two lines seem to be superseded by the usage of `kargs`:
https://github.com/cupy/cupy/blob/e7c1086c04b782133633b6b10bd120ef1a699086/cupy/cuda/function.pyx#L121
https://github.com/cupy/cupy/blob/e7c1086c04b782133633b6b10bd120ef1a699086/cupy/cuda/function.pyx#L127
I suppose they can be removed?

**Comment by beam2d** [comment]
It looks they can be removed. Could you send a PR?

**Comment by leofang** [comment]
Thanks for confirmation, @beam2d. Sure, see #2449.

**Comment by asi1024** [comment]
@leofang @beam2d These lines seem to be needed to prevent the contents of the pointers `kargs` being freed before referred.
`args` are converted to `CPointer` type, and passed to `driver.launchKernel` by pointer at the end of function `_launch`. If `pargs` are removed, the `CPointer` object created at L126 will be freed at the end of `for` scope.

**Comment by leofang** [comment]
Ah...Yet another lifetime trap....Sorry that I overlooked and made noise 🙁 Thank you @asi1024 for pointing this out.
