### ISSUE TITLE
Handle PCI bus ID

### ISSUE THREAD

**Issue by gwtnb** [cupy/cupy#2440]
`cudaDeviceGetByPCIBusId` converts a PCI bus ID string to a device ID integer. It may be useful to add a feature which handles a PCI bus ID string to specify a device. The feature may be split into two functions:

- a thin wrapper of `cudaDeviceGetByPCIBusId`
- a conversion function from a PCI bus ID string to cupy `Device` object.

**Comment by leofang** [comment]
This is closed by #2531.
