### ISSUE TITLE
Feature Request: cupyx implementation of scipy.sparse.linalg.spsolve

### ISSUE THREAD

**Issue by lastephey** [cupy/cupy#2457]
Dear CuPy developers,

We would like to request that you consider implementing scipy.sparse.linalg.spsolve.

We are exploring porting some part of the DESI spectroscopic pipeline to GPUs (https://github.com/desihub) and we would like to use scipy.sparse.linalg.solve in CuPy. 

At the moment we are using cp.linalg.solve instead, but we are finding that it is the current bottleneck in our workload:
[overview_gpu_only.txt](https://github.com/cupy/cupy/files/3597482/overview_gpu_only.txt)

If you would like more information please let us know.

Thank you very much,
Laurie Stephey

**Comment by kmaehashi** [comment]
Thank you for raising a feature request!  We welcome pull-request for this feature if anyone is interested in writing it.

@lastephey Please be aware that `line_profiler` results may not be correct for CuPy code as CuPy (CUDA) runs asynchronously. You can use nvprof/nvvp to diagnose which CUDA kernel is actually taking time.

**Comment by lastephey** [comment]
I see, thank you for the profiling advice @kmaehashi . In the future we will use nvprof/nvvp.

**Comment by ashkspark** [comment]
Regarding this issue, does CuPy have UMFPACK sparse direct solver?
