### ISSUE TITLE
cp.linalg.inv does not support a complex-valued matrix

### ISSUE THREAD

**Issue by imtoolkit** [cupy/cupy#2464]
I sincerely appreciate the outstanding efforts having been devoted to this project. It seems that cp.linalg.inv does not support a complex-valued matrix. For example, one can reproduce the same situation as follows:

    import numpy as np
    A = np.eye(1) + 1.j
    print(A.dot(np.linalg.inv(A))) #=> [[1.+0.j]]
    A = np.eye(2) + 1.j
    print(A.dot(np.linalg.inv(A)))  # => [[1.+5.55111512e-17j, 0.+2.77555756e-17j], [0.+5.55111512e-17j, 1.+5.55111512e-17j]]
    # This NumPy implementation returns the identity matrix.

    import cupy as cp
    A = cp.eye(1) + 1.j
    print(A.dot(cp.linalg.inv(A))) #=> [[1.+1.j]]
    A = cp.eye(2) + 1.j
    print(A.dot(cp.linalg.inv(A)))  # => [[2.+0.j, 0.+1.j], [1.+1.j, 1.+1.j]]
    # This CuPy implementation returns somewhat strange matrices.

According to the current implementation, cp.linalg.inv supports the dtypes of 'f' and 'd' only, although the getrf and getrs functions originally support the data types of cuComplex and cuDoubleComplex.
https://github.com/cupy/cupy/blob/master/cupy/linalg/solve.py#L236

The followings are my environment information.

    $ cat /etc/os-release
    NAME="Ubuntu"
    VERSION="18.04.3 LTS (Bionic Beaver)"

    $ python -c 'import cupy; cupy.show_config()'
    CuPy Version          : 6.3.0
    CUDA Root             : /usr/local/cuda-10.1
    CUDA Build Version    : 10010
    CUDA Driver Version   : 10010
    CUDA Runtime Version  : 10010
    cuDNN Build Version   : 7602
    cuDNN Version         : 7602
    NCCL Build Version    : 2402
    NCCL Runtime Version  : 2402

It is highly appreciated if CuPy supports the avobe complex-valued operation. Many thanks in advance.

**Comment by leofang** [comment]
possible dup: #2071

**Comment by imtoolkit** [comment]
Dear @leofang, I appreciate your immediate notice. Since this cp.linalg.inv issue has been already labeled as `contribution-welcome`, I would like to close this one -- with thanks.

**Comment by leofang** [comment]
it doesn't hurt to keep it open I think. Multiple dup issues could perhaps help prioritize things and signal the need.

**Comment by leofang** [comment]
@imtoolkit check out #2468 if you have time.

**Comment by imtoolkit** [comment]
Thanks to @leofang 's immediate patch and @hvy 's appropriate Jenkins fix, cp.linalg.inv does now support a complex-valued matrix. I really appreciate your efforts!

**Comment by hvy** [comment]
Thanks for mentioning, Jenkins was fixed by @kmaehashi 🙂
