### ISSUE TITLE
`import cupy` causes `ImportWarning`

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#2476]
Reported [here](https://github.com/chainer/chainer/pull/8131#issuecomment-532521654).

(by running with `python -W error`)
> ```
> >>> import cupy
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "******/python3.7/site-packages/cupy/__init__.py", line 12, in <module>
>     from cupy import core  # NOQA
>   File "******/python3.7/site-packages/cupy/core/__init__.py", line 1, in <module>
>     from cupy.core import core  # NOQA
>   File "cupy/core/core.pyx", line 1, in init cupy.core.core
>   File "******/python3.7/site-packages/cupy/cuda/__init__.py", line 4, in <module>
>     from cupy.cuda import compiler  # NOQA
>   File "******/python3.7/site-packages/cupy/cuda/compiler.py", line 12, in <module>
>     from cupy.cuda import function
>   File "cupy/cuda/memory.pxd", line 11, in init cupy.cuda.function
>   File "cupy/cuda/memory.pyx", line 1, in init cupy.cuda.memory
>   File "fastrlock/_lock.pxi", line 4, in init fastrlock.rlock
> ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
> ```

It is actually `fastrlock` that is causing `ImportWarning`:
```
$ python -W error -c 'import fastrlock.rlock'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "fastrlock/_lock.pxi", line 4, in init fastrlock.rlock
ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
```

**Comment by emcastillo** [comment]
Seems to be a Cython issue
https://github.com/cython/cython/issues/1720

**Comment by emcastillo** [comment]
Installing `fastrlock==0.3` makes this error dissapear, however now theres a new one
```
    import pytest
  File "/home/ecastill/anaconda3/lib/python3.7/site-packages/pytest.py", line 7, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/home/ecastill/anaconda3/lib/python3.7/site-packages/_pytest/assertion/__init__.py", line 12, in <module>
    from _pytest.assertion import rewrite
  File "/home/ecastill/anaconda3/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 8, in <module>
    import imp
  File "/home/ecastill/anaconda3/lib/python3.7/imp.py", line 33, in <module>
    DeprecationWarning, stacklevel=2)
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```

**Comment by emcastillo** [comment]
Should we force fastrlock to be 0.3 in the requirements?
pytest is restricted to 4.1 only in our infra
