### ISSUE TITLE
Offer a `cupy.cuda.get_allocator` , and a pinned allocator that can associate with a particular device. Current workaround allows 110x speed over Pytorch CPU pinned tensors

### ISSUE THREAD

**Issue by Santosh-Gupta** [cupy/cupy#2481]
I am filing these requests on the suggestion of this stackoverflow answer

https://stackoverflow.com/questions/57752516/how-to-use-cuda-pinned-zero-copy-memory-for-a-memory-mapped-file

Which is an answer to how to pinn cupy tensors to CPU memory. This is important, because pinned Cupy tensors with dlpack offer the fastest CPU<->GPU transfer for Pytorch cuda variables. 

I have made a library around this method, which can achieve speeds up to 110x than Pytorch pinned cpu tensors. 

https://github.com/Santosh-Gupta/SpeedTorch

Here is the direct issue suggestions from the stackoverflow answer

> It appears to me that currently, cupy doesn't offer a pinned allocator that can be used in place of the usual device memory allocator, i.e. could be used as the backing for cupy.ndarray. If this is important to you, you might consider filing a cupy issue.

> after doing what you need with pinned memory (allocations) you should probably revert the cupy allocator to its default value. Unfortunately, unlike cupy.cuda.set_allocator, I did not find a corresponding cupy.cuda.get_allocator, which strikes me as a deficiency in cupy, something that also seems worthy of filing a cupy issue to me. 

> Ordinary device memory associated with cupy's default device memory allocator, has an association with a particular device. pinned memory need not have such an association, however our trivial replacement of BaseMemory with a lookalike class means that we are suggesting to cupy that this "device" memory, like all other ordinary device memory, has a specific device association. In a single device setting such as yours, this distinction is meaningless. However, this isn't suitable for robust multi-device use of pinned memory. For that, again the suggestion would be a more robust change to cupy, perhaps by filing an issue.

**Comment by niboshi** [comment]
Probably related to #1899.

**Comment by emcastillo** [comment]
I think that the main reason behind the original stackoverflow post might be this
https://github.com/cupy/cupy/blob/master/cupy/core/core.pyx#L1945

Even though the array is mem-mapped, it is unraveled creating a copy in the pinned host memory and then t that object is transferred to the device.

**Comment by Santosh-Gupta** [comment]
Some details on how it's speeding up transfer processes in certain cases for Pytorch

https://discuss.pytorch.org/t/introducing-speedtorch-4x-speed-cpu-gpu-transfer-110x-gpu-cpu-transfer/56147

**Comment by emcastillo** [comment]
#2489 adds the `get_allocator`

**Comment by Santosh-Gupta** [comment]
Heads up, what's causing the speed up in Pytorch is "masquerading the pinned-memory CPU tensor as a cupy GPU tensor and using the cupy GPU indexing kernels". 

from 

https://discuss.pytorch.org/t/introducing-speedtorch-4x-speed-cpu-gpu-transfer-110x-gpu-cpu-transfer/56147/2

So unless the Cupy CPU indexing kernels are more optimized at lower numbers of cores than the Pytorch cpu indexing kernels, then workout around described here

https://stackoverflow.com/questions/57752516/how-to-use-cuda-pinned-zero-copy-memory-for-a-memory-mapped-file

Will probably still be used for the Pytorch speedup.
