### ISSUE TITLE
`concatenate` not compatible with NumPy

### ISSUE THREAD

**Issue by liwt31** [cupy/cupy#2486]
According to the [NumPy 1.17 document](https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html#numpy.concatenate), `np.concatenate` supports `axis=None` in which case arrays are flattened before use. Currently, CuPy doesn't support the behavior.

This should be easy to implement if performance is not crucial.

**Comment by beam2d** [comment]
Interesting, I didn't know that feature! Are you interested in contributing?

**Comment by liwt31** [comment]
I'd be glad to! Working on it
