### ISSUE TITLE
pip install problem: Could not find a version that satisfies the requirement cupy-cuda100

### ISSUE THREAD

**Issue by rjurney** [cupy/cupy#2490]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - Conda version 4.7.11
  - Python 3.7.4
  - pip version 19.2.3
  - CuPy version 6.3.0
  - OS/Platform Mac OS X
  - CUDA version 10.0
* `pip install cupy-cuda100==6.3.0`
* Error messages, stack traces, or logs

```bash
pip install cupy-cuda100==6.3.0

Collecting cupy-cuda100==6.3.0
  ERROR: Could not find a version that satisfies the requirement cupy-cuda100==6.3.0 (from versions: none)
ERROR: No matching distribution found for cupy-cuda100==6.3.0
```

**Comment by leofang** [comment]
It's because the CuPy team stoped building wheels for Mac OS X for a while. Check out the wheel list on PyPI: https://pypi.org/project/cupy-cuda100/#files

**Comment by kmaehashi** [comment]
Actually we have never published a wheel for macOS.
(Also note that CUDA won't work with the latest macOS Mojave)
You can try building it from source.

**Comment by leofang** [comment]
@kmaehashi it is a known problem that building from source isn't working on Mac, see https://github.com/cupy/cupy/issues/952#issuecomment-491635935 and links there. Are you able to take a look?

**Comment by kmaehashi** [comment]
Mac wheels will not be provided as NVIDIA dropped support for it
