### ISSUE TITLE
pip install fails on ubuntu

### ISSUE THREAD

**Issue by xuzhang5788** [cupy/cupy#2507]
When I use $pip install cupy, or I install it from the source, both I got:

ERROR: Complete output from command python setup.py egg_info:
    ERROR: Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'wheel_includes': [], 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}
    
    -------- Configuring Module: cuda --------
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    In file included from /usr/include/cuComplex.h:59:0,
                     from /usr/include/cublas_api.h:73,
                     from /usr/include/cublas_v2.h:65,
                     from /tmp/tmpniwko91p/a.cpp:1:
    /usr/include/math.h:31:10: fatal error: bits/math-vector.h: No such file or directory
     #include <bits/math-vector.h>
              ^~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    command 'gcc' failed with exit status 1
    
    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************
    
    Build Environment:
      Include directories: ['/usr/include']
      Library directories: ['/usr/lib']
      nvcc command       : ['/usr/bin/nvcc']
    
    Environment Variables:
      CFLAGS          : (none)
      LDFLAGS         : (none)
      LIBRARY_PATH    : (none)
      CUDA_PATH       : (none)
      NVTOOLSEXT_PATH : (none)
      NVCC            : (none)
    
    Modules:
      cuda      : No
        -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
        -> Check your CFLAGS environment variable.
    
    ERROR: CUDA could not be found on your system.
    Please refer to the Installation Guide for details:
    https://docs-cupy.chainer.org/en/stable/install.html
    
    ************************************************************
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4y8z78w6/cupy/setup.py", line 120, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "/tmp/pip-install-4y8z78w6/cupy/cupy_setup_build.py", line 632, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "/tmp/pip-install-4y8z78w6/cupy/cupy_setup_build.py", line 387, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-4y8z78w6/cupy/

**Comment by emcastillo** [comment]
Do you have cuda installed?

**Comment by xuzhang5788** [comment]
@emcastillo 
Yes. It is cuda10

**Comment by emcastillo** [comment]
`ERROR: CUDA could not be found on your system.`

Seems like you don't have the cuda paths correctly configured.

**Comment by kmaehashi** [comment]
If you have no special reasons to build from source, I'd suggest you to use wheels.
https://docs-cupy.chainer.org/en/latest/install.html#install-cupy

**Comment by jiahaosuda** [comment]
> @emcastillo
> Yes. It is cuda10

Hello! I also met the problem when I tried to install cupy. Have you already solved the problem? And how did you solve the problem? Thanks!

**Comment by xuzhang5788** [comment]
@jiahaosuda 
I gave it up. I tried several methods to install it, but no one worked. unfortunately, they made my system crushed. So, it took my time to restore the system. So, I gave up.
