### ISSUE TITLE
Comparing `numpy.ndarray` and `cupy.ndarray`

### ISSUE THREAD

**Issue by UmashankarTriforce** [cupy/cupy#2515]
Is it possible to implement a method which compares `numpy.ndarray` and `cupy.ndarray`?

```
>>> a = cupy.array([1, 2, 3])
>>> b = numpy.array([1, 2, 3])
>>> a == b
array([True, True, True])
```

**Comment by niboshi** [comment]
We intentionally prohibit this kind of mixing of `numpy.ndarray` and `cupy.ndarray`, because that would inherently lead to host-device synchronization which greatly degrades performance, and it's difficult to spot for users.

Thank you for raising an issue, anyway!
