### ISSUE TITLE
Write unit tests for older protocols of __cuda_array_interface__

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#2521]
#2491 has updated the supported protocol version to 2, and it's tested.

CuPy should also ensure protocol 0 and 1 are accepted.

**Comment by leofang** [comment]
Before adding a compatibility test, we need to first backport #2491 to v6, see numba/numba#4661. @niboshi I could work on the tests once this is done.

**Comment by niboshi** [comment]
Why do you think #2491 needs to be backport first?
Conversely I think the test is needed first, because otherwise backporting it could break support of older protocols in v6.

**Comment by niboshi** [comment]
Simply backporting #2491 without appropriate tests could break older protocols in v6.
I think we should write the tests first and backport them altogether.

**Comment by leofang** [comment]
> Simply backporting #2491 without appropriate tests could break older protocols in v6.

The updated implementation of `_convert_object_with_cuda_array_interface()` guarantees backward compatibility. The problem in numba/numba#4661 is that v6.4.0 did not support CUDA arrays compliant with the new v3 protocol. This is why I suggested backport first.

> I think we should write the tests first and backport them altogether.

I have no objection to this. Would you like me to fire up a backport PR with the compatibility tests included?

**Comment by niboshi** [comment]
>> Simply backporting #2491 without appropriate tests could break older protocols in v6.
>
>The updated implementation of `_convert_object_with_cuda_array_interface()` guarantees backward compatibility. The problem in numba/numba#4661 is that v6.4.0 did not support CUDA arrays compliant with the new v2 protocol. This is why I suggested backport first.

In #2491 there's no test for older protocols. In that sense there's no "guarantee" for backward compatibility. That's why we need test first.


>> I think we should write the tests first and backport them altogether.
>
>I have no objection to this. Would you like me to fire up a backport PR with the compatibility tests included?

We can do that, but if you prefer, you can as well.

**Comment by leofang** [comment]
> > I have no objection to this. Would you like me to fire up a backport PR with the compatibility tests included?
> 
> We can do that, but if you prefer, you can as well.

OK. Let me make a first pass. I was the one pushing the protocol renewal, and I feel I'm somewhat responsible for the aftermath 😅

**Comment by niboshi** [comment]
Oh, it's all our responsibility once PRs are merged.
You don't have to feel like that, but thank you so much anyway! 🙏

**Comment by leofang** [comment]
See #2534.

**Comment by leofang** [comment]
It'd be nice to give a short warning like in numba/numba#4682 about the protocol update in the release notes of v6.5.0 and v7.0.0.

**Comment by leofang** [comment]
@niboshi Would you like to backport #2491 and #2536 now that both are merged?

**Comment by niboshi** [comment]
@leofang Yes, I've made a backport PR #2669. Thanks!
