### ISSUE TITLE
Support other boundary modes in convolve/correlate

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#2525]
Would be good to support the other `mode` arguments in `convolve` and `correlate`. Currently [only a few are supported]( https://github.com/cupy/cupy/blob/6c4799638abb046d7e0512ff07d7c4a38e9ba97a/cupyx/scipy/ndimage/filters.py#L100-L102 ).

At a first pass, it would be great to just use `cupy.pad` to do this and trim off the excess after convolution or correlation. At a second pass, it should be possible to do this without constructing a new array. It's unclear how much savings one would get though.

**Comment by grlee77** [comment]
It seems that it is already supported. I think maybe you missed the `not` in ```if mode not in"  in the line you linked?

**Comment by jakirkham** [comment]
Yep you are right. Thanks for the correction. Have rescoped this to handling all other boundary modes that are not supported.

**Comment by grlee77** [comment]
Do you mean adding support for other modes supported by `cupy.pad`, but not by `scipy.ndimage`? (I think all the modes available in `ndimage` are implemented)

As you may be aware, there are unfortunately some differences in naming conventions among the modes in `ndimage` and `pad`. Particular confusing is that:

pad's `'mirror'` is equivalent to ndimage's `'reflect'`
pad's `'reflect'` is equivalent to ndimage's `'symmetric'`

**Comment by anaruse** [comment]
I also think all modes available in scipy.ndimage are already supported.  Am I missing something?
https://github.com/scipy/scipy/blob/4bfc152f6ee1ca48c73c06e27f7ef021d729f496/scipy/ndimage/_ni_support.py#L38-L52

**Comment by kmaehashi** [comment]
@jakirkham As commented above all modes available in SciPy are implemented in CuPy. Please feel free to reopen if you have further requests!

**Comment by quasiben** [comment]
The convolve mode `same` is currently not supported.  To motivate a use-case, `same` is used in the skimage library: 

https://github.com/scikit-image/scikit-image/blob/967886138a28727f954048b8a8ce1c295d857476/skimage/restoration/deconvolution.py#L370-L371

If you'd like me to open a new issue I'd be happy to

**Comment by quasiben** [comment]
Apologies, I think i've conflated scipy.ndimage.convole and scipy.signal convolve
