### ISSUE TITLE
Add 'axes' option to ufuncs

### ISSUE THREAD

**Issue by SebastianSemper** [cupy/cupy#2547]
It would be nice to replicate the feature added in numpy 1.15:

> **axes**: A list of tuples with indices of axes a generalized ufunc should operate on. For instance, for a signature of (i,j),(j,k)->(i,k) appropriate for matrix multiplication, the base elements are two-dimensional matrices and these are taken to be stored in the two last axes of each argument. The corresponding axes keyword would be [(-2, -1), (-2, -1), (-2, -1)]. For simplicity, for generalized ufuncs that operate on 1-dimensional arrays (vectors), a single integer is accepted instead of a single-element tuple, and for generalized ufuncs for which all outputs are scalars, the output tuples can be omitted.

In my special case, I would need this in cupy.matmul.

**Comment by kmaehashi** [comment]
Thanks for the catch, and yes, #2552 was created during discussing this issue.

**Comment by kmaehashi** [comment]
Discussed in the team today. Closing this issue as it is now tracked in #2552.
