### ISSUE TITLE
cupy.cuda.runtime.CUDARuntimeError: cudaErrorNoDevice: no CUDA-capable device is detected

### ISSUE THREAD

**Issue by say2sarwar** [cupy/cupy#2549]
cupy.show_config()
CuPy Version          : 6.4.0
CUDA Root             : /usr/local/cuda-10.0
CUDA Build Version    : 10000
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10000
cuDNN Build Version   : 7603
cuDNN Version         : 7603
NCCL Build Version    : 2402
NCCL Runtime Version  : 2402
CuPy Version: 6.4.0
OS: Ubuntu 18.04
Cuda: 10.0
cuDNN version: 7.5
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

with all the information mention above. i am still getting error cudaErrorNoDevice.
i installed cupy using pip install cupy-cuda100
i tried using anacoda but the issue is the same.

**Comment by emcastillo** [comment]
Hello,

Do you get your gpus listed in the output of `nvidia-smi`?

**Comment by say2sarwar** [comment]
I have only one GPU and it's listed. output is below. the GPU is working without CUPY. but CUPY create this issue. 
![Screenshot from 2019-10-17 18-02-36](https://user-images.githubusercontent.com/34134990/66999399-82eb4580-f108-11e9-84b0-3d5006c76057.png)

**Comment by emcastillo** [comment]
Do you have a minimum script to reproduce the error?

**Comment by kmaehashi** [comment]
Ref. https://github.com/cupy/cupy/issues/2106#issuecomment-537910196

Another possible reason is that your installation of CUDA driver is not complete.
https://devtalk.nvidia.com/default/topic/876432/cuda-setup-and-installation/no-cuda-capable-device-is-detected/

**Comment by leofang** [comment]
Wait, your CUDA version (from `nvidia-smi`) is 10.1, but you installed `cupy-cuda100`? Could you try uninstalling it and then installing `cupy-cuda101`?

**Comment by say2sarwar** [comment]
> Do you have a minimum script to reproduce the error?

I didn't understand. if you are talking about the code. the link is here. https://github.com/LiangSiyuan21/Adversarial-Attacks-for-Image-and-Video-Object-Detection/tree/master/img_attack_with_attention

**Comment by say2sarwar** [comment]
> Wait, your CUDA version (from `nvidia-smi`) is 10.1, but you installed `cupy-cuda100`? Could you try uninstalling it and then installing `cupy-cuda101`?

10.1 is the available version of cuda. i check with NVCC and it's 10.0. still, i did what you asked and no solution.

**Comment by say2sarwar** [comment]
> Ref (past discussions): [#2106 (comment)](https://github.com/cupy/cupy/issues/2106#issuecomment-538372409)
> 
> Another possible reason is that your installation of CUDA driver is not complete.
> https://devtalk.nvidia.com/default/topic/876432/cuda-setup-and-installation/no-cuda-capable-device-is-detected/

I can use GPU on other programs and i run different codes under different env. but the cupy is creating the problems.
