### ISSUE TITLE
Support texture objects in `ElementwiseKernel`?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2550]
This feature is requested by @the-lay in https://github.com/cupy/cupy/pull/2432#issuecomment-543193359. I'll briefly comment below.

**Comment by leofang** [comment]
@the-lay, I quickly skimmed over the implementation of `ElementwiseKernel` in `cupy/core/_kernel.pyx`. It seems a bit involved for supporting textures, but not impossible. 

Before proceeding, I believe the following two prerequisites are necessary:
1. Only support texture objects and not texture references: the latter is to be deprecated, and you don't want extra effort.
2. Only support `tex1D<type>`: this is because `ElementwiseKernel` calls `_linear_launch()`, which launches 1D blocks. To support multiple dimensions a more complicate indexing scheme would be needed to be compatible with the current `ElementwiseKernel`'s design.

Basically there are two parts to be addressed: type inference and code generation. First, you need to make `ElementwiseKernel` recognize the class type `cupy.cuda.texture.TextureObject` and then pass the actual C type `cudaTextureObject_t` to the generated kernel. There are several functions called in `ElementwiseKernel.__call__()` that need to be changed for recognizing the input type.

Second, you need to make `tex1D<type>` appearing in the generated code. The easiest thing is probably to hard-code it in the input argument `operation`, making users responsible to ensure the correctness. But, care must be taken for the indexing of texture (I suppose for a linear texture indexing by `i` should be sufficient? Not sure...)

I don't have time recently to work on texture-related things myself, but I am happy to comment and review.

**Comment by leofang** [comment]
One more thought: you might need to specialize an instance of `CIndexer` (from `cupy/core/include/cupy/carray.cuh`) for texture objects. In particular, the `set()` method should be disabled, as textures are read-only.

**Comment by the-lay** [comment]
> Only support texture objects and not texture references: the latter is to be deprecated, and you don't want extra effort. Plus, it's impossible to fetch the reference generated in runtime for initializing it.

I agree, no need in adding something that will be deprecated soon.

> Only support tex1D<type>: this is because ElementwiseKernel calls _linear_launch(), which launches 1D blocks. To support multiple dimensions a more complicate indexing scheme would be needed to be compatible with the current ElementwiseKernel's design.

> Second, you need to make tex1D<type> appear in the generated code. The easiest thing is probably to hard-code it in the input argument operation, making users responsible to ensure the correctness. But, care must be taken for the indexing of texture (I suppose for a linear texture indexing by i should be sufficient? Not sure...)

I think this might be an overkill, as indexing is not a problem. You can always convert a flattened index to original indices, and it should be up to "operation" of ElementwiseKernel what to do, there's no need to force end users to use texture (if I understood you correctly and that's what you meant). For example in PyCUDA, I was launching an elementwise kernel to iterate over 3D float array. It provided index `i` that I "converted" into original `x, y, z` and could do `tex3D<float>(texture, x, y, z)`. Cupy's ElementwiseKernel also provides `i` and `_ind.size()`, so it should be possible to calculate original index if original dimensions would also be passed to the kernel. Something like this:
```c++
inline __device__ int get_z_idx(const int i, const int4 const dims) {
    return i / (dims.y * dims.z);
}
inline __device__ int get_y_idx(const int i, const int4 const dims) {
    return (i % (dims.y * dims[0].z)) / dims[0].z;
}
inline __device__ int get_x_idx(const int i, const int4 const dims) {
    return (i % (dims.y * dims.z)) % dims.z;
}
```

> Basically there are two parts to be addressed: type inference and code generation. First, you need to make ElementwiseKernel recognize the class type cupy.cuda.texture.TextureObject and then pass the actual C type cudaTextureObject_t to the generated kernel. There are several functions called in ElementwiseKernel.__call__() that need to be changed for recognizing the input type.

I will look into it today, thank you very much for the hints and direction. So to summarize, I'll focus on ability to pass `TextureObject` and figuring out conversion of flat index back to original indices.

**Comment by leofang** [comment]
> I think this might be an overkill, as indexing is not a problem. You can always convert a flattened index to original indices, and it should be up to "operation" of ElementwiseKernel what to do, there's no need to force end users to use texture (if I understood you correctly and that's what you meant). 

No, this is not what I meant. If you look at the implementation of `ElementwiseKernel`, it doesn't care the array dimension, and always launches 1D blocks that operate over the whole array. What I meant is that because of this, users should only pass in 1D texture objects. (See further below.)  

>For example in PyCUDA, I was launching an elementwise kernel to iterate over 3D float array. It provided index `i` that I "converted" into original `x, y, z` and could do `tex3D<float>(texture, x, y, z)`. Cupy's ElementwiseKernel also provides `i` and `_ind.size()`, so it should be possible to calculate original index if original dimensions would also be passed to the kernel. Something like this:
> 
> ```c++
> inline __device__ int get_z_idx(const int i, const int4 const dims) {
>     return i / (dims.y * dims.z);
> }
> inline __device__ int get_y_idx(const int i, const int4 const dims) {
>     return (i % (dims.y * dims.z)) / dims.z;
> }
> inline __device__ int get_x_idx(const int i, const int4 const dims) {
>     return (i % (dims.y * dims.z)) % dims.z;
> }
> ```
> 

I understand we can always compute the index on the fly. My concern is that how would you pass in this `dims` information to the `ElementwiseKernel`'s implementation without changing too much its design? (It could be possible, I don't know. I didn't think it very hard...)

**Comment by the-lay** [comment]
Unfortunately, I won't continue this (I'd be very happy if someone else does though). Making `ElementwiseKernel` accept and pass texture object seems too much work at this moment (current dtype-ctype parameters system is based on numpy types) , so I just made a `RawKernel` that mimics elementwise processing - not as pretty and integrated as actual ElementwiseKernel, but works for my current needs.

Here it is in case someone is looking for something similar:

<details>
  <summary>Kernel code</summary>

```python

    code = '''
        extern "C" {
            inline __device__ int get_z_idx(const int i, const uint4* const dims) {
                return i / (dims[0].y * dims[0].z);
            }
            inline __device__ int get_y_idx(const int i, const uint4* const dims) {
                return (i % (dims[0].y * dims[0].z)) / dims[0].z;
            }
            inline __device__ int get_x_idx(const int i, const uint4* const dims) {
                return (i % (dims[0].y * dims[0].z)) % dims[0].z;
            }
            __global__ void copy_texture(float* const volume,
                                      cudaTextureObject_t texture,
                                      const uint4* const dims) {
                // adapted pycuda elementwise kernel code
                unsigned tid = threadIdx.x;
                unsigned total_threads = gridDim.x*blockDim.x;
                unsigned cta_start = blockDim.x*blockIdx.x;
                unsigned i;
                unsigned n = dims[0].x * dims[0].y * dims[0].z;
                
                for (i = cta_start + tid; i < n; i += total_threads) {{
                    int z = get_x_idx(i, dims);
                    int y = get_y_idx(i, dims);
                    int x = get_z_idx(i, dims);
                    volume[i] = tex3D<float>(texture, x, y, z);
                }
            }
        }
    '''
    kernel = cp.RawKernel(code=code, name='copy_texture')
```
</details>

<details>
  <summary>Workgroup (block/grid) calculations</summary>

  [Adapted from this PyCUDA code](https://github.com/inducer/pycuda/blob/a30b86722977e71ac2e2176f9b1240bd96eabced/pycuda/gpuarray.py#L81)

</details>

<details>
  <summary>Actual kernel launch</summary>

  ```python
    ....
    texobj = cp.cuda.texture.TextureObject(res, tex) # like in https://github.com/cupy/cupy/pull/2432
    volume = cp.zeros_like(tex_data)
    dims = cp.asarray(volume.shape, dtype=cp.uint32)
    dim_grid, dim_blocks = compute_elementwise_launch_dims(volume.shape) # from previous spoiler
    kernel(dim_grid, dim_blocks, (volume, texobj, dims))
  ```
</details>

**Comment by leofang** [comment]
If you just need a copy kernel, also take a look at this example from the texture tests:
https://github.com/cupy/cupy/blob/b9db374f4d0ccee358a998d7b283248f77cef351/tests/cupy_tests/cuda_tests/test_texture.py#L112-L126

**Comment by the-lay** [comment]
Thank you! The actual elementwise operation that I use is more complicated than just copying texture, it's just an example (and I agree that copying texture can be done much easier).

**Comment by leofang** [comment]
I've been looking into `ElementwiseKernel` lately (for other reasons), and I think @the-lay was right in https://github.com/cupy/cupy/issues/2550#issuecomment-544157487. Looks to me that as long as we make `ElementwiseKernel` recognize `texObj` the rest can be handled in users' hand.
