### ISSUE TITLE
Support generalized universal functions

### ISSUE THREAD

**Issue by emcastillo** [cupy/cupy#2552]
Cupy does not offer generalized universal functions.
I would like to discuss how should we proceed and implement this feature.

https://docs.scipy.org/doc/numpy/reference/c-api.generalized-ufuncs.html

TODOs

- [ ] Parse gufuncs signatures to retrieve the core dimensions.
- [ ] Modify `core.pyx::ndarray::__array_ufunc__` to remove the signature check.
- [ ] Given the signature, modify `_kernel.pyx::ufunc::__call__` to call the 
       function sub-arraywise. Ufunc class relies on elementwise kernels when calling `_get_ufunc_kernel`. GUfuncs can also call kernels operating on regular vectors.
- [ ] Convert cupy inner1d, matmat, vecmat, matvec, matmul, outer_inner to actual gufuncs
- [ ] Add features such as `axes`,  `order`, etc.

List of numpy gufuncs (thanks to @asi1024)
```
(n?,k),(k,m?)->(n?,m?)
         matmul
(m,m)->(),()
         slogdet
(m,m)->()
         det
(m,m)->(m),(m,m)
         eigh_lo
         eigh_up
         eig
(m,m)->(m)
         eigvalsh_up
         eigvalsh_lo
         eigvals
(m,m),(m,n)->(m,n)
         solve
(m,m),(m)->(m)
         solve1
(m, m)->(m, m)
         inv
(m,m)->(m,m)
         cholesky_lo
(m,n)->(m)
         svd_m
(m,n)->(n)
         svd_n
(m,n)->(m,m),(m),(m,n)
         svd_m_s
(m,n)->(m,n),(n),(n,n)
         svd_n_s
(m,n)->(m,m),(m),(n,n)
         svd_m_f
(m,n)->(m,m),(n),(n,n)
         svd_n_f
(m,n),(m,nrhs),()->(n,nrhs),(nrhs),(),(m)
         lstsq_m
(m,n),(m,nrhs),()->(n,nrhs),(nrhs),(),(n)
         lstsq_n
```

**Comment by leofang** [comment]
FYI, Numba already supports this, see http://numba.pydata.org/numba-doc/latest/cuda/ufunc.html. But I am not sure if their generalized ufuncs support CuPy arrays (via `__cuda_array_interface__`). Should be quickly verifiable.

**Comment by emcastillo** [comment]
Dask have some facilities too https://docs.dask.org/en/latest/array-gufunc.html

**Comment by emcastillo** [comment]
Would like some feedback on the TODOs list :).
Thanks!

**Comment by jakirkham** [comment]
Support for gufuncs in CuPy would be great! 😄

Maybe @rgommers could provide us some guidance on how we do this in an effective way 😉

**Comment by rgommers** [comment]
+1 for this feature:)

Actually there's people on the NumPy team who know much more about this than I do - I'll ping @mattip and @seberg here for input.

**Comment by seberg** [comment]
Not sure how we can be of much help here, if you have any questions I am happy to take a look of course. One thing I am not sure is when your plan is to dispatch to the GPU. The idea of gufuncs is that dispatching occurs on a 1-D vectors of the computational subarrays. I feel for you it may depend on the gufunc whether dispatching to the GPU should occur for each subarray or for a vector of subarrays. However, I do not see that as a big issue. The iffiest point is really just the bookeeping around which axes to iterate, which not, and allocating the correct output shape.

**Comment by rushabh-v** [comment]
I am interested to work on this project under GSoC '20 and I am currently writing the proposal for it. Understood all the concepts quite nicely accept the feature `order`? Can you please elaborate a bit more on that @emcastillo ?
