### ISSUE TITLE
How can I obtain the source code generated from user-defined kernel?

### ISSUE THREAD

**Issue by hgt312** [cupy/cupy#2575]
As title.
Besides, a way to get source code generated by built-in kernels?

**Comment by grlee77** [comment]
You can set the environment variable CUPY_CACHE_SAVE_CUDA_SOURCE to 1. This will cause `.cu` files to appear alongside the `.cubin` files in the directory containing your cached kernels (by default this is in the user's home account under `.cupy/kernel_cache`). If the corresponding `.cubin` already exists, I am not sure the `.cu` will get created; you might have to clear the cache folder first (or perhaps temporarily set the CUPY_CACHE environment variable to a new folder if you don't want to lose your existing cache).

If it is a `cupy.RawKernel` you can directly print the `code` attribute of the RawKernel object.

**Comment by hgt312** [comment]
Thanks!
