### ISSUE TITLE
Test CUB and cuTensor in CI

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#2579]

**Comment by leofang** [comment]
@kmaehashi I am working on writing a test suite for CUB, is it duplicate to what you're working on?

**Comment by kmaehashi** [comment]
No, I intended to track CI infrastructure tasks, not test code in this repo.

**Comment by leofang** [comment]
Cool, thanks. Then I will add the CUB test to #2584.

**Comment by leofang** [comment]
I suppose this can be closed!
