### ISSUE TITLE
No matching distribution for PowerPC

### ISSUE THREAD

**Issue by berceanu** [cupy/cupy#2583]
When trying to install on the IBM ppc64 architecture with
`pip install cupy-cuda90` we get

```console
​​ERROR: Could not find a version that satisfies the requirement cupy-cuda90 (from versions: none)
​​ERROR: No matching distribution found for cupy-cuda90
```

**Comment by leofang** [comment]
For the time being you need to build from source. Try `pip install cupy`. We’ve done that on Ascent (test nodes for Summit) and it worked fine.

**Comment by leofang** [comment]
No, unfortunately. You will need a local copy of CUDA toolkit, not the one from conda, as it only contains the runtime libraries and not the compiler toolchain (`nvcc` and friends).

**Comment by berceanu** [comment]
I see. And how do I point cupy to this local copy?

**Comment by leofang** [comment]
A heads-up: if you have a local CUDA installation, it's better to remove the one from conda to avoid potential conflicts (not saying it's necessary, just a precautionary step).

**Comment by berceanu** [comment]
This doesn't affect `numba` at all, right?

**Comment by leofang** [comment]
No, if the installation is in default path `/usr/local/cuda`, numba should be able to find it. If not, set `CUDA_HOME`: http://numba.pydata.org/numba-doc/latest/cuda/overview.html#setting-cuda-installation-path

**Comment by leofang** [comment]
@berceanu did it work?

**Comment by berceanu** [comment]
```
$ python -m pip install cupy
Collecting cupy
  Downloading https://files.pythonhosted.org/packages/67/4b/6960cdfeee8bbfa12450da6b83206b57f6d6951a74043f055905449bb657/cupy-6.5.0.tar.gz (3.1MB)
     |████████████████████████████████| 3.1MB 1.0MB/s
Requirement already satisfied: numpy>=1.9.0 in ./miniconda3/envs/fbpic/lib/python3.7/site-packages (from cupy) (1.17.3)
Collecting six>=1.9.0
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting fastrlock>=0.3
  Using cached https://files.pythonhosted.org/packages/89/50/e2ca3f37b783975a7e1f4e7d81a62d6fe269254cdfc46610d8fe42a3f38f/fastrlock-0.4-cp37-cp37m-manylinux1_x86_64.whl
Building wheels for collected packages: cupy
  Building wheel for cupy (setup.py) ... done
  Created wheel for cupy: filename=cupy-6.5.0-cp37-cp37m-linux_x86_64.whl size=25365131 sha256=3e0ebd457349a54ef2af5b1c526088bc77d2d5274dad4752e071a405af1426fc
  Stored in directory: /home/berceanu/.cache/pip/wheels/d6/bd/4e/ce32a2bd6af01b2823b2335c3b842d5f2c2fe4a19f85627f27
Successfully built cupy
ERROR: stevedore 1.30.1 requires pbr!=2.1.0,>=2.0.0, which is not installed.
Installing collected packages: six, fastrlock, cupy
Successfully installed cupy-6.5.0 fastrlock-0.4 six-1.13.0
```

**Comment by berceanu** [comment]
Any idea what causes the `ERROR: stevedore 1.30.1 requires pbr!=2.1.0,>=2.0.0, which is not installed`?

**Comment by kmaehashi** [comment]
> Any idea what causes the ERROR: stevedore 1.30.1 requires pbr!=2.1.0,>=2.0.0, which is not installed?

I think this issue is not related to CuPy. It's just an error/warning message about your environment printed after any package installation.

**Comment by kmaehashi** [comment]
Closing as the original issue seems resolved.

**Comment by berceanu** [comment]
I was wondering, what if one uses the conda-forge channel to install cupy? Does that have packages for ppc?

**Comment by leofang** [comment]
Currently no: https://anaconda.org/search?q=cupy. If you need this, please feel free to open an issue on [conda-forge/cupy-feedstock](https://github.com/conda-forge/cupy-feedstock). 

I am not sure if conda-forge has the resource/infrastructure to build GPU packages for Power PC though; the `{{ compiler("cuda") }}` support is fairly new. We can continue the discussion there.

**Comment by leofang** [comment]
> Currently no: https://anaconda.org/search?q=cupy. If you need this, please feel free to open an issue on [conda-forge/cupy-feedstock](https://github.com/conda-forge/cupy-feedstock).

Issue opened in conda-forge/cupy-feedstock#14.
