### ISSUE TITLE
CuPy to PyTorch with __cuda_array_interface__ - Array Strides not Multiple of Element Byte Size

### ISSUE THREAD

**Issue by awthomp** [cupy/cupy#2589]
PyTorch version:
`torch.__version__`: 1.3.0

CuPy config:
```
CuPy Version          : 7.0.0rc1
CUDA Root             : /usr/local/cuda-10.0
CUDA Build Version    : 10000
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10000
cuDNN Build Version   : None
cuDNN Version         : None
NCCL Build Version    : None
NCCL Runtime Version  : None
```

With PyTorch accepting the __cuda_array_interface__, I'd expect to be able to use a CuPy generated CUDA array in PyTorch without going through DLPack.

```python
import cupy as cp
import torch

a = cp.random.rand(10000)
b = torch.as_tensor(a)
```
Throws: `ValueError: given array strides not a multiple of the element byte size. Make a copy of the array to reallocate the memory.`

If this is on PyTorch's side, please let me know, and I'll file an issue there. Thanks!

**Comment by leofang** [comment]
This is supposed to be handled in pytorch/pytorch#24947, but I don’t know why it is halt. The CUDA array interface protocol is updated to v2 recently in cupy’s master. Before pytorch fixes it, you can stay on cupy v6.

**Comment by leofang** [comment]
@beam2d is your PR to PyTorch ready, or you're still working on it? Thanks.

**Comment by awthomp** [comment]
@leofang -- I'm still getting this error with PyTorch version 1.2 and 1.3 and CuPy 6.5. Anything I'm missing?

**Comment by leofang** [comment]
@awthomp Could you please file an issue there? It's meant to be solved in pytorch/pytorch#24947. 

Taking a closer look at the error message, I think my earlier reply was wrong: it's actually a bug in PyTorch (at which the PR pytorch/pytorch#24947 targeted) even before the CUDA array interface was updated to v2, so it would not help even if you use CuPy v6 unfortunately. Sorry. 

CUDA arrays passed using this protocol are allowed not to contain strides as long as they're C contiguous, which is 99% the case in CuPy, unless you explicitly request for an F-contiguous array or slice an array in a bizarre way. In other words, PyTorch is not compliant with the protocol starting v0.

**Comment by leofang** [comment]
@awthomp in the meanwhile, could you try DLPack and see if it works?
https://docs-cupy.chainer.org/en/latest/reference/interoperability.html#dlpack

**Comment by awthomp** [comment]
@leofang Using DLPack works great. I have an example in one of my [cuSignal]( https://github.com/rapidsai/cusignal) notebooks located [here](https://github.com/rapidsai/cusignal/blob/master/notebooks/E2E_Example.ipynb)

**Comment by leofang** [comment]
Glad to know it works! Thank you, @awthomp. I should have been more keen on this issue. 

I just brought this issue to @gchanan in https://github.com/pytorch/pytorch/pull/24947#pullrequestreview-320958580.

**Comment by leofang** [comment]
This should be fixed in PyTorch now with pytorch/pytorch#24947 merged.

**Comment by awthomp** [comment]
Thanks @leofang. I'm compiling as we speak.

**Comment by leofang** [comment]
Yeah it's nice you're testing it! I wonder how long it takes to build PyTorch?

**Comment by awthomp** [comment]
Let's just say I think I'll go for a run, and check when I get back :smile:

**Comment by awthomp** [comment]
Confirmed fixed with https://github.com/pytorch/pytorch/pull/24947

**Comment by leofang** [comment]
Awesome, @awthomp! Thanks for your time! Which version of CuPy did you use? v6 or v7?

**Comment by awthomp** [comment]
Thanks for driving this, @leofang! I used CuPy v7 (`pip install cupy-cuda100`) in my testing.

**Comment by leofang** [comment]
It seems the bug fix will be included in PyTorch v1.4.0, see https://github.com/pytorch/pytorch/pull/31450.

**Comment by leofang** [comment]
Since PyTorch v1.4.0 is out, shall we close this issue?

**Comment by awthomp** [comment]
> Since PyTorch v1.4.0 is out, shall we close this issue?

Yep. I'll close the issue. Thanks to everyone for your help!

**Comment by jakirkham** [comment]
Also just a small note, using the following code (based off the code in the OP), we notice something peculiar

```python
import cupy as cp
import torch

a = cp.random.rand(10000)
b = torch.as_tensor(a)
assert b.is_cuda  # fails
```

This happens because PyTorch has actually done a device-to-host transfer under-the-hood. To fix this we have to specify the `device`.

```python
import cupy as cp
import torch

a = cp.random.rand(10000)
b = torch.as_tensor(a, device=torch.device('cuda'))
assert b.is_cuda  # works!
```

One can also inspect `__cuda_array_interface__` of both objects to confirm that this not only remains on device, but was a zero-copy conversion. Thus `b` uses the same memory as `a`.
