### ISSUE TITLE
Signatures and behaviors of `argmax` and `argmin` are incompatible with NumPy

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2595]
First, for the signature: In CuPy the signature for `argmax()` and `argmin()` is 
```python
cupy.argm*(a, axis=None, dtype=None, out=None, keepdims=False)
```
But in NumPy it's 
```python
numpy.argm*(a, axis=None, out=None)
```
That is, `dtype` and `keepdims` should be removed.

Second, for the behavior: In CuPy the `axis` could be a tuple, but in Numpy it can only be an integer:
```python
>>> import cupy as cp
>>> a = cp.arange(60).reshape(3,4,5)
>>> a.argmax(axis=(0,1))
array([11, 11, 11, 11, 11], dtype=int64)
>>> 
>>> import numpy as np
>>> a = np.arange(60).reshape(3,4,5)
>>> a.argmax(axis=(0,1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'tuple' object cannot be interpreted as an integer
```

I think both are easy to fix. Just add a few guards prior to calling the actual workhorses.

**Comment by leofang** [comment]
From my viewpoint, I don't mind at all such deviations. I think it'd help more use cases. Rather than fixing them, I think documenting them clearly is enough.

**Comment by grlee77** [comment]
Although the `dtype` argument is provided in argmin/argmax in CuPy, isn't it broken for anything except `dtype=None`?.

At least when I tried it (with CUB disabled), I get a `TypeError`:
`Wrong type (<class 'numpy.float32'>) of arguments for cupy_argmin`

(whereas NumPy gives a `TypeError` stating `'dtype' is an invalid keyword argument for argmin`)

**Comment by grlee77** [comment]
`keepdims` does work in CuPy, though, which seems useful if not strictly NumPy-compatible

**Comment by leofang** [comment]
For this case I think NumPy should change -- naively I'd expect `argmax`/`argmin`'s behavior should be the same as that of `max`/`min`, i.e. accepting a tuple `axis` and `keepdims` and so on.

**Comment by niboshi** [comment]
I think `dtype` has a use case, because without it you don't have control of the retuned dtype, even if you know int64 is too much.

**Comment by toslunar** [comment]
Issue numpy/numpy#8710: "Add `keepdims` argument to argmin and argmax"

**Comment by niboshi** [comment]
We don't have to remove any arguments?
Then, #2872 fixes the remaining issue (`dtype` argument of `argmin/argmax`).
