### ISSUE TITLE
`cupyx.scipy.ndimage.rotate()` saturates P100's 16G memory for 1G input data

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2607]
We discovered this out-of-memory (OOM) issue in a recent GPU Hackathon with @jqyin and @dxm447, and I'm revisiting this. 

The implementation along the call path `cupyx.scipy.ndimage.rotate()` -> `affine_transform()` -> `map_coordinates()` is very memory-inefficient. The memory inflation from a 1G input to over 16G on a P100 as shown in the following example (extracted from a real-life workload) is not acceptable.
```python
>>> import cupy as cp
>>> from cupyx.scipy.ndimage import rotate
>>>
>>> a = cp.random.random((512, 512, 512))  # 1GB data
>>> b = rotate(a, 15, axes=(1,2))
/home/leofang/test/cupy2/cupyx/scipy/ndimage/interpolation.py:27: UserWarning: In the current feature the default order of rotate is 1. It is different from scipy.ndimage and can change in the future.
  'the future.'.format(func_name))
/home/leofang/test/cupy2/cupyx/scipy/ndimage/interpolation.py:27: UserWarning: In the current feature the default order of affine_transform is 1. It is different from scipy.ndimage and can change in the future.
  'the future.'.format(func_name))
/home/leofang/test/cupy2/cupyx/scipy/ndimage/interpolation.py:27: UserWarning: In the current feature the default order of map_coordinates is 1. It is different from scipy.ndimage and can change in the future.
  'the future.'.format(func_name))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leofang/test/cupy2/cupyx/scipy/ndimage/interpolation.py", line 351, in rotate
    mode, cval, prefilter)
  File "/home/leofang/test/cupy2/cupyx/scipy/ndimage/interpolation.py", line 242, in affine_transform
    prefilter).reshape(output_shape)
  File "/home/leofang/test/cupy2/cupyx/scipy/ndimage/interpolation.py", line 112, in map_coordinates
    coordinates_floor = cupy.floor(coordinates).astype(cupy.int32)
  File "cupy/core/core.pyx", line 320, in cupy.core.core.ndarray.astype
  File "cupy/core/core.pyx", line 378, in cupy.core.core.ndarray.astype
  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 540, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1186, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1207, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 994, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1009, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 743, in cupy.cuda.memory._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 2,415,384,576 bytes (allocated so far: 15,566,063,104 bytes).
```
Using `pdb` I was able to spot that the biggest memory consumer is in `affine_transform()`:
https://github.com/cupy/cupy/blob/93547cedd3a87074e42edda5e88922c22e5f04b4/cupyx/scipy/ndimage/interpolation.py#L237
which alone took about 4.5G (=3\*512\*627\*627\*8 bytes). 

Another inefficiency I could tell that contributes to OOM is also in `affine_transform()`: 
https://github.com/cupy/cupy/blob/93547cedd3a87074e42edda5e88922c22e5f04b4/cupyx/scipy/ndimage/interpolation.py#L240-L242
which shows that an output buffer `ret` is allocated but not passed into `map_coordinates()`, so in `map_coordinates()` yet another buffer `ret` is allocated:  
https://github.com/cupy/cupy/blob/93547cedd3a87074e42edda5e88922c22e5f04b4/cupyx/scipy/ndimage/interpolation.py#L91
But even if this is fixed, I still got OOM in `map_coordinates()` here:
https://github.com/cupy/cupy/blob/93547cedd3a87074e42edda5e88922c22e5f04b4/cupyx/scipy/ndimage/interpolation.py#L125 
At this point I am not sure what's the best strategy to proceed, so I thought it's better to pause and report back.

Our current workaround is to batch process the images along the first axis, which is OK but less efficient.

**Comment by leofang** [comment]
Just tested @not522's #1168, and unfortunately it doesn't help resolve the OOM either...

**Comment by kmaehashi** [comment]
Thanks for the detailed report!
SciPy roughly used 2.5 GB including the original 1GB array for the same operation.
We definitely need optimization of memory usage here...

**Comment by not522** [comment]
Thank you. My code of #1168 is buggy and outdated. I'll try to write smarter implementation.
