### ISSUE TITLE
Bug for 0-size arrays in `__cuda_array_interface__`

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2610]
From https://github.com/cupy/cupy/pull/2536#issuecomment-549676148:
```python
>>> import cupy as cp
>>> a = cp.arange(3)
>>> b=a[0:1:-1]
>>> b.size
0
>>> b.__cuda_array_interface__
{'shape': (0,), 'typestr': '<i8', 'descr': [('', '<i8')], 'data': (139843608772608, False), 'version': 2, 'strides': None}
```
`b` is a 0-size array but it's pointer is not 0, violating the v2 protocol.

This is due to my oversight when updating the interface...😞 PR to follow.

**Comment by asi1024** [comment]
Note: https://numba.pydata.org/numba-doc/latest/cuda/cuda_array_interface.html
