### ISSUE TITLE
cupy.where fails for complex arrays

### ISSUE THREAD

**Issue by Leberwurscht** [cupy/cupy#2613]
The function cupy.where does not work for complex arrays (numpy.where does):

```
import cupy as cp
a = cp.arange(5).astype(cp.complex128)
b = cp.arange(5).astype(cp.complex128)
c = cp.where(a==b,a,b)
```

fails with the error message

> TypeError: Wrong type ((<class 'numpy.bool_'>, <class 'numpy.complex128'>, <class 'numpy.complex128'>)) of arguments for cupy_where

For `cp.float64`, everything works fine.

CuPy Version          : 6.4.0
CUDA Root             : /usr
CUDA Build Version    : 8000
CUDA Driver Version   : 10020
CUDA Runtime Version  : 8000
cuDNN Build Version   : 7102
cuDNN Version         : 7102
NCCL Build Version    : 2213
NCCL Runtime Version  : (unknown)

**Comment by emcastillo** [comment]
Hello, thanks for the report.

This issue was fixed on the 7.0 series but it wasn't backported. 
I just created the corresponding backport so it will be included in the next 6.x release.

If you need this feature urgently please install `cupy-cuda80==v7.0.0rc1`
