### ISSUE TITLE
TypeError: Unsupported type <type 'numpy.ndarray'>

### ISSUE THREAD

**Issue by Algabri** [cupy/cupy#2623]
how to fix this error
here more details

https://stackoverflow.com/questions/58786923/typeerror-unsupported-type-type-numpy-ndarray

**Comment by emcastillo** [comment]
Detections needs to be a cupy array to
```python
detections = np.array(net.forward())
```

**Comment by Algabri** [comment]
@emcastillo, thank you so much for your help.
 I got another error:
```
Traceback (most recent call last):
  File "/home/redhwan/learn1.py", line 33, in <module>
    label = "{}: {:.2f}%".format('person', confidence * 100)
ValueError: Unknown format code 'f' for object of type 'str'
```

it's work if mak comment out for these lines:
```
label = "{}: {:.2f}%".format('person', confidence * 100)
cv2.putText(frame, label, (startX, y), cv2.FONT_HERSHEY_SIMPLEX, 0.5, [0, 0, 255], 2)
```

**Comment by emcastillo** [comment]
Your `confidence` variable is a string instead of a float

**Comment by Algabri** [comment]
it is fine now. thank you sooo much @emcastillo
