### ISSUE TITLE
set_allocator context manager

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#2625]
In some cases a library developer may want to change the allocator temporarily. The don't want to negatively affect other library or user code. However they may need to temporarily set the allocator to a specific type for a block of code. In service of this it would be useful if `set_allocator` could be used like a context manager.

**Comment by emcastillo** [comment]
Let me send a PR about this, I actually drafted it a while ago  😄

**Comment by jakirkham** [comment]
Awesome! Thanks for doing that. Great minds think alike 😄

**Comment by emcastillo** [comment]
It should be tested whether the allocator can be stored in thread-local memory without conflicts.
Then use the thread-local for the context manager and the global one for regular set/get allocator calls.

**Comment by jakirkham** [comment]
Yeah that makes sense to me too.
