### ISSUE TITLE
Sync the headers in `cupy/core/include/cupy/complex/` with upstream?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2629]
Recently the bundled Thrust complex headers have been modified on a per-PR basis for the following reasons:
1. Performance impact: #2562 (fixed alignment)
2. Missing `__host__` qualifiers: #2538
3. Missing support: #2520 

All of these changes are more or less in sync with the latest Thrust codes. I suggest that these headers can be brought up to date with the upstream. The incentive is that one might discover another one-liner change like in #2562 that boosts the performance considerably 🙂

**Comment by emcastillo** [comment]
All these changes are already present in the current thrust?

**Comment by leofang** [comment]
> All these changes are already present in the current thrust?

Yes 😄 For example:

>> 1. Performance impact: #2562 (fixed alignment)

The alignment is done via a specialized data holder `complex_storage`:
https://github.com/thrust/thrust/blob/324243f6bb70687aeaeb2419193a335648c5869d/thrust/complex.h#L454

>> 2. Missing `__host__` qualifiers: #2538

All Thrust complex functions have a `__host__` qualifier, as it is meant to be interchangeable with `std::complex` on the host:
https://github.com/thrust/thrust/blob/324243f6bb70687aeaeb2419193a335648c5869d/thrust/complex.h#L140-L142

>> 3. Missing support: #2520

`real()` and `imag()` are now supported in Thrust:
https://github.com/thrust/thrust/blob/324243f6bb70687aeaeb2419193a335648c5869d/thrust/complex.h#L384-L407

Now, my question: Since Thrust comes with the CUDA toolkit now, is there a reason we can't use it and get rid of the bundled version?

**Comment by kmaehashi** [comment]
> Now, my question: Since Thrust comes with the CUDA toolkit now, is there a reason we can't use it and get rid of the bundled version?

If I recall correctly Thrust bundled with CUDA Toolkit uses `__host__` code so NVRTC cannot compile it.

**Comment by leofang** [comment]
> If I recall correctly Thrust bundled with CUDA Toolkit uses `__host__` code so NVRTC cannot compile it.

As long as the full qualifier is `__host__ __device__`, as in both #2538 and the Thrust, NVRTC will not complain: https://docs.nvidia.com/cuda/nvrtc/index.html#execution-space

**Comment by emcastillo** [comment]
The minimum cuda version we support is 8, I guess we have to check the status of thrust headers on that version

**Comment by emcastillo** [comment]
I am doing some tests and thrust has 
```

#include <cmath>
#include <complex>
#include <sstream>
#include <thrust/detail/type_traits.h>
```
included in the base thrust.h which makes nvrtc blow up 😂

**Comment by leofang** [comment]
Sounds like `#include <thrust/complex.h>` won't work 🤣

**Comment by emcastillo** [comment]
nope, and all the detail/complex/ headers include `thrust/complex.h` back
So it seems that we need to hold cupy specific thrust headers

**Comment by kmaehashi** [comment]
Discussed in dev team, it is better to have a forked version of Thrust in cupy organization so that we can easily rebase to the future upstream changes. Then we can use it as a submodule from CuPy.
Well, first we need to find the base version which that we started fork in https://github.com/cupy/cupy/pull/232 😂

**Comment by okuta** [comment]
I introduced complex header to CuPy in following commit.
https://github.com/cupy/cupy/commit/799001330654b0d8818f6ba4b7d658e2dabcaf2b

I also modified the header due to some limitations of nvrtc.

Maybe I ported from CUDA7.5 bundle version or github master.

**Comment by leofang** [comment]
With errors like this:

> `cupy.cuda.compiler.CompileException: /usr/local/cuda/include/thrust/complex.h(26): catastrophic error: cannot open source file "cmath"`

and this: https://github.com/cupy/cupy/pull/1866#issuecomment-457791608, it seems the root cause is system headers are not included and passed to NVRTC? Can't we simply include them and solve this issue with minimum to zero future effort?

Just curious, not suggesting anyone's time is urgently needed to investigate this 😛

**Comment by okuta** [comment]
We can use `__CUDACC_RTC__` macro to avoid including cmath header.
>__CUDACC_RTC__: useful for distinguishing between runtime and offline nvcc compilation in user code.

**Comment by emcastillo** [comment]
We discussed at the daily and I will take care of creating the thrust fork for our organization.

**Comment by leofang** [comment]
Thank you @emcastillo for the update and @okuta for comments. 

Tried a bit today, I don't think `__CUDACC_RTC__` can help. The following test leads to a zoo of compilation errors irrelevant of "headers not found". 
```python
import cupy as cp

cuda_ker = r'''
#include <thrust/complex.h>

using namespace thrust;

extern "C"{
__global__ void add_one(complex<double> * A, int N) {
   int id = threadIdx.x + blockIdx.x * blockDim.x;
   if (id<N) {
      A[id] = A[id] + complex<double>(1.0, 0.0);
   }
}
}
'''

a = cp.random.random(10) + 1j*cp.random.random(10)
b = a.copy()
# ker = cp.RawKernel(cuda_ker, 'add_one', backend='nvcc')  # this would work!
ker = cp.RawKernel(cuda_ker, 'add_one', backend='nvrtc',
                   options=('--std=c++11',
                            '-I/usr/include/x86_64-linux-gnu/', 
                            '-D__x86_64__', 
                            '-I/usr/lib/gcc/x86_64-linux-gnu/4.9/include/', 
                            '-default-device',  
                            '-I/usr/include/c++/4.9/',
                            '-I/usr/include/x86_64-linux-gnu/c++/4.9/')) 
block = (10, 0, 0)
grid = (1, 0 , 0)
args = (b, 10)
ker(grid, block, args)
assert (a+1==b).all()
``` 
(I am convinced the submodule approach is the most viable one, just curious how far we could push in this direction.)

**Comment by emcastillo** [comment]
I just got it working using a submodule and `__CUDACC_RTC__`
I am currently running tests and plan to submit a PR in the next few hours/day

**Comment by leofang** [comment]
Cool! Ping me when it's ready!

**Comment by emcastillo** [comment]
Actually it didn't work, the thrust headers need a lot of extra work

**Comment by emcastillo** [comment]
The current thrust headers are just full of code that NVRTC does not accept,
we have to put a lot of ifndef and the code becomes dirty and unmanageable.

The subset of the complex interface is just small enough and is not prone to changes other than align size for future GPUs, I don't think we really need to sync with the current thrust in this case.

I will make it work just to show a prototype and take a decision-based in actual code instead of just an opinion, but the deeper I go the more against it I am.

**Comment by leofang** [comment]
I see. Thank you for looking into this issue, @emcastillo. I can totally imagine the challenges. In that case I suggest we just take incremental changes (as we currently do) to bring the cupy complex headers up to date. 

I can help go over the current Thrust some time next week, and find if we miss any non-trivial changes (like alignment); adding the missing `__host__` qualifiers is easy. Will report back here.

**Comment by emcastillo** [comment]
@leofang can I get your opinion on the PRs that are above?
They are quite dirty so the quality can (and should) be improved but they should give an idea of the needed effort to keep everything synced

**Comment by leofang** [comment]
Thanks so much for working on this @emcastillo! It is amazing that you even got the dirty hack to build! 🎉 

You convinced me it does not worth the time and effort to sync it, unless the maintenance can be fully automated (I don't see how to). I think later I will take a look at these upstream files, since they are modified within the last two years:
- arithmetic.h
- complex.inl
- cpow.h
- cproj.h 
- csinh.h

And I will also figure out why c99math.h is not here and what it offers (doesn't seem critical). But unless I find something needed to be fixed/improved, I suggest we close this issue.

**Comment by leofang** [comment]
I spotted a few minor differences in the listed files. I intend to make a PR, incorporate the major changes in upstream (will not be a 100% clone), and close this issue.

**Comment by emcastillo** [comment]
Do they affect functionality or performance?

**Comment by leofang** [comment]
Functionality -> I doubt they would (apart from the missing `__host__` qualifier).
Performance -> Hard to tell. Can only be measured with the changes ready.

**Comment by emcastillo** [comment]
Thanks for looking into it.
