### ISSUE TITLE
Using RMM with CuPy

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#2635]
As RMM is the memory manager used in the RAPIDS stack, it might be interesting to explore what would be needed to use RMM with CuPy. This would allow users working with RAPIDS and CuPy to ensure all memory allocations are managed by the same memory manager (RMM) and come from the same memory pool. Not only can this be useful at a low-level by consolidating memory management, but it can be useful at a high-level by tools tracking memory management (like dashboards, etc.).

On the flip side, it could be interesting to use CuPy's memory manager for allocating objects outside of CuPy. This could be useful for developers debugging different kinds of problems. It could also be helpful to users that are trying to see how their performance is impacted by different kinds of memory managers. Additionally this could be helpful in improving different memory managers by learning about the design choices each makes.

**Comment by kmaehashi** [comment]
Basically it sounds feasible as CuPy supports replacing allocator (https://docs-cupy.chainer.org/en/latest/reference/memory.html#changing-memory-pool) and `rmm` provides Python interface for allocating memory.
It's nice if RMM (or cuDF?) provides CuPy memory pool support.

**Comment by kkraus14** [comment]
@kmaehashi We're going to explore this when we get some free cycles. The initial thought is that when someone imports RMM we'll check if cupy is importable, and if it is we'll set the cupy allocator to use an RMM defined allocator.

Do you foresee any issues with this or situations where the allocator will get overridden?

**Comment by kmaehashi** [comment]
As library imports are often implicit to end-users, I'd rather prefer an explicit API to override the memory pool, e.g., `rmm.override_cupy_memory_pool()`.
(e.g. if user imports a library that has strong dependency to cupy and weak (optional) dependency to RMM, users may want to use CuPy memory allocator.)
Automatic override in higher layer application like cuDF sounds fine for me.

**Comment by jakirkham** [comment]
If we are trying to constrain the allocator used based on context, we may consider using the `set_allocator` context manager ( https://github.com/cupy/cupy/issues/2625 ).

**Comment by kkraus14** [comment]
> As library imports are often implicit to end-users, I'd rather prefer an explicit API to override the memory pool, e.g., `rmm.override_cupy_memory_pool()`.

My experience with this is that many users won't look at the docs / find that API and then will have conflicting memory pools. In order to avoid this with using Numba we ended up re-exposing large portions of the user facing Numba API related to device array construction, and even then we still get plenty of users creating a combination of RMM backed and cudaMalloc backed device arrays.

Ideally we'd be able to target CuPy's memory pool underneath RMM as an option, but it would be super non-trivial to implement due to it being mostly defined at the C++ level in RMM.

**Comment by jakirkham** [comment]
Perhaps. Though we do have users running `rmm.reinitialize(...)` to setup the RMM pool anyways. Maybe it is reasonable to add a flag there ( https://github.com/rapidsai/rmm/issues/191 )?

**Comment by jakirkham** [comment]
FWIW we have a proposed implementation of this in PR ( https://github.com/rapidsai/rmm/pull/198 ) if this is of interest.

**Comment by kmaehashi** [comment]
Closing as this the support has been implemented in RMM. (FYI - We're now periodically revisiting old/inactive issues.)
Feel free to leave a comment if needed.
