### ISSUE TITLE
Allocating aligned memory

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#2647]
This is more of a question at the moment, but could lead to a doc issue or a feature request.

Some lower level libraries prefer memory allocated with a specific alignment. In some cases, incorrect alignment means poor performance. In other cases, it's the difference between some code running or not. To this end, it would be really useful to allocate aligned memory with CuPy. However after looking through the docs and the code, am not entirely sure if there is a way to do that.

If it is possible to do aligned allocations with CuPy, it would be great to understand how to influence alignment. Hopefully we can then document this pattern for other users looking for similar functionality.

If it is not possible, this would be a great feature to have.

For a related discussion on this topic with NumPy, please see issue ( https://github.com/numpy/numpy/issues/5312 ).

**Comment by leofang** [comment]
My impression is that in terms of memory allocation, CuPy follows the internal practice of `cudaMalloc()` and is always aligned: https://github.com/cupy/cupy/blob/59e6c2b2e0c722b09c7a7af13f908942ef7806cc/cupy/cuda/memory.pyx#L805-L809
(I actually investigated this problem when working on #2432 but I can't recall what I've learned off my head...😞)

**Comment by emcastillo** [comment]
I think a custom allocator or memory pool should solve this.

**Comment by kmaehashi** [comment]
> Some lower level libraries prefer memory allocated with a specific alignment.

Could you elaborate more on this? Do you think it fine if `ALLOCATION_UNIT_SIZE` can be adjusted in the default mempool?

**Comment by kmaehashi** [comment]
Closing as this issue is not active for months. Feel free to reopen if needed.
