### ISSUE TITLE
`linalg.det` should return 0 if getrf failed

### ISSUE THREAD

**Issue by toslunar** [cupy/cupy#2650]
`det` of a singular matrix is 0. `getrf` failure has to be checked.

* Conditions
  - CuPy version: from a0869c60b5fe5551949f5c815de0206cf8e5759b (#2437)

* Code to reproduce

  ```
  >>> cupy.linalg.det(cupy.zeros((2, 2), cupy.float32))
  array(nan, dtype=float32)
  ```

**Comment by niboshi** [comment]
Jenkins, test this please
