### ISSUE TITLE
Sparse support to include vstack & hstack

### ISSUE THREAD

**Issue by cjnolet** [cupy/cupy#2655]
I am finding the `cupy.sparse` packages to be very useful. For the most part, they match the `scipy.sparse` in provided functionality. One important feature that is currently lacking, which is supported by `scipy.sparse` [1], is the ability to `hstack` and `vstack` sparse arrays. 

I am working to integrate `cupy.sparse` arrays into `Dask.Array` and it is necessary for the `Dask.Array` to be able to concatenate multiple blocks containing sparse arrays together when data is redistributed.

[1] https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.hstack.html

**Comment by grlee77** [comment]
+1

On first glance, it looks like this should be pretty easy to add (mostly just copy/paste the following code from SciPy):
https://github.com/scipy/scipy/blob/634d0c03d77cebb3ce162688509ddc9b9f695098/scipy/sparse/construct.py#L401-L623

**Comment by cjnolet** [comment]
I don’t mind contributing this feature, unless you plan to work on it, @grlee77. I’ll get myself familiar with the contributor guide.

**Comment by grlee77** [comment]
Please go ahead. Docstrings will have to be changed to the CuPy style and
test cases added under tests/cupyx_tests/scipy_tests/sparse_tests/

**Comment by kmaehashi** [comment]
Ongoing in #2665

**Comment by cjnolet** [comment]
The PR is ready to go, if someone wouldn’t mind giving it a final review.

**Comment by jakirkham** [comment]
I think this issue can be closed now (as the PR is merged). Is that right @cjnolet? 🙂
