### ISSUE TITLE
Is `cupy/internal.py` redundant?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2661]
It seems that it does nothing but provides a duplicate of `cupy.core.internal.prod()`. Looks like we could just remove that file? I think all functions in `*.pxd`/`*.pyx`/`*.pxi` already use `cupy.core.internal.prod()`, so only the following two files need to change the import:
- `cupy/testing/helper.py`
- `cupy/linalg/product.py`

(based on `grep --include=\*.{py,pxd,pyx,pxi} -R './' -e 'internal.prod'`).

**Comment by leofang** [comment]
Relevant: #2689.

**Comment by kmaehashi** [comment]
I think it's redundant and can be removed.
