### ISSUE TITLE
Specific Scipy/Numpy functions for cupy

### ISSUE THREAD

**Issue by UmashankarTriforce** [cupy/cupy#2663]
I'm working closely with a team from RAPIDS organization and I would like to port the following for cupy from numpy/scipy - 

- [x] numpy.convolv (https://numpy.org/devdocs/reference/generated/numpy.convolve.html)
- [x] numpy.roots (https://numpy.org/devdocs/reference/generated/numpy.roots.html)
- [x] numpy.polyval (https://docs.scipy.org/doc/numpy/reference/generated/numpy.polyval.html)
- [ ] numpy.poly (https://docs.scipy.org/doc/numpy/reference/generated/numpy.poly.html)
- [ ]  numpy.linalg.eig (https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html)

Just correct me if any of the above features are already implemented. If not, I wish to work on implementing them for cupy.

**Comment by leofang** [comment]
Cool! I don't think any of the functions you listed are implemented in CuPy, see https://docs-cupy.chainer.org/en/latest/reference/comparison.html.

**Comment by lanzithinking** [comment]
Would love to see partial eigensolver scipy.sparse.linalg.eigs (https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigs.html)

**Comment by Dahlia-Chehata** [comment]
I have opened PR for cupy.append #3136

**Comment by quasiben** [comment]
for `numpy.convolv` could we reuse the ndimage implementation but with the appropriate API mappings.  For example, `same` -> `constant` ?

**Comment by kmaehashi** [comment]
Let me close this one, as the complete list is now in a separate issue: #6078
