### ISSUE TITLE
Implement `mean` for `cupyx.scipy.sparse.csr.csr_matrix`

### ISSUE THREAD

**Issue by tomwhite** [cupy/cupy#2674]
This would be similar to the already existing implementation of `sum`.

This came up when trying to run Scanpy with CuPy and Dask: https://github.com/theislab/scanpy/issues/921, and @mrocklin suggested I open an issue here.

**Comment by jakirkham** [comment]
cc @pentschev

**Comment by YashBhartia00** [comment]
Hello, is this issue still open? I would like to work on it.

**Comment by YashBhartia00** [comment]
I would like to work on this issue. Thank you!

**Comment by YashBhartia00** [comment]
I would like to work on this issue. Thank you!

**Comment by jakirkham** [comment]
That would be great! Please do 🙂
