### ISSUE TITLE
Implement column subsetting for `cupyx.scipy.sparse.csr.csr_matrix`

### ISSUE THREAD

**Issue by tomwhite** [cupy/cupy#2676]
E.g. `xs[:, 1:3]` should work when `xs` is a `cupyx.scipy.sparse.csr.csr_matrix`. Note that row subsetting does work in this case.

This came up when trying to run Scanpy with CuPy and Dask: https://github.com/theislab/scanpy/issues/921.

**Comment by jakirkham** [comment]
cc @mrocklin @pentschev
