### ISSUE TITLE
Implement boolean column subsetting for `cupyx.scipy.sparse.csr.csr_matrix`

### ISSUE THREAD

**Issue by tomwhite** [cupy/cupy#2677]
E.g. `xs[:, subset]`, where subset is e.g. `np.array([True, False, True, False, True])` and `xs` is a `cupyx.scipy.sparse.csr.csr_matrix`. Note that row subsetting does not work in this case.

This came up when trying to run Scanpy with CuPy and Dask: https://github.com/theislab/scanpy/issues/921.

**Comment by jakirkham** [comment]
cc @mrocklin @pentschev
