### ISSUE TITLE
Wrong array order due to reduction over non-contiguous axes of F-order arrays

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2678]
I was working on CUB support for F-order arrays, and I found that when the reduced axes do not have contiguous strides, the output array order is wrong:
```python
import cupy as cp
import numpy as np

a_cp = cp.random.random((2, 3, 4, 5))
a_cp = cp.asfortranarray(a_cp)
a_np = cp.asnumpy(a_cp, order='F')
assert a_cp.flags.f_contiguous
assert a_np.flags.f_contiguous

result_cp = a_cp.max(axis=(0,2))
result_np = a_np.max(axis=(0,2))
print( cp.allclose(a_cp, a_np) )        # True
print( result_np.flags.f_contiguous )   # True
print( result_cp.flags.f_contiguous )   # False -> wrong!
```
(Note that here it uses CuPy's reduction kernel rather than CUB, since CUB doesn't work when the axes are not contiguous.) It seems when entering the reduction routines, the input array order is not memoized.

**Comment by niboshi** [comment]
Thank you for raising an issue.
We do not guarantee strides compatibility. So this difference is expected. 

Rel: #2717

**Comment by kmaehashi** [comment]
Also rel: #605

**Comment by leofang** [comment]
Ah, didn't notice this is duplicate of #605. Thanks.
