### ISSUE TITLE
Expose CuPy memory pool to C/C++ space?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2710]
I found the following snippet (L15-L40) in `cupy.cuda.thrust`: 
https://github.com/cupy/cupy/blob/4586fedac8254dcd71d97617f2f95f98254dbbcc/cupy/cuda/thrust.pyx#L15-L40

I think this is an important low-level API for external C/C++/Cython code (such as Thrust and CUB) to use CuPy's memory pool. Is it possible to move them to, say, `cupy/cuda/memory.pxd` so that it can be reused?

**Comment by kmaehashi** [comment]
Does CUB allocate memory by itself, out of CuPy memory pool? I think that issue should be addressed first. Moving to `cupy/cuda/memory.pxd` sounds fine if it's done in that fix.

**Comment by emcastillo** [comment]
I've been checking on CUB and they use a single allocator that is not swappable by others.
So having cub getting memory from cupy involve to modify the cub code itself. Maybe we can send a PR to cub? I think that providing an Allocator interface for cub and the ability to set it up is a valuable contribution.

Another possibility here is to have cupy using the cub allocator underneath cupy's own, but this would probably sensibly decrease performance.

**Comment by leofang** [comment]
That’s right. Currently all CUB routines integrated with CuPy use CuPy memory pool. This is just for future extensions and code reusability.

**Comment by leofang** [comment]
I found myself in a situation where having a C/C++ interface to CuPy's memory pool is important. I will try to find some time and make a PR to close this issue. The goal is to move the existing memory manger interface from the `thrust` module to the `memory` module so as to make it more reusable.

**Comment by jakirkham** [comment]
Am curious to know what those use cases are (just out of personal interest 🙂).

**Comment by leofang** [comment]
Well, @jakirkham, I am glad you asked. See leofang/cupy#10 for my WIP...I got good performance boost there for *every partial reduction* functions in CuPy. But I no longer thought #3212 is useful for my purpose 😞 A little fresh thoughts could be very helpful.

**Comment by jakirkham** [comment]
Ah ok. Thanks for that context, Leo 😀

So it’s not for use with other C/C++ libraries.

Yeah that makes sense. So the idea is you want to perform an allocation once in advance and then reuse it as part of nested reductions. Is that right?

cc @anaruse (in case you have thoughts on this use case 🙂)

**Comment by leofang** [comment]
> So it’s not for use with other C/C++ libraries.

Well...Thrust is a C++ library...I guess you meant "standalone" C/C++ libraries that do not talk to Python? 

#3212 is still needed in that it cleans things up quite a bit. It could also be useful for Python modules written in C/C++ depending on how early we wanna bind with CuPy's default memory manager. If late binding is OK, then perhaps those modules should just access `cupy.cuda.memory` at Python runtime.

> Yeah that makes sense. So the idea is you want to perform an allocation once in advance and then reuse it as part of nested reductions. Is that right?

Ah yes, let me revise the text in my WIP 😅 I need to allocate a temp buffer to be used indeed like you said. (To do a full reduction I need two passes of CUB BlockReduce, and the buffer holds the intermediate result.)

**Comment by jakirkham** [comment]
I guess 😄 Though admittedly now those libraries might be kind of talking to Python if they are sharing a memory pool 😉

Yep this makes sense to me and seems very useful. To @jrhemstad's [point]( https://github.com/cupy/cupy/pull/3212#issuecomment-602960907 ), I wonder if you could have some simple allocator that merely pulls from the front of this preallocated memory or do you run into issues when trying this? 🙂

**Comment by leofang** [comment]
Closing this issue as CuPy's (Cython-based) memory pool would not be as performant as C/C++ based ones, so it is of limited interest to native C/C++ applications. (For Python applications, it should be fairly simple to access this pool.)

However, this issue aside, I do think #3212 is a good housecleaning PR. Memory management should simply not appear in `cupy/cuda/thrust.pyx`...Just my two cents.
