### ISSUE TITLE
Use `intptr_t` instead of `size_t ` for handle types

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#2716]
Related: #1913

Handles are pointers. `intptr_t` should be used as a representative type.

* [ ] cublas
* [ ] cusolver  #2718
* [ ] cusparse
* [ ] cudnn

**Comment by anaruse** [comment]
Would it be better to use `intptr_t` in #2709 as well?

**Comment by niboshi** [comment]
Yes, but there may be a room for discussion on how to define these types: https://github.com/cupy/cupy/pull/2718#issuecomment-558891688

**Comment by jakirkham** [comment]
Should it be `intptr_t` or `uintptr_t`?

**Comment by niboshi** [comment]
It shouldn't matter much, but I think `intptr_t` is more natural because Python `int` is a signed integer.
