### ISSUE TITLE
inconsistent behavior of keepdims for CUB-based reductions

### ISSUE THREAD

**Issue by grlee77** [cupy/cupy#2720]
It appears that keepdims does not keep all of the reduction dimensions when CUB is enabled and axis is a tuple containing more than one axis.

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
```
CuPy Version          :  7.0.0rc1 (build from master branch)
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10010
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10010

```
* Code to reproduce

```Python
import cupy
x = cupy.ones((64, 64))

cupy.cuda.cub_enabled=False
out = x.sum(axis=(0, 1), keepdims=True)
print("CUB DISABLED shape={}".format(out.shape))

cupy.cuda.cub_enabled=True
out = x.sum(axis=(0, 1), keepdims=True)
print("CUB ENABLED shape={}".format(out.shape))
```
gives
```
CUB DISABLED shape=(1, 1)
CUB ENABLED shape=(1,)
```

cc @leofang

**Comment by grlee77** [comment]
actually the behavior is as above only for `sum`, `min` and `max`

For `argmin` and `argmax` the CUB case gives shape `()` instead( while non-CUB is still (1, 1) as expected)

**Comment by grlee77** [comment]
The issue is within `device_reduce` rather than `device_segmented_reduce`. 

This can be confirmed by using `axis=(1, 0)` instead of `axis=(0,1)` which does not meet the criteria of `_cub_device_reduce_axis_compatible` . In that case, all reductions give shape (1, 1) as expected indicating that the `device_segmented_reduce` treats `keepdims` correctly.


A separate issue is to fix `_cub_device_reduce_axis_compatible` so that axis (0, 1) and (1,0) are both recognized as compatible.

**Comment by grlee77** [comment]
I am working on a fix for this currently.

**Comment by leofang** [comment]
Apparently I didn’t think it was a problem 🤦‍♂️ Thanks for catching it, @grlee77. I think calling `_preprocess_array()` should give you the right shape?

**Comment by grlee77** [comment]
> Apparently I didn’t think it was a problem

I think the origin of the problem was an oversight on my part in #2517. I enabled reduction over all axes there, but did not ensure that `keepdims` preserved all of the axes.
