### ISSUE TITLE
Mark explicit `plan` in `cupyx.scipy.fftpack.*` a stable API?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2743]
The explicit `plan` argument in `cupyx.scipy.fftpack.*` and the `get_fft_plan()` function there were added in v6. I have used it extensively in production since then, and I also heard positive feedbacks (via private communication). The plans (`Plan1d` or `PlanNd`) returned by the `get_fft_plan()` handle can be reused either explicitly as an argument, or implicitly as a context manager. In other words, the plans can be used
- implicitly in `cupy.fft.fft.*` (and later `cupyx.scipy.fft.*`)
- explicitly in `cupyx.scipy.fftpack.*`

Given where we are now, and that the `cupyx.scipy.fft` API will be added soon (#2355) which do not take a `plan` as argument, I wonder if this nice feature can be removed from the "experimental" status and become a stable API. Thanks.

**Comment by asi1024** [comment]
`cupyx.scipy.fftpack.fft` have `plan` keyword argument, but I think it might be better to support this feature as a method of `plan`. (That means an API like as `plan.fft(x, ...)` seems better to me.) So, I'm hesitating to make it as stable support. How do you think?

**Comment by leofang** [comment]
I consider the methods in `Plan1d` and `PlanNd` private APIs that are subject to change as deemed necessary anytime, so I really do not like the idea of exposing them to average users. It takes much more work to make them robust, easily accessible, and stable, than just marking `plan` stable. 

In addition, using the low-level APIs directly means we lose all the benefits and conveniences that high-level API provides (require a lot of code change, extra work to prepare input & output arrays, etc). 👎 from me.

Since the master supports solely PY3 now, I suggest we can make `plan` a [keyword-only argument](https://www.python.org/dev/peps/pep-3102/).

**Comment by leofang** [comment]
I am throwing in some notes while refreshing my memory on pyFFTW. @grlee77 as one of the core maintainers for pyFFTW, please correct me if I am wrong 🙂 

I think there is 1-to-1 correspondence between pyFFTW and CuPy's FFT support:
- `pyfftw.interfaces` <-> `cupy.fft`/`cupyx.scipy.fftpack`
- `pyfftw.FFTW`        <-> `cupy.cuda.cufft.Plan1d`/`PlanNd`
- `pyfftw.builders`    <-> `cupyx.scipy.fftpack.get_fft_plan`

So, for keeping a similar interface with the best Python FFT library on CPU (does `pocketfft` win now?), `get_fft_plan()` should definitely be a public API. 

Next, if we decide to polish and maintain `Plan1d`/`PlanNd` as noted in my earlier comment, they can also be made as public APIs, but it's a harder route that requires some work. 

Finally, to counteract my standpoint, I note that in `pyfftw.interfaces` the API does not accept any `FFTW` (i.e., plan) object, but it's only because there plans can be cached for arbitrarily long time. If we're also willing to invest efforts into a plan cache, which was in fact part of the original discussion that led to the current plan support (#1669), then as a compromise -- I still think it's a good API and couldn't understand why pyFFTW didn't do a similar job -- I'll be on board with removing the `plan` argument from `cupyx.scipy.fftpack.*`.

@grlee77 I remember you had a prototype for plan cache. How did it go?

**Comment by grlee77** [comment]
>I think there is 1-to-1 correspondence between pyFFTW and CuPy's FFT support:
>
>    pyfftw.interfaces <-> cupy.fft/cupyx.scipy.fftpack
>    pyfftw.FFTW <-> cupy.cuda.cufft.Plan1d/PlanNd
>    pyfftw.builders <-> cupyx.scipy.fftpack.get_fft_plan

Yeah, this is pretty close. The pyFFTW builders also return a `pyfftw.FFTW` object, it is just a more convenient interface than calling `pyfftw.FFTW` directly.  In either case, the FFTW object has a `__call__` method implemented so that the end-user can use it like a function.

e.g.
fft = pyfftw.builders.fft(...)
y = fft(x)  # applys a pre-planned transform

So I think the main difference between this FFTW object and the cupy `PlanNd` `.fft` method call that @asi1024 suggested above is that is uses the `__call__` method so it looks more like a function to the end-user.

**Comment by grlee77** [comment]
> Since the master supports solely PY3 now, I suggest we can make plan a keyword-only argument.

I am +1 on making it keyword-only.

The need for the separate `plan` argument has been reduced somewhat by the ability to use the plans as a context manger, but I think it is convenient to still have the option to explicitly pass in a plan.

I think one issue with calling a method from a Plan object itself is that this is even less like the style of NumPy or SciPy fft code.

**Comment by grlee77** [comment]
> @grlee77 I remember you had a prototype for plan cache. How did it go?

I should revisit to recall the full details. I know I had a working implementation that was basically a copy of the pyFFTW one, but wanted to instead use a non time-based cache. I did start that somewhere, but haven't looked at it recently and never got around to making a PR for it. 

In one recent application I have just been explicitly storing a given PlanNd object and using it as a context manager rather than relying on a plan cache. I think having a cache could still be useful, though.

**Comment by grlee77** [comment]
> does pocketfft win now?

It can be faster in some cases than non-preplanned pyFFTW or for small transform sizes due to lower overhead. I think pyFFTW still wins in general when using pre-planned transforms, but the relative benefit is much less than previously. For near-prime sizes, FFTPack could be orders of magnitude slower than pyFFTW, but pocketfft does not have that same weakness.

**Comment by leofang** [comment]
> I know I had a working implementation that was basically a copy of the pyFFTW one, but wanted to instead use a non time-based cache. 

I like a non-time-based cache. Before we migrated to GPUs and used cuFFT, we used pyFFTW a lot with a practically infinite timeout. Could you share with us just briefly why pyFFTW would like a timed one?

I just started looking into how PyTorch implements its cuFFT plan cache. Seems like they do not have any timeout:
https://github.com/pytorch/pytorch/tree/master/torch/backends/cuda (Python level)
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/CuFFTPlanCache.h (C++ level)
I will report back if I have any comments or thoughts for their approach.

**Comment by grlee77** [comment]
> Could you share with us just briefly why pyFFTW would like a timed one?

I don't know what the reasoning was for that choice. It has been that way since before I joined the project. I did see that there was some suggestion to change it to LRU a few years back, but it was not accepted at the time: pyFFTW/pyFFTW#129

**Comment by asi1024** [comment]
`scipy.fftpack.*`s are not guaranteed never to support `plan` argument in the future, so we cannot assure you that we keep the backward compatibility of `plan` keyword argument of `cupy.scipy.fftpack.*`.

**Comment by leofang** [comment]
@asi1024 Don't worry too much 🙂 

First, with `scipy.fft` being added in v1.4.0 and in preference to `scipy.fftpack`, the latter is considered as "long term legacy" (https://github.com/cupy/cupy/pull/2355#issuecomment-517325388) and maintained only for backward compatibility. I doubt there will be any change over its API. 

Second, in the event that a `plan` argument is to be added to `scipy.fftpack`, we can and will try to coordinate the efforts (with @grlee77 and @peterbell10). For example, [this SciPy issue](https://github.com/scipy/scipy/issues/10302#issuecomment-517351532) title is renamed exactly for the need of CuPy discussed here, see https://github.com/scipy/scipy/issues/10302#issuecomment-517351532.

**Comment by niboshi** [comment]
I think the discussion is not necessarily limted to `fft`, but about general policy on how CuPy supports a feature that is not in NumPy (or SciPy). It doesn't seem a good idea to add a CuPy-specific argument to NumPy- or SciPy-compatible functions in general.

If `scipy.fftpack` is "long term legacy", I have a feeling that we have no motivation to improve `cupyx.scipy.fftpack`.

Also, as there's an ongoing issue to add `plan` in `scipy.fft` as @leofang pointed out, I think we should wait for the argument there before making our own interface stable.

**Comment by leofang** [comment]
> I think the discussion is not necessarily limted to `fft`, but about general policy on how CuPy supports a feature that is not in NumPy (or SciPy). 

Agreed.

> It doesn't seem a good idea to add a CuPy-specific argument to NumPy- or SciPy-compatible functions in general.
> 

If it is made a keyword-only argument as discussed above, there is no compatibility issue and I don’t see why it is a concern. Could you elaborate more?

> If `scipy.fftpack` is "long term legacy", I have a feeling that we have no motivation to improve `cupyx.scipy.fftpack`.

I don’t get it. What exactly do you mean here?

> 
> Also, as there's an ongoing issue to add `plan` in `scipy.fft` as @leofang pointed out, I think we should wait for the discussion there before making our own interface stable.

@niboshi It means a deadlock here. The discussion there is on hold largely because we need it here, yet we have not reached any consensus that can be communicated with upstream. As I said we need and can do a coordinated effort, but we need to land somewhere in order to move on. From what I see where we are heading to, this is getting frustrating...😥

**Comment by niboshi** [comment]
>If it is made a keyword-only argument as discussed above, there is no compatibility issue and I don’t see why it is a concern. Could you elaborate more?

If we have our own argument (even if it's keyword-only), it becomes problematic when other libraries adds the same argument with different meaning.
We would have to change the meaning of that argument, which would cause backward incompatibility.
Likeliness does not matter because this is about the general policy throughout CuPy.

>> If `scipy.fftpack` is "long term legacy", I have a feeling that we have no motivation to improve `cupyx.scipy.fftpack`.
>
>I don’t get it. What exactly do you mean here?

I don't know what exactly "long term legacy" means, so I might be wrong, but I feel SciPy does not recommend using these functions. Why should we add new features to them, instead of new ones?

>@niboshi It means a deadlock here. The discussion there is on hold largely because we need it here, yet we have not reached any consensus that can be communicated with upstream. As I said we need and can do a coordinated effort, but we need to land somewhere in order to move on. From what I perceive where we are heading to, this starts getting frustrating...😥

Hmm, I don't think they need our consensus here.
We don't expect them to follow our API, but we follow them.

**Comment by leofang** [comment]
> If we have our own argument (even if it's keyword-only), it becomes problematic when other libraries adds the same argument with different meaning.
We would have to change the meaning of that argument, which would cause backward incompatibility.

@niboshi You are making the same argument as @asi1024 did earlier. I am not convinced that it is the scenario we need to worry about. In particular, 

> We don't expect them to follow our API, but we follow them.

this is a kinda passive view to me. We have SciPy-FFT folks @grlee77 @peterbell10 here & in the linked issue, and @grlee77 and I are familiar enough with CuPy. A coordinated effort is entirely possible (for whether and/or how to support a `plan` argument in `scipy.fftpack`). The preservation of backward ***and forward*** compatibilities will definitely be part of the decision making process to ensure neither `scipy.fftpack` nor `cupyx.scipy.fftpack` is broken. Perhaps you can put more faith in external contributors and be less worried. 🙂

Moreover,

> Likeliness does not matter because this is about the general policy throughout CuPy

this is an argument I have seen more than once, but — correct me if I am mistaken — I cannot find any exact reference to it. For example, it’s not stated in the API Compatibility Policy here: https://docs-cupy.chainer.org/en/latest/compatibility.html.

Finally, there are two more technicalities that will make the situation not as complex as you guys insisted. First, as you reiterated in another PR, Python is a duck-typing language. So if `plan` is added by SciPy, it must have a different type than our `Plan1d` and `PlanNd` here, and we can just detect the type and split the code path. Second, SciPy now switches to pocketfft, which seems to keep `plan` ***not*** exposed to the Python space. Plus, my understanding is that a pocketfft plan can be generated very quickly. In short, they really have no motivation to add an explicit `plan` argument to support pre-generated plans, unless 3rd party libraries like us and pyFFTW requests so.

> I don't know what exactly "long term legacy" means, so I might be wrong, but I feel SciPy does not recommend using these functions. Why should we add new features to them, instead of new ones?

@grlee77 @peterbell10 It would be nice if you could comment briefly on any of the SciPy parts in the above discussions. 😅

**Comment by leofang** [comment]
For those who follow the issue via email notification: I modified my response above to make my points clearer.

**Comment by grlee77** [comment]
Hi @leofang. I think your summary of the SciPy side of things sounds correct.

I understand wanting to keep APIs consistent, but I also think there are practical considerations that warrant exceptions. For example IIRC, `cupy.fft.fft` has always preserved single precision dtypes while NumPy's version explicitly casts to double, so apparently an exception was already made in that case. When there is a clear performance or utility benefit to allowing something, then I think it makes sense to do so as long as it is clearly documented. Perhaps there could even be a specific documentation page that collects these exceptions in a central location for easier reference.

I was also under the impression that the `cupyx` module was perhaps a bit more accepting of such deviations than the core cupy API.

**Comment by leofang** [comment]
> I think your summary of the SciPy side of things sounds correct.

Glad to confirm my understanding! Thank you, @grlee77.

> I understand wanting to keep APIs consistent, but I also think there are practical considerations that warrant exceptions. For example IIRC, `cupy.fft.fft` has always preserved single precision dtypes while NumPy's version explicitly casts to double, so apparently an exception was already made in that case. 

I can throw in more examples of such exceptions that were just vetted and made quite recently:
- `argmin`/`argmax` have different signatures (#2595)
- `allclose` does not return bool (#2799)

which echo what you said:
> When there is a clear performance or utility benefit to allowing something, then I think it makes sense to do so as long as it is clearly documented.  

As for documentation: 
> Perhaps there could even be a specific documentation page that collects these exceptions in a central location for easier reference.

I think in addition to do so in the docstrings, we could also add to https://docs-cupy.chainer.org/en/stable/reference/difference.html.

> I was also under the impression that the `cupyx` module was perhaps a bit more accepting of such deviations than the core cupy API.

This is my impression too. Perhaps it was the reason we added `plan` to `cupyx.scipy.fftpack` in the first place, so I am really surprised at the pushbacks here...

**Comment by leofang** [comment]
This is an update from upstream: two conclusions were reached in scipy/scipy#10302:
1. A keyword-only argument `plan` is added to `scipy.fft`. This is done in scipy/scipy#11408 (to appear in SciPy v1.5.0) and ongoing for CuPy in #2998.
2. The `scipy.fftpack` module is effectively "frozen", so no API changes will be made there, and thus we do not need to worry about incompatibility between `scipy.fftpack` and `cupyx.scipy.fftpack`. 

One more note: If considered as a "drop-in" replacement (though it won't work literally like that), having extra arguments like `plan` in `cupyx.scipy.fftpack` is safe, in the sense that pyFFTW has done that too in `pyfftw.interfaces.scipy_fftpack`: 
https://pyfftw.readthedocs.io/en/latest/source/pyfftw/interfaces/scipy_fftpack.html 
There are more extra arguments added that it is in `cupyx.scipy.fftpack`. Should have raised this point earlier.
