### ISSUE TITLE
`max()` and `min()` handle complex NaN differently from NumPy

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2750]
Reproducer:
```python
import numpy as np
import cupy as cp


cp.cuda.cub_enabled = False  # fall back to cupy's reduction routines
a = [0.5 + 3.7j, np.complex(0.7, np.nan), np.complex(np.nan, -3.9),  np.complex(np.nan, np.nan)]

a_np = np.asarray(a)
print(a_np.max(), a_np.min())

a_cp = cp.asarray(a_np)
print(a_cp.max(), a_cp.min())
```
Outputs from NumPy and CuPy do not match:
```shell
(0.7+nanj) (0.7+nanj)
(nan-3.9j) (nan-3.9j)
```
NumPy seems to propagate the first encountered NaN, but I can't verified this rigorously. BTW, CUB handles this correctly (set `cp.cuda.cub_enabled = True`).

I can't figure out what's wrong by inspecting the `_amax` and `_amin` implementations in `cupy/core/_routines_statistics.pyx`. Seems to be an issue of how pairwise operations are actually done in the reduction kernel.

**Comment by emcastillo** [comment]
Sounds like cupy is not using a proper comparison operator for the complex numbers?

**Comment by leofang** [comment]
Taking `max()` as example, I actually tried manipulating here
https://github.com/cupy/cupy/blob/8d6317313a714dd37a69fe4738fbc09fd6a88b1b/cupy/core/_routines_statistics.pyx#L130-L138
and here
https://github.com/cupy/cupy/blob/8d6317313a714dd37a69fe4738fbc09fd6a88b1b/cupy/core/include/cupy/complex.cuh#L71-L86
and various combinations, but none of them worked. So this was why I suspected the problem is in the reduction kernel implementation, not in the comparison operator.

**Comment by leofang** [comment]
I thought about it, and I think this can be marked "unsolvable". CuPy performs strided reductions -- the reduction is done among two elements separated by the stride size. So, if the order of first encountering matters, this algorithm would break. 

Ex: For the case `input = [a, X1, X2, X3]`, where `X` has NaN, `X1` is the desired answer. But, a two-stage strided reduction, with stride size 2 in the first stage, would give `[a, X1, X2, X3] -> [X2, X1] -> X2`. This is exactly what happened here (the element `nan-3.9j` -- corresponding to `X2` -- was returned).

**Comment by emcastillo** [comment]
I cross-checked what you said and you are right.
I think this behavior should be documented. 
Would you like to add a note to max, and min docstrings with this?

**Comment by leofang** [comment]
I am not sure which place is better. Another possibility is to mention this in "Difference between CuPy and NumPy". It's up to you 😇

**Comment by emcastillo** [comment]
"Difference between CuPy and NumPy" sounds good

With some sentence like "The way that reductions are done in the GPU does not ensure a proper
comparison order for some NaN inputs, resulting in subtle differences from NumPy".

**Comment by leofang** [comment]
Do we wanna document that CUB reductions can handle this (even though it's not applicable to all scenarios)?
