### ISSUE TITLE
CUPY 7.0 fails with Python 2.7

### ISSUE THREAD

**Issue by JanuszL** [cupy/cupy#2763]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
 - Python version 2.7.15+
  - CuPy version 7.0.0
  - Ubuntu 18.04
  - CUDA version NA
  - cuDNN/NCCL version (if applicable) NA
* Code to reproduce
```
Run python, issue `import cupy`.
```
* Error messages, stack traces, or logs
```
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cupy/__init__.py", line 47, in <module>
    import cupyx as _cupyx
  File "/usr/local/lib/python2.7/dist-packages/cupyx/__init__.py", line 11, in <module>
    from cupyx._ufunc_config import errstate  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/cupyx/_ufunc_config.py", line 17
    def errstate(*, divide=None, over=None, under=None, invalid=None, linalg=None):
                  ^
SyntaxError: invalid syntax
```

**Comment by grlee77** [comment]
Hi Janusz.
7.0 only supports Python 3.5-3.8. I think you will have to stay on the 6.x releases for python 2 support.

**Comment by JanuszL** [comment]
Hi Gregory,
Thank you for the response. I just noticed that prebuild packages are not available for Python 2.7, and the reason why it installs in my case is that source distribution cannot be limited to a particular python version.
Maybe source distribution installation could fail with python 2.7 with an appropriate message?

**Comment by leofang** [comment]
> Maybe source distribution installation could fail with python 2.7 with an appropriate message?

Good suggestion. I made a PR (#2766) for this.

**Comment by JanuszL** [comment]
Thanks!

**Comment by leofang** [comment]
Rel: https://stackoverflow.com/questions/59276773/cupy-with-tx2-and-cuda-9-0
