### ISSUE TITLE
Deprecate warning for some Python and CUDA codes

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2768]
See, for example, https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=101105

Python:
- `PyThread_get_key_value` (observed starting 3.7)
- `PyThread_set_key_value` (observed starting 3.7)
- `PyThread_create_key` (observed starting 3.7)

CUDA:
- `cuParamSetTexRef` (based on the doc this was already marked deprecated at least starting 8.0)
- `cudaPointerAttributes::isManaged`  (observed starting 9.2, but the doc says 10.0)
- `cudaPointerAttributes::memoryType` (observed starting 9.2, but the doc says 10.0)

**Comment by niboshi** [comment]
Thank you for raising an issue!
Just a pointer to a related issue: #1940

**Comment by leofang** [comment]
Thanks, @niboshi! I knew I've seen this raised somewhere!

**Comment by leofang** [comment]
I think I added `cuParamSetTexRef` in #2432 but didn't really use it 😅

**Comment by leofang** [comment]
With #2769 and #2770 merged, now we are left with the warnings from `cudaPointerAttributes`.

**Comment by leofang** [comment]
> * `cudaPointerAttributes::isManaged`  (observed starting 9.2, but the doc says 10.0)
> * `cudaPointerAttributes::memoryType` (observed starting 9.2, but the doc says 10.0)

As far as I can tell, these attributes are never used in the codebase. How about just removing them entirely so as to suppress the deprecation warning? We're gonna remove them when they are removed from CUDA anyway.
