### ISSUE TITLE
CUDA stream errors

### ISSUE THREAD

**Issue by xiaodong-yu** [cupy/cupy#2777]
When I play with the CUDA stream APIs in cupy, I find even running the official examples (cupy/examples/stream/cufft.py) returns the following errors:
Exception ignored in: <bound method Stream.__del__ of <cupy.cuda.stream.Stream object at 0x7fa0f7366050>>
Traceback (most recent call last):
  File "cupy/cuda/stream.pyx", line 168, in cupy.cuda.stream.Stream.__del__
  File "cupy/cuda/stream.pyx", line 50, in cupy.cuda.stream._set_current_stream
AttributeError: 'NoneType' object has no attribute 'ref'

I believe I installed cupy 6.5 for my CUDA version (10.0), anybody knows what causes this error? Thank you so much in advance!

**Comment by leofang** [comment]
Possibly the same problem: #2658 

@emcastillo I was not alone! Could it be some modules have a hidden stream added for some reason, and that stream was deconstructed too late (after `cupy.cuda.runtime` is de-imported)?

**Comment by emcastillo** [comment]
I am not sure but maybe https://github.com/cupy/cupy/pull/2769/ can fix this.

The problem seems to be that part of the thread-local storage gets blown up before the stream itself is destructed.

**Comment by leofang** [comment]
> I am not sure but maybe #2769 can fix this.

Just tested the master branch on the machine that I observed the #2658 symptom, and it still happens ☹️

**Comment by emcastillo** [comment]
The problem is object destruction order here, the globals are not guaranteed to be alive when a object `__del__` is called. I think that just wrapping it into a try/catch should suffice

**Comment by leofang** [comment]
I wonder why it is not reproducible everywhere...

**Comment by leofang** [comment]
@xiaodong-yu could you confirm that the error you saw happened at interpreter shutdown, i.e., the script itself ran correctly?

**Comment by niboshi** [comment]
#2809
