### ISSUE TITLE
`TypeError` when using `cupy.nanstd` and `cupy.nanvar`

### ISSUE THREAD

**Issue by heyu91** [cupy/cupy#2780]
Hello, `cupy` raised `TypeError` when I ran the following code.

```python
import cupy as cp

cp.nanstd(cp.asarray([1, 2, 3, 4, 5], dtype='float64'))
```
the error is shown as below:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-167-1194b91fc5af> in <module>
      1 import cupy as cp
      2 
----> 3 cp.nanstd(cp.asarray([1, 2, 3, 4, 5], dtype='float64'))

~\Anaconda3\envs\py37\lib\site-packages\cupy\statistics\meanvar.py in nanstd(a, axis, dtype, out, ddof, keepdims)
    219     # TODO(okuta): check type
    220     return _statistics._nanstd(
--> 221         a, axis=axis, dtype=dtype, out=out, ddof=ddof, keepdims=keepdims)

cupy/core/_routines_statistics.pyx in cupy.core._routines_statistics._nanstd()

cupy/core/_routines_statistics.pyx in cupy.core._routines_statistics._nanstd()

cupy/core/_routines_statistics.pyx in cupy.core._routines_statistics._nanvar()

cupy/core/reduction.pxi in cupy.core._kernel.ReductionKernel.__call__()

cupy/util.pyx in cupy.util.memoize.decorator.ret()

cupy/core/_kernel.pyx in cupy.core._kernel._decide_params_type()

cupy/core/_kernel.pyx in cupy.core._kernel._decide_params_type_core()

TypeError: Type is mismatched. _count <class 'numpy.int32'> <class 'numpy.int64'>
```

Here is some information about my device:

OS : Windows 10 64 bit

Python : 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]

numpy Vesion : 1.74.4

CuPy Version : 7.0.0

CUDA Root : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0

CUDA Build Version : 10000

CUDA Driver Version : 10020

CUDA Runtime Version : 10000

cuBLAS Version : 10000

cuFFT Version : 10000

cuRAND Version : 10000

cuSOLVER Version : (10, 0, 0)

cuSPARSE Version : 10000

NVRTC Version : (10, 0)

cuDNN Build Version : 7605

cuDNN Version : 7605

NCCL Build Version : None

NCCL Runtime Version : None

**Comment by emcastillo** [comment]
Seems to be a bug on how some datatypes are being handled in windows.
We will look into this.
