### ISSUE TITLE
TypeError: lowerb is not a numpy array, neither a scalar

### ISSUE THREAD

**Issue by Algabri** [cupy/cupy#2781]
how to fix this error
here more details
https://stackoverflow.com/questions/59224490/typeerror-lowerb-is-not-a-numpy-array-neither-a-scalar

**Comment by emcastillo** [comment]
Opencv does not work with cupy arrays, you will need to convert back and from cupy when calling Opencv using the cupy.asnumpy and cupy.asarray functions.

**Comment by Algabri** [comment]
when using `cupy.asnumpy` , the output: ```
Traceback (most recent call last):
  File "/home/redhwan/learn.py", line 22, in <module>
    mask = cv2.dilate(mask, kernal , iterations=1)
TypeError: kernel is not a numpy array, neither a scalar
```

when using `cupy.asarray` , the output: 

```
Traceback (most recent call last):
  File "/home/redhwan/learn.py", line 18, in <module>
    mask = cv2.inRange(hsv, red_lower, red_upper)
TypeError: lowerb is not a numpy array, neither a scalar
```

**Comment by emcastillo** [comment]
Unfortunately, you can't call OpenCV functions with cupy arrays.

**Comment by Algabri** [comment]
Thanks, emcastillo for this information

**Comment by AlexanderKozhevin** [comment]
@emcastillo Hey, so if we can't use cupy arrays in OpenCV, 
can we convert cupy results to numpy?

Im my case, I'm calling cp.dstack. But I'm getting an error. 

```
result = cp.dstack([result, cp.ones((512, 512), dtype="uint8") * 255])
```
```
TypeError: src1 is not a numpy array, neither a scalar

```
