### ISSUE TITLE
Implementing specific NumPy functions in CuPy 

### ISSUE THREAD

**Issue by suryadwar** [cupy/cupy#2783]
As a part of a course project, I'd like to contribute to CuPy. I reached out to @kmaehashi who told me I could start by implementing simple functions which are not yet present in CuPy according to this [Comparison Table](https://docs-cupy.chainer.org/en/latest/reference/comparison.html).

I would like to start by implementing numpy.argwhere in CuPy. It would be great if someone could guide me on what I can do to implement it.

Thanks!

**Comment by kmaehashi** [comment]
Sorry I haven't responded here after replying to you via email...
Closing as this issue is not active for months.

For those who need support when contributing to CuPy, please join the [Gitter](https://gitter.im/cupy/community) chat so that we can help you.
