### ISSUE TITLE
`__cuda_array_interface__ ` with `NULL` pointer fails to convert to CuPy array

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#2789]
Recently ran into an issue with CuPy's `__cuda_array_interface__` conversion support where it fails if it holds a `NULL` pointer for the data. Here's an example using an existing CuPy array. Though this happens with any `__cuda_array_interface__` supporting object that holds a `NULL` pointer. 

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version: 6.6.0
  - OS/Platform: Ubuntu 18.04, x86_64
  - CUDA version: 10.0
  - cuDNN/NCCL version (if applicable): 7.6.4/2.4.6
* Code to reproduce

```python
import cupy                                                             

a = cupy.empty((0,), dtype="|u1")                                       
a2 = cupy.core.core._convert_object_with_cuda_array_interface(a)
```

* Error messages, stack traces, or logs

```python
CUDARuntimeError                          Traceback (most recent call last)
<ipython-input-3-cf9277f8c1fb> in <module>
----> 1 a2 = cupy.core.core._convert_object_with_cuda_array_interface(a)

cupy/core/core.pyx in cupy.core.core._convert_object_with_cuda_array_interface()

cupy/core/core.pyx in cupy.core.core._convert_object_with_cuda_array_interface()

cupy/cuda/memory.pyx in cupy.cuda.memory.UnownedMemory.__init__()

cupy/cuda/runtime.pyx in cupy.cuda.runtime.pointerGetAttributes()

cupy/cuda/runtime.pyx in cupy.cuda.runtime.check_status()

CUDARuntimeError: cudaErrorInvalidValue: invalid argument
```

**Comment by leofang** [comment]
Thanks, @jakirkham. This was my oversight when fixing it in #2611. As we discussed elsewhere, in this case `ptr = 0` is used as a flag to prevent from looking up the pointer attribute. 

Are you able to create a PR to fix this? It should just be a simple one liner `if ptr > 0: ...` added to `cupy.cuda.memory.UnownedMemory`. I can also create one later today (no access to my computer now). Thanks.

**Comment by jakirkham** [comment]
No worries. There were a lot of good fixes there too. Thanks for all of those. 🙂

Yeah I think it should be straightforward. It might be a little bit until I get to it (so if someone beats me to it no worries), but more than happy to submit a fix. 😄

Mostly wanted to make sure we were aware of the issue and were tracking it somewhere. 😉
