### ISSUE TITLE
Detection of device synchronization

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#2808]
Device synchronization is a source of performance degradation, but currently even some of CuPy functions implicitly (whether intentionally or not) do that (#2797).

It would be nice to have a mechanism to detect device synchronization.

### Proposal

Add a context manager within which any operation that synchronizes the device causes an error. The context manager sets a thread-local configuration variable.

```py
with cupyx.allow_synchronize(False):
    ... # operations that are not supposed to synchronize
```

In low-level CuPy code that cause synchronization like `ndarray.get`, insert `_declare_synchronize()` call as follows:

```py
cpdef _declare_synchronize():
    ... # Raise an error if within allow_synchronize(False).

cdef class ndarray:
    cpdef get(self, ...):
        _declare_synchronize()
       ...
```

### Application in unit tests

Given the above implemented, we could apply it in `testing.numpy_cupy_equal` for example. If the test code has expected device synchronization, the test implementation can enclose the code with `cupyx.allow_synchronize(True)` explicitly.

### Notes
* `ndarray.get` may copy asynchronously if certain conditions are met (if using a non-default stream and given an explicit `out` with pinned memory). If's difficult for the code to predict whether it's actually synchronous or not. Maybe it's safe to separate asynchronous behavior as another method like `ndarray.get_async`.

**Comment by emcastillo** [comment]
I think this is great and could be pretty useful to improve performance of user codes.

One minor detail that just comes to my mind is that instead of declaring every method that synchronizes, could we make the cuda runtime call used to synchronize devices to check the flag set by the context manager. This will solve the second issue, but it will not detect calls that “could” synchronize but they are not doing it due to certain runtime conditions. (I don’t know if your proposal is just to error on anything that may synchronize).

**Comment by leofang** [comment]
+1 for the runtime module to check the flag if possible. This seems more robust, and also less painful for implementing new functions. At least we don’t need to chase after which function syncs.

**Comment by niboshi** [comment]
Even `runtime` API wrapper doesn't know if the call synchronizes (because it depends on the pointer attributes), so it won't solve the problem.

**Comment by emcastillo** [comment]
It doesn't synchronize only if the memory is pinned memory in memcpy calls? or are there other cases where behavior is unclear.

I guess that being able to know if the host memory is page locked or not should be a sufficient condition for this, but I am afraid this is not easy 😢

**Comment by niboshi** [comment]
I'm not sure about other cases, but checking pointer attributes is not roboust, and also incurs some overhead as well.

**Comment by leofang** [comment]
> I'm not sure about other cases, but checking pointer attributes might not be roboust, and also incurs some overhead as well.

I think it is meant to be very robust. One potential pitfall could be the change of fields in the attribute struct (in 10.0 or above? I don't remember...#2768 is relevant). When looking up and interpreting the attributes we should be careful. 

For the overhead, I am always under the impression that it's a cheap operation:
```shell
$ nvprof python -m pytest -v tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
... omitted ...
==17886== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
... omitted ...
                    0.05%  632.73us       100  6.3270us  3.4130us  11.791us  cudaPointerGetAttributes
... omitted ...
```
From what I know, it's rather common in a CUDA program to check the pointer attributes before an operation.

**Comment by niboshi** [comment]
Thank you for the measurement, but 6us looks quite expensive.
In my environment it's about 1us, but I'm still not confident that it's cheap enough for an overhead of the lowest-level API call.
