### ISSUE TITLE
random.randint support for range larger than int32

### ISSUE THREAD

**Issue by fredericoschardong** [cupy/cupy#2816]
[random.randint](https://github.com/cupy/cupy/blob/master/cupy/random/generator.py#L1122) doesn't support ranges larger than int32 apparently because [RandomState._interval](https://github.com/cupy/cupy/blob/f121d14f6d3d2f5b25a58f26d2f8bca40dd10812/cupy/random/generator.py#L631) doesn't. Is there a plan to support larger numbers such as int64 and uint64?

**Comment by emcastillo** [comment]
Hello and thanks for your question,
The main problem here is the reliance in the `curand` library which does not support generating numbers with a extent greater than 2^32 bits.
