### ISSUE TITLE
`cupyx.scipy.fft` is not compatible with `scipy.fft`

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#2843]
In SciPy, `scipy.fft` is accessible after importing `scipy`.
```
$ python -c 'import scipy; print(scipy.fft)'
<module 'scipy.fft' from '/home/niboshi/.pyenv/versions/3.8.0/lib/python3.8/site-packages/scipy/fft/__init__.py'>
```

`cupyx.scipy.fft` is not accessible after importing `cupyx.scipy`.
```
$ python -c 'import cupyx.scipy; print(cupyx.scipy.fft)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'cupyx.scipy' has no attribute 'fft'
```

----
*(What follows is the initial version of this post, where I used an old version of SciPy (1.3.3) and it doesn't apply to the newest one).*
>In SciPy, `scipy.fft` is accessible after importing `scipy` and is a function.
>```
>$ python -c 'import scipy; print(scipy.fft)'
><function fft at 0x7fab290c95e0>
>```
>
>`cupyx.scipy.fft` is not accessible after importing `cupyx.scipy`.
>```
>$ python -c 'import cupyx.scipy; print(cupyx.scipy.fft)'
>Traceback (most recent call last):
>  File "<string>", line 1, in <module>
>AttributeError: module 'cupyx.scipy' has no attribute 'fft'
>```
>
>Further, it's not a function. You have to spell out as `cupyx.scipy.fft.fft`.
>```
>$ python -c 'import cupyx.scipy.fft; print(cupyx.scipy.fft)'
><module 'cupyx.scipy.fft' from '/data2/work/w/repos/cupy/cupyx/scipy/fft/__init__.py'>
>
>$ python -c 'import cupyx.scipy.fft; print(cupyx.scipy.fft.fft)'
><function fft at 0x7f4787ea91f0>
>```

**Comment by grlee77** [comment]
This function ``scipy.fft`` is just ``numpy.fft``. There are a number of other NumPy functions that get imported into the root SciPy namespace as well, but all of them have recently been deprecated: https://github.com/scipy/scipy/pull/10290.

We would like to remove all of them as it is odd to provide functions from a separate library in the public API. Most of them may not be removed for some time, but the current plan is to remove `scipy.fft` from 1.5 so we don't have this weird hack where there is both a function and module with the same name!

**Comment by niboshi** [comment]
Oh...
I was using an old version of SciPy (1.3.3).
I updated the issue description, as the first problem still remains.

**Comment by toslunar** [comment]
I got `scipy.fft` as function will be removed in 1.5.  I'm still not sure about the result of `import scipy; scipy.fft` with scipy 1.5.  The change in the availability of `scipy.fft` module without the import may be a kind of compatibility issue, while SciPy recommends `from scipy import foo` (https://docs.scipy.org/doc/scipy/reference/api.html).

**Comment by niboshi** [comment]
Oh, thanks.
Probably it's a problem at SciPy's side.

**Comment by niboshi** [comment]
https://github.com/scipy/scipy/issues/11264#issuecomment-568426924

Closing as it's confirmed we don't have to follow SciPy's behavior.
