### ISSUE TITLE
Clean up intermediate aliases

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#2863]
Intermediate aliases (something in this file: https://github.com/cupy/cupy/blob/master/cupy/sorting/__init__.py) are not necessary and rather confusing for users.

**Comment by rushabh-v** [comment]
Can you please elaborate on what do you exactly mean by something in that file @niboshi ?

**Comment by niboshi** [comment]
Sorry, what I wrote above (including the title) was not exactly correct.

In order to define a function `cupy.sort`, whose NumPy's counterpart is `numpy.sort`, there are unnecessary objects defined within CuPy:
* `cupy.sorting`
* `cupy.sorting.sort`
* `cupy.sorting.sort.sort`

There are no such intermediate objects in NumPy and they are not meant to be used by users, so I think they should be inaccessible (either by prefixing with `_` or removing them entirely).
I'm sorry for confusing description 😔.

**Comment by rushabh-v** [comment]
Would just renaming the `cupy/sorting/sort.py` to _sort.py and importing * from _sort.py in `cupy/sorting/__init__.py` do it?

**Comment by leofang** [comment]
@kmaehashi This is closed by #2944.

**Comment by toslunar** [comment]
Another example: `cupy.manipulation`

**Comment by kmaehashi** [comment]
Closing this as we're now managing this task in #3420.
