### ISSUE TITLE
Support None value `strides` in `__cuda_array_interface__` while creating array.

### ISSUE THREAD

**Issue by trivialfis** [cupy/cupy#2873]
This line assumes `strides` being a valid iterable value: https://github.com/cupy/cupy/blob/a89d44dc1ed74cdb7a0305dc0312050465a36d90/cupy/core/core.pyx#L2717

While according to numpy `__array_interface__` `strides` can be of value `None`: https://docs.scipy.org/doc/numpy/reference/arrays.interface.html

When input `__cuda_array_interface__` contains None strides, cupy throws an error here:
```
TypeError: zip argument #2 must support iteration
```

**Comment by leofang** [comment]
You are referring to an old snapshot of the codebase. This issue has been fixed in the branches master (for v8), v7, and v6.

**Comment by trivialfis** [comment]
I see, thanks!
