### ISSUE TITLE
converting cupy to numpy is very slow

### ISSUE THREAD

**Issue by ylht** [cupy/cupy#2902]
* Conditions
  - CuPy version 7.0.0
  - OS/Platform Ubuntu 18.04
  - CUDA version 10.1
* Code to reproduce
```python
import cupy as np
import time
size = 60000000
tag = np.zeros(size)
value = np.random.random(size)
starttime = time.perf_counter()
for i in range(100):
    tag +=(value> 0.3)*100
print (time.perf_counter() - starttime)
starttime = time.perf_counter()
cpu_value = np.asnumpy(value)
print (time.perf_counter() - starttime)
```
* Error messages, stack traces, or logs
converting cupy to numpy is very slow The result is
> 0.02095769099832978
> 6.170492547998947

**Comment by emcastillo** [comment]
Replied in https://stackoverflow.com/questions/59578835/convert-cupy-to-numpy-is-very-slow
