### ISSUE TITLE
cupy.einsum is very slow for elementwise operations

### ISSUE THREAD

**Issue by shinaoka** [cupy/cupy#2904]
I've found a performance issue on the einsum function.
The einsum function runs 100x slower than the simple elementwise expression for 1D elementwise operations.

* Conditions
Debian GNU/Linux 10.2

```
CuPy Version          : 7.0.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10000
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10000
cuBLAS Version        : 10000
cuFFT Version         : 10000
cuRAND Version        : 10000
cuSOLVER Version      : (10, 0, 0)
cuSPARSE Version      : 10000
NVRTC Version         : (10, 0)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2408
NCCL Runtime Version  : 2408
None
```

```
Model: 		 Tesla P100-PCIE-16GB
IRQ:   		 35
GPU UUID: 	 GPU-9b34f11a-1998-9a07-e54e-5ff7f7a0157f
Video BIOS: 	 86.00.4d.00.01
Bus Type: 	 PCI
DMA Size: 	 47 bits
DMA Mask: 	 0x7fffffffffff
Bus Location: 	 0000:00:04.0
Device Minor: 	 0
Blacklisted:	 No
```

* Code to reproduce
Here, we measure timings 10 times.

```
N = 10000000

A = cp.zeros(N)
B = cp.zeros(N)
C = cp.empty(N)

print("elementwise operations")
for i in range(5):
    cp.cuda.Stream.null.synchronize()
    t1 = time.time()
    C[:] = A[:] * B[:]
    cp.cuda.Stream.null.synchronize()
    t2 = time.time()
    print(t2-t1)

print("einsum")
for i in range(5):
    cp.cuda.Stream.null.synchronize()
    t1 = time.time()
    C[:] = cp.einsum('i,i->i', A, B)
    cp.cuda.Stream.null.synchronize()
    t2 = time.time()
    print(t2-t1)
```

3. Output
einsum is super slow!
```
elementwise operations
0.0012805461883544922
0.0007987022399902344
0.000858306884765625
0.0008094310760498047
0.0008041858673095703
einsum
0.06707024574279785
0.06706762313842773
0.06700778007507324
0.06230592727661133
0.06144094467163086
```

**Comment by shinaoka** [comment]
I've figured out that the einsum ends up with matmul of two 3D arrays of shape (N, 1, 1).
This function indeed runs slow for these arrays.
In the following results, I used Tesla P4 instead of P100, the numbers differ by a factor of 4.

```
print("matmul")
AA = cp.zeros((N, 1, 1))
BB = cp.zeros((N, 1, 1))
CC = cp.empty((N, 1, 1))

for i in range(5):
    cp.cuda.Stream.null.synchronize()
    t1 = time.time()
    CC[:, :, :] = cp.matmul(AA, BB)
    cp.cuda.Stream.null.synchronize()
    t2 = time.time()
    print(t2-t1)
```

```
matmul
0.31870174407958984
0.2773165702819824
0.26548099517822266
0.2651982307434082
0.26521778106689453
```

**Comment by emcastillo** [comment]
As you noticed, einsum is a generalization of several operations and the current implementation relies on matrix multiplications. Therefore we favor the general case over specific ones and simple Element-wise or reduction operations are expected to be faster when directly implemented.

**Comment by shinaoka** [comment]
Agreed.
But, this issue becomes annoying when cupy is used together with opt_einsum (or numpy.einsum_path).

I am trying to contract many arrays/tensors using the opt_einsum package with cupy backend.
In this case, an optimal contraction is searched at runtime and the whole contraction procedure is split into multiple einsum operations.
Thus, I have no prior knowledge of what elementary operations appear along the contract path. 
If such an "elementwise operation" appears,
it ruins the speed of the contraction.

Do you think if it's possible to add a special treatment of elementwise operations to cupy.einsum?

**Comment by emcastillo** [comment]
It should be possible, let us discuss this in the team.

**Comment by emcastillo** [comment]
Do you have an example of an einsum equation where this is a burden besides the trivial case?

**Comment by shinaoka** [comment]
Thank you for your help.
Another bottleneck in my test calculations is the following.
The einsum is slower than the optimal case by a factor of 10 on P100.
But, it may not a big difference.

```
import cupy as cp
import time

N1, N2, N3 = 20, 100000, 16

a = cp.zeros((N1, N2, N3))
b = cp.zeros(N2)
c = cp.empty((N1, N2, N3))

print("Elementwise operations")
for i in range(5):
    cp.cuda.Stream.null.synchronize()
    t1 = time.time()
    c[:,:,:] = a * b[None,:,None]
    cp.cuda.Stream.null.synchronize()
    t2 = time.time()
    print(t2-t1)

print("Einsum")
for i in range(5):
    cp.cuda.Stream.null.synchronize()
    t1 = time.time()
    c[:,:,:] = cp.einsum('ACB, C->ACB', a, b)
    cp.cuda.Stream.null.synchronize()
    t2 = time.time()
    print(t2-t1)
```

```
Elementwise operations
0.0029981136322021484
0.002943754196166992
0.0029549598693847656
0.002942800521850586
0.0029387474060058594
Einsum
0.02181863784790039
0.02160191535949707
0.021611928939819336
0.021459341049194336
0.021472454071044922
```

**Comment by shinaoka** [comment]
One more (maybe independent) bottleneck:

```
import cupy as cp
import time

N1, N2, N3, N4 = 20, 100000, 16, 30

print("Einsum")
print(N2 * N1 * N3 * N4 * 1e-12)
a = cp.zeros((N2, N1, N3))
b = cp.zeros((N2, N3, N4))
c = cp.empty((N1, N3, N4))
for i in range(5):
    cp.cuda.Stream.null.synchronize()
    t1 = time.time()
    c[:,:,:] = cp.einsum('CAB, CBD->ABD', a, b)
    cp.cuda.Stream.null.synchronize()
    t2 = time.time()
    print(t2-t1)
```

Timings on Tesla P100-PCIE-16GB
```
Einsum
0.00096
0.2861499786376953
0.02833104133605957
0.02822113037109375
0.02715277671813965
0.02727365493774414
```

It may be simply bounded by the memory bandwidth?

**Comment by anaruse** [comment]
One possible solution is to use `cutensorContraction`, a tensor contraction routine in cuTENSOR, instead of `matmul` as a backend for cupy.einsum.

    N = 10000000
    
    A = cp.zeros(N)
    B = cp.zeros(N)
    C = cp.empty(N)
    
    print("elementwise operations")
    for i in range(5):
        cp.cuda.Stream.null.synchronize()
        t1 = time.time()
        C[:] = A[:] * B[:]
        cp.cuda.Stream.null.synchronize()
        t2 = time.time()
        print(t2-t1)
    
    print("einsum")
    for i in range(5):
        cp.cuda.Stream.null.synchronize()
        t1 = time.time()
        C[:] = cp.einsum('i,i->i', A, B)
        cp.cuda.Stream.null.synchronize()
        t2 = time.time()
        print(t2-t1)
    
    print("cuTensor")
    for i in range(5):
        cp.cuda.Stream.null.synchronize()
        t1 = time.time()
        desc_a = cutensor.create_tensor_descriptor(A)
        desc_b = cutensor.create_tensor_descriptor(B)
        desc_c = cutensor.create_tensor_descriptor(C)
        C = cutensor.contraction(1.0,
                             A, desc_a, ('i',),
                             B, desc_b, ('i',),
                             0.0,
                             C, desc_c, ('i',))
        cp.cuda.Stream.null.synchronize()
        t2 = time.time()
        print(t2-t1)

Measurement results on GV100

    elementwise operations
    0.08599257469177246
    0.0007219314575195312
    0.0007059574127197266
    0.0007042884826660156
    0.0007023811340332031
    einsum
    0.2394275665283203
    0.05134439468383789
    0.05128169059753418
    0.04924917221069336
    0.048856496810913086
    cuTensor
    0.1486213207244873
    0.0010166168212890625
    0.0009043216705322266
    0.0009119510650634766
    0.00090789794921875

**Comment by anaruse** [comment]
import cupy as cp
    from cupy import cutensor
    import time
    
    N1, N2, N3 = 20, 100000, 16
    
    a = cp.zeros((N1, N2, N3))
    b = cp.zeros(N2)
    c = cp.empty((N1, N2, N3))
    
    print("Elementwise operations")
    for i in range(5):
        cp.cuda.Stream.null.synchronize()
        t1 = time.time()
        c[:, :, :] = a * b[None, :, None]
        cp.cuda.Stream.null.synchronize()
        t2 = time.time()
        print(t2-t1)
    
    print("Einsum")
    for i in range(5):
        cp.cuda.Stream.null.synchronize()
        t1 = time.time()
        c[:, :, :] = cp.einsum('ACB, C->ACB', a, b)
        cp.cuda.Stream.null.synchronize()
        t2 = time.time()
        print(t2-t1)
    
    print("cuTensor")
    for i in range(5):
        cp.cuda.Stream.null.synchronize()
        t1 = time.time()
        desc_a = cutensor.create_tensor_descriptor(a)
        desc_b = cutensor.create_tensor_descriptor(b)
        desc_c = cutensor.create_tensor_descriptor(c)
        C = cutensor.contraction(1.0,
                                 a, desc_a, ('A', 'C', 'B'),
                                 b, desc_b, ('C',),
                                 0.0,
                                 c, desc_c, ('A', 'C', 'B'))
        cp.cuda.Stream.null.synchronize()
        t2 = time.time()
        print(t2-t1)

Performance measure on GV100

    Elementwise operations
    0.08752107620239258
    0.0018515586853027344
    0.0018191337585449219
    0.001821279525756836
    0.0018160343170166016
    Einsum
    0.19353342056274414
    0.011642932891845703
    0.011593818664550781
    0.01158905029296875
    0.011589527130126953
    cuTensor
    0.15397882461547852
    0.0030057430267333984
    0.0029113292694091797
    0.002923727035522461
    0.002886533737182617

**Comment by anaruse** [comment]
import cupy as cp
    from cupy import cutensor
    import time
    
    N1, N2, N3, N4 = 20, 100000, 16, 30
    
    print("Einsum")
    print(N2 * N1 * N3 * N4 * 1e-12)
    a = cp.zeros((N2, N1, N3))
    b = cp.zeros((N2, N3, N4))
    c = cp.empty((N1, N3, N4))
    for i in range(5):
        cp.cuda.Stream.null.synchronize()
        t1 = time.time()
        c[:,:,:] = cp.einsum('CAB, CBD->ABD', a, b)
        cp.cuda.Stream.null.synchronize()
        t2 = time.time()
        print(t2-t1)
    
    print("cuTensor")
    for i in range(5):
        cp.cuda.Stream.null.synchronize()
        t1 = time.time()
        desc_a = cutensor.create_tensor_descriptor(a)
        desc_b = cutensor.create_tensor_descriptor(b)
        desc_c = cutensor.create_tensor_descriptor(c)
        C = cutensor.contraction(1.0,
                                 a, desc_a, ('C', 'A', 'B'),
                                 b, desc_b, ('C', 'B', 'D'),
                                 0.0,
                                 c, desc_c, ('A', 'B', 'D'))
        cp.cuda.Stream.null.synchronize()
        t2 = time.time()
        print(t2-t1)

Performance measure on GV100

    Einsum
    0.00096
    0.30731821060180664
    0.03711557388305664
    0.037061214447021484
    0.03646731376647949
    0.03490185737609863
    cuTensor
    0.19055414199829102
    0.041312217712402344
    0.04131007194519043
    0.03946805000305176
    0.037695884704589844

**Comment by shinaoka** [comment]
Thank you for your data. Impressive improvement!
Using cuTensor seems to be the right direction.

**Comment by shinaoka** [comment]
Thank you for the fix.
I tried to test the new code but got some error.
It may be due to some mistake in my environment setting but have not figured what's wrong (cutensor is not well documented yet...)

I installed 04d85b422 using pip as follows.
> pip install --user . --verbose --no-cache-dir > pip_out.txt 2>&1

```
  75     Modules:
  76       cuda      : Yes (version 10000)
  77       cusolver  : Yes
  78       cudnn     : Yes (version 7605)
  79       nccl      : No
  80         -> Include files not found: ['nccl.h']
  81         -> Check your CFLAGS environment variable.
  82       nvtx      : Yes
  83       cutensor  : Yes (version 1000)
  84       cub       : No
  85         -> Include files not found: ['cub/util_namespace.cuh']
  86         -> Check your CFLAGS environment v
```

[pip_out.txt](https://github.com/cupy/cupy/files/4062348/pip_out.txt)

Then, I go the following error.
```
> import cupy
> cupy.show_config()
CuPy Version          : 7.0.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10000
CUDA Driver Version   : 10000
CUDA Runtime Version  : 10000
cuBLAS Version        : 10000
cuFFT Version         : 10000
cuRAND Version        : 10000
cuSOLVER Version      : (10, 0, 0)
cuSPARSE Version      : 10000
NVRTC Version         : (10, 0)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : None
NCCL Runtime Version  : None
> cupy.cuda.cutensor.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/cuda/cutensor.pyx", line 229, in cupy.cuda.cutensor.init
  File "cupy/cuda/cutensor.pyx", line 234, in cupy.cuda.cutensor.init
  File "cupy/cuda/cutensor.pyx", line 222, in cupy.cuda.cutensor.check_status
cupy.cuda.cutensor.CuTensorError: CUTENSOR_STATUS_CUDA_ERROR
```

What should I check to figure what's wrong?
My environment is K80 and Debian GNU/Linux 10.2.

**Comment by anaruse** [comment]
That seems because K80 is not supported by cuTensor...

**Comment by anaruse** [comment]
I will prepare another PR to improve performance of "element-wise" cases w/o cuTensor.

**Comment by niboshi** [comment]
#2960 has been merged. I think this issue can be closed.
