### ISSUE TITLE
`cupy.cumsum()` much slower than `cupy.core._routines_math.scan()`?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2905]
I noticed that there are two functions in CuPy that can do prefix sum, so out of curiosity I did a quick benchmark, and I found `cumsum()` is much slower than the internal `scan()` (it's a `cdef` function wrapped by `_scan_for_test()`):
```python
>>> import cupy as cp
>>> import cupyx
>>> c = cp.random.random(1000000)
>>> print(cupyx.time.repeat(cp.cumsum, (c,)))
cumsum              :   468.171 us   +/-66.449 (min:  403.769 / max: 1040.217) us    493.367 us   +/-55.708 (min:  450.144 / max: 1056.448) us
>>> print(cupyx.time.repeat(cp.core._routines_math._scan_for_test, (c,)))
_scan_for_test      :    98.772 us   +/- 5.683 (min:   94.778 / max:  198.381) us    125.730 us   +/- 5.498 (min:  121.152 / max:  219.488) us
>>> cp.allclose(cp.core._routines_math._scan_for_test(c), cp.cumsum(c))
array(True)
```
I wonder if we should just use the implementation of `scan()` in `cumsum()` when the input array is 1D (or raveled)?

**Comment by emcastillo** [comment]
I've been looking at the code.
It actually make sense to do it that way, but that's an ugly hack and I think that we should look into why is cumsum being that slow and try to fix that.

**Comment by emcastillo** [comment]
I just have a PR that solves this without using scan, let me post it :)

**Comment by emcastillo** [comment]
There is a problem with the synchronization and data races.

**Comment by leofang** [comment]
Update: just did a quick test against the master (with #2907 and #2919 included)
```python
>>> import cupy as cp
>>> import cupyx
>>>
>>> c = cp.random.random(1000000)
>>> cp.cuda.cub_enabled=False
>>> print(cupyx.time.repeat(cp.cumsum, (c,)))  # from #2907
cumsum              :    37.220 us   +/-10.946 (min:   34.066 / max:  380.719) us    136.430 us   +/- 9.255 (min:  127.168 / max:  406.944) us
>>> print(cupyx.time.repeat(cp.core._routines_math._scan_for_test, (c,)))
_scan_for_test      :    22.048 us   +/- 3.469 (min:   20.648 / max:   75.092) us    100.439 us   +/- 9.159 (min:   94.528 / max:  148.224) us
>>> cp.allclose(cp.core._routines_math._scan_for_test(c), cp.cumsum(c))
array(True)
>>>
>>> cp.cuda.cub_enabled=True
>>> print(cupyx.time.repeat(cp.cumsum, (c,)))  # from #2919
cumsum              :    25.972 us   +/- 6.498 (min:   23.678 / max:  104.285) us     81.899 us   +/- 4.428 (min:   71.264 / max:  138.048) us
>>> cp.allclose(cp.core._routines_math._scan_for_test(c), cp.cumsum(c))
array(True)
```
So CUB is indeed providing the best performance, but the new scan kernels are also much performant. (This  test is done on a different machine from the one I used when  opening this issue, though.)

I think this issue can be closed now.

cc: @emcastillo
