### ISSUE TITLE
Incorrect logic to check explicit size argument in ElementwiseKernel

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#2908]
Version: current master (0af45a409d002ff8a413f83df1b4df5e6d12792f)

### Code
```py
import cupy
kernel = cupy.ElementwiseKernel(
    'T x, T a', 'T out',
    '''
    out = x + a
    ''')
x = cupy.array([1, 2], dtype='float32')
a1 = cupy.array([3, 4], dtype='float32')
a2 = 9
kernel(x, a1, size=2)  # A (a1 is an array): causes an error
#kernel(x, a2, size=2)  # B (a2 is a scalar): no error
```

A causes an error: `ValueError: Specified 'size' can be used only if all of the ndarray are 'raw'.`,
while B doesn't.
I think B should cause an error as well.

Relevant code: https://github.com/cupy/cupy/blob/0af45a409d002ff8a413f83df1b4df5e6d12792f/cupy/core/_kernel.pyx#L343

**Comment by toslunar** [comment]
#2909 also fixed the following
```python
kernel = cupy.ElementwiseKernel(
    '', 'raw float32 out',
    '''
    out[i] = 1
    ''')
print(kernel(size=2))
```

It returns `[1. 1.]`, while it raised the ValueError before the PR.

**Comment by niboshi** [comment]
@toslunar Thank you for pointing out. I'll add a test.

**Comment by niboshi** [comment]
#2931
