### ISSUE TITLE
Use Cython `cimport` to statically access NumPy's dtypes?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2945]
There are many places in CuPy's Cython codebase where NumPy is imported at runtime just to access the `dtype` information. But this information is statically available from Cython, so instead of, say, doing 
```python
import numpy
my_dtype = numpy.int64  # a fictitious code resembling real-life usage
```
we can equivalently do
```
cimport numpy                    # Cython provides this .pxd header
ctypedef numpy.int64_t my_dtype  # note the _t suffix for dtype names
# my_dtype can then be used as usual
```
so that the `dytpe`s can be determined at compile time. 

Is there any reason CuPy chose not to do so? AFAIK, Cython's exposure of NumPy stubs has been stable for quite some time. Since recently NumPy releases always come with a suggested Cython version to work with, and we are dropping support of older NumPy now (#2900, #2938), IMHO an investigation along this line would worth the effort? (I'm hoping to improve the performance by reducing runtime access of types.)

**Comment by kmaehashi** [comment]
Will `dtype == numpy.int64_t` in Cython code work? (where `dtype` is a user-specified dtype object e.g. `numpy.int64`)

**Comment by leofang** [comment]
Thanks, @kmaehashi. At first glance it's not possible, but there might be some performant solutions. I'll benchmark and report.

**Comment by leofang** [comment]
Unfortunately I am losing my interest in doing this 😅 Might revisit later, but the take-away is that there are too many places in the codebase relying on determining the dtype in runtime. Even if I could come up with a static solution, it won't be easy to throughly fix them.
