### ISSUE TITLE
Remove cupyx.allow_synchronize?

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#2946]
`cupyx.allow_synchronize` (#2808) was introduced originally for both unit tests and users who want to notice device synchronization in their own code.

Application in uint tests was dissmissed (#2893) because much more tests were synchronous than I had expected. 

Now I doubt the usefulness of this feature for users as well.
It's fundamentally impossible to eliminate false positives and/or false negatives.

If we took a policy for zero false positives, there would be too many false negatives which I think would make this feature useless.
For example, the documentation of [cudaMemcpy](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1gc263dbe6574220cc776b45438fc351e8) says *"This function exhibits synchronous behavior for most use cases"*. If we took this policy, we wouldn't be able to consider this function synchronous, because no condition is mentioned that would make this function asynchronous.

If we took a policy to allow some false positives, this feature wouldn't be used to detect unexpected synchronization in users' code.

**Comment by leofang** [comment]
+1 for removing sync detect stuff. Currently we rely on (incomplete) knowledge of the CUDA APIs for the (a-)sync behaviors, but for CUDA libraries (cuFFT, cuSOLVER, whatever) we have absolutely no idea in general, unless someone from NVIDIA is willing to sit down with us and mark all public APIs one by one.

**Comment by kmaehashi** [comment]
I'd like to remove this in v10.
