### ISSUE TITLE
CUDA_PATH and duplicate "bin"

### ISSUE THREAD

**Issue by borissheikman** [cupy/cupy#2950]
Hi! This is my first time posting here. Please excuse me if I missed something :)

I am receiving the following error when I try "import cupy"

>>> import cupy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\204018120\AppData\Local\Programs\Python\Python38\lib\site-packages\cupy\__init__.py", line 14, in <module>
    _environment._setup_win32_dll_directory()  # NOQA
  File "C:\Users\204018120\AppData\Local\Programs\Python\Python38\lib\site-packages\cupy\_environment.py", line 38, in _setup_win32_dll_directory
    os.add_dll_directory(os.path.join(cuda_path, 'bin'))
  File "C:\Users\204018120\AppData\Local\Programs\Python\Python38\lib\os.py", line 1105, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\bin\\bin'
>>>

I am running Python 3.8.1 on a Windows 10 Pro machine.

"Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32"

I installed cupy using "pip install cupy-cuda101" according to cupy's documentation.

I have CUDA v10.2, the latest, installed. Is this an issue? I would be happy to install v10.1 if that fixes everything. 

I have CUDA_PATH set to "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin". I added "bin" according to issue #2243. 

If I remove "bin" from the CUDA_PATH environment variable then I get lots of errors as described in issue #2243 where DLL files cannot be found. 

Is this an issue or am I do I have something wrong with my configuration?

Thank you for your help!

-=- Boris S.

**Comment by borissheikman** [comment]
Anyone?

**Comment by kmaehashi** [comment]
`cupy-cuda101` is for CUDA 10.1 and does not run with CUDA 10.2.

**Comment by borissheikman** [comment]
Thanks for the reply, @kmaehashi! :)

I installed CUDA 10.1 on my machine alongside 10.2. Now I have both versions.

After installing 10.1 and updating my CUDA_PATH environment variable I no longer see the same error. Everything is fine. For some reason I thought CUDA 10.2 would be backwards compatible but it appears cupy is locked to a specific version of the CUDA toolkit. 

I'm very happy to have cupy working and seeing the significant performance gains.

**Comment by borissheikman** [comment]
Quick question : are there any plans to update cupy so it works with CUDA 10.2? Would there be any additional performance or stability benefit?

**Comment by kmaehashi** [comment]
Yes, CuPy wheels are built for each CUDA version. I'm working on for CUDA 10.2 support in the next release.
