### ISSUE TITLE
Rename `cupy.conj` to `cupy.conjugate`, add new `cupy.conj` alias

### ISSUE THREAD

**Issue by pentschev** [cupy/cupy#2967]
According to NumPy documentation, [`np.conj` is an alias for `np.conjugate`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.conj.html). However, CuPy implements [`cupy.conj`](https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.conj.html) but not `cupy.conjugate`. Given that in NumPy the implementation is `np.conjugate`, I suggest renaming the current implementation to `cupy.conjugate` and make `cupy.conj` and alias for that.

Would there be any reason _not_ to do that?

**Comment by toslunar** [comment]
`cupy.abs` is an alias for `cupy.absolute`.  I'll make a PR to fix the issue.

**Comment by pentschev** [comment]
Thanks @toslunar for working on this!
