### ISSUE TITLE
Columnar matrix slice doesn't work properly with ravel

### ISSUE THREAD

**Issue by thomcom** [cupy/cupy#2970]
When creating a view into a 2d array using `[:, n:]` notation, the resulting view doesn't work properly with `ravel` or functions that depend on it.

```
import cupy as cp
a = cp.zeros((3, 3))
b = a[:, 1:]
b.ravel()[0] = 1
print(b)
b[0, 0] = 2
print(a)
```

``` output
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 2. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
```

As you can see, `b[0, 0]` still works as expected, but the array produced by `ravel` is a copy. This is not the case for the array produced with a row-wise slice:

```
c = a[1:, :]
c.ravel()[0] = 3
print(a)
```

``` output
array([[0., 2., 0.],
       [3., 0., 0.],
       [0., 0., 0.]])
```

This affects me because I'm trying to fill out a tridiagonal matrix using `cupy`, but the upper diagonal can't be properly referenced:
```
d = cp.zeros((3, 3))
cp.fill_diagonal(d, 3)
cp.fill_diagonal(d[1:], 2)
cp.fill_diagonal(d[:, 1:], 1)
print(d)
```

``` output
[[3. 0. 0.]
 [2. 3. 0.]
 [0. 2. 3.]]
```

```
In [182]: cp.show_config()
CuPy Version          : 7.1.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10000
CUDA Driver Version   : 10000
CUDA Runtime Version  : 10000
cuBLAS Version        : 10000
cuFFT Version         : 10000
cuRAND Version        : 10000
cuSOLVER Version      : (10, 0, 0)
cuSPARSE Version      : 10000
NVRTC Version         : (10, 0)
cuDNN Build Version   : 7605
cuDNN Version         : 7600
NCCL Build Version    : 2406
NCCL Runtime Version  : 2406
```

**Comment by takagi** [comment]
Thanks for your report. We've got that the issue is not the way of `cupy.ndarray.ravel` but `cupy.fill_diagonal` uses `ravel` in its implementation as opposed to `numpy.fill_diagonal` that uses `numpy.ndarray.flat`.

The value of `numpy.ndarray.flat` is a `numpy.flatiter` instance. It is supposed to act as Python's  built-in iterator object and the concept is essentially sequential, so providing the same feature in CuPy would be fairly inefficient. Please let us consider how to address this issue. A possible option would be providing `cupy.flatiter` that worked in parallel under giving some restriction compared to `numpy.flatiter`.

**Comment by emcastillo** [comment]
I think that creating a new type of `Indexer` could work

**Comment by takagi** [comment]
I suppose that, as far as making `fill_diagonal` work, 1D basic slicing can be done with making use of the existing `CIndexer`.  

https://github.com/cupy/cupy/blob/27e64d24394f06df57d146443ec8a8311599bee3/cupy/indexing/insert.py#L112

The idea is something like:

```C
extern "C" __global__
void foo(CArray<TYPE, NDIM> a, CIndexer<NDIM> ind, int start, int stop, int step, TYPE value) {
    int n = (stop - start) / step
    CUPY_FOR(i, n) {
        ind.set(start + i * step);
        in0[ind.get()] = value;
    }
}
```
where `ind` is an indexer for the supplied ndarray `a`, and `start`, `stop` and `step` are those of the slicing we want to get in `fill_diagonal`. First, `i` is an index in the 1D  sliced index space, mapped to the ndarray's flattened index space by `start + i * step`. Then, the index in the flattened index space is mapped to the ndarray's n-dimensional index space by the indexer.

@emcastillo Would you take a brief look if it would work?

**Comment by emcastillo** [comment]
Seems a good approach.
