### ISSUE TITLE
Installation error: Visual C++ 14.1 required, but v19.24 is installed

### ISSUE THREAD

**Issue by trzy** [cupy/cupy#2977]
I'm trying to install CuPy on my Windows machine and it complains about Visual C++ 14.1 being required. I've installed the VisualC++ command line build tools and am using Visual Studio Community 2019. I run the x64 developer console (equivalent to executing vcvars64.bat to set the environment).

CuPy is still unhappy. Here is the tail of the output along with the output of me running 'cl' on the command line:

``
creating build\lib.win-amd64-3.7\cupy\core\include\cupy\_cuda\cuda-10.0
    copying cupy\core\include\cupy\_cuda\cuda-10.0\cuda_fp16.h -> build\lib.win-amd64-3.7\cupy\core\include\cupy\_cuda\cuda-10.0
    creating build\lib.win-amd64-3.7\cupy\core\include\cupy\_cuda\cuda-10.1
    copying cupy\core\include\cupy\_cuda\cuda-10.1\cuda_fp16.h -> build\lib.win-amd64-3.7\cupy\core\include\cupy\_cuda\cuda-10.1
    creating build\lib.win-amd64-3.7\cupy\core\include\cupy\_cuda\cuda-9.2
    copying cupy\core\include\cupy\_cuda\cuda-9.2\cuda_fp16.h -> build\lib.win-amd64-3.7\cupy\core\include\cupy\_cuda\cuda-9.2
    copying cupy\core\include\cupy\_cuda\cuda-10.0\cuda_fp16.hpp -> build\lib.win-amd64-3.7\cupy\core\include\cupy\_cuda\cuda-10.0
    copying cupy\core\include\cupy\_cuda\cuda-10.1\cuda_fp16.hpp -> build\lib.win-amd64-3.7\cupy\core\include\cupy\_cuda\cuda-10.1
    copying cupy\core\include\cupy\_cuda\cuda-9.2\cuda_fp16.hpp -> build\lib.win-amd64-3.7\cupy\core\include\cupy\_cuda\cuda-9.2
    copying cupy\cuda\cupy_thrust.cu -> build\lib.win-amd64-3.7\cupy\cuda
    running build_ext
    building 'cupy.core._dtype' extension
    error: Microsoft Visual C++ 14.1 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
Command "d:\nn\src\.venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Bart\\AppData\\Local\\Temp\\pip-install-km7ys3d8\\cupy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Bart\AppData\Local\Temp\pip-record-ub94gskt\install-record.txt --single-version-externally-managed --compile --install-headers d:\nn\src\.venv\include\site\python3.7\cupy" failed with error code 1 in C:\Users\Bart\AppData\Local\Temp\pip-install-km7ys3d8\cupy\
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(.venv) D:\nn\src>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28315 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

(.venv) D:\nn\src>
``

**Comment by toslunar** [comment]
https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering says 

```
MSVC++ 14.1  _MSC_VER == 1910 (Visual Studio 2017 version 15.0)
...
MSVC++ 14.24 _MSC_VER == 1924 (Visual Studio 2019 Version 16.4)
```

**Comment by kmaehashi** [comment]
Please use pre-built wheels as suggested in the installation guide, unless you have specific reasons to build from source.
https://docs-cupy.chainer.org/en/latest/install.html#install-cupy

FYI, Visual C++ version required to build modules depends on Python version.
https://wiki.python.org/moin/WindowsCompilers#Which_Microsoft_Visual_C.2B-.2B-_compiler_to_use_with_a_specific_Python_version_.3F
