### ISSUE TITLE
Drop Python 3.5 support

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#2993]
Related: #2900

[NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) specifies Python drop plan as well. We should drop Python 3.5 according to it.
Thank you @leofang for pointing out! (https://github.com/cupy/cupy/pull/2938#issuecomment-576883982)

**Comment by leofang** [comment]
Thanks! I asked this because I wondered if we should
1. merge #2766 first, backport it to v7, and then drop Python 3.5 in v8, or
2. drop 3.5 directly in #2766

Perhaps 1 is easier and cleaner?

**Comment by leofang** [comment]
btw, the CI needs to stop testing PY35.

**Comment by kmaehashi** [comment]
I think this decision is a bit early as the default Python in Ubuntu 16.04 LTS is Python 3.5.
Unlike NumPy, using older versions of CuPy is not reasonable for some users as (1) CuPy is actively developed, (2) we're not providing support for the latest CUDA in older versions (e.g., if we drop Python 3.5 in v8, Ubuntu 16 (Py 3.5) users who need future CUDA versions need to build v7 (which is no longer unsupported by us after v8 release) from source, even though both Ubuntu and CUDA are under support)

**Comment by leofang** [comment]
Well, that's a fair consideration, given that Ubuntu 16.04 is still supported by NVIDIA as of CUDA 10.2.

However, I think Python users are kinda forced to gradually move away from Python 3.5 because of NEP 29. Even if CuPy supports it, other libraries likely do not, and I think it's best to just follow the trend. 

For users who really have to stay on Python 3.5, there are a number of options like virtualenv and conda. They don't have to stick to system Python. (In the past this was the recommended practice on OS X to not use system Python, but nowadays it seems to become a universal recommendation.)

**Comment by kmaehashi** [comment]
Discussed in the team and decided to continue Py35 support, as we have no immediate need to drop it. We may revise this decision when the situation changes.

(It seems there're more Python 3.5 users than 3.8 users at least for now... https://pypistats.org/packages/cupy)

**Comment by leofang** [comment]
Thanks for the update and the link (it's handy!), @kmaehashi. I only have one comment:

> (It seems there're more Python 3.5 users than 3.8 users at least for now... https://pypistats.org/packages/cupy)

That's expected. You should compare 3.5 users to those on 3.6 and 3.7. The former is significantly lower. So, the other way of looking at this is that by dropping PY35 support we can force these users to update, which is something they need to do anyway to use other projects from the NumPy ecosystem.

**Comment by leofang** [comment]
Hi @kmaehashi Just wanna bring this to your attention: NumPy folks have dropped the support of **PY35** for the upcoming 1.19 (https://github.com/numpy/numpy/pull/14673), and today they are actively discussing dropping **PY36** (starting here: https://github.com/numpy/numpy/pull/14086#issuecomment-644990246), as the support window specified in NEP-29 is close to end soon.

**Comment by kmaehashi** [comment]
I revisited this issue with @asi1024. We'll keep Python 3.5 support for v8 but drop in v9.

**Comment by leofang** [comment]
It'd be nice to drop Python 3.5 from the current master. I think f-strings from Python 3.6 is a very nice feature for handling strings (in comparison to `string.Template(...).substitute(...)`).
