### ISSUE TITLE
Remove Python 2 support in code

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#2994]
- [x] Eliminate `six`
- [x] Eliminate `__future__` imports
- Eliminate py2-specific fixes, e.g. 
- [x]  `_tempdir`,  #3003
- [x]  `cupy.util.collcetions_abc`,
- [x] Py2-only route (grep with  `sys.version_info`)) #3004

**Comment by niboshi** [comment]
`six` and `cupy.util.collections_abc` have been removed in #2980.
