### ISSUE TITLE
Implement cupy.require

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#2999]
Much as there is a [`numpy.require`]( https://docs.scipy.org/doc/numpy-1.17.0/reference/generated/numpy.require.html ), it would be useful to have a `cupy.require` for enforcing certain requirements are met by the array returned.

**Comment by niteya-shah** [comment]
Hello, I would like to work on this Issue.

**Comment by jakirkham** [comment]
Wow that's great @niteya-shah! 😄 Thanks so much for solving this
