### ISSUE TITLE
Implementing `__bytes__` on `ndarray`s

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#3007]
It would be useful to have an implementation of `__bytes__` for `ndarray` analogous to NumPy's. Ideally this would avoid an intermediate copy to a NumPy array (by using things like `cuMemcpyDtoH`).

**Comment by Harshan01** [comment]
Could you please elaborate more on the issue? I couldn't find any implementation of `__bytes__` for NumPy `ndarray`.

**Comment by jakirkham** [comment]
I think they are just calling `.tobytes(...)`. Maybe we can do the same 🙂

```python
In [1]: import numpy as np                                                      

In [2]: a = np.arange(6, dtype="u1").reshape((2, 3), order="F"); a              
Out[2]: 
array([[0, 2, 4],
       [1, 3, 5]], dtype=uint8)

In [3]: a.tobytes()                                                             
Out[3]: b'\x00\x02\x04\x01\x03\x05'

In [4]: bytes(a)                                                                
Out[4]: b'\x00\x02\x04\x01\x03\x05'
```

Though agree it's not easy to figure out how they are hooking this in. Maybe raise an issue upstream if you are interested in more details about what is happening 😉 (would be interested to hear as well 🙂)

**Comment by emcastillo** [comment]
Sorry, as I commented on the PR we try not to add functions to the core array that are not present in NumPy if they are not strictly necessary to try to keep compatibility as high as possible.

Since `tobytes` does exactly this. Implementing `__bytes__` is not needed at the current stage.
Sorry and thanks for the effort.

**Comment by jakirkham** [comment]
I'm not sure I understand. NumPy does implement this as [shown above]( https://github.com/cupy/cupy/issues/3007#issuecomment-593180427 ). What am I missing here? 🤔

Well the values of `__bytes__` is that I can call `bytes(...)` on a wide variety of objects (not just NumPy-like arrays) and it just works. IOW it works very nicely with duck-typing. 🙂

**Comment by emcastillo** [comment]
Sorry, it is my mistake

**Comment by jakirkham** [comment]
No worries. Thanks for checking 🙂

Honestly I'm still not sure (even after having read some of the C code). It's a great question. Probably it has been hooked into the C-level somehow? Asking upstream to see if they can shed some light on it ( https://github.com/numpy/numpy/issues/15698 ). 😉

**Comment by leofang** [comment]
Thanks, John. I'm also confused. Parsed the NumPy C code and found nothing.

This is just chatting: sometimes I wonder if the mailing list can be abandoned when a project is hosted on GitHub or somewhere else...It's much easier to search and link.

**Comment by Harshan01** [comment]
I observed that their implementation of `tobytes` is `PyArray_BYTES`, but I couldn't find any mention of `PyObject_Bytes` for `ndarray`, for hooking into Python.

**Comment by jakirkham** [comment]
Yeah what implements `tobytes` at the C-level is actually [`PyArray_ToString`]( https://docs.scipy.org/doc/numpy/reference/c-api.array.html#c.PyArray_ToString ), which gets [wrapped here]( https://github.com/numpy/numpy/blob/e682fc21b20a58f5665a78fdd7d9785320a03ab7/numpy/core/src/multiarray/methods.c#L566 ). This is then [hooked into the methods as `tobytes`]( https://github.com/numpy/numpy/blob/e682fc21b20a58f5665a78fdd7d9785320a03ab7/numpy/core/src/multiarray/methods.c#L2837-L2839 ).

I would expect to see something similar for `__bytes__`, but we don't see that. As NumPy is actually a pretty old code base, we might also find [`tp slots`]( https://docs.python.org/3/c-api/typeobj.html#examples ). Maybe [this]( https://github.com/numpy/numpy/blob/e682fc21b20a58f5665a78fdd7d9785320a03ab7/numpy/core/src/multiarray/arrayobject.c#L1782 )? (NumPy's build system is actually pretty sophisticated so that might be wrong) What I'm less sure of is whether `__bytes__` might map to one of these.

Though this could all be wrong and maybe Python is doing [the heavy lifting here]( https://github.com/numpy/numpy/issues/15698#issuecomment-594334920 ).

(Yeah GitHub is pretty nice for discussion I think. Some people have pushed for Discourse. Haven't used that enough to have an opinion yet.)

**Comment by Harshan01** [comment]
Though, `bytes(a)` works, I don't think it is supported by numpy officially, because `bytes` for an empty numpy array works mysteriously. 
`
>>> z = np.empty((), dtype=np.int8)
>>> z.tobytes()
b'\x00'
>>> bytes(z)
b''

>>> z = np.empty((), dtype=np.int64)
>>> z.tobytes()
b'\x90gd\x1b\x19V\x00\x00'
>>> bytes(z)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError
`

**Comment by Harshan01** [comment]
Or it could be a bug, so an issue could be raised upstream.

**Comment by jakirkham** [comment]
Yeah that seems like a bug to me. Would expect to get `b''` in all cases.

**Comment by jakirkham** [comment]
It seems `bytes` handles `memoryview`s similarly to `tobytes`.

```python
In [1]: import numpy as np                                                      

In [2]: a = np.empty((), dtype=np.int8)                                         

In [3]: a.tobytes()                                                             
Out[3]: b'\x00'

In [4]: bytes(a)                                                                
Out[4]: b''

In [5]: bytes(memoryview(a))                                                    
Out[5]: b'\x00'
```

**Comment by Harshan01** [comment]
This does solve some of the mystery. But I am still confused as to what implementation is to be used for `cupy`.

**Comment by jakirkham** [comment]
Maybe `bytes(self.get())` (where `self` is the `ndarray`)? This aligns most closely to what NumPy is doing as it uses NumPy's behavior exactly.

**Comment by Harshan01** [comment]
This could be possibly done. Then, the documentation for `tobytes` needs to be altered to include a warning message that for some cases, it could differ from `__bytes__`

**Comment by jakirkham** [comment]
When you have a chance, it would be good to capture some of these edge cases in that NumPy issue as a comment. I think the NumPy developers will find this interesting 🙂

**Comment by Harshan01** [comment]
I think this is a bug on Numpy's part (see comment on numpy/numpy#15698). The `bytes` differs with `tobytes` only for empty shape tuple with `int` dtype.

**Comment by jakirkham** [comment]
Thanks for collecting and sharing all of those details with them, Harshan. 😄 Let's see what they say 😉
