### ISSUE TITLE
MemoryPool().free_all_bytes() doesn't change the value of total_bytes()

### ISSUE THREAD

**Issue by gjy1992** [cupy/cupy#3008]
* Conditions
  - OS/Platform: Window 10
  - CuPy Version          : 7.1.1
  - CUDA Root             : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
  - CUDA Build Version    : 10000
  - CUDA Driver Version   : 10020
  - CUDA Runtime Version  : 10000
  - cuBLAS Version        : 10000
  - cuFFT Version         : 10000
  - cuRAND Version        : 10000
  - cuSOLVER Version      : (10, 0, 0)
  - cuSPARSE Version      : 10000
  - NVRTC Version         : (10, 0)
  - cuDNN Build Version   : 7605
  - cuDNN Version         : 7605
  - NCCL Build Version    : None
  - NCCL Runtime Version  : None
* Code to reproduce
  just as the code in https://docs-cupy.chainer.org/en/latest/reference/memory.html, 
  after a=None and mempool.free_all_blocks(), mempool.total_bytes() is still 512.
  The real memory usage in GPU is indeed freed, but the value of total_bytes() is not changed.
  This will make an influence on further malloc action when a non-zero limit is set. The actual memory is enough but the allocator thought total_bytes_limit is reached.

**Comment by takagi** [comment]
Thanks for the reporting. I can exactly reproduce the issue on my local. I'll look into it to find what happens.

**Comment by takagi** [comment]
It seems that #2113 introduced `SingleDeviceMemoryPool._total_bytes` to eagerly compute total bytes in order to check if the memory allocation limit is reached effeiciently, while it is not properly decremented when allocated memory is released.
