### ISSUE TITLE
[Bug] Mask assignment throws an error when CUPY_EXPERIMENTAL_SLICE_COPY=1

### ISSUE THREAD

**Issue by daxiongshu** [cupy/cupy#3013]
An error occurs when setting CUPY_EXPERIMENTAL_SLICE_COPY = 1

  - CuPy version: 6.6.0
  - OS/Platform: Ubuntu 16.04.6 LTS
  - CUDA version: 10.0

* Code to reproduce
```
import os
os.environ["CUPY_EXPERIMENTAL_SLICE_COPY"] = "1"
import cupy as cp

a = cp.array([1,2,3,4,5])
a[a<3] = 0
a
```
* Error messages, stack traces, or logs
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-9ff589a008e4> in <module>
      4 
      5 a = cp.array([1,2,3,4,5])
----> 6 a[a<3] = 0
      7 a

cupy/core/core.pyx in cupy.core.core.ndarray.__setitem__()

cupy/core/core.pyx in cupy.core.core.ndarray.__richcmp__()

cupy/core/_kernel.pyx in cupy.core._kernel.ufunc.__call__()

cupy/core/_kernel.pyx in cupy.core._kernel._preprocess_args()

TypeError: Unsupported type <class 'slice'>
```

**Comment by daxiongshu** [comment]
@pentschev Thanks!

**Comment by takagi** [comment]
Thanks for the reporting. I reproduced the issue, let me check its detail.

**Comment by takagi** [comment]
When CUPY_EXMERIMENTAL_SLICE_COPY is enabled, a comparison ufunc is invoked between a ndarray and a slicing object in the following line, causing the type error above:

https://github.com/cupy/cupy/blob/9da978ba0b4fa0605d4755fa00968a7fefe8075f/cupy/core/core.pyx#L1239-L1240

**Comment by pentschev** [comment]
Awesome, thanks for working on this @takagi ! Would you be able to test if this solves your issue @daxiongshu ?
