### ISSUE TITLE
time.clock was removed in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [cupy/cupy#3059]
https://github.com/python/cpython/pull/13270 . Given that the project is Python 3 only it will be better to use the alternatives. There is https://github.com/cupy/cupy/issues/2599 for Python 3.8 but not sure why it didn't error out.

https://github.com/cupy/cupy/blob/8d923719ced31fdff4a42702d395ec87a7e98045/cupy/random/generator.py#L681

**Comment by niboshi** [comment]
This is not relevant to this issue, but `try... except NotImplementedError` should only enclose `os.urandom`.

https://github.com/cupy/cupy/blob/8d923719ced31fdff4a42702d395ec87a7e98045/cupy/random/generator.py#L677-L681

**Comment by rushabh-v** [comment]
I would like to make this change.

will be raising a PR soon.
