### ISSUE TITLE
cupy.linalg.{svd, pinv} should support broadcasting

### ISSUE THREAD

**Issue by carterbox** [cupy/cupy#3062]
Problem
-----------
The NumPy implementation of [pinv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.pinv.html) supports broadcasting, but the CuPy implementation does not.

Conditions
--------------
```
CuPy Version          : 7.0.0
CUDA Root             : /local/cuda-10.0
CUDA Build Version    : 10010
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10010
cuBLAS Version        : 10201
cuFFT Version         : 10101
cuRAND Version        : 10101
cuSOLVER Version      : (10, 2, 0)
cuSPARSE Version      : 10300
NVRTC Version         : (10, 1)
cuDNN Build Version   : 7604
cuDNN Version         : 7605
NCCL Build Version    : 2406
NCCL Runtime Version  : 2506
```
Reproduce
--------------
```python
import numpy as np
import cupy as cp

A = np.random.rand(3, 4, 5)
xA = cp.array(A)
np.linalg.pinv(A)
cp.linalg.pinv(xA)
```
```
Traceback (most recent call last):
  File "pinv.py", line 7, in <module>
    cp.linalg.pinv(xA)
  File "/home/beams/DCHING/miniconda3/envs/tike/lib/python3.7/site-packages/cupy/linalg/solve.py", line 421, in pinv
    u, s, vt = decomposition.svd(a.conj(), full_matrices=False)
  File "/home/beams/DCHING/miniconda3/envs/tike/lib/python3.7/site-packages/cupy/linalg/decomposition.py", line 245, in svd
    util._assert_rank2(a)
  File "/home/beams/DCHING/miniconda3/envs/tike/lib/python3.7/site-packages/cupy/linalg/util.py", line 20, in _assert_rank2
    'two-dimensional'.format(a.ndim))
numpy.linalg.LinAlgError: 3-dimensional array given. Array must be two-dimensional
```
Solution
-----------
Change CuPy implementation to allow broadcasting on N+2 dimensional arrays. This may also require updating `cupy.linalg.svd` because `pinv` relies on `svd` and NumPy allows broadcasting for that function too.

**Comment by carterbox** [comment]
Broadcasting has been enabled for some `linalg` functions since [`numpy=1.8`](https://numpy.org/doc/1.18/reference/routines.linalg.html#module-numpy.linalg)

**Comment by carterbox** [comment]
This problem is being addressed in #2337

**Comment by toslunar** [comment]
#2337 implements efficient batched SVD of **small** matrices.  The first support could be done by a trivial loop (in Python or in Cython).

**Comment by carterbox** [comment]
Related to #3470.

**Comment by leofang** [comment]
Related: https://github.com/data-apis/array-api/pull/114, https://github.com/data-apis/array-api/pull/118

**Comment by leofang** [comment]
Batched SVD is in. pinv is the next.
