### ISSUE TITLE
There is no CuPy in PyPI that support CUDA 10.2

### ISSUE THREAD

**Issue by arktrin** [cupy/cupy#3091]
As it said in README.md and also in [official docs](https://docs-cupy.chainer.org/en/stable/install.html), I can install CuPy that support CUDA 10.2 just by using pip (`pip install cupy-cuda102`). But there is no such package in PyPI:
```
$ pip search cupy | grep cupy-cuda
cupy-cuda91 (7.2.0)       - CuPy: NumPy-like API accelerated with CUDA
cupy-cuda92 (7.2.0)       - CuPy: NumPy-like API accelerated with CUDA
cupy-cuda100 (7.2.0)      - CuPy: NumPy-like API accelerated with CUDA
cupy-cuda80 (7.2.0)       - CuPy: NumPy-like API accelerated with CUDA
cupy-cuda90 (7.2.0)       - CuPy: NumPy-like API accelerated with CUDA
cupy-cuda101 (7.2.0)      - CuPy: NumPy-like API accelerated with CUDA
```
I know that a related [issue](https://github.com/cupy/cupy/issues/2667) already exist, but I just want to mention wrong info in docs.

**Comment by emcastillo** [comment]
Wheel packages for CUDA 10.2 (cupy-cuda102) are currently unavailable on PyPI. Packages will be published after getting approval of the file size limit increase.

**Comment by kmaehashi** [comment]
Published `cupy-cuda102`.
