### ISSUE TITLE
Out of bounds array access when using broadcast arrays

### ISSUE THREAD

**Issue by noahstier** [cupy/cupy#3095]
When I compile my kernel that contains a loop over an input array, the compiled PTX contains hard-coded byte offsets from one element in the array to the next. As a result if I pass in an array whose stride is not equal to the size of the data type, the hardcoded offsets are wrong, and it looks like it results in out of bounds array access.

I believe the solution would be to specialize compilation for non-contiguous input arrays.

conditions
---
```
CuPy Version          : 6.0.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10000
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10000
cuDNN Build Version   : 7301
cuDNN Version         : 7605
NCCL Build Version    : 1000
NCCL Runtime Version  : (unknown)
```

Code to reproduce
---
```
import cupy as cp

source_code = """\
extern "C"{

__global__ void test(float* x, float* result, int n) {

    for (size_t i = 0; i < n; i += 1) {
        result[i] = x[i];
    }
}

}
"""

with open("cupy_ptx.txt", "w") as fp:
    fp.write(cp.cuda.compiler.compile_using_nvrtc(source_code))

test_kernel = cp.RawKernel(source_code, "test")

x = cp.broadcast_to(cp.ones(1, dtype=cp.float32), (1000,))
y = cp.zeros(len(x), dtype=cp.float32)
test_kernel((512,), (512,), (x, y, len(x)))

assert cp.all(x == y)
```
Loop body with hardcoded 4-byte offsets:
```
BB0_9:
	add.s64 	%rd29, %rd2, %rd34;
	ld.global.f32 	%f4, [%rd29];
	add.s64 	%rd30, %rd1, %rd34;
	st.global.f32 	[%rd30], %f4;
	ld.global.f32 	%f5, [%rd29+4];
	st.global.f32 	[%rd30+4], %f5;
	ld.global.f32 	%f6, [%rd29+8];
	st.global.f32 	[%rd30+8], %f6;
	ld.global.f32 	%f7, [%rd29+12];
	st.global.f32 	[%rd30+12], %f7;
	add.s64 	%rd34, %rd34, 16;
	add.s64 	%rd31, %rd31, 4;
	setp.lt.u64	%p6, %rd31, %rd3;
	@%p6 bra 	BB0_9;
```

**Comment by asi1024** [comment]
This is expected behavior. The primitive float data type in C does not consider NumPy's strides.

**Comment by noahstier** [comment]
> The primitive float data type in C does not consider NumPy's ndarray strides.

Of course. But cupy could support ndarray strides, either at compile time by not hardcoding the (potentially incorrect) strides, or at kernel launch time by 1) raising an error if the array strides don't match the expected, hard-coded ones, or 2) making a copy of the array so that the strides do match.

This might be enough of a corner case that it's not worth fixing, but it wasn't the behavior I expected.
