### ISSUE TITLE
`cupy.min` returns wrong result when CUB is enabled

### ISSUE THREAD

**Issue by asi1024** [cupy/cupy#3097]
`cupy.min` returns a wrong value when CUB is enabled for float16 inputs.

Reproducer:
```py
import cupy

print(cupy.array([1, 2, 3], dtype='e').min())
print(cupy.array([1, 2, 3], dtype='e').max())
print(cupy.array([1, 2, 3], dtype='f').min())
print(cupy.array([1, 2, 3], dtype='f').max())
```

Result:
```
65500.0
3.0
1.0
3.0
```

**Comment by leofang** [comment]
I think this line should return `b` instead?
https://github.com/cupy/cupy/blob/25b68333154c5aa59750fb6a83ef12f7dc0552f7/cupy/cuda/cupy_cub.cu#L204

**Comment by asi1024** [comment]
@leofang I made a fix. Thanks for your help!

**Comment by leofang** [comment]
Thanks, @asi1024 🙂
