### ISSUE TITLE
Include CUB info in show_config

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#3108]
It would be useful to include info about the CUB build in `cupy.show_config()`. In particular was it enabled and what version/commit were used if so.

**Comment by leofang** [comment]
I thought about this too, but it doesn't seem possible to fetch the CUB version because there's none from the source...

**Comment by jakirkham** [comment]
Interesting. So they don’t define this in a `#define` somewhere?

**Comment by leofang** [comment]
Didn’t find it. Only git tags AFAIK...I’ll take a look how PyTorch handles this issue later.

**Comment by jakirkham** [comment]
No worries. Happy to poke around this as well. Just figured it might be handy when debugging issues 🙂

**Comment by leofang** [comment]
PyTorch takes effectively the same approach as in CuPy: if the CUB headers are found, it uses them. Otherwise, it uses CUB from submodule. John, perhaps it's time for you to poke NVIDIA people? 😉 

(BTW, they've stopped updating CUB for quite a while...I am a bit concerned...)

**Comment by leofang** [comment]
I think for the time being we can just use the git tag (currently we're using v1.8.0) as the source of version string.

**Comment by leofang** [comment]
@jakirkham @emcastillo Catching up with this issue. Apparently, NVIDIA has added a version string to CUB starting v1.9.9 (not released yet), see this commit: https://github.com/thrust/cub/commit/629f01ec7b4f660d293899ab84680fb7819ece42. (Note CUB is taken over from NVLabs to Thrust.) So, if the bundled version is v1.9.9+, getting a version string from the source code wouldn't be a problem. We won't need to parse the git tag records.

**Comment by emcastillo** [comment]
We can then show in the cub version field `< 1.9.9` or the exact one
