### ISSUE TITLE
Implemention of `cupyx.scipy.ndimage.filters`

### ISSUE THREAD

**Issue by coderforlife** [cupy/cupy#3111]
I have implemented nearly all of `cupyx.scipy.ndimage.filters` matching `scipy.ndimage.filters` exactly. However, before I finish it I would like to confirm that I am developing it correctly. I have the file currently in a gist: https://gist.github.com/coderforlife/d953303da4bb7d8d28e49a568cb107b2

This works towards https://github.com/cupy/cupy/issues/2099. One of their requests was one of the missing features though.

Current Lacking Features:
- Does not have the implementations of `generic_filter()` or `generic_filter1d()`.
- I want to make some changes to how rank filters work (includes `rank_filter`, `median_filter`, `percentile_filter`) based on the answers below.
- There are no tests.
- There are no function docs (but most would just refer to the scipy docs).

Changes From Current `cupyx.scipy.ndimage.filters`:
- Implements tons of new functions (and they re-use slightly adjusted code that was already there).
- `convolution()` and `correlate()` were adjusted to support non-contiguous input arrays without copying them (weights are still forced to be contiguous, but they are expected to be quite small).
- `convolution()` and `correlate()` are slightly (~5%) faster now.
- The `ElementwiseKernel`s generated are now more runtime adjustable.

Open Questions:
- The `ElementwiseKernel`s are only used internally and are never returned. Should they have as much as possible compiled into them? The current version of the code compiles the number of dimensions, input shape, weights shape, border mode, constant value, and origin values. My version moves input shape (and actually strides), constant value, and origin values to be runtime values. Is it better to have more compile time values and thus need to compile new `ElementwiseKernel`s more frequently or have more things moved to runtime values and need fewer compiles?
- To implement `generic_filter()` and `generic_filter1d()` I think they should take a `ReductionKernel` (or a Python function that can be fused into a `ReductionKernel`). However, Cuda does not let you call functions in other modules. So to accomplish this I was thinking about re-creating the reduction kernel code in the convolution kernel like at https://github.com/cupy/cupy/blob/de3d32536c39eefea1805f4a7a76a14356eb3bff/cupy/core/_reduction.pyx#L36 however it would actually be simpler since the entire reduction would happen in a single thread and not need synchronization. Is this a reasonable approach?
- Is it okay that numpy is used to create some of the filters internally? It is several orders of magnitude faster than doing it in cupy, even at the large kernels of 25.
- Is the quality of the code okay?

Thanks for your consideration.

**Comment by coderforlife** [comment]
I have updated the code fixing some issues including adding all documentation. I also added a partially working `generic_filter()` and a 'working' `generic_filter1d()` however it turns out that in Scipy the 1d version doesn't behave like any of the other 1d versions so it needs to be updated to be inconsistent...

`generic_filter()` as written now supports 'functions' that are `ReductionKernels`, simple reduction kernels, `Fusion` objects that result in reduction, and regular Python callables that can be fused. There are several issues with the implementation, primarily with handling data types and possible name clashes.

I compared some timings with this generic filter. I used a 1024x1024 image stored as uint8 and did an L2-norm over a 5x5 region.

- Scipy with a Python function using Numpy function: 4.72 s
- Scipy with a `LowLevelCallback` around a Cython function: 47.1 ms (100x faster)
- Cupy using `ReductionKernel`: 855 µs (55x to 5500x faster)

However, for the Cupy function to accept a fusable function I had to make the output a float64 which increased the time to 2.42 ms. This was comparable to using the `ReductionKernel` with a float64 output.

I have another question. For the "no shortcuts" rules, does it mean that I need to fully spell out the following:

- `cupy.fuse` -> `cupy.core.fusion.fuse`
- `cupy.ndarray` -> `cupy.core.core.ndarray`
- `cupy.ReductionKernel` -> `cupy.core._kernel.ReductionKernel`
- `cupy.ElementwiseKernel` -> `cupy.core._kernel.ElementwiseKernel`
- `cupy.ones` -> `cupy.creation.basic.ones`
- `cupy.zeros` -> `cupy.creation.basic.zeros`
- `cupy.array` -> `cupy.creation.basic.array`
- `cupy.asarray` -> `cupy.creation.basic.asarray`
- `cupy.float64` -> `numpy.float64`
- `cupy.sqrt` -> ?

Some of those seem weird because they end up being in protected modules or switch to `numpy`.

**Comment by grlee77** [comment]
Thanks for working on this @coderforlife!

I had also done a similar thing in January of this year, although I did not attempt `generic_filter` or `generic_filter1d` and hadn't posted the code yet. I will try to take a look at this version as well as make the code I have worked on available over the next week. Most likely we can collaborate on getting these into CuPy proper.

I had implemented tests by basically just adapting the existing test suite from `scipy.ndimage`, but had not made the tests consistent with the CuPy style or converted docstrings to the CuPy format.

I also have implementations for many of the `ndimage.morphology` operations and `ndimage.fourier_shift` as well as quite a few functions from scikit-image.

I was hoping to look at refactoring/implementing some things from `ndimage.interpolation`, but so far only made a first-order interpolation kernel for `map_coordinates`. 

The other function I would really like to have is `ndimage.label` as requested in #3119, but I have not tried to implement it myself.

**Comment by Skielex** [comment]
Interesting work!

I've recently implemented ```gaussian_filter``` and ```gaussian_filter1d``` on top of ```cupyx.scipy.ndimage.filters.correlate```, based on the SciPy implementation. As I have no experience writing CUDA code it's just Python. My functions produce results comparable to SciPy, but are much faster with a proper GPU. The code is available here if you want to have look:
https://github.com/Skielex/structure-tensor/blob/master/structure_tensor/cp/filters.py

@coderforlife I tried running your implementation of  ```gaussian_filter``` and ```gaussian_filter1d```. Here are a few things i noticed.
1. Both functions perform really well, much faster than mine. Nice work!
2. ```gaussian_filter``` does not appear the produce correct results. I tried comparing to the results from SciPy and my implementation and values we quite a bit off. Also even though data was float64, there we no decimals on the returned values.
3. Results of ```gaussian_filter1d``` are comparable to SciPy for the data I tested with.
4. ```cupyx.scipy.ndimage.filters.correlate``` suffers significantly from more dimensions, even if the kernel has a size of 1 for the dimensions. Your implementation of ```gaussian_filter1d``` appears to suffer at little from more dimensions even though I believe the computations should be identical.
``` python
# d.shape is (130, 150, 100)
%timeit filters2.gaussian_filter1d(d, 1, -1, mode='nearest'); cp.cuda.Stream.null.synchronize()
# 3.79 ms ± 11.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
%timeit filters2.gaussian_filter1d(d.reshape(-1, 100), 1, -1, mode='nearest'); cp.cuda.Stream.null.synchronize()
# 3.33 ms ± 6.18 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
If you can fix the ```gaussian_filter``` I'd very much like to try it for my [```structure-tensor```](https://github.com/Skielex/structure-tensor) package.

**Comment by coderforlife** [comment]
It is fixed now. I actually discovered that bug yesterday just hadn't uploaded my solution. If the image had an even number of dimensions it would return the last off-numbered dimension result I believe. Now I am getting `np.allclose()` to pass.

For the other issue about speed, this is related to my question about making the internal kernels more flexible or more often compiled. My code makes them compiled less often, but my guess this ends up having a larger overhead especially with larger number of dimensions. I will play around with timing the results of how long things actually take to compile,. I was already leaning towards making more things "compile time" constants.

**Comment by Skielex** [comment]
I found small bug in line [312](https://gist.github.com/coderforlife/d953303da4bb7d8d28e49a568cb107b2#file-filters-py-L302).

``` python
P = numpy.diag(cupy.ones(order) * sigma2i, -1)  # P @ q(x) = q(x) * p'(x)
```
should be 
``` python
P = numpy.diag(numpy.ones(order) * sigma2i, -1)  # P @ q(x) = q(x) * p'(x)
```
otherwise it'll throw an exception when calling with ```order``` > 0

**Comment by Skielex** [comment]
@coderforlife I found another issue in the ```_gaussian_kernel1d``` function. If ```order``` > 0, the weights are calculated wrong, as the value of ```x``` is incorrect.

Is there any reason not just to copy the ```_gaussian_kernel1d``` function directly from SciPy? I can see you opted for in-place ops, which I understand, but I don't think it makes a difference given the relatively small size of the weights. I did a small benchmark and the SciPy one was actually slightly faster.

In this gist I've changed to use an exact copy of the SciPy ```_gaussian_kernel1d``` function and changed the places it is used to be more aligned with the SciPy implementation:
https://gist.github.com/Skielex/14c060b962e1cfb64fe98de9e9dc7cbe

The gist produce the same results on my own implementation, which are close to the SciPy ones. After fixing the issues with ```_gaussian_kernel1d``` I compared time for both ```gaussian_filter1d``` and ```gaussian_filter``` from the [gist](https://gist.github.com/Skielex/14c060b962e1cfb64fe98de9e9dc7cbe) to [my own](https://github.com/Skielex/structure-tensor/blob/master/structure_tensor/cp/filters.py) implementation. Below ```filters_old``` is mine, while ```filters``` is the gist one (yours modified).

``` python
%timeit Vx = filters.gaussian_filter1d(d, sigma, axis=0, order=1, mode='nearest'); cp.cuda.Stream.null.synchronize()
15 ms ± 34.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit Vx2 = filters_old.gaussian_filter1d(d, sigma, axis=0, order=1, mode='nearest'); cp.cuda.Stream.null.synchronize()
34.6 ms ± 74.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit Vx = filters.gaussian_filter(d, sigma, order=[0, 0, 1], mode='nearest'); cp.cuda.Stream.null.synchronize()
44.6 ms ± 268 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit Vx2 = filters_old.gaussian_filter(d, sigma, order=[0, 0, 1], mode='nearest'); cp.cuda.Stream.null.synchronize()
45.1 ms ± 219 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
I'm a bit surprised that while your ```gaussian_filter1d``` is about twice as fast, ```gaussian_filter``` performs the same. As ```gaussian_filter``` uses ```gaussian_filter1d```, I would've thought it to be faster too. The GPU used is a RTX2070 Super and ```d``` is (128, 128, 128) ```float64```.

**Comment by jakirkham** [comment]
This is great! Thanks for driving this work forward @coderforlife and everyone for chipping in 😄

Would it make sense to move this work to a PR for further discussion, refinement, and eventually integration? 😉

**Comment by grlee77** [comment]
> Would it make sense to move this work to a PR for further discussion, refinement, and eventually integration?

To ease review, a potential first step PR from the code proposed by @coderforlife would be to integrate the refactored CUDA kernels for convolution/correlation in place of those currently in CuPy (i.e. a PR focusing on using your refactored `_get_nd_kernel` with the functions already in `cupy.ndimage.filters`).

I tried your kernels on Friday and did find that they are substantially faster (by about a factor of two in some fully dense cases I tested), but I found some existing test cases with even sized kernels and/or non-zero origin did not give matching results. Making a PR updating the existing correlate/convolve would let you reuse the existing CuPy tests to work out any potential bugs in the refactored nd kernels.

**Comment by jakirkham** [comment]
cc @jni @GenevieveBuckley (for general awareness 😉)

**Comment by coderforlife** [comment]
I will work on the PR now. I was on vacation over the last week.

**Comment by grlee77** [comment]
> I will work on the PR now. I was on vacation over the last week.

Sounds good to me, but it would be nice if any core devs here could provide guidance on whether they agree with the general approach in your gist. Having separate 1d/nd cases seems reasonable to me, however if it is possible to just use nd for everything without substantial overhead that would probably ease maintenance.

You may also want to take a look at #3179 which was just recently opened and improves performance for the existing nd convolve/correlate.

**Comment by coderforlife** [comment]
The 1D and ND are actually fairly different beasts. One applies along an axis and the other doesn't.

I am close to submitting. I found two bugs in my code causing failures that I have now fixed (I added origins instead of subtracting and didn't handle 0-sized dimensions exactly like scipy). I am doing some speed tests on some final changes and then submitting the PR.

**Comment by jakirkham** [comment]
FWIW would check against the latest SciPy release. Recall there were a few bugs they fixed. Some of which relate to these edge cases (like 0-sized).

**Comment by coderforlife** [comment]
@Skilex I was attempting to optimize _gaussian_kernel1d() to work as fast with cupy as it did with numpy, and thus trying to use in-place everywhere, but yeah, it could just be Scipy's function.

The (non) speed difference is definitely interesting. I will look into that more.

At the moment my goal is to get a PR with convolve, correlate, convolve1d, and correlate1d including tests. I have the current tests passing with convolve and correlate and have started writing the 1d tests.

**Comment by coderforlife** [comment]
@grlee77 I have added the PR with just convolve, correlate, convovle1d, and correlate1d. All other functions use the same core of `_get_nd_kernel` and `_get_1d_kernel` so once those are seen and approved then I can easily add the rest of the functions (besides the `generic_filter` functions which will likely need some debating). I did fix the even-number-of-dimensions issue (I always returned the last odd dimension result) and the origin issue (a double-negative issue). I have added tests for the 1D versions and this actually caused me to find a bug in scipy, so I fail 8 tests right now because scipy gives the wrong result.

**Comment by jakirkham** [comment]
Did you raise an issue with SciPy already?

**Comment by coderforlife** [comment]
Yes, scipy/scipy#11661

**Comment by grlee77** [comment]
I have made the code mentioned previously ( https://github.com/cupy/cupy/issues/3111#issuecomment-591052725) available at [cupyimg](https://github.com/mritools/cupyimg). 
See a more extended comment related to this in https://github.com/cupy/cupy/issues/2099#issuecomment-598381598.

**Comment by coderforlife** [comment]
@grlee77 You originally requested to see if 1d and nd could be combined, and the answer is yes. With a few tweaks to nd I was able to make 1d work with the nd kernel generation but maintain its speed. I have updating the gist with this and will be updating the PR shortly. At this point all kernels in ndimage.filters are the same base kernel with a few substitutions. I am also curious about making the shared memory kernel like you suggested somewhere and will be playing with that soon.

@Skielex the most recent gist has addressed the speed issues you were seeing (along with the bugs). Length-1 dimensions do not impact significantly speed any more and the speed is more reasonable in general.

**Comment by grlee77** [comment]
> @grlee77 You originally requested to see if 1d and nd could be combined, and the answer is yes. With a few tweaks to nd I was able to make 1d work with the nd kernel generation but maintain its speed. 

Okay, I will take a look. When I implemented the 1d convolutions, I had just reused the same nd kernels and just broadcasted the 1d kernel to be size 1 along any non-filtered axes.

**Comment by coderforlife** [comment]
@grlee77 I did that too, but added in a little if that says if a dimension's length is 1 don't produce the loop or boundary condition checking in CUDA for that dimension. That was necessary to maintain the same speed with the original 1D code.

**Comment by coderforlife** [comment]
@grlee77 Using shared memory for the weights was actually fairly easy using the `loop_prep=` extra argument `cupy.ElementwiseKernel`. It gave marginal improvements. For a 4000-by-4000 image, using various sized kernels:

- 3x3 goes from 750 to 739 µs (1.5% faster)
- 7x7 goes from 1.52 to 1.49 ms (2% faster)
- 11x11 goes from 3.16 to 2.9 ms (9% faster)
- 21x21 goes from 27.8 to 25.3 ms (10% faster)
- 25x25 goes from 37.9 to 34.6 ms (10% faster)
- 29x29 goes from 55.8 to 47.5 ms (17% faster)
- 31x31 goes from 63.6 to 54.6 ms (17% faster)
- 33x33 goes from 66.7 to 41.3 ms (62% faster)
- 35x35 goes from 74.4 to 70 ms (6% faster)
- 37x37 goes from 89.9 to 84.6 ms (6% faster)
- 39x39 goes from 92.5 to 23.1 ms (300% faster)
- 41x41 goes from 110 to 99.4 ms (11% faster)
- 43x43 goes from 121 to 135 ms (12% **slower**)
- 45x45 goes from 120 to 33 ms (264% faster)
- 47x47 goes from 144 to 177 ms (23% **slower**)

I do find the ups and downs in the speed interesting. Like why are 33x33, 39x39, and 45x45 so much faster than the neighboring sizes? How to predict the slower ones?

I played with a few of the shared memory settings. Changing the device cache config with `cudaDeviceSetCacheConfig()` (default was `cudaFuncCachePreferNone`) always caused things to be slower. I could not change the device shared mem config with `cudaDeviceSetSharedMemConfig()`. It default to `cudaSharedMemBankSizeFourByte` and changing to eight-byte had no effect (no error, but `cudaDeviceGetSharedMemConfig()` still returned `cudaSharedMemBankSizeFourByte`). If it matters, this is on a Titan V.

**Comment by coderforlife** [comment]
A few questions about the desired level of compatibility between numpy/scipy and cupy. I am finding that there are some edges cases in which the filters in scipy are very hard to reproduce in cupy. A few examples:

1. Handling of the UB of casting a negative float to an unsigned int. CUDA has this as UB, although it seems that the behavior is to clip to 0 instead of wrap around. In C/numpy I am not sure if this is defined behavior, but it usually seems to wrap around. This is coming up when testing `uint8` inputs with `mode='constant'` and `cval=-1` (an invalid `uint8` value). The point in time in which that `-1` resolves to a `uint8` is highly variable in all of the filters meaning there are lots of places that have inconsistent behavior between the two. I try to move some casting around and it fixes one but breaks another. Should we just write this whole situation off as `cval=-1` makes no sense for `uint8` so it is okay if there is inconsistent behavior? Or should we try to make all possible situations match?

2. Integer outputs with floating-point intermediates. I found this peculiar result in scipy's ndimage (imported as `ndi`):

```python
ndi.gaussian_filter1d(np.array([5, 5, 5]), 2.5) # returns [4, 4, 4], should be all 5's
```

There are numerous way to avoid that particular output, all of the following return all integer 5's:

```python
ndi.gaussian_filter1d(np.array([5, 5, 5]), 2.49)
ndi.gaussian_filter1d(np.array([5, 5, 5]), 2.51)
(ndi.gaussian_filter1d(np.array([5, 5, 5], float), 2.5) + 1e-14).astype(int)
(ndi.gaussian_filter1d(np.array([5, 5, 5]), 2.5, output=float) + 1e-14).astype(int)
```

Additionally, the implementation of `ndi.gaussian_fitler1d` I am writing also happens to return all 5's in the regular case which is making a test fail. The easiest solution would be to just change the 2.5 to something else like 2.25 and call it a day. Do we care?

**Comment by coderforlife** [comment]
Actually, I found that any number I would pick for sigma, either numpy or cupy would round down some of the numbers. Increasing the value of the `truncate` value can help. The `1e-14` solution only helped for small enough `sigma` values, eventually, I needed `1e-12` to deal with it. But that would only apply to cupy, not scipy. If both sides implemented that, then maybe we would have consistent results.

**Comment by coderforlife** [comment]
I actually see that the first issue is with wrapping vs clipping is actually not the same in numpy vs cupy already with the `astype()` method for casting:

```python
((cp.random.rand(10, 10) * 2 - 1)*100).astype(cp.uint8) # contains lots of 0s
((np.random.rand(10, 10) * 2 - 1)*100).astype(np.uint8) # contains lots of >200
```

So apparently this behavior is expected (I found the documenation https://docs-cupy.chainer.org/en/stable/reference/difference.html#cast-behavior-from-float-to-integer that says exactly that).

**Comment by Skielex** [comment]
Thanks for putting so much effort into this @coderforlife! I'm looking forward to replacing my hacky code with a proper ```generic_filter1d``` implementation. Curious to see how much faster it'll be.

While I appreciate as much compatibility as possible, I think we'll just have to live with small variations due to (lack of) floating point precision. If you're using ```gaussian_fitler1d``` with integer input and output, precision is clearly not a great concern. 

In my case, I will be using ```float32``` or ```float64```, so as long as the results are "reasonably" close to SciPy I'm happy.

**Comment by grlee77** [comment]
regarding casting float to unsigned:

At least as of 1.5.0, ndimage does the following in the C code.
https://github.com/scipy/scipy/blob/e4238172b1925e1bf6a554678fd765553f0e069c/scipy/ndimage/src/ni_filters.c#L159-L163

I think if you add a boolean `unsigned_output` to `_get_correlate_kernel` you can modify set `post` argument to `_get_correlate_kernel` using

```Python
if unsigned_output:
    post = 'y = (sum > -1) ? (Y)sum : -(Y)(-sum);'
else:
    post = 'y = (Y)sum;'
```

**Comment by grlee77** [comment]
> Integer outputs with floating-point intermediates. I found this peculiar result in scipy's ndimage (imported as ndi):
>
> ndi.gaussian_filter1d(np.array([5, 5, 5]), 2.5) # returns [4, 4, 4], should be all 5's

I don't think we can ensure identical output in such cases where perhaps one implementation gives a float of 4.999999999999999 while another might give 5.00000000001, so that the cast to integer gives different values. 

In principle one could argue whether integers should be rounded instead in SciPy, but that would still have the same potential differences due to precision, just for values on either side of the midpoint instead.

I have also seen similar differences in rounding for `cupyx.scipy.ndimage` vs `scipy.ndimage` when using interpolation functions like `rotate` with integer output type. I can't remember the exact case offhand, but it was the same type of  issue.

**Comment by grlee77** [comment]
Based on the above how does the following sound?

1.) cast float to unsigned using the same convention from SciPy noted above
2.) add a note to the docstrings indicating potential non-identical results when casting intermediate floats to integer output types

**Comment by coderforlife** [comment]
Sounds good. For the casting bit, I made it based on type_traits abilities:

```C++
// Implements a casting function to make it compatible with scipy
// Use like cast<to_type>(value)

template <typename B, typename A>
__device__
typename enable_if<!is_floating_point<A>::value||is_signed<B>::value, B>::type
cast(A a) { return (B)a; }

template <typename B, typename A>
__device__
typename enable_if<is_floating_point<A>::value&&!is_signed<B>::value, B>::type
cast(A a) { return (a >= 0) ? (B)a : -(B)(-a); }
```

However, I then discovered you can't import `<type_traits>` in NVRTC (even though there is a CUDA-specific version in `<cuda/std/type_traits>` - they didn't mark the `static constexpr` functions as `__device__` functions so it errors out...). So I need to provide a few `<type_traits>` pieces in addition to the 2 functions above:

```
// Small bit of <type_traits> which cannot be imported in NVRTC
// Requires compiling with --std=c++11 or higher
template<bool B, class T=void> struct enable_if {};
template<class T> struct enable_if<true, T> { typedef T type; };
template<class T> struct remove_const          { typedef T type; };
template<class T> struct remove_const<const T> { typedef T type; };
template<class T> struct remove_volatile             { typedef T type; };
template<class T> struct remove_volatile<volatile T> { typedef T type; };
template<class T> struct remove_cv {
  typedef typename remove_volatile<typename remove_const<T>::type>::type type;
};
template<class T, T v>
struct integral_constant { static constexpr T value = v; };
//struct true_type { static constexpr bool value = true; };
//struct false_type { static constexpr bool value = false; };
typedef integral_constant<bool, true> true_type;
typedef integral_constant<bool, false> false_type;
template<class T> struct __is_fp : public false_type {};
template<>        struct __is_fp<float> : public true_type {};
template<>        struct __is_fp<double> : public true_type {};
template<>        struct __is_fp<long double> : public true_type {};
template<class T> struct is_floating_point
    : public __is_fp<typename remove_cv<T>::type> {};
template<class T> struct is_signed : integral_constant<bool, (T)(-1)<0> {};
```
