### ISSUE TITLE
[FEA] Implement cupy.argwhere

### ISSUE THREAD

**Issue by beckernick** [cupy/cupy#3114]
A CuPy equivalent of numpy.argwhere would be a nice addition to the library. This has been mentioned in #2783 , but it's likely worth breaking out into a separate issue for tracking purposes.

**Comment by beckernick** [comment]
@suryadwar if you're still interested, you may be able to implement this feature by combining `cupy.tranpose` and `cupy.nonzero`. Depending on the performance, that might be enough.

**Comment by jakirkham** [comment]
This may be even easier than that. `argwhere` is basically the single array version of `nonzero`. I'd guess that the answer already is available before we transform it into a `tuple` of 1-D arrays. In fact [this line]( https://github.com/cupy/cupy/blob/b17bdb472f4cd5f7d59ffdc7e99be0fb0cee5378/cupy/core/_routines_indexing.pyx#L76 ) suggests as much.

**Comment by beckernick** [comment]
As usual, thanks for finding a potentially cleaner approach to a problem @jakirkham ! 😄

**Comment by jakirkham** [comment]
Happy to help 🙂

Looks like there is now a PR ( https://github.com/cupy/cupy/pull/3135 ) 😉
