### ISSUE TITLE
Support `scipy.ndimage.label`

### ISSUE THREAD

**Issue by emcastillo** [cupy/cupy#3119]
Per request:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.label.html

@anaruse

**Comment by rushabh-v** [comment]
I would like to implement this.

Will be raising a PR soon.

**Comment by rushabh-v** [comment]
Do I need to implement https://github.com/scipy/scipy/blob/e7d5dd4a77a2c330a467fde773e267d5cbb90f13/scipy/ndimage/src/_ni_label.pyx#L204 here or I should directly use `scipy.ndimage.ni_label._label`? @emcastillo

**Comment by emcastillo** [comment]
You have to re-implement it using cuda kernels and/or cupy arrays.

**Comment by jakirkham** [comment]
Agree this would be a nice feature to have 😄

cc @jni @GenevieveBuckley

**Comment by anaruse** [comment]
@rushabh-v, I suppose you have already started working on this, but let me do this one. This is needed for us immediately. Thanks.

**Comment by rushabh-v** [comment]
Okay. No worries!
Even I will be busier for a few days, so you are welcome to go ahead with this 👍

**Comment by jakirkham** [comment]
Thanks for working on this Akira! 😄 Would be interested in looking at a PR once it is ready 😉
