### ISSUE TITLE
`Edit on GitHub` link in API reference is not working

### ISSUE THREAD

**Issue by rushabh-v** [cupy/cupy#3133]
Hyperlink of the `edit on Github` button on the top right corner of this page https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.ndarray.html#cupy.ndarray.nonzero seems to be broken.

right now it is linked to https://github.com/cupy/cupy/blob/107c7d2899fa34af8ea3a80f79edaf950709b764/docs/source/reference/generated/cupy.ndarray.rst

**Comment by emcastillo** [comment]
These ones are generated by sphinx, so there are no actual sources in the repo for them to refer to.
Most of the routines documentation happens to be so, another example:
https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.vdot.html#cupy.vdot

**Comment by emcastillo** [comment]
Related:
https://github.com/readthedocs/readthedocs.org/issues/4671

**Comment by kmaehashi** [comment]
Closing as we migrated to `pydata_sphinx_theme`. `pydata_sphinx_theme` has the same issue (stub pages generated by Sphinx's `autosummary` links to invalid page), so we turned off this Edit link feature.

https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html#add-an-edit-this-page-button
>     "use_edit_page_button": True,
