### ISSUE TITLE
Help, problems in cupy.asnumpy() or cupy.get()。When in first loop, time2 is only 4.3ms.But in next loops，time2 reachs 41+ms.I want  time2 to stays under 5ms.  Does anybody know how to solve this?

### ISSUE THREAD

**Issue by Govan111** [cupy/cupy#3142]
- CuPy version =6.0.0
  - OS/Platform=CentOS
  - CUDA version=10.1
* Code to reproduce
```
import numpy as np
import cupy
import json
import time

regs_feats = cupy.random.normal(size=[200000, 512])
regs_id = cupy.random.randint(1, 110000, (200000,))

def calculate_distance(feats, regs_feats, threshold):
    t0 = time.time()
    try:
        src = cupy.asarray(feats)
        distances = cupy.zeros(shape=(src.shape[0], regs_feats.shape[0]))
        for i in range(src.shape[0]):
            distances[i] = cupy.linalg.norm(src[i] - regs_feats, axis=1)
    except:
        print('failed')
        raise
    candidate_num = 2 if regs_feats.shape[0] > 5 else regs_feats.shape[0]
    t1 = time.time()
    work_numbers, min_distances = [], []
    for i in range(distances.shape[0]):
        min_indices = distances[i].argsort()[: candidate_num]
        numb, dis = [], []
        for j in range(candidate_num):
            numb.append(regs_id[min_indices[j].get()])
            #dis.append(distances[i][min_indices[j]])
        work_numbers.append(numb)
        #min_distances.append(dis)
    print('time1: {},time2: {}'.format(t1 - t0, time.time() - t1))
    return work_numbers, min_distances

if __name__ == '__main__':
    feature = cupy.random.normal(size=[1, 512])
    for i in range(5):
        work_numbers, min_distances = calculate_distance(feats=feature, regs_feats=regs_feats, threshold=1)

```

*The result of running the above program 
time1: 0.04357028007507324,        time2: 0.004300832748413086
time1: 0.00022912025451660156,  time2: 0.04258894920349121
time1: 0.0002181529998779297,    time2: 0.04140281677246094
time1: 0.00023508071899414062, time2: 0.04133772850036621
time1: 0.00021719932556152344,  time2: 0.04119539260864258

**Comment by emcastillo** [comment]
Measuring times without synchronizing the device can lead to weird results as the ones you are seeing.

Inserting `cupy.cuda.Stream.null.synchronize()` in the right places yields the correct results
Before:
```
time1: 0.009093761444091797,time2: 0.002468109130859375
time1: 0.00011539459228515625,time2: 0.007904767990112305
time1: 0.00010585784912109375,time2: 0.007896900177001953
time1: 0.00010323524475097656,time2: 0.00789022445678711
time1: 0.00010013580322265625,time2: 0.00789332389831543
```

After:
```
time1: 0.00883626937866211,time2: 0.0024640560150146484
time1: 0.006998300552368164,time2: 0.0007545948028564453
time1: 0.006988048553466797,time2: 0.0007328987121582031
time1: 0.006985187530517578,time2: 0.0007340908050537109
time1: 0.006983757019042969,time2: 0.0007350444793701172
```

Code
```python
import numpy as np
import cupy
import json
import time

regs_feats = cupy.random.normal(size=[200000, 512])
regs_id = cupy.random.randint(1, 110000, (200000,))

def calculate_distance(feats, regs_feats, threshold):
    t0 = time.time()
    try:
        src = cupy.asarray(feats)
        distances = cupy.zeros(shape=(src.shape[0], regs_feats.shape[0]))
        for i in range(src.shape[0]):
            distances[i] = cupy.linalg.norm(src[i] - regs_feats, axis=1)
    except:
        print('failed')
        raise
    candidate_num = 2 if regs_feats.shape[0] > 5 else regs_feats.shape[0]
    cupy.cuda.Stream.null.synchronize()
    t1 = time.time()
    work_numbers, min_distances = [], []
    for i in range(distances.shape[0]):
        min_indices = distances[i].argsort()[: candidate_num]
        numb, dis = [], []
        for j in range(candidate_num):
            numb.append(regs_id[min_indices[j].get()])
            #dis.append(distances[i][min_indices[j]])
        work_numbers.append(numb)
        #min_distances.append(dis)
    cupy.cuda.Stream.null.synchronize()
    print('time1: {},time2: {}'.format(t1 - t0, time.time() - t1))
    return work_numbers, min_distances

if __name__ == '__main__':
    feature = cupy.random.normal(size=[1, 512])
    for i in range(5):
        work_numbers, min_distances = calculate_distance(feats=feature, regs_feats=regs_feats, threshold=1)
```

**Comment by Govan111** [comment]
> Measuring times without synchronizing the device can lead to weird results as the ones you are seeing.
> 
> Inserting `cupy.cuda.Stream.null.synchronize()` in the right places yields the correct results
> Before:
> 
> ```
> time1: 0.009093761444091797,time2: 0.002468109130859375
> time1: 0.00011539459228515625,time2: 0.007904767990112305
> time1: 0.00010585784912109375,time2: 0.007896900177001953
> time1: 0.00010323524475097656,time2: 0.00789022445678711
> time1: 0.00010013580322265625,time2: 0.00789332389831543
> ```
> 
> After:
> 
> ```
> time1: 0.00883626937866211,time2: 0.0024640560150146484
> time1: 0.006998300552368164,time2: 0.0007545948028564453
> time1: 0.006988048553466797,time2: 0.0007328987121582031
> time1: 0.006985187530517578,time2: 0.0007340908050537109
> time1: 0.006983757019042969,time2: 0.0007350444793701172
> ```
> 
> Code
> 
> ```python
> import numpy as np
> import cupy
> import json
> import time
> 
> regs_feats = cupy.random.normal(size=[200000, 512])
> regs_id = cupy.random.randint(1, 110000, (200000,))
> 
> def calculate_distance(feats, regs_feats, threshold):
>     t0 = time.time()
>     try:
>         src = cupy.asarray(feats)
>         distances = cupy.zeros(shape=(src.shape[0], regs_feats.shape[0]))
>         for i in range(src.shape[0]):
>             distances[i] = cupy.linalg.norm(src[i] - regs_feats, axis=1)
>     except:
>         print('failed')
>         raise
>     candidate_num = 2 if regs_feats.shape[0] > 5 else regs_feats.shape[0]
>     cupy.cuda.Stream.null.synchronize()
>     t1 = time.time()
>     work_numbers, min_distances = [], []
>     for i in range(distances.shape[0]):
>         min_indices = distances[i].argsort()[: candidate_num]
>         numb, dis = [], []
>         for j in range(candidate_num):
>             numb.append(regs_id[min_indices[j].get()])
>             #dis.append(distances[i][min_indices[j]])
>         work_numbers.append(numb)
>         #min_distances.append(dis)
>     cupy.cuda.Stream.null.synchronize()
>     print('time1: {},time2: {}'.format(t1 - t0, time.time() - t1))
>     return work_numbers, min_distances
> 
> if __name__ == '__main__':
>     feature = cupy.random.normal(size=[1, 512])
>     for i in range(5):
>         work_numbers, min_distances = calculate_distance(feats=feature, regs_feats=regs_feats, threshold=1)
> ```

👏Thanks for helping me out！
