### ISSUE TITLE
Configurable kernel_cache directory

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#3144]
It would be nice to make the `kernel_cache` directory location configurable. This is handy in situations where the user's home directory might live on NFS (very slow for IO), when a container is used (might lack permissions for the home directory), etc. In these cases the user could set another location with an environment variable.

**Comment by leofang** [comment]
Doesn’t `CUPY_CACHE_DIR` work?
https://docs-cupy.chainer.org/en/stable/reference/environment.html

**Comment by jakirkham** [comment]
Oops 😬 Only a failure to read it seem 😞 Thanks Leo! 😄

**Comment by leofang** [comment]
No problem, John! If it doesn’t work we’ll need to fix it. We also need to set this in our HPC environments.

**Comment by jakirkham** [comment]
As you mention setting this on HPC, I'm curious what you choose for this. Do you use node local scratch or something visible to multiple nodes (like an NFS mounted directory)?

**Comment by leofang** [comment]
For us it depends on the MPI pool size. If it's not too large, then my preference is NFS to maximize reusability (and a bit easier to set up). If using many nodes, then local scratch may be necessary (NFS is super slow and one of ours is particularly unstable 😞).

But, this is just a minor concern to me, as our bottleneck is usually something else (like `@numba.cuda.jit` or HDF5 I/O). So usually we forget about this issue 😅 

Another thing I occasionally do is to clean up the `kernel_cache` directory. I hope for faster lookup speed, but I never seriously measure it. It's more like a personal hygiene habit 😛

**Comment by jakirkham** [comment]
Thanks for the info! 😄 Yeah NFS is tricky. 😞

I guess Numba has [caching too]( http://numba.pydata.org/numba-doc/latest/user/jit.html#cache ). Have you experimented with that at all? 😉

What are the slow parts of HDF5 you are running into? 🙂

Yeah that's an interesting point. I guess it is somewhat a function of the underlying filesystem.

Suppose if we got really interested in this, we could imagine using a sharded key-value database for faster retrieval. This is probably not hard to do. Just not sure of the performance benefits. 🤔

**Comment by leofang** [comment]
@jakirkham:

> I guess Numba has caching too. Have you experimented with that at all? 😉

Not for `@numba.cuda.jit`. For the CPU jit (`@numba.jit`) it's pretty sophisticated and mature now: you can do either caching or ahead-of-time (AOT) compiling (via `pycc`). None of these exists for CUDA kernels so far... 

I've wanted AOT for CUDA for a while (numba/numba#4389) but I don't think it's on the Numba team's priority list...

> What are the slow parts of HDF5 you are running into? 🙂

Many MPI processes reading the same HDF5 file. Depending on hardware and filesystem this could take a long time. I could be wrong but I remember we were bandwidth-limited for this part.

Another thing for consideration for your earlier question on local vs global scratch: I think it's also worth asking where your Python installation and shared libraries live. This directly impact the launch time of your programs, and, although I am lazy to measure, it might be more important than where CuPy's `kernel_cache` is.

**Comment by jakirkham** [comment]
Thanks for pointing out that issue! Was not aware this discussion was already happening 😄

Yeah that makes sense. Have you looked into distributed stores (like [Zarr]( https://github.com/zarr-developers/zarr-python ) 😉)?

This is a really good point. I don't think we have this particular issue, but it is good to be aware of. Are you familiar with tools for distributing environments to nodes (like [conda-pack]( https://conda.github.io/conda-pack/# ))? Can be handy if you find yourself needing your Conda environment to be locally available, but still have to figure out some way to ship it to other nodes.

**Comment by leofang** [comment]
As a follow-up of this `kernel_cache` discussion, in #3164 I made an attempt for fully in-memory cache. It seems with that we could avoid disk I/O entirely in CuPy?!

I haven't tried Zarr and conda-pack. I heard of Zarr for quite some time, and my main question is how performant it is, compared to HDF5, in an HPC environment in which multiple MPI processes can simultaneously read / write / read-and-write different parts of data? I took a look at Zarr's doc but it just says it's an open research question 😕 Any chance you can point me to a better reference, John?

As for conda-pack, I only became aware of it very recently, so haven't tried that yet.

**Comment by asi1024** [comment]
Most of CuPy routines call `cuda.compile_with_cache` at most once with the same parameters. For example, `cupy.ufunc` caches the kernels in memory [here](https://github.com/cupy/cupy/blob/master/cupy/core/_kernel.pyx#L570).
How about just avoiding disk access without supporting in-memory cache in `compile_with_cache`?

**Comment by leofang** [comment]
@asi1024 Yeah I noticed that too...Looks like most compiled kernels are memoized in one place or another, except for
1. the ufunc kernels: https://github.com/cupy/cupy/blob/7f8614930eaeadc8384cb3c257d668df6a0b3f1c/cupy/core/_kernel.pyx#L798-L800 
2. RawKernel/RawModule

Should I add another PR to address this?

Also, for #3164, if we don't add an in-memory cache, we'll assume that when `compile_with_cache` is invoked, it's always because the kernel is not memoized and needs recompiling, is that right?

**Comment by asi1024** [comment]
1. `_kernel._get_ufunc_kernel` is assumed to be called from `ufunc._get_ufunc_kernel` and cached to self._kernel_memo`. (See [here](https://github.com/cupy/cupy/blob/v8.0.0a1/cupy/core/_kernel.pyx#L1054)).
2. `RawKernel` caches the kernel to `self._kernel` in `RawKernel.kernel` property method is called. (See [here](https://github.com/cupy/cupy/blob/v8.0.0a1/cupy/core/raw.pyx#L77)).

**Comment by leofang** [comment]
Ah OK, thanks, Akifumi! Forgot the `self._kernel` thing for `RawKernel`😅 So there are ways other than `@util.memoize()` already in place to cache kernels...Should I just close #3164?

**Comment by asi1024** [comment]
Yes!

**Comment by jakirkham** [comment]
Sorry still catching up here. So in-memory caching already happens? If so, how do users enable/disable this?

**Comment by asi1024** [comment]
Yes, in-memory caching is already supported in default but the interface that disables it is not supported currently.

**Comment by leofang** [comment]
> How about just avoiding disk access without supporting in-memory cache in `compile_with_cache`?

I may revisit this task recently. I think it'd be useful and I suspect we experienced slowdown when the machine is busy at I/O. Will find a way to confirm this.

**Comment by jakirkham** [comment]
How do you typical configure the cache directory? What sort of storage medium is it backed by?

**Comment by leofang** [comment]
Frankly I don't remember to which environment I was referring back in my June comment 😅 The most frequent ones I use are the possible combinations of
- cache under the user's home directory (CuPy's default)
- cache in the scratch space (something lime `/scratch` visible to all compute nodes)

and
- local SSD
- GPFS
