### ISSUE TITLE
Cupy function doesn't utilize pinned memory inside stream

### ISSUE THREAD

**Issue by ziyaointl** [cupy/cupy#3154]
* Conditions
    CuPy Version          : 7.2.0
    CUDA Root             : /usr/common/software/cuda/10.1.243
    CUDA Build Version    : 10010
    CUDA Driver Version   : 10020
    CUDA Runtime Version  : 10010
    cuBLAS Version        : 10202
    cuFFT Version         : 10102
    cuRAND Version        : 10102
    cuSOLVER Version      : (10, 3, 0)
    cuSPARSE Version      : 10301
    NVRTC Version         : (10, 1)
    cuDNN Build Version   : 7605
    cuDNN Version         : 7605
    NCCL Build Version    : 2506
    NCCL Runtime Version  : 2506

* Code to reproduce
```python
import numpy as np
import cupy as cp
import cupy.linalg
import cupyx.scipy.special
import cupyx as cpx

stream_1 = cp.cuda.stream.Stream()
with stream_1:
    cp.random.seed(1)
    A = cp.random.rand(10000, 10000)
    u, v = cp.linalg.eigh(cpx.scipy.sparse.csr_matrix(A).todense())
```

* Error messages, stack traces, or logs
By profiling the above code, I observe that there are many small bursts of `cudaMemcpy2DAsync`s happening in `eigh`, despite never explicitly requesting cupy to transfer data back. I am putting the cupy call in a stream. How do I force cupy to use pinned memory efficiently?
![Screenshot from 2020-03-04 18-41-52](https://user-images.githubusercontent.com/18119047/75942675-ed96e680-5e47-11ea-93be-776aa8c59d2a.png)
[eigh_profile5.qdrep.zip](https://github.com/cupy/cupy/files/4290654/eigh_profile5.qdrep.zip)

**Comment by emcastillo** [comment]
I am not pretty sure here, but the issue might be cuSOLVER doing data transfers?
CuPy has a pinned memory pool used for its data transfers. But we can't guarantee what happens inside libraries.

**Comment by leofang** [comment]
Looks like those data transfers are made outside of CuPy (likely in cuSPARSE or cuSOLVER). IIUC almost all CuPy internal kernels are prefixed with `cupy_`, but I don't see any in those transfers.

**Comment by jakirkham** [comment]
Can you please retest with CUDA 10.2? IIUC there were some performance improvements in cuSOLVER.

**Comment by ziyaointl** [comment]
@jakirkham Looks like Cuda 10.2 shows a similar behaviro compared to 10.1
* Conditions
CuPy Version          : 8.0.0a1
CUDA Root             : /usr/common/software/cuda/10.2.89
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : None
NCCL Runtime Version  : None
![Screenshot from 2020-03-06 12-12-02](https://user-images.githubusercontent.com/18119047/76119217-d5d47500-5fa3-11ea-93ad-1e7a5725915d.png)
[eigh_cuda102.qdrep.zip](https://github.com/cupy/cupy/files/4300240/eigh_cuda102.qdrep.zip)

**Comment by jakirkham** [comment]
How is the overall runtime though?

**Comment by jakirkham** [comment]
Also it appears that the cuSOLVER and cuSPARSE versions are the same in both cases. Any ideas why that is happening? 🙂

**Comment by ziyaointl** [comment]
@jakirkham The CUDA 10.1 version took 10.7s, while the CUDA 10.2 version took 7.0s. However, the parts where the GPU is busy running kernels seem to stay the same.

I am using the software packages compiled by NERSC, so maybe they are using the same cuSOLVER and cuSPARSE versions for both CUDA versions? If there are newer versions of cuSOLVER and cuSPARSE, I can open a ticket asking NERSC to update those packages.

**Comment by jakirkham** [comment]
Ok good to see that performance improvement at least.

Not sure that's needed yet.

Am talking to get some more insight into what is going on here.

**Comment by jakirkham** [comment]
What sort of GPU is this running on @ziyaointl? 🙂

**Comment by ziyaointl** [comment]
@jakirkham V100 with 16GB of memory
A more detailed description about the configuration can be found here: https://docs-dev.nersc.gov/cgpu/hardware/

**Comment by jakirkham** [comment]
Could you please provide a bit of context on how the DtoH and HtoD transfers are affecting your workflow? IOW what sorts of things are you hoping to accomplish by eliminating them that you can't otherwise accomplish now?

**Comment by ziyaointl** [comment]
@jakirkham Functionality-wise `eigh` does what we want it to do - calculate eigenvalues and eigenvectors. We'll use the output only on the GPU, so it would be great if either memory transfers do not happen at all or they happen more quickly (which can possibly be achieved by pinned memory). `eigh` takes 50% of wall time in our procedure, so any performance improvements would be very welcome.

**Comment by emcastillo** [comment]
As this is related to CUDA libraries more than CuPy, we will close this issue.

**Comment by jakirkham** [comment]
Yeah that makes sense. Thanks @emcastillo. We will find another forum for this.

cc @anaruse (for awareness)

**Comment by jakirkham** [comment]
FYI this was opened as a bug internally in NVIDIA.

**Comment by lastephey** [comment]
Thank you, we appreciate it!
