### ISSUE TITLE
Supporting datetime and timedelta in CuPy

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#3170]
When working with data that has timestamps, timesteps, measures of latency, events, etc., it is useful to have types that correspond to these. In NumPy this is solved with [datetime and timedelta types]( https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html ). It would be useful to have equivalent support in CuPy.

**Comment by leofang** [comment]
You must be desperately needing this feature, John? 🤣 Dup: #2622

**Comment by jakirkham** [comment]
Thanks Leo! 😂 I searched and didn't find. Closing...

**Comment by leofang** [comment]
Hahaha I didn't either. Ended up searching your id instead...

**Comment by stormycloudy** [comment]
Running into this issue... Any updates? Thanks! 😅

**Comment by jakirkham** [comment]
This issue is a duplicate. Please follow issue ( https://github.com/cupy/cupy/issues/2622 ).
