### ISSUE TITLE
Cupy streams are not supporting concurrent GPU operation (cp.linalg.svd)

### ISSUE THREAD

**Issue by drcdr** [cupy/cupy#3174]
**_Issue_**
Cupy streams are not supporting concurrent GPU operation, for cp.linalg.svd.  (This is my first time using Cupy, to try and do concurrent SVDs on the GPU with a stack of matrices.)

Copying @mrocklin and @seibert as they seem to have spent a lot of time with similar issues.

**_Related Links_**
For background on this, see:

- #1695: How to get concurrency from cupy Streams. (Closed with a change, to support longer operations, but that doesn't seem to apply in this case.)
- [Dask 4040](https://github.com/dask/dask/issues/4040): Issues getting dask.delayed to work concurrently
- example, map_reduce : [link](https://github.com/cupy/cupy/blob/master/examples/stream/map_reduce.py)
- example, concurrency in Cupy with streams: [link](https://gist.github.com/mrocklin/d3b70cea6a555ae2387556e4f0808ac1) 
- [Related Stackoverflow question](https://stackoverflow.com/questions/55516973/apply-cupy-linalg-svd-over-a-stack-of-matrices/55528478) (suggests trying gesvdjBatched, in C++)

**_Conditions:_**
CuPy Version : 7.2.0
CUDA Root : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
CUDA Build Version : 10010
CUDA Driver Version : 10010
CUDA Runtime Version : 10010
cuBLAS Version : 10200
cuFFT Version : 10010
cuRAND Version : 10010
cuSOLVER Version : (10, 1, 0)
cuSPARSE Version : 10010
NVRTC Version : (10, 1)
cuDNN Build Version : 7605
cuDNN Version : 7605
NCCL Build Version : None
NCCL Runtime Version : None

**_Code to reproduce_**  [edit: fixed a bug and a couple of bad comments]

```
import time
import cupy as cp
import numpy as np
import dask
import dask.array as da

def many_svd_np_vs_cp():
    device = cp.cuda.Device()

    N = 16      # number of desired SVDs, grouped.
    M = 1024  # size of each matrix, for SVD (MxM)
    A = np.asarray(np.random.randn(N, M, M), dtype=np.float32)
    
    # ----- Prime Pump, to eliminate CUDA overhead in timings. ----- 
    A_gpu = cp.asarray(A)
    for i in range(16):  
        sg = cp.linalg.svd(A_gpu[0], compute_uv=False)
    time.sleep(0.25)  # to separate this, in nvvp

    # ----- Grouped SVDs in numpy ----- 
    tm = time.time()
    s_npall = np.linalg.svd(A, compute_uv=False)  # 256 x 16
    elaps = time.time() - tm
    print('%20s: elaps=%f' % ('Numpy', elaps))

    # ----- Cupy-Loop: grouped SVDs in cupy ----- 
    sg_all = cp.asarray([])
    tm = time.time()
    for i in range(A_gpu.shape[0]):
        sg = cp.linalg.svd(A_gpu[i], compute_uv=False)
        sg_all = cp.concatenate((sg_all, sg), axis=0) # N*16 = 4096, but that's OK
    s_cpall = cp.asnumpy(sg_all)
    elaps = time.time() - tm
    print('%20s: elaps=%f' % ('Cupy-Loop', elaps))
    time.sleep(0.20)

    # ----- Cupy-ListComp: is List Comprehension Faster? -----
    sg_all = cp.asarray([])
    tm = time.time()
    sg_all = [cp.linalg.svd(A_gpu[i], compute_uv=False) for i in range(A_gpu.shape[0])]
    s_cpall = cp.asnumpy(sg_all)
    elaps = time.time() - tm
    print('%20s: elaps=%f' % ('Cupy-ListComp', elaps))
    time.sleep(0.20)

    # ----- Cupy-Dask-Delayed: try using Dask.Delayed for parallelism/concurrency -----
    # TODO: not currently trying to retrieve the results, with this example.
    tm = time.time()
    tasks = [ dask.delayed(cp.linalg.svd)(A_gpu[i], compute_uv=False) for i in range(A_gpu.shape[0])]
    tasks_list = dask.delayed( list(tasks) )
    res = dask.compute(tasks_list)  # Does return a list of 256 x 16
    device.synchronize()
    elaps = time.time() - tm
    print('%20s: elaps=%f' % ('Cupy-Dask-Delayed', elaps))
    time.sleep(0.20)

    # ----- Cupy-Streams: try cupy streams for paralellism/concurrency -----
    # TODO: not currently trying to retrieve the results, with this example.
    device = cp.cuda.Device()
    map_streams = [cp.cuda.stream.Stream() for i in range(N)]
    tm = time.time()  # BUG: was start_time = time.time()
    for i, stream in enumerate(map_streams):
        with stream:
            sg = cp.linalg.svd(A_gpu[i], compute_uv=False)
            # This is a little worse:
            # C_gpu = cp.asarray(np.random.randn(M, M), dtype=np.float32) 
            # sg = cp.linalg.svd(C_gpu, compute_uv=False)
    device.synchronize()
    elaps = time.time() - tm
    print('%20s: elaps=%f' % ('Cupy-Streams', elaps))

if __name__ == "__main__":
    many_svd_np_vs_cp()


```
**_Output:_**

```
               Numpy: elaps=2.181430
           Cupy-Loop: elaps=1.396355
  Cupy-ListComp: elaps=1.467271
   Cupy-Dask-Delayed: elaps=1.206578
        Cupy-Streams: elaps=~1.6 (was 3.104342 with bug)
```
**_NVVP:_**
Running in NVVP, here are two example of what the stream launches look like, for (N,M) = (64,256) and (N,M) = (16,1024), where N are the number of SVDs/streams, and the matrices are size MxM.  Each SVD is taking 23 ms (or 116 ms in the second case), which clearly is enough time to try and launch them concurrently.  Using 'C_gpu' instead of A_gpu[i] doesn't make a difference.

![nvvp_cupy_streams](https://user-images.githubusercontent.com/18181131/76151933-042b8080-6088-11ea-807b-acc0941b8de5.png)

**Comment by leofang** [comment]
I was testing this yesterday but got distracted, so I have not completed my tests 😅

For now I have a few general remarks:
1. CuPy is providing the correct stream behavior: from nvvp you can see that there're `N` streams, and the work is done on different streams. 
2. Whether or not kernels can be  run concurrently is a completely different story: It depends on the workload, the underlying hardware, the libraries in use, etc. CuPy can't (and neither could any GPU library) guarantee any concurrency even if streams are in use.
3. For the case of the map_reduce example, increasing the workload helps, see #2588. My feeling for your case is that your workload is perhaps too small. I saw many short-running kernels launched by cuSOLVER, but I haven't figured out why there're so many tiny kernels, and why there're tiny (4B!) data transfers in-between. (@anaruse, a little help for this would be very appreciated! 🙏)
4. Any CuPy internal kernels are prefixed with either `cupy_` or `cupyx_`. If you don't see such names appearing in nvvp/Nsight, it's likely not CuPy's fault.

I'll continue my investigation later this week and update here.

**Comment by leofang** [comment]
Oh, one more thing: preferably we wanna do batched SVD for better performance, especially for your use case. But I don't know what's the current status of #2337...

**Comment by drcdr** [comment]
Thanks for looking into this, @leofang.  I'd seen #2588 later, and then had some quirk reproducing it, but now I have done it OK.  BTW, I'm using TitanXp.

I've now tried N x svd(A<sub>MM</sub>) and N x cp.matmul(A<sub>MM</sub>, A<sub>MM</sub>), for M in [8, 32, 256, 1024, 4096].  In NVVP, I'm seeing for these cases that the matmul is always in some sort of concurrency (maybe 2x or 4x) but the SVD is never in any concurrency. Agree that the cupy stream behavior seems OK, I'm thinking it must be something at the CUDA or CUDA interface layer.

I generally get better times using list comprehension than Cupy Streams. (Dask.delayed is slightly better still, but I can't tell why.)  My numbers above showed quite a bit of difference; but, there was a bug above: `start_time = time.time()` should be `tm = time.time()`.  With that change, list comprehension is still slightly faster; looking at NVVP, it seems that the cudaMemcpyAsync that each stream does for Cupy-Streams is taking much longer than it should - around 22 ms, and it is not done in parallel with the execution of the next stream.  If you want, I can document this more.

I just tried torch.svd, it's 2.5x slower.

On #2337: in my case, the 32x32 limitation of `gesvdjBatched` would be a showstopper.  The CUDA docs say `gesvdaStridedBatched` computes eigenvalues of (X.T@X) instead of singular values of (X).  This may be part of why they call it 'approximate'.   For my application, condition numbers within a matrix (and across a batch of matrices) probably aren't too bad, so the approximate approach...might be OK.  I don't see a limitation on m and n for `gesvdaStridedBatched` , which is good.  I may try that next.

**Comment by anaruse** [comment]
The reason why you don't see any kernel concurrent execution in this case is probably that kernel launch by CPU is longer than kernel execution on GPU.

In cuSolver, more specifically `cusolverDn<t>gesvd`, lots of kernels are to be launched and executed to compute the SVD. When a matrix size is not large, most kernels in `cusolverDn<t>gesvd` can finish its execution in less than 10 usec on modern GPUs, which may be shorter than the launch time by CPU..

A possible solution for now is to use the batched API in cuSolver as described above. If cusolverDn<t>getsvdaStridedBatched is fine for you, I will work on making it available in CuPy.

For reference, presentation slides on SVD solvers in cuSolver: https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9226-fast-singular-value-decomposition-on-gpus-v2.pdf

**Comment by drcdr** [comment]
OK, thanks.  But, see the image above; do you think the kernel launch by the CPU is more than 116 ms (in the 16 x 1024x1024 case)?  I was starting to think that the problem might be way too many threads being launched, based on the answer [here](https://stackoverflow.com/questions/36658324/concurrency-of-cufft-streams), as well as the large amount of stuff in the nvvp trace

```A 128x128 FFT to a first order approximation will spin up ~15,000 threads, so if my thread blocks are ~500 threads each, that would be 30 threadblocks, which will keep a GPU fairly occupied, leaving not much "room" for additional kernels```

I just benchmarked ```cusolverDnSgesvdaStridedBatched``` in C++, based on a lightly modified version of what's in the cuSOLVER documentation example, on matrices with random entries, _N(0,1)_. The accuracy seems fine for now, but the processing time was a little bit of a shock.  Here are the results, varying #in stack and matrix size (`Nr x Nc`)

```
Batch-GeSVD(#=  64, Nr= 256, Nc= 256): time =  1.223s   #gflops ~    2.147   gflops/s ~   1.755
Batch-GeSVD(#=  64, Nr=1024, Nc= 256): time =  1.085s   #gflops ~   21.475   gflops/s ~  19.797
Batch-GeSVD(#=  64, Nr=4096, Nc= 256): time =  1.221s   #gflops ~   17.180   gflops/s ~  14.067
Batch-GeSVD(#=1000, Nr= 256, Nc=  32): time =  0.144s   #gflops ~    2.359   gflops/s ~  16.332
Batch-GeSVD(#=1000, Nr=1024, Nc=  32): time =  0.172s   #gflops ~   34.603   gflops/s ~ 201.018
Batch-GeSVD(#=1000, Nr=4096, Nc=  32): time =  0.198s   #gflops ~  541.065   gflops/s ~ 2738.091
Batch-GeSVD(#=1000, Nr= 256, Nc= 256): time = 15.892s   #gflops ~   33.554   gflops/s ~   2.111
Batch-GeSVD(#=1000, Nr=1024, Nc= 256): time = 15.161s   #gflops ~  335.544   gflops/s ~  22.133
```
This is in the ballpark of what NVIDIA gets, from what you sent me, on page 12; they get ~0.08 ms for 1000 x 32, I get 0.172 ms, but they are probably on a faster GPU.

Notice that the throughput is terrible for square matrices;  64 x 256 x 256 is ~1.2 seconds, or only an effective ~2 GFLOPs/s (just based on a nominal O(2 * Nstack *(MN<sup>2</sup>+M<sup>2</sup>N))!  By comparison, a cupy stream approach for this case is only 0.28 sec.

For my application, I have both square-ish and tall-skinny matrices.  For tall-skinny, I would do the eig(X.T @ X) trick anyway, so it'd be even faster than this, I suppose.

Not sure what I'm going to do yet, but in general, I think having this stacked SVD using `cusolverDnSgesvdaStridedBatched` on the GPU as an option would be good for cupy.

**Comment by anaruse** [comment]
Thank you for benchmarking `cusolverDnSgesvdaStridedBatched` so quickly, though the result of the 64 x 256x256 case is bit disappointing...  Anyway, I will work on it later.


> OK, thanks. But, see the image above; do you think the kernel launch by the CPU is more than 116 ms (in the 16 x 1024x1024 case)?

I run your repro on Quadro GV100 and CUDA 10.2.  It took about 1.04 sec to compute the 16 x 1024x1024 case and number of kernels launched for this compute was neally 200K. Given each kernel needs 4 usec to launch, total kernel launch time becomes around 0.8 sec. It looks to me that kernel launch by CPU is performance limiter in this case..

```
        Cupy-Streams: elaps=1.042194
```

```
      API calls:   45.07%  840.33ms    196720  4.2710us  3.7370us  377.44us  cudaLaunchKernel
```

**Comment by leofang** [comment]
Thanks Akira for the insights and @drcdr for quick testing! As I mentioned earlier I also saw many tiny kernels launched in the nvvp timeline, but I didn't realize it took so much CPU time! Shouldn't this be considered as a critical deficiency, if not a bug, of the cuSOLVER library?

**Comment by drcdr** [comment]
@anaruse: OK, I see now, thanks for explaining.  I just didn't realize how much of an impact these kernel launches were!

@leofang: I agree, thanks, it seems like a very difficult limitation, especially for this use case.

Here are some more results on `cusolverDnSgesvdaStridedBatched`, and other svd approaches in MKL, and Python:

![svd_compare](https://user-images.githubusercontent.com/18181131/76469191-22fd8000-63c4-11ea-9e07-02f12b0e500a.png)

The table shows timings for several different approaches and cases, for batched SVDs: 
_C++:_
   (A) MKL using gebrd and bdsqr; 
   (B) MKL using geqrf, gebrd, and bdsqr (recommended by Intel for SVD of tall/skinny);
   (C) CUDA, using gesvdaStridedBatched (gesvda), the 'approximate algorithm'
_Python:_
  (D) numpy np.linalg.svd (I have numpy MKL installed)
  (E) cupy list comprehension [cp.linalg.svd(A_gpi[i]) ...]
  (F) cupy streams
An obvious missing approach is eig(A.T@A) for tall/skinny, but then accuracy, etc. would have to be considered.

Comments:
1. **Excel-style conditional-formatting is done row-wise, to highlight best option per row.**
2. Two different initializations are considered: Identity (e.g. np.eye(Nr,Nc)), and Random (gaussian(0,1) entries).  The former might be considered a good case for (C); the latter might be considered a poor case for (C).  At the very bottom, see the mean and stdev of (time-Identity / time-Random).
3. I've implemented a few C++ unit tests.  First, for [Hilbert matrices](https://en.wikipedia.org/wiki/Hilbert_matrix), the relative error on the largest eigenvalue is ~1e-7; the smallest, ~1e-3.  Second, singular values of Identity match are 1 for MKL and CUDA. Third, eigenvalues match for random matrices, across the C++ approaches. 
4. No multiple runs with confidence intervals here!  Eyeballing it, it looks like +/- 1 to 10% variation across runs.

Some Timing Takeaways (CPU=4790K, GPU=TitanXP):
* Identity, Column (C): CUgesvda shines when it doesn't have to do too many iterations.
* Random, Column (C): CUgesvda shines only when Nr/Nc is huge.
* Random, Column (C) vs (E,F): CUgesvda is sometimes better, sometimes worse than current cupy.
* Column (B) vs (D): maybe numpy should consider a tall/skinny routine?  IDK, I'm sure there are other considerations here (stability, accuracy, etc.)
* Column (E) vs (F): since no parallelism for cupy SVD, list comprehensions is better than streams.
* Mean,Std(Iden./Rand.): python has lower variance, mean closer to 1.

There's a lot to digest here.  I know what I have to do for my application now, but let me know if you have any other questions. As far as the initial issue is concerned - maybe `cusolverDnSgesvdaStridedBatched` could be considered in cupy for tall/skinny cases.
