### ISSUE TITLE
Allow C++ Templating Functionality

### ISSUE THREAD

**Issue by mnicely** [cupy/cupy#3185]
Would it be possible to allow C++ Templating functionality to raw kernels?

Rationale:
Instead of having multiple functions based on input type, there would be one templated global function.

**Comment by leofang** [comment]
Unfortunately this is not possible despite how easy it seems. The reason is C++ name mangling. When specializing a template function, its name gets mangled (note that the template specialization can't be done with the `extern "C"` linkage to avoid name mangling), so you can't retrieve the function via `cuModuleGetFunction` (the actual CUDA API used in `RawKernel` and `RawModule`). The name just gets distorted by the compiler.

This is something that's bothering indeed. For example, we might want to cache the compiled template code in disk (ref: numba/numba#4389) for future reuse, but given this challenge we have no way to retrieve the kernels (but compiling is OK!)

**Comment by leofang** [comment]
Example:
```python
import cupy as cp


template = '''
template <typename T>
__global__ void do_something(T* input, int N) {
    unsigned int tid = blockDim.x * blockIdx.x + threadIdx.x;
    if (tid < N) {
        input[tid] += 1;
    }
}

// specialization for float
template<>
__global__ void do_something(float* input, int N);
'''

mod = cp.RawModule(code=template, options=('--std=c++11',))  # <-- compiling is OK!
func = mod.get_function('do_something')                      # <-- error
```
Error:
```python
Traceback (most recent call last):
  File "template.py", line 19, in <module>
    func = mod.get_function('do_something')
  File "cupy/core/raw.pyx", line 302, in cupy.core.raw.RawModule.get_function
  File "cupy/cuda/function.pyx", line 213, in cupy.cuda.function.Module.get_function
  File "cupy/cuda/function.pyx", line 216, in cupy.cuda.function.Module.get_function
  File "cupy/cuda/function.pyx", line 162, in cupy.cuda.function.Function.__init__
  File "cupy/cuda/driver.pyx", line 262, in cupy.cuda.driver.moduleGetFunction
  File "cupy/cuda/driver.pyx", line 124, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_NOT_FOUND: named symbol not found
```

**Comment by mnicely** [comment]
Okay, I expected as much. I sounds like if want multiple types, I'll need multiple kernels...

**Comment by mnicely** [comment]
What is rationale for `extern C` ? Would an improvement to `cuModuleGetFunction` alleviate the issue?

**Comment by leofang** [comment]
`extern "C"`: https://stackoverflow.com/questions/1041866/what-is-the-effect-of-extern-c-in-c

`cuModuleGetFunction` is a CUDA driver API. There's nothing we can do to it. 

If you want to make your life *much* harder, you can always write a dispatcher that can live with the C linkage, but internally calls any C++ specializations you want. This is more or less how CuPy interfaces with some C++ template code internally, see:
https://github.com/cupy/cupy/blob/master/cupy/cuda/thrust.pyx (interface with https://github.com/cupy/cupy/blob/master/cupy/cuda/cupy_thrust.cu)
https://github.com/cupy/cupy/blob/master/cupy/cuda/cub.pyx (interface with https://github.com/cupy/cupy/blob/master/cupy/cuda/cupy_cub.cu)
But you might as well write a string template in Python, do a string replacement with the types you want, and recompile using RawKernel/RawModule. This is much easier.

**Comment by mnicely** [comment]
@leofang When are say _string template_, are you referring to the following?
https://www.geeksforgeeks.org/template-class-in-python/

I could have something like
```
# A Python program to demonstrate working of string template 
from string import Template 
  
# List Student stores the name and marks of three students 
type = ['float', 'double', 'complex<float>', 'complex<double>'] 
  
# We are creating a basic structure to print the name and 
# marks of the students. 
t = Template(<some cuda kernel>) 
  
for i in type: 
     print (t.substitute(data_type = i))
```

Then call _t_ from inside the _extern "C"_, inside the _loaded_from_source_?

**Comment by leofang** [comment]
That's right. In CuPy both ufuncs and reduction kernels are done like this. For example, this is ufunc: https://github.com/cupy/cupy/blob/f00bf53ec16c67ce26b06c0afcd76da9df038349/cupy/core/_kernel.pyx#L38-L62
It's a bit more complicated because of the machinery needed for generalizations, but depending on your use cases it could be much simpler.

**Comment by mnicely** [comment]
Thanks!

**Comment by leofang** [comment]
Sorry @mnicely for getting back late. I was digesting email backup and wondering why you reopened. For some reason GH didn't send me your message...

I took a quick look and I think it's hard. @emcastillo can correct me. Calls to  `nvrtcAddNameExpression` and `nvrtcGetLoweredName` must be done before an NVRTC program is destroyed. This means we need to intrude CuPy's compiler workflow and get these nasty tasks done and return the mangled names to us *before* the program is closed and the cubin is loaded. In other words, everything needs to be done before `compile_with_cache` ends. Not impossible but requires some thoughts for getting back the mangled names to a proper place.

The biggest challenge is to use `nvrtcGetTypeName` if you have custom types. For built-in types (those NumPy and CuPy recognize), this call can be bypassed as we already know their C names, but supporting arbitrary types/structs/classes means they need to be recognized at the Cython level, which is not possible at the build time. 

I feel the simplest way out, in addition to a string template we discussed earlier, is to add thin wrappers within `extern "C"` around a C++ template kernel:
```python
import cupy as cp

cuda_code = '''
template<typename T>
__global__ void f(T* input) {
  unsigned int x = blockIdx.x * blockDim.x + threadIdx.x;
  input[x] += 1;
}

// this part can be easily auto-generated in Python and attach to the code string
extern "C" __global__ void f_int(int* x) { f<int>(x); }
extern "C" __global__ void f_float(float* x) { f<float>(x); }
... // specialize for whatever types you need
'''

mod = cp.RawModule(code= cuda_code, options=('--std=c++11',))
f_int = mod.get_function('f_int')
f_float = mod.get_function('f_float')

in_int = cp.zeros(10, dtype=cp.int32)
in_float = cp.zeros(10, dtype=cp.float32)

f_int((1,), (10,), (in_int,))
f_float((1,), (10,), (in_float,))

assert (in_int == 1).all()
assert (in_float == 1.0).all()
```

**Comment by mnicely** [comment]
Hi @leofang. No worries on the delay. I'm just trying to get a better understanding of functionality of CuPy raw kernels and NVRTC. Thank you for clarifying. Templating types would be nice, but also, I'm trying to figure out how to access libraries like CUB and cuFFTDx, which are templated based, through a raw kernel. Also, it should allow me to pass templated `int`s that I can then use to unroll loops. 

I'm going to review your snippet next week. I have coded up your string template suggestion and it works great!! :1st_place_medal: 

All this might not even be necessary if we start precompile the kernels into cubins. I need to look into that as well.

**Comment by leofang** [comment]
> Templating types would be nice, but also, I'm trying to figure out how to access libraries like CUB and cuFFTDx, which are templated based, through a raw kernel. 

For CUB: I think NVRTC hates it, and you'll need jitify to bypass tons of compilation errors. I have a working PR that uses CUB to back *all* reduction kernels in CuPy (#3244; it is based on string template btw). I had to use NVCC to work around this issue. I would like to try jitify next after it's merged, but I need some time to polish it first...

For cuFFTDx: Have you made any benchmark for it (against cuFFT)? I'm very interested! I haven't had time to look into it, and it'd be nice if you could point me to any work either you've done or still ongoing! 🙂
 
> Also, it should allow me to pass templated `int`s that I can then use to unroll loops.

Right, indeed this is important.

> I'm going to review your snippet next week. I have coded up your string template suggestion and it works great!! 🥇
> 

Glad to know! :tada:

> All this might not even be necessary if we start precompile the kernels into cubins. I need to look into that as well.

Yeah...There's a trade-off to be made. Precompiling makes runtime a bit faster (even with CuPy's cache, it still takes some time to go through the compiler stage and retrieve the image in every first run, whereas you know exactly which cubin to be loaded at start time), but if your users wanna build from source, they'd need a working CUDA environment.

**Comment by mnicely** [comment]
Thanks for all the information!! 

Here is some examples comparing cuFFT and cuFFTDx (0.1.0). It's been a few months since I've looked at it. Let me know if you find issues. https://github.com/mnicely/cufft_examples

**Comment by leofang** [comment]
> Calls to `nvrtcAddNameExpression` and `nvrtcGetLoweredName` must be done before an NVRTC program is destroyed. This means we need to intrude CuPy's compiler workflow and get these nasty tasks done and return the mangled names to us _before_ the program is closed and the cubin is loaded. In other words, everything needs to be done before `compile_with_cache` ends. Not impossible but requires some thoughts for getting back the mangled names to a proper place.

This is done in #3319. 

> The biggest challenge is to use `nvrtcGetTypeName` if you have custom types.

I still have no idea how to support this...

**Comment by mnicely** [comment]
@leofang Wanted to put this here for reference. I figured out a workaround if you have to have templates but still want nvcc compiler

```python
import cupy as cp

# CuPy raw kernel
cuda_code = r"""

template <typename T>
__device__ void transfer(T * in, T * out) {
    int thread_id = blockIdx.x * blockDim.x + threadIdx.x;

    out[thread_id] = in[thread_id] * thread_id;
    printf("d: %d\n", thread_id);

}

extern "C" __global__ void transfer_int(int * in, int * out) {
    transfer<int>(in, out);
}

extern "C" __global__ void transfer_float(float * in, float * out) {
    transfer<float>(in, out);
}

"""

module = cp.RawModule(
    code=cuda_code,
    backend="nvcc",
    options=(
        "-std=c++11",
        "-use_fast_math",
        "-lineinfo",
        "-Xptxas",
        "-v -warn-spills -warn-lmem-usage -warn-double-usage",
    ),
)

ker_int = module.get_function("transfer_int")
ker_float = module.get_function("transfer_float")

N = 4

arr_in = cp.ones(N * N, dtype=cp.int32)
arr_out = cp.zeros(N * N, dtype=cp.int32)

ker_int((N,), (N,), (arr_in, arr_out))
print(cp.asnumpy(arr_out))
print()

arr_in = cp.ones(N * N, dtype=cp.float32)
arr_out = cp.zeros(N * N,  dtype=cp.float32)

ker_float((N,), (N,), (arr_in, arr_out))
print(cp.asnumpy(arr_out))
```

**Comment by leofang** [comment]
Sorry, what's the difference between your code snippet and my https://github.com/cupy/cupy/issues/3185#issuecomment-622539640?

**Comment by mnicely** [comment]
:man_facepalming: Multitasking at its worst... Total forgot about that!!

But there is one subtle difference though. With `nvcc`, if you use `__global__` with transfer function you get the following error. If you think this is a bug, let me know and I'll submit and issue.

```bash
Traceback (most recent call last):
  File "constant_test.py", line 25, in <module>
    module = cp.RawModule(
  File "cupy/core/raw.pyx", line 304, in cupy.core.raw.RawModule.__init__
  File "cupy/core/raw.pyx", line 312, in cupy.core.raw.RawModule.module.__get__
  File "cupy/util.pyx", line 74, in cupy.util.memoize.decorator.ret
  File "cupy/core/raw.pyx", line 429, in cupy.core.raw._get_raw_module
  File "cupy/core/core.pyx", line 1812, in cupy.core.core.compile_with_cache
  File "cupy/core/core.pyx", line 1863, in cupy.core.core.compile_with_cache
  File "/home/belt/workStuff/cupy/cupy/cuda/compiler.py", line 312, in compile_with_cache
    return _compile_with_cache_cuda(
  File "/home/belt/workStuff/cupy/cupy/cuda/compiler.py", line 385, in _compile_with_cache_cuda
    cubin = compile_using_nvcc(source, options, verbose, arch, name + '.cu',
  File "/home/belt/workStuff/cupy/cupy/cuda/compiler.py", line 199, in compile_using_nvcc
    _run_nvcc(cmd, root_dir, verbose)
  File "/home/belt/workStuff/cupy/cupy/cuda/compiler.py", line 42, in _run_nvcc
    e.output.decode(encoding='UTF-8',
AttributeError: 'str' object has no attribute 'decode'
```

`__device__` and `__global__` both work with `nvrtc`

**Comment by leofang** [comment]
Hi @mnicely I think there're two issues in the error you observed. First is that the template function in my https://github.com/cupy/cupy/issues/3185#issuecomment-622539640 example should be declared `__device__` instead of `__global__` (I actually meant that, so it's probably a typo...😅). Second, I think there're some local changes in your CuPy build that led to the `AttributeError`; I didn't see any error after fixing `__device__`.
