### ISSUE TITLE
Expected behavior when pass float64 to a CuPy raw kernel with float * input.

### ISSUE THREAD

**Issue by mnicely** [cupy/cupy#3186]
CuPy Version          : 7.2.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2406
NCCL Runtime Version  : 2507

What is the expected behaviour when passing a cp.array(x, dtype=cp.float64) to a float * variable in a CuPy raw kernel? Also, for the opposite cp.array(x, dtype=cp.float32) to a double *.

I expected promotion and demotion like I would see in C++, but that's not the case. I'm getting all zeros.

The only combinations that work are 
cp.array(x, dtype=cp.float32) to a float *
cp.array(x, dtype=cp.float64) to a double *

**Comment by leofang** [comment]
numpy.float32 / cupy.float32 -> float in C/C++
numpy.float64 / cupy.float64 -> double in C/C++

**Comment by mnicely** [comment]
To clarify, are you saying that we should see automatic argument promotion and demotion?

**Comment by leofang** [comment]
There's no type promotion or demotion whatsoever. When using RawKernel or RawModule there's a one-to-one type mapping between NumPy/CuPy dtypes and C/C++ intrinsic types.

**Comment by mnicely** [comment]
Got it!
