### ISSUE TITLE
add documentation for building a development env on google colab

### ISSUE THREAD

**Issue by rushabh-v** [cupy/cupy#3188]
In my opinion, some people might not be able to contribute to CuPy because of not having an NVIDIA GPU. But they might not know that we can build a development env on google colab(As I did [here](https://github.com/cupy/cupy/pull/3130#issuecomment-592973250)).
```python
import os
from google.colab import drive
drive.mount('/content/drive')
os.chdir("/content/drive/My Drive/")

!git clone https://github.com/user-name/cupy
os.chdir("cupy/")
!pip install -e . --no-cache-dir -vvvv
```
And then we can test the code and do benchmarks there.
And as I did above, by cloning it directly on google drive we don't need to clone the repo each time we open the notebook. We just need to build and pull the changes there.

And I think adding the documentation for the same would be very useful for newcomers.

**Comment by rushabh-v** [comment]
Is this a good idea? I mean I am not sure. 
But if it is, I would love to add that piece of documentation!

any thoughts? @kmaehashi @asi1024

**Comment by kmaehashi** [comment]
Sorry for not responding here. We revisited this issue today and concluded that documenting the development on Colab environment is too specific for the official docs. I think your own blog or medium would be the best place to share such tips and experience.
