### ISSUE TITLE
Excessive overhead for CuPy raw kernel launch.

### ISSUE THREAD

**Issue by mnicely** [cupy/cupy#3193]
CuPy Version          : 7.2.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2406
NCCL Runtime Version  : 2507

![numba_vs_cupy](https://user-images.githubusercontent.com/50021634/76656967-2705db00-6547-11ea-93ec-348f3b1952be.png)

I have kernels, one Numba and one CuPy raw kernel. They are nearly identical and the CuPy raw kernel is 2x faster. But the overhead of launching _cuModuleLoadData_ and _cuModuleUnload_ make the overall execution of the CuPy function 2x **slower** than Numba. I've attached a screenshot from Nsight Systems. 

Also, code can be found https://github.com/rapidsai/cusignal/pull/31

**Comment by leofang** [comment]
@mnicely I don't think this is not a fair comparison. You need to run the kernel multiple times and focus on the average runtime. This is also what really matters in a typical workflow. If you're not going to reuse the kernel, you should really just merge it to somewhere else to reduce kernel launch overhead.

Numba has its own compiling toolchain that seems to avoid these driver API calls (no idea how's that done, @gmarkall probably knows it well 🙂), whereas CuPy uses NVRTC (default) or NVCC to do the compilation and load the resulting cubin using the driver API.

**Comment by leofang** [comment]
Oh, by the way:
> I have kernels, one Numba and one CuPy raw kernel. They are nearly identical and the CuPy raw kernel is 2x faster. 

Yes, this is more or less I expected (perhaps a bit better?), see numba/numba#4647. We saw a 2x-3x difference in that particular test.

**Comment by emcastillo** [comment]
As @leofang said above CuPy kernel execution times are amortized.

**Comment by mnicely** [comment]
@leofang @emcastillo 

I've attached qdrep files and screenshots (in tar), which I hope shows what I'm seeing and why I'm confused. First, I agree with everything that's been said and have verified it in code. I'm seeing the entire workflow (python function) of launching a cupy raw kernel take twice as long to run then a Numba kernel if they are **not** cached in a dictionary.

The screenshot (numba_vs_cupy_2) show Numba (left) ran 10 times and cupy (right) ran 10 times **without** a dictionary to cache the modules. 

The screenshot (numba_vs_cupy_3) show Numba (left) ran 10 times and cupy (right) ran 10 times **with** a dictionary to cache the modules. 

[cusignal.tar.gz](https://github.com/cupy/cupy/files/4340221/cusignal.tar.gz)

![numba_vs_cupy_2](https://user-images.githubusercontent.com/50021634/76796078-08028580-67a1-11ea-89f4-ecc6a3cd3888.png)

![numba_vs_cupy_3](https://user-images.githubusercontent.com/50021634/76796803-97f4ff00-67a2-11ea-86db-2e779d758827.png)

**Comment by leofang** [comment]
Could you point us to some gist or code snippet? This could happen depending on how you call `RawKernel`. Most likely 
1. you changed the CUDA code and recompiled, or
2. you repeatedly created a `RawKernel` (with the same CUDA code) in a loop.

For 2, you could compile the kernel outside the loop and reuse it (**without** your dictionary). 

In the meanwhile, I can try revisiting my #3164 and see if the entire CUDA module could be cached or not. (The original goal there was to enable in-memory cache by setting an env var `CUPY_CACHE_IN_MEMORY=1` to avoid disk I/O, but with some tweaks I think we could take one step further and cache the loaded module rather than unloaded cubin in binary).

**Comment by mnicely** [comment]
Hi @leofang, I used the code at https://github.com/rapidsai/cusignal/pull/31.

Just comment out the following to see what I'm talking about.
```
    if '_cupy_upfirdn_1d_double' in _cached_modules:
        return
```

**Comment by leofang** [comment]
Could you point us to your timing script? I wanna see how your code is launched. Thanks.

**Comment by mnicely** [comment]
I'm just running this simple test script
[test.py.txt](https://github.com/cupy/cupy/files/4340370/test.py.txt)

with Systems
```
./nsys profile --sample=none --trace=cuda,nvtx python3 test.py
```

**Comment by leofang** [comment]
Thanks @mnicely, and sorry for being stupid.😅 I now see that the call path is `upfirdn` -> `apply_filter` -> `_cupy_init` -> `_init_cupy_upfirdn_1d_modules`, and you create a `RawModule` in there. 

The problem is --- IIUC --- if you don't cache the created `RawModule` at the module level (in your case `cusignal._upfirdn`), you're recompiling the code every time you call `upfirdn()`. This is exactly the No.2 situation I mentioned. 

Try making your `RawModule` instance a module-level object, and you should be able to remove your own dict.

Have to go, will check back tonight. Let me know how it goes!

**Comment by leofang** [comment]
@mnicely How did it go?

**Comment by mnicely** [comment]
I'm actually looking at it now. I don't use Python on a daily basis... Googling what a module-level object is and how to implement one.

**Comment by mnicely** [comment]
IIUC, you're saying to run `_init_cupy_upfirdn_1d_modules` (without dict), in `_UpFIRDn.__init__()`?

**Comment by mnicely** [comment]
Okay, I'm compiling the kernel during `_UpFIRDn.__init__()` and passing the module around. I'm getting the following output and slower overall performance. It seems `cuModuleLoadData` and `cuModuleUnLoad` are being call every call.

![cupy_with_module_object](https://user-images.githubusercontent.com/50021634/76864831-22d40900-6838-11ea-9f06-4c1c846c35f0.png)

**Comment by leofang** [comment]
No, I meant you should init your RawModule directly in `python/cusignal/_upfirdn.py` (not in any class or function), and then find a way to pass it into any class or function that needs it. Placing it in `_UpFIRDn.__init__()` would not help.

**Comment by leofang** [comment]
Remove `_init_cupy_upfirdn_1d_modules` and flatten this function by one indentation level, the resulting `module=cp.RawModule` would live in the Python module level (lifetime tied to Python module).

**Comment by mnicely** [comment]
[_upfirdn.py.txt](https://github.com/cupy/cupy/files/4343890/_upfirdn.py.txt)

Okay, I think I've done that, but I'm getting the following error.
```
Traceback (most recent call last):
  File "test.py", line 244, in <module>
    cc = cusignal.upfirdn(c_h, c_x, 2, use_numba=False)
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cupy/prof/time_range.py", line 109, in inner
    return func(*args, **kwargs)
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cusignal-0.13.0a0+63.g1be0217.dirty-py3.8.egg/cusignal/_upfirdn.py", line 602, in upfirdn
    return ufd.apply_filter(x, axis, cp_stream=cp_stream, use_numba=use_numba)
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cupy/prof/time_range.py", line 109, in inner
    return func(*args, **kwargs)
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cusignal-0.13.0a0+63.g1be0217.dirty-py3.8.egg/cusignal/_upfirdn.py", line 507, in apply_filter
    _cupy_init(
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cupy/prof/time_range.py", line 109, in inner
    return func(*args, **kwargs)
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cusignal-0.13.0a0+63.g1be0217.dirty-py3.8.egg/cusignal/_upfirdn.py", line 395, in _cupy_init
    kernel(
  File "cupy/core/raw.pyx", line 66, in cupy.core.raw.RawKernel.__call__
  File "cupy/cuda/function.pyx", line 162, in cupy.cuda.function.Function.__call__
  File "cupy/cuda/function.pyx", line 144, in cupy.cuda.function._launch
  File "cupy/cuda/driver.pyx", line 293, in cupy.cuda.driver.launchKernel
  File "cupy/cuda/driver.pyx", line 118, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_HANDLE: invalid resource handle

```

**Comment by leofang** [comment]
I am trying to set up an env for cusignal. This is weird. In the meanwhile, could you also try calling `module.get_function(...)` at the module level?

**Comment by mnicely** [comment]
No luck. Same issue...

**Comment by leofang** [comment]
Does your test script require a particular version of Numba? I got this
```bash
$ python test.py 

Doubles
[ 0.          0.         -0.00088594 ...  0.00055354  0.00027253
  0.        ]



Traceback (most recent call last):
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/typing/context.py", line 344, in resolve_argument_type
    return typeof(val, Purpose.argument)
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/typing/typeof.py", line 34, in typeof
    raise ValueError(msg)
ValueError: cannot determine Numba type of <class 'cupy.core.core.ndarray'>
```

**Comment by mnicely** [comment]
```
(cusignal) belt@orion:~/workStuff/cusignal/cusignal/python/cusignal$ python3
Python 3.8.2 | packaged by conda-forge | (default, Mar  5 2020, 17:11:00) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
>>> numba.__version__
'0.48.0'
>>> 
```

Interesting. It's installed using the standard instructions.

**Comment by leofang** [comment]
Updated to Numba 0.48.0 and got a different error:
```bash
$ python test.py 

Doubles
[ 0.          0.         -0.00088594 ...  0.00055354  0.00027253
  0.        ]



Traceback (most recent call last):
  File "test.py", line 237, in <module>
    c_ufd = cusignal.upfirdn(c_h, c_x, 2, use_numba=True)
AttributeError: module 'cusignal' has no attribute 'upfirdn'
```

**Comment by mnicely** [comment]
Did you run 
`git clone https://github.com/rapidsai/cusignal.git`?

**Comment by leofang** [comment]
yeah never mind...Made a stupid mistake. I can reproduce it now.

**Comment by mnicely** [comment]
Or can you just pull down
`https://github.com/mnicely/cusignal/tree/mnicely-dev`?
Sorry for any frustration.

**Comment by leofang** [comment]
No worries, I am still scratching my head trying to figure out what's wrong. Seems like the underlying image is freed too early when the kernel is called, but don't understand how it can happen.

**Comment by leofang** [comment]
The CUDA context is changed when `_cupy_init` is called --- why?!

**Comment by mnicely** [comment]
Got it! As soon as you said, _The CUDA context is changed_

Are you using my test.py? At line 225, I'm running `cp.cuda.runtime.setDevice(1)`, so I can target my GPU not running my displays.

By running `loaded_from_source` and `cp.RawModule`, they are getting created in a CUDA context on device 0

**Comment by leofang** [comment]
I think setting device before import cusignal would fix the problem --- can you confirm @mnicely?

**Comment by mnicely** [comment]
I can confirm that works. Can you explain what is happening with `cusignal` is imported?

**Comment by leofang** [comment]
For real?! I am lost...Let me grab a cup of coffee and rethink over it.....

**Comment by mnicely** [comment]
Okay! I'm glad I'm not the only one!

**Comment by leofang** [comment]
Yeah, sorry for not realizing this sooner @mnicely. 

When CuPy or Numba is imported, none of them establishes the CUDA context. But, any runtime API calls such as `setDevice()` would do it for the current or chosen device. In addition to that, in CuPy a context can also be created when 1. compiling with NVRTC (default) or 2. launching a kernel, and with my suggested change the line `import cusignal` would trigger compiling. 

Therefore, if we do the actions in this order:
1. `import cusignal` (which invokes `RawModule`)
2.`setDevice(1)`
3. `upfirdn()`
Then the code is compiled and loaded in device 0's context, but `upfirdn()` expects the kernel to live on device 1, so we're screwed. 

@emcastillo Looks like we need to apply `util.memoize(for_each_device=True)` somewhere in `RawKernel`/`RawModule` and trigger recompiling for different devices if necessary...

**Comment by mnicely** [comment]
That makes complete sense. I like the performance of making Raw Module a module object, especially for the first kernel launch.
I think we want the flexibility to target multiple GPUs easily.
So I'll stick to a cached dictionary for the time being.

**Comment by leofang** [comment]
Yeah sounds good for the time being (until we fix this). But you'll need to incorporate device ID as part of your cache key, otherwise it'd fail again when switching to another device. Should be easily verifiable.

**Comment by mnicely** [comment]
> incorporate device ID as part of your cache key

Good idea!

**Comment by leofang** [comment]
#3200 should hopefully fix this.
