### ISSUE TITLE
Add arm64 binary for Jetson Nano

### ISSUE THREAD

**Issue by jalfonsi** [cupy/cupy#3196]
Please, provide optimized binaries for pip installing CuPy on Nvidia Jetson Nano arm64 architecture under latest CUDA 10.x . Compiling from source with pip takes a lot of time.

**Comment by emcastillo** [comment]
@leofang @jakirkham should be possible to do this in conda?

**Comment by leofang** [comment]
AFAIK My understanding is that currently Anaconda only supports nvcc for Linux + x86-64, so we can't yet build an arm64 package. (It's the same issue for ppc64 btw.)

@jakirkham How difficult is it to support arm64 in nvcc-feedstock?

**Comment by emcastillo** [comment]
i think i’ve seen aarch64 pacakges for numpy in conda. But can’t look at it right now 😥

**Comment by leofang** [comment]
ping @jakirkham

**Comment by jakirkham** [comment]
Ah sorry for missing this. 😞

There are `aarch64` packages for things like `numpy`. However we don't currently have [`cudatoolkit` packages]( https://anaconda.org/anaconda/cudatoolkit/files ) for `aarch64`, which we would need for CUDA enabled packages on that platform. Have raised issue ( https://github.com/AnacondaRecipes/cudatoolkit-feedstock/issues/3 ) about `aarch64` packages for `cudatoolkit`.

**Comment by leofang** [comment]
Thanks, @jakirkham! Do we also need a `aarch64` package for nvcc-feedstock?

**Comment by jakirkham** [comment]
Sorry for the slow reply. We would, but it would be straightforward once we have the other pieces in place.

**Comment by kmaehashi** [comment]
FYI: NGC's L4T ML Docker container provides CuPy v8 by default 😃 
https://ngc.nvidia.com/catalog/containers/nvidia:l4t-ml

**Comment by jakirkham** [comment]
@kmaehashi do you have a build script that you could share for the wheel builds?

**Comment by kmaehashi** [comment]
@jakirkham CuPy wheels are built with this tool: https://github.com/cupy/cupy-release-tools/

For Jetson, first build a Docker image:

```
$ cd REPO_ROOT/builder/base/cuda-10.2-jetson/
$ ./build.sh
```

Then you can build wheels using the Docker image:

```
$ cd REPO_ROOT
$ ./build.sh 10.2-jetson 3.7
$ ./build.sh 10.2-jetson 3.8
$ ./build.sh 10.2-jetson 3.9
$ ./build.sh 10.2-jetson 3.10
```

**Comment by kmaehashi** [comment]
Closing as Arm binaries are now officially provided in v10.0.0rc1 release.
