### ISSUE TITLE
I tried to install using pip but it failed. So I used conda and it worked. There seems to be something wrong with the pip installation.

### ISSUE THREAD

**Issue by spnova12** [cupy/cupy#3199]
- CuPy version : https://docs-cupy.chainer.org/en/stable/
  - OS/Platform : ubuntu 16.04
  - CUDA version : 10.2

**Comment by emcastillo** [comment]
How did you tried to install it with pip?
`pip install cupy-cuda102` should work for your case.

Also which python version are you using?
ubuntu 16.04 default python is 2.7 which is not supported anymore.
You can try to install python 3.6, 3.7 or 3.8 using conda or pyenv.

**Comment by spnova12** [comment]
Thanks for the answer!

I used that commend.
pip install cupy-cuda102
However, the following error occurred.

My python version is Python 3.6.10
And i am using virtualenv

*>>> import cupy*
Traceback (most recent call last):
  File
"/home/lab/python_envs/nt_env/lib/python3.6/site-packages/cupy/__init__.py",
line 21, in <module>
    from cupy import core  # NOQA
  File
"/home/lab/python_envs/nt_env/lib/python3.6/site-packages/cupy/core/__init__.py",
line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: libcudart.so.10.2: cannot open shared object file: No such
file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/home/lab/python_envs/nt_env/lib/python3.6/site-packages/cupy/__init__.py",
line 42, in <module>
    six.reraise(ImportError, ImportError(msg), exc_info[2])
  File "/usr/lib/python3/dist-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File
"/home/lab/python_envs/nt_env/lib/python3.6/site-packages/cupy/__init__.py",
line 21, in <module>
    from cupy import core  # NOQA
  File
"/home/lab/python_envs/nt_env/lib/python3.6/site-packages/cupy/core/__init__.py",
line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the
version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment,
uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs-cupy.chainer.org/en/latest/install.html

original error: libcudart.so.10.2: cannot open shared object file: No such
file or directory


2020년 3월 18일 (수) 오전 10:21, emcastillo <notifications@github.com>님이 작성:

**Comment by emcastillo** [comment]
```ImportError: libcudart.so.10.2: cannot open shared object file: No such
file or directory```

Do you have CUDA on your `LD_LIBRARY_PATH`?
Alternative you cant set `CUDA_PATH` pointing to the root installation of the CUDA toolkit.
