### ISSUE TITLE
Convert CUDA Vectors or Device ptr to cupy arrays?

### ISSUE THREAD

**Issue by chaithyagr** [cupy/cupy#3202]
Right now, if we have any source code base in CUDA, in order to expose the array to cupy, we bind it with pybind11 and later pass the array to cp.array.

However, this has a major drawback of moving data to and fro CPU.
Is it possible to read cupy array from GPU data pointers?
We could have a `cupy.h` that can be included that supports this, similar to `numpy.h` provided by pybind11

**Comment by leofang** [comment]
It's already possible within CuPy. See, for example, how to wrap your own pointer using CuPy's `UnownedMemory` and pass it to construct a CuPy array with zero copy:
https://github.com/cupy/cupy/blob/dac89258cfba08398cb4ce1c902420c46324e442/cupy/core/raw.pyx#L327-L346
You just need to change the line `ptr = ...` to the pointer (as int) of your array.

If your codebase already exposes CUDA arrays to the Python space, please consider supporting `__cuda_arrary_interface__`. A number of projects, including CuPy and PyTorch, already participate. See: http://numba.pydata.org/numba-doc/dev/cuda/cuda_array_interface.html

**Comment by chaithyagr** [comment]
> If your codebase already exposes CUDA arrays to the Python space, please consider supporting

I dont think it does, I was planning to work on this, mostly this is a good starting point

**Comment by jakirkham** [comment]
Just curious, what code are you hoping to use `__cuda_arrary_interface__` in? 🙂

**Comment by chaithyagr** [comment]
Well, we are trying to get this up for https://github.com/andyschwarzl/gpuNUFFT/issues/76

**Comment by jakirkham** [comment]
Thanks for the link!

Well one option is to construct your own class that implements the `__cuda_arrary_interface__` property and keeps the memory alive. Then just pass that to `cupy.asarray(...)` to get a CuPy `ndarray` that users can work with.

Alternatively you could create an empty CuPy `ndarray` and grab the underlying memory to use to write output data from your C problem. This would benefit from the fact that CuPy owns the memory and will perform memory management for you.

Not sure which is easier as I don't really know your code, but hopefully that gives you some options 🙂

**Comment by chaithyagr** [comment]
Ahhh thank you! I'll follow these steps.
Closing this issue

**Comment by mfoglio** [comment]
Hello, so is there a way to easily create a cupy array given a gpu pointer and the array size?

**Comment by chaithyagr** [comment]
Actually, I am also trying to tackle this. @jakirkham  I would like to go by this option:

> Alternatively you could create an empty CuPy ndarray and grab the underlying memory to use to write output data from your C program. This would benefit from the fact that CuPy owns the memory and will perform memory management for you.

Can you please point to minor simple examples? 

@mfoglio, I think based on responses I got, you have to implement the `__cuda_array_interface__`. I think a version of it is done in cuML if I am right. 

Reopening this here to complete this discussion with minor examples, which possibly can be added to the documentation (if it doesn't exist)

**Comment by leofang** [comment]
@mfoglio 
```python
mem = cp.cuda.UnownedMemory(ptr, size, owning_obj)
mem_ptr = cp.cuda.MemoryPointer(mem, 0)
arr = cp.ndarray(..., memptr= mem_ptr, ...)  # make sure you interpret the array shape/dtype/strides correctly 
```

**Comment by chaithyagr** [comment]
Can we pass this pointer into C/ C++ so that we can call custom CUDA kernels?

**Comment by leofang** [comment]
The pointer address of a CuPy array is available either from `arr.__cuda_array_interface__` or just `arr.data.ptr`. The rest (passing something from Python to C/C++) is on your hand.

**Comment by chaithyagr** [comment]
Thank you

**Comment by jakirkham** [comment]
@chaithyagr, right at least by "...create an empty CuPy ndarrayand grab the underlying memory...", was meaning something like this

```python
arr = cp.empty((size,), dtype=dtype)
my_c_func(arr.data.ptr, size)
```

**Comment by corneliusschroeder** [comment]
> The pointer address of a CuPy array is available either from `arr.__cuda_array_interface__` or just `arr.data.ptr`. The rest (passing something from Python to C/C++) is on your hand.

Could you give me a hint on how to pass the python integer `arr.data.ptr` returns to a C++ function. Im using Cython.
My initial idea was
`cdef float *  ptr = arr.data.ptr`
I also tried:
`cdef cupy.ndarray[ndim=3, dtype=float32_t] data = ...
Cfunc(&data[0])`
(how I did with numpy arrays)
But I get the error: `cupy  is not a cimported module`

Thanks for your help!

**Comment by jakirkham** [comment]
This should work

```cython
from libc.stdint cimport uintptr_t

...

cdef uintptr_t addr = arr.data.ptr
cdef float* ptr = <float*>addr
```

One could also do all the casting at once

**Comment by corneliusschroeder** [comment]
Thank you for your help, passing the pointer to the C++ function works!
However, when reading the data stored at this address, my C++ function throws a segmentation fault error. Is this because of the cupy.cuda.Memorypool or in general due to the location of the cupy.array on the device? Would it help to instantiate a thrust::devicevector with this pointer in the C++ function?

**Comment by jakirkham** [comment]
The pointer won't be accessible on host. So dereferencing it could very well cause a segmentation fault.

Ideally this pointer would be passed to whatever CUDA kernel is called. Alternatively yes it could be wrapped up in some other CUDA aware container that knows how to handle it correctly.
