### ISSUE TITLE
CuPy to support accepting `order` as a parameter to functions other than `cupy.array`

### ISSUE THREAD

**Issue by divyegala** [cupy/cupy#3213]
Would it be possible that functions can accept an `order` parameter? For example, I would love to use https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.random.standard_normal.html#cupy.random.standard_normal with `order='F'`. As it stands, the only way to convert a `C` matrix to `F` is by doing `X = cp.array(X, order='F')`. This temporarily blows up memory usage to 2x as it is most likely creating a copy of the transpose, I believe. For memory intensive applications, this is not the best as OOMs are common.

**Comment by emcastillo** [comment]
Hi!
Thanks for the feedback. With random functions, all the elements are generated independently so just transposing the matrix should give you a Fortran order matrix without an additional copy.

For the random package, NumPy does not support the `order` argument for the routines. So in order to keep as close as possible to NumPy we won't be adding such option. But we are working on adding Generalized Universal Functions, so that `order` will be an argument of several NumPy core routines.

**Comment by leofang** [comment]
You can generate a 1D random array, and then do `arr.reshape(..., order='F')`. No copy would be involved, and only the array metadata (for how to interpret the data) is modified.

**Comment by divyegala** [comment]
@emcastillo so to be sure, ` X = X.T` would involve no additional transfers?

@leofang would the same work for a 2D random array? Since, a 1D array's meta-data about being F or C contiguous wouldn't really mean anything

**Comment by leofang** [comment]
"Reshape" in NumPy/CuPy means changing the dimension of the array as long as the total size remains constant:
https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.ndarray.html#cupy.ndarray.reshape

**Comment by divyegala** [comment]
> "Reshape" in NumPy/CuPy means changing the dimension of the array as long as the total size remains constant:
> https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.ndarray.html#cupy.ndarray.reshape

If you could help with this code snippet, if you don't mind:
```
X = cp.random.multivariate_normal(mean, cov_matrix, size=n_samples, dtype='float32')
X.reshape(X.shape, order='F')
print(X.strides)
print(X.flags)
```

I get an output:
```
(80, 4)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
```

**Comment by leofang** [comment]
Do `X = X.reshape(...)`. Reshape returns a view, and the change is not done in place.

**Comment by divyegala** [comment]
> Do `X = X.reshape(...)`. Reshape returns a view, and the change is not done in place.

```
    X = cp.random.multivariate_normal(mean, cov_matrix, size=n_samples, dtype='float32')
    X = X.reshape(X.shape, order='F')
    print(X.shape)
    print(X.strides)
    print(X.flags)
```
gives me:
```
(100000000, 20)
(80, 4)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
```

Basically nothing changed?

**Comment by leofang** [comment]
Apparently if we wanna draw 1D samples, we should not specify `size` in `multivariate_normal`:
```python
>>> import cupy as cp
>>>
>>> size = 1000
>>> mean = cp.random.random(size)
>>> cov_matrix = cp.diag(cp.ones(size))
>>> a = cp.random.multivariate_normal(mean, cov_matrix, dtype='float32')
>>> a.shape
(1000,)
>>> a = a.reshape(4, 250, order='F')
>>> a.shape
(4, 250)
>>> a.flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
```

**Comment by divyegala** [comment]
> Apparently if we wanna draw 1D samples, we should not specify `size` in `multivariate_normal`:
> 
> ```python
> >>> import cupy as cp
> >>>
> >>> size = 1000
> >>> mean = cp.random.random(size)
> >>> cov_matrix = cp.diag(cp.ones(size))
> >>> a = cp.random.multivariate_normal(mean, cov_matrix, dtype='float32')
> >>> a.shape
> (1000,)
> >>> a = a.reshape(4, 250, order='F')
> >>> a.shape
> (4, 250)
> >>> a.flags
>   C_CONTIGUOUS : False
>   F_CONTIGUOUS : True
>   OWNDATA : False
> ```

@leofang upon more testing, that works but this is also what works for me:
`X = X.T.reshape(X.shape, order='F')`

The problem with the approach you suggested is that I am using the covariance matrix to verify whether my PCA algorithm worked correctly. Reshaping point samples of size `n` to form `1D samples` would not reproduce the same covariance matrix for me from PCA, I believe, as then the columns would become features of their own. If you could verify for me if my approach is correct, then it would be really helpful! :)

**Comment by leofang** [comment]
Ah, I see. I kept thinking in terms of a stream of random numbers and ignored the meaning of dimensions. I think for 2D outputs this should be what you need. 

I suppose you already knew you could check if a copy is made by inspecting if the returned array is just a view or actually holding something. This can be done in a few different ways off my head:
1. `arr.flags['OWNDATA']`
2. `arr.base is None`
3. looking at `arr.data.ptr` (the actual pointer address; a view should have the same address as its base, if it starts from the same address)

**Comment by divyegala** [comment]
This seems to work, thank you so much! In the first method you suggested though, even if a copy is returned, wouldn't `arr.flags['OWNDATA']` be true for both `X` and `X = X.T.reshape(X.shape, order='F')` since I own and created both these arrays?

Also, just as an FYI which I am sure you know about, this kind of gets invalidated the moment we pass X to a function as python takes over at that point, unfortunately!

```
def foo(x):
    x = x.T.reshape(x.shape, order='F')

foo(X)
```
In this case, the re-order isn't in-place and is performed on a copy, which must be returned.
