### ISSUE TITLE
Sparse array created from a cupy ndarray has incorrect values

### ISSUE THREAD

**Issue by Garfounkel** [cupy/cupy#3223]
I'm trying to build a sparse array from a reasonably large cupy ndarray using `cp.sparse.csr_matrix(x)`, but when I test the correctness of the result, some values mismatch between the input array and the output sparse array.

### Code to reproduce
```python
import cupy as cp

dense_ary = cp.ones(shape=(50000, 1003))
sones = cp.sparse.csr_matrix(dense_ary)
cp.testing.assert_array_almost_equal(dense_ary, sones.toarray(), decimal=1)
```

### Error messages, stack traces, or logs
```
AssertionError: 
Arrays are not almost equal to 1 decimals

Mismatched elements: 17973 / 50150000 (0.0358%)
Max absolute difference: 1.
Max relative difference: 0.
 x: array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],...
 y: array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],...`
```

### Conditions
- CuPy Version          : 7.2.0
- CUDA Root             : /usr/local/cuda
- CUDA Build Version    : 10000
- CUDA Driver Version   : 10010
- CUDA Runtime Version  : 10000
- cuBLAS Version        : 10000
- cuFFT Version         : 10000
- cuRAND Version        : 10000
- cuSOLVER Version      : (10, 0, 0)
- cuSPARSE Version      : 10000
- NVRTC Version         : (10, 0)
- cuDNN Build Version   : 7605
- cuDNN Version         : 7600
- NCCL Build Version    : 2406
- NCCL Runtime Version  : 2507

**Comment by emcastillo** [comment]
I have reproduced the issue, and I think this might be a cusparse bug. cc @anaruse @jakirkham @pentschev @leofang 

When creating a csr matrix copy only calls the corresponding `cusparseXdense2csr` routine,
the data array that is returned from there has some entries set to zero.

This is a reduced example

```
import cupy as cp

dense_ary = cp.ones(shape=(50000, 9))
sones = cp.sparse.csr_matrix(dense_ary)
print(dense_ary.sum(), sones.sum(), sones.toarray().sum())
```
If we look at the elements that are set to 0 in the cusparse `dense2csr` returned data array we see that starting from the row 40960 to row 49999 all elements in column 8 are set to 0.

Note that this error only happens when creating a csr matrix and not a csc one.

**Comment by jakirkham** [comment]
cc @cjnolet (for awareness)

**Comment by anaruse** [comment]
Thank you so much for reporting and analyzing the issue, @Garfounkel and @emcastillo !
Fow now, cuSparse team is aware of this issue.

**Comment by jakirkham** [comment]
Should we close if this is a cuSparse issue, @anaruse, or is that still to be determined? 🙂

**Comment by emcastillo** [comment]
I would like to get confirmation whether it is 100% a cusparse issue.

**Comment by anaruse** [comment]
This issue should be left open, in my opinion, but it is a issue of cuSparse, more specifically, cusparse\<t\>dense2csr().

**Comment by kmaehashi** [comment]
We decided to close this as we can't do anything for this issue.
