### ISSUE TITLE
Lexsort output is incorrect

### ISSUE THREAD

**Issue by MrArsGravis** [cupy/cupy#3232]
The output of cupy.lexsort is incorrect. I can't see any pattern as to what is wrong with the output.

### Code to reproduce
```
import cupy
import numpy

# numpy output is correct:
a = (numpy.random.random((10,2)) * 10).astype(int)  # random ints between 0 and 9
print(a[numpy.lexsort(a.T[::-1])])                  # sorted by first column, not last

# cupy output is unsorted:
b = cupy.array(a)
print(b[cupy.lexsort(b.T[::-1])])
```
The same thing happens for floats, so that's not the reason.

### Conditions
(output of `python -c 'import cupy; cupy.show_config()'`):

CuPy Version          : 7.1.1
CUDA Root             : /opt/cuda
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2507
NCCL Runtime Version  : 2507

**Comment by takagi** [comment]
Thanks for the report, I can reproduce the result.

**Comment by leofang** [comment]
Not sure if this is relevant, but lexsort would fail these two tests:
```diff
diff --git a/tests/cupy_tests/sorting_tests/test_sort.py b/tests/cupy_tests/sorting_tests/test_sort.py
index b00856866..5b0c67d58 100644
--- a/tests/cupy_tests/sorting_tests/test_sort.py
+++ b/tests/cupy_tests/sorting_tests/test_sort.py
@@ -202,6 +202,20 @@ class TestLexsort(unittest.TestCase):
         with self.assertRaises(TypeError):
             return cupy.lexsort(a)
 
+    @testing.for_dtypes('fdFD')
+    @testing.numpy_cupy_allclose()
+    def test_nan2(self, xp, dtype):
+        a = testing.shaped_random((2, 10), xp, dtype)
+        a[0, 2] = a[1, 6] = xp.nan
+        return xp.lexsort(a)
+
+    @testing.for_dtypes('fdFD')
+    @testing.numpy_cupy_allclose()
+    def test_nan3(self, xp, dtype):
+        a = testing.shaped_random((2, 10), xp, dtype)
+        a[1, 2] = a[1, 6] = xp.nan
+        return xp.lexsort(a)
+
 
 @testing.parameterize(*testing.product({
     'external': [False, True],
```
lexsort with `a[0, 2] = a[0, 6] = xp.nan` is correct, though.
