### ISSUE TITLE
CuPy fails to autodetect CUDA root directory after successful ROCm installation.

### ISSUE THREAD

**Issue by mihirparadkar** [cupy/cupy#3246]
I installed CuPy using the ROCm install instructions 
```shell
$ export HCC_AMDGPU_TARGET=gfx1010,gfx1012 && export __HIP_PLATFORM_HCC__ && export CUPY_INSTALL_USE_HIP=1 && export ROCM_HOME=/opt/rocm

$ pip install --no-cache-dir cupy
```
Installation completed successfully, I can create a cupy ndarray, but attempting any operation on it results in the following error:
```python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cupy as cp
>>> x = cp.array([1, 2, 3.])
>>> 2 * x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 980, in cupy.core.core.ndarray.__mul__
  File "cupy/core/_kernel.pyx", line 951, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/_kernel.pyx", line 974, in cupy.core._kernel.ufunc._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 714, in cupy.core._kernel._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 61, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 179, in cupy.core.core.compile_with_cache
RuntimeError: Failed to auto-detect CUDA root directory. Please specify `CUDA_PATH` environment variable if you are using CUDA v9.0, v9.1 or versions not yet supported by CuPy.
```

System is CuPy version 7.3.0, Linux Mint 19.3 on amd64, ROCm version 3.1.0 .

Thanks!

**Comment by mihirparadkar** [comment]
I got the specific example working by setting `CUDA_PATH=/opt/rocm`. I'll send a PR adding this step to the docs.

**Comment by leofang** [comment]
Interesting. I think in the long run we need to add `get_hip_path()` and `get_hipcc_path` (analogs of `get_cuda_path()` and `get_nvcc_path()` in `cupy/_environment.py`, respectively) and use them in an HIP build.

**Comment by emcastillo** [comment]
I will fix this by not looking `CUDA_PATH` when an AMD build is done

**Comment by leofang** [comment]
possibly related: #3222.

**Comment by emcastillo** [comment]
Thanks Leo!

**Comment by leofang** [comment]
I think this issue is resolved, @mihirparadkar could you confirm? Though currently we only support ROCm 3.5.0 on the master branch. I will add a PR to support 3.5+ asap.

**Comment by leofang** [comment]
ROCm 3.5+ is supported on the master branch.
