### ISSUE TITLE
cufftPlanMany() argument support in cupyx.scipy.fftpack.get_fft_plan

### ISSUE THREAD

**Issue by jhill2** [cupy/cupy#3263]
I'm looking for the ability to do multiple overlapped FFTs on a 1D array of data. With cufftPlanMany() function in cuFFT I can set the istride/ostride and idist/odist arguments to accomplish this. I can also set the type to R2C, C2R, C2C (and other datatype equivalents).

I appreciate that cupyx.scipy.fftpack.get_fft_plan gives me the ability to set a plan prior to running multiple FFTs. However, it doesn't seem to give the same functionality as cufftPlanMany does. It is also currently restricted to C2C or Z2Z. Can get_fft_plan be expanded to give the user the same options as cufftPlanMany offers?

**Comment by leofang** [comment]
If you'd like to set `istride` and friends, I'd suggest you to initiate `cupy.cuda.cufft.PlanNd` directly. This is the object returned by `cupyx.scipy.fftpack.get_fft_plan()`. The convenience function `get_fft_plan()` is meant to be a high-level API, whereas you're asking low-level access. Let me know if you encounter any difficulty doing this.

As for the transform types, there's a PR pending review to support C2R/R2C/D2Z/Z2D: #3102.

**Comment by leofang** [comment]
I'll add the support of R2C/C2R to `get_fft_plan()` after #3102 is merged.

**Comment by leofang** [comment]
#3293 enables getting R2C/C2R FFT plans from `get_fft_plan()`.

**Comment by leofang** [comment]
@jhill2 Both #3102 and #3293 are merged to master.
