### ISSUE TITLE
cupy.cov is slower than numpy.cov

### ISSUE THREAD

**Issue by GwangsooHong** [cupy/cupy#3267]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
CuPy Version          : 7.3.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10010
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10010
cuBLAS Version        : 10201
cuFFT Version         : 10101
cuRAND Version        : 10101
cuSOLVER Version      : (10, 2, 0)
cuSPARSE Version      : 10300
NVRTC Version         : (10, 1)
cuDNN Build Version   : 7605
cuDNN Version         : 7600
NCCL Build Version    : 2406
NCCL Runtime Version  : 2507

* Code to reproduce
```
import cudf
import numpy as np
import cupy as cp
import time
from cupy.cuda import nvtx

path = 'random_data_9000000.csv' 
gdf = cudf.io.read_csv(path, header = None)

print(gdf)
np_data = gdf.as_matrix()[:,0]
cp_data = cp.fromDlpack(gdf.to_dlpack())[:,0]

y_cp =cp_data 
x_cp = cp.asarray(range(len(cp_data)))

y_np = np_data
x_np = np.asarray(range(len(np_data)))

nvtx.RangePush('numpy.cov')
np.cov(x_np, y_np, bias=1)
nvtx.RangePop()
nvtx.RangePush('cupy.cov')
cp.cov(x_cp, y_cp, bias=1)
nvtx.RangePop()
```
![image](https://user-images.githubusercontent.com/60726624/78730735-adf87880-7978-11ea-83e6-1e88906d1de5.png)

CUDA free is so long!!

* Error messages, stack traces, or logs

**Comment by emcastillo** [comment]
You are only measuring the first execution which is known to be slow. If you warmup cov in a loop and repeat it should be considerably faster.
