### ISSUE TITLE
missing constructor for `scipy.sparse.csr_matrix`

### ISSUE THREAD

**Issue by csukuangfj** [cupy/cupy#3289]
<https://docs-cupy.chainer.org/en/stable/reference/sparse.html#sparse-matrices>
says

> CuPy supports sparse matrices using cuSPARSE. **These matrices have the same interfaces of SciPy’s sparse matrices.**

**However**, the constructor
> csr_matrix((data, (row_ind, col_ind)), [shape=(M, N)])

from <https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html#scipy-sparse-csr-matrix>

![Screen Shot 2020-04-16 at 18 36 47](https://user-images.githubusercontent.com/5284924/79446710-434adb00-8011-11ea-8242-ca7f7153e3a5.png)

is **missing** in `cupyx.scipy.sparse.csr_matrix` in
https://docs-cupy.chainer.org/en/stable/reference/generated/cupyx.scipy.sparse.csr_matrix.html#cupyx-scipy-sparse-csr-matrix

![Screen Shot 2020-04-16 at 18 37 47](https://user-images.githubusercontent.com/5284924/79446777-64abc700-8011-11ea-8690-ef2943ab5b33.png)

**Comment by leofang** [comment]
To add another example: the constructor `coo_matrix(D)` (initializing a COO matrix with a dense matrix) is also missing.
