### ISSUE TITLE
Drop support for CUDA 8.0 and 9.1 in v8

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3301]
As users of CUDA 8.0 and 9.1 are decreasing, we are planning to drop support for these CUDA versions.

**Comment by leofang** [comment]
Note: This is in line with conda-forge's CUDA support. Currently we only build for CUDA 9.2+.

**Comment by leofang** [comment]
Hi @gmarkall I read somewhere that Numba still supports CUDA 8.0. Am I right? Would this plan cause negative impacts?

**Comment by kmaehashi** [comment]
We are going to drop support for CUDA 8.0 / 9.1 starting in CuPy v8.0.0rc1.

**Comment by gmarkall** [comment]
> Hi @gmarkall I read somewhere that Numba still supports CUDA 8.0. Am I right? Would this plan cause negative impacts?

It only supports it because it has not been inconvenient to - I believe we could drop support for 8.0 without causing issues.

**Comment by leofang** [comment]
Thanks, @gmarkall!
