### ISSUE TITLE
Element-wise power of ndarray is not accurate

### ISSUE THREAD

**Issue by b787abel** [cupy/cupy#3302]
Bug report - configuration 

OS: Windows 10 Enterprise 2016 LTSB 64-bit (10.0, Build 14393)
```
CuPy Version          : 7.3.0
CUDA Root             : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
CUDA Build Version    : 10010
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10010
cuBLAS Version        : 10201
cuFFT Version         : 10101
cuRAND Version        : 10101
cuSOLVER Version      : (10, 2, 0)
cuSPARSE Version      : 10300
NVRTC Version         : (10, 1)
cuDNN Build Version   : 7500
cuDNN Version         : 7500
NCCL Build Version    : None
NCCL Runtime Version  : None
```
I noticed a small difference between raising arrays to a power (in particular to power of 2) between cupy and numpy. I used three different methods, the ** operator, the cupy.power function and element wise product of array with itself. 
```
x=np.random.random(1000)
xcu=cupy.array(x)
xsqnp=np.power(x,2)
xsqcu1=xcu**2
xsqcu2=cupy.power(xcu,2)
xsqcu3=xcu*xcu
print(np.sum(xsqnp!=cupy.asnumpy(xsqcu1)))
print(np.sum(xsqnp!=cupy.asnumpy(xsqcu2)))
print(np.sum(xsqnp!=cupy.asnumpy(xsqcu3)))
```

The output was 209, 209, 1 for a single run, but in general, the first two methods created equal results in the range 150-300 while the third method created a result under 10.

**Comment by emcastillo** [comment]
That is due to numerical precision.
Comparing the numbers without a tolerance threshold is likely going to yield differences if the algorithms used to implement the operations are different.

You can compare the results using `cupy.testing.assert_allclose(xsqnp, xsqcu1)`

**Comment by b787abel** [comment]
The reason was indeed numerical precision, the difference between the two arrays was typically one last digit.

**Comment by emcastillo** [comment]
Glad it worked out for you!
Thanks for reporting back
