### ISSUE TITLE
Convert Following piece of code from Numpy to Cupy

### ISSUE THREAD

**Issue by bosssaurav** [cupy/cupy#3306]
**Assume : segmentation,image_raw is cupy array**
from PIL import Image as Img

        mask = cp.dot(segmentation, cp.array([[1, 255, 1]]))
        output = cp.where(segmentation==0,image_raw,mask)
  ---->      output = Img.fromarray(output.astype('uint8'))
1 error that i get is : AttributeError: 'cupy.core.core.ndarray' object has no attribute '__array_interface__'

2nd error : 
This line gives a very randomised output like this : 
xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01\xff\x01\x01

**Comment by emcastillo** [comment]
I think PIL's ` Img.fromarray` requires the input to be a NumPy array, so you have to convert the array back.
`Img.fromarray(cupy.asnumpy(output.astype('uint8')))` should do it.

**Comment by bosssaurav** [comment]
Hmmm.. yes. I was using open Cv Bridge which takes in input as numpy arrays. If you could bring cupy as a feature compatible with Opencv PIL and tensorflow. It could be a great hit, i suppose
