### ISSUE TITLE
cupy website problem

### ISSUE THREAD

**Issue by QinZhang99** [cupy/cupy#3313]
https://docs-cupy.chainer.org/en/stable/

The page isn’t redirecting properly

**Comment by leofang** [comment]
Looks like the website is down?

**Comment by QinZhang99** [comment]
Yes, but it worked yesterday.

**Comment by emcastillo** [comment]
We are looking into it, thanks :)

**Comment by QinZhang99** [comment]
The website works now!
Thanks,
Qin
