### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'record'

### ISSUE THREAD

**Issue by mnicely** [cupy/cupy#3316]
CuPy Version          : 7.3.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2406
NCCL Runtime Version  : 2507

If I try to run the following command, I get the following error.
`cp.asarray(z[cp.newaxis, :, :])`

```bash
Traceback (most recent call last):
  File "kalman.py", line 125, in <module>
    z = cp.asarray(z[cp.newaxis, :, :])
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cupy/creation/from_data.py", line 68, in asarray
    return core.array(a, dtype, False, order)
  File "cupy/core/core.pyx", line 1785, in cupy.core.core.array
  File "cupy/core/core.pyx", line 1862, in cupy.core.core.array
  File "cupy/core/core.pyx", line 1950, in cupy.core.core._send_object_to_gpu
AttributeError: 'NoneType' object has no attribute 'record'
```

What's interesting is that it only happens after a run a CuPy kernel. One which doesn't even access variable z.

**Comment by leofang** [comment]
What's the shape of `z`?

**Comment by mnicely** [comment]
2 x 1 array
`z = np.array([i, i], dtype=dt).T`

**Comment by mnicely** [comment]
I thought I got around but I'm hitting it again. I'm trying to run a loop and it crashes on the first `cp.asarray` of the second loop (that uses CuPy raw kernels).

See my latest script.
[kalman_test_script.txt](https://github.com/cupy/cupy/files/4611552/kalman_test_script.txt)

**Comment by takagi** [comment]
I'll try to reproduce the error with installing cuSignal.

**Comment by takagi** [comment]
@mnicely I couldn't find `cusignal.KalmanFilter` when I tried to run `kalman_test_script.txt`. Do you know something about it? I installed cuSignal following its install guide with conda.

```Python
$ python kalman_test_script.py
num_points 4096
iterations 1
use_numba True
data type <class 'numpy.float32'>
loops 50
Traceback (most recent call last):
  File "kalman_test_script.py", line 143, in <module>
    run_test(p, i, n, d)
  File "kalman_test_script.py", line 22, in run_test
    cuS = cusignal.KalmanFilter(
AttributeError: module 'cusignal' has no attribute 'KalmanFilter'
```

**Comment by mnicely** [comment]
@takagi Thanks for the help. It's probably easier to checkout my local branch.

https://github.com/mnicely/cusignal/tree/kalman_filter. You'll need to build cuSignal with `build.sh` in the parent cuSignal folder. Let me know if you have issues.

**Comment by takagi** [comment]
Thanks, I'll try it.

**Comment by takagi** [comment]
@mnicely Which CuPy do you use? I tried [leofang:nvrtc_template](https://github.com/leofang/cupy/tree/nvrtc_template) but still could not find `RawModule.get_mangled_name`.

```
AttributeError: 'cupy.core.raw.RawModule' object has no attribute 'get_mangled_name'
```

**Comment by mnicely** [comment]
@takagi I've been using this 
https://github.com/cupy/cupy/pull/3319#issuecomment-623479983

**Comment by leofang** [comment]
Hi, sorry I dropped the ball. Not sure why that PR is needed here, but `get_mangled_name` is now merged to `get_function` so you just need to call the latter.

**Comment by mnicely** [comment]
@takagi It looks like I need to pull in @leofang's latest updates to the API.

**Comment by mnicely** [comment]
@takagi I believe I made the appropriate changes. Can you try now?

**Comment by leofang** [comment]
Sorry I should have updated the PR description to reflect the change. Working on it now...

**Comment by takagi** [comment]
Thanks! I could run the script, but not reproduce the error. Here shows `cupy.show_config()`

```
CuPy Version          : 8.0.0b2
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10010
cuBLAS Version        : 10201
cuFFT Version         : 10101
cuRAND Version        : 10101
cuSOLVER Version      : (10, 2, 0)
cuSPARSE Version      : 10300
NVRTC Version         : (10, 1)
cuDNN Build Version   : 7500
cuDNN Version         : 7600
NCCL Build Version    : 2402
NCCL Runtime Version  : 2604
CUB Version           : None
cuTENSOR Version      : None
```

Weird is that https://github.com/leofang/cupy/tree/nvrtc_template is based on CuPy's `master`, which should not be version `7.3.0` shown above. I guess something wrong on your environment. Would you check CuPy you use and try again?

**Comment by mnicely** [comment]
@takagi Thanks for checking it out. Below is my configuration
```bash
CuPy Version          : 8.0.0b2
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : None
cuDNN Version         : None
NCCL Build Version    : None
NCCL Runtime Version  : None
CUB Version           : Enabled
cuTENSOR Version      : None
```

I'm still getting that error. :/
I've attached output below. To confirm, you're using the code from `kalman_test_script.txt`, not what's in the repo (`kalman_test_script.py`)?

[kalman_test_output.txt](https://github.com/cupy/cupy/files/4710972/kalman_test_output.txt)

**Comment by takagi** [comment]
Ah, I ran one in the repo and now can reproduce the error with running `kalman_test_script.txt` . Okay, I'll look into it further.

**Comment by takagi** [comment]
It is supposed that the cause is `cusignal.KalmanFilter` instance doesn't keep reference to `Stream`s it uses and they are already collected when they are to be used. Would you check the part?

**Comment by mnicely** [comment]
Sorry @takagi, I'm confused. All cusignal functions use default streams if one is not specified.

**Comment by takagi** [comment]
I mean CuPy's `Stream` objects at the following lines:

https://github.com/mnicely/cusignal/blob/a366bb66fb56357d98e77276ba9d031c347febb8/python/cusignal/estimation/filters.py#L150

https://github.com/mnicely/cusignal/blob/a366bb66fb56357d98e77276ba9d031c347febb8/python/cusignal/estimation/filters.py#L160

but, sorry, I misunderstood that these objects are actually referenced by `_cupy_predict_wrapper` and `_cupy_update_wrapper` so it's not the cause.

The actual cause is that, in a previous loop, a `KalmanFilter` instance's CuPy `Stream` is left being `use`d and, in the next loop, it is collected when another `KalmanFilter` instance is assigned, eventually the CuPy current stream becomes `None` with a dead weak reference.

I've confirmed that `with` statement for temporary `Stream` use eliminate the error:

```Python
diff --git a/python/cusignal/estimation/_filters.py b/python/cusignal/estimation/_filters.py
index 3686d68..0fbad8b 100644
--- a/python/cusignal/estimation/_filters.py
+++ b/python/cusignal/estimation/_filters.py
@@ -676,8 +676,8 @@ class _cupy_predict_wrapper(object):

         kernel_args = (x.shape[0], alpha_sq, x, F, P, Q)

-        self.stream.use()
-        self.kernel(self.grid, self.block, kernel_args)
+        with self.stream:
+            self.kernel(self.grid, self.block, kernel_args)


 class _cupy_update_wrapper(object):
@@ -696,8 +696,8 @@ class _cupy_update_wrapper(object):

         kernel_args = (x.shape[0], x, z, H, P, R)

-        self.stream.use()
-        self.kernel(self.grid, self.block, kernel_args)
+        with self.stream:
+            self.kernel(self.grid, self.block, kernel_args)


 def _get_backend_kernel(dtype, grid, block, smem, stream, use_numba, k_type):
```

**Comment by mnicely** [comment]
Thanks @takagi! This is great to understand. It looks like I need to update our library to issue we don't see this issue again.

**Comment by takagi** [comment]
Also, it's not essential for this issue but you can use predefined `cupy.cuda.stream.Stream.null` instead of instantiating your own for the default stream.

**Comment by mnicely** [comment]
Thanks! I didn't realize that.
