### ISSUE TITLE
feature request:  add ability to pass multiple arches using CUPY_NVCC_GENERATE_CODE

### ISSUE THREAD

**Issue by JasonAtNvidia** [cupy/cupy#3317]
It would be very helpful to change this line
https://github.com/cupy/cupy/blob/2804af926cead8d2e80665283473a71212e824b0/cupy_setup_build.py#L765
to use list comprehension in order to pass multiple architectures on the command line.  This is useful for building the list of not included architectures from Jetson such as 53,62,and 72.

Something like this with + sign delimited works great
`return ['--generate-code={}'.format(val) for val in envcfg.split('+')]`

and allows me to build with CUPY_NVCC_GENERATE_CODE="arch=compute_62,code=sm_62+arch=compute_72,code=sm_72" and everything builds great.

**Comment by leofang** [comment]
I guess for style consistency with CuPy's companioning project Chainer, we better use semicolon as the delimiter, see https://github.com/chainer/chainer/pull/8370.
