### ISSUE TITLE
different result between cupy.sort and numpy.sort with NaN

### ISSUE THREAD

**Issue by Sean6028** [cupy/cupy#3324]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version: cupy-cuda100==7.4.0
  - Python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
  - OS/Platform: win32
  - CUDA version: V10.0.130
* Code to reproduce:

`
import numpy as np
import cupy as cp
arr_np = np.array(
    [[0.77],
     [0.00],
     [np.nan],
     [0.50],
     [0.85]]
)
arr_cp = cp.array(arr_np)

print(cp.sort(arr_cp, axis=0))
print(np.sort(arr_np, axis=0))
`
* Outputs:
Result of cupy.sort:
 [[0.  ]
 [0.77]
 [ nan]
 [0.5 ]
 [0.85]]
Result of numpy.sort:
 [[0.  ]
 [0.5 ]
 [0.77]
 [0.85]
 [ nan]]

**Comment by leofang** [comment]
Hi @Sean6028, I recently fixed it in v8.0.0b2 (#3291). Could you give it a try?

**Comment by Sean6028** [comment]
> Hi @Sean6028, I recently fixed it in v8.0.0b2 (#3291). Could you give it a try?

Sure. It works well in v8.0.0b2. Thank you.

**Comment by leofang** [comment]
Glad to know 🙂 Thanks, Sean.
