### ISSUE TITLE
delay due to cudaFree in 1st call of cupy.dot or similar calls 

### ISSUE THREAD

**Issue by shourya-otta** [cupy/cupy#3339]
I am attaching an example comparing numpy and cupy. There are frequent cudaMallocs/Frees. Using RMM (rapids), this is reduced. But it is still not possible to get rid of the 1st call.  Please see the cudaFree in the fig below : 

```
CuPy Version          : 7.3.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2406
NCCL Runtime Version  : 2507
``` 
I used for profiling : nsys profile -o np_cp_example -t cuda,nvtx,cublas,cudnn python timings_np_cp_0501.py

![image](https://user-images.githubusercontent.com/55850779/81864252-3bebf400-9521-11ea-8535-404cec82778f.png)

[timings_np_cp_0501_py.txt](https://github.com/cupy/cupy/files/4624629/timings_np_cp_0501_py.txt)

**Comment by leofang** [comment]
xref: https://stackoverflow.com/questions/61785008/

**Comment by kmaehashi** [comment]
It seems `cudaFree` is called during the creation of the cuBLAS handle, which cannot be controlled from outside of the CUDA Toolkit.

https://docs-cupy.chainer.org/en/latest/reference/memory.html
> CUDA allocates some GPU memory outside of the memory pool (such as CUDA context, library handles, etc.).
