### ISSUE TITLE
Couple of small issues when building from source

### ISSUE THREAD

**Issue by benvanwerkhoven** [cupy/cupy#3349]
Hi! I just built Cupy from source and ran into some issues.

I noticed that the environment variable LIBRARY_PATH is used where LD_LIBRARY_PATH is meant: https://github.com/cupy/cupy/blob/master/cupy_setup_build.py#L342
I know the difference between the two is very subtle, but the fact that LIBRARY_PATH is used here to provide shared library locations to the linker was unexpected for me.

After several failed attempts I noticed that cython version was the issue. Cython is (to my surprise) not listed as a required package in setup.py so my outdated cython installation was going unnoticed. I had cython version 0.25.2, and after a ``pip install -U cython`` I now have cython-0.29.17. After this I was able to compile most files until I ran into this error:

```
    cupy/cuda/cupy_cub.cu:1:28: fatal error: cupy/complex.cuh: No such file or directory
     #include <cupy/complex.cuh>
                                ^
    compilation terminated.
    error: command '/cm/shared/apps/cuda10.0/toolkit/10.0.130/bin/nvcc' failed with exit status 1
```
which I could fix by adding the include directory ``cupy/build/lib.linux-x86_64-3.5/cupy/core/include`` to my CPATH. After that I could compile everything and it's working. 

So these aren't exactly bugs, and if you've been through this once you won't have the issues again, but I thought it could be relevant to share my experiences.

**Comment by leofang** [comment]
> I noticed that the environment variable LIBRARY_PATH is used where LD_LIBRARY_PATH is meant: https://github.com/cupy/cupy/blob/master/cupy_setup_build.py#L342
> I know the difference between the two is very subtle, but the fact that LIBRARY_PATH is used here to provide shared library locations to the linker was unexpected for me.

I think if you build from source, `LD_LIBRARY_PATH` is used. Notice the line you quoted was only used to print the info; the env var `LIBRARY_PATH` was not used. In this sense, I agree that line should be changed.
> After several failed attempts I noticed that cython version was the issue. Cython is (to my surprise) not listed as a required package in setup.py so my outdated cython installation was going unnoticed. I had cython version 0.25.2, and after a `pip install -U cython` I now have cython-0.29.17. After this I was able to compile most files until I ran into this error:
> 
> ```
>     cupy/cuda/cupy_cub.cu:1:28: fatal error: cupy/complex.cuh: No such file or directory
>      #include <cupy/complex.cuh>
>                                 ^
>     compilation terminated.
>     error: command '/cm/shared/apps/cuda10.0/toolkit/10.0.130/bin/nvcc' failed with exit status 1
> ```
> 
> which I could fix by adding the include directory `cupy/build/lib.linux-x86_64-3.5/cupy/core/include` to my CPATH. After that I could compile everything and it's working.

Your Cython version was pretty old. CuPy requires at least 0.28.0: https://docs-cupy.chainer.org/en/stable/install.html. It's not listed as requirement because (I guess) it's possible to build from sdist, which would not require Cython.

**Comment by leofang** [comment]
Hit "Comment" too quick...

> After this I was able to compile most files until I ran into this error:
> 
> ```
>     cupy/cuda/cupy_cub.cu:1:28: fatal error: cupy/complex.cuh: No such file or directory
>      #include <cupy/complex.cuh>
>                                 ^
>     compilation terminated.
>     error: command '/cm/shared/apps/cuda10.0/toolkit/10.0.130/bin/nvcc' failed with exit status 1
> ```
> 
> which I could fix by adding the include directory `cupy/build/lib.linux-x86_64-3.5/cupy/core/include` to my CPATH. After that I could compile everything and it's working.

I don't understand why you ran into this error. Did you set `CUB_PATH` but did not point it to a proper CUB source, or were CUB headers available in your include search path?

**Comment by benvanwerkhoven** [comment]
Hi! Yeah I've been using CUB for various codes so its headers are already on my CPATH. I don't follow how that influences things, but maybe the script checks if CUB is found and makes some assumption?

**Comment by leofang** [comment]
Thanks for confirming, @benvanwerkhoven. This issue has been brought up in #3075, see https://github.com/cupy/cupy/issues/3075#issuecomment-587274690. It will be fixed in #2584. For now the resolution is to always point `CUB_PATH` to your local CUB folder.

**Comment by leofang** [comment]
@emcastillo Something is fishy here. We do have this line specifying lowest Cython version:
https://github.com/cupy/cupy/blob/e6474838a922b7869fb56380c8b9421702da1b26/cupy_setup_build.py#L25

but why didn't it give a hard error in the op's case?

**Comment by benvanwerkhoven** [comment]
I was surprised by that as well.

**Comment by kmaehashi** [comment]
> but why didn't it give a hard error in the op's case?

If you build from source tarball on PyPI, Cython is not used at all because pre-generated `*.cpp` files are included in it. (as discussed above Cython was not a cause of the op's issue)
