### ISSUE TITLE
Is there a way to pass a structured buffer to a custom kernel, like arrow cuda buffer or flatbuffers buffer

### ISSUE THREAD

**Issue by pragmasoft-ua** [cupy/cupy#3359]
This isn't actually an issue, just a question and maybe a feature request or at least documentation request, as I didn't find other ways to ask a question, like chat or group. 

I'm looking for a way / example to pass a structured byte buffer to a custom kernel. 

I didn't find any documentation or examples of how to use low level cuda api, for example 

cupy.cuda.MemoryPointer with a custom kernel, ie pass it as an argument, create it from the host and/or device buffer?

I'm looking for an integration with an Arrow and/or Flatbuffers or alike offset based flat structures.

**Comment by kmaehashi** [comment]
Thanks for the feedback, `cupy.cuda.MemoryPointer` can be passed as an argument to raw kernels but not documented very well. We now have a gitter channel so feel free to join and ask questions when needed. https://gitter.im/cupy/community
