### ISSUE TITLE
cupy doesn't support install in arm

### ISSUE THREAD

**Issue by guoxiaolu** [cupy/cupy#3362]
- CuPy version:7.0.4
  - OS/Platform:ubuntu18.04
  - CUDA version:10.0
When install in nvidia-nx(arm), pip install and python setup.py install cannnot be successful.
Error message like this: "ERROR: Failed building wheel for fastrlock".
If fastrlock is installed before, pip install will be successful.

**Comment by leofang** [comment]
related: #3196

**Comment by kmaehashi** [comment]
AFAIK this is the error in setuptools. https://github.com/chainer/chainer-test/issues/565
Workarounds: `pip install wheel` or `pip install 'setuptools<42'`.
