### ISSUE TITLE
missing  libcufft.so.10

### ISSUE THREAD

**Issue by benjaminhon** [cupy/cupy#3368]
Hi I am using nvidia's official docker image nvidia/cudagl:10.1-base-ubuntu18.04

I installed cupy corresponding to cuda 10.1

```
pip install cupy-cuda101
```

after import cupy i get this error, 

```
>>> import cupy
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cupy/__init__.py", line 21, in <module>
    from cupy import core  # NOQA
  File "/usr/local/lib/python3.6/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: libcufft.so.10: cannot open shared object file: No such file or directory
```

**Comment by benjaminhon** [comment]
i think its because the cuda toolkit is not installed is there a list of which cuda toolkit libraries that cupy uses? because the entire toolkit is quite large about 2GBs, im thinking of just copying out the required .so files like libcufft etc.. for a smaller docker image

**Comment by kmaehashi** [comment]
CuPy requires many libraries from the standard CUDA runtime toolkit. For minimal footprint, you can install a separate package like `apt install cuda-cufft-10-1`. (I'd suggest avoid copying required so files manually).

Libraries required are not documented but you can make a guess by: 
```
$ cd site-packages
$ ldd $(find cupy cupyx -name '*.so') | awk '{print $1}' | sort | uniq | grep lib
/lib64/ld-linux-x86-64.so.2
libc.so.6
libcublas.so.9.2
libcudart.so.9.2
libcuda.so.1
libcudnn.so.7
libcufft.so.9.2
libcurand.so.9.2
libcusolver.so.9.2
libcusparse.so.9.2
libdl.so.2
libgcc_s.so.1
libgomp.so.1
libm.so.6
libnccl.so.2
libnvidia-fatbinaryloader.so.396.37
libnvrtc.so.9.2
libnvToolsExt.so.1
libpthread.so.0
librt.so.1
libstdc++.so.6
```

**Comment by benjaminhon** [comment]
it works after copied all the toolkit libraries

```
COPY --from=nvidia/cudagl:10.1-devel-ubuntu18.04  /usr/local/cuda-10.1/targets/x86_64-linux/lib       /usr/local/cuda-10.1/targets/x86_64-linux/lib/
```
