### ISSUE TITLE
Support Jitify ?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#3408]
This is more for my own little curiosity than a feature request, but I thought it's worth discussing.

It is not possible to compile Thrust/CUB code in NVRTC because many system headers are missing, which was why @emcastillo struggled in #2629 and we still have to keep a copy of our own Thrust complex headers. [Jitify](https://github.com/NVIDIA/jitify) claims to provide an easy solution to address this.

I have been looking into jitify's implementation lately, and I think the key idea is to:
1. Recursively find out what header (and its absolute path) should be included (by repeating compiling -> inspecting error log)
2. Fix the headers: for example, provide some stubs to patch a few C++ `std` functions or system headers so that they can work as `__device__` functions, remove static variables, fix `pragma`, etc

Since we have most of the toolchain in place (compile/launch/CUDA API/etc), especially #3319 is now merged, I think it is not super difficult to address this. I can think of two design choices:
1. Wrap jitify in `cupy.cuda.jitify`: 
Ideally, we still use our NVRTC wrapper to do compilation, and only take all these lookup implementations as-is so we don't reinvent the wheel. Unfortunately it is currently not possible, as many logics are baked in jitify's public APIs, and it requires some refactoring on the their side for us to reuse.
2. Implement the compile-error search loop by ourselves in `cupy/cuda/compiler.py`: 
This would require kinda reimplementing what's done in jitify, but only for a small part (I hope). The pro is jitify doesn't need to be a dependency and we just reuse what's already available (very important for code maintenance), and the cons are that it takes more effort and that it needs to copy a significant amount of code from jitify (mainly those code patches).

I think a few RAPIDS libraries like cuDF use jitify. I will dig into how they use it...

**Comment by emcastillo** [comment]
cub complex headers are pretty much stable, as they are just a struct and a couple of functions to manipulate the members that are very unlikely to change. I am not sure if doing all this is better than just keep the headers the way they are.

**Comment by leofang** [comment]
> cub complex headers are pretty much stable, as they are just a struct and a couple of functions to manipulate the members that are very unlikely to change. I am not sure if doing all this is better than just keep the headers the way they are.

No, I don't mean to remove CuPy's complex headers. The jitify solution (either the native one or the proposed designs) would impose a lot of overhead for compilation (according to [a public talk](https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s91043-rapids-cuda-dataframe-internals-for-c++-developers.pdf) it's ~300 ms), so for complex numbers we better not to do this and stay with the status quo (I agree it's quite stable and good). 

The use case I have in mind is 1. custom C++ `RawKernel`s that uses Thrust, CUB (ex: #3244), or other CUDA C++ libraries.

> Also most likely, this is going to increase the cubin generated files size. Not sure if it's affordable

I don't understand why cubin size would increase. Even the native jitify uses NVRTC under the hood.

**Comment by emcastillo** [comment]
Sorry, I just replied without completely understanding the issue.
I agree that for CUB this is good.
Regarding the cubin, nvmd that😅.

**Comment by leofang** [comment]
Ah, actually it's a legit concern and your intuition was right, @emcastillo. A jitify-generated kernel could have a larger size due to the addition of extra things (which might not be used). They recently fixed this: https://github.com/NVIDIA/jitify/pull/40.

**Comment by emcastillo** [comment]
Yeah, I thought that it was possible for all the declarations in the templates to bloat the ptx files.
Glad to see that our Nvidia friends are smart and solved this :)

**Comment by kkraus14** [comment]
cc @devavret @harrism and @jrhemstad who are the most familiar with Jitify usage in cuDF if they can answer any questions for you 😄

**Comment by devavret** [comment]
libcudf does not use jitify with cub/thrust if that’s the primary goal. We have some basic kernels and jitify was used as a convenience wrapper around NVRTC.

**Comment by leofang** [comment]
Thanks a lot for bringing the party here, @kkraus14 😂 Now I know who to ask when I revisit this issue!

**Comment by harrism** [comment]
There is interest in compiling Thrust / CUB with jitify. Here's a PR that takes steps toward that: https://github.com/NVIDIA/jitify/pull/39  Not sure what the status of that PR is now.

**Comment by leofang** [comment]
> The use case I have in mind is custom C++ `RawKernel`s that uses Thrust, CUB (related: #3244), or other CUDA C++ libraries.

I knew there must be someone thinking of the same thing! See #3728.

**Comment by maddyscientist** [comment]
@harrism just to note that https://github.com/NVIDIA/jitify/pull/39 has been merged.

**Comment by leofang** [comment]
Hi @maddyscientist, just out of curiosity to evaluate the level of challenge, do I understand it correctly that once C/C++ header includes are mapped correctly (ex: `#include <limits.h>` -> `jitsafe_header_limits_h`) NVRTC will be able to compile it correctly? We (CuPy) already have NVRTC and a full build chain working, so I am hoping this is the last missing piece to achieve what jitify can provide.

**Comment by maddyscientist** [comment]
Not sure I follow this question @leofang.  Jitify takes care of this mapping automatically, so that the code the user provides just has to `#include <limits.h>` are normal in the user kernel source code.

**Comment by leofang** [comment]
Thanks @maddyscientist, I meant to do this mapping under the hood for CuPy users. So suppose I have a piece of "illegal" code like below:
```python
my_bad_code = r'''
#include <limits.h>
#include <thrust/...>

// If we just use NVRTC to compile this snippet, we get errors
extern "C" __global__ some_kernel_cannot_be_compiled_natively_by_nvrtc(...) { 
    /* ... */
}
'''
```
but I'd still like to pass this to `cupy.RawKernel`/`cupy.RawModule` and use NVRTC to compile it:
```python
mod = cupy.RawModule(code=my_bad_code, backend='nvrtc')
ker = mod.get_function('some_kernel_cannot_be_compiled_natively_by_nvrtc')
ker(grid, block, ...)  # launch it
```
My understanding for a working prototype is that behind the scene we should do something equivalent of this for users:
```python
if '#include <limits.h>' in my_bad_code: 
    # jitsafe_header_limits_h is a string read from jitify.hpp
    my_bad_code = my_bad_code.replace('#include <limits.h>', jitsafe_header_limits_h)
elif '...' in my_bad_code:
    ...
```
then pass the processed string to NVRTC and compile it. Do I miss or misunderstand anything here? (I hope the Python part is not too confusing 🙂)

**Comment by maddyscientist** [comment]
@leofang if you're just wanting some of the headers provided by Jitify, you might be better looking at using libcu++'s headers: https://github.com/NVIDIA/libcudacxx/tree/main/include/cuda/std.

These are more fully featured, and are being continually expanded to provide more coverage of the the C++ standard library, as well as some C headers.

**Comment by leofang** [comment]
Hello @kkraus14 @harrism @devavret @emcastillo @jrhemstad @maddyscientist I sent a PR (#4228) to support Jitify in CuPy. Please feel free to comment there 🙂
