### ISSUE TITLE
Replace links for NumPy docs

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3418]
NumPy documentation is now hosted on numpy.org:

old: https://docs.scipy.org/doc/numpy/reference/routines.bitwise.html
new: https://numpy.org/doc/stable/reference/routines.bitwise.html

**Comment by Palash-Vishnani** [comment]
I can work on this issue. 
@kmaehashi can you tell me in which files do I have to replace the numpy documentation link.

**Comment by kmaehashi** [comment]
Thanks @Palash-Vishnani! Several files are still using the old link:
https://github.com/cupy/cupy/search?q=docs.scipy.org
