### ISSUE TITLE
Make undocumented APIs unvisible to users

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3420]

**Comment by kmaehashi** [comment]
I think it's better to make this v8 blocker?

**Comment by takagi** [comment]
Ah yes, please add this to the list.

**Comment by kmaehashi** [comment]
Thanks!

**Comment by takagi** [comment]
Note about `__all__` variable:
- `__all__` determines public names defined in a module when it is imported by `from ... import *` statement.
- It is optional to define `__all__`. If it is not defined, the set of public names of a module includes all names found in the module's namespace which do not begin with an underscore character.

**Comment by toslunar** [comment]
Revisited #2863 in the internal discussion.

**Comment by kmaehashi** [comment]
Discussed internally:
* Maintaining `__all__` list is costly (we need to double manage the list and the implementation, and it is likely to be forget updating the list)
* Current CuPy's `__init__.py` files has almost the same role as `__all__`, e.g. https://github.com/cupy/cupy/blob/master/cupy/binary/__init__.py (these imports are only for u
* We rather think black-list approach, i.e., name remove intermediate aliases and non-public imports (like `import sys` in `__init__.py`) by prefixing `_` (#2863) is better than `__all__`.

**Comment by takagi** [comment]
I tried some and found that, for example, `from cupy.manipulation.basic import copyto` in `cupy/__init__.py` loads `cupy.manipulation` and `cupy.manipulation.basic` as well, so just removing the intermediate alias `cupy.manipulation` does not look enough to hide CuPy's private submodules from users. We need to prefix each private submodule with `_` to conventionally hide it as #2944 does.

**Comment by takagi** [comment]
Let me make sure the goal of this issue:

a. Making them clear CuPy's public names that are imported by `form ... import *` statement

b. Keeping users off unexpectedly using CuPy's private submodules as `cupy.manipulation`

With just a., users can see `cupy.manipulation` after `import cupy`.

**Comment by takagi** [comment]
The remaining part to make corresponsing PRs is `cupy.cuda` submodule. I classified `cupy.cuda`'s submodules as following:

- Submodules seen on the reference
  - cupy.cuda.memory_hooks
  - cupy.cuda.texture
  - cupy.cuda.profiler
  - cupy.cuda.nvtx
  - cupy.cuda.nccl
  - cupy.cuda.runtime
- Submodules not seen on the reference
  - Wrappers for CUDA related libraries
    - Implemented under `cupy_backends`
      - cupy.cuda.cudnn
      - cupy.cuda.driver
      - cupy.cuda.cublas
      - cupy.cuda.curand
      - cupy.cuda.cusolver
      - cupy.cuda.cusparse
      - cupy.cuda.nvrtc
    - Implemented under `cupy`
      - cupy.cuda.cufft
      - cupy.cuda.cub
      - cupy.cuda.thrust
  - CuPy's own concepts
      - cupy.cuda.common
      - cupy.cuda.compiler
      - cupy.cuda.device
      - cupy.cuda.function
      - cupy.cuda.memory
      - cupy.cuda.memory_hook
      - cupy.cuda.pinned_memory
      - cupy.cuda.stream

Now we have the question that which submodules to be public and which to be private. I suppose that the following submodules are clearly to be public:
- Submodules seen on the reference
- Wrappers for CUDA related libraries

How about the rest of the submodules (CuPy's own concepts)?

**Comment by leofang** [comment]
I'd strongly prefer to keep all `cupy.cuda.*` as is, at least until we figure out how to deal with issues like #3597. There's no way that Numpy could possibly have a namespace like `numpy.cuda` that conflicts with ours, so I think it's safe to keep. Also, many functions are already made public/used by downstream. I think we document them.

**Comment by kmaehashi** [comment]
Discussed offline, as Leo said `cupy.cuda.*` APIs are frequently used although undocumented, so let's keep them as is for now.

**Comment by leofang** [comment]
Yeah I think a lot of `cupy.cuda` utilities are documented here: https://docs.cupy.dev/en/latest/reference/cuda.html

**Comment by kmaehashi** [comment]
This can be closed now? 😄 @takagi

**Comment by takagi** [comment]
Yes!
