### ISSUE TITLE
Mapped memory functionality (zero-copy)

### ISSUE THREAD

**Issue by mnicely** [cupy/cupy#3452]
Does CuPy have an implementation of _numba.cuda.mapped_array_ (https://numba.pydata.org/numba-doc/dev/cuda-reference/memory.html)

The idea is to use zero-copy on Jetson devices. 

An example, let's say I loaded a 2GB file into the global memory space of a TX2. I want to give the GPU access to the data without make a deep copy.
https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#zero-copy

**Comment by mnicely** [comment]
Pulling on that thread some more, I'm wondering if I using the CuPy pinned memory correctly. Below is a screenshot compare CuPy and Numba to pin memory. The CuPy is taking twice as long.

![numba_vs_cupy_pinned](https://user-images.githubusercontent.com/50021634/85127873-3fe4f300-b1fe-11ea-8570-b264d35df428.png)

### CuPy code
```python
# https://github.com/cupy/cupy/blob/master/examples/stream/cupy_memcpy.py
def _pin_memory(array):
    mem = cp.cuda.alloc_pinned_memory(array.nbytes)
    ret = np.frombuffer(mem, array.dtype, array.size).reshape(array.shape)
    ret[...] = array
    return ret


def get_pinned_array(size, dtype):
    pinned_memory_pool = cp.cuda.PinnedMemoryPool()
    cp.cuda.set_pinned_memory_allocator(pinned_memory_pool.malloc)

    x_cpu_dst = np.empty(size, dtype)
    x_pinned_cpu_dst = _pin_memory(x_cpu_dst)

    return x_pinned_cpu_dst

buffer = cusignal.get_pinned_array(binary.shape, cp.ubyte)
```

### Numba code
```python
def get_shared_mem(shape, dtype=np.float32, strides=None, order='C', stream=0,
                   portable=False, wc=True):
    return cuda.mapped_array(shape, dtype=dtype, strides=strides, order=order,
                             stream=stream, portable=portable, wc=wc)

buffer = cusignal.get_shared_mem(binary.shape, cp.ubyte)
```

**Comment by leofang** [comment]
@mnicely I think for the CuPy code you allocated host memory twice. You shouldn't need the line `x_cpu_dst = np.empty(size, dtype)` in `get_pinned_array()` and should just allocate the memory directly using `cp.cuda.alloc_pinned_memory()`. I think it's why it took twice as long.

**Comment by mnicely** [comment]
Thanks! I'll give it a shot.
Did you have any feedback on mapping the pinned memory?

**Comment by mnicely** [comment]
Actually, I might be able to do it manually with the `cupy.cuda.runtime.*` calls.

From programming guide.
>A block of page-locked host memory can also be mapped into the address space of the device by passing flag cudaHostAllocMapped to cudaHostAlloc() or by passing flag cudaHostRegisterMapped to cudaHostRegister(). Such a block has therefore in general two addresses: one in host memory that is returned by cudaHostAlloc() or malloc(), and one in device memory that can be retrieved using cudaHostGetDevicePointer() and then used to access the block from within a kernel.

**Comment by mnicely** [comment]
Using the following I'm still able to recreate the issue.
1. Each additional time I call `get_pinned_mem`, `cudaFreeHost` is ran during `set_pinned_memory_allocator`
2. Numba `cuMemHostAlloc` is averaging 50ms and CuPy's `cudaHostAlloc` averaging 80-100ms

```python

def get_pinned_mem(shape, dtype):
    pinned_memory_pool = cp.cuda.PinnedMemoryPool()
    cp.cuda.set_pinned_memory_allocator(pinned_memory_pool.malloc)
    mem = cp.cuda.alloc_pinned_memory(shape[0])
    ret = np.frombuffer(mem, dtype, shape[0])

    return ret
```
Sorry if I'm missing something obvious :confused:

**Comment by mnicely** [comment]
Okay, removing these two lines help greatly
```python
    pinned_memory_pool = cp.cuda.PinnedMemoryPool()
    cp.cuda.set_pinned_memory_allocator(pinned_memory_pool.malloc)
```

**Comment by mnicely** [comment]
I've been back and forth on what I _can_ do and what I _should_ do. Is there a way to change an attribute in the default pinned memory pool? I guess is the default flag is `cudaHostAllocDefault` but I'd like to be able to change it to `cudaHostAllocMapped`, in some scenarios.

I'm trying to avoid writing my own allocator and memory management if I don't need to.

**Comment by mnicely** [comment]
I've been digging into `pinned_memory.pyx` to get a better understanding how CuPy is creating a memory pool.

Does this workflow look correct?
1. Create PinnedMemory class with Mapped attribute
`mem = cp.cuda.PinnedMemory(size, cp.cuda.runtime.hostAllocMapped)`
2. Create PInnedMemoryPointer (allocator)
`pmp = cp.cuda.PinnedMemoryPointer(mem, 0)`
3. Create PinnedMemoryPool
`ppm = cp.cuda.PinnedMemoryPool(pmp)`
4. Set new allocator
`cp.cuda.set_pinned_memory_allocator(pmp)`

But when I try to run 
`mem = cp.cuda.alloc_pinned_memory(data.nbytes)`
it's erroring out
```bash
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cusignal-0.15.0a0+181.gba62649.dirty-py3.8.egg/cusignal/utils/arraytools.py", line 92, in get_pinned_array
    mem = cp.cuda.alloc_pinned_memory(data.nbytes)
  File "cupy/cuda/pinned_memory.pyx", line 201, in cupy.cuda.pinned_memory.alloc_pinned_memory
  File "cupy/cuda/pinned_memory.pyx", line 215, in cupy.cuda.pinned_memory.alloc_pinned_memory
TypeError: 'cupy.cuda.pinned_memory.PinnedMemoryPointer' object is not callable
```

**Comment by leofang** [comment]
Hi @mnicely Sorry I dropped the ball here...Not sure if this short snippet would help answer your questions? 
```python
import cupy
from cupy.cuda import PinnedMemory, PinnedMemoryPointer, PinnedMemoryPool
from cupy.cuda import runtime

import numpy as np


# analogous to cupy.cuda.pinned_memory._malloc()
def mapped_malloc(size):
    mem = PinnedMemory(size, runtime.hostAllocMapped)
    return PinnedMemoryPointer(mem, 0)


mapped_pinned_mem_pool = PinnedMemoryPool(mapped_malloc)

# do this if wanna have a memory pool...
cupy.cuda.set_pinned_memory_allocator(mapped_pinned_mem_pool.malloc)
# ...otherwise do this to always call hostAlloc()
cupy.cuda.set_pinned_memory_allocator(mapped_malloc)


# either way, the memory can now be allocated:
mem = cupy.cuda.alloc_pinned_memory(8*100)
# ...then wrap it with numpy and it's ready to use
a = np.ndarray((100,), dtype=np.float64, buffer=mem)
a[...] = np.arange(100, dtype=np.float64)
print(a)
```

**Comment by mnicely** [comment]
Thanks @leofang. Everything is working except one detail.
With the custom memory pool above, `cupy.cuda.alloc_pinned_memory(data.nbytes)` is running `cudaHostAlloc` each time.
But it doesn't do this with the default memory pool. :thinking:

**Comment by mnicely** [comment]
Wait... I think I got it. If I run `del buffer` on the pinned memory I get back some available blocks! 
I'm just not sure why I need to delete sometimes but not others...

Thanks for your help, as always!!

**Comment by leofang** [comment]
Interesting...I wonder if life would be easier if you allocate a large buffer then delete it. 

I had a wrong impression that we could set the pool size and have the allocation done in the beginning, but I checked both the doc and the source again and it doesn't seem possible...

**Comment by kmaehashi** [comment]
Implemented via #4870.
https://docs.cupy.dev/en/latest/reference/ext.html#cupy-specific-functions

**Comment by eedalong** [comment]
@mnicely So is there any manual on how to use mapped pinned memory in cupy like  `mapped_array` in numba? Thx!

**Comment by leofang** [comment]
@eedalong See https://docs.cupy.dev/en/stable/user_guide/memory.html#memory-management. There's [`cupyx.empty_pinned()`](https://docs.cupy.dev/en/stable/reference/generated/cupyx.empty_pinned.html#cupyx.empty_pinned) etc for allocating NumPy arrays backed by pinned memory. However, this may or may not meet your need.

Specifically, pinned memory in CUDA can be allocated with 3 flags: (portable, mapped, wc), see the doc for [`cuMemHostAlloc`](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1g572ca4011bfcb25034888a14d4e035b9) for detail. Here's the defaults used by the cupyx helpers and `numba.mapped_array()`:
- cupyx: (True, False, False) (no way to change)
- numba: (False, True, False) (portable and wc can be changed)

The cupyx API can be extended if needed, but currently there's no plan. If you find it mission critical, please open a new issue to request this feature.

**Comment by mnicely** [comment]
@eedalong Maybe you're wanting this??

```python
def get_pinned_array(data):
    """Return populated pinned memory.
    Parameters
    ----------
    data : cupy.ndarray or numpy.ndarray
        The array to be copied to shared buffer
    strides: int or None
    order: char
    """

    mem = cp.cuda.alloc_pinned_memory(data.nbytes)
    ret = np.frombuffer(mem, data.dtype, data.size).reshape(data.shape)
    ret[...] = data

    return ret

def mapped_malloc(size):
    mem = cp.cuda.PinnedMemory(size, cp.cuda.runtime.hostAllocMapped)
    return cp.cuda.PinnedMemoryPointer(mem, 0)

# Create custom memory pool
mapped_pinned_mem_pool = cp.cuda.PinnedMemoryPool(mapped_malloc)
cp.cuda.set_pinned_memory_allocator(mapped_pinned_mem_pool.malloc)

npbuffer = np.empty(<shape>, cp.ubyte)

buffer = get_pinned_array(npbuffer)
```

It's been awhile since I tried this, so please test

**Comment by eedalong** [comment]
@mnicely Thx! So I can pass this `buffer` to a `cupy.RawModule` directly for kernel execution right?

**Comment by eedalong** [comment]
> https://docs.cupy.dev/en/stable/user_guide/memory.html#memory-management

Thx! I'll check this out

**Comment by eedalong** [comment]
@mnicely @leofang 
I found an interesting way to use mapped memory with the help of numba
indptr = np.ones([100000, 602], dtype=np.int64)
indptr_mapped = numba_cuda.mapped_array(indptr.shape, dtype=indptr.dtype, strides=None, order='C', stream=0, portable=False, wc=False)
cupy_mapped_array = cupy.asarrray(indptr_mapped)
