### ISSUE TITLE
Batch Solving in cupy.linalg.eigh

### ISSUE THREAD

**Issue by electronsandstuff** [cupy/cupy#3454]
The interface to numpy's hermitian eigenvalue solver `numpy.linalg.eigh` may accept an (n, m, m) array for batch calculations.  CuSOLVER has the corresponding functions `cusolverDnSsyevjBatched`, `cusolverDnDsyevjBatched`, `cusolverDnCheevjBatched`, and `cusolverDnZheevjBatched`.  It seems like it would be a good idea to generalize cupy's interface to match what numpy has.  I have never contributed to cupy, but have made similar changes to a julia GPU library.  Is this a good feature to add and would this be a good first time PR for me to make?  I have a need for a function like this and so I have some motivation to get it done.

**Comment by grlee77** [comment]
I would find it useful.

The cuSOLVER functions could be added to the existing ones in `cupy/cuda/cusolver.*`. There is some precedence for other batched functions there.

It actually looks like we don't currently have the non-batched `syevj` versions either and are using the `syevd` solver instead. I had to look up in the NVIDIA docs to remember the difference between `syevd` and `syevj`:

> "syevj has the same functionality as syevd. The difference is that syevd uses QR algorithm and syevj uses Jacobi method. The parallelism of Jacobi method gives GPU better performance on small and medium size matrices. Moreover the user can configure syevj to perform approximation up to certain accuracy. "

**Comment by kmaehashi** [comment]
We welcome contribution for this feature.
Steps:
1. add implementation in `cupy.cuda.cusolver`
2. add implementation in `cupy.cusolver`
3. use `cupy.cusolver` in `eigh`

See https://github.com/cupy/cupy/pull/3247 which would be an example for 1 and 2.

For record: cusolverDnSsyevjBatched, cusolverDnDsyevjBatched, cusolverDnCheevjBatched, and cusolverDnZheevjBatched are first available in CUDA 9.0

**Comment by electronsandstuff** [comment]
Thanks!  I will take a look at it over the weekend.

**Comment by kmaehashi** [comment]
@electronsandstuff FYI, @dmargala just contributed `cusolverDn<t>syevjBatched` implementation in  https://github.com/cupy/cupy/pull/3488.

**Comment by electronsandstuff** [comment]
> @electronsandstuff FYI, @dmargala just contributed `cusolverDn<t>syevjBatched` implementation in #3488.

That should make this addition easy.  I changed the cupy.linalg.eigh unit test to check for batched eignsolving, but I suppose that I will wait until #3488 is merged before moving on.

**Comment by yoshipon** [comment]
Hi! I already have a personal code that extends CuPy to calculate eigh with syevjBatched.
@electronsandstuff If you like, I will make a PR to merge my code after #3488 is merged.

**Comment by electronsandstuff** [comment]
Sweet!  If you have some code already written, then it's all yours.

**Comment by leofang** [comment]
This can be closed.
