### ISSUE TITLE
[DOC] Bad 'See also' for ndarray.tofile

### ISSUE THREAD

**Issue by mnicely** [cupy/cupy#3455]
The `See also` for ndarray.tofile is pointing to `tolist`.

https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.ndarray.html

**Comment by leofang** [comment]
https://github.com/cupy/cupy/blob/a6c71a0c8004d89e5a51daa03f503932cf15c206/cupy/core/core.pyx#L323-L326
