### ISSUE TITLE
Functionality to print nvcc and nvrtc output

### ISSUE THREAD

**Issue by mnicely** [cupy/cupy#3482]
```bash
CuPy Version          : 8.0.0b3
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10020
CUDA Driver Version   : 11000
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : None
cuDNN Version         : None
NCCL Build Version    : None
NCCL Runtime Version  : None
CUB Version           : Enabled
cuTENSOR Version      : None
```

I'm trying to get some register spillage information of some CuPy raw kernels. Unfortunately, the compiler fails on `-Xptxas`.
https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#phase-options

```python
module = cp.RawModule(
    code=cuda_code,
    backend='nvcc',
    options=("-std=c++11", "-use_fast_math", "-lineinfo", '-Xptxas -warn-spills'),
)
```

**Comment by leofang** [comment]
Just a thought: try splitting the string into two:
```python
    options=(..., '-Xptxas', '-warn-spills'),
```
I am guess `subprocess` is the unhappy guy.

**Comment by mnicely** [comment]
That removed error! :smile:
But no output :confused: 
Added `-v` to try and force verbose, but no luck.

```python
module = cp.RawModule(
    code=cuda_code,
    backend='nvcc',
    options=("-std=c++11", "-use_fast_math", "-lineinfo", '-Xptxas', '-v -warn-spills'),
)
```

**Comment by leofang** [comment]
Is the output written to stderr?

**Comment by mnicely** [comment]
So I think I need to output from below. If I understand the correctly to output should be in stdout.
```python
def _run_nvcc(cmd, cwd):
    try:
        return subprocess.check_output(cmd, cwd=cwd, stderr=subprocess.STDOUT)
```

I'm rebuilding CuPy with this to see if I can see stdout. I'll know in a few minutes.
``` python
dump = _run_nvcc(cmd, root_dir)
print(dump)
```

**Comment by leofang** [comment]
OK yeah it's the right place to change. And note that you don't need rebuild: it's a Python file, so you just change it and rerun! I was also bothered that the warning messages from nvcc aren't printed out, so if you have a good way to handle this we can work out a PR together.

**Comment by mnicely** [comment]
That worked! Although the formatting is quite off.
I'm going to see what I can do to fix formatting and do some thinking on how to do this cleanly.

I'll submit a PR with some suggestions :smile:

**Comment by mnicely** [comment]
@leofang I think the fix can be quite simple
Maybe we add to `RawModule` and/or `RawKernel` like _verbose_. 

Then in `compiler.py`
```python
def _run_nvcc(cmd, cwd, verbose=False):
    try:
        temp = subprocess.check_output(cmd, cwd=cwd, stderr=subprocess.STDOUT, universal_newlines=True)
        if verbose is True:
            print(temp)
        return temp
```

Let me know what you think.

**Comment by leofang** [comment]
#3485 is in! This can be closed now.
