### ISSUE TITLE
Reason for inclusion of NumPy license?

### ISSUE THREAD

**Issue by alexbw** [cupy/cupy#350]
Hi all, thanks for the great library. What is the reason for inclusion of both the MIT and NumPy license? Is it because there are some files that borrow implementation details from NumPy, or is it just because CuPy uses the NumPy interface?

**Comment by okuta** [comment]
This project is made with reference to NumPy. In particular, there are parts of documents and implementations that are copies or rewrites of NumPy. Therefore, we decided to include NumPy's license.

**Comment by okuta** [comment]
Do you have additional question or idea? May I close this PR?

**Comment by alexbw** [comment]
Ah, yes. My understanding is there are not *single* *files* that should use
the NumPy or CuPy license separately, but that most files are in some way
affected by both licenses. No need to keep the PR open.

**Comment by okuta** [comment]
OK, Thanks.
