### ISSUE TITLE
Support batched slogdet

### ISSUE THREAD

**Issue by yoshipon** [cupy/cupy#3522]
Thank you for developing CuPy, which helps my signal processing research very much.

The current `slogdet` is implemented to compute one-by-one for each matrix.
I already have a personal code that calculates `slogdet` in a batched manner by using `sgetr*Batched`.
Can I make PR about this extension?

**Comment by yoshipon** [comment]
I'm sorry, I was looking old version (7.x) of CuPy.
I realized that the current version already has a batched `slogdet` with cuSolver instead of `sgetr*Batched`

The current implementation, however, seems only supports matrices with real numbers.
`sgetr*Batched` can handle complex numbers in addition to real numbers.

**Comment by emcastillo** [comment]
Feel free to send a PR using your approach for complex numbers 😄

**Comment by yoshipon** [comment]
Thank you :)

I also found that the problem is only in the `slogdet` function and `_lu_factor`, which is called in the function, already supports complex numbers with `sgetr*Batched`.
I'll try to make a PR to fix it.
