### ISSUE TITLE
timing kernels with cupyx.time.repeat requires specifying a name

### ISSUE THREAD

**Issue by grlee77** [cupy/cupy#3527]
I have a question about convenience when using `cupyx.time.repeat` with kernels such as a `ReductionKernel` or `ElementwiseKernel`. Unless the user specifies something like `name=kernel.name` as an argument to `repeat`, it will fail when trying to access a non-existant `__name__` attribute.

Having to specify the name manually is a little inconvenient. What do you think about any of the following solutions?:

1.) try falling back to a `.name` attribute
2.) fall back to a default name (e.g.  `name=''"` or `name="unknown"`)
3.) add a `__name__` attribute to `_AbstractReductionKernel`, `ElementwiseKernel`, etc. 

minimal example:

```Python
import cupy
from cupyx.time import repeat

x = cupy.arange(8)
e = cupy.core.ElementwiseKernel('X x', 'Y y', '2 * x', 'doubler')
repeat(e, (x,))
```

```Python
Traceback (most recent call last):

  File "<ipython-input-11-2afc789db431>", line 6, in <module>
    repeat(e, (x,))

  File "/home/lee8rx/my_git/pyir/cupy/cupyx/time.py", line 53, in repeat
    name = func.__name__

AttributeError: 'cupy.core._kernel.ElementwiseKernel' object has no attribute '__name__'
```

**Comment by leofang** [comment]
I encountered the same error too, though I don't remember if the use case was the same. +1
