### ISSUE TITLE
Add docs to build cub module in Ubuntu 16.04 / RHEL 7

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3530]
After merging #2584, Ubuntu 16.04 users will need to:

```
$ sudo add-apt-repository ppa:ubuntu-toolchain-r/test
$ sudo apt update
$ sudo apt install g++-6
```

and `export NVCC="nvcc --compiler-bindir gcc-6"` to build CuPy from source.

The apt part needs to be documented. Maybe we can detect gcc version in `setup.py` and automatically set NVCC appropriately?

**Comment by leofang** [comment]
RHEL 7 users will also need to know they need more recent gcc (than the default 4.8.5), see https://github.com/cupy/cupy/issues/2530#issuecomment-657103420. This is needed to build both Thrust and CUB support.

**Comment by leofang** [comment]
@kmaehashi We might as well simply require all host compliers to be C++11 compliant and mention no reference to CUB or Thrust, since we need a C++11 compiler not only at build time for them, but also at runtime for recent big PRs like #3244 and #3505.

**Comment by kmaehashi** [comment]
@leofang 
I added the gcc-6 requirement to install guide, without mentioning CUB or Thrust.
Just saying "C++11 compliant compiler is required" is not enough to build CuPy. gcc-4/5 supports C++11 (somewhat incompletely) https://gcc.gnu.org/projects/cxx-status.html#cxx11

@asi1024 Could you mention the runtime host compiler requirement when writing docs for CUDA_ACCERELATOR?

**Comment by kmaehashi** [comment]
Refs #3586.

Please also update the link `:docs:environment:` in the installation guide to your documentation

**Comment by leofang** [comment]
Yeah gcc 4.x series is not ok with full C++11 support...
