### ISSUE TITLE
Guidance regarding downstream package naming and development

### ISSUE THREAD

**Issue by grlee77** [cupy/cupy#3531]
### **Summary**

I have few questions for the CuPy team (and RAPIDS/NVIDIA folks) regarding package naming and future plans regarding GPU n-dimensional image processing support. Please let me know if there is a better forum to raise this and feel free to invite others who may be interested to the discussion.

cc'ing a few PFN/NVIDIA/etc. folks who seem to have been interested/involved in past image-processing discussions:
@anaruse, @asi1024, @not522, @takagi, @mnicely, @jakirkham, @leofang

Also, @coderforlife for his great recent contributions to CuPy in this area! 

I have briefly mentioned a [cupyimg](https://github.com/mritools/cupyimg) package that I have been developing in recent months a few times (most recently https://github.com/cupy/cupy/issues/3526#issuecomment-652604895).  `cupyimg` covers some additional `scipy.ndimage` functions and a substantial subset of `scikit-image`. I am planning to continue helping to port some existing NumPy/SciPy functions from `cupyimg` over to this repository as time permits so that they can benefit from reviewer feedback and CI testing. The plan is to eventually remove those from `cupyimg` and mainly cover the `scikit-image` API.

### **A few questions I would like feedback on:**

1.) Does PFN have a problem with the `cupyimg` name for the package? (I have not released it on PyPI yet and could change the name if needed). Specifically, is the term "cupy" trademarked by PFN and discouraged for use within the name of any downstream modules?  I think it is clear from the organization where `cupyimg` is hosted and the README that this is not an official PFN project, but don't want to cause issues if the team here feels there is potential for confusion.

2.) My understanding is that CuPy itself intends to only cover NumPy and SciPy functions, but not expand to other scientific packages such as scikit-image, scikit-learn, etc?

3.) If the package evolved to contain mainly scikit-image functionality, that would seem to fit the pattern of RAPIDS proving packages mirroring the API of other popular scientific packages: e.g. cusignal vs. scipy.signal,  cuML vs. scikit-learn, etc. Are there already existing plans within the RAPIDS team to create a CUDA equivalent to scikit-image? I was thinking of potential ways to obtain official funding to do this and wondered if there is potential for future collaboration in that direction?

I think there is a lot of potential in the area of n-dimensional image processing on the GPU that is not currently well covered by other packages (e.g. [ITK](https://ITK.org) is nD, but has limited GPU capabilities while the Java+OpenCL-based [CLIJ](https://clij.github.io/) has good GPU support but is more limited in the dtypes supported and seems to be 2D/3D only).

**Comment by leofang** [comment]
cc: @kkraus14 @awthomp @ke-zhang-rd

**Comment by jakirkham** [comment]
cc @quasiben

**Comment by kkraus14** [comment]
cc @datametrician

**Comment by datametrician** [comment]
I love this idea. I know @jakirkham would also appreciate this.
We'd also be willing to house this in the [RAPIDS Github](https://github.com/rapidsai) unless PFN wants to be the home of it.

I'm personally partial to cuImage, but that's just because it follows the RAPIDS simply naming convention. RAPIDS also has no plans to do this, but like cuSignal, we had no plans until @awthomp just did it.

**Comment by grlee77** [comment]
@datametrician, Thank you for the kind offer! I have some questions regarding the logistics of hosting at RAPIDS:

1.) I assume that if the project were hosted under RAPIDS, this would provide access to NVIDIA hardware for CI testing, etc. Would there be support from the RAPIDS team to help get CI, documentation and wheel builds configured similarly to other existing projects?

2.) What constraints/requirements would hosting under RAPIDS impose on the project? e.g.
   - how would commit rights work (would PRs require sign-off from an existing RAPIDS team member?)
   - are there specific requirements for release timetables, etc?
   - require a common code of conduct with issues to be reported to the RAPIDS team?

Clearly, hosting at RAPIDS would increase visibility and having CI testing would be very valuable. I am just trying to get a better idea of what the other implications would be.

I just sent an email to other scikit-image maintainers for awareness and feedback and am cc'ing a few who may be interested here as well: @stefanv, @jni, @emmanuelle

**Comment by kmaehashi** [comment]
> We'd also be willing to house this in the RAPIDS Github unless PFN wants to be the home of it.

Great! I think RAPIDS organization is the best place to host it.

> 1.) Does PFN have a problem with the cupyimg name for the package? (I have not released it on PyPI yet and could change the name if needed). Specifically, is the term "cupy" trademarked by PFN and discouraged for use within the name of any downstream modules? I think it is clear from the organization where cupyimg is hosted and the README that this is not an official PFN project, but don't want to cause issues if the team here feels there is potential for confusion.

If the project is hosted as a part of RAPIDS, I think the name "cuImage" better fits with other products, as suggested by @datametrician. Regarding the trademark, let me confirm after the hosting discussion has been settled.

> 2.) My understanding is that CuPy itself intends to only cover NumPy and SciPy functions, but not expand to other scientific packages such as scikit-image, scikit-learn, etc?

Yes.

**Comment by grlee77** [comment]
> If the project is hosted as a part of RAPIDS, I think the name "cuImage" better fits with other products, as suggested by @datametrician. 

I agree this is a good name and matches RAPIDS naming conventions. It would also make the "CuPy" trademark question moot.

So far, I have received one +1 response and no objections from the scikit-image team regarding hosting under the RAPIDS organization (as opposed to the scikit-image organization).

**Comment by datametrician** [comment]
> @datametrician, Thank you for the kind offer! I have some questions regarding the logistics of hosting at RAPIDS:
> 
> 1.) I assume that if the project were hosted under RAPIDS, this would provide access to NVIDIA hardware for CI testing, etc. Would there be support from the RAPIDS team to help get CI, documentation and wheel builds configured similarly to other existing projects?
If it's hosted in RAPIDS we would provide CI and docs would be similar to https://docs.rapids.ai/api/cudf/stable/
One thing to note is RAPIDS is conda only for now, and wheels would not be something we'd help with
> 2.) What constraints/requirements would hosting under RAPIDS impose on the project? e.g.
> 
> * how would commit rights work (would PRs require sign-off from an existing RAPIDS team member?)
We could whitelist you and over time give you commit rights
> * are there specific requirements for release timetables, etc?
https://docs.rapids.ai/maintainers plus we have boards for each project such as https://github.com/rapidsai/cudf/projects/21
> * require a common code of conduct with issues to be reported to the RAPIDS team?
Yes... https://docs.rapids.ai/resources/conduct/ is the link for all our projects

**Comment by grlee77** [comment]
@datametrician: I am in favor of the `RAPIDS/cuImage` approach. Thank you for answering my questions, above. 

Can somebody from the RAPIDS team contact me regarding the next steps for pursuing this? I can be reached via the email in my profile.

**Comment by datametrician** [comment]
@jakirkham @kkraus14 would you like to shepherd this?

**Comment by kkraus14** [comment]
Will send an email to kickstart this in the near future. cc @mike-wendt for his visibility as well

**Comment by grlee77** [comment]
> Will send an email to kickstart this in the near future. cc @mike-wendt for his visibility as well

Great! 

I am closing this issue as resolved.

We did not end up resolving the general CuPy trademark question, but it will no longer apply in this case given the proposed `cuImage` package name.
