### ISSUE TITLE
cupy.around gives wrong output for complex argument

### ISSUE THREAD

**Issue by joris-lab** [cupy/cupy#3532]
cupy.around gives the correct output for real arguments, but incorrect output for complex arguments:

```python
import cupy as cp
import numpy as np

print(cp.around(0.1234567,decimals=4))
print(np.around(0.1234567,decimals=4))

print(cp.around(0.1234567+0.1234567j,decimals=4))
print(np.around(0.1234567+0.1234567j,decimals=4))
```

Output:
```
0.1235
0.1235
(0.12350000000000001+0.12350000000000001j)
(0.1235+0.1235j)
```
Note that I am not giving an cupy array as input.
____
I'm using version cupy-cuda101==6.5.0

**Comment by kmaehashi** [comment]
This is considered by-design. We don't guarantee exact output match with NumPy in terms of floating point accuracy. See also: https://docs.nvidia.com/cuda/floating-point/index.html

This is one of FAQ and needs to be documented in https://docs.cupy.dev/en/stable/reference/difference.html
