### ISSUE TITLE
cupy-cuda101 windows wheel package error

### ISSUE THREAD

**Issue by royqh1979** [cupy/cupy#3541]
I'm using Python 3.7 on windows 10.
After installing cupy using "pip install cupy-cuda101"
When I run the following code:
```
import cupy as cp
import time

x_gpu = cp.random.uniform(0,1,(400,1000,1000))
```
I got the error:

```
AttributeError: module 'cupy' has no attribute 'random'
```

And browsing the cupy library dir, I found that it don't have the random folder.

And cupy-cuda102 wheel is fine.

So it's there anything wrong with the cupy-cuda101's windows wheel?

**Comment by emcastillo** [comment]
First, do you have cuda 10.2 installed in your system and added to the `CUDA_PATH` and other paths for cupy to find it?

What does `cupy.show_config()` shows.?

**Comment by kmaehashi** [comment]
I think you have multiple CuPy packages installed.
Try:
  1. `pip list` to list find all CuPy packages installed (`cupy` and `cupy-cuda*`)
  2. `pip uninstall <package name>` to uninstall all CuPy packages found
  3. `pip install <package name>` to install the proper one

**Comment by kmaehashi** [comment]
I checked v7.6.0/v8.0.0b4 wheels and they contained `cupy/random` directory.

**Comment by royqh1979** [comment]
> I think you have multiple CuPy packages installed.
> Try:
> 
> 1. `pip list` to list find all CuPy packages installed (`cupy` and `cupy-cuda*`)
> 2. `pip uninstall <package name>` to uninstall all CuPy packages found
> 3. `pip install <package name>` to install the proper one

Maybe that's the reason.
I have both cupy from https://www.lfd.uci.edu/~gohlke/pythonlibs/ and cupy-cudaxxx from pypi installed.
