### ISSUE TITLE
Detect wrong installation (duplicate wheels) and warn 

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3552]
Refs: #3541

https://github.com/chainer/chainer/blob/e8283065bc706447bf4f721122fc3e49f0a06ea1/chainer/_environment_check.py#L44

**Comment by leofang** [comment]
Is it possible to also detect if a source-build and a wheel coexist?

**Comment by kmaehashi** [comment]
> Is it possible to also detect if a source-build and a wheel coexist?

Yes, packages are named `cupy`  for source build and `cupy-cudaXXX` for wheels.

**Comment by leofang** [comment]
I think if a user does `pip install cupy` and then `pip install cupy-cudaXXX` (or vice versa), the second attempt should error out. I've been stumbled by this possible coexistence of wheel + source build several times...

**Comment by kmaehashi** [comment]
I understand that, but wheel installation is basically just a unzip and cannot run code. `pip install cupy` can run any code but unable to display a message to users because stdout/stderr is captured and discarded if the installation succeeds.
