### ISSUE TITLE
NVIDIA NCCL: 100% busy blocking.

### ISSUE THREAD

**Issue by xf3227** [cupy/cupy#3557]
I have a 4-GPU setup and recently try utilizing NVIDIA NCCL library to speed up inter-GPU communication. In the test program, 4 processes were created via Python multiprocessing module and each of them was assigned one GPU. I've managed to make nccl.allGather() function working. The communication speedup was definitely noticeable even without using timeit() to check.

When I intentionally let one process skip the allGather() step, the other 3 were blocked as expected, waiting for their allGather() function to return. The issue here is that nvidia-smi shown all those 3 GPUs were fully (i.e. 100%) occupied, although the temperature remained low. There are 3 assumptions I can come up with:

1. Such busy-looping behavior is shipped with NCCL library.
2. CuPy wrapper's problem?
3. nvidia-smi is not accurate.

CuPy version: 7.6.0
CUDA version: 10.2
NCCL version: 2506

**Comment by leofang** [comment]
It's most likely due to NCCL. All processes in the same communicator must participate in a collective call, otherwise deadlock happens (which is what you see).

**Comment by xf3227** [comment]
@leofang Thank you for the reply! I will post this issue under NCCL repo then.

**Comment by leofang** [comment]
Not sure why you'd like to move the issue to the NCCL repo, perhaps I wasn't being clear: Deadlocks are totally expected. It'd be wrong if no deadlock happens, and your usage of purposely leaving out a process in a collective call is abnormal (and buggy) in this sense.

**Comment by emcastillo** [comment]
Most likely the GPU is doing an active wait until the last process joins the collective, so I would say this is expected behavior.

**Comment by xf3227** [comment]
@leofang @emcastillo Thank you for the replies. I agree that it's not necessarily to be a bug or even an issue. I generally use GPU utilization to quickly assess the efficiency of my code, but with NCCL, even if I don't intentionally challenge it, all GPUs can simply be pushed to 100% with nccl.allGather() regardless of what the underlying computation is. Anyway, in terms of performance and GPU temperature, NCCL is efficient and has least communication overhead. I probably should have pretended to be blind on the utilization percentage XD.

**Comment by xf3227** [comment]
@leofang @emcastillo Although this thread is closed, I'd like to let you know that the 100% busy blocking was caused by my carelessness. The issue has now been perfectly solved by synchronizing the operating stream.
