### ISSUE TITLE
cupy.percentile only calculates integer percentiles when the input data is an integer.

### ISSUE THREAD

**Issue by pptman** [cupy/cupy#3568]
This seems to be caused by a cast of the percentiles array `q` to the same type as the input array `a` in the cupy.percentile source :

https://github.com/cupy/cupy/blob/adfcc44bc9a17886a340cd85b7c9ebadd94b38a1/cupy/statistics/order.py#L189

Example code to reproduce the issue:

`cupy.percentile(cupy.arange(1001).astype(cupy.int16),[98, 99, 99.9, 100]).get()`
`array([ 980.,  990.,  990., 1000.])`

`cupy.percentile(cupy.arange(1001).astype(cupy.float16),[98, 99, 99.9, 100]).get()`
`array([ 980.,  990.,  999., 1000.])`

For comparison the numpy version always calculates correctly:

`numpy.percentile(numpy.arange(1001).astype(numpy.int16),[98, 99, 99.9, 100])`
`array([ 980.,  990.,  999., 1000.])`

Cupy configuration:
CuPy Version          : 7.6.0
CUDA Root             : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020

**Comment by emcastillo** [comment]
Verified with

```
>>> numpy.percentile(numpy.arange(1001).astype(numpy.int16),[98, 99, 99.9, 100])
array([ 980.,  990.,  999., 1000.])
>>> cupy.percentile(cupy.arange(1001).astype(cupy.int16),[98, 99, 99.9, 100])
array([ 980.,  990.,  990., 1000.])
```
