### ISSUE TITLE
Change docs to reflect `cupy_backends`

### ISSUE THREAD

**Issue by emcastillo** [cupy/cupy#3581]
#3386 decoupled the cuda wrapping code from cupy.

We have to modify docs accordingly

**Comment by kmaehashi** [comment]
Related: https://github.com/cupy/cupy/issues/3597

**Comment by kmaehashi** [comment]
As the discussion in #3597 (splitting cuda_backends as a separate library) is ongoing, I think it's better not to change the user-facing interface immediately.
