### ISSUE TITLE
Reuse cufft plan objects

### ISSUE THREAD

**Issue by emcastillo** [cupy/cupy#3588]
Reusing a plan object have a significant impact in the complete fft performance. I measured a ~500us time drop.

We should try to create a `PlanAllocator` or a pool of plans to reuse objects according to the requested size.

(Plans allocate gpu memory so we have to be careful when reusing them).

CC @leofang @asi1024 @grlee77

**Comment by leofang** [comment]
Previous discussion was in #1669. @grlee77 mentioned he has a cache prototype. For the purpose of #3587 to speed up correlate/convolve, we should first focus on memoizing `Plan1d`, as it has less parameters to be used as the cache key.

**Comment by leofang** [comment]
PyTorch refs:
- usage: https://github.com/pytorch/pytorch/blob/master/docs/source/notes/cuda.rst#cufft-plan-cache
- implementation: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/CuFFTPlanCache.h

**Comment by emcastillo** [comment]
```
Because some cuFFT plans may allocate GPU memory, these caches have a maximum capacity.
```
That's what I was scared about 🙂

**Comment by leofang** [comment]
@emcastillo, I found @peterbell10 is working on exposing SciPy's pocketfft plan cache to the Python space (https://github.com/scipy/scipy/pull/12512). I think 
1. it is best to coordinate the efforts 
2. looks like we'll have to do this for the compatibility with SciPy, so it's no longer an optional thing in the future...
