### ISSUE TITLE
On how to enable users to use TF32 in CuPy

### ISSUE THREAD

**Issue by anaruse** [cupy/cupy#3602]
TensorCore, special hardware units executing matrix multiply operations, has been enhanced in the A100 GPU. One of the enhancements is the TF32 compute mode, in which inputs and outputs are still in F32 data type, but are internally converted to proprietary 19-bit floating point for fast matrix multiply. The results in TF32 compute mode are not exactly the same as the results in FP32, but it is much faster.

The CUDA11 libraries support the TF32 compute mode; for example, [cublasGemmEx](https://docs.nvidia.com/cuda/cublas/index.html#cublas-GemmEx), one of the matrix multiply subroutines in cuBLAS, uses the TF32 compute mode when the parameter computeType is [CUBLAS_COMPUTE_32F_FAST_TF32](https://docs.nvidia.com/cuda/cublas/index.html#cublascomputetype_t).

We would like to make this TF32 compute mode available in CuPy as well, so I hope we can discuss here specifically how we can make TF32 compute mode available to users.

We believe there are three levels of CUDA library use in CuPy.

1. directly call the thin wrapper of the C/C++ API of the CUDA libraries (e.g., [cupy_backends.cuda.libs.cublas.gemmEx](https://github.com/cupy/cupy/blob/78a83d71ed2518e7920c2bacd4e9c36b8381b45a/cupy_backends/cuda/libs/cublas.pyx#L1025)).
2. call a python routine that abstracts the C/C++ API of the CUDA libraries (e.g., [cupy.cutensor.contraction](https://github.com/cupy/cupy/blob/78a83d71ed2518e7920c2bacd4e9c36b8381b45a/cupy/cutensor.py#L351)).
3. use from Numpy/Scipy compatible subroutines (e.g., cupy.matmul, cupy.einsum).

As for 1., I don't think there is any need to discuss on it, as we just need to make it available in Cupy, TF32 compute mode related data types defined in each CUDA library.

As for 2., for example, in cupy.cutensor.contraction, you use numpy dtype to allow you to specify the compute mode, there is no TF32 in numpy dtype, so you need to do something about it.

As for 3., for example, you may call a subroutine of cuBLAS library in cupy.matmul, so you need to be able to specify in some way whether you want to use the TF32 compute mode there.

I think we should decide on a general policy before we start implementation.
What would you think on this?

**Comment by leofang** [comment]
Hi @anaruse, any chance you could comment on #3370? Someone suggested that TensorCores might help speed up `complex32` computations.

**Comment by kmaehashi** [comment]
We discussed in the team:

- Adding new dtype like `cupy.tf32` sounds inappropriate as the acutal array data format on memory is exactly the same as `cupy.float32`.
- Adding new keyword arguments to each routine (e.g, `cupy.matmul`) is a burden and should be avoided also in terms of compatibility with NumPy.
- We think the relationship between "float32" and "tf32" is similar to that of "cudnn disabled" and "cudnn enabled" in Chainer, so it is better to make it a configuration that users can opt-in, like environment variable `CUPY_TF32=1`.

**Comment by leofang** [comment]
> * Adding new dtype like `cupy.tf32` sounds inappropriate as the acutal array data format on memory is exactly the same as `cupy.float32`.

Why? Do I miss something? It doesn't look like so to me:
https://blogs.nvidia.com/wp-content/uploads/2020/05/tf32-Mantissa-chart-hi-res-FINAL.png

**Comment by kmaehashi** [comment]
https://blogs.nvidia.com/blog/2020/05/14/tensorfloat-32-precision-format/

> TF32 Tensor Cores operate on FP32 inputs and produce results in FP32.

I guess naruse-san intended to use this?

**Comment by leofang** [comment]
Ah I see, thanks @kmaehashi!

**Comment by kmaehashi** [comment]
TF32 implemented via #3810. Thanks @anaruse!
