### ISSUE TITLE
Document that contiguity match is not guaranteed

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3609]
Let's add it to this docs:

https://docs-cupy.chainer.org/en/latest/reference/difference.html

Current policy: We try to reproduce NumPy's contiguity behavior for the output array when it is "reasonably" possible (e.g., we won't do `cupy.asfortranarray` just to align the spec with NumPy).

**Comment by leofang** [comment]
Is #2717 related?

**Comment by kmaehashi** [comment]
Good catch!

**Comment by kmaehashi** [comment]
Fixed via #7344
