### ISSUE TITLE
tobytes in cupy.core.core.ndarray is missing on GPU memory

### ISSUE THREAD

**Issue by kryztoval** [cupy/cupy#3610]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy 6.0.0 (via miniconda)
  - Python 3.7.7
  - Windows 10 r2004 64 bits
  - CUDA version 10.0.130,  (cupy show config says: build 10000, Driver 11000, Runtime 10000)
  - no cuDNN, no NCCL
* Code to reproduce
```
import cupy

# Create an array in GPU memory and copy it to CPU memory and convert it to bytes
nd_array = cupy.random.randint(0,256,32,'<u1').get()

### This works
print(nd_array.tobytes())

# Create an array in GPU memory and try to convert it to bytes
nd_new_array = cupy.ndarray(32, 'uint8')
nd_new_array.set(nd_array)

### This fails
print(nd_new_array.tobytes())
```

```
b',\xec\x06R\x83\xddI\xb2os\xb9\xc2p\xa1\x1c\xc6o$\xc8\xd0\xe5\x16\xf8Fp,,oo\x96V\x1a'
Traceback (most recent call last):
  File "tobytes_test.py", line 8, in <module>
    print(nd_new_array.tobytes())
AttributeError: 'cupy.core.core.ndarray' object has no attribute 'tobytes'
```

While checking the versions I realized that conda in windows has cupy version 6.0 but I couldn't find any version higher than that. This may be fixed in a newer version of cupy, the provided code should make it easy to test if it works in a more recent version.

**Comment by emcastillo** [comment]
I confirmed this works in CuPy v7.
You can install the windows wheel using pip 😄

**Comment by kryztoval** [comment]
> You can install the windows wheel using pip

forcing a cuda version in pip worked. in mycase `pip install cupy-cuda100` worked while `pip install cupy===7.6.0` failed to install.

Thanks!
