### ISSUE TITLE
ufuncs are missing the accumulate, at, outer, reduce, and reduceat methods

### ISSUE THREAD

**Issue by coderforlife** [cupy/cupy#3637]
Title says it all. I have used the `outer` method several times of various ufuncs in numpy, I am sure the other ones are also useful in many cases.

**Comment by coderforlife** [comment]
I just found an old issue related to `add.at` at #1658 which is just one of the functions listed here. Thus, the following could are for a specific `ufunc` and if they could be adapted to any `ufunc` most of these would be completed:

* `cupyx.scatter_add` is the same as `add.at`, `cupyx.scatter_max` is the same as `maximum.at`, `cupyx.scatter_min` is the same as `minimum.at`
* `cumsum` is the same as `add.accumulate` and `cumprod` is the same as `multiply.accumulate`
* `sum` is the same as `add.reduce` and `prod` is the same as `multiply.reduce`
* `outer` is the same as `multiply.outer`

The only one missing is `reduceat` but even just getting 4 out of 5 by generalizing the above would be great.

**Comment by kmaehashi** [comment]
Thanks for the feature request! I'm closing the issue as #2552 covers this topic, let's continue discussing there.
