### ISSUE TITLE
Sparse argmin/argmax return scalar values on CPU

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#3640]
CuPy returns zero-dimensional ndarrays for reduction functions where NumPy/SciPy return scalar values to keep off synchronizing between GPU and CPU. However, CuPy's sparse matrix argmin/argmax currently return scalar values as SciPy's counterparts, causing device to host sync.

```Python
>>> import cupy
>>> import cupyx
>>> a = cupy.array([[0,1,0],[2,0,3]], dtype='f')
>>> cupyx.scipy.sparse.csc_matrix(a).argmin()
0
```

**Comment by dloney** [comment]
If I'm understanding correctly, the preferred behavior is for CuPy to return a (1, self.shape[0]) in this case? I'm happy to put together a pull request.

**Comment by takagi** [comment]
No, CuPy should return a zero-dimensional array `cupy.array(value)`, completing the computation on the GPU side as described [here](https://docs.cupy.dev/en/stable/reference/difference.html#reduction-methods). It would be nice if you post a pull request to fix it.
