### ISSUE TITLE
Installing from source - update documentation

### ISSUE THREAD

**Issue by Nicholas-Mitchell** [cupy/cupy#3648]
Given the new inclusion of CUB as a git sub-module, I believe the documentation for installing from source should be updated to reflect this.

```git clone --recurse-submodules https://github.com/cupy/cupy.git```

---

You will get an error if you follow the current instructions:

![image](https://user-images.githubusercontent.com/12820901/88259038-cc814600-ccc1-11ea-8748-957aa905c4ce.png)

**Comment by leofang** [comment]
The doc is already updated after we included CUB as a submodule, but before the official release is out you can only see that by switching to "latest" (it's at the bottom of the left panel):
<img width="1081" alt="截圖 2020-07-23 下午10 31 37" src="https://user-images.githubusercontent.com/5534781/88355986-64b81300-cd34-11ea-9a13-b21095618805.png">

**Comment by Nicholas-Mitchell** [comment]
That makes sense, thanks for clarifying.

Maybe you could use tags or commit names? Because cloning the basic link
(as per the current documentation) takes master branch at HEAD, so you get
cub, eben though it isn't part of the latest release.

**Comment by leofang** [comment]
The documentation does mention "development version". But, perhaps this doc change can be backported to the v7 branch, which is still under maintenance.
