### ISSUE TITLE
Document which routines support cub

### ISSUE THREAD

**Issue by emcastillo** [cupy/cupy#3692]
Right now, we support CUB based reduction, but some routines such as max, min, sum, or scan use some CUB special functions.

We should add a note to the docstring of such functions stating that cub acceleration is available.

**Comment by emcastillo** [comment]
> We can certainly mention that the main routines direct backed by CUB 

It would be great if in the docstring of these routines we add a note, saying it's backed by CUB.

Otherwise, the interface gives you options to accelerate things you don't know :)

**Comment by leofang** [comment]
I wonder changes along this line would be sufficient...? https://github.com/leofang/cupy/commit/57ee0a4d3292f986b7be679c4dcb77fa37705bd7
