### ISSUE TITLE
[Feature Request] Add support OpenCL

### ISSUE THREAD

**Issue by redradist** [cupy/cupy#3695]
It would be nice if CuPy was able to use OpenCL or CUDA language

**Comment by kmaehashi** [comment]
Could you elaborate more on what you mean by "OpenGL or CUDA language"?

**Comment by redradist** [comment]
> 
> 
> Could you elaborate more on what you mean by "OpenGL or CUDA language"?
> Do you want to use APIs like [cudaGraphicsGLRegisterBuffer](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__OPENGL.html#group__CUDART__OPENGL_1g0fd33bea77ca7b1e69d1619caf44214b)?

@kmaehashi I want to use OpenCL language to be able to run software on other Graphic modules

**Comment by leofang** [comment]
There's a CuPy-fork called "clpy" (https://github.com/fixstars/clpy), which uses OpenCL as the backend.

**Comment by redradist** [comment]
> 
> 
> There's a CuPy-fork called "clpy" (https://github.com/fixstars/clpy), which uses OpenCL as the backend.

@leofang Yes, I have seen it, but the reason that I wrote here is due to maintainability, this fork has 11000 commits as current cupy has 17000 ... This fork is little-bit outdated

**Comment by kmaehashi** [comment]
Let me close this issue as currently we don't have a plan to support OpenCL in the short/mid-term. Many parts of CuPy codebase heavily rely on CUDA API/semantics so introducing an OpenCL backend will require a huge design change and rewrite.
