### ISSUE TITLE
ValueError when loading .npy using np.load()

### ISSUE THREAD

**Issue by albertokjian** [cupy/cupy#3701]
The data stored has the following schema:
{ str: { key: ndarray, ... } }

Conditions:
CuPy Version          : 7.7.0
CUDA Build Version    : 10000
CUDA Driver Version   : 11000
CUDA Runtime Version  : 10000
cuBLAS Version        : 10000
cuFFT Version         : 10000
cuRAND Version        : 10000
cuSOLVER Version      : (10, 0, 0)
cuSPARSE Version      : 10000
NVRTC Version         : (10, 0)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2406
NCCL Runtime Version  : 2708
CUB Version           : None
cuTENSOR Version      : None

Code to reproduce:
```
import cupy as np
a = {'a': np.zeros((10,))}
np.save('a.npy', a)
b = np.load('a.npy', allow_pickle=True)
```

Error messages, stack traces, or logs:
Traceback (most recent call last):
  File ".../test.py", line 5, in <module>
    b = np.load('a.npy', allow_pickle=True)
  File ".../miniconda3/lib/python3.7/site-packages/cupy/io/npz.py", line 71, in load
    return cupy.array(obj)
  File ".../miniconda3/lib/python3.7/site-packages/cupy/creation/from_data.py", line 43, in array
    return core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/core/core.pyx", line 1785, in cupy.core.core.array
  File "cupy/core/core.pyx", line 1862, in cupy.core.core.array
  File "cupy/core/core.pyx", line 1936, in cupy.core.core._send_object_to_gpu
ValueError: Unsupported dtype object

The same code executes with no error with numpy instead of cupy.

**Comment by kmaehashi** [comment]
This is by design; CuPy does not support `dtype=object` arrays.

```py
a = {'a': np.zeros((10,))}
np.save('a.npy', a)
b = np.load('a.npy', allow_pickle=True)
```

The resulting array `b` is `dtype=object` in NumPy, which is (obviously) not supported in GPU.

```py
>>> b
array({'a': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])}, dtype=object)
```
