### ISSUE TITLE
Do not bundle cuDNN v8 for CUDA 10.1/10.2/11.0 packages

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3724]
We're now discussing removal of bundled cuDNN in CuPy wheels hosted on PyPI.
This is because cuDNN v8 is quite huge (1.5GB) and not reasonable to redistribute on our own.

This affects:
- CUDA 10.1/10.2 wheels for CuPy v8
- CUDA 11.0 wheels for CuPy v7 and v8

## Requirements

1. Load shared libraries placed outside of the package
2. (optionally) Provide means to download cuDNN automatically

### Requirement 1

- Before loading cupy_backends,
    - Find the library from search paths in the following order:
        - ~`cupy/_data/lib` (shared libaries bundled in wheels)~ *update: this is not needed as cuDNN binary is not located here*
        - `CUPY_LIBRARY_PATH` env var
        - default system search path
    - If the library is found, `dlopen` the library.
      Otherwise, show a warning (`please install the lib manually`) to users on the initial use of each library.

### Requirement 2

- Users run `python -m cupyx.utils.download_cudnn cuda_version`
- Download cuDNN binary to e.g. `~/.cupy/cuda_libs/{cuda_version}/{library_name}/{library_version}/lib/libcudnn.so.8.0.2`

If we provide this implementation, we should add `~/.cupy/cuda_libs/{cuda_version}/{library_name}/{library_version}/lib` to search path in requirement 1.

**Comment by emcastillo** [comment]
can we add https://github.com/unnonouno/cudnnenv as a requirement and call it from setup.py?

**Comment by kmaehashi** [comment]
> can we add https://github.com/unnonouno/cudnnenv as a requirement and call it from setup.py?

I come up with that idea too, but cudnnenv does not support Windows.
Also, wheel installations does not invoke `setup.py`, so cudnn download should be done by users (or maybe automatically by CuPy)

**Comment by leofang** [comment]
@jakirkham, I don't think Anaconda has packaged cuDNN v8, nor would this have impact to conda releases (conda's cuDNN would be found when searching "default system path"). Just FYI.

**Comment by jakirkham** [comment]
> @jakirkham, I don't think Anaconda has packaged cuDNN v8

That's sound right.

cc @kkraus14 @pentschev

**Comment by kmaehashi** [comment]
The preloading has been implemented in #3731.
