### ISSUE TITLE
AssertionError occurs for some reductions when CUB is enabled

### ISSUE THREAD

**Issue by grlee77** [cupy/cupy#3738]
I get some test suite failures in `cupyimg` when `CUPY_ACCELERATORS="cub,cutensor"` environment variable is set.

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
CuPy Version          : 8.0.0b5
CUDA Root             : /usr/local/cuda-10.2
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
Thrust Version        : 100907
CUB Build Version     : 100800
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2604
NCCL Runtime Version  : 2604
cuTENSOR Version      : 10001

* Code to reproduce

```Python
import cupy as cp
x = cp.arange(2*4*3).reshape((2, 4, 3), order='F')
x.max(-1)  # or x.max(1), but not for x.max(0) which is the contiguous axis
```

This gives the correct result, but prints:
```
AssertionError

Exception ignored in: 'cupy.cuda.cub._preprocess_array'
AssertionError
```

* Error messages, stack traces, or logs

**Comment by grlee77** [comment]
cc @leofang: I haven't looked into it yet, but thought you may know offhand what the issue is?

**Comment by leofang** [comment]
This looks suspicious to me...I need to look into why I added it in the first place.
https://github.com/cupy/cupy/blob/97573d737beefb7a9ae9f81c294a005ed475bf4f/cupy/cuda/cub.pyx#L106-L107

**Comment by leofang** [comment]
#3562 is to blame 😅
