### ISSUE TITLE
Make a copy for input when calling FFT on CUDA 10.1+

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3770]
#3763 adds a warning that inputs may be modified (because cuFFT performs in-place operation), but it's better to make a copy for input before calling cuFFT.

* Make a copy by default.
* Provide an option to avoid copy, e.g., `cupy.fft(..., *, overwrite_x=False)` for users needing performance. (using keyword argument as this is not numpy-compatible)

This feature is not to be backported to v7.

**Comment by leofang** [comment]
> * Make a copy by default.

I think we only need to do this for certain kinds of FFT (like C2R). I am digging into the docs.

**Comment by leofang** [comment]
If cuFFT aims to be interchangable with FFTW, then we only need to worry about C2R transforms (i.e., `irfft`, `irfft2`, `irfftn`). See https://github.com/cupy/cupy/issues/3736#issuecomment-672073361 and the [cuFFT documentation](https://docs.nvidia.com/cuda/cufft/index.html#data-layout):
> Note that in-place complex-to-real FFTs may overwrite arbitrary imaginary input point values when non-unit input and output strides are chosen. Out-of-place complex-to-real FFT will overwrite input buffer if custom strides are set by the user.
