### ISSUE TITLE
Deprecate `cupy.sparse` package

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#3773]
Rel #3420.

CuPy's sparse matrix feature was initially implemented as `cupy.sparse` package, and is moved to `cupyx.scipy.sparse` package with keeping `cupy.sparse` for backward compatibility.

Is it good time to deprecate `cupy.sparse` package?

**Comment by kmaehashi** [comment]
LGTM, but maybe Dask team is using `cupy.sparse`?
https://github.com/dask/dask/pull/5735 cc/ @jakirkham @cjnolet

**Comment by jakirkham** [comment]
Yeah cuML appears to be using this and Dask has some usage. So we would probably want to fix those first.

**Comment by jakirkham** [comment]
Submitted PRs to cuML and Dask.

xref: https://github.com/rapidsai/cuml/pull/2708
xref: https://github.com/dask/dask/pull/6530

**Comment by jakirkham** [comment]
Is `cupy.cusparse` affected by this change?

**Comment by jakirkham** [comment]
Also one last question, what timeline are we planning to make this change on?

**Comment by kmaehashi** [comment]
@jakirkham Thank you for the quick actions!

> Is cupy.cusparse affected by this change?

`cupy.cusparse` remains as is.

> Also one last question, what timeline are we planning to make this change on?

I think raiseing deprecation warning in v8rc1 and remove in v9 is the best, but if you have concerns we can delay the deprecation.

**Comment by jakirkham** [comment]
@JohnZed @cjnolet, any thoughts on this deprecation plan? 🙂

**Comment by JohnZed** [comment]
That seems reasonable to me. Giving a full release cycle for people to update is usually fair.

**Comment by JohnZed** [comment]
I like it. I think one full release cycle then deprecation is a fair amount of time to give users, especially if it is clearly noted in cupy 8 release notes.

**Comment by kmaehashi** [comment]
@takagi Could you start working on this?
