### ISSUE TITLE
Support Visual Studio 2019 build

### ISSUE THREAD

**Issue by zhihaoy** [cupy/cupy#3778]
Building CuPy is not as simple as having "Build Tools for Visual Studio 2017" installed.  If a user has a CUDA dev environment with Visual Studio 2019, he/she has to install CUDA on top of "Build Tools for Visual Studio 2017."  It significantly increase the bar for users.

**Comment by kmaehashi** [comment]
The VS version is automatically selected by Python setuptools, not CuPy.
https://wiki.python.org/moin/WindowsCompilers

Please consider using wheel packages if you don't have reasons to build from source.

**Comment by zhihaoy** [comment]
I'm trying to use cupy 8.0.0 for CUDA 11, but there is no binary package for Windows.  I may try upgrading setuptools and come back.

**Comment by zhihaoy** [comment]
intelpython3_core -> requires setuptools==47.3.0=py37_0

So setuptools shouldn't be an issue.

Here are the error messages I see:

```
************************************************************
* CuPy Configuration Summary                               *
************************************************************

Build Environment:
  Include directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.0\\include\\cub', 'C:\\Users\\zy\\devel\\cupy\\install\\../cupy/core/include', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.0\\include', 'C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\include']
  Library directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.0\\lib\\x64', 'C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\lib\\x64']
  nvcc command       : ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.0\\bin/nvcc.exe']

Environment Variables:
  CFLAGS          : (none)
  LDFLAGS         : (none)
  LIBRARY_PATH    : (none)
  CUDA_PATH       : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0
  NVTOOLSEXT_PATH : C:\Program Files\NVIDIA Corporation\NvToolsExt\
  NVCC            : (none)
  ROCM_HOME       : (none)

Modules:
  cuda      : Yes (version 11000)
  cusolver  : Yes
  cudnn     : No
    -> Include files not found: ['cudnn.h']
    -> Check your CFLAGS environment variable.
  nccl      : No
    -> Include files not found: ['nccl.h']
    -> Check your CFLAGS environment variable.
  nvtx      : Yes
  cutensor  : No
    -> Include files not found: ['cutensor.h']
    -> Check your CFLAGS environment variable.
  cub       : Yes (version 100909)
  thrust    : Yes (version 100909)

WARNING: Some modules could not be configured.
CuPy will be installed without these modules.
Please refer to the Installation Guide for details:
https://docs.cupy.dev/en/stable/install.html

************************************************************

Compiling cupy\core\_kernel.pyx because it changed.
Compiling cupy\lib\polynomial.pyx because it changed.
Compiling cupy\cuda\nvtx.pyx because it changed.
[1/3] Cythonizing cupy\core\_kernel.pyx
[2/3] Cythonizing cupy\cuda\nvtx.pyx
[3/3] Cythonizing cupy\lib\polynomial.pyx
building 'cupy_backends.cuda.api.driver' extension
error: Microsoft Visual C++ 14.1 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
```

So in configuration steps, Visual C++ 14.2 works fine.  But what this step is?

**Comment by kmaehashi** [comment]
> error: Microsoft Visual C++ 14.1 is required. **Get** it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

This means your Python is compiled with Visual C++ 14.1. Extensions like CuPy must use the same VC++ as the Python. Unfortunately we can't do anything.

> If a user has a CUDA dev environment with Visual Studio 2019, he/she has to install CUDA on top of "Build Tools for Visual Studio 2017." It significantly increase the bar for users.

Users only need to add "MSVC v141 - VS 2017 C++ Build Tools" option during Visual Studio 2019 installation. You don't have to install the entire VS 2017 nor reinstall CUDA.
