### ISSUE TITLE
Why some of the numpy functions are straight applicable on cupy array?

### ISSUE THREAD

**Issue by xf3227** [cupy/cupy#3781]
This is simply a question instead of an issue. I've noticed, for example, `numpy.fft.fft()` can be fed with a cupy array without any issue and the computation is mounted on GPU as expected. How is this black magic implemented?

Many Thanks!

**Comment by xf3227** [comment]
Oh, I think I've managed to figured it out. It seems like cupy array has overrided sufficiently enough operators in the manner of numpy such that the computation routine defined in numpy has no conflict with it. Please feel free to close the thread anytime.

**Comment by pentschev** [comment]
Actually, this is a mechanism called `__array_function__`, which is described in [NEP-18](https://numpy.org/neps/nep-0018-array-function-protocol.html), that allows NumPy to dispatch work to downstream libraries such as CuPy based on the input array types.

**Comment by xf3227** [comment]
Solved.

**Comment by xf3227** [comment]
@pentschev Thank you for the info. I will check it for details.
