### ISSUE TITLE
CuPy reducers return zero-dimensional arrays, rather than scalars

### ISSUE THREAD

**Issue by jpivarski** [cupy/cupy#3819]
One point of compatibility between CuPy and NumPy: when NumPy computes a reducer (`sum`, `prod`, `any`, `all`, `min`, `max`, ...), it returns a scalar that is interchangeable with Python numbers and inherits from `numbers.Number`:

```python
>>> np_scalar = numpy.sum(numpy.array([1, 4, 3, 0, 6]))
>>> np_scalar
14
>>> type(np_scalar)
<class 'numpy.int64'>
>>> isinstance(np_scalar, numbers.Integral)
True
>>> isinstance(np_scalar, numpy.integer)
True
>>> isinstance(np_scalar, numpy.ndarray)
False
```

but when CuPy computes a reducer, it returns a zero-dimensional array:

```python
>>> cp_scalar = cupy.sum(cupy.array([1, 4, 3, 0, 6]))
>>> cp_scalar
array(14)
>>> isinstance(cp_scalar, numbers.Integral)
False
>>> isinstance(cp_scalar, cupy.integer)
False
>>> isinstance(cp_scalar, cupy.ndarray)
True
```

The one thing they have in common is that their `shape` is an empty tuple:

```python
>>> np_scalar.shape
()
>>> cp_scalar.shape
()
```

But this is a test that can't be applied to Python numbers:

```python
>>> py_scalar = 14
>>> py_scalar.shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'int' object has no attribute 'shape'
```

The fact that this is different prevents us from being able to swap NumPy for CuPy everywhere; we need a [compatibility layer](https://github.com/scikit-hep/awkward-1.0/blob/f5662b5cc3e260140064dd49960499d006f4f63f/src/awkward1/nplike.py#L248-L354) to adjust for the differences.

Is there a reason for reducers to return zero-dimensional arrays instead of scalars, or is this an accident/bug?

```
>>> cupy.show_config()
CuPy Version          : 7.7.0
CUDA Root             : /home/jpivarski/miniconda3
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10201
cuFFT Version         : 10101
cuRAND Version        : 10101
cuSOLVER Version      : (10, 2, 0)
cuSPARSE Version      : 10300
NVRTC Version         : (10, 2)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2406
NCCL Runtime Version  : 2708
CUB Version           : None
cuTENSOR Version      : None
```

**Comment by leofang** [comment]
It's a documented behavior: https://docs.cupy.dev/en/latest/reference/difference.html#reduction-methods. We intentionally do this to avoid unexpected data transfer.

**Comment by jpivarski** [comment]
I suppose, then, to get NumPy/CuPy compatibility and also avoid unnecessary data transfers, you'd have to invent a scalar type that references data on the GPU but behaves in Python like a number. A transfer would be invoked if the user printed such a value to the screen (e.g. through `__repr__`) or used it in a Python or NumPy calculation (e.g. through `__float__`), but not if it's subsequently used in more CuPy calculations. Then a scalar that appears in the middle of a formula, involving only CuPy arrays and other CuPy scalars, wouldn't cause a transfer, but looking at the final result would, and that's acceptable because looking at the final result is something that happens on human timescales.

I'm not suggesting that this has to be done, but it would be a way to get both.

**Comment by leofang** [comment]
I think what you said is already there, except that operating a cupy array and a numpy array raises an error (as it should be, because it's unclear whether the computation should happen in GPU or CPU):
```python
>>> import cupy as cp
>>> a = cp.empty((), dtype=cp.float64)
>>> a[()] = 1.0
>>> int(a)
1
>>> float(a)
1.0
>>> print(a)
1.0
>>> import numpy as np
>>> b = np.random.random(3)
>>> b
array([0.56087557, 0.26437255, 0.61881601])
>>> a * b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 1012, in cupy.core.core.ndarray.__mul__
  File "cupy/core/_kernel.pyx", line 1041, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/_kernel.pyx", line 104, in cupy.core._kernel._preprocess_args
TypeError: Unsupported type <class 'numpy.ndarray'>
```
