### ISSUE TITLE
Provide manylinux wheels for cuda 11

### ISSUE THREAD

**Issue by ethanhs** [cupy/cupy#3824]
I'm currently keen to use cupy with CUDA 11.0 on Linux. Would it be possible to get manylinux wheels on pypi? It seems currently there are only Windows wheels. Thanks!

**Comment by leofang** [comment]
Please check out the release note: https://github.com/cupy/cupy/releases/tag/v7.8.0. The wheels for Linux is currently pending the PyPI team's response.

**Comment by ethanhs** [comment]
Ah thanks! I didn't think to look at the release notes. Hopefully they allow you to publish wheels soon!

**Comment by kmaehashi** [comment]
I've attached the Linux wheels in the Assets section in the release note.
https://github.com/cupy/cupy/releases/tag/v7.8.0
