### ISSUE TITLE
Very slow cupy.outer for some array sizes

### ISSUE THREAD

**Issue by alfiopuglisi** [cupy/cupy#3825]
While experimenting with cupy.outer(a,b), I found out that performance can be very slow if the A array is small and B is very big. I made a script where one array is size 3, while the other can grow to a few million elements (this was discovered doing computer graphics, the size 3 was an RGB array). When the A array grows keeping B at size 3, everything is fine. If instead the A array has size 3 and B grows, when B has more than a million elements things slow down to a crawl. See what happens for "3xN, N=2**21" and later:

Test script is attached to the end of this post. Times in seconds

```
                numpy    cupy    
---------------------------------
Nx3, N=2**18:   0.014   0.002
Nx3, N=2**19:   0.029   0.003
Nx3, N=2**20:   0.057   0.005
Nx3, N=2**21:   0.124   0.082
Nx3, N=2**22:   0.246   0.016
Nx3, N=2**23:   0.496   0.031

                numpy    cupy    
---------------------------------
3xN, N=2**18:   0.003   0.001
3xN, N=2**19:   0.019   0.002
3xN, N=2**20:   0.046   0.003
3xN, N=2**21:   0.053   4.562
3xN, N=2**22:   0.105   9.035
3xN, N=2**23:   0.214   18.163
```

* Conditions
CuPy Version          : 7.6.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 9010
CUDA Driver Version   : 10010
CUDA Runtime Version  : 9010
cuBLAS Version        : 9010
cuFFT Version         : 9010
cuRAND Version        : 9010
cuSOLVER Version      : (9, 1, 0)
cuSPARSE Version      : 9010
NVRTC Version         : (9, 1)
cuDNN Build Version   : 7102
cuDNN Version         : 7102
NCCL Build Version    : 2115
NCCL Runtime Version  : (unknown)
CUB Version           : None
cuTENSOR Version      : None

Test script (with txt extension because github does not support .py):

[test_outer.py.txt](https://github.com/cupy/cupy/files/5108402/test_outer.py.txt)

**Comment by kmaehashi** [comment]
I think the performance issue has been resolved in recent CuPy versions with the rewritten `tensordot_core`. However, I found another issue when testing your snippet: #4387 so we'll working on it.
