### ISSUE TITLE
Sparse equality & inequality functions

### ISSUE THREAD

**Issue by cjnolet** [cupy/cupy#3831]
Currently, it's not possible to compare sparse arrays using less than, greater, etc... 

This would be a very useful feature to have.

**Comment by anaruse** [comment]
I will work on this after https://github.com/cupy/cupy/pull/3860 is merged.

**Comment by cjnolet** [comment]
Since sparse equality is right there with all the inequality functions, it would be extremely useful just to support them all:

```python
    def __eq__(self, other):
        raise NotImplementedError

    def __ne__(self, other):
        raise NotImplementedError

    def __lt__(self, other):
        raise NotImplementedError

    def __gt__(self, other):
        raise NotImplementedError

    def __le__(self, other):
        raise NotImplementedError

    def __ge__(self, other):
        raise NotImplementedError
```
