### ISSUE TITLE
Duplicate indices in dense fancy indexing doesn't follow the "last in wins" semantics of Numpy

### ISSUE THREAD

**Issue by cjnolet** [cupy/cupy#3836]
One little rule that I found while implementing fancy indexing in `cupyx.scipy.sparse` is that when duplicate indices are encountered, the last one should always win. Though I found this extremely challenging to implement in sparse indexing, I don't think it's as bad to implement implement on the dense side.

I encountered this while investigating a test failure in https://github.com/cupy/cupy/pull/3533. For example, the following test encounters differences of 1-2 elements when comparing the results of the indexing against Cupy and Scipy/Numpy:

```python
sparse_csr_mat[0, 5, 10, 2, 0, 10], [1, 2, 3, 4, 1, 3]] = [1, 2, 3, 4, 5, 6]
```

Upon deeper inspection, I found this to be the case:
```python
>>> import cupy as cp
>>> a = cp.arange(5)
>>> a[[0, 1, 0, 1, 0, 1]] = [2, 3, 4, 5, 6, 7]
>>> a
array([2, 3, 2, 3, 4])
>>> import numpy
>>> b = numpy.arange(5)
>>> b[[0, 1, 0, 1, 0, 1]] = [2, 3, 4, 5, 6, 7]
>>> b
array([6, 7, 2, 3, 4])
```

Notice the Cupy dense array uses a `first-in-wins` rule while the Numpy array uses a `last-in-wins` rule for handling duplicates. It's a small detail, but it leads to unexpected differences in the behavior between Numpy & Cupy.

**Comment by toslunar** [comment]
CuPy does not always follow the first-in-wins rule neither: https://docs.cupy.dev/en/stable/reference/difference.html#duplicate-values-in-indices
