### ISSUE TITLE
CuPy v9 Release Schedule

### ISSUE THREAD

**Issue by asi1024** [cupy/cupy#3891]
Here is the current plan for CuPy v9 development.

## Highlights in CuPy v9

* CUDA JIT
* New Random Generator API (`numpy.random.Generator` interface added in NumPy 1.17)
* Improved HIP Support
* Other Feature/Performance Enhancements:
  * Expand cuTENSOR / CUB to more functions
  * Optimize user-specified parameters using Optuna (design TBD)

## Timeline

- [x] **v9.0.0a1 (v8.1.0)** (2020-10-29)
- [x] **v9.0.0a2 (v8.2.0)** (2020-11-26)
    - CUDA JIT implementation (initial PR merged)
- [x] **v9.0.0b1 (v8.3.0)** (2020-12-25) 🎄
    - Deprecations (old Python/CUDA/etc.)
-  [x] **v9.0.0b2 (v8.4.0)** (2021-01-28)
    - New Random Generator API (initial PR merged)
- [x] **v9.0.0b3 (v8.5.0)** (2021-02-26)
    - CUDA 11.2 support
    - HIP 4.0 support
    - HIP CI (`master` branch)
    - HIP packaging (`cupy-rocm-4-0`) + Docker image
- [x] **v9.0.0rc1 (v8.6.0)** (2021-03-25)
    - "Feature complete" release
    - `v9` branch cut
- [x] **v9.0.0** (2021-04-22)

Notes:

* The schedule and listed features are tentative and may subject to change depending on the progress.
* The code will be frozen around 15:00 on 2 days before the release date for QA. Dates are in JST.
* `v8.x.x` releases will only contain backported pull-requests (mainly bug-fixes) from the v9 (master) branch.

## Past Release Schedules

* v8: https://github.com/cupy/cupy/issues/3627

**Comment by mnicely** [comment]
Is there a list of features that v9 is expected to offer?

**Comment by kmaehashi** [comment]
.We are going to skip v9.0.0a1 release this month, as many PRs are backported to v8.0.0 and there's no major difference between them.

> Is there a list of features that v9 is expected to offer?

We will post v9 roadmap later in this issue!

**Comment by kmaehashi** [comment]
Added the highlights for v9 and updated timeline.

**Comment by kmaehashi** [comment]
v9.0.0b3 release date updated from 2020-02-25 to 2020-02-26 due to scheduling reasons.

**Comment by kmaehashi** [comment]
Filled a date for -v9.0.0rc1 and v9.0.0.
