### ISSUE TITLE
CUB bundle missing in GitHub's tarball

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#3895]
I am trying to build a conda package for v8.0.0rc1 locally, and notice that `cupy/core/include/cupy/cub/` is empty in https://github.com/cupy/cupy/archive/v8.0.0rc1.tar.gz. So, attempting to build CuPy would get this error message (that we deliberately set up):
```
        The folder cupy/core/include/cupy/cub/ is a git submodule but is
        currently empty. Please use the command

            git submodule update --init

        to populate the folder before building from source.
```
The current workaround I have is to download and move CUB 1.8.0 to the include path, but I don't think this is expected behavior.

**Comment by kmaehashi** [comment]
How about using tarball from PyPI instead of GitHub?

**Comment by leofang** [comment]
Thanks, @kmaehashi. Maybe it'd work! The predictable url is https://pypi.io/packages/source/c/cupy/cupy-8.0.0rc1.tar.gz.

ref: https://stackoverflow.com/a/47840593/2344149

**Comment by kmaehashi** [comment]
The GitHub tarball is auto-generated from the tag, so we can't do anything.
(Maybe we can improve the message if `cupy/core/include/cupy/cub/.git` is absent, though)

**Comment by leofang** [comment]
Yeah makes sense. I confirm that the PyPI tarball has the CUB bundle. Closing this issue. Will open a new one if I encounter any problem with the PyPI tarball.

**Comment by jakirkham** [comment]
One option would be to publish a tarball under the GitHub release. Though maybe that’s not too important with PyPI `sdist`s as an option

**Comment by leofang** [comment]
The current drawback of building with PyPI tarballs that I observe is that we lose the CUB version information:
https://dev.azure.com/nsls2forge/nsls2forge/_build/results?buildId=4283&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412&l=3281

**Comment by jakirkham** [comment]
Are there ways we can adjust the `sdist` generation process to handle this need?

**Comment by leofang** [comment]
I think so, although it's probably not a big deal. We can inject a file containing the CUB version string to `cupy_package_data` (added in #3879) and instruct setup.py to look it up during build time.
