### ISSUE TITLE
Installing cupy 7.8.0 from PyPi using pip throws a RuntimeError: Missing file: cupy/cuda/cutensor.cpp

### ISSUE THREAD

**Issue by maximtrp** [cupy/cupy#3971]
I am trying to install `cupy` from PyPi using `pip install cupy` and getting an error.

* Installation log: https://dpaste.com/EJ8BKNM3X
* `/proc/cpuinfo`: https://dpaste.com/44Z7M7JH5
* CUDA deviceQuery: https://dpaste.com/HEZTLAP26

I have all necessary libraries and tools:
```
      cuda      : Yes (version 11000)
      cusolver  : Yes
      cudnn     : Yes (version 8002)
      nccl      : Yes (version 2703)
      nvtx      : Yes
      thrust    : Yes
      cutensor  : Yes (version 1200)
      cub       : Yes
```

... and Cython v0.29.21.

```bash
$ cython -V
Cython version 0.29.21
$ python -V
Python 3.8.5
$ pip -V
pip 20.1.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)
$ python -c "import setuptools as st; print(st.__version__)"
50.3.0
```

**Comment by leofang** [comment]
For the time being you can install the `cupy-cuda110` wheel, downloadable from https://github.com/cupy/cupy/releases/tag/v7.8.0.

**Comment by kmaehashi** [comment]
We've released a post-release for this issue.
https://pypi.org/project/cupy/7.8.0.post1/
Thanks for reporting!
