### ISSUE TITLE
Add support for subclassing cupy.ndarray

### ISSUE THREAD

**Issue by mrkwjc** [cupy/cupy#3972]
Hi!

Many projects (including mine) use subclasses of numpy.ndarray, like this:
```python
class Field(np.ndarray):
    def __new__(cls, data, prefix=1):
        data = np.asarray(data)
        field = data.view(cls)
        field.prefix = prefix
        return field

    def __array_finalize__(self, field):
        if field is None:
            return
        self.prefix = getattr(field, 'prefix', 1)
```
If one tries to use cupy.ndarray as a numpy replacement, then at creation of the `Field` instance an error is raised:
```python
AttributeError: 'cupy.core.core.ndarray' object has no attribute 'prefix'
```
Are there plans to support in cupy subclassing similar to [numpy approach](https://numpy.org/doc/stable/user/basics.subclassing.html)? Maybe some workarounds are possible currently?

Regards,
Marek

**Comment by leofang** [comment]
What if you follow https://numpy.org/devdocs/user/basics.subclassing.html#simple-example-adding-an-extra-attribute-to-ndarray and do `field = super(Field, cls).__new__(...)` in `__new__`?

In general, though, my impression is even in NumPy subclassing `ndarray` is considered a poor practice despite they provide the instruction. In your case it might also prevent you from using CuPy as a drop-in replacement (though not impossible).

**Comment by mrkwjc** [comment]
Thanks for the answer. I redefined Field this way:
```python
class Field(np.ndarray):
    def __new__(cls, shape, dtype=float, buffer=None, offset=0,
                strides=None, order=None, prefix=1):
        field = super().__new__(cls, data.shape, dtype, buffer, offset,
                                strides, order)
        field.prefix = prefix
        return field

    def __array_finalize__(self, field):
        if field is None:
            return
        self.prefix = getattr(field, 'prefix', 1)
```
and then i succesfully created an instance with:
```python
f = Field(shape=(2, 2))
```
But the initialization with prefix gives an error:
```python
f = Field(shape=(2, 2), prefix=2)
TypeError: __init__() got an unexpected keyword argument 'prefix'
```
It seems this method is not a real option because i cannot initialize prefix at instance creation. I don't see the way to initialize also the array entries...

**Comment by leofang** [comment]
I think NumPy has some internal hooks to pass arguments from `__new__` to `__init__` to avoid this issue, whereas CuPy doesn't do because likely subclassing `cupy.ndarray` wasn't considered an option before. For example, `__array_finalize__` is not honored in CuPy.

**Comment by mrkwjc** [comment]
Ok. Thanks for clarifications. So it seems that it would be much better to switch my project to this approach: https://numpy.org/devdocs/user/basics.dispatch.html, i.e. to make Field an array container exposing the array methods and working seemlesly with ufuncs. But it seems this is not so easy as well, because cupy does not provide for example a counterpart of numpy.lib.mixins.NDArrayOperatorsMixin. And also: will __array__, __array_ufunc__ and __array_function__ methods work properly with cupy?

**Comment by leofang** [comment]
I don't know about `NDArrayOperatorsMixin`, will need to check that. CuPy supports `__array_ufunc__` and `__array_function__`, see https://docs.cupy.dev/en/stable/reference/interoperability.html#numpy. However, `__array__` is deliberately disabled to prevent silent data transfer.

**Comment by mrkwjc** [comment]
I understand disabling `__array__` to prevent silent data transfer in `cupy.ndarray`, but what about custom objects providing `__array__` and passed to `cupy.array` function? See this:

```python
import cupy as cp

class CustomArrayClass:
    def __array__(self):
        return cp.array([1,2,3,4,5])

a = CustomArrayClass()
b = cp.array(a)
Traceback (most recent call last):

  File "<ipython-input-40-8b0253934ebc>", line 1, in <module>
    cp.array(a)

  File "/home/mwojc/Anaconda/lib/python3.7/site-packages/cupy/creation/from_data.py", line 41, in array
    return core.array(obj, dtype, copy, order, subok, ndmin)

  File "cupy/core/core.pyx", line 1785, in cupy.core.core.array

  File "cupy/core/core.pyx", line 1862, in cupy.core.core.array

  File "cupy/core/core.pyx", line 1932, in cupy.core.core._send_object_to_gpu

ValueError: object __array__ method not producing an array
```
Apparently `__array__` was not called in `cp.array` and things are falling back to numpy which in turn does not recognize cupy array... It would be logical here to test `__array__` before casting to numpy. The attribute `__cuda_array_interface__` is supported this way. For example this will work:
```python
import cupy as cp

class CustomArrayClass:
    @property
    def __cuda_array_interface__(self):
        return cp.array([1,2,3,4,5]).__cuda_array_interface__

a = CustomArrayClass()
b = cp.array(a)
# All is OK now
```
But this way the array is recreated unnecessarily.

**Comment by rubendibattista** [comment]
Ehi @mrkwjc, did you find a solution? I'm also interested in understanding how to make `cupy` work with subclassed `numpy.ndarrays` or how to refactor to allow to use both.

**Comment by leofang** [comment]
Out of curiosity I revisited this request and am wondering what we've missed earlier? It seems this works fine:
```python
import cupy as cp


class MyArray(cp.ndarray):
    def __init__(self, *args, **kwargs):
        # remove "prefix" from kwargs if it's set, as the ndarray
        # constructor does not recognize it
        try:
            prefix = kwargs.pop('prefix')
        except KeyError:
            prefix = -10
        self.prefix = prefix
        super().__init__(*args, **kwargs)

a = MyArray([1, 2, 3])
print(a.prefix)
a = MyArray([1, 2, 3], prefix=10)
print(a.prefix)
```
Output:
```
-10
10
```

**Comment by mrkwjc** [comment]
Unfortunately, this will not work if we simply interchange cp.ndarray with np.ndarray. That's what this question was about, cupy and numpy are incompatible at this point...

**Comment by leofang** [comment]
Ah yes, I had forgotten how NumPy's subclassing works. Thanks for reminder.

**Comment by leofang** [comment]
Just some random thoughts: 
- [`__init_subclass__ `](https://docs.python.org/3/reference/datamodel.html#object.__init_subclass__): could it be useful? Say adding a hidden slot to `ndarray` to record the subclass type?
- If we take baby steps and do not support _view casting_ (see [here](https://numpy.org/doc/stable/user/basics.subclassing.html#the-role-of-array-finalize)) for now, honoring `__array_finalize__(self, obj)` might be easier as `obj` is either `None` or of the subclass type.

**Comment by kmaehashi** [comment]
Thanks @leofang! @takagi and I started discussing how we can achieve this within Cython: 
https://gist.github.com/takagi/84c616a0a4346454dbdf893dc550bcdb

**Comment by takagi** [comment]
I'm trying to realize cupy.ndarray subclassing by workaround1 in the [gist](https://gist.github.com/takagi/84c616a0a4346454dbdf893dc550bcdb) The following TODO is for managing its progress.

- [ ] Direct constructor call
- [ ] View casting
- [ ] New from template
  - [ ] ufuncs
  - [ ] ndarray methods
  - [ ] routines (this part includes many things and is to be expanded)
- [ ] documentation

**Comment by kmaehashi** [comment]
Now that the support is implemented, I guess this issue can be closed?

**Comment by takagi** [comment]
Yes.
