### ISSUE TITLE
Current streams must be managed for each device

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3980]
Currently, it is the users' responsibility to switch the current stream after changing the current device.
I think it's better to let CuPy manage it.

```py
print(cupy.cuda.get_current_stream().ptr)  # 0
cupy.cuda.Stream().use()  # stream on GPU 0
print(cupy.cuda.get_current_stream().ptr)  # 55448656
cupy.cuda.Device(1).use()  # switch to GPU 1
print(cupy.cuda.get_current_stream().ptr)  # 55448656
cupy.ones(10)
-> cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_INVALID_HANDLE: invalid resource handle
```

**Comment by leofang** [comment]
I think the first step IMHO is to add a new attribute to `cupy.cuda.Stream`, say `Stream.device`, that points to a `cupy.cuda.Device` object on which the stream is created. This would allow a quick lookup when the current stream needs to be retrieved from / stored to the thread-local storage.

**Comment by leofang** [comment]
> I think the first step IMHO is to add a new attribute to `cupy.cuda.Stream`, say `Stream.device`, that points to a `cupy.cuda.Device` object on which the stream is created. This would allow a quick lookup when the current stream needs to be retrieved from / stored to the thread-local storage.

This idea is fundamentally incompatible with the `Stream.null` and `Stream.ptds` singleton objects, as they meant to work for *all* devices. Also, for `ExternalStream` it's too hard to retrieve the associated device (`cuStreamGetCtx` -> `cuCtxSetCurrent` -> `cuCtxGetDevice` -> ...). Probably not worth bookkeeping.
