### ISSUE TITLE
Enhancement: custom CUB reduction kernel for non-contiguous cases

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#3982]
I think with some changes it might be possible to perform reduction over non-contiguous axes as well, for example `axis=(0, 2)` for a 3D array. For one-pass kernels, each block is currently in charge of a contiguous segment. I am hoping to extend this approach to "non-contiguous segments" (we still call them segments but the stride is no longer 1). 

Specifically, each thread should load the data from each non-contiguous segment in tiles:
https://github.com/cupy/cupy/blob/c1bf1aab6eb79a1cfcd5bb374460082d8eb2f3ca/cupy/core/_cub_reduction.pyx#L101-L102
where the loading will need to be done in this loop (instead of calling `BlockLoadT.Load()`):
https://github.com/cupy/cupy/blob/c1bf1aab6eb79a1cfcd5bb374460082d8eb2f3ca/cupy/core/_cub_reduction.pyx#L140-L159
and then perform the reduction as usual. Looks like we will need to use `CIndexer` to index over the input and output arrays, which is currently unused.

**Comment by leofang** [comment]
I've put most of pieces together locally, and the last missing piece is a sequence permutation problem, but I have had a hard time figuring out a valid and robust procedure to solve this, so a little fresh thoughts would be appreciated! @asi1024 @emcastillo 🙏 

Problem: Given a continuous sequence `i = (0, 1, 2, 3, ..., N-1)`, I would like to do a permutation based on the reduction axes. So, for example, given an input array of shape `(2, 3, 4)`, I expect to generate the below sequences:
```
axes = (0,):  out = 12 * (i % 2) + (i // 2) = (0, 12, 1, 13, 2, 14, ...)
axes = (1,): out = 4 * (i % 3) + (i // 3) % 4 + 12 * (i // 12) = (0, 4, 8, 1, 5, 9, ...)
axes = (0, 1): out = 4 * (i % 6) + i // 6 = (0, 4, 8, 12, 16, 20, ...)
axes = (0, 2): out = (12 * (i // 4)) % 24 + i % 4 + 4 * (i // 8) = (0, 1, 2, 3, 12, 13, 14, 15, 4, ...)
```
I guessed and verified the answers here, but don't see the logic clearly...

**Comment by leofang** [comment]
nvm I figured it out! Will do more tests and then send a PR!

**Comment by leofang** [comment]
I have a branch that can handle non-contiguous reductions in the segmented fashion: https://github.com/leofang/cupy/tree/cub_seg_reduce_stride. The idea is to use iterators to group all elements logically belonging to the same segments together. The experiment was done for CUB device reduction kernels (in `cupy.cuda.cub`) as it's an easier starting point.

However, this is an extremely inefficient approach unfortunately. The first issue is index calculation is slow, and the second issue is bad memory coalesce. Together it makes the reduction even slower than numpy...Looks like CuPy's strided reduction kernel is the best approach to handle such scenarios (and my guess is cuTENSOR more or less does the same thing).

Closing this issue...

**Comment by emcastillo** [comment]
😭 thanks for all the effort!
