### ISSUE TITLE
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

### ISSUE THREAD

**Issue by duongpaKikai** [cupy/cupy#3987]
**When i use torch.jit.trace to convert Pytorch model sang TorchScript model i get error with cupy**

`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DIFRINT-v4\lib\site-packages\cupy\cuda\compiler.py", line 449, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy\cuda\nvrtc.pyx", line 101, in cupy.cuda.nvrtc.compileProgram
  File "cupy\cuda\nvrtc.pyx", line 111, in cupy.cuda.nvrtc.compileProgram
  File "cupy\cuda\nvrtc.pyx", line 56, in cupy.cuda.nvrtc.check_status
**cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)**

During handling of the above exception, another exception occurred:`

` File "D:\project\test_1.0.0.pytorch\DIFRINT\models\correlation\correlation.py", line 143, in cupy_launch
    return cupy.cuda.compile_with_cache(strKernel).get_function(strFunction)
  File "C:\ProgramData\Anaconda3\envs\DIFRINT-v4\lib\site-packages\cupy\cuda\compiler.py", line 297, in compile_with_cache
    return _compile_with_cache_cuda(source, options, arch, cache_dir,
  File "C:\ProgramData\Anaconda3\envs\DIFRINT-v4\lib\site-packages\cupy\cuda\compiler.py", line 350, in _compile_with_cache_cuda
    ptx = compile_using_nvrtc(source, options, arch, name + '.cu')
  File "C:\ProgramData\Anaconda3\envs\DIFRINT-v4\lib\site-packages\cupy\cuda\compiler.py", line 158, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "C:\ProgramData\Anaconda3\envs\DIFRINT-v4\lib\site-packages\cupy\cuda\compiler.py", line 453, in compile
    raise CompileException(log, self.src, self.name, options, 'nvrtc')
**cupy.cuda.compiler.CompileException: C:\Users\Admin\AppData\Local\Temp\tmpg65_9di1\8f8f5ff490d72ae331cc951d3896a60d_2.cubin.cu(16): error: identifier "tensor" is undefined**   

1 error detected in the compilation of "C:\Users\Admin\AppData\Local\Temp\tmpg65_9di1\8f8f5ff490d72ae331cc951d3896a60d_2.cubin.cu".`

**I use Conda on Window 10
  torch==1.6.0
  torchvision==0.7.0
  cupy-cuda102**

**I dont know why some one can help me
May be cause cuda in conda enviroment and cuda in window conflict** ??

[pytorch-pwc/correlation/correlation.py](https://github.com/sniklaus/pytorch-pwc/blob/cf0d2f2cbef4bcb0f6cbf09011960a4899d77dec/correlation/correlation.py#L8-L33)

```
kernel_Correlation_rearrange = ''' 
 	extern "C" __global__ void kernel_Correlation_rearrange( 
 		const int n, 
 		const float* input, 
 		float* output 
 	) { 
 	  int intIndex = (blockIdx.x * blockDim.x) + threadIdx.x; 
  
 	  if (intIndex >= n) { 
 	    return; 
 	  } 
  
 	  int intSample = blockIdx.z; 
 	  int intChannel = blockIdx.y; 
  
 	  float fltValue = input[(((intSample * SIZE_1(input)) + intChannel) * SIZE_2(input) * SIZE_3(input)) + intIndex]; 
  
 	  __syncthreads(); 
  
 	  int intPaddedY = (intIndex / SIZE_3(input)) + 4; 
 	  int intPaddedX = (intIndex % SIZE_3(input)) + 4; 
 	  int intRearrange = ((SIZE_3(input) + 8) * intPaddedY) + intPaddedX; 
  
 	  output[(((intSample * SIZE_1(output) * SIZE_2(output)) + intRearrange) * SIZE_1(input)) + intChannel] = fltValue; 
 	} 
 ''' 
```

**Comment by kmaehashi** [comment]
Could you share the code to reproduce the issue?

**Comment by duongpaKikai** [comment]
@kmaehashi 
i have updated code

**Comment by kmaehashi** [comment]
Thanks, could you set `set CUPY_DUMP_CUDA_SOURCE_ON_ERROR=1` environment variable and rerun the code so that you can find what's wrong at line 16 (`... cubin.cu(16): error: identifier "tensor" is undefined`)?
