### ISSUE TITLE
Cannot determine the device from pointer using `cudaPointerGetAttributes` if device mismatch

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3991]
It seems `cudaPointerGetAttributes` (and `cuPointerGetAttributes`) is no longer working in CUDA 10.1+ if the device the pointer resides and the current device do not match. It was working in CUDA 10.0.

```py
import cupy
a = cupy.arange(10)  # array on GPU 0
cupy.cuda.Device(0).use()
cupy.cuda.runtime.pointerGetAttributes(a.data.ptr)
cupy.cuda.Device(1).use()
cupy.cuda.runtime.pointerGetAttributes(a.data.ptr) # raises CUDARuntimeError
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy_backends/cuda/api/runtime.pyx", line 601, in cupy_backends.cuda.api.runtime.pointerGetAttributes
    cpdef PointerAttributes pointerGetAttributes(intptr_t ptr):
  File "cupy_backends/cuda/api/runtime.pyx", line 604, in cupy_backends.cuda.api.runtime.pointerGetAttributes
    check_status(status)
  File "cupy_backends/cuda/api/runtime.pyx", line 246, in cupy_backends.cuda.api.runtime.check_status
    raise CUDARuntimeError(status)
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInvalidValue: invalid argument
```

We rely on `cudaPointerGetAttributes` to determine the device for foreign pointers, e.g., `__cuda_array_interface__` which does not contain the device number.
https://github.com/cupy/cupy/blob/v8.0.0rc1/cupy/cuda/memory.pyx#L123

**Comment by anaruse** [comment]
We're checking with the CUDA team, so please wait for a while.

**Comment by leofang** [comment]
@anaruse Is this identified as a bug?

**Comment by anaruse** [comment]
Yes, CUDA team is working on it.

**Comment by leofang** [comment]
Thanks! Do we know which CUDA version(s) are impacted by this bug?

@gmarkall Looks like we need to revise the CUDA Array Interface protocol to include the device id and get around this bug...

**Comment by anaruse** [comment]
CUDA 10.2 and later are influenced by this issue.

**Comment by anaruse** [comment]
This issue is related to timing of CUDA context creation.  If you allocate memory "current" GPU before calling cudaPointGetAttributes(), this issue can be avoided.

```python
import cupy
a = cupy.arange(10)  # array on GPU 0
cupy.cuda.Device(0).use()
cupy.cuda.runtime.pointerGetAttributes(a.data.ptr)
cupy.cuda.Device(1).use()
b = cupy.arange(1)  # work-around
cupy.cuda.runtime.pointerGetAttributes(a.data.ptr)
```

**Comment by kmaehashi** [comment]
Thank you for sharing the workaround!

For record, more realistic case of this error:
```py
import cupy, torch
cupy.asarray(torch.arange(3).to('cuda:1'))
```
With the workaround #4085, I confirmed this snippet work correctly with CUDA 10.2.
