### ISSUE TITLE
Inconsistent casting behavior between a zero-dim array and an array

### ISSUE THREAD

**Issue by unnonouno** [cupy/cupy#400]
When a zero-dim array and an array are given, NumPy uses the type of the array and CuPy uses common type of them.
```
>>> (cupy.array(3, 'd') * cupy.arange(3, dtype='f')).dtype
dtype('float64')
>>> (numpy.array(3, 'd') * numpy.arange(3, dtype='f')).dtype
dtype('float32')
```

**Comment by okuta** [comment]
In CuPy, we are trying to keep it inconsistent for performance reasons.

**Comment by unnonouno** [comment]
If so we need to write it in the document.
