### ISSUE TITLE
Possible typo ("dype" instead of "dtype") in cufft.pyx

### ISSUE THREAD

**Issue by plamenivanov257** [cupy/cupy#4009]
Hi!

I think I have stumbled upon a typo in cufft.pyx. The function cufft.PlanNd.check_output_array has several mentions of "ndarray.dype", which I strongly suspect was intended to be "dtype". Apologies if this has already been reported.

Here is a traceback:

File "cupy\cuda\cufft.pyx", line 845, in cupy.cuda.cufft.PlanNd.check_output_array
AttributeError: 'cupy.core.core.ndarray' object has no attribute 'dype'

And here is my CuPy version:

CuPy Version          : 8.0.0rc1
CUDA Root             : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0
CUDA Build Version    : 11000
CUDA Driver Version   : 11000
CUDA Runtime Version  : 11000
cuBLAS Version        : 11200
cuFFT Version         : 10201
cuRAND Version        : 10201
cuSOLVER Version      : (10, 6, 0)
cuSPARSE Version      : 11101
NVRTC Version         : (11, 0)
Thrust Version        : 100909
CUB Build Version     : 100909
cuDNN Build Version   : None
cuDNN Version         : None
NCCL Build Version    : None
NCCL Runtime Version  : None
cuTENSOR Version      : None

**Comment by leofang** [comment]
Thanks for reporting. They are indeed typos. But I wonder how did you trigger this error? Could you post a code snippet?

**Comment by plamenivanov257** [comment]
Hi, leofang,

Sure! The way I triggered it was to create a C2R (or Z2D) FFT plan and then call check_output_array. Here's a snippet that triggers the error:

```
import cupy as cp
from cupy.cuda import cufft

nx = 128
ny = 128
nz = 64
plan_c2r = cufft.PlanNd(shape=tuple([nz, nx, ny]),
                        istride=1,
                        ostride=1,
                        inembed=tuple([1, nx, half_ny]),
                        onembed=tuple([1, nx, ny]),
                        idist=nz*nx*half_ny,
                        odist=nz*nx*ny,
                        fft_type=cufft.CUFFT_Z2D,
                        batch=12,
                        order='C',
                        last_axis=3,
                        last_size=ny)

data_in_half_many= cp.random.rand(12, nz, nx, half_ny)[:] + 1j * cp.random.rand(12, nz, nx, half_ny)[:]
data_out_half_many = cp.zeros([12, nz, nx, ny], dtype=cp.float64)
plan_c2r.check_output_array(data_in_half_many, data_out_half_many)
```

**Comment by leofang** [comment]
I see, so you called `cupy.cuda.cufft.PlanNd.check_output_array` directly. I will fix it shortly.

However, please note that 1. this function is currently unused in any code path (it was there mainly for an extension but no one is working on it afaik), 2. classes and functions in `cupy.cuda.cufft` are considered semi-internal and will be subject to change without deprecation notice, so please avoid using them if possible. To generate a cuFFT plan, you can use `cupyx.scipy.fft.get_fft_plan`.

**Comment by plamenivanov257** [comment]
Thank you, @leofang ! I never assumed that using `cupy.cuda.cufft` directly is the intended way of using CuPy. The sole reason I had to resort to this is that I can specify an output array when using cufft plans; and (as far as I know) there is no way to do this when using the NumPy/SciPy-like interface of CuPy.

**Comment by leofang** [comment]
Hi @plamenivanov257, did you mean you wanna pass in a pre-allocated buffer for FFT calls to hold the output?

**Comment by plamenivanov257** [comment]
Yes, that is exactly what I meant!

**Comment by leofang** [comment]
I see. Yeah it seems to be a legitimate usage (which was the planned work that I referred to earlier). In your case, though, you don't have to call `check_output_array()` as the array shape and dtype can be easily predetermined for C2C transforms, or obtained by `PlanNd.get_output_array()`. The latter is what's used in the codebase (for all kinds of transforms).
