### ISSUE TITLE
Certain cupy functions are not able to be run concurrently

### ISSUE THREAD

**Issue by itisyeetimetoday** [cupy/cupy#4026]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
CuPy Version          : 7.8.0
CUDA Root             : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
CUDA Build Version    : 10010
CUDA Driver Version   : 11000
CUDA Runtime Version  : 10010
cuBLAS Version        : 10100
cuFFT Version         : 10010
cuRAND Version        : 10010
cuSOLVER Version      : (10, 1, 0)
cuSPARSE Version      : 10010
NVRTC Version         : (10, 1)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : None
NCCL Runtime Version  : None
CUB Version           : None
cuTENSOR Version      : None

When using functions in cupy like mean or cov, I notice that concurrency no longer happens, and instead, each mapped stream is run serially. I can provide example code if necessary, but my code is basically identical to the map_reduce.py in stream under examples.

**Comment by kmaehashi** [comment]
ref: https://stackoverflow.com/questions/64055737/cupy-only-1-stream-launched-when-8-streams-are-allocated-to-gpu

Could you provide a reproducer without using open3d so that we can reproduce locally?

**Comment by itisyeetimetoday** [comment]
Okay, I will shortly upload an example with open3d.

**Comment by itisyeetimetoday** [comment]
Here is the example: https://github.com/itisyeetimetoday/outlier-cupy-concurrency/blob/master/outlier_parallel_test.py
Here is the link to a screenshot of visual profiler, with the cp.linalg.inv 
[https://drive.google.com/file/d/1Fs9l3MhQylC_0-3hZgPd6kloIwJmeNi6/view?usp=sharing](url)
And without:
[https://drive.google.com/file/d/1jdVsJ-PcPcRJZUMrFWgFJXTopuvyXyFp/view?usp=sharing](url).
I've noticed that when adding cp.linalg.inv and cp.where, concurrency is instantly stops, and becomes serial.

**Comment by emcastillo** [comment]
cp.where and cp.linalg.inv synchonizes the device so it is expected :(

**Comment by itisyeetimetoday** [comment]
For cp.linalg.inv, can I replace it with code here: https://stackoverflow.com/questions/11972102/is-there-a-way-to-efficiently-invert-an-array-of-matrices-with-numpy, but substitute cupy with numpy in order to get around the synchronization issue?
Also, would using the function:  get_indices_sparse(data): from the first answer: https://stackoverflow.com/questions/33281957/faster-alternative-to-numpy-where get around the syncrhonization for cp.where?

**Comment by itisyeetimetoday** [comment]
Also, how do I check which functions will synchronize the device?

**Comment by itisyeetimetoday** [comment]
I looked into the source code and found a line under the cupy.where implementation: `return nonzero(condition)  # may synchronize`.

**Comment by asi1024** [comment]
This synchronization is not avoidable because `nonzero` cannot determine the size of the return value without looking into the values in the input array.

**Comment by asi1024** [comment]
`cupy.linalg.inv` raises `LinAlgError` if invalid input is given. This routine requires device synchronization to looking into the status value cuBLAS returns. You can disable this check by `cupy.seterr(linalg='ignore')`. :smile:

**Comment by leofang** [comment]
In addition to potential synchronizations, it could also be that certain functions simply demand a lot of hardware resources such that it is not possible to schedule concurrent kernels. If it's the case, it is a hard problem beyond CuPy's control.

**Comment by itisyeetimetoday** [comment]
Asi1024, I tried your method on 7.8.0. with the cupx flag, and it did not work. I tried upgrading, and I found out that `cupy.mean` apparently also runs serially on 8.0.0. Could someone confirm this issue, or is it just because I did not uninstall the old cuda package?

**Comment by asi1024** [comment]
@itisyeetimetoday `cupy.mean` will not require device synchronization. Could you show me a minimal reproducer?

**Comment by asi1024** [comment]
`cupy.ndarray` stores its shape and strides in CPU memory space and stores the array data in GPU memory space. The shape of the return value of `nonzero` cannot be determined only from the input's shape/strides.
