### ISSUE TITLE
RawKernel does not work with dask.distributed

### ISSUE THREAD

**Issue by jglaser** [cupy/cupy#4044]
When I call a `RawKernel` using on a remote worker using `distributed`, e.g. `ddf.map_partitions(kernel_wrapper)`, the worker crashes with a segfault. I suspect this is because of the following:

If I first execute the kernel on the client side, it compiles and runs successfully. After that, I submit the kernel for execution by the workers, at which point the NVRTC compiled code gets serialized. Once it gets sent to the other host, the CUDA context is different and the data structures of the compiled kernel are no longer valid. When I do not execute the kernel locally before submitting it to the workers (i.e. do not trigger compilation), everything runs fine.

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version: master, commit:dd2fb09f63fce8b7ddb58deb4b91f0b3669d1a0d
  - OS/Platform: Linux PPCle64
  - CUDA version: 10.1.243
  - cuDNN/NCCL version N/A
* Code to reproduce

(sketch, I did not actually try to run the below code exactly as is)
```
import dask
import cupy as cp

kernel = cp.RawKernel(r'''

extern "C" __global__ void test_kernel()
    {
    printf("Test\n");
    }
''', 'test_kernel')

def launch_kernel():
    kernel((1,),(128,),())

# comment out the below line and it should run on the remote workers
launch_kernel() # should print out Test

from dask.distributed import Client
client = Client(scheduler_file='my-scheduler.json')
ddf = dask.datasets.timeseries()
ddf.map_partitions(launch_kernel) # Segfault on the workers
```

* Error messages, stack traces, or logs
```
distributed.nanny - INFO - Worker process 56138 was killed by signal 11
distributed.nanny - WARNING - Restarting worker
```

**Comment by leofang** [comment]
Pinging Dask experts @jakirkham @pentschev to help debug, since I know very little about Dask's internal. When do Dask-Distributed (?) workers import CuPy? When do they initialize the CUDA context?

**Comment by leofang** [comment]
My wild guess: We need to make `RawKernel`s picklable (by adding `__reduce__`).

**Comment by jakirkham** [comment]
That was going to be my first question, "Is `RawKernel` pickleable"? Sounds like the answer no. Certainly making it pickleable would help.

As a workaround, one might consider creating and using the `RawKernel` within another wrapper function. This would bypass the question of whether `RawKernel` is pickleable by asking instead whether the wrapper function is pickleable. Usually the answer here is yes, but we may need additional tweaks depending.

**Comment by jakirkham** [comment]
One other thing worth noting here, is that if it is difficult to make `RawKernel` objects pickleable, we might want to simply raise a `PicklingError` with `__reduce__` for now. This would give an error as opposed to a crash, which would make for a notable improvement on user experience (even if it means pickling still doesn't happen).

**Comment by pentschev** [comment]
That can be tricky indeed. I wrote a blog about Dask+CuPy raw kernels about a year ago: https://medium.com/rapids-ai/parallelizing-custom-cupy-kernels-with-dask-4d2ccd3b0732 . It was since shown to have some flaws, perhaps some introduced in Dask after I wrote it, there's a discussion in https://github.com/dask/dask/issues/5992 . Note that the blog was using Dask alone (without Distributed/Dask-CUDA, so no multi-GPU) and it worked. At the time I didn't test multi-GPU to keep things simple, but I indeed saw crashes, as described in item 2 from https://github.com/dask/dask/issues/5992#issuecomment-665099640.

I think pickling seems like a potential problem, but not for the `launch_kernel` function, and not for the `RawKernel`:

```python
In [1]: import cupy as cp, pickle
   ...:
   ...: kernel = cp.RawKernel(r'''
   ...:
   ...: extern "C" __global__ void test_kernel()
   ...:     {
   ...:     printf("Test\n");
   ...:     }
   ...: ''', 'test_kernel')
   ...:
   ...: def launch_kernel():
   ...:     kernel((1,),(128,),())
   ...:

In [2]: kernel
Out[2]: <cupy.core.raw.RawKernel at 0x7fa4be1c7ad0>

In [3]: kernel_str = pickle.dumps(kernel)
   ...: kernel_str
Out[3]: b'\x80\x03ccupy.core.raw\n__pyx_unpickle_RawKernel\nq\x00ccupy.core.raw\nRawKernel\nq\x01J\xcc\xa1w\x03N\x87q\x02Rq\x03(NX\x05\x00\x00\x00nvrtcq\x04XM\x00\x00\x00\n\nextern "C" __global__ void test_kernel()\n    {\n    printf("Test\\n");\n    }\nq\x05X\x0b\x00\x00\x00test_kernelq\x06)\x89tq\x07b.'

In [4]: new_kernel = pickle.loads(kernel_str)

In [5]: new_kernel
Out[5]: <cupy.core.raw.RawKernel at 0x7fa1bcfe27d0>

In [6]: launch_kernel_str = pickle.dumps(launch_kernel)
   ...: launch_kernel_str
Out[6]: b'\x80\x03c__main__\nlaunch_kernel\nq\x00.'
```

It seems we can unpickle `RawKernel`, but `launch_kernel` bytestring is definitely incomplete. I'm not very experienced with pickling, but a quick search seems to point to alternatives to pickle, like dill and marshal. @jakirkham do you know if function pickling in Dask is generally supposed to work?

**Comment by jakirkham** [comment]
If `RawKernel` contains content that is process specific (like pointers), it may appear to pickle fine in one process and cause problems when unpickling in another process (like pointing to invalid memory). This could cause segmentation faults and other kinds of havoc. We've seen this sort of issue before with other CuPy objects ( https://github.com/cupy/cupy/issues/3061 ).

**Comment by leofang** [comment]
I will try working on this later today or tomorrow. The codebase is frozen for release anyway, so the fix won't be in unfortunately. I will try to create a failing case without Dask, and then test if we can fix it.

**Comment by jakirkham** [comment]
Sounds good. One thought in terms of a failing case would be to try writing out the pickled data from one process and loading/unpickling it in another. Maybe a little cumbersome for a test, but it would at least help us determine if that is the issue or if we are missing something else.

**Comment by leofang** [comment]
That is exactly my plan 👍

**Comment by pentschev** [comment]
> If `RawKernel` contains content that is process specific (like pointers), it may appear to pickle fine in one process and cause problems when unpickling in another process (like pointing to invalid memory).

A CUDA kernel can't contain process specific content. However, it seems that the kernel cache could be a problem indeed: https://github.com/cupy/cupy/blob/34cb08d9c9aab29f51d1c58284a7dce12f75a0f5/cupy/core/raw.pyx#L55-L56 

But also, pickling of the launcher function could be a problem too, even though it's usually pure Python, I'm not sure if Dask is handling that.

**Comment by jakirkham** [comment]
Thanks all! 😄
