### ISSUE TITLE
cp.nonzero, and cp.where Synchronizes Device, can not Run Concurrently

### ISSUE THREAD

**Issue by itisyeetimetoday** [cupy/cupy#4050]
CuPy Version : 7.8.0
CUDA Root : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
CUDA Build Version : 10010
CUDA Driver Version : 11000
CUDA Runtime Version : 10010
cuBLAS Version : 10100
cuFFT Version : 10010
cuRAND Version : 10010
cuSOLVER Version : (10, 1, 0)
cuSPARSE Version : 10010
NVRTC Version : (10, 1)
cuDNN Build Version : 7605
cuDNN Version : 7605
NCCL Build Version : None
NCCL Runtime Version : None
CUB Version : None
cuTENSOR Version : None

When I use `cp.nonzero,` and as a result, `cp.where,` synchronizes the device, and breaks concurrency. 
Under the implementation code, I found this line, `return nonzero(condition) # may synchronize`, indicating that there may be further synchronization in the source code. In the map_reduce.py, under the streams example folder, if I generate a random array `x = rand.normal(size=(1024**2))` and replace `matmul` with `cp.nonzero(x>0.5)` or `cp.where(x>0.5)`, and profile the application with the visual profiler, I get this result: https://drive.google.com/file/d/1OsVM_Lhcz2L3NIQb8MLgULzTADWc5AnG/view?usp=sharing, showing the serial code. Does anyone have an alternative method to replace `cp.where` or `cp.nonzero` that will work synchronizes, or am I using the functions incorrectly?

**Comment by asi1024** [comment]
Please see this comment: https://github.com/cupy/cupy/issues/4026#issuecomment-702025770
