### ISSUE TITLE
argmax and argmin return wrong results for F-order arrays

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#4061]
On CuPy master:
```python
import cupy as cp
import numpy as np


cp.core.set_routine_accelerators([])
cp.core.set_reduction_accelerators([])

a = cp.asarray([[3, 1], [4, 2]], order='F')
b = cp.asnumpy(a)
print("cp.argmax:", a.argmax(), "  np.argmax:", b.argmax())
print("cp.argmin:", a.argmin(), "  np.argmin:", b.argmin())
```
output:
```
cp.argmax: 1   np.argmax: 2
cp.argmin: 2   np.argmin: 1
```
This bug affects both CuPy's original implementation as well as the CUB block reduction (in `cupy.core._cub_reduction`), but not the CUB device reduction (`cupy.cuda.cub`). My guess is for Fortran arrays we calculated the array index (`_J`) wrong...

**Comment by kmaehashi** [comment]
Thanks for reporting!
@asi1024 Could you look into this in detail?
