### ISSUE TITLE
cupy.asarray doesn't accept list of cupy.ndarray

### ISSUE THREAD

**Issue by muupan** [cupy/cupy#409]
Both `numpy.asarray` and `cupy.asarray` accept list of `numpy.ndarray`:

```
>>> numpy.asarray([numpy.zeros(1)])
array([[ 0.]])
>>> cupy.asarray([numpy.zeros(1)])
array([[ 0.]])
```

However, `cupy.asarray` doesn't accept list of `cupy.ndarray`:

```
>>> cupy.asarray([cupy.zeros(1)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/.pyenv/versions/flatten-obs/lib/python3.6/site-packages/cupy/creation/from_data.py", line 46, in asarray
    return core.array(a, dtype, False)
  File "cupy/core/core.pyx", line 1799, in cupy.core.core.array (cupy/core/core.cpp:58790)
  File "cupy/core/core.pyx", line 1824, in cupy.core.core.array (cupy/core/core.cpp:58526)
ValueError: Unsupported dtype object
```

This behavior might be consistent in some sense, but I often find it cumbersome when writing numpy/cupy agnostic code.

**Comment by kmaehashi** [comment]
When writing code with Chainer, `Unsupported dtype object` was one of the common issue, especially in pre-processing code that is both compatible with NumPy/CuPy.
It is hard to guess the reason from this error message for first-timers.

How about documenting it in https://docs-cupy.chainer.org/en/stable/reference/difference.html?

(Note, to fully fix this issue, we need to implement CuPy version of `PyArray_FromAny`)

**Comment by Paul0M** [comment]
Got the same issue when split the prediction of Siamese Net to us Triplet loss.
Is there a workaround for this kind of usage?
```python
    pred = net(X)
    a_preds = [pred[i] for i in range(0, batch*3, 3)]
    p_preds = [pred[i] for i in range(1, batch*3, 3)]
    n_preds = [pred[i] for i in range(2, batch*3, 3)]
    
    xp = cuda.get_array_module(pred)
    a_preds = xp.asarray(a_preds)
    p_preds = xp.asarray(p_preds)
    n_preds = xp.asarray(n_preds)
    
    loss = F.triplet(a_preds, p_preds, n_preds)

**Comment by kmaehashi** [comment]
If you want to convert a list of CuPy arrays with the same shape to a single CuPy array, you can use `xp.stack`.
(Note that this does not work with more complicated structure, e.g., a list of list of CuPy arrays.)

**Comment by niboshi** [comment]
Now this behavior is documented in #1027.
Should we close this issue?

**Comment by kmaehashi** [comment]
Let's close this issue after finishing discussion in #1030.

**Comment by niboshi** [comment]
OK.
