### ISSUE TITLE
Feature request: Support cuFFT callback routines

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#4105]
This is something that @maxpkatz and I tried a while ago but we never figured it out. It would be nice to support the cuFFT callback routines in CuPy:
https://docs.nvidia.com/cuda/cufft/index.html#callback-routines
https://developer.nvidia.com/blog/cuda-pro-tip-use-cufft-callbacks-custom-data-processing/
The idea is to reduce access to global memory by fusing both elementwise pre- and post- processing kernels with the FFT operations to increase the performance.

The problem we encountered was that it requires linking to cuFFT's static library instead of shared library, but if we do this by changing this line
https://github.com/cupy/cupy/blob/5dcd1a53c2c6667b6cfafc132402554f8e5d3299/cupy_setup_build.py#L141
to ~~`'cufftw'`~~ `'cufft_static'` as instructed by the [cuFFT documentation](https://docs.nvidia.com/cuda/cufft/index.html#static-library) and rebuild CuPy (to be precise, the `cupy.cuda.cufft` module), we encounter "undefined symbols" errors when importing CuPy. Those symbols are for the callback support and are leaked from ~~`libcufftw.a`~~ `libcufft_static.a` into the module object. 

**I can work out this support myself, but I need someone to help me resolve this issue.**

cc: @bjoernenders @smarkesini

**Comment by leofang** [comment]
If this works, my idea was that users can write `cupy.RawKernel`s for pre- and post- processings, respectively, and then pass them to the callback APIs to tie with an existing cuFFT plan. This might not be fully compatible with the high-level APIs like `cupy.ftt`, but at least makes it exposed to the Python space for advanced users to try.

**Comment by mnicely** [comment]
@leofang If I'm reading the docs right, `cufftw` is for FFTW user that want to port code.

To utilize callbacks you have to link `cufft_static` and `culibos`. Unfortunately, the library also has to be device linked with `-dc`.

From blog: https://developer.nvidia.com/blog/cuda-pro-tip-use-cufft-callbacks-custom-data-processing/

The cuFFT callback feature is available in the statically linked cuFFT library only, currently only on 64-bit Linux operating systems. Callbacks therefore require us to compile the code as relocatable device code using the --device-c (or short -dc) compile flag and to link it against the static cuFFT library with -lcufft_static. Important: If you forget to compile as relocatable device code your application may quietly ignore callbacks and produce wrong results!

nvcc -ccbin g++ -dc -m64 -o cufft_callbacks.o -c cufft_callbacks.cu
nvcc -ccbin g++ -m64 -o cufft_callbacks cufft_callbacks.o -lcufft_static -lculibos

**Comment by leofang** [comment]
Right, thanks @mnicely, sorry my description was wrong. I tried to recollect what I did but it was long ago, but I'm sure what you said is what I followed; @maxpkatz helped me ensured that 😅 Let me check if I still keep my failed attempts locally and link here.

**Comment by leofang** [comment]
@mnicely The point is we want to make sure the support of callbacks exists in `cupy.cuda.cufft` is already there when we launch Python. I also tried that creating a cuFFT plan from `cupy.cuda.cufft` (which links to `libcufft.so`), and passing it to the callback API that I wrapped in `cupy.cuda.cufftx` (statically linked to `libcufft_static.a`), and it didn't work (`CUFFT_INVALID_PLAN` or something was raised). It seems plans created in `libcufft.so` are not accepted in  `libcufft_static.a`.

**Comment by mnicely** [comment]
> @mnicely The point is we want to make sure the support of callbacks exists in `cupy.cuda.cufft` is already there when we launch Python. I also tried that creating a cuFFT plan from `cupy.cuda.cufft` (which links to `libcufft.so`), and passing it to the callback API that I wrapped in `cupy.cuda.cufftx` (statically linked to `libcufft_static.a`), and it didn't work (`CUFFT_INVALID_PLAN` or something was raised). It seems plans created in `libcufft.so` are not accepted in `libcufft_static.a`.

Ahh okay!

**Comment by leofang** [comment]
@mnicely The undefined symbol error can be reproduced simply by building from my branch: https://github.com/leofang/cupy/tree/cufft_retry. It's nothing more than linking to the libraries you mentioned (`cufft_static` and `culibos`) instead of to `cufft`.

This is what you will see:
```
$ python -c "import cupy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/leofang/dev/cupy_cuda10.2/cupy/__init__.py", line 57, in <module>
    from cupy import fft  # NOQA
  File "/home/leofang/dev/cupy_cuda10.2/cupy/fft/__init__.py", line 1, in <module>
    from cupy.fft._fft import fft  # NOQA
  File "/home/leofang/dev/cupy_cuda10.2/cupy/fft/_fft.py", line 8, in <module>
    from cupy.cuda import cufft
ImportError: /home/leofang/dev/cupy_cuda10.2/cupy/cuda/cufft.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterLinkedBinary_34_dpRadix0004A_cb_compute_75_cpp1_ii_3bf92bec
```
Note the symbol name contains `_cb_` which I guess stands for "callback". (My impression was we've seen other symbol names undefined but I couldn't recall which one.)

**Comment by bjoernenders** [comment]
I just quickly wanted to give a thumbs up here for the discussion. Easily fusing affine transformations or other elementwise kernels with the FFT or similar compute kernels is a very important feature for science.

**Comment by llukas** [comment]
@leofang could you post link command that is used?

**Comment by leofang** [comment]
@llukas Good question. If you clone from my branch and build from source (`pip install -v -e .`), you can see the compile and linker commands:
```
    building 'cupy.cuda.cufft' extension
    gcc -pthread -B /home/leofang/miniconda3/envs/cupy_cuda102_dev/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_FORCE_INLINES=1 -DCUPY_CUB_VERSION_CODE=100800 -I/home/leofang/dev/cupy_cuda10.2/install/../cupy/core/include/cupy/cub -I/home/leofang/dev/cupy_cuda10.2/install/../cupy/core/include -I/usr/local/cuda-10.2/include -I/home/leofang/sources/libcutensor-1.2.0/include -I/home/leofang/miniconda3/envs/cupy_cuda102_dev/include/python3.7m -c cupy/cuda/cufft.cpp -o build/temp.linux-x86_64-3.7/cupy/cuda/cufft.o -fopenmp
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    g++ -pthread -shared -B /home/leofang/miniconda3/envs/cupy_cuda102_dev/compiler_compat -L/home/leofang/miniconda3/envs/cupy_cuda102_dev/lib -Wl,-rpath=/home/leofang/miniconda3/envs/cupy_cuda102_dev/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/cupy/cuda/cufft.o -L/usr/local/cuda-10.2/lib64 -L/home/leofang/sources/libcutensor-1.2.0/lib/10.2 -lcuda -lcudart -lcufft_static -lculibos -o build/lib.linux-x86_64-3.7/cupy/cuda/cufft.cpython-37m-x86_64-linux-gnu.so -Wl,--disable-new-dtags,-rpath,/usr/local/cuda-10.2/lib64,-rpath,/home/leofang/sources/libcutensor-1.2.0/lib/10.2
```

**Comment by leofang** [comment]
I think the ultimate question is whether it's possible to wrap `cufftXtSetCallback` in a shared library (so that we can call it from Python). Looks like the answer is no.

**Comment by leofang** [comment]
> The undefined symbol error can be reproduced simply by building from my branch: https://github.com/leofang/cupy/tree/cufft_retry.

I have a working prototype in this branch! Will polish it and send a PR.

**Comment by llukas** [comment]
@leofang sorry for late reply, what was missing in link above is device link, if you use nvcc to link it does it automatically, if you use host linker then you need to produce *.o with device code linked (nvcc -dlink)

> I think the ultimate question is whether it's possible to wrap cufftXtSetCallback in a shared library (so that we can call it from Python). Looks like the answer is no.

If your callback functions are known at time of linking this shared library then yes. In other cases no.

**Comment by leofang** [comment]
Hello @llukas, thanks for your comments! 

> what was missing in link above is device link, if you use nvcc to link it does it automatically, if you use host linker then you need to produce *.o with device code linked (nvcc -dlink)

Yeah I know. The example code was mainly to show what I meant by leakage of undefined symbols. When we first started working on this, @maxpkatz helped me ensure we did exactly what's needed (`nvcc -dc` -> `nvcc -dlink` -> `gcc` to link all objects). I also repeated everything myself when I started #4141 as you may have noticed, since I lost the previous attempt code, and still got no luck.

> If your callback functions are known at time of linking this shared library then yes. In other cases no.

Yes, I figured it out too 🎉 so in #4141 the first key is to generate a shared library (for Python module) per pair of load/store callbacks. But it's not enough. The second key is to use `nvcc -shared` to do the final linking, instead of `gcc -shared`, otherwise there would a different set of symbols (from cuFFT callback's) leaking into the module. Very, very weird, and counter-intuitive...

**Comment by leofang** [comment]
@llukas @mnicely Any chance you know the callback linking must be done by a c++ compiler (ex: g++)? We are experiencing some issues in which if the host compiler is specified as `gcc` instead of `g++`, there'd be undefined symbols:
```
E   /home/jenkins-external-slave/.chainer-test/.cupy/cupy_callback_73a6d618332a23385893bf640c1dbaa5.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cxa_pure_virtual
```
see, e.g. https://jenkins.preferred.jp/job/chainer/job/chainer-test_pr/231/label=mn1-p100,test=cupy-combination/testReport/junit/tests.cupy_tests.fft_tests.test_fft/Test1dCallbacks_param_0_%7Bn=None,%20norm=None,%20shape=(10,%207)%7D/test_fft_load/

cc: @emcastillo

**Comment by mnicely** [comment]
Interesting :thinking: 
I'm not sure, but I'll check with @llukas
