### ISSUE TITLE
`cublasGemmEx` should only be used when compute capablity >= 5.0

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#4111]
As reported here: https://groups.google.com/g/cupy/c/mgQ_bCFu9Jw/m/q4MRLI_ZAAAJ

`cublasGemmEx` does not run on CC < 5.0 hardware, but it is always used when CUDA >= 11.0.

https://github.com/cupy/cupy/blob/v8.0.0/cupy/core/core.pyx#L2893-L2959

cc/ @anaruse

**Comment by anaruse** [comment]
Thank you for reporting the issue.
Sorry, I didn't check the compute capability.
This issue should be fixed by a PR https://github.com/cupy/cupy/issues/4111.
