### ISSUE TITLE
Cupy concurrency does not work with for loop

### ISSUE THREAD

**Issue by itisyeetimetoday** [cupy/cupy#4131]
I'm currency write code that requires iterating over a point cloud, and as a result, I often need to use for loops. More specifically, I'm trying to calculate the distance of each point from each other, where a first row is the distance of the first point from all the other points, the second row is the distance of the second point to all the other points, etc. Here is my repo, where I created a minamal reproducible example: https://github.com/itisyeetimetoday/outlier-cupy-concurrency  In Screenshot (9).png, I have the for loop, and as you can see, each stream runs serially. However, when I replaced the index variable that is passed to linalg.norm with a constant, I got the result in Screenshot (10).png, which is clearly parallel. Could someone suggest an alternative to a for loop for my use case, without rewriting a cupy elementwise, etc kernel? Thank you.

**Comment by kmaehashi** [comment]
I think this is also related to the synchronization issue. Let's continue discuss in #4026.
