### ISSUE TITLE
ROCm 3.5+ support roadmap

### ISSUE THREAD

**Issue by emcastillo** [cupy/cupy#4132]
Tracking issue for ROCm tasks before v9
@leofang 

- rocSOLVER/ hipMAGMA

**Comment by leofang** [comment]
Library support:
- sparse: #4101 
- dnn: #4100 

Improvement:
- move from hipBLAS to rocBLAS (#3989)
- SVD (available since ROCm 3.8.0?)

Known bugs:
- #4078 
- #3841 
- #3834 
- #3833

**Comment by leofang** [comment]
Looks like ROCm 3.9.0 is out...😞😞😞

**Comment by leofang** [comment]
> Looks like ROCm 3.9.0 is out...😞😞😞

It seems CuPy master builds just fine on 3.9.0: https://ci.preferred.jp/cupy.py3.amd/64299/

**Comment by leofang** [comment]
btw I noticed the cythonized .c & .cpp codes could be very different between CUDA and HIP builds, so if uploading sdist to PyPI is on the roadmap, this issue must be addressed (ex: can we upload two sets of sdist, one for CUDA and the other for HIP?)

**Comment by leofang** [comment]
ROCm 3.10:
<img width="384" alt="rocsolverAPI" src="https://user-images.githubusercontent.com/5534781/101657748-3d778f00-3a12-11eb-8665-88bdc0545318.PNG">
https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html#new-rocsolver-apis

**Comment by kmaehashi** [comment]
https://github.com/cupy/cupy/pull/4461

> grids with total size of 2**32 do not launch threads at all.

this is not fixed as of ROCm 3.10/4.0.0.

**Comment by kmaehashi** [comment]
We have to take care of branching based on CUDA versions.
e.g. https://github.com/cupy/cupy/blob/65ca0818b8c922e52adf2c5788226316849c60d7/cupy/core/core.pyx#L1971-L1977

**Comment by leofang** [comment]
> We have to take care of branching based on CUDA versions.

@kmaehashi This will be handled in #4102.

**Comment by kmaehashi** [comment]
> > We have to take care of branching based on CUDA versions.

> @kmaehashi This will be handled in #4102.

Ah, nice! 👍🏼

**Comment by leofang** [comment]
I noticed that in many tests we call `runtimeGetVersion()` to determine whether to skip a test. The effect of this on HIP is to skip unconditionally, as in HIP `runtimeGetVersion()` gives an elusive version like 3212 (likely from the HIP runtime `ROCclr`, in which `AMD_PLATFORM_BUILD_NUMBER` is defined as such) that is much smaller that the currently supported CUDA versions. This is OK, but we should probably revisit it at some point.

**Comment by leofang** [comment]
For texture memory: ROCm has a renewed interest since 3.6.0 (the support is added in the ROCclr layer). I have a local branch that makes host-device texture copy work: https://github.com/leofang/cupy/tree/hip_texture, but device-device copy is not working. I consider this a low priority unless there are ROCm users who have a serious need, otherwise I think we should disable texture support and tests until ROCm catches up.

**Comment by kmaehashi** [comment]
I started to publish ROCm 4.0 test results for the latest matser branch commit, every 1 hour (note that the full unit test takes 4 hours):
https://github.com/kmaehashi/cupy-rocm-ci-report/commits/gh-pages
(It seems there’s a breaking change for ROCm between commit 1f6f9ebe1  and f1bda44e1 ...)

I've asked @takagi to work on resolving test failures.

**Comment by leofang** [comment]
> (It seems there’s a breaking change for ROCm between commit [1f6f9eb](https://github.com/cupy/cupy/commit/1f6f9ebe161858bfc7777252484cb327bbfc1931) and [f1bda44](https://github.com/cupy/cupy/commit/f1bda44e190a07ca6f699d21b67cc31b3a53b8bc) ...)

```
tests/cupy_tests/cuda_tests/test_stream.py ..Fatal Python error: Segmentation fault
```
@kmaehashi @takagi It's likely we forgot to disable testing PTDS (#4322) on HIP. We hit the same segfault before.

**Comment by leofang** [comment]
I sent #4651 to fix PTDS.

**Comment by leofang** [comment]
Looks like we are back to the game after merging #4651 🙂
https://github.com/kmaehashi/cupy-rocm-ci-report/commit/989f57fb33a2ed8b36d2a54d59cee45cdd233810

**Comment by leofang** [comment]
@kmaehashi The ROCm CI hasn't been active for most of the day, is this expected?
https://github.com/kmaehashi/cupy-rocm-ci-report/tree/gh-pages

**Comment by kmaehashi** [comment]
The CI script has died with `srun: error: Node failure on xxx-xxx2-09`... modified the script to respawn when node failed, and restarted.

**Comment by leofang** [comment]
Cool, thanks. Maybe it was due to allocation timeout?

**Comment by kmaehashi** [comment]
The CI script is on the login node, and I'm `srun`ing for every test run, so I guess it's unlikely.
https://github.com/kmaehashi/cupy-rocm-ci-report/blob/master/tools/daemon.sh

**Comment by leofang** [comment]
I see, I thought it's run on the compute node interactively.

**Comment by leofang** [comment]
@kmaehashi @takagi Looks like something went wrong recently. The number of CI errors went from 9X to 18X:
https://github.com/kmaehashi/cupy-rocm-ci-report/compare/ce51038..d66d2c55
Looks like sorting is broken.

**Comment by leofang** [comment]
> @kmaehashi @takagi Looks like something went wrong recently. The number of CI errors went from 9X to 18X:
> https://github.com/kmaehashi/cupy-rocm-ci-report/compare/ce51038..d66d2c55
> Looks like sorting is broken.

This is the offending commit: https://github.com/cupy/cupy/commit/74c54b07a9d8a0f1c0130e6cfec989b3aa3ed867

**Comment by takagi** [comment]
Newly got strange failures...

```
FAILED tests/cupy_tests/lib_tests/test_polynomial.py::TestPoly1dInit_param_0_{variable=None}::test_poly1d_numpy_poly1d
FAILED tests/cupy_tests/lib_tests/test_polynomial.py::TestPoly1dInit_param_0_{variable=None}::test_poly1d_numpy_poly1d_variable
FAILED tests/cupy_tests/lib_tests/test_polynomial.py::TestPoly1dInit_param_1_{variable='y'}::test_poly1d_numpy_poly1d
FAILED tests/cupy_tests/lib_tests/test_polynomial.py::TestPoly1dInit_param_1_{variable='y'}::test_poly1d_numpy_poly1d_variable
```
```
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 2 / 5 (40%)
E       Max absolute difference: 1.
E       Max relative difference: 1.
E        x: array([0.   , 1.875, 3.   , 4.   , 5.   ], dtype=float32)
E        y: array([1., 2., 3., 4., 5.], dtype=float32)
```

```
>>> import cupy, numpy
>>> cupy.asarray(numpy.arange(5, dtype='d')+1).get()
array([1., 2., 3., 4., 5.])
>>> cupy.asarray(numpy.arange(5, dtype='f')+1).get()
array([0.   , 1.875, 3.   , 4.   , 5.   ], dtype=float32)
```

`1.875` is higher four bytes of double `1.0` interpreted as a (single) float so the first two elements seem to be occupied by `1.0` in double.

**Comment by kmaehashi** [comment]
It's ok to close this?

**Comment by leofang** [comment]
I dunno 😅 Do we want to resolve all xfail tests first (if at all possible)?

**Comment by takagi** [comment]
Let's close this as the situation is updated.
