### ISSUE TITLE
Add `cupy.random.BitGenerator` and `cupy.random.Generator`

### ISSUE THREAD

**Issue by emcastillo** [cupy/cupy#4163]
In order to match NumPy's new random API, these mechanisms need to be added.

There are two main issues that I am currently working on:
1st, curand, and NumPy random generators are not equivalent.
NumPy supports
- PCG64 (PCG XSL RR 128/64) 128 bit state/ 64 bit output
- MT19937
- Philox 4x64
- SFC64

And the only one available in curand is mt19937.
Moreover, in the current `cupy.random.RandomState`, when distributions are generated, in some of them the specified curand generator is ignored, and a custom xor based random bits generator is used in the device code. 

To draw samples from a distribution, most of the kernels rely on a sample-rejection mechanism, so in order to consistently use the user-specified random generator inside these kernels, curand generators need to be device callable. But curand does not work with NVRTC (@anaruse any hint about this?). We need to create an additional .cu file with the distributions and mechanism to draw samples from either curand generators or custom ones inside the kernels generating the distributions.

**Comment by toslunar** [comment]
See also #1431.

**Comment by leofang** [comment]
Cool, didn't know there's device API!
