### ISSUE TITLE
`sparse.coo_matrix.tocsr` memory release issue 

### ISSUE THREAD

**Issue by Yuriyzabegaev** [cupy/cupy#4171]
I have `cupy.sparse.coo_matrix` and construct `csr_matrix` from it with method `tocsr`. After it I release memory with `free_all_blocks`. Then I check number of free blocks with `n_free_blocks`. I expect 0 free block in memory pool right after `free_all_blocks`, but it shows 1 free block.

Conditions:
> CuPy Version          : 8.0.0
> CUDA Root             : /usr/local/cuda
> CUDA Build Version    : 10000
> CUDA Driver Version   : 10020
> CUDA Runtime Version  : 10000
> cuBLAS Version        : 10000
> cuFFT Version         : 10000
> cuRAND Version        : 10000
> cuSOLVER Version      : (10, 0, 0)
> cuSPARSE Version      : 10000
> NVRTC Version         : (10, 0)
> Thrust Version        : 100903
> CUB Build Version     : <unknown>
> cuDNN Build Version   : 7603
> cuDNN Version         : 7603
> NCCL Build Version    : 2408
> NCCL Runtime Version  : 2408
> cuTENSOR Version      : None

Code to reproduce:
```
import cupy as cp

MEMPOOL = cp.get_default_memory_pool()

def free():
    MEMPOOL.free_all_blocks()
    print('Used bytes now:  ', MEMPOOL.used_bytes())
    print('Total bytes now: ', MEMPOOL.total_bytes())
    print('Free bytes now:  ', MEMPOOL.free_bytes())
    print('Free blocks now: ', MEMPOOL.n_free_blocks())

print('Initial memory:')
free()
coo_col = cp.array([0, 1, 2, 0, 1, 2, 0, 1, 2])
coo_row = cp.array([0, 0, 0, 1, 1, 1, 2, 2, 2])
coo_data = cp.ones(9).astype(float)
coo_mat = cp.sparse.coo_matrix((coo_data, (coo_row, coo_col)))
del coo_col
del coo_row
del coo_data

print('\nReleasing before constructing CSR from COO:')
free()
csr_mat = coo_mat.tocsr()
del coo_mat

print('\nReleasing after constructing CSR from COO:')
free()

del csr_mat
print('\nReleasing after deleting CSR:')
free()
```

Output:

> Initial memory:
> Used bytes now:   0
> Total bytes now:  0
> Free bytes now:   0
> Free blocks now:  0
> 
> Releasing before constructing CSR from COO:
> Used bytes now:   1536
> Total bytes now:  1536
> Free bytes now:   0
> Free blocks now:  0
> 
> Releasing after constructing CSR from COO:
> Used bytes now:   1536
> Total bytes now:  2048
> Free bytes now:   512
> Free blocks now:  1
> 
> Releasing after deleting CSR:
> Used bytes now:   0
> Total bytes now:  0
> Free bytes now:   0
> Free blocks now:  0

**Comment by takagi** [comment]
Thanks for reporting. I can reproduce the result above.

CuPy's memory pool may split a pooled block to a smaller size required for space efficiency, and the split block is not freed until all its parts are put back to the pool even when `free_all_blocks` is called. In that sense, the behavior is valid. Maybe it should be described in the reference.

Or You mean something another?

**Comment by Yuriyzabegaev** [comment]
Thanks for explaining. Well it's not a memory leak! I'm closing the issue.
