### ISSUE TITLE
[Feature Request] Add Cupy.delete

### ISSUE THREAD

**Issue by stanleyshly** [cupy/cupy#4176]
Usage:
Currently, numpy.delete is a very often used function, as it allows numpy row/columns to be quickly and efficiently deleted from an array. However, this function does not exist in cupy.
Proposal:
I would suggest writing a function that hopefully be run synchronously, which works as close as possible to the numpy.delete function, but runs on the GPU.

**Comment by IchiruTake** [comment]
Same request

**Comment by IchiruTake** [comment]
> Usage:
> Currently, numpy.delete is a very function, as it allows numpy row/columns to be quickly and efficiently deleted from an array. However, this function does not exist in cupy.
> Proposal:
> I would suggest writing a function that hopefully be run synchronously, which works as close as possible to the numpy.delete function, but runs on the GPU.

I have searched once but it seems CuPy does not own that feature. I have used Cupy to check array_equal but don't have its delete function. I have posted a request about array_equal

**Comment by dwysocki** [comment]
I assume this was omitted because it's not going to be well-suited to a GPU?  Either way, it should at least be possible to work around it if need be using array indexing instead, even if it's less efficient.

Is there any plan to implement this in CuPy anyway?

**Comment by kmaehashi** [comment]
Implemented via #7359
