### ISSUE TITLE
Question: maximum ndim discrepancy between CuPy and NumPy?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#4193]
I noticed in CuPy we set `MAX_NDIM = 25`:
https://github.com/cupy/cupy/blob/46e5ff0bdf401ad88f404cd7cb7d26dd62b061c0/cupy/core/_carray.pxd#L10
whereas in NumPy this is set to 32 more than a decade ago:
https://github.com/numpy/numpy/blob/9563a3a63fd3dfb3b687fbabad134b5ded72bd46/numpy/core/include/numpy/ndarraytypes.h#L40

Is there a particular reason to pick 25? I was experimenting some iterator stuff and realized I need to know the largest possible `ndim` at build time. I can work around things so this is not critical at all, just simply curious.

**Comment by leofang** [comment]
Looks like NumPy has a sanity check for this limit:
```python
>>> import numpy as np
>>> a = np.arange(33)
>>> a = a.reshape(range(33))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: maximum supported dimension for an ndarray is 32, found 33
>>> 
>>> import cupy as cp
>>> a = cp.arange(33)
>>> a = a.reshape(range(33))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 542, in cupy.core.core.ndarray.reshape
    return _manipulation._ndarray_reshape(self, shape, order)
  File "cupy/core/_routines_manipulation.pyx", line 79, in cupy.core._routines_manipulation._ndarray_reshape
    return _reshape(self, shape)
  File "cupy/core/_routines_manipulation.pyx", line 317, in cupy.core._routines_manipulation._reshape
    raise ValueError('cannot reshape array of size {}'
ValueError: cannot reshape array of size 33 into shape 0
```

**Comment by leofang** [comment]
Might consider this as a compatibility issue?
```python
>>> import numpy as np
>>> import cupy as cp
>>>
>>> x = [1]*33
>>> x[-1] = 33
>>> x = tuple(x)
>>> x
(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 33)
>>> len(x)
33
>>>
>>> # test numpy max ndim
>>> a = np.arange(33)
>>> a = a.reshape(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: maximum supported dimension for an ndarray is 32, found 33
>>>
>>> # test cupy max ndim
>>> a = cp.arange(33)
>>> a = a.reshape(x)
>>> a.ndim
33
```

**Comment by IchiruTake** [comment]
> Might consider this as a compatibility issue?
> 
> ```python
> >>> import numpy as np
> >>> import cupy as cp
> >>>
> >>> x = [1]*33
> >>> x[-1] = 33
> >>> x = tuple(x)
> >>> x
> (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 33)
> >>> len(x)
> 33
> >>>
> >>> # test numpy max ndim
> >>> a = np.arange(33)
> >>> a = a.reshape(x)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ValueError: maximum supported dimension for an ndarray is 32, found 33
> >>>
> >>> # test cupy max ndim
> >>> a = cp.arange(33)
> >>> a = a.reshape(x)
> >>> a.ndim
> 33
> ```

Hugh error, although I haven't used this feature once

**Comment by kmaehashi** [comment]
I talked with @okuta regarding this. It seems there's no strong reason why 25 is picked. I think changing it to 32 for NumPy compatibility is better (but must verify that there's no strong performance degradation).

If I recall correctly there was a MAX_NDIM validation in the past versions of CuPy but seems it's lost at some point. It should be added too.

**Comment by beam2d** [comment]
Yeah, if I remember correctly. That just meant there was a well-used tensor library that chose the number without any problem for years.

**Comment by leofang** [comment]
Thanks @kmaehashi @beam2d!

> I think changing it to 32 for NumPy compatibility is better (but must verify that there's no huge performance degradation).

I was actually wondering whether changing it to 32 would *improve* performance or not, as it'd likely make the struct aligned.

**Comment by leofang** [comment]
I'd suggest to bump `MAX_NDIM` to at least 32 (NumPy) or 40 (cuTENSOR).
