### ISSUE TITLE
hip runtime compilation bug in simple cupy code

### ISSUE THREAD

**Issue by ipe-zhangyz** [cupy/cupy#4216]
Hello, I'm trying to use cupy with AMD MI50 GPUs and I find that there is a bug in the hip runtime compilation code.  Running this simple code piece will get these error messages:

```
import numpy as np
import cupy as cp

squared_diff = cp.ElementwiseKernel(
    'float32 x, float32 y',
    'float32 z',
    'z = (x - y) * (x - y)',
    'squared_diff')

x = cp.arange(10, dtype=np.float32).reshape(2, 5)
y = cp.arange(5, dtype=np.float32)
squared_diff(x, y)

```
```
Traceback (most recent call last):
  File "/home/.conda/envs/cupy/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 512, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 108, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 122, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 58, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: HIPRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "111.py", line 10, in <module>
    x = cp.arange(10, dtype=np.float32).reshape(2, 5)
  File "/home/.conda/envs/cupy/lib/python3.8/site-packages/cupy/_creation/ranges.py", line 57, in arange
    _arange_ufunc(typ(start), typ(step), ret, dtype=dtype)
  File "cupy/core/_kernel.pyx", line 1084, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/_kernel.pyx", line 1107, in cupy.core._kernel.ufunc._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 881, in cupy.core._kernel._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 60, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/core.pyx", line 1921, in cupy.core.core.compile_with_cache
  File "/home/.conda/envs/cupy/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 324, in compile_with_cache
    return _compile_with_cache_hip(
  File "/home/.conda/envs/cupy/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 662, in _compile_with_cache_hip
    binary = compile_using_nvrtc(source, options, arch, name + '.cu')
  File "/home/.conda/envs/cupy/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 163, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "/home/.conda/envs/cupy/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 144, in _compile
    prog = _NVRTCProgram(source, cu_path,
  File "/home/.conda/envs/cupy/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 523, in compile
    raise CompileException(log, self.src, self.name, options, 'nvrtc')
cupy.cuda.compiler.CompileException: /tmp/comgr-2f0b69/input/CompileSource:2:10: fatal error: 'cupy/complex.cuh' file not found
#include <cupy/complex.cuh>
         ^~~~~~~~~~~~~~~~~~
1 error generated when compiling for gfx906.
Error: Failed to compile opencl source (from CL or HIP source to LLVM IR).
```
I've already found that it's the hiprtcCompileProgram API in cupy/cupy_backends/cuda/libs/cupy_hiprtc.h that cause this problem and I have submitted an issue to the HIP project https://github.com/ROCm-Developer-Tools/HIP/issues/2182#issue-731199084.
I'm curious if anyone else encountered this problem.

**Comment by leofang** [comment]
Thanks for reporting. This is a known issue in ROCm that hipRTC does not recognize the -I option. However, a workaround has been made on our side to avoid this. May I ask how did you install your CuPy, which version/branch did you use, etc?

**Comment by leofang** [comment]
Notes:
1. The workaround to which I referred was added in #3823: https://github.com/cupy/cupy/blob/50361e0d42ca8e41e7200382c3031cfc4e201764/cupy/cuda/compiler.py#L613-L627
2. I just checked that this hipRTC bug is still present in ROCm 3.8.0
3. I can run @ipe-zhangyz's sample code locally on two different machines without problem. (One with Radeon VII (gfx906) + ROCm 3.5.0, the other with the same GPU + ROCm 3.8.0.)

**Comment by ipe-zhangyz** [comment]
Thank you @leofang ! The version I installed before is v8.0.0rc1.  I installed it on a server with CentOS 7.6 and ROCM 3.5 from source in this steps:
```
$ cd cupy
$ export HCC_AMDGPU_TARGET=gfx906
$ export __HIP_PLATFORM_HCC__
$ export CUPY_INSTALL_USE_HIP=1
$ export ROCM_HOME=/opt/rocm/rocm-3.5.0
$ pip install .

```
I've switched to v8.0.0 and reinstalled  it in the same steps. My test code can run now.

**Comment by leofang** [comment]
Thanks for confirming, @ipe-zhangyz. Yes, this was fixed between v8.0rc1 and v8.0, so you had the buggy version installed 😅

**Comment by ipe-zhangyz** [comment]
Hi @leofang , I find that you have done many tests of cupy on rocm platform. I also want to do a systematical test on my CentOS 7.6 + rocm 3.5 server, as the official supported OS of hip is usually ubuntu. Could you please tell me how do you do your tests? Did you use the code in the source code of cupy, or you write your own test codes? If it is the first case, is there any simple command to run all the test cases at once? Thank you！

**Comment by leofang** [comment]
The current CuPy test suite has a great coverage, some much more extensive than NVIDIA's internal ones that we were able to catch a dozen of CUDA bugs in the past. I'd say if you're super interested, running CuPy's tests locally (given that you already built from source) is the best. You can do it as simple as `pytest tests/` to run them all!

However, I don't recommend you to do this for the moment. If you search my ID, you can see I've already found a bunch of ROCm bugs, and between I and PFN (the company behind CuPy) we have a much longer bug list not tracked on this issue tracker. Some bugs are serious enough that you would just get segfaults. The more severe issue is hipRTC is >5x slower than NVRTC, so unlike on NVIDIA GPUs we couldn't run the full tests within a reasonable amount of time on AMD GPUs. I'll be slowly working on this when I have time & hear more from AMD, but in the meanwhile I suggest the way to go is to first run your own applications written in CuPy, and see whether they like AMD GPUs or not. This is more reasonable than trying to make sure everything work at once...

**Comment by ipe-zhangyz** [comment]
Thanks for your advice! I just tried the cases on the cupy tutorial web page. Most of them work on my machine, however, I find that if the kernel in my source file includes some headers, like this:
```
import numpy as np
import cupy as cp

complex_kernel = cp.RawKernel(r'''
    #include <cupy/complex.cuh>
    extern "C" __global__
    void my_func(const complex<float>* x1, const complex<float>* x2,
                 complex<float>* y, float a) {
        int tid = blockDim.x * blockIdx.x + threadIdx.x;
        y[tid] = x1[tid] + a * x2[tid];
    }
    ''', 'my_func')

x1 = cp.arange(25, dtype=cp.complex64).reshape(5, 5)
x2 = 1j*cp.arange(25, dtype=cp.complex64).reshape(5, 5)
y = cp.zeros((5, 5), dtype=cp.complex64)
complex_kernel((5,), (5,), (x1, x2, y, cp.float32(2.0)))  # grid, block and arguments
print(y)

```
I will still encounter the hiprtc error for not found the header file. I can include the absolute path to the header, but if the header itself includes some other header files, the error still occurs. Is there any workaround for this problem?

**Comment by leofang** [comment]
For RawKernel and RawModule, you can set `backend='nvcc'` to make it use hipcc. It's probably a confusing name for ROCm users that we should change.

**Comment by ipe-zhangyz** [comment]
Thank you! @leofang Now all of my test cases are passed.
