### ISSUE TITLE
Check number and types of args passed to RawKernel function?

### ISSUE THREAD

**Issue by ooreilly** [cupy/cupy#4246]
Hello CuPy developers,
I noticed that if you pass the wrong number or types of input arguments to RawKernel that CuPy crashes. What do you think about adding some checks?
```python
source = "extern "C" __global__ void test(float *arg1, float *arg2, const int n) {  } " 
test = cupy.RawKernel(source, "test")
grid=(1,)
block=(1,)
```
```python
# 1. Too few input arguments
args = (arg1, arg2)
# Segmentation fault (CUDA_ERROR_ILLEGAL_ADDRESS)
# test(grid, block, args)

# 2. Too many input arguments
args = (arg1, arg2, arg2, n)

# 3. Wrong type for input argument #1 (0-based)
args = (arg1, n, arg2)
```
If you think it is a good idea, I would be happy to try to contribute a PR.

**Comment by leofang** [comment]
IMHO this is a very hard task with potentially non-negligible overhead, which I strive to avoid. The problem with RawKernels/RawModules is that they also support template arguments, texture objects, struct inputs, etc, whose types are not easy to deduce if not impossible. My 2 cents is that if users are brave enough to write their own CUDA C++ kernels, it should be fairly easy for them to detect issues like these.

For the problem No.2, we actually hit this issue before, and to me it's a bug in CUDA driver API.

I think your suggestion may well align with the ongoing JIT work #3392. There it'd be much easier to detect argument numbers and types by inspecting the Python objects (as opposed to pure code strings here).

**Comment by ooreilly** [comment]
Thank you for your detailed explanation and for your input. I didn’t think about how complicated it can get when you need to support type deduction for structs and template parameters. Also, I agree that you definitely don’t want to add a lot of overhead for having a little bit of convenience. 

I am pretty good at making mistakes, especially when the kernel has to take in a lot of args. What I will probably do for now is to write my own python function that will use some regex to parse the function signature and do some type checking for constants and pointers, but without supporting structs and templates. 

The JIT work looks really interesting and promising.

**Comment by leofang** [comment]
> What I will probably do for now is to write my own python function that will use some regex to parse the function signature and do some type checking for constants and pointers, but without supporting structs and templates.

@ooreilly It would be great if you could point me to how you achieve this with regex! 🙂 I am not a regex user but I know it can be very powerful. I might be able to apply a similar approach elsewhere.

**Comment by ooreilly** [comment]
@leofang sorry it took a while for me to get back to you, busy day here! I agree with you, regex is really powerful.  I was able to get started on checking the number of args with regex. Usually, what I do when I try to build something with regex is to use this nice tool: https://regexr.com/. If you copy and paste the regex below (with some small modifications) into regexr.com, it can explain it piece by piece. Here is the key code I ended up with:
```python
import re
regex = r'extern\s+"C"\s+__global__\s+void\s+%s\s*\(([\w\W]+?)\)' % function
pattern = re.compile(regex, re.MULTILINE)
match = re.findall(pattern, source)
```
and here's the complete code I wrote: https://github.com/ooreilly/cucheckargs. I hope you find it useful. Note that I haven't done any type checking yet (just number of args). I'll save that for another day. Let me know if you have any questions or if there's anything I can do to help.

**Comment by leofang** [comment]
Thanks, @ooreilly! Already bookmarked your repo and regexr.com (looks like a nice resource) 👍

Maybe I should move the discussion to your repo. Your `regex` line made me wonder if there's an easy way to parse multiple kernels in a common `extern` block? Something like this:
```python
source = r'''
extern "C" {
__global__ void x1(float* y) {}
__global__ void x2(double* y) {}
}
'''

**Comment by ooreilly** [comment]
Nice!

Sure. Up to you if you want to continue the conversation there. Yes, what you are asking for should be possible to do in a single pass. I can try to do that on Thursday for you. You could also do a double pass where you first search for the `extern "C"` block and then extract each function in a second search. Do you want to grab all functions within the extern block or just a specific one?

**Comment by mnicely** [comment]
@leofang I'm pretty sure the `log_stream` method you and I added should have caught this error just as if you compile directly with NVCC/NVRTC.

I agree with @leofang that while the regex feature would be useful, it also chips away at the speed-of-line performance.

@ooreilly Would you might giving it a try and let us know the output? https://docs.cupy.dev/en/stable/reference/generated/cupy.RawKernel.html#cupy.RawKernel

**Comment by leofang** [comment]
@mnicely I thought @ooreilly's problems happen at kernel launch time, not at compile time?

**Comment by mnicely** [comment]
Oh okay. Completely missed that. Is there any cuda error checking built-in? That could be activated by passing a flag? I’ve never thought about it until know. Use it when your developing/debugging and turn it off when your finished

**Comment by leofang** [comment]
> Is there any cuda error checking built-in? 

Yes, for CUDA driver/runtime API and other CUDA libraries we check the return value and convert it to Python exceptions, for example here: 
https://github.com/cupy/cupy/blob/ed52a652ed9fb30b9c78378cad2aa38a45526eeb/cupy_backends/cuda/api/driver.pyx#L122-L124
The problem, at least in his 2nd example, is that CUDA driver API would actually return `CUDA_SUCCESS` despite that the argument number mismatches with what's declared in the kernel. I suspect `cuLaunchKernel` doesn't really check (or have no way to check) this.

**Comment by mnicely** [comment]
> I suspect cuLaunchKernel doesn't really check (or have no way to check) this.

We might need to file a bug. Having too many parameter should return a illegal address error

**Comment by leofang** [comment]
You know, one nice thing I enjoy when working with NVIDIA people is that there's always someone kind enough to do this for me so that I never have to file bugs myself 😂😂😂

**Comment by mnicely** [comment]
@leofang No problem. I just need a few days to create an example to submit. I'm swamped with my new position!

**Comment by leofang** [comment]
Haha, no pressure Matt! (And congrats!)

**Comment by ooreilly** [comment]
@leofang, I finally had time to update the regex function to handle extern blocks.
