### ISSUE TITLE
ROCm: HIP does not provide math_constants.h 

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#4268]
In a number of places in the codebase, we use constants like `CUDART_NAN`:
https://github.com/cupy/cupy/blob/fd11f0d917426cea9c4f3658e5d8b8cf7c9d56f2/cupyx/scipy/ndimage/_filters_core.py#L261-L266
But HIP does not provide `math_constants.h`, so any code involving math constants will fail. Looks like we need to provide a stub file on our own?

**Comment by grlee77** [comment]
In I prior PR, I had originally tried to define NAN and INF when I didn't know about the CUDART_NAN and CUDART_INF defines. Perhaps those can be used to define CUDART_NAN and CUDART_INF for HIP? see: https://github.com/cupy/cupy/pull/2861/commits/c06acf6d6632975c8e6c3f92df3c9bf59bd1d843#

**Comment by leofang** [comment]
Cool, yeah I think this is exactly what `math_constants.h` in CUDA does too:
```C
/* single precision constants */
#define CUDART_INF_F            __int_as_float(0x7f800000)
#define CUDART_NAN_F            __int_as_float(0x7fffffff)
#define CUDART_MIN_DENORM_F     __int_as_float(0x00000001)
#define CUDART_MAX_NORMAL_F     __int_as_float(0x7f7fffff)
#define CUDART_NEG_ZERO_F       __int_as_float(0x80000000)
#define CUDART_ZERO_F           0.0f
#define CUDART_ONE_F            1.0f
...
```
So a stub file can be generated as easy as copying all contents from there.
