### ISSUE TITLE
array and asarray incorrectly convert some arrays

### ISSUE THREAD

**Issue by brandondube** [cupy/cupy#4288]
Download reference data from https://wfirst.ipac.caltech.edu/sims/Coronagraph_pupil_masks.html
WFIRST Pre-cycle 5 pupil, 1000x1000 pixels (FITS file).

Per the FITS standard, this data is big endian.  The data of the particular file is 64-bit / double precision.

Reproducible script:
```python
from astropy.io import fits
import cupy as cp

d = fits.getdata('wfirst_pre-cycle5_pupil_D1000pix.fits')
dd = cp.array(d)
print(d.max(), dd.max())
print(d.flags)

1.0 4.633986936687488e+307
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```

The "white" part of the mask should be 1, but cupy converts it to something a few bits from the max value for a double.
Doing an astype on it converts the max to Inf, as well, but I think it should become NaN (not representable, anyway)  Or wrap...

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
```
OS                           : Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core
CuPy Version                 : 8.1.0
NumPy Version                : 1.19.2
SciPy Version                : 1.5.2
CUDA Root                    : /usr/local/cuda
CUDA Build Version           : 10020
CUDA Driver Version          : 10020
CUDA Runtime Version         : 10020
cuBLAS Version               : 10202
cuFFT Version                : 10102
cuRAND Version               : 10102
cuSOLVER Version             : (10, 3, 0)
cuSPARSE Version             : 10301
NVRTC Version                : (10, 2)
Thrust Version               : 100907
CUB Build Version            : 100800
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : 2708
NCCL Runtime Version         : 2708
cuTENSOR Version             : None
Device 0 Name                : TITAN Xp
Device 0 Compute Capability  : 61
Device 1 Name                : TITAN Xp
Device 1 Compute Capability  : 61
```
python 3.7.9 from conda.

**Comment by leofang** [comment]
I think it is a known issue that CuPy currently does not support big-endian arrays (#3652). The discussion and workaround there might be relevant for you. I am unaware of anyone working on this support at the moment.

**Comment by brandondube** [comment]
There is a widespread question of what to do about BE.  For the case of `array` or `asarray` which are used to transfer the data from host->device, could cupy just convert the endianness?  Numpy has a method `ary.byteswap()`.

The logic to handle edge cases could look something like...

```
# ary = np.array with dtype('>f8')
dtyp = ary.dtype
if `>` in dtyp:
    # look for indicator of data size and format (f vs i vs u), use .astype to convert to LE
ary = cp.asarray_guts(ary)

**Comment by kmaehashi** [comment]
Thank you for the report! We discussed this today and prioritized issue #3652. We will be fixing to automatically convert big-endian NumPy arrays to little-endian in `array`/`asarray`. This will be backported to v8 as we considere this as bug.

Let's continue discussing further in #3652 if needed.
