### ISSUE TITLE
cupy.random.bytes not working

### ISSUE THREAD

**Issue by lucasrodes** [cupy/cupy#4312]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)

```
OS                           : Linux-5.9.8-2-MANJARO-x86_64-with-arch-Manjaro-Linux
CuPy Version                 : 8.1.0
NumPy Version                : 1.19.4
SciPy Version                : 1.5.3
CUDA Root                    : /[hiden]/.conda/envs/rapids-0.16
CUDA Build Version           : 10010
CUDA Driver Version          : 11010
CUDA Runtime Version         : 10010
cuBLAS Version               : 10201
cuFFT Version                : 10101
cuRAND Version               : 10101
cuSOLVER Version             : (10, 2, 0)
cuSPARSE Version             : 10300
NVRTC Version                : (10, 1)
Thrust Version               : 100906
CUB Build Version            : 100800
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : 2708
NCCL Runtime Version         : 2708
cuTENSOR Version             : None
Device 0 Name                : GeForce GTX 1080 Ti
Device 0 Compute Capability  : 61
```

* Code to reproduce
```python
import cupy as cp
b = cp.random.bytes(10)
```

* Error messages, stack traces, or logs
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-121-104e7c75af44> in <module>
      1 import cupy as cp
----> 2 b = cp.random.bytes(10)

~/.conda/envs/rapids-0.16/lib/python3.7/site-packages/cupy/random/__init__.py in bytes(length)
      8                  <numpy.random.mtrand.RandomState.bytes>`
      9     """
---> 10     return _numpy.bytes(length)
     11 
     12 

~/.conda/envs/rapids-0.16/lib/python3.7/site-packages/numpy/__init__.py in __getattr__(attr)
    213             else:
    214                 raise AttributeError("module {!r} has no attribute "
--> 215                                      "{!r}".format(__name__, attr))
    216 
    217         def __dir__():

AttributeError: module 'numpy' has no attribute 'bytes'
```

**Comment by toslunar** [comment]
The bug came from a typo in https://github.com/cupy/cupy/pull/484/files#diff-91d0b84e88f4b46502000e7ec2cf6c4ebd35d9089d800805c1caf80525a20b21.  `numpy.bytes` -> `numpy.random.bytes`.

**Comment by kmaehashi** [comment]
Hi, thanks for reporting! Although I'm going to address this bug in #4318, there are several discussions in CuPy dev team whether the current implementation is appropriate. More specifically there can be several ways to provide `cupy.random.bytes`:

- Just call the NumPy implementation (as-is)
    - Pros: Convenient when users are using CuPy as a replacement for NumPy
    - Cons: Implicitly consumes the default RNG of NumPy, which may be unexpected for users manually seeding NumPy RNG
- Generate random bytes using CUDA, then copy it back to CPU and return it as Python bytes.
    - Pros: Aligns with other CuPy features (in terms of "providing GPU implementation of NumPy")
    - Cons: Possibly slow, incurs device synchronization
- Generate random bytes using CUDA, then return it as cupy.ndarray(dtype=int8).
    - Pros: Aligns with other CuPy features (in terms of "do not run implicit device-to-host copy / synchronization")
    - Cons: Return type is incompatible with NumPy
- Do not provide the CuPy implementation at all

Could you let us know how you are using `cp.random.bytes`?
- What do you expect for the returned value (`bytes` or `cupy.ndarray`)?
- Do you need to generate random bytes on CPU (NumPy) or GPU?

**Comment by lucasrodes** [comment]
Hi, 
Thanks for your answers! 

First of all, a small disclaimer: I am new to working with cupy.

My case might be a bit specific, but let me briefly explain it:
1. Generate array of shape _N_ x 1, _N_: number of elements (each of them being a byte sequence if a given length _L_). So, basically an array of bytes: `[b'\xc9', b'DV', b'\x93/', ...]`.  **<-- problem raised here**
2. Next, I am trying to apply a hash function (sha1, md5, ..) to each of these elements in the array.

Ideally, I was trying to implement both of these steps using python and GPU and found this library. For problem 1, I guess `cupy.random.bytes` could be a solver, eventhough for my purpose probably would need to either change its API to differ from numpy's (only accepts one argument: length) or call it in sort of optimized for loop?

Problem 2 is another story, and probably using native library `hashlib` is not compatible with working on the GPU.

Thanks once again!

**Comment by kmaehashi** [comment]
Thanks for sharing the details of your use-case @lucasrodes!
In your case, I think it's better to generate and handle data as a sequence of uint8 instead of bytes.

```py
N = 10
L = 8
data = numpy.random.randint(0,256, size=(N, L), dtype=numpy.uint8)  # or cupy instead of numpy
```

As for hash functions, you will need to write or find the CUDA implementation like [this one](https://github.com/tadasv/gpgpu_sha/blob/master/src/sha1_kernel.cu#L153]), load it using `cupy.RawKernel` and pass the generated random array to it.

**Comment by lucasrodes** [comment]
Thanks for your hints, @kmaehashi, really appreciate it. While trying this I ran into an error. I opened issue #4321
