### ISSUE TITLE
Make `ctypes.c_void_p` optional for copying to/from host memory?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#4317]
Take this function as an example: https://github.com/cupy/cupy/blob/50361e0d42ca8e41e7200382c3031cfc4e201764/cupy/cuda/memory.pyx#L368-L378
I found it a bit cumbersome having to wrap a pointer by `c_void_p` first. Using integer as input is more intuitive IMHO. IIUC this is because the distinction between host and device pointers was desired: `c_void_p` is always for the former and `MemoryPointer` for the latter. (Correct me if I'm wrong!)

However, I think in all these copy functions we can just accept `int` as inputs everywhere, and pass `runtime.memcpyDefault` to let the runtime API figure out where the data is (through inspecting the pointer attributes internally).

Perhaps the above proposal is too disruptive and thus backward incompatible, so I wonder if it would be more acceptable if we accept `int` wherever `c_void_p` is expected? At least to me it's a milder change:
```python
     cpdef copy_from_host(self, mem, size_t size): 
         """Copies a memory sequence from the host memory. 
  
         Args: 
             mem (int or ctypes.c_void_p): Source memory pointer. 
             size (int): Size of the sequence in bytes. 
  
         """ 
         if size > 0:
             ptr = mem if isinstance(mem, int) else mem.value
             runtime.memcpy(self.ptr, ptr, size,
                            runtime.memcpyDefault) 
```
The benefit is that lines such as this one get cleaned up a bit:
https://github.com/cupy/cupy/blob/abbcecc59828bb381e3e6fa33889b4b1631c3a74/cupy/core/core.pyx#L1272

**Comment by kmaehashi** [comment]
Thanks for the proposal! We discussed this today, but from the dev side, there's not much motivation to accept int because `copy_*` is not frequently called in CuPy codebase. I feel that it's better to keep it strictly-typed (similar to C semantics) as this is relatively a low-layer API.
Do you often use these copy APIs from your code outside of CuPy?

> IIUC this is because the distinction between host and device pointers was desired: c_void_p is always for the former and MemoryPointer for the latter. (Correct me if I'm wrong!)

@okuta Are there any background why `c_void_p` is used instead of `size_t` in `MemoryPointer.copy_*` APIs?

**Comment by leofang** [comment]
> Thanks for the proposal! We discussed this today, but from the dev side, there's not much motivation to accept int because `copy_*` is not frequently called in CuPy codebase. I feel that it's better to keep it strictly-typed (similar to C semantics) as this is relatively a low-layer API.
> Do you often use these copy APIs from your code outside of CuPy?

Thanks @kmaehashi for quick discussion over my question. Yes in one of our code we ended up using Runtime API directly, something like
```python
    host_ptr = np_array.ctypes.data
    dev_ptr = cp_array.data.ptr
    stream_ptr = stream.ptr if stream is not None else 0
    if nbytes > 0:
        runtime.memcpyAsync(dev_ptr, host_ptr, nbytes, runtime.memcpyHostToDevice, stream_ptr)
```
But it is arguably too low-level and I'd prefer to reuse CuPy's utilities whenever possible. My impression is that, despite our view of them being low-level, they are documented public APIs:
https://docs.cupy.dev/en/stable/reference/generated/cupy.cuda.MemoryPointer.html#cupy.cuda.MemoryPointer

Another use case off top of my head is from the snippet I showed in the structured array discussion: https://github.com/cupy/cupy/issues/2031#issuecomment-731414757. I reiterate, though, that all these use cases can be worked around one way or another, so other than convenience there's no urgent need in pushing a PR for this (I am definitely happy to put together one if accepted).

**Comment by kmaehashi** [comment]
I talked with @okuta regarding this. The reason why `size_t` is used here is that CuPy was originally implemented using ctypes. Considering this is a part of public API exposed to the Python code as you said, the change proposed (`ptr = mem if isinstance(mem, int) else mem.value`) sounds good to me.

**Comment by leofang** [comment]
Thanks, @kmaehashi! Will send a PR later 🙂
