### ISSUE TITLE
suprising behavior of cupy.array on numpy views with base array of a different dtype

### ISSUE THREAD

**Issue by grlee77** [cupy/cupy#4354]
The following example illustrates that creating CuPy array from a NumPy view where the underlying array has a different base dtype can result in unexpected behavior. Here is a minimal concrete example for a boolean view of a `uint8` array. In NumPy calling `np.array()` creates a copy. In CuPy, the created array has flags.owndata=True as expected, so it looks like it is a copy, but the underlying data still correspond to the view! This can be seen if converting back from `bool`->`uint8` via astype, values > 1 occur!

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)

CuPy 9.0.0a2

* Code to reproduce

```Python
import numpy as np
import cupy as cp

# boolean view of a uint8 array
a = np.array([0, 3, 1, 2, 0, 1], dtype=np.uint8)
a_view = a.view(np.bool)
print(f"a_view.flags = {a_view.flags}")

# calling np.array makes a copy as expected
b = np.array(a_view)  # will make a copy!
print(f"b.flags = {b.flags}")
print(f"b.astype(int) = {b.astype(int)}\n")  # only 1 and 0 as expected

# create CuPy array from the NumPy view
gpu_a = cp.array(a_view)
print(f"gpu_a = {gpu_a}")
print(f"gpu_a.astype(int) = {gpu_a.astype(int)}")   # unexpected values of 2 and 3!
print(f"gpu_a.flags = {gpu_a.flags}")  # flags look like it is a copy (owndata=True)
```
gives
```
a_view.flags =   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

b.flags =   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

b.astype(int) = [0 1 1 1 0 1]

gpu_a = [False  True  True  True False  True]
gpu_a.astype(int) = [0 3 1 2 0 1]
gpu_a.flags =   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
```

Possible Solution
=============
Possibly need a check on the input object in cp.array that looks something like the following
```Python
if isinstance(obj, numpy.ndarray) and not obj.flags.owndata and obj.base.dtype != obj.dtype:
    obj = numpy.copy(obj)
```
or if a copy is not requested then perhaps creating the cupy.ndarray from obj.base and then create a view?

**Comment by takagi** [comment]
Thanks for reporting! (and sorry for late response)

It looks the copied `b` has the same binary with `a` in NumPy,

```Python
>>> b = np.array(a_view)
>>> b.view(np.uint8)
array([0, 3, 1, 2, 0, 1], dtype=uint8)
```

so `cupy.ndarray.astype` may have some miss compatibility. Would you also check the result above?

**Comment by takagi** [comment]
`cupy.ndarray.astype` does `elementwise_copy` to copy underlying data:

https://github.com/cupy/cupy/blob/cff7da1130587d814b744293e81ca64c22081839/cupy/_core/core.pyx#L466

On the other hand, `numpy.ndarray.astype` seems to do a more complicated thing than I thought:

https://github.com/numpy/numpy/blob/a11945d7dc930afe47e1cf7f81cb69f2958f4c1f/numpy/core/src/multiarray/array_assign_array.c#L117-L125

```c
/* Get the function to do the casting */
NPY_cast_info cast_info;
if (PyArray_GetDTypeTransferFunction(aligned,
                    src_strides_it[0], dst_strides_it[0],
                    src_dtype, dst_dtype,
                    0,
                    &cast_info, &needs_api) != NPY_SUCCEED) {
    return -1;
}
```

**Comment by takagi** [comment]
I think we can make a special path for boolean in CuPy, and it's would be enough here.

**Comment by toslunar** [comment]
Now CuPy is fixed, but NumPy reads bytes for float16 (numpy/numpy#19514).
```
>>> gpu_a.astype(int)
array([0, 1, 1, 1, 0, 1])
>>> a_view.astype(int)
array([0, 1, 1, 1, 0, 1])
>>> gpu_a.astype('float16')
array([0., 1., 1., 1., 0., 1.], dtype=float16)
>>> a_view.astype('float16')
array([0., 3., 1., 2., 0., 1.], dtype=float16)
```
