### ISSUE TITLE
Method-level parameterized test

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#4371]
We can parametrize test classes by `testing.parameterize`. It would be nice if we can do a similar thing on the test method level. `pytest` has `pytest.mark.parametrize` that may be used for that purpose, however, there are the following problems once we are to use it naively in CuPy:

- `pytest.mark.parametrize` can not be used in a subclass of `unittest.TestCase`
- it can not be with `cupy.testing` decorators as `testing.for_dtypes` and `testing.numpy_cupy_allclose` because it uses extra parameters of a test function for fixtures

Rel #4368.

**Comment by toslunar** [comment]
> * it can not be with `cupy.testing` decorators as `testing.for_dtypes` and `testing.numpy_cupy_allclose` because it uses extra parameters of a test function for fixtures


It seems working.

```python
class TestA:
    @pytest.mark.parametrize('foo', [1, 2])
    @testing.for_all_dtypes()
    def test_a(self, foo, dtype):
        assert numpy.array(foo, dtype).item() == foo
```

result

```
============================= test session starts ==============================
platform linux -- Python 3.9.0, pytest-4.1.1, py-1.9.0, pluggy-0.13.1 -- .../python3.9
cachedir: .pytest_cache
rootdir: .../cupy, inifile: setup.cfg
collecting ... collected 2 items

test_tmp.py::TestA::test_a[1] PASSED                                     [ 50%]
test_tmp.py::TestA::test_a[2] FAILED                                     [100%]

=================================== FAILURES ===================================
_______________________________ TestA.test_a[2] ________________________________

self = <test_tmp.TestA object at 0x7f95ca61cf70>, foo = 2
dtype = <class 'numpy.bool_'>

    @pytest.mark.parametrize('foo', [1, 2])
    @testing.for_all_dtypes()
    def test_a(self, foo, dtype):
>       assert numpy.array(foo, dtype).item() == foo
E       assert True == 2
E         -True
E         +2

test_tmp.py:15: AssertionError
----------------------------- Captured stdout call -----------------------------
dtype is <class 'numpy.bool_'>
```

**Comment by toslunar** [comment]
It would be simpler to stop inheriting `unittest.TestCase`.

Also note that https://docs.pytest.org/en/stable/unittest.html#pytest-features-in-unittest-testcase-subclasses says:

> The following pytest features do not work, and probably never will due to different design philosophies:
> * Fixtures (except for autouse fixtures, see below);
> * Parametrization;
> * Custom hooks;

**Comment by takagi** [comment]
Oh, it may depend on pytest version. It seems I used older pytest and let me check it with `pytest==4.1.1`.

**Comment by takagi** [comment]
It works!
