### ISSUE TITLE
Error when installing cupy: nvcc fatal : host compiler targets unsupported os

### ISSUE THREAD

**Issue by philipchild** [cupy/cupy#439]
I have been trying to solve this for days without success: I am trying to install cupy via `pip install --user cupy` but the installation fails with this error:
```
tmpxft_000047b8_00000000-1.cpp
nvcc fatal   : Host compiler targets unsupported OS.
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\bin/nvcc.exe' failed with exit status 1

```

I have previously installed Visual Studio Community 2015 (as is compatible with Cuda toolkit 8) and Cuda v8 & latest update.

I found that I had to install msinttypes to get over an initial issue. It's possible I have the wrong version installed (as I wasn't sure which I needed) but I don't think that is the issue. I am using Windows 10 and Python 2.7. I have also tried installing the visual cpp build tools but that made no difference. I also have VS2013 Community installed. Could that be interfering? Any help would be much appreciated.

Full log below from failed install: http://s000.tinyupload.com/index.php?file_id=03439880912431265287

**Comment by Sirokujira** [comment]
Python 2.7 uses msvc compiler 2008.
Python 3.5/3.6 uses msvc compiler 2015.

MSVC Compiler use Python Version List
https://wiki.python.org/moin/WindowsCompilers

**Comment by philipchild** [comment]
Ah thank you. So that mains that cupy won't be compatible with Python 2.7? Since Cuda needs VS 2015.
Thanks again

**Comment by philipchild** [comment]
This is the compiler I installed: https://www.microsoft.com/en-gb/download/details.aspx?id=44266 It would seem correct for my python version but maybe not for Cuda?

**Comment by Sirokujira** [comment]
When building the cpp file, in the Python 2.7 environment, as the default setting of Cython
Compile using Visual C ++ for Python compiler (VS 2008).
In Python 3.5 / 3.6, compile using Visual Studio 2015.
(Please check the log you are uploading)

**Comment by philipchild** [comment]
Can I configure that via a pip option or do I need to edit my config for Cython somewhere?
Thanks for your help!

**Comment by okuta** [comment]
Did you solve this problem? I recommend using Python3.6, if you use Windows.

Below is a useful tips for installation
- nvcc need latest VC++, please set ``PATH`` that includes ``C:\Program Files (x86)\Microsoft Visual Studio ????\VC\bin``.
- Python installer uses some special environment variable such as a ``VS90COMNTOOLS``. If you want to use another version visual studio compiler, please set another PATH. For example, ``VS90COMNTOOLS=%VS140COMNTOOLS%``.

**Comment by philipchild** [comment]
Thanks for the tips. Sadly I still don't have it working.
I tried adding the env vars (some I had) but it didn't seem to make a
difference.
I might try with Python 3.6 to see if that helps but I use 2.7 for other
things so don't really want to complicate my system but installing both
versions in parallel if I can help it.
Thanks

**Comment by room3dev** [comment]
CUDA v9.0 RC is looking for VS2017 to identify as 1910 but the latest update actually identifies as 1911. To fix open .../CUDA/v9.0/include/crt/host_config.h and change this line:
#if _MSC_VER < 1600 || _MSC_VER > 1910
to this:
#if _MSC_VER < 1600 || _MSC_VER > 1911

You may also have to add the following to your CMakeLists:
list(APPEND CUDA_NVCC_FLAGS --cl-version=2017)

Source:
https://stackoverflow.com/questions/43745099/using-cuda-with-visual-studio-2017
