### ISSUE TITLE
Compilation Error from the latest Source Code in GitHub possibly caused by CUSPARESE APIs 

### ISSUE THREAD

**Issue by suntaochun** [cupy/cupy#4412]
Kindly need help. 
I'm currently trying to install cupy packages by compiling the source code released in the GitHub.

My System version is:
`Ubuntu 18.04`

My CUDA version is:
`Copyright (c) 2005-2019 NVIDIA Corporation`
`Built on Fri_Feb__8_19:08:17_PST_2019`
`Cuda compilation tools, release 10.1, V10.1.105`

My Python version is:
`Python 3.8.5`

And when installing the packages by the following commands:
`cd cupy`
`pip install . -vvvv`

Some errors occur:
`In file included from cupy_backends/cuda/libs/cusparse.cpp:676:0:`
`cupy_backends/cuda/libs/../cupy_cusparse.h:282:17: error: conflicting declaration ‘typedef enum cusparseIndexType_t cusparseIndexType_t’`
`typedef enum {} cusparseIndexType_t`
 `                             ^~~~~~~~~~~~~~~~~~~`
 ` In file included from cupy_backends/cuda/libs/../cupy_cusparse.h:7:0,
                   from cupy_backends/cuda/libs/cusparse.cpp:676:`
  `/usr/local/cuda-10.1/include/cusparse.h:6960:3: note: previous declaration as ‘typedef enum cusparseIndexType_t cusparseIndexType_t’
   } cusparseIndexType_t;
     ^~~~~~~~~~~~~~~~~~~`
 ` In file included from cupy_backends/cuda/libs/cusparse.cpp:676:0:
  cupy_backends/cuda/libs/../cupy_cusparse.h:283:17: error: conflicting declaration ‘typedef enum cusparseFormat_t cusparseFormat_t’
   typedef enum {} cusparseFormat_t;
                   ^~~~~~~~~~~~~~~~`
 ` In file included from cupy_backends/cuda/libs/../cupy_cusparse.h:7:0,
                   from cupy_backends/cuda/libs/cusparse.cpp:676:
  /usr/local/cuda-10.1/include/cusparse.h:6944:3: note: previous declaration as ‘typedef enum cusparseFormat_t cusparseFormat_t’
   } cusparseFormat_t;
     ^~~~~~~~~~~~~~~~`
 ` In file included from cupy_backends/cuda/libs/cusparse.cpp:676:0:
  cupy_backends/cuda/libs/../cupy_cusparse.h:284:17: error: conflicting declaration ‘typedef enum cusparseOrder_t cusparseOrder_t’
   typedef enum {} cusparseOrder_t;
                   ^~~~~~~~~~~~~~~`
  `In file included from cupy_backends/cuda/libs/../cupy_cusparse.h:7:0,
                   from cupy_backends/cuda/libs/cusparse.cpp:676:
  /usr/local/cuda-10.1/include/cusparse.h:6949:3: note: previous declaration as ‘typedef enum cusparseOrder_t cusparseOrder_t’
   } cusparseOrder_t;
     ^~~~~~~~~~~~~~~`
  `In file included from cupy_backends/cuda/libs/cusparse.cpp:676:0:
  cupy_backends/cuda/libs/../cupy_cusparse.h:286:17: error: conflicting declaration ‘typedef enum cusparseSpMMAlg_t cusparseSpMMAlg_t’
   typedef enum {} cusparseSpMMAlg_t;
                   ^~~~~~~~~~~~~~~~~`
`  In file included from cupy_backends/cuda/libs/../cupy_cusparse.h:7:0,
                   from cupy_backends/cuda/libs/cusparse.cpp:676:
  /usr/local/cuda-10.1/include/cusparse.h:6955:3: note: previous declaration as ‘typedef enum cusparseSpMMAlg_t cusparseSpMMAlg_t’
   } cusparseSpMMAlg_t;
     ^~~~~~~~~~~~~~~~~`
`  In file included from cupy_backends/cuda/libs/cusparse.cpp:676:0:
  cupy_backends/cuda/libs/../cupy_cusparse.h:450:17: error: conflicting declaration ‘typedef enum cusparseCsr2CscAlg_t cusparseCsr2CscAlg_t’
   typedef enum {} cusparseCsr2CscAlg_t;
                   ^~~~~~~~~~~~~~~~~~~~`
`  In file included from cupy_backends/cuda/libs/../cupy_cusparse.h:7:0,
                   from cupy_backends/cuda/libs/cusparse.cpp:676:
  /usr/local/cuda-10.1/include/cusparse.h:6898:3: note: previous declaration as ‘typedef enum cusparseCsr2CscAlg_t cusparseCsr2CscAlg_t’
   } cusparseCsr2CscAlg_t;
     ^~~~~~~~~~~~~~~~~~~~`

I search for several ways attempting to solve the conflicts, including finding the declarations in the `cusparse.h` included in CUDA-10,1 and trying to make correspondences between cupy's and CUDA's conflicted declarations. However, no one works. So I am sincerely asking for some help.

By the way, I have already tried to install by `pip install --pre cupy-cuda101`. There are also some errors in the linking reference of cupy to 'libcusparse.so', with the same familiar functions. I suspect there may be relationships between the compilation problems and the linking problems.

**Comment by kmaehashi** [comment]
Thanks for reporting! I'm working on the fix in #4419.
If you need an immediate workaround, please upgrade to CUDA 10.1 Update 2 (V10.1.243) or later (currently your have CUDA 10.1 (V10.1.105)).

> By the way, I have already tried to install by pip install --pre cupy-cuda101. There are also some errors in the linking reference of cupy to 'libcusparse.so', with the same familiar functions. I suspect there may be relationships between the compilation problems and the linking problems.

Due to ABI changes between CUDA 10.1, 10.1 Update 1, and 10.1 Update 2, we were unable to support CUDA 10.1 Update 1 or earlier with the same package `cupy-cuda101`.

**Comment by suntaochun** [comment]
Thanks for @kmaehashi 's kind reply. I have already seen #4419 and am surprised that this issue receives your quick response. I'm closely paying attention to the future updates of the cupy, which is really useful to be an accelerator of the numpy with CUDA! 
I have already installed Tensorflow, etc. ,with the current version of CUDA, so I will just wait for your newly fix-solved version and won't change my CUDA  version, in order to avoid the possible conflicts between CUDA and other already-installed packages and libraries. 
Thanks again !
