### ISSUE TITLE
Converting integer to float32 results in error.

### ISSUE THREAD

**Issue by wd1969** [cupy/cupy#4434]
(base) PS C:\Users\mengh> python -c 'import cupy; cupy.show_config()'
OS : Windows-10-10.0.19041-SP0
CuPy Version : 8.1.0
NumPy Version : 1.19.3
SciPy Version : 1.5.0
CUDA Root : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
CUDA Build Version : 10010
CUDA Driver Version : 11010
CUDA Runtime Version : 10010
cuBLAS Version : 10100
cuFFT Version : 10010
cuRAND Version : 10010
cuSOLVER Version : (10, 1, 0)
cuSPARSE Version : 10010
NVRTC Version : (10, 1)
Thrust Version : 100906
CUB Build Version : 100800
cuDNN Build Version : None
cuDNN Version : None
NCCL Build Version : None
NCCL Runtime Version : None
cuTENSOR Version : None
Device 0 Name : GeForce RTX 2070 SUPER
Device 0 Compute Capability : 75
(base) PS C:\Users\mengh>

code:
bins.shape, bins[-10:]
bins.cumsum()[-10:]
bins.cumsum().astype(cp.float64).astype(int)[-10:]
bins.cumsum().astype(cp.float32).astype(int)[-10:]

return:
((32400,), array([ 590, 650, 1285, 589, 647, 1299, 598, 641, 1300, 591]))
array([26855200, 26855850, 26857135, 26857724, 26858371, 26859670, 26860268, 26860909, 26862209, 26862800])
array([26855200, 26855850, 26857135, 26857724, 26858371, 26859670, 26860268, 26860909, 26862209, 26862800])
array([26855200, 26855850, 26857136, 26857724, 26858372, 26859670, 26860268, 26860908, 26862208, 26862800])

26862209 -> 26862208

**Comment by wd1969** [comment]
(base) PS C:\Users\mengh> python -c 'import cupy; cupy.show_config()'
OS                           : Windows-10-10.0.19041-SP0
CuPy Version                 : 8.1.0
NumPy Version                : 1.19.3
SciPy Version                : 1.5.0
CUDA Root                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
CUDA Build Version           : 10010
CUDA Driver Version          : 11010
CUDA Runtime Version         : 10010
cuBLAS Version               : 10100
cuFFT Version                : 10010
cuRAND Version               : 10010
cuSOLVER Version             : (10, 1, 0)
cuSPARSE Version             : 10010
NVRTC Version                : (10, 1)
Thrust Version               : 100906
CUB Build Version            : 100800
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
Device 0 Name                : GeForce RTX 2070 SUPER
Device 0 Compute Capability  : 75
(base) PS C:\Users\mengh>

code:
bins.shape, bins[-10:]
bins.cumsum()[-10:]
bins.cumsum().astype(cp.float64).astype(int)[-10:]
bins.cumsum().astype(cp.float32).astype(int)[-10:]

return:
((32400,), array([ 590,  650, 1285,  589,  647, 1299,  598,  641, 1300,  591]))
array([26855200, 26855850, 26857135, 26857724, 26858371, 26859670, 26860268, 26860909, 26862209, 26862800])
array([26855200, 26855850, 26857135, 26857724, 26858371, 26859670, 26860268, 26860909, 26862209, 26862800])
array([26855200, 26855850, 26857136, 26857724, 26858372, 26859670, 26860268, 26860908, 26862208, 26862800])

26862209 -> 26862208

**Comment by anaruse** [comment]
This is not a cupy or numpy problem, but a problem caused by the fact that float32 has only 23-bits for mantissa.

    >>> import numpy
    >>> a = numpy.array(26862208)
    >>> a
    array(26862209)
    >>> a.astype('float64')
    array(26862209.)
    >>> a.astype('float32')
    array(26862208., dtype=float32)

**Comment by wd1969** [comment]
Thank you. I see
