### ISSUE TITLE
numpy.version.version

### ISSUE THREAD

**Issue by shssf** [cupy/cupy#4436]
It looks like cuPy doesn't have runtime version getter.
It would be great to have something like `cupy.version.version`

**Comment by thomasaarholt** [comment]
I may just be unfamiliar with the concept of a "runtime version getter", but I think what you want is `cp.__version__`.
 Most packages have their version stored at `package.__version__`, to the degree that it's [basically a standard](https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package).
```python
>>> np.__version__
'1.19.4'
>>> cp.__version__
'8.2.0'
```
