### ISSUE TITLE
implement cupyx.scipy.special.lambertw

### ISSUE THREAD

**Issue by brandondube** [cupy/cupy#4450]
This function is missing in the scipy compatible routines.  It would be nice to see it added.

[Scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.lambertw.html)

[cupyx special page](https://docs.cupy.dev/en/stable/reference/special.html)

**Comment by izaid** [comment]
Indeed, part of the inspiration for doing this is to create a minimal, header-only C++ library for special functions. Right now, it is part of SciPy, but that may change in the future. These are functions that are meant to just be fed into `cp.ElementwiseKernel` or something similar. It should already be possible to provide `lambertw` this way, and we're certainly keen on feedback.
