### ISSUE TITLE
cumsum and cumprod modify the input array

### ISSUE THREAD

**Issue by grlee77** [cupy/cupy#4456]
While debugging a test failure in `cupyimg`, I found that `cupy.cumsum` unexpectedly modifies the input array. This did not used to be the case, so I suspect it may be due to recent changes from #4316 or #4366 (attn: @anaruse)

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
CuPy 9.0.0a3

* Code to reproduce

Here is a basic example to illustrate the issue:
```Python
a = cp.testing.shaped_arange((4, 4))
print(a)
b = np.cumsum(a, axis=1)
print(a)  # a will now be equal to b (it was modified in-place)
```
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]], dtype=float32)

array([[ 1.,  3.,  6., 10.],
       [ 5., 11., 18., 26.],
       [ 9., 19., 30., 42.],
       [13., 27., 42., 58.]], dtype=float32)
```

**Comment by grlee77** [comment]
cumprod has the same issue

**Comment by leofang** [comment]
An indirect way to confirm is to set `CUPY_ACCELERATORS=cub` and rerun the test. Looks like there's a check that prevented in-place operations got removed.

**Comment by leofang** [comment]
I think the bug is this line (from #4316): 
https://github.com/cupy/cupy/blob/3388dcec8c939eb01baecb2a0459e4116db05b1d/cupy/core/_routines_math.pyx#L742
`copy` should be `True`.

**Comment by grlee77** [comment]
> copy should be True.

Thanks for finding that quickly! I think I had encouraged @anaruse to try and avoid copies, so this is probably my fault. I guess we didn't have any test cases that would have detected the problem.

**Comment by grlee77** [comment]
My environment was set to `CUPY_ACCELERATORS=cub,cutensor` when I encountered this

**Comment by leofang** [comment]
Ah, never mind. Forgot you set an axis...

**Comment by anaruse** [comment]
Sorry, my checks were inadequate.
I'll prepare a PR that fixes this issue and adds the relevant tests.
