### ISSUE TITLE
Getting Error in cupy module(cupy.append())

### ISSUE THREAD

**Issue by kratika464** [cupy/cupy#4516]
Getting Error in cupy module(cupy.append()):-
error:- Getting Error in cupy module(cupy.append())
full error:- File "GPU_Code_CUML.py", line 478, in
result = sse_numba(symbol,look_back)
File "GPU_Code_CUML.py", line 420, in sse_numba
actual_price_start_date_plus_five = cupy.append(actual_price_start_date_plus_five, ['nan'], axis=None)
AttributeError: module 'cupy' has no attribute 'append'

This was my code line in which i am getting error:-
actual_price_start_date_plus_five = [218.39 211.01 216.55 215.44 216.51 217.23 214.46 211.08
212.42 210.39 210.11 213.86 213.87 213.86 213.87 215.23 214.07 216.21
215.37 214.24 214.36 214.29]
actual_price_start_date_plus_five = cupy.append(actual_price_start_date_plus_five, ['nan'], axis=None)
and i want to append "nan" five time in actual_price_start_date_plus_five.
Where I am doing wrong and how to use cupy.append in my code.

link cupy = "https://docs.cupy.dev/en/v9.0.0a2/reference/generated/cupy.append.html#cupy.append".

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version = 8.1.0
  - OS/Platform = Ubuntu 18.04 amd64(AWS)
  - CUDA version = 10.1
  - cuDNN version (V == 7.6)
* Code to reproduce
* Error messages, stack traces, or logs

**Comment by leofang** [comment]
`cupy.append()` was just added recently (#4112), so it won't be available in CuPy v8.x. If needed you can pip install the pre-release versions (v9.0.0b1, for example).

**Comment by kratika464** [comment]
Can you suggest to me how to update the cupy version on the conda environment?
Because I download rapids through conda.
cmd:-
conda create -n rapids-0.17 -c rapidsai -c nvidia -c conda-forge
-c defaults rapids-blazing=0.17 python=3.7 cudatoolkit=10.1

So should I try...... conda install cupy==v9.0.0b1?

**Comment by leofang** [comment]
The pre-release versions are not available on any of the conda channels, so you must install it via pip. You can safely do so in a conda environment and usually it'd just work. The caveat in your case is that the RAPIDS stack depends on CuPy from conda-forge, so you should force-remove it first (otherwise all packages depending on it would also be removed), and then do `pip install 'cupy-cuda101==v9.0.0b1'`. This should work (though I didn't try).

**Comment by emcastillo** [comment]
As this issue seems to be solved, let us close this. Feel free to reopen it if needed 😄
