### ISSUE TITLE
Dictionary keys cannot be CuPy element

### ISSUE THREAD

**Issue by aitikgupta** [cupy/cupy#4531]
A more answerable question would be, can keys of a dictionary be an element stored in GPU?

* Code to reproduce
```python
import numpy as np
import cupy as cp

arr = [1, 2, 3]
np_dict = dict()
cp_dict = dict()
np_arr = np.asarray(arr)
cp_arr = cp.asarray(arr)

for i in np_arr:
     np_dict[i] = "okay"

print(np_dict)                                # {1: 'okay', 2: 'okay', 3: 'okay'}

for i in cp_arr:
     cp_dict[i] = "okay"

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: unhashable type: 'cupy.core.core.ndarray'
```
* Error messages, stack traces, or logs
Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
```console
CuPy Version          : 6.0.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10000
CUDA Driver Version   : 11010
CUDA Runtime Version  : 10000
cuDNN Build Version   : 7301
cuDNN Version         : 7605
NCCL Build Version    : 1000
NCCL Runtime Version  : (unknown)
```

**Comment by kmaehashi** [comment]
Unlike NumPy, CuPy returns a ndarray when iterating over a ndarray, even if the resulting value is a scalar. This is because the scalar value is on GPU and we don't want to implicitly transfer it to the host (CPU) memory. You can use ndarray.item() to explicly convert the ndarray (cupy or numpy) into a scalar, e.g., `cp_dict[i.item()] = "okay"` instead of `cp_dict[i] = "okay"`.
https://docs.cupy.dev/en/stable/reference/generated/cupy.ndarray.html#cupy.ndarray.item

**Comment by aitikgupta** [comment]
Thanks! 👍🏼

**Comment by leofang** [comment]
btw @aitikgupta I guess you installed CuPy from Anaconda's channel? v6.0 is unsupported now. If you're a conda user, you can either pip install in your conda environment, or do `conda install -c conda-forge cupy`.

**Comment by aitikgupta** [comment]
> btw @aitikgupta I guess you installed CuPy from Anaconda's channel? v6.0 is unsupported now. If you're a conda user, you can either pip install in your conda environment, or do `conda install -c conda-forge cupy`.

That's right, I trust Anaconda to handle CUDA binaries and their versions better than me. :)
(you're right though, I should update)

**Comment by leofang** [comment]
We maintain the `cupy` package on Conda-Forge and we have better toolchain now. Recently Conda-Forge has been completely decoupled from the default channel, so perhaps you could give it a try and report any issues to https://github.com/conda-forge/cupy-feedstock 🙂

**Comment by aitikgupta** [comment]
Ah, I was in the wrong conda env when I filed the issue. Turns out, I do trust myself with handling the versions. :D
I do a pip install within conda envs, this should be updated now:
`python -c 'import cupy; cupy.show_config()'`:
```console
OS                           : Linux-5.8.0-7630-generic-x86_64-with-debian-bullseye-sid
CuPy Version                 : 8.3.0
NumPy Version                : 1.19.2
SciPy Version                : 1.5.4
Cython Build Version         : 0.29.21
CUDA Root                    : /usr/local/cuda
CUDA Build Version           : 10000
CUDA Driver Version          : 11010
CUDA Runtime Version         : 10000
cuBLAS Version               : 10000
cuFFT Version                : 10000
cuRAND Version               : 10000
cuSOLVER Version             : (10, 0, 0)
cuSPARSE Version             : 10000
NVRTC Version                : (10, 0)
Thrust Version               : 100903
CUB Build Version            : 100800
cuDNN Build Version          : 7605
cuDNN Version                : 7605
NCCL Build Version           : 2604
NCCL Runtime Version         : 2604
cuTENSOR Version             : None
Device 0 Name                : GeForce GTX 1650
Device 0 Compute Capability  : 75
```
> Recently Conda-Forge has been completely decoupled from the default channel, so perhaps you could give it a try and report any issues to https://github.com/conda-forge/cupy-feedstock :slightly_smiling_face:

Thanks, I'll try the conda-forge channel 👍🏼
