### ISSUE TITLE
Does copy.array initialize array asynchronously?

### ISSUE THREAD

**Issue by mfoglio** [cupy/cupy#4582]
Suppose I do the following:

        numpy_frame = np.array([0,1,2,3,4,5])
        cupy_frame = cp.array(numpy_frame, dtype=cp.uint8)

Is the data copied to the GPU asynchronously or do I need to something like the following

        stream = cp.cuda.Stream(non_blocking=True)
        cupy_frame  = cp.empty(numpy_frame.shape, dtype=cp.uint8)
        cupy_frame.set(numpy_frame, stream=stream)
        stream.synchronize()

I can't find this information in the doc. Thank you!

**Comment by kmaehashi** [comment]
CuPy asynchronously transfers from host to device using pinned memory on the [current stream](https://docs.cupy.dev/en/stable/reference/cuda.html#streams-and-events) (by default, it is a "default stream".)

**Comment by mfoglio** [comment]
Thank you.

Sometime I have the following error simply doing `cupy_frame = cp.array(numpy_frame, dtype=cp.uint8)`:

```
--- Logging error ---
Traceback (most recent call last):
  File "/myfile.py", line 37, in __init__
    self.cupy_frame = cp.array(self.numpy_frame, dtype=cp.uint8)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cupy/_creation/from_data.py", line 41, in array
    return core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/core/core.pyx", line 1984, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2063, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2150, in cupy.core.core._send_object_to_gpu
  File "cupy/cuda/stream.pyx", line 242, in cupy.cuda.stream.BaseStream.record
  File "cupy_backends/cuda/api/runtime.pyx", line 854, in cupy_backends.cuda.api.runtime.eventRecord
  File "cupy_backends/cuda/api/runtime.pyx", line 247, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInvalidResourceHandle: invalid resource handle

```

Do I need to pin the numpy array somehow? Also, I am running on other cuda applications (tensorRT) so I don't know how cupy manages different contexts (e.g. cuda's context.push() and context.pop() )

**Comment by mfoglio** [comment]
Why can I specify the stream when downloading an array from the GPU `cp_array.get(stream=cp.stream.Stream())` but not when uploading it `cp.array(np_array)`? Is there a performance reason for this?

**Comment by leofang** [comment]
AFAIK the `.get()` API was a legacy from Chainer. CuPy encourages the following usage to do async transfer on streams:
```python
s = cp.cuda.Stream()
with s:
    a_np = cp.asnumpy(a)  # d -> h

with s:
    b = cp.asarray(b_np)  # h -> d
```

**Comment by kmaehashi** [comment]
As Leo commented we encourage setting a stream using the context manager. `cupy.array` does not provide `stream` argument because it is a counterpart of `numpy.array` so we don't want to change the signature.
