### ISSUE TITLE
Error when creating a CuPy ndarray from a TensorFlow DLPack object

### ISSUE THREAD

**Issue by miguelusque** [cupy/cupy#4590]
Hi,

When trying to convert a TensorFlow EagerTensor to a CuPy ndarray via DLPack, a runtime error is raised.

* Conditions:

> CuPy Version          : 8.0.0
> CUDA Root             : /opt/conda/envs/rapids
> CUDA Build Version    : 11000
> CUDA Driver Version   : 11000
> CUDA Runtime Version  : 11000
> cuBLAS Version        : 11200
> cuFFT Version         : 10201
> cuRAND Version        : 10201
> cuSOLVER Version      : (10, 6, 0)
> cuSPARSE Version      : 11101
> NVRTC Version         : (11, 0)
> Thrust Version        : 100909
> CUB Build Version     : 100909
> cuDNN Build Version   : 8000
> cuDNN Version         : 8000
> NCCL Build Version    : 2708
> NCCL Runtime Version  : 2708
> cuTENSOR Version      : None

* Code to reproduce

> import tensorflow as tf
> import cupy as cp
> 
> src = tf.convert_to_tensor([[1, 2], [3, 4]])
> dst = cp.fromDlpack(tf.experimental.dlpack.to_dlpack(src))
> 
> print(type(dst), "\n", dst)
> 

* Error messages, stack traces, or logs

> ---------------------------------------------------------------------------
> CUDARuntimeError                          Traceback (most recent call last)
> <ipython-input-4-92abbefa4778> in <module>
>       7 
>       8 print(tf.__version__, "\t", cp.__version__)
> ----> 9 print(type(dst), "\n", dst)
> 
> cupy/core/core.pyx in cupy.core.core.ndarray.__str__()
> 
> cupy/core/core.pyx in cupy.core.core.ndarray.get()
> 
> cupy/core/core.pyx in cupy.core.core.ndarray.get()
> 
> cupy/cuda/memory.pyx in cupy.cuda.memory.MemoryPointer.copy_to_host()
> 
> cupy_backends/cuda/api/runtime.pyx in cupy_backends.cuda.api.runtime.memcpy()
> 
> cupy_backends/cuda/api/runtime.pyx in cupy_backends.cuda.api.runtime.check_status()
> 
> CUDARuntimeError: cudaErrorInvalidValue: invalid argument

Hope it helps!
Miguel

**Comment by miguelusque** [comment]
I have dug a bit more into this issue, and it looks like the Tensor was being created in CPU. Therefore, the DLPack object returned by TensorFlow is also hosted in CPU, and that is the source of the issue.

The following code works fine:
>with tf.device('/GPU:0'):
>     src = tf.convert_to_tensor([[1, 2], [3, 4]])
>     dst = cp.fromDlpack(tf.experimental.dlpack.to_dlpack(src))

Nevertheless, I think it is well-worth to add support to CPU-based DLPack objects.

Regards,
Miguel

**Comment by miguelusque** [comment]
I have been digging a bit more about this issue, and I think that the issue is due to the fact that the DLPack object is hosted in CPU memory, and not GPU memory.

Nevertheless, I think it would be great if cupy.fromDlpack() method would support DLPack objects in host memory.

Regards,
Miguel

**Comment by leofang** [comment]
Thanks for reporting, @miguelusque. DLPack is meant for zero-copy among libraries (where data resides is set in `DLDeviceType`), so if your TF tensor lives on CPU you have to do the explicit copy (using TF-provided mechanisms) yourself.

**Comment by miguelusque** [comment]
Hi @leofang ,

I agree that DLPack is meant for zero copy, but it is also being discussed as the standard data representation to be use to interop among libraries.

In the worst scenario (when the data is in host memory), the user will need to manually move the data from host memory to device memory. Therefore, why don’t making his life easier? :-)

**Comment by leofang** [comment]
> I agree that DLPack is meant for zero copy, but it is also being discussed as the standard data representation to be use to interop among libraries.

Yes, but the discussion is not yet finalized either on the DLPack side (https://github.com/dmlc/dlpack/issues/57) or Array API side (https://github.com/data-apis/array-api/pull/106), so I suggest we wait 🙂 One of the issues being discussed is that it is currently unclear on which stream the data should be copied. 

> In the worst scenario (when the data is in host memory), the user will need to manually move the data from host memory to device memory. Therefore, why don’t making his life easier? :-)

CuPy has a convention to avoid implicit copy whenever possible, which is why the `__array__` method raises: 
https://github.com/cupy/cupy/blob/880918c978dc6f8eb91585764e2501b1ca2bea89/cupy/core/core.pyx#L1267-L1273
so the current DLPack support is consistent with this convention. A user opt-in deviation is certainly possible, but I think it's best to defer until the protocol update is finalized.

**Comment by miguelusque** [comment]
Thank you! Sure! Let’s wait for a while.

Nevertheless, in your code reference above it looks like implicit conversions are a TODO task:

     # TODO(imanishi): Support an environment variable or a global 
     # configure flag that allows implicit conversions to NumPy array. 
     # (See https://github.com/cupy/cupy/issues/589 for the detail.)

**Comment by leofang** [comment]
> Nevertheless, in your code reference above it looks like implicit conversions is in someone’s TODO list:

It reflected the current decision and noted the place for possible changes in the future. If you're interested please refer to the referenced issue (#589) 🙂 AFAIK no one is working on this, though I could be wrong.

**Comment by miguelusque** [comment]
Hi @leofang ,

Apologies for disturbing you again.

I have found a weird case that I think it is well-worth to mention.

The following code works:

> # Convert a TensorFlow EagerTensor to a CuPy ndarray
> src = tf.math.add(tf.zeros([2, 2]), [[1, 2], [3, 4]])
> dst = cp.fromDlpack(tf.experimental.dlpack.to_dlpack(src))
> 
> print(src.device)
> print(type(dst), "\n", dst)

```
/job:localhost/replica:0/task:0/device:GPU:0
<class 'cupy.core.core.ndarray'> 
 [[1. 2.]
 [3. 4.]]
```

While the following code doesn't work (I have highlighted in bold the code change):

> # Convert a TensorFlow EagerTensor to a CuPy ndarray
> src = tf.math.add(tf.zeros([2, 2]**, dtype=tf.dtypes.int32**), [[1, 2], [3, 4]])
> dst = cp.fromDlpack(tf.experimental.dlpack.to_dlpack(src))
> 
> print(src.device)
> print(type(dst), "\n", dst)

```
int(type(dst), "\n", dst)
/job:localhost/replica:0/task:0/device:GPU:0
<class 'cupy.core.core.ndarray'> 
 
---------------------------------------------------------------------------
CUDARuntimeError                          Traceback (most recent call last)
<ipython-input-83-2ce60eee9d5b> in <module>
      4 
      5 print(src.device)
----> 6 print(type(dst), "\n", dst)

cupy/core/core.pyx in cupy.core.core.ndarray.__str__()

cupy/core/core.pyx in cupy.core.core.ndarray.get()

cupy/core/core.pyx in cupy.core.core.ndarray.get()

cupy/cuda/memory.pyx in cupy.cuda.memory.MemoryPointer.copy_to_host()

cupy_backends/cuda/api/runtime.pyx in cupy_backends.cuda.api.runtime.memcpy()

cupy_backends/cuda/api/runtime.pyx in cupy_backends.cuda.api.runtime.check_status()

CUDARuntimeError: cudaErrorInvalidValue: invalid argument
```

Any ideas why?

And thank you for your great work with CuPy. I am a happy user of this library!

Miguel

**Comment by leofang** [comment]
Hi @miguelusque I know TF very little, but I can say you're still seeing the same error caused by a CPU tensor. For some reason even if I use the device context `with tf.device(...):` the tensors could still reside on CPU, and only actual computations are done on GPU. It's unclear what happened to me...
```python
>>> with tf.device("/GPU:0"):
...     a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
...     a.device
... 
'/job:localhost/replica:0/task:0/device:CPU:0'
```
If you upgrade to CuPy v8.4.0 you'll see a clearer error:
```python
>>> src = tf.convert_to_tensor([[1, 2], [3, 4]])
>>> dst = cp.fromDlpack(tf.experimental.dlpack.to_dlpack(src))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/dlpack.pyx", line 185, in cupy.core.dlpack.fromDlpack
  File "cupy/core/dlpack.pyx", line 226, in cupy.core.dlpack.fromDlpack
  File "cupy/core/dlpack.pyx", line 161, in cupy.core.dlpack.DLPackMemory.__init__
RuntimeError: CuPy is built against CUDA, different from the backend that backs the incoming DLPack tensor
>>> src.device
'/job:localhost/replica:0/task:0/device:CPU:0'
```

> thank you for your great work with CuPy. I am a happy user of this library!

Happy to hear CuPy works for you! Many thanks to the CuPy team at PFN who create and maintain this awesome library 🙂

**Comment by miguelusque** [comment]
You are right. If I invoke backing_device method instead. It highlights it is a CPU-based tensor. Thank you for your support. Much appreciated!
