### ISSUE TITLE
Excessive malloc time on Nvidia Ampere Arch

### ISSUE THREAD

**Issue by weishiuchang** [cupy/cupy#4593]
We recently upgraded our servers from V100s to A100s and encountered a lengthy initialization cupy.cuda.runtime.malloc issue. Narrowing down the problem we were able to reproduce it with:

`docker run -it --rm cupy/cupy:v8.0.0 python3 -c 'import time, cupy; start=time.time(); ptr=cupy.cuda.runtime.malloc(1); end=time.time(); print(end-start); cupy.cuda.runtime.free(ptr)'`

This took 67 seconds to malloc a single byte. However, successive mallocs within the same process took fractional seconds:

`docker run -it --rm cupy/cupy:v8.0.0 python3 -c 'import time, cupy; start=time.time(); ptr=cupy.cuda.runtime.malloc(1); end=time.time(); print(end-start); cupy.cuda.runtime.free(ptr); start=time.time(); ptr=cupy.cuda.runtime.malloc(1); end=time.time(); print(end-start); cupy.cuda.runtime.free(ptr)'`

Prints 67 seconds followed by 0.15 seconds. We put the V100s back into the same server and ran the same docker command and it resulted in 0.15s always. We have also tried to malloc different amounts, but whether it is 1 byte or multiple gigs, the first initialization is always roughly 67 seconds. Most of our processes do not last that long so the initial delay is doubling or tripling our runtimes.

We have contacted Nvidia and they were able to reproduce the same lengthy cupy.cuda.runtime.malloc on Ampere A100 and RTX A6000, with no such delay on Volta and Turing (they tested cuPy on A100, RTX A6000, GV100, & T4).

We plan on additional testing when time permits, but were wondering if this is something already known by cuPy (a quick search for Ampere and/or malloc delay returned nothing), and if there are additional commands or configurations we can try to help debug this problem once we have the hardware setup again.

**Comment by leofang** [comment]
Could you try an equivalent C code calling `cudaMalloc` (should just be a few lines) and see if there's something odd on the local environment? IIRC at least @anaruse has done some tests for CuPy on A100 but I don't think this issue was raised before.

**Comment by weishiuchang** [comment]
We had tested it with a few of the example code listed in /usr/local/cuda/samples/0_Simple/ (such as matrixMul) at the host level rather than in a docker container, and none of them took more than factional seconds to cudaMalloc. We have not ran it in n nvidia profiler however, as it was just a quick test for ourselves to narrow the problem. Sorry I didn't mention that in the initial.

**Comment by leofang** [comment]
I see, how about running the same codes in a docker (as you did in your original report) instead of on bare metal? Would it be Docker's fault?

**Comment by leofang** [comment]
btw which driver version are you on?

**Comment by leofang** [comment]
I can't reproduce this on bare metal:
```
$ python -c "import cupy; cupy.show_config()"
OS                           : Linux-5.4.0-64-generic-x86_64-with-glibc2.10
CuPy Version                 : 9.0.0b2
NumPy Version                : 1.20.0
SciPy Version                : 1.6.0
Cython Build Version         : 0.29.21
Cython Runtime Version       : 0.29.21
CUDA Root                    : /usr/local/cuda-11.0
CUDA Build Version           : 11000
CUDA Driver Version          : 11000
CUDA Runtime Version         : 11000
cuBLAS Version               : 11200
cuFFT Version                : 10201
cuRAND Version               : 10201
cuSOLVER Version             : (10, 6, 0)
cuSPARSE Version             : 11101
NVRTC Version                : (11, 0)
Thrust Version               : 100909
CUB Build Version            : 100909
Jitify Build Version         : <unknown>
cuDNN Build Version          : 8005
cuDNN Version                : 8005
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
Device 0 Name                : A100-SXM4-40GB
Device 0 Compute Capability  : 80
Device 1 Name                : A100-SXM4-40GB
Device 1 Compute Capability  : 80
Device 2 Name                : A100-SXM4-40GB
Device 2 Compute Capability  : 80
Device 3 Name                : A100-SXM4-40GB
Device 3 Compute Capability  : 80
Device 4 Name                : A100-SXM4-40GB
Device 4 Compute Capability  : 80
Device 5 Name                : A100-SXM4-40GB
Device 5 Compute Capability  : 80
Device 6 Name                : A100-SXM4-40GB
Device 6 Compute Capability  : 80
Device 7 Name                : A100-SXM4-40GB
Device 7 Compute Capability  : 80
$ python -c 'import time, cupy; start=time.time(); ptr=cupy.cuda.runtime.malloc(1); end=time.time(); print(end-start); cupy.cuda.runtime.free(ptr)'
0.3536720275878906
```

Due to permission issue I can't run Docker on this machine, though, so can't test if Docker is to blame. Perhaps you could build CuPy locally?

**Comment by weishiuchang** [comment]
We had not considered if it might be a docker issue, simply because the same docker run of cupy with the V100 slotted back in did not exhibit the same malloc delay. We may try to test that theory further once we have free hardware (all are currently being used).

We are running cuda 11.0.3 with nvidia-driver latest-dkms 450.51.06

**Comment by leofang** [comment]
Yeah give it a try. It could be that the driver has a bad interplay with Docker on a new architecture, since you said NVIDIA could also reproduce this issue.

Our driver is 450.102.04.

**Comment by leofang** [comment]
```
$ python -c 'import time, cupy; start=time.time(); ptr=cupy.cuda.runtime.malloc(1); end=time.time(); print(end-start); cupy.cuda.runtime.free(ptr); start=time.time(); ptr=cupy.cuda.runtime.malloc(1); end=time.time(); print(end-start); cupy.cuda.runtime.free(ptr)'
0.3302488327026367
0.0004801750183105469
```

**Comment by leofang** [comment]
Another way to run on bare metal without building from source: Installing CuPy from conda-forge.
```
$ conda create -n test -c conda-forge -y python=3.8 cupy cudatoolkit=11.0
$ conda activate test
$ python -c 'import time, cupy; start=time.time(); ptr=cupy.cuda.runtime.malloc(1); end=time.time(); print(end-start); cupy.cuda.runtime.free(ptr); start=time.time(); ptr=cupy.cuda.runtime.malloc(1); end=time.time(); print(end-start); cupy.cuda.runtime.free(ptr)'
0.4425685405731201
0.0004782676696777344
```

**Comment by kmaehashi** [comment]
Thanks for reporting! Currently, the CuPy image on Dockerhub uses CUDA Toolkit 10.2 ([Dockerfile](https://github.com/cupy/cupy/blob/master/docker/python3/Dockerfile#L1)), which does not support A100. We also had similar issue even in the bear metal environment with CUDA 10.x + A100.
We will consider upgrading it to CUDA 11 or later in v9 releases.

**Comment by leofang** [comment]
> We also had similar issue even in the bear metal environment with CUDA 10.x + A100.

I thought A100 is only supported since CUDA 11.0?

**Comment by kmaehashi** [comment]
> I thought A100 is only supported since CUDA 11.0?

Right, but it runs while the initialization takes much time.
