### ISSUE TITLE
BUG: CUDA_VERSION is set to 0 in sdist

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#4597]
I was investigating the bug reported in https://github.com/conda-forge/cupy-feedstock/issues/98, and it turns out the reason is on Conda-Forge we built CuPy from sdist, but the source has `CUDA_VERSION` inlined to 0:
```c++
// cupy_backends/cuda/api/driver.cpp

/* ... */

static PyObject *__pyx_pf_13cupy_backends_4cuda_3api_6driver_2get_build_version(CYTHON_UNUSED PyObject *__pyx_self) {
  PyObject *__pyx_r = NULL;
  __Pyx_RefNannyDeclarations
  __Pyx_RefNannySetupContext("get_build_version", 0);

  /* "cupy_backends/cuda/api/driver.pyx":141
 * 
 * def get_build_version():
 *     return CUDA_VERSION             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __Pyx_XDECREF(__pyx_r);
  __Pyx_INCREF(__pyx_int_0);
  __pyx_r = __pyx_int_0;
  goto __pyx_L0;

  /* "cupy_backends/cuda/api/driver.pyx":140
 * ###############################################################################
 * 
 * def get_build_version():             # <<<<<<<<<<<<<<
 *     return CUDA_VERSION
 * 
 */

  /* function exit code */
  __pyx_L0:;
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* ... */

static CYTHON_SMALL_CODE int __Pyx_InitGlobals(void) {
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) __PYX_ERR(0, 1, __pyx_L1_error);
  __pyx_int_0 = PyInt_FromLong(0); if (unlikely(!__pyx_int_0)) __PYX_ERR(0, 1, __pyx_L1_error)
  return 0;
  __pyx_L1_error:;
  return -1;
}
```
I don't have a good solution or patch for now, as it seems to imply sdist should be generated per CUDA version. Perhaps I am overlooking some obvious fix?

cc: @jakirkham @kmaehashi

**Comment by kmaehashi** [comment]
Hmm... I don't come up with the good solution either other than installing the Cython during the installation of CuPy so that CPP code is generated in the user envirnoment.
I think the same can be said for `use_hip` compile time env. (sdist should be buildable on HIP but I guess currently not)

**Comment by leofang** [comment]
Yeah, in #4556 I am removing `use_hip` and making `HIP_VERSION` propagated together with `CUDA_VERSION`, but it wouldn't solve the problem I think. On Conda-Forge we have no problem switching to the git source, so this issue is more for awareness.

**Comment by kmaehashi** [comment]
Discussed a bit in the team, adding Cython to `setup_requires` in `setup.py` and exclude cpp files from sdist sounds good to us. This way we can also resolve https://github.com/cupy/cupy/pull/4494 without dirty hacking.

**Comment by leofang** [comment]
It's great to solve two bugs at once 👍
