### ISSUE TITLE
Percentile output non-monotonic for monotonically increasing percentiles

### ISSUE THREAD

**Issue by wphicks** [cupy/cupy#4607]
# Description
For certain inputs, `cupy.percentile` with linear interpolation can produce non-monotonically increasing output for a monotonically-increasing list of desired percentiles. This is identical to the issue resolved by https://github.com/numpy/numpy/pull/16273 in numpy and can be resolved with the same adjustment in how the linear interpolation gets calculated in the `percentile_weightnening` kernel.

# Reproduction code
```python
import cupy
magic_value = -1.00795396e+08
arr = cupy.array([magic_value, 1.2, magic_value, 2.1, 3.5])
quantiles = cupy.linspace(0, 100, 21)
percentile = cupy.percentile(arr, quantiles, interpolation='linear')
print(percentile[0] <= percentile[1]) # Should be True; is False
```
This example was found using Hypothesis, and while the other values in the array can be anything, this "magic" value (or one of the other magic values that Hypothesis found) must be present twice in order to demonstrate the issue. These magic values are due to how floating error propagates with the current linear interpolation formula (additional details [here](https://math.stackexchange.com/questions/907327/accurate-floating-point-linear-interpolation)) and depend on which and how many percentiles are calculated.

# Environment
OS                           : Linux-5.8.0-36-generic-x86_64-with-glibc2.31
CuPy Version                 : 8.4.0
NumPy Version                : 1.20.0
SciPy Version                : None
Cython Build Version         : 0.29.21
CUDA Root                    : /home/whicks/anaconda3/envs/cupy
CUDA Build Version           : 11000
CUDA Driver Version          : 11020
CUDA Runtime Version         : 11000
cuBLAS Version               : 11200
cuFFT Version                : 10201
cuRAND Version               : 10201
cuSOLVER Version             : (10, 6, 0)
cuSPARSE Version             : 11101
NVRTC Version                : (11, 0)
Thrust Version               : 100909
CUB Build Version            : 100909
cuDNN Build Version          : 8005
cuDNN Version                : 8005
NCCL Build Version           : 2708
NCCL Runtime Version         : 2803
cuTENSOR Version             : 10202
Device 0 Name                : Quadro RTX 8000
Device 0 Compute Capability  : 75
Device 1 Name                : Quadro RTX 8000
Device 1 Compute Capability  : 75

**Comment by wphicks** [comment]
This should require only a very small change, and I'm happy to take care of it myself later today or first thing tomorrow.

**Comment by kmaehashi** [comment]
Thank you for reporting! It would be great if you could make a PR 👍🏼
