### ISSUE TITLE
cupy map_coordinates doesn't support order = 3? 

### ISSUE THREAD

**Issue by Joevaen** [cupy/cupy#4609]
Thank you for using and contributing to CuPy!

cupy map_coordinates doesn't support order = 3?

**Comment by grlee77** [comment]
The 8.x releases only support orders 0 and 1. The upcoming 9.0 release supports all orders (0-5) supported by SciPy. Many other features have been added to the `cupyx.scipy.ndimage` module in 9.0.

If you are using conda, you can install a release candidate for 9.0 using
```
conda install conda-forge/label/cupy_rc::cupy=9
```
