### ISSUE TITLE
Support NumPy 1.20

### ISSUE THREAD

**Issue by toslunar** [cupy/cupy#4621]
### Deprecations

- type aliases `np.int`, `np.float`, and etc.
  - [x] #4598
  - [x] #4605
  - [x] #4620
- `shape=None` in `ndarray`, `zeros`, and etc.
  - [x] #4616

### Changes

- int `linspace` rounding
  - [x] #4604
- all-zero `poly1d`
  - [x] #4611

**Comment by asi1024** [comment]
Now all CIs for the master branch are green.

**Comment by asi1024** [comment]
#4625 is the last PR for this task.
