### ISSUE TITLE
By switching device altenately accelerate calculations?

### ISSUE THREAD

**Issue by TakuNishiumi** [cupy/cupy#4655]
This is not a bug. I would like to ask a question.
I tested below codes and
I found that by switching device alternately accelerated calculation.
Do you know the reason?

```python
import cupy as cp
import numpy as np
```

## define function

```python
arr0 = np.linspace(0, 1023,1024)
arr1 = np.tile(arr0, (1024, 1))

def example(device, arr1):
    cp.cuda.Device(device).use()
    arr2 = cp.array(arr1)
    return cp.median(arr2)
```

## GPU0 => GPU1 => GPU0 => ...

```python
%%time
for i in range(0,10000):
    for j in range(0,2):
        r = example(j,arr1)
```

    CPU times: user 17.9 s, sys: 212 ms, total: 18.1 s
    Wall time: 18.1 s

## GPU0 only

```python
%%time
for i in range(0,10000):
    for j in range(0,2):
        r = example(0,arr1)
```

    CPU times: user 22.1 s, sys: 5.53 s, total: 27.7 s
    Wall time: 27.6 s

## GPU1 only

```python
%%time
for i in range(0,10000):
    for j in range(0,2):
        r = example(1,arr1)
```

    CPU times: user 22.7 s, sys: 6.21 s, total: 28.9 s
    Wall time: 28.9 s

## GPU0 => GPU1

```python
%%time
for j in range(0,2):
    for i in range(0,10000):
        r = example(j,arr1)
```

    CPU times: user 22.3 s, sys: 5.38 s, total: 27.7 s
    Wall time: 27.6 s

* Conditions 
OS                           : Linux-4.15.0-135-generic-x86_64-with-debian-buster-sid
CuPy Version                 : 8.4.0
NumPy Version                : 1.19.2
SciPy Version                : 1.5.2
Cython Build Version         : 0.29.21
CUDA Build Version           : 11010
CUDA Driver Version          : 11010
CUDA Runtime Version         : 11010
cuBLAS Version               : 11300
cuFFT Version                : 10102
cuRAND Version               : 10102
cuSOLVER Version             : (11, 0, 1)
cuSPARSE Version             : 11300
NVRTC Version                : (11, 1)
Thrust Version               : 100910
CUB Build Version            : 100910
cuDNN Build Version          : 8005
cuDNN Version                : 8001
NCCL Build Version           : 2708
NCCL Runtime Version         : 2708
cuTENSOR Version             : None
Device 0 Name                : TITAN RTX
Device 0 Compute Capability  : 75
Device 1 Name                : TITAN RTX
Device 1 Compute Capability  : 75

**Comment by emcastillo** [comment]
You are splitting your workload into two GPUs while the work amount remains constant.

See that you are doing the same amount of iterations with one and two devices, so it is expected to take more time with only one gpu. Work is enqueued and control flow returns to the cpu immediately. Calculations are being done in the background while you are enqueuing the next task.

Also, you are synchronizing the devices every iteration by doing a CPU->GPU transfer. `arr2 = cp.array(arr1)`.
Usually you would like to measure like:

```
arr0 = np.linspace(0, 1023,1024)
arr1 = cp.array(np.tile(arr0, (1024, 1)) # Create the array here to avoid sync everytime

def example(device, arr1):
    cp.cuda.Device(device).use()
    return cp.median(arr1) # Avoids syncronization
```

GPU0 only
```
%%time
for i in range(0,10000):
    for j in range(0,2):
        r = example(0,arr1)
cp.cuda.Stream.null.synchronize() # Wait for all the GPU work to be over
```

GPU0 and GPU1
```
%%time
for i in range(0,10000):
    for j in range(0,2):
        r = example(j,arr1)
cp.cuda.Stream.null.synchronize() # Wait for all the GPU work to be over
```
This should take half the time of only GPU0

**Comment by TakuNishiumi** [comment]
Dear @emcastillo,

Thank you for your comment!

I predicted that time of GPU0=GPU1=GPU0&GPU1 is same because python has GIL. So I was surprised.
Anyway, we can speed up such calculations if we use alternately multiple GPUs, because the calculation worked in background.
Is this correct?

**Comment by emcastillo** [comment]
Yes, you are correct. Computations are done asynchronously.

**Comment by TakuNishiumi** [comment]
Thank you!
