### ISSUE TITLE
RuntimeError: CUDA environment is not correctly set up

### ISSUE THREAD

**Issue by fathia-ghribi** [cupy/cupy#4696]
when i run this code from lda2vec  in google colab `https://github.com/cemoody/lda2vec/blob/master/examples/hacker_news/lda2vec/lda2vec_run.py`
i'm getting this error: 
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/chainer/chainer#installation).No module named 'cupy.util'
how to fix this probleme ??

**Comment by kmaehashi** [comment]
Please use CuPy v7 for Chainer v7. https://github.com/chainer/chainer/issues/8601
