### ISSUE TITLE
CUDA 11.2 Wheel Packages for Linux

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#4704]
**Edit (2021-03-23)**: We've uploaded `cupy-cuda112` for Linux. You can simply install it by:

```
pip install cupy-cuda112
```

The following workaround (`-f` option) is no longer needed.

-----

[`cupy-cuda112` package on PyPI](https://pypi.org/project/cupy-cuda112/) is currently only available for Windows. We are going to publish Linux wheels once we get approval from the PyPI team (https://github.com/pypa/pypi-support/issues/939). Meanwhile, Linux wheels can be downloaded from the Assets section of each release.

### v8.5.0

```
pip install cupy-cuda112 -f https://github.com/cupy/cupy/releases/v8.5.0
```

### v9.0.0b3

```
~pip install cupy-cuda112 -f https://github.com/cupy/cupy/releases/v9.0.0b3~
```

**Comment by leofang** [comment]
For Conda users:
```
conda install -c conda-forge cupy cudatoolkit=11.2
```

**Comment by leofang** [comment]
(updated the instruction for the rc package)

**Comment by kmaehashi** [comment]
We got approval so I uploaded Linux wheels. Description updated.
