### ISSUE TITLE
Automatically infer HCC_AMDGPU_TARGET

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#4719]
- build: Support `CUPY_NVCC_GENERATE_CODE=current` equivalent in ROCm to set `HCC_AMDGPU_TARGET` automatically
- runtime: Automatically infer `HCC_AMDGPU_TARGET` (this environment variable is only needed for hipcc case?)

**Comment by leofang** [comment]
> * runtime: Automatically infer `HCC_AMDGPU_TARGET` (this environment variable is only needed for hipcc case?)

I suspect we need it at runtime. There was a time I forgot to set it with a fresh local build, but CuPy still ran fine:
https://github.com/cupy/cupy/blob/6a663512ee888c49ef6542fd065a6046fa9e9353/cupy/cuda/compiler.py#L761-L767

**Comment by leofang** [comment]
It should be readily testable by running `test_raw.p` without the env var set. Both `hiprtc` and `hipcc` got tested.

**Comment by leofang** [comment]
> * build: Support `CUPY_NVCC_GENERATE_CODE=current` equivalent in ROCm to set `HCC_AMDGPU_TARGET` automatically

I just did a quick test locally. It seems if only building for local use, as mentioned in the above linked comment `hipcc` can also infer `HCC_AMDGPU_TARGET` correctly. I confirmed this by removing the `cub` and `thrust` modules, unset both `HCC_AMDGPU_TARGET` and `__HIP_PLATFORM_HCC__`, and rebuild. After that, we can examine the binary by ROCm's built-in tool (similar to `cuobjdump` on CUDA):
```
extractkernel -i cupy/cuda/thrust.cpython-37m-x86_64-linux-gnu.so
```
which generates three files, two of which are for my arch (gfx906):
```
$ cd cupy/cuda; ls -lh thrust.cp*
-rw-rw-r-- 1 leofang leofang 328K Feb 23 16:16 thrust.cpp
-rwxrwxr-x 1 leofang leofang 7.6M Feb 23 16:19 thrust.cpython-37m-x86_64-linux-gnu.so
-rw-rw-r-- 1 leofang leofang 6.2M Feb 23 16:20 thrust.cpython-37m-x86_64-linux-gnu.so-000.bundle
-rw-rw-r-- 1 leofang leofang 6.2M Feb 23 16:20 thrust.cpython-37m-x86_64-linux-gnu.so-000-gfx906.hsaco
-rw-rw-r-- 1 leofang leofang  73M Feb 23 16:20 thrust.cpython-37m-x86_64-linux-gnu.so-000-gfx906.isa
```

**Comment by leofang** [comment]
>> > * runtime: Automatically infer `HCC_AMDGPU_TARGET` (this environment variable is only needed for hipcc case?)
>> 
>> I doubt we need it at runtime. There was a time I forgot to set it with a fresh local build, but CuPy still ran fine:
>> 
>> https://github.com/cupy/cupy/blob/6a663512ee888c49ef6542fd065a6046fa9e9353/cupy/cuda/compiler.py#L761-L767
>
> It should be readily testable by running `test_raw.py` without the env var set. Both `hiprtc` and `hipcc` got tested.

OK I tested this locally without setting `HCC_AMDGPU_TARGET` and `__HIP_PLATFORM_HCC__`. By removing the checks for `HCC_AMDGPU_TARGET` in `cupy/cuda/compiler.py` all checks passed on ROCm 3.5.0. Let me know if you think it's ok to remove them and I will send a PR.

**Comment by kmaehashi** [comment]
I skimmed hipcc code (it's written in perl 😅 ), it seems the output from `/opt/rocm/bin/rocm_agent_enumerator -t GPU` (which prints arch for each GPU installed) is used when `HCC_AMDGPU_TARGET` is unset. I'm curious how hiprtc would behave, though.

**Comment by leofang** [comment]
> I skimmed hipcc code (it's written in perl 😅 ), it seems the output from `/opt/rocm/bin/rocm_agent_enumerator -t GPU` (which prints arch for each GPU installed) is used when `HCC_AMDGPU_TARGET` is unset. 

Cool, thanks @kmaehashi. Pointer: https://github.com/ROCm-Developer-Tools/HIP/blob/2080cc113a2d767352b512b9d24c0620b6dee790/bin/hipcc#L717-L728

> I'm curious how hiprtc would behave, though.

hipRTC first queries the current device, and then delegates the actual compilation to the ROCclr backend:
https://github.com/ROCm-Developer-Tools/HIP/blob/2080cc113a2d767352b512b9d24c0620b6dee790/rocclr/hip_rtc.cpp#L225
https://github.com/ROCm-Developer-Tools/ROCclr/blob/5cefcaf62893fcd86c8feed6bb1ebb84850fcd2f/platform/program.cpp#L477

So looks like we're good to remove the advice of setting `HCC_AMDGPU_TARGET` at runtime.
