### ISSUE TITLE
Fail build if essential module cannot be built

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#4750]
Currently, when CuPy failed to configure a module other than `cuda`, build succeeds without building the module.
If non-optional (essential) modules cannot be built, the build should fail with an error.

Optional modules are nccl, cudnn, nvtx
Non-optional modules are others e.g., random, thrust, cub, dlpack, ...

**Comment by takagi** [comment]
Exhaustive list of MODULES in `cupy_setup_buid.py`:
- mandatory
  - cuda
  - cusolver
  - cutensor
  - cub
  - jitify
  - random
  - thrust
  - dlpack
- optional
  - nccl
  - cudnn
  - nvtx
