### ISSUE TITLE
Deprecate `cupy.bool`, `cupy.int`, `cupy.float` and `cupy.complex`

### ISSUE THREAD

**Issue by asi1024** [cupy/cupy#4755]
`numpy.bool`, `numpy.int`, `numpy.float` and `numpy.complex` were deprecated in NumPy 1.20.

**Comment by kmaehashi** [comment]
https://github.com/cupy/cupy/blob/57ef68c33a03ac68ddba149b20657c3668ae511c/cupy/__init__.py#L215
