### ISSUE TITLE
Initializing CuPy array ~30x slower than NumPy

### ISSUE THREAD

**Issue by VisionaryMind** [cupy/cupy#4767]
We are now running simple tests with CuPy to gauge its ability to replace our NumPy-based pipeline. Unfortunately, it appears that initializing an array takes at least 10x longer with CuPy than with Numpy.  For example:

$ python3.9 -m timeit 'import cupy; t = cupy.array([-2.48370488e-05, -4.60709998e-04,  3.10862320e-03,  1.00000000e+00])'
**1 loop, best of 5: 298 usec per loop**

$ python3.9 -m timeit 'import numpy; t = numpy.array([-2.48370488e-05, -4.60709998e-04,  3.10862320e-03,  1.00000000e+00])'
**1 loop, best of 5: 10.4 usec per loop**

<details>
<summary>Conditions</summary>

* OS                           : Linux-4.9.201-tegra-aarch64-with-glibc2.27
CuPy Version                 : 9.0.0b3
NumPy Version                : 1.20.1
SciPy Version                : 1.6.1
Cython Build Version         : 0.29.22
Cython Runtime Version       : 0.29.22
CUDA Root                    : /usr/local/cuda-10.2
CUDA Build Version           : 10020
CUDA Driver Version          : 10020
CUDA Runtime Version         : 10020
cuBLAS Version               : 10202
cuFFT Version                : 10102
cuRAND Version               : 10102
cuSOLVER Version             : (10, 3, 0)
cuSPARSE Version             : 10301
NVRTC Version                : (10, 2)
Thrust Version               : 100907
CUB Build Version            : 101200
Jitify Build Version         : 60e9e72
cuDNN Build Version          : 8000
cuDNN Version                : 8000
NCCL Build Version           : 2804
NCCL Runtime Version         : 2804
cuTENSOR Version             : None
Device 0 Name                : Xavier
Device 0 Compute Capability  : 72
</details>

Is this expected behavior? If so, is there any way to speed up array creation, or is this library more to be used for single-pass, large operations without loops? Our current workflow builds smaller NumPy array and gradually concatenates them together into millions of datapoints. By the time we reach ~1,000,000, CuPy concatenate is crawling to more than 100x slowdown from baseline. NumPy running the same concatenates processes all points, up to billions, in just under a minute. We were waiting ~1 hour for CuPy to process the same task and eventually stopped the process.

**Comment by emcastillo** [comment]
This is expected, array creation with CPU data is pretty heavy since you have to create the array first in the CPU and then transfer it to the GPU. This shortcoming is mostly due to the CUDA programming model and the GPU computing architecture than CuPy. There are a few optimization techniques to alleviate this such as using pinning memory and others but I doubt they will be helpful in your case.

If you can somehow change your code to create your arrays with larger sizes and operate on slices of them rather than concatenating it may help a bit.

**Comment by leofang** [comment]
Just FYI, the way you timed it also includes the time on initializing a CUDA context, which is known slow. A proper timing involving GPUs should always do a few "warm-up" runs. `cupyx.time.repeat` does it for you:
```python
>>> import cupy as cp
>>> import numpy as np
>>> from cupyx.time import repeat
>>>
>>> print(repeat(cp.array, ([-2.48370488e-05, -4.60709998e-04, 3.10862320e-03, 1.00000000e+00],)))
array               :    CPU:   20.341 us   +/- 0.788 (min:   19.717 / max:   40.809) us     GPU-0:   24.410 us   +/- 0.893 (min:   23.520 / max:   45.408) us
>>> print(repeat(np.array, ([-2.48370488e-05, -4.60709998e-04, 3.10862320e-03, 1.00000000e+00],)))
array               :    CPU:    1.043 us   +/- 0.524 (min:    0.844 / max:   15.370) us     GPU-0:    5.377 us   +/- 2.514 (min:    3.840 / max:   25.696) us
```
It is still slow (for the reasons replied above; also, your test workload is too small), but not as crazy.

**Comment by VisionaryMind** [comment]
I have been going over multiple approaches to this problem. Given slowdowns in both initialization and small datasets (that don't saturate the GPU computing surface), I have consolidated the entire dataset into a single cuDF dataframe and then attempt to vectorize functions over its contents with CuPy.

First, a brief summary of what we are trying to do -- We process gigabyte / terrabyte pointcloud data streamed from multiple LiDARs. There are roughly 100 point clouds per second, each containing 2,400 points. Each of those clouds has a specific transform (i.e. rotation and translation, using a 4x4 matrix). Each cloud's points and positions are unique. Grouping or extrapolation is not possible, given the scan area (up to 400 square meters).

So that leaves us with the task of applying  4x4 matrices using numpy.dot / matmul per cloud. In our (small) test dataset, that amounts to ~3,000 clouds and 9,436,800 points. I initially attempted to mount this task using CuPy alone, iterating over the cloud dataset, but that leads to the delays established above.

It seems clear to me I need to compose a custom UDF, but it's not entirely obvious how that would play out, as datatypes need to be homogeneous. The problem is we have that "wildcard" field at the end of the dataset containing the 4x4 matrix. To make matters more complicated, in order to put all clouds into a single dataframe / CuPy matrix, it is necessary to flatten x,y,z, so there are 2,400 rows for each cloud, each row representing a single point. I have tried slicing the data in 2,400 chunks, transposing, then multiplying by a matrix based on that chunk's matrix reference, but it is still slow. 

Before I attempt to go down the road of a custom function, I need to know if that would be worth the time expenditure or if there are any other approaches that could serve our purposes better. As it stands, "rotating" 3,000 clouds takes ~3 minutes, if we include the data retrieval and packaging. That would jump to hours or days with our typical production datasets. Here is a sample of the test data:

**Cloud**:

   cloudindex  tfidx      x      y      z
0         0.0    0.0  1.965 -1.180  0.556
1         0.0    0.0  1.983 -1.200  0.605
2         0.0    0.0  1.986 -1.212  0.651
3         0.0    0.0  1.981 -1.220  0.696
4         0.0    0.0  1.987 -1.237  0.745
5         0.0    0.0  1.996 -1.256  0.798
6         0.0    0.0  1.968 -1.180  0.565
7         0.0    0.0  1.982 -1.197  0.613
8         0.0    0.0  1.983 -1.208  0.658
9         0.0    0.0  1.980 -1.217  0.703

**Transform matrices** (in quaternions):
	tfidx	rotx	roty	rotz	rotw	tx	ty	tz	pad
0	0	-0.005878243	0.003167481	0.000616568	0.999977589	2.483704884E-05	0.00046071	0.003108623	1
1	1	-0.005882217	0.00318294	0.000619622	0.999977469	2.479219074E-05	0.000467599	0.003160389	1
2	2	-0.00587778	0.003173387	0.000632759	0.999977469	2.905680958E-05	0.000474509	0.003213217	1
3	3	-0.005846149	0.003170798	0.000620814	0.999977708	-1.201823216E-05	0.000791186	0.002964074	1
4	4	-0.00584388	0.003189664	0.000622862	0.999977648	1.273459134E-06	0.00080655	0.00300498	1
5	5	-0.00584413	0.003187391	0.000622334	0.999977648	8.488708772E-06	0.000823291	0.003043184	1
6	6	-0.005841899	0.003185551	0.000628488	0.999977648	1.646657074E-05	0.00083952	0.003083278	1
7	7	-0.005844229	0.003191105	0.000618665	0.999977648	1.82285894E-05	0.000853595	0.003131089	1
8	8	-0.005836984	0.003200473	0.000636424	0.999977708	2.540703827E-05	0.000867733	0.003179409	1
9	9	-0.005846468	0.003180521	0.000640258	0.999977648	0.000136525	0.000504061	0.002965805	1
10	10	-0.005844729	0.003178042	0.000634281	0.999977708	0.000154513	0.000503787	0.003007369	1

Here is a brief breakdown of how this data is currently being handled:

1. Both clouds and transform matrices are placed into separate Pandas dataframes. cuDF cannot be used, as some of the libraries used for conversions implement Numpy, and we don't want to re-write them (pyquaternion, for example).

2. An additional "matrix" column is added to the transform dataset, containing a 4x4 matrix derived from the quaternion / translation columns. The resulting records look like this:
![image](https://user-images.githubusercontent.com/47434136/110125957-888f0d00-7d89-11eb-9f85-6481dec604c5.png)

3. Next, the clouds are merged with the transforms using `clouds = clouds.merge(tranforms,on='tfidx').` I realize this is inefficient, because there are 2,400x less transforms than clouds, and this greatly expands the total dataset. The only other option is putting the tranforms into a dictionary and looping on slices, which, as I have already mentioned, is _quite slow_. This merge appears to be marginally faster. 

4. The cloud points are rotated by channeling them into a function: 
`c[['x','y','z']] = rotateclouds(c['x'].values,c['y'].values,c['z'].values,c['pad'].values,c['matrix'].values)`

That function takes three minutes to run:

`def rotateclouds_cuda(x,y,z,p,rs):
    
    points = np.vstack((x,y,z,p))
    
    for i,r in enumerate(rs):
        points[:,i] = np.dot(points[:,i],r)
    
    return pd.DataFrame(points.T) `

To be clear, this is a stopgap to get things working. I couldn't figure out how to use Numpy's "apply_along_axis" method with this data, because there isn't a single static function call. Every single vertically stacked line is a point and must be multiplied by its corresponding matrix (a single transposed row from the pd.Series stored in rs). 

My apologies for running off with a lot of detail here, but we've been sitting on this task for over a week now and can't figure out how to cut the processing time down to seconds -- which was the whole reason for looking at CUDA-enabled libraries. I am open to any suggestions.

Processing time is a critical factor for us, because we will have datasets with literally hundreds of thousands of clouds and billions of points, and what is slow at 3,000 could take hours or days with our realtime data.

**Comment by leofang** [comment]
Hi @VisionaryMind Thank you for your detailed explanation! I think it's helpful for us to learn more how to help. 

So on your `rotateclouds` function: It looks like the inputs `x`, `y`, `z`, and `pads` are 1D arrays of size 2400, and `rs` is a 2400-stack of 4\*4 matrices? And for each point `i` (total 2400) you need to take a dot product of `(x_i, y_i, z_i, pad_i)` with the associated 4\*4 matrix? I think we support *batched* (vectorized) matrix-matrix multiplication so you don't need that for loop. 
```python
points = cp.vstack((x,y,z,p))
processed_points = cp.dot(points.T, r).T
```

On `apply_along_axis`: CuPy added it recently (#4008), so if you install CuPy v9 (currently on beta, available on both PyPI and Conda-Forge) you should be able to test it out, but if I understand your use case correctly `cp.dot` should be sufficient. What's unclear to me is when your data is moved from CPU to GPU (since you mentioned a few dependencies are CPU-only) -- could you elaborate on that?

cc: @kkraus14 Could you tag a few cuDF people to help @VisionaryMind's interesting use case of cuDF + CuPy? I don't think I am the best person giving advice on best practices of cuDF 😅

**Comment by kkraus14** [comment]
> cc: @kkraus14 Could you tag a few cuDF people to help @VisionaryMind's interesting use case of cuDF + CuPy? I don't think I am the best person giving advice on best practices of cuDF 😅

I'm keeping an eye on this, but seems like there aren't any questions related to cuDF as it's mainly just being used as a convenience storage mechanism here. One comment I will make is that cuDF stores data differently than Pandas does under the hood. CuDF is purely columnar, so each column is effectively a 1d array likely with its own memory allocation, whereas Pandas has the block manager under the hood which will try to store things in a 2d array if possible.
