### ISSUE TITLE
Bump to cuDNN 8.1.1.33

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#4779]

**Comment by takagi** [comment]
- [x] Update chainer-test to test version.
- [ ] Update the library installer.
  - [ ] Fix `cupyx/tools/install_library.py`.
  - [ ] Backport.
- [ ] Wheel distribution
  - [ ] Update cupy-release-tools.
- [ ] Documentation
  - [ ] Update Requirements section in [Installtion Guide](https://docs.cupy.dev/en/latest/install.html)
- [ ] Implement new features using the version, if any.
