### ISSUE TITLE
Order of axes after advanced indexing

### ISSUE THREAD

**Issue by toslunar** [cupy/cupy#4799]
In some cases, order of axes after advanced indexing differs betwen NumPy and CuPy.

```
>>> for xp in (numpy, cupy):
...     print(xp.__name__)
...     print(f"{xp.zeros((3, 4, 5))[:, [0, 1], [0, 1]].shape = }")
...     print(f"{xp.zeros((3, 4, 5))[:, [0, 1], ..., [0, 1]].shape = }")
...
numpy
xp.zeros((3, 4, 5))[:, [0, 1], [0, 1]].shape = (3, 2)
xp.zeros((3, 4, 5))[:, [0, 1], ..., [0, 1]].shape = (2, 3)
cupy
xp.zeros((3, 4, 5))[:, [0, 1], [0, 1]].shape = (3, 2)
xp.zeros((3, 4, 5))[:, [0, 1], ..., [0, 1]].shape = (3, 2)
```

The `Ellipsis` index is not always equivalent with some number of slices (`(slice(None),) * n`).  The NumPy doc says
> Two cases of index combination need to be distinguished:
>
> - The advanced indexes are separated by a slice, [`Ellipsis`](https://docs.python.org/dev/library/constants.html#Ellipsis) or [`newaxis`](https://numpy.org/doc/stable/reference/constants.html#numpy.newaxis). For example `x[arr1, :, arr2]`.
> - The advanced indexes are all next to each other. For example `x[..., arr1, arr2, :]` but *not* `x[arr1, :, 1]` since `1` is an advanced index in this regard.

in https://numpy.org/doc/stable/reference/arrays.indexing.html#combining-advanced-and-basic-indexing.

The function `internal.complete_slice_list` may not be a correct way to implement `Ellipsis`.  It says "# Expand ellipsis into empty slices" and does
https://github.com/cupy/cupy/blob/05ddcc013c248613eae9ce56cc1817b016b001cf/cupy/core/internal.pyx#L255-L256

See also #1512 for the issue on the number of `slice(None)`.

**Comment by kmaehashi** [comment]
Oops I noticed to set assignee for this issue. @toslunar Could you take care of this?
