### ISSUE TITLE
How to get GPU model

### ISSUE THREAD

**Issue by mfoglio** [cupy/cupy#4807]
Is there a way to retrieve the GPU model? 

For instance, in pycuda the device has the `name` function: see https://documen.tician.de/pycuda/driver.html#pycuda.driver.Device.name

**Comment by leofang** [comment]
Off top of my head:
https://github.com/cupy/cupy/blob/50f22f04d8a98fa1c67131fe65bfc0b15c73a432/cupyx/_runtime.py#L240-L243
I suppose it is fairly straightforward to support `cupy.cuda.Device().name` similar to PyCUDA's API if there's a need.

**Comment by emcastillo** [comment]
This seems to be solved, so let's close it.
