### ISSUE TITLE
Implement Cupy equivalent of numpy.degree2rad

### ISSUE THREAD

**Issue by cjnolet** [cupy/cupy#4817]
The k-nearest neighbors implementation in 0.19 is going to include Haversine as one of the distance options. We followed Scikit-learn's style of assuming the input has been normalized to radians and it would be useful to provide a simple convenience function for users to convert a matrix of degrees to radians on device.

**Comment by leofang** [comment]
There is already a `cupy.deg2rad`, following `numpy.deg2rad`: https://docs.cupy.dev/en/stable/reference/generated/cupy.deg2rad.html 
Am I missing something?

**Comment by cjnolet** [comment]
Yeah, for some reason I missed
