### ISSUE TITLE
Compile without modules to reduce memory footprint

### ISSUE THREAD

**Issue by hyperfraise** [cupy/cupy#4863]
Hi. 

I see that, in the latest version, minimum memory footprint is about 190MB.

Is there a way to remove some modules from compilation, like cudnn or nccl, in order to reduce this ?

I only need to do some very basic things with cupy. Barely more than resizing and reshaping. And I don't need it to be fast anyways.

Thank you in advance.

**Comment by kmaehashi** [comment]
Optional libraries like cuDNN and NCCL are not built if they're unavailable at build time. You can also consider using `CUPY_NVCC_GENERATE_CODE=current` option to reduce fatbin size by building CuPy for your GPU only.

**Comment by hyperfraise** [comment]
Please reopen.

I tried commenting lines in there and it didn't change the GPU memory size taken 
https://github.com/cupy/cupy/blob/master/cupy_setup_build.py

I removed almost everything and it was still always the same size in memory.

**Comment by hyperfraise** [comment]
How to reduce the memory footprint ?

**Comment by hyperfraise** [comment]
Thank you.
