### ISSUE TITLE
Cupy out of memory in multithreading applications

### ISSUE THREAD

**Issue by mfoglio** [cupy/cupy#4866]
I have an application that starts several threads. Each thread uses cupy. There seems to be some memory leakage but I cannot understand why.

I tried to set the memory limit as soon as I start the application:

```
    mempool = cupy.get_default_memory_pool()
    with cupy.cuda.Device(0):
        mempool.set_limit(size=2 * 1024 ** 3)  # 2 GiB
```
However, when debugging, if I stop in one of the threads and run `cp.get_default_memory_pool().get_limit()` the memory limits seem 0.

I then used an environment variable `CUPY_GPU_MEMORY_LIMIT=1073741824` and I have been able to find the same limit within the thread. But will this be a limit per thread or a global limit?

I also tried to force cupy to release memory: after starting each thread I stored the default memory pool `mempool = cp.get_default_memory_pool()` and then I frequently call the `free_all_blocks()`. Same for the default pinned memory pool. However, 20 minutes after the application has started, the has been a cupy error and, consequently, the application stopped working (all GPU operations couldn't work). I will reproduce the error and write it here as soon as I can.

My questions are the following:
- How can I set a global memory limit?
- Are there any situations where `free_all_blocks` can cause crashes (maybe if called at the same time by two different threads)?
- How can I see what variables are allocated on the GPU and causing the memory leak? Each of my threads has an infinite loop that uses a small cupy array. Since the cupy array is initialized at the beginning of each iteration (kind of `myvar = cp.array(...)`) its reference should be lost at the beginning of the next iteration. So it is strange that cupy is not releasing the memory

Thanks

EDIT: when calling `free_all_blocks()`, after many executions of the loop, the following error happened, causing the process never to recover.
```
    cpu_output = gpu_output.get()
  File "cupy/core/core.pyx", line 1422, in cupy.core.core.ndarray.get
  File "cupy/core/core.pyx", line 1491, in cupy.core.core.ndarray.get
  File "cupy/core/core.pyx", line 1497, in cupy.core.core.ndarray.get
  File "cupy/cuda/memory.pyx", line 446, in cupy.cuda.memory.MemoryPointer.copy_to_host
  File "cupy_backends/cuda/api/runtime.pyx", line 632, in cupy_backends.cuda.api.runtime.memcpy
  File "cupy_backends/cuda/api/runtime.pyx", line 247, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Comment by mfoglio** [comment]
Possibly related to this: https://stackoverflow.com/questions/63061699/memory-leak-in-python-for-loop-even-if-i-delete-all-variables-at-the-end-of-each

**Comment by emcastillo** [comment]
Can you add a minimum reproducible example?
It is hard to track where the memory leak is happening without knowing the executed routines.

**Comment by mfoglio** [comment]
I know. I am sorry, but I cannot provide the code due to IP and I am not being able to reproduce it with a smaller example. You can close the issue. As of now I have a code that worked: I am calling 
```
                        cp.get_default_memory_pool().free_all_blocks()
                        cp.get_default_pinned_memory_pool().free_all_blocks()
```
when the memory usage exceeds a certain threshold. Also, I am calling it within a thread lock to avoid calling it twice at the same time from multiple threads (possibly that was the cause).
You can close the issue. I hope this comment could be of use to somebody else.

**Comment by kmaehashi** [comment]
Closing as inactive for a while. Please feel free to open another issue if you still have problem.
