### ISSUE TITLE
Improve interoperability docs

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#4869]
https://docs.cupy.dev/en/latest/reference/interoperability.html

* Add PyTorch section
    * Move an example code from DLPack section
    * Add a link to memory pool sharing feature in pytorch-pfn-extras: https://github.com/pfnet/pytorch-pfn-extras/blob/master/docs/cuda.md.
    * Add an example of `cupy.asarray` and `torch.as_tensor` as PyTorch 1.3+ supports `__cuda_array_inferface__`
* Describe that `__cuda_array_inferface__` does not take care of ownership, unlike DLPack.
* Add TensorFlow as an example in DLPack section.

**Comment by leofang** [comment]
I'd also like to mention RMM as a alternative choice of memory allocator (cc: @jakirkham @kkraus14).

**Comment by jakirkham** [comment]
cc @harrism @jrhemstad
