### ISSUE TITLE
 module 'cupy' has no attribute 'memoize'

### ISSUE THREAD

**Issue by aligoglos** [cupy/cupy#4872]
I've installed `cupy-cuda102 8.5.0 ` on python3.7 and windows 10 and want to run source code that use `@cupy.memoize(for_each_device=True)` but this error rise:

`AttributeError: module 'cupy' has no attribute 'memoize'`

**Comment by kmaehashi** [comment]
Could you try uninstalling all CuPy packages installed (check output from `pip list`), then reinstall `cupy-cuda102`?

**Comment by dillfrescott** [comment]
Having this issue as well

**Comment by yizhikan** [comment]
run the following command in CMD

**Comment by yizhikan** [comment]
run the following command in cmd

**Comment by yizhikan** [comment]
run the following commands in cmd
```
conda install -c conda-forge cudatoolkit=11.3
pip install cupy-cuda113
```
make sure there is not any version installed cupy before running commands

**Comment by TANG-CREATOR** [comment]
> run the following commands in cmd
> 
> ```
> conda install -c conda-forge cudatoolkit=11.3
> pip install cupy-cuda113
> ```
> 
> make sure there is not any version installed cupy before running commands

it`s helpful.thank you!
