### ISSUE TITLE
cupy._default_memory_pool.total_bytes() suddenly returns -1

### ISSUE THREAD

**Issue by oliversmith6500** [cupy/cupy#4881]
Hi,

Using cupy 9.0.0b3.

Here's my scenario:

- allocating a large (1 billion bytes) cp.array at the beginning of my program, then deallocating it immediately. As a result, total_bytes() = 1000000000, and used_bytes() = 0. I do this so that cupy CUDA-allocates memory once for all, and then reuses that allocated memory.
- I then allocate an NdImage, then use cupy's NdImage.zoom(), then deallocate. I'm back to total_bytes = 1000000000, and used_bytes = 0.
- for many iterations, this works as expected : total_bytes returns 100000000, used_bytes returns 0.

But then, all of a sudden, cupy decides to return total_bytes = -1 (and used_bytes = 0).

What does this mean, and is it worrying?

Thanks in advance.

Note: inbetween iterations I am doing some training with TensorFlow (2.3.2).

EDIT : using cupy 9.0.0b3 over CUDA 10.1. GTX 1080, Windows 10 64 bits, 461.72 WHQL drivers.

**Comment by kmaehashi** [comment]
Hi, thanks for reporting. It would be great if you could share the code to reproduce the issue.
`total_bytes` is defined to return `size_t` which is unsigned, so `-1` is strange.
https://github.com/cupy/cupy/blob/v9.0.0b3/cupy/cuda/memory.pyx#L1444

If you are building from source, also try again with the wheel release.

**Comment by fcunilim** [comment]
Thanks for your reply. It is very difficult to share the code, as the problem is buried deep in my code base.

I have slightly narrowed down the issue.

My main training loop is sometimes requesting more memory, so reallocation occurs. It does it twice. This is not a big issue in itself. I try to avoid this in general as TF does not always appreciate concurrent use of GPU memory.

The required memory size for the NdImages at some point reaches 1.13 then 1.29 billion bytes. So two reallocations are occurring upon calling IdImage.zoom(). The second time (only), immediately after the call to zoom(), total_bytes returns -1. I also know that immediately prior to the call, total_bytes is valid.

**Comment by oliversmith6500** [comment]
(using the right account). Thanks for your reply. It is very difficult to share the code, as the problem is buried deep in my code base.

I have slightly narrowed down the issue.

My main training loop is sometimes requesting more memory, so reallocation occurs. It does it twice. This is not a big issue in itself. I try to avoid this in general as TF does not always appreciate concurrent use of GPU memory.

The required memory size for the NdImages at some point reaches 1.13 then 1.29 billion bytes. So two reallocations are occurring upon calling IdImage.zoom(). The second time (only), immediately after the call to zoom(), total_bytes returns -1. I also know that immediately prior to the call, total_bytes is valid.

**Comment by oliversmith6500** [comment]
- allocate large cupy array
- dispose of it. Total/used bytes: 1000000000/0

begin:
- create numpy array < 1000000000 in size in most cases
- check that cupy Total/used bytes is indeed 1000000000/0
- create cupy version of this array using cp.array
- call NdImage.zoom (this allocates more GPU memory)
- dispose of this data
- check that cupy Total/used bytes is indeed 1000000000/0 (*)

- TF training
- goto "begin"

At some point, in here (*), reallocation occurs, reaching 1.13 billion bytes, so I get : Total/used : 1130000000/0.
Then another cycle occurs, with 1.29 billion bytes. After disposing the objects, I get -1/0.

Note the returned NdImage is always perfectly valid.

**Comment by kmaehashi** [comment]
Closing as inactive for a while and also unable to reproduce on our end. Please feel free to open another issue if you still encounter the problem.
