### ISSUE TITLE
use cupy in Anaconda

### ISSUE THREAD

**Issue by quoniammm** [cupy/cupy#489]
I install it by `pip install cupy`.
But I can not import cupy in notebook.
I use Anaconda python3.6 pytorch=0.2.0 and Ubuntu16.04.
The error info:
`No module named cupy`
What is the reason of it

**Comment by unnonouno** [comment]
Oh, really? Can you paste whole install log with full verbose mode?
```
$ pip uninstall cupy
$ pip install cupy --no-cache-dir -vvvv
```

**Comment by quoniammm** [comment]
Hi,thank you very much.The problem is solved After I run `nvidia-docker run -it cupy/cupy /bin/bash`.I don't why it can fix this problem.But It seems have some effects.

**Comment by unnonouno** [comment]
OK. Can I close this issue?

**Comment by quoniammm** [comment]
Yes,Of course.
