### ISSUE TITLE
Use CUB by default

### ISSUE THREAD

**Issue by emcastillo** [cupy/cupy#4897]
It feels a bit weird that since cub is bundled in cupy and performs quite fast in the majority of cases, it is not the default choice for at least routines such as sum or mission-critical ones.

Are there any issues that prevent us from using CUB by default, at least in routines?

I was discussing offline with @kmaehashi and maybe reproducibility of results with cub is not ensured, but I am not familiar with cub enough to assert on this. Maybe @leofang or @asi1024 can shed some light here.

Thanks!

**Comment by leofang** [comment]
I don't remember in which issue/PR we decided to not make it default, but IIRC the concern was not about CUB's reproducibility, but about users code might not be perfectly reproducible after they upgrade CuPy if CuPy update the default backend.

AFAIK, CUB claims deterministic outcomes, so I wouldn't worry about it.

**Comment by leofang** [comment]
But, be aware of https://github.com/cupy/cupy/issues/3822#issuecomment-782607637, and potential issues linked in #3723.

**Comment by emcastillo** [comment]
I think that we should select a series of routines where CUB is enabled by default.
Others could be left as experimental.

**Comment by leofang** [comment]
That's what I thought too. CUB reduction is definitely fine. I think it's probably safe to default everything except CUB SpMV.

**Comment by leofang** [comment]
> That's what I thought too. CUB reduction is definitely fine. 

btw if we default to this, we fix #2750 for free, as CUB reduction is not strided. Though it's not a big deal. 

> I think that we should select a series of routines where CUB is enabled by default.
> Others could be left as experimental.

We'll need to document whatever we decide (#3692).

**Comment by kmaehashi** [comment]
I think `atomicAdd` is used in CUB ops which does not have reproducibility.

**Comment by kmaehashi** [comment]
Discussed internally:

* We are using `atomicAdd` in several locations (not limited to CUB) and not guaranteeing reproducibility overall. Considering the merit (esp performance improvements in reduction) it is worth doing enabling CUB by default.
* However as this will change the behavior of many reduction operations, we should explicitly add documentation for users who needs reproducibility (i.e., `export CUPY_ACCELERATORS=""` to disable CUB)

**Comment by duncanriach** [comment]
> I think `atomicAdd` is used in CUB ops which does not have reproducibility.

I think it's worth highlighting that atomic operations do not in themselves introduce nondeterminism, and they can be used in ways that do not introduce nondeterminism. However, their presence can often be taken as a warning sign because they are often used in such a way as to convert truly asynchronous functionality into truly random floating-point rounding errors.
