### ISSUE TITLE
UnboundLocalError on cuda/memory.pyx

### ISSUE THREAD

**Issue by viantirreau** [cupy/cupy#4898]
Hi!

I'm having an error when using a GPU from SpaCy, but originated in a cupy module.
The relevant (and repeatable) traceback is as follows:
```
 File "spacy/ml/parser_model.pyx", line 327, in spacy.ml.parser_model.step_forward.backprop_parser_step
  File "spacy/ml/parser_model.pyx", line 277, in spacy.ml.parser_model.ParserStepModel.backprop_step
  File "/home/user/.cache/pypoetry/virtualenvs/notebooks-noypvBLr-py3.8/lib/python3.8/site-packages/spacy/util.py", line 958, in get_async
    array.set(numpy_array, stream=stream)
  File "cupy/core/core.pyx", line 1622, in cupy.core.core.ndarray.set
  File "cupy/core/core.pyx", line 1649, in cupy.core.core.ndarray.set
  File "cupy/core/core.pyx", line 1651, in cupy.core.core.ndarray.set
  File "cupy/cuda/memory.pyx", line 479, in cupy.cuda.memory.MemoryPointer.copy_from_host_async
UnboundLocalError: local variable 'ptr' referenced before assignment
``` 
I think the solution is pretty straightforward. In these lines
https://github.com/cupy/cupy/blob/2e95ed7e994b1db230501a69e8a323666164fb80/cupy/cuda/memory.pyx#L462-L480
the variable `ptr` is effectively undefined when the `stream` is not `None`.
I'm not very used to the library, but I think that just by swapping L473 with L474 so that `ptr` is defined regardless of the value of `stream`, it should get sorted out.

Let me know if I can help in any way :)

**Comment by leofang** [comment]
This doesn't make sense. `cupy.cuda.Stream` always has a `ptr` attribute. What  object did you pass to `stream` here? Could you show us a minimal reproducer?

**Comment by viantirreau** [comment]
Thanks for your fast response, @leofang 
I'll try to build a minimal example from SpaCy's code

**Comment by leofang** [comment]
Thanks, that would be great. On a second thought, it's not AttributeError, so it might not be related to stream. Let me take a look.

**Comment by leofang** [comment]
btw which version of CuPy are you using?

**Comment by leofang** [comment]
Sorry @viantirreau I spoke too fast. You are completely right. Exchanging L473 with L474 would do the job and was my intent in #4562. Thanks for spotting my oversight 😅 Would you like to send a PR?

**Comment by viantirreau** [comment]
Of course :)
I'll send it right away.
Just arrived home, I'm currently on v9.0.0b3

**Comment by leofang** [comment]
Thanks, @viantirreau!

**Comment by leofang** [comment]
> I'm currently on v9.0.0b3

And yes, I expect this bug to only appear in 9.0.0b2+. Thanks for confirming.
