### ISSUE TITLE
Added the implementation of method "alen"

### ISSUE THREAD

**Issue by ameyachawla99** [cupy/cupy#4936]
Hi , I am Ameya Chawla currently pursuing my B.Tech in Computer Science and Engineering .
I read about your organization in GSOC 2021 and looking forward to work with your organization .

Added the implementation of method "alen" in #4935 
Please can you review my implementation and suggest any change to be made
as mentioned in the comparison document
https://docs.cupy.dev/en/stable/reference/comparison.html

Please guide me why i am getting error Error: Process completed with exit code 1. 

Thank you

Ameya Chawla

**Comment by kmaehashi** [comment]
Closing as discussed in #4935.
