### ISSUE TITLE
GSOC 2021 Proposal

### ISSUE THREAD

**Issue by ameyachawla99** [cupy/cupy#4979]
Respected sir/madam

Hi , I am Ameya Chawla currently pursuing my B.Tech in Computer Science and Engineering .
I read about your organization in GSOC 2021 and looking forward to work with your organization .

I have also made a pull request "Implemented the Hyperbolic Sine Function for matrix #4944"

Please can you guide further how should start working .

Please can you share a sample template for the proposal to be made for Google Summer of Code Application..

Thank You

**Comment by emcastillo** [comment]
Please join gitter and lets discuss it there.

https://gitter.im/cupy/community
