### ISSUE TITLE
asarray Ignores the Current Stream

### ISSUE THREAD

**Issue by insertinterestingnamehere** [cupy/cupy#4988]
Right now, when copying from one GPU to another, cupy.asarray (and ndarray.copy) execute on the default stream even if some other stream is currently in use. This is because cudaMemcpy always runs on the default stream. This can cause synchronization issues if the next operation on the current stream executes on the copied data. This shows up in a larger app I'm helping with, but we haven't yet found a small example that shows the bad synchronization. I suspect that the fix is to change https://github.com/cupy/cupy/blob/23f0b72e6b9e8c8daf34548ac6649dd164da1c45/cupy/_core/core.pyx#L518 to use copy_from_device_async, but I'm not sure if there would be other undesirable consequences from that approach. Now that we've identified the problem, we can work around this by calling copy_from_device_async directly, but this is a major pitfall for multi-device users. What would be a sane way to fix this? A big thanks to @nicelhc13 for pinning down what was happening on our end.

**Comment by leofang** [comment]
I think we also need to fix #3980...

**Comment by emcastillo** [comment]
this seems to be the cause behind the flaky copy_to multigpu tests

**Comment by leofang** [comment]
I don't think #4673 is related to this. @takagi Could you run the stress tests (https://github.com/cupy/cupy/issues/4673#issuecomment-804335269, https://github.com/cupy/cupy/issues/4673#issuecomment-804350948) with your patch #5004?

**Comment by kmaehashi** [comment]
I asked @asi1024 to test @leofang's reproducer with this PR.

**Comment by emcastillo** [comment]
This was the reason behind #4673 
We confirmed it :D

**Comment by kmaehashi** [comment]
It should be fixed via #5004.
Thanks @insertinterestingnamehere for reporting!

**Comment by insertinterestingnamehere** [comment]
This is great! Thanks for your help!

**Comment by takagi** [comment]
I also checked the appearance of other `MemoryPointer` methods including `copy_{from,to}_*` and `memset`, and found any other part didn't have issues such that the current stream was ignored.
