### ISSUE TITLE
cupy.cuda.Device()._device_stack is not thread-local

### ISSUE THREAD

**Issue by insertinterestingnamehere** [cupy/cupy#5006]
We noticed mysterious device switching behavior in a multithreaded app we're developing and have traced it back to the device stack used to make cupy.cuda.Device a context manager not being thread local. The net effect of this is that a single cupy.cuda.Device object can't safely be used as a context manager in different threads. We can work around this downstream, but this seems like a potential pitfall in the multithreaded use case.

**Comment by insertinterestingnamehere** [comment]
I'm not sure I fully follow your point about matching the behavior of cudaSetDevice. Can you elaborate? The problem I'm seeing is that the context manager API built on top of cudaSetDevice breaks when multiple threads use the same Device object simultaneously.

More concretely, the issue we were seeing is something like this:
Thread A: enters device 1 from device 0
Thread B: enters device 1 from device 2
Thread A: exits to device 2 erroneously (popping the most recent entry from the non-thread-local stack)
Thread B: exits to device 1 erroneously

The expected behavior is:
Thread A: enters device 1 from device 0
Thread B: enters device 1 from device 2
Thread A: exits to device 0
Thread B: exits to device 2

I think the fix is to have thread-local copies of _device_stack associated with each Device object, not in the thread-local storage that's global to the module. I can try to throw together a PR if that'd help. I don't have a development environment set up for cupy at the moment though, so there may be some delay.

The alternative is to tell users to never use the same Device object in different threads simultaneously. That's doable, but at least in our case, we'll likely end up writing a similar thread-local storage idiom downstream to make the right thing happen.

**Comment by insertinterestingnamehere** [comment]
I think a workaround downstream is to refer to devices based off of their ids and initialize a new cupy.cuda.Device object every time we want to use the context manager and just store device ids. Neither this solution nor the thread-local storage one suggested above has any significant performance impact.

**Comment by kmaehashi** [comment]
Thanks for reporting @insertinterestingnamehere, I think it makes sense to keep the device ID history in TLS as the device ID is set per-thread in CUDA.
