### ISSUE TITLE
CuPy JIT: Undesired type promotion to int64

### ISSUE THREAD

**Issue by asi1024** [cupy/cupy#5018]
## Background

Typical case is as follows:

```py
import cupy
from cupyx import jit

@jit.rawkernel()
def func():
    jit.threadIdx.x + 1

func[1, 1]()
print(func.codes[0])
```

Following CUDA code is generated.

```cpp
extern "C" __global__ void func() {
  ((long long)(threadIdx.x) + 1ll);
}
```

## Typing rule

Currently, `cupyx.jit.rawkernel` supports 2 kinds of typing rules: `'cuda'` mode and `'numpy'` mode. The difference of the typing rule is only the default dtype of integer and floating type (`'cuda'`: `int32` and `float32`, `'numpy'`: `int64` and `float64`).
In both typing rules, the result dtype of operations follows the rule of cupy ufuncs. In the above example, `cupy.add` returns `int64` value for `int32` and `uint32` inputs.

Currently I think C++ casting rule might be better in `'cuda'` mode (It means `uint32` is desired for the return type of `int32` and `uint32` operation). Does someone have a concern or a better solution about it?

(cc: @kmaehashi @emcastillo @leofang)

**Comment by leofang** [comment]
Sounds good to me to default to the `'cuda'` mode!
