### ISSUE TITLE
Removing experimental flag for `cupyx.time.repeat`

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5031]
We originally named `cupyx.time.repeat` as it is similar to `timeit.repeat`, but later we noticed that the semantics is slightly different between them. The latter measures the time taken to run given code for *number* times and repeat that measurement for *repeat* times. This is one of the reason why we marked it as experimental.

However, it is important to provide a stable API for benchmarking / profiling. To remove experimental flag from the `cupyx.time.repeat`, we should consider a good name for it.

Besides that, it would be beneficial if we can provide a wall-clock timer function with CUDA synchronization that can be passed as `timer` argument of `timeit.repeat`.

**Comment by leofang** [comment]
> However, it is important to provide a stable API for benchmarking / profiling. To remove experimental flag from the `cupyx.time.repeat`, we should consider a good name for it.

Do you mean you wanna rename the API? If so there's #2896. Just FYI 🙂

**Comment by kmaehashi** [comment]
Ah, ok, totally overlooked that issue 😅
