### ISSUE TITLE
CuPy v10 Release Schedule

### ISSUE THREAD

**Issue by asi1024** [cupy/cupy#5049]
Here is the current plan for CuPy v10 development.

## Highlights in CuPy v10

- Enhanced Multi-GPU Support
  - `cupyx.distributed`
  - Peer access support
- #4789
  - [Python array API standard](https://data-apis.org/array-api/latest/)
  - ref: https://github.com/numpy/numpy/pull/18585
  - https://github.com/cupy/cupy/pull/5698
- More cuTENSOR support
  - Implement element-wise operation using cuTENSOR

## Timeline

- [x] **v10.0.0a1 (v9.1.0)** (2021-05-27)
- [x] **v10.0.0a2 (v9.2.0)** (2021-06-24)
- [x] **v10.0.0b1 (v9.3.0)** (2021-08-05)
- [x] **v10.0.0b2 (v9.4.0)** (2021-08-26)
- [x] **v10.0.0b3 (v9.5.0)** (2021-09-30)
- [x] **v10.0.0rc1 (v9.6.0)** (2021-11-11)
- [x] **v10.0.0** (2021-12-09)

Release Blocking Issues: https://github.com/cupy/cupy/labels/blocking

Notes:

* The schedule and listed features are tentative and may subject to change depending on the progress.
* The code will be frozen around 15:00 on 2 days before the release date for QA. Dates are in JST.
* `v9.x.x` releases will only contain backported pull-requests (mainly bug-fixes) from the v9 (master) branch.

## Past Release Schedules

* v9: https://github.com/cupy/cupy/issues/3891

**Comment by kmaehashi** [comment]
Due to scheduling reasons, v10.0.0b1 / v9.3.0 release date has been changed from 2021-07-29 to 2021-08-05.

**Comment by kmaehashi** [comment]
As there are several remaining issues and pull-requests that we would like to include in v10.0.0rc1 release, we are updating the release schedule as follows:

* v10.0.0rc1 (v9.6.0) (~2021-10-28~) -> (2021-11-11)
* v10.0.0 (~2021-11-25~) -> (2021-12-09)

**Comment by asi1024** [comment]
Released v10.0.0! https://github.com/cupy/cupy/releases/tag/v10.0.0
