### ISSUE TITLE
Timings with ROCm

### ISSUE THREAD

**Issue by benjha** [cupy/cupy#5056]
Hi CuPy team,

I am timing  some CuPy's math functions on MI100 GPU. From some of your examples  I noted you use some kind of device/stream synchronization just before calculating  the elapsed time of an operation. 

Is this approach also applies for ROCm ? 

As reference, this what I am doing

```
...
device = cp.cuda.Device()
...
def FFT (x):
    t0 = time.time()
    r = cp.cupy.fft.fft2(x)
    device.synchronize()
    t1 = time.time()
    dt = t1 - t0
    return dt
...
```

Thanks

**Comment by emcastillo** [comment]
Yes!, you can also check the `cupyx.time.repeat` function that does all for you and works in a similar fashion than `timeit`
https://github.com/cupy/cupy/blob/master/cupyx/time.py#L64-L113

**Comment by leofang** [comment]
It's documented here 🙂
https://docs.cupy.dev/en/latest/reference/generated/cupyx.time.repeat.html#cupyx.time.repeat

**Comment by benjha** [comment]
great, thank you @emcastillo and  @leofang
