### ISSUE TITLE
ModuleNotFoundError when running .exe generated by pyinstaller

### ISSUE THREAD

**Issue by 1155159410** [cupy/cupy#5090]
I am using Pyinstaller to build a single _.exe_ file for my code with the command `pyinstaller -F main.py`.

But once I run the _.exe_ file, I got the below error message:
````
Traceback (most recent call last):
  File "cupy\__init__.py", line 20, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "cupy\core\__init__.py", line 1, in <module>
  File "cupy\core\core.pyx", line 1, in init cupy.core.core
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "cupy\cuda\__init__.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "cupy\cuda\compiler.py", line 11, in <module>
  File "cupy\cuda\device.pyx", line 8, in init cupy.cuda.device
  File "cupy_backends\cuda\libs\cublas.pyx", line 1, in init cupy_backends.cuda.libs.cublas
ModuleNotFoundError: No module named 'cupy_backends.cuda.stream'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "cupy\__init__.py", line 41, in <module>
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the
 version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: No module named 'cupy_backends.cuda.stream'
[4108] Failed to execute script main
````

But when I run the code in PyCharm, it works well. Here are my conditions print with PyCharm with `cupy.show_config()`:
- OS                           : Windows-10-10.0.19041-SP0
- CuPy Version                 : 8.6.0
- NumPy Version                : 1.20.2
- SciPy Version                : None
- Cython Build Version         : 0.29.22
- CUDA Root                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
- CUDA Build Version           : 11020
- CUDA Driver Version          : 11030
- CUDA Runtime Version         : 11020
- cuBLAS Version               : 11401
- cuFFT Version                : 10401
- cuRAND Version               : 10203
- cuSOLVER Version             : (11, 1, 0)
- cuSPARSE Version             : 11401
- NVRTC Version                : (11, 2)
- Thrust Version               : 101000
- CUB Build Version            : 101000
- cuDNN Build Version          : None
- cuDNN Version                : None
- NCCL Build Version           : None
- NCCL Runtime Version         : None
- cuTENSOR Version             : None
- Device 0 Name                : NVIDIA GeForce RTX 3060 Ti
- Device 0 Compute Capability  : 86

In order to exclude other factors, I tried to compile a _.py_ file with only `import cupy as cp` inside it. But after I ran the _.exe_ generated by pyinstaller, the same error message above still generated.

Does anyone know how to solve this problem?
Thank you!

**Comment by kmaehashi** [comment]
To package Cython-based library (not limited to CuPy) using pyinstaller, you need to manually create a spec file and add all modules to [hidden imports](https://pyinstaller.readthedocs.io/en/stable/feature-notes.html#cython-support).  You may also want to package `package_data`s. https://github.com/cupy/cupy/blob/v9.0.0rc1/setup.py#L92-L105

See also #2140 and #1262.

**Comment by 1155159410** [comment]
Thanks for your quick responses!

I added `'cupy_backends.cuda.stream'` to _hiddenimports_ in the spec file, it does change. But I still got an error message that another module `'cupy.core._carray'` not found.

After that, I add all the modules and package I found from these links you provided me:
[https://github.com/cupy/cupy/blob/v9.0.0rc1/setup.py#L92-L105](url)
[https://github.com/cupy/cupy/issues/2140](url)
[https://github.com/cupy/cupy/issues/1262](url)

Then the _hiddenimports_ in my spec file looks like this now:
```
import glob

hiddenimports=[
             # found from https://github.com/cupy/cupy/blob/v9.0.0rc1/setup.py#L92-L105
             'cupy/cuda/cupy_thrust.cu',
             'cupy/cuda/cupy_cub.cu',
             'cupy/cuda/cupy_cufftXt.cu',
             'cupy/cuda/cupy_cufftXt.h',
             'cupy/cuda/cupy_cufft.h',
             'cupy/cuda/cufft.pxd',
             'cupy/cuda/cufft.pyx',
             'cupy/random/cupy_distributions.cu',
             'cupy/random/cupy_distributions.cuh',
             ] + [
             x for x in glob.glob('cupy/core/include/cupy/**', recursive=True)
             if os.path.isfile(x)
             ] + [
             # found from error message
             'cupy_backends.cuda.stream'
             'cupy.core._carray'
             ] + [
             # found from #2140 and #1262
             'fastrlock',
             'fastrlock.rlock',
             'cupy.core.flags',
             'cupy.core._routines_indexing',
             'cupy.core._dtype',
             'cupy.core._scalar',
             'cupy.core._ufuncs',
             'cupy.core._routines_sorting'
             ],
```

But still there is an error message showing certain module are missing, for instance `'cupy.core._cub_reduction'`. What should I include in the _hiddenimports_ in order to import the complete modules of CuPy, besides of adding one by one?

Since I am still not so familiar with Python, I am sorry if I asked a stupid question.

**Comment by 1155159410** [comment]
After days of trying, I finally solve the problem. Although I'm not sure if this is the best way, here below is part of my code in the pyinstaller's _.spec_ file, which can make cupy works in portable .exe:
```
hiddenimports=[
'cupy_backends.cuda.stream',
'fastrlock',
'fastrlock.rlock'
],
```
and
```
# the code below should place between the assignment of 'a' and 'exe'
a.datas += Tree('.\\venv\\Lib\\site-packages\\cupy\\core', '.\\cupy\\core', excludes=['_accelerator.cp38-win_amd64.pyd',
                                                                                      '_dtype.cp38-win_amd64.pyd',
                                                                                      '_fusion_thread_local.cp38-win_amd64.pyd',
                                                                                      '_kernel.cp38-win_amd64.pyd',
                                                                                      '_memory_range.cp38-win_amd64.pyd',
                                                                                      '_optimize_config.cp38-win_amd64.pyd',
                                                                                      '_reduction.cp38-win_amd64.pyd',
                                                                                      '_routines_binary.cp38-win_amd64.pyd',
                                                                                      '_routines_indexing.cp38-win_amd64.pyd',
                                                                                      '_routines_linalg.cp38-win_amd64.pyd',
                                                                                      '_routines_logic.cp38-win_amd64.pyd',
                                                                                      '_routines_manipulation.cp38-win_amd64.pyd',
                                                                                      '_routines_math.cp38-win_amd64.pyd',
                                                                                      '_routines_statistics.cp38-win_amd64.pyd',
                                                                                      '_scalar.cp38-win_amd64.pyd',
                                                                                      'core.cp38-win_amd64.pyd',
                                                                                      'dlpack.cp38-win_amd64.pyd',
                                                                                      'fusion.cp38-win_amd64.pyd',
                                                                                      'internal.cp38-win_amd64.pyd',
                                                                                      'raw.cp38-win_amd64.pyd'])
```

Hope this can help those who have the same problem as mine. :smile:
(I know it is a little dumb to exclude the duplicate files one by one. Thus, if there is a better way, please let me know!)
