### ISSUE TITLE
Stream stack does not take care of garbage-collected Stream (i.e. weakref is None)

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5143]
```py
import cupy as cp
from cupy import cuda

with cuda.Stream() as s1:
    s2 = cuda.Stream()
    s2.use()
    with cuda.Stream() as s3:
        del s2
```

This fails when exiting `s3` context:

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    del s2
  File "cupy/cuda/stream.pyx", line 197, in cupy.cuda.stream.BaseStream.__exit__
  File "cupy/cuda/stream.pyx", line 34, in cupy.cuda.stream._ThreadLocal.set_current_stream_ref
AttributeError: 'NoneType' object has no attribute 'ptr'
```

**Comment by emcastillo** [comment]
Related https://github.com/cupy/cupy/pull/4337

**Comment by leofang** [comment]
Since #4337 is closed and the focus is shifted to #5172, where I am refactoring the stream stack, it may be a good idea for me to fix this issue at the same time.

**Comment by leofang** [comment]
In this case, after leaving the `s3`'s context, since `s2` is deleted the current stream will fall back to `null`, but we are still in `s1` 's context. Is this expected behavior?

**Comment by leofang** [comment]
I think this line is problematic:
https://github.com/cupy/cupy/blob/97acfcdd7293ea5f06083b95d4d14947366542f3/cupy/cuda/stream.pyx#L34
It assumes the weakref is alive, which is incompatible with weakref. If this assumptions is needed (which I think is the case), we shouldn't use weakref at all.

I traced back to e9aaa3c from #306, which added the weakref usage, but the commit message made little sense to me...

**Comment by kmaehashi** [comment]
Yes, we need to rewind the stream stack until we find an alive one. If everything is dead we should fallback to the default stream.

**Comment by leofang** [comment]
> Yes, we need to rewind the stream stack until we find an alive one. If everything is dead we should fallback to the default stream.

Ah...OK so this is what you meant for #4337. Let me think about it. I feel it might be possible to just peek at the latest stream in the stack.

**Comment by leofang** [comment]
> > Yes, we need to rewind the stream stack until we find an alive one. If everything is dead we should fallback to the default stream.
> 
> Ah...OK so this is what you meant for #4337. Let me think about it. I feel it might be possible to just peek at the latest stream in the stack.

OK I don't think this is feasible, as it means when calling `stream.use()` we also need to push the current stream to the stack, which has no way to be popped correctly and is inconsistent with the current behavior.

**Comment by leofang** [comment]
> > Yes, we need to rewind the stream stack until we find an alive one. If everything is dead we should fallback to the default stream.
> 
> Ah...OK so this is what you meant for #4337. Let me think about it. I feel it might be possible to just peek at the latest stream in the stack.

I was being silly. To enable this we just need to push the current steam to the stack as well.
