### ISSUE TITLE
CSC matrix constructor bug

### ISSUE THREAD

**Issue by viclafargue** [cupy/cupy#5175]
There seems to be a bug in the CSC matrix constructor since CuPy 9.0 . The `data` attribute is different from the one produced by Scipy. On my machine, the bug seems to be triggered with a 2D matrix with the first dimension being >= 129. This works even when no zero is present. Also, I noticed that for unknown reason, the `nnz` value is printed.

Reproducer :
```
import scipy as sp
import cupy as cp

data = cp.random.rand(129, 1)
a = cp.sparse.csc_matrix(data)
b = sp.sparse.csc_matrix(data.get())
assert cp.allclose(a.data, b.data)
```

Error messages, stack traces :
```
# nnz: 129
Traceback (most recent call last):
  File "script.py", line 7, in <module>
    assert cp.allclose(a.data, b.data)
AssertionError
```

Environment :
```
  OS                           : Linux-5.8.0-50-generic-x86_64-with-glibc2.10
  CuPy Version                 : 9.0.0
  NumPy Version                : 1.20.2
  SciPy Version                : 1.6.0
  Cython Build Version         : 0.29.23
  Cython Runtime Version       : 0.29.23
  CUDA Root                    : /usr/local/cuda-11.2
  CUDA Build Version           : 11020
  CUDA Driver Version          : 11020
  CUDA Runtime Version         : 11020
  cuBLAS Version               : 11301
  cuFFT Version                : 10400
  cuRAND Version               : 10203
  cuSOLVER Version             : (11, 0, 2)
  cuSPARSE Version             : 11301
  NVRTC Version                : (11, 2)
  Thrust Version               : 101000
  CUB Build Version            : 101000
  Jitify Build Version         : <unknown>
  cuDNN Build Version          : None
  cuDNN Version                : None
  NCCL Build Version           : None
  NCCL Runtime Version         : None
  cuTENSOR Version             : None
  cuSPARSELt Build Version     : None
  Device 0 Name                : Quadro RTX 8000
  Device 0 Compute Capability  : 75
  Device 0 PCI Bus ID          : 0000:1A:00.0
  Device 1 Name                : Quadro RTX 8000
  Device 1 Compute Capability  : 75
  Device 1 PCI Bus ID          : 0000:68:00.0
```

**Comment by leofang** [comment]
@viclafargue A few issues:
1. `cp.allclose(a.data, b.data)` is not the correct way to compare two sparse matrices, as you also need to compare the matrix indices. In fact, in this example if you sort the `data` attribute first and then compare, the results agree.
2. The better way to make comparison is to do `cp.allclose(a.todense(), b.todense())`. In SciPy 1.5.x this would guarantee to be `True`. However, it fails with SciPy 1.6.0: I think this is a SciPy bug, because when I called `b.todense()` locally, it sorted the data array regardless of the indices. Could you please confirm this observation?
3. > I noticed that for unknown reason, the `nnz` value is printed.

This should not happen. Thanks for reporting it.

**Comment by leofang** [comment]
btw the `cupy.sparse` namespace is deprecated, and you should use `cupyx.scipy.sparse` instead. For some reason the warning was not printed (#5176).

**Comment by viclafargue** [comment]
Thanks @leofang. I thought there was a problem in the way the sparse matrix was encoded. After a closer look, it indeed looks like since version 9.0 it's just made differently from Scipy but still in a valid way. This was causing an issue in my code when trying to edit the sparse matrix from the `data` attribute as I expected a similar behavior to the one of Scipy. Since, the problem isn't to be found in CuPy's code I'll close this issue.

**Comment by leofang** [comment]
Normally CuPy would follow closely with NumPy/SciPy whenever possible. However, in this case it looks more like a SciPy bug to me, and I'd suggest you to open an issue upstream. I don't think we want to clone upstream bugs just to be 100% compatible 😅
