### ISSUE TITLE
Finished installing correctly, but can't use cudnn

### ISSUE THREAD

**Issue by dhgrs** [cupy/cupy#521]
CUDA: V8.0.61
cudnn: 6.0.21

I set PATH.
```
export CFLAGS=-I~/cuda/include
export LDFLAGS=-L~/cuda/lib64
export LD_LIBRARY_PATH=~/cuda/lib64:$LD_LIBRARY_PATH
```

And I installed cupy via pip.
`pip install cupy --no-cache-dir -vvvv > log`

Then, I tried using cudnn.
```
python
>>> import chainer
>>> chainer.cuda._resolution_error
ImportError('/home/user/anaconda3/lib/python3.6/site-packages/cupy/cuda/cudnn.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudnnSetFilterNdDescriptor_v3',)
```
It maybe failed to load cudnn library dynamically. So I tried [this issue](https://github.com/chainer/chainer/issues/1493) and add PATH.
`LD_LIBRARY_PATH=~/cuda/lib64:/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH`

But still I can't use cudnn. (I can use cupy without cudnn.)

This is install log.
https://gist.github.com/dhgrs/be5ec56b62576851757f52c96433d327

**Comment by unnonouno** [comment]
As you say, it looks dynamic loading problem. `cudnnSetFilterNdDescriptor_v3` is a symbol in `libcudnn.so`. And you need to set `LD_LIBRARY_PATH` correctly.
I think you installed `libcudnn.so` to `~/cuda/lib64`, right? Please check it and its version. All cudnn does not have binary compatibility. If your OS tries to link different version of cudnn, it fails.

I can find gcc can link to `libcudnn.so` here: https://gist.github.com/dhgrs/be5ec56b62576851757f52c96433d327#file-log-L285
So gcc successfully found `libcudnn.so`. Please check other directories also. I suspect that there are two different versions of cudnn, and gcc uses one and OS tries to load another one.

**Comment by dhgrs** [comment]
Yes, I installed cudnn to `~/cuda/` .

And cudnn is installed to /usr/local/cuda-8.0/ for other user. In that directory, there are two versions of cudnn(5.0.5 and 6.0.21).
I think use cudnn in `/usr/local/cuda-8.0/` . So I set PATH.
```
export CFLAGS=-I~/cuda/include
export LDFLAGS=-L~/cuda/lib64
export LD_LIBRARY_PATH=~/cuda/lib64:$LD_LIBRARY_PATH
```

But in the log, directories are set to `/usr/local/cuda-8.0/` .
https://gist.github.com/dhgrs/be5ec56b62576851757f52c96433d327#file-log-L39

I check libcudnn.so is realy in `~/cuda/lib64` .
```
$ echo $CFLAGS
-I~/cuda/include

$ echo $LDFLAGS
-L~/cuda/lib64

$ echo $LD_LIBRARY_PATH
/home/user/cuda/lib64:/usr/local/DL-Box/torch7/install/lib:/opt/OpenBLAS/lib:/usr/local/lib:/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/extras/CUPTI/lib64:/usr/local/DL-Box/digits-4.0/caffe/distribute/lib:

$ ls ~/cuda/lib64
libcudnn.so  libcudnn.so.6  libcudnn.so.6.0.21  libcudnn_static.a

$ ls ~/cuda/include
cudnn.h
```

As a trial, I removed `/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/extras/CUPTI/lib64:` from `LD_LIBRARY_PATH` . But the result didn't change.

FYI: 
```
$ which nvcc
/usr/local/cuda-8.0/bin/nvcc
```

**Comment by unnonouno** [comment]
Hum... it is difficult.
I checked the symbol `cudnnSetFilterNdDescriptor_v3` and it exists in cudnn v5, but does not in v6. It suggests your compiler and linker used v5. 

In this line, the linker searched the library from `-L/home/user/anaconda3/lib`, `-L~/cuda/lib64` and `-L/usr/local/cuda-8.0/lib64` in this order, and successfully found the libcudnn.
https://gist.github.com/dhgrs/be5ec56b62576851757f52c96433d327#file-log-L285
Can you check `/home/user/anaconda3/lib`?

**Comment by dhgrs** [comment]
I checked `/home/user/anaconda3/lib` as below.
```
$ find /home/user/anaconda3/lib/*cudnn*
```
But I couldn't find libcudnn.

**Comment by dhgrs** [comment]
The problem was solved!

I reset PATH.
```
export CFLAGS=-I/home/user/cuda/include
export LDFLAGS=-L/home/user/cuda/lib64
export LD_LIBRARY_PATH=/home/user/cuda/lib64:$LD_LIBRARY_PATH
```

`make` can't understand `~` as home directory. So linker didn't search `/home/user/cuda/lib64` and did search `/usr/local/cuda-8.0/lib64` .

**Comment by unnonouno** [comment]
Oh, I understand... I'll add a notice about it in the document.
