### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by research-boy** [cupy/cupy#5211]
OS                           : Linux-5.4.0-73-generic-x86_64-with-Ubuntu-18.04-bionic
CuPy Version                 : 9.0.0
NumPy Version                : 1.19.5
SciPy Version                : 1.5.4
Cython Build Version         : 0.29.23
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda-11.3
CUDA Build Version           : 11030
CUDA Driver Version          : 11030
CUDA Runtime Version         : 11030
cuBLAS Version               : 11402
cuFFT Version                : 10402
cuRAND Version               : 10204
cuSOLVER Version             : (11, 1, 1)
cuSPARSE Version             : 11500
NVRTC Version                : (11, 3)
Thrust Version               : 101100
CUB Build Version            : 101100
Jitify Build Version         : <unknown>
cuDNN Build Version          : 8200
cuDNN Version                : 8200
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA Quadro RTX 6000
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0
* Error messages, stack traces, or logs:
original error: /python3.6/site-packages/cupy_backends/cuda/api/runtime.cpython-36m-x86_64-linux-gnu.so: symbol cudaMemPoolTrimTo version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference

**Comment by research-boy** [comment]
TRIED WITH CUDA 11.2 also
OS                           : Linux-5.4.0-73-generic-x86_64-with-Ubuntu-18.04-bionic
CuPy Version                 : 9.0.0
NumPy Version                : 1.19.5
SciPy Version                : None
Cython Build Version         : 0.29.22
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda-11.2
CUDA Build Version           : 11020
CUDA Driver Version          : 11030
CUDA Runtime Version         : 11030
cuBLAS Version               : 11402
cuFFT Version                : 10402
cuRAND Version               : 10204
cuSOLVER Version             : (11, 1, 1)
cuSPARSE Version             : 11500
NVRTC Version                : (11, 3)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 60e9e72
cuDNN Build Version          : 8101
cuDNN Version                : 8200
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA Quadro RTX 6000
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0

Error messages, stack traces, or logs:

Traceback (most recent call last):
  File "/home/usr/.local/lib/python3.6/site-packages/cupy/__init__.py", line 16, in <module>
    from cupy import _core  # NOQA
  File "/home/usr/.local/lib/python3.6/site-packages/cupy/_core/__init__.py", line 1, in <module>
    from cupy._core import core  # NOQA
  File "cupy/_core/core.pyx", line 1, in init cupy._core.core
  File "/home/usr/.local/lib/python3.6/site-packages/cupy/cuda/__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/home/usr/.local/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 11, in <module>
    from cupy.cuda import device
  File "cupy/cuda/device.pyx", line 1, in init cupy.cuda.device
ImportError: /home/usr/.local/lib/python3.6/site-packages/cupy_backends/cuda/api/runtime.cpython-36m-x86_64-linux-gnu.so: symbol cudaFreeAsync version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference

**Comment by kmaehashi** [comment]
I think you have multiple CUDA versions installed. Please try setting `export LD_LIBRARY_PATH=/usr/local/cuda-11.3/lib64`.
https://docs.cupy.dev/en/stable/install.html#working-with-custom-cuda-installation

**Comment by research-boy** [comment]
@kmaehashi  initially i had 11.3 thought it was issue due to that , so i installed 11.2 now and tried ,gives the error.
Anyway i tried the option you suggested which didn't work either.

**Comment by kmaehashi** [comment]
Could you share the output of `LD_DEBUG=libs python -c 'import cupy' 2>&1 | grep libcudart` command?

**Comment by research-boy** [comment]
@kmaehashi 
     18281:	find library=libcudart.so.11.0 [0]; searching
     18281:	  trying file=/usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0
     18281:	calling init: /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0
     18281:	calling fini: /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0 [0]

**Comment by kmaehashi** [comment]
Could you try again after setting `export LD_LIBRARY_PATH=/usr/local/cuda-11.3/lib64`?

**Comment by research-boy** [comment]
@kmaehashi Thanks for the support , it didn't solve the issue .
Solved by setting :
export CUDA_PATH=/usr/local/cuda
export LD_LIBRARY_PATH=$CUDA_PATH/lib64:$LD_LIBRARY_PATH

**Comment by cod3licious** [comment]
I'm having the same issue, i.e. I'm getting the error
```
original error: /home/franzi/anaconda3/lib/python3.8/site-packages/cupy_backends/cuda/api/runtime.cpython-38-x86_64-linux-gnu.so: symbol cudaDeviceSetMemPool version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference
```
with a CUDA version 11.3. I've tried all sorts of combinations for the CUDA_PATH and LD_LIBRARY_PATH but they all result in the same problem, even when I uninstall and reinstall cupy (with pip, directly the version for cuda113).

**Comment by research-boy** [comment]
@cod3licious How did you install cuda ?  is the file actually present in that path ?

**Comment by cod3licious** [comment]
@research-boy I installed CUDA according to the nvidia instructions and in /usr/local I have a cuda-11.3 folder with bin and lib64 and then symlinks for cuda and cuda-11, which point to /etc/alternatives/cuda[-11]. PyTorch also has no problem using the GPU, so cuda itself should not be the problem...

**Comment by kmaehashi** [comment]
@cod3licious Please confirm that `cudatoolkit` package installed in your conda environment matches with the CUDA version installed in your host (i.e. CUDA 11.3).

**Comment by cod3licious** [comment]
thanks @kmaehashi this seems to have been it (although I needed to do a complete reinstall of anaconda and everything since it wouldn't let me update cudatoolkit to the required version due to some supposed conflicts... 🙄)

**Comment by vkorotkine** [comment]
In case anyone else has this problem, it can also be caused by a mismatched torch installation. 
I had torch for CUDA=11.1, even though my CUDA=11.3 and CuPy was for the corresponding version. Torch by itself worked, but CuPy threw this exact error. 
Installing correct torch version fixed it.
