### ISSUE TITLE
cupy.cuda.set_allocator() sets allocator to non-memory pool allocator although the default allocator is memory pool allocator now

### ISSUE THREAD

**Issue by sonots** [cupy/cupy#524]
follow-up: https://github.com/cupy/cupy/pull/472

The default memory allocator is changed to be memory pool allocator at https://github.com/cupy/cupy/pull/472.

So, `cupy.cuda.set_allocator()` looks like it changes the allocator to be default, which is the memory pool allocator now. However, it actually changes the allocator to non-memory pool allocator as before. The interface is not intuitive.

**Comment by kmaehashi** [comment]
Fixed via #885.
