### ISSUE TITLE
NVRTCError: NVRTC_ERROR_COMPILATION with `cupy.cuda.compile_with_cache`

### ISSUE THREAD

**Issue by tommy19970714** [cupy/cupy#5294]
## 🐛 Bug

I got the following error when I compile the model with `cupy.cuda.compile_with_cache` to jit.

```
NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

CompileException                          Traceback (most recent call last)

cupy/util.pyx in cupy.util.memoize.decorator.ret()

/usr/local/lib/python3.7/dist-packages/cupy/cuda/compiler.py in compile(self, options)
    440         except nvrtc.NVRTCError:
    441             log = nvrtc.getProgramLog(self.ptr)
--> 442             raise CompileException(log, self.src, self.name, options, 'nvrtc')
    443 
    444 

CompileException: /tmp/tmpan1ut480/3b7c153ce98d06488f1cbac8793f6dff_2.cubin.cu(16): error: identifier "tensor" is undefined

1 error detected in the compilation of "/tmp/tmpan1ut480/3b7c153ce98d06488f1cbac8793f6dff_2.cubin.cu".
```

## To Reproduce

This is a colab to reproduce the error.
https://colab.research.google.com/drive/1WDRCN6wPIAsl5tBFKfne0ABN49estM9P?usp=sharing

This is a minimum code.

```
@cupy.util.memoize(for_each_device=True)
def cupy_launch(strFunction, strKernel):
	return cupy.cuda.compile_with_cache(strKernel).get_function(strFunction)

kernel_Correlation_rearrange = " .... "

import torch
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()

    def forward(self, x_warp_after, x_cond):
        cupy_launch('kernel_Correlation_rearrange', cupy_kernel('kernel_Correlation_rearrange', {
          'intStride': 1,
          'input': x_warp_after,
          'output': x_cond
        }))(
        )
        return x_warp_after, x_cond

net = Net().cuda()
input1 = torch.randn([1, 256, 8, 6]).cuda()
input2 = torch.randn([1, 256, 8, 6]).cuda()
trace_model = torch.jit.trace(net, [input1, input2])
```

## Expected behavior

I think the above error occurs when I use cupy.cuda.compile_with_cache.

## Environment

 - CuPy version: cupy-cuda101==7.4.0
 - CUDA/cuDNN version: 11.0.221
 - PyTorch Version (e.g., 1.0): 1.8.1+cu101
 - OS (e.g., Linux): Ubuntu 18.04.5 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): no
 - Python version: 3.7 (64-bit runtime)
 - GPU models and configuration: GPU 0: Tesla T4
 - Any other relevant information:

## Additional context

I opened an [issue](https://github.com/pytorch/pytorch/issues/58529) in the pytorch repository before, but I realized that the problem is not a pytorch issue, but a cupy issue.

**Comment by leofang** [comment]
This is neither PyTorch's nor CuPy's bug, but rather an issue in the way you did string processing to generate your kernel. Notice this error:
```
CompileException: /tmp/tmpan1ut480/3b7c153ce98d06488f1cbac8793f6dff_2.cubin.cu(16): error: identifier "tensor" is undefined
```
It is a normal C/C++ error telling your the definition for an identifier `tensor` is missing. You should check how that identifier entered the code string. [CuPy provides some env variables](https://docs.cupy.dev/en/stable/reference/environment.html), and the one you need to help you debug the code generation is either `CUPY_CACHE_SAVE_CUDA_SOURCE` or `CUPY_DUMP_CUDA_SOURCE_ON_ERROR`. 

By the way, it is best to not use `cupy.cuda.compile_with_cache()` because it is subject to change without notification (it's considered internal API AFAIK). There is a public API [`cupy.RawModule`](https://docs.cupy.dev/en/stable/reference/generated/cupy.RawModule.html) for exactly this need (see [tutorial](https://docs.cupy.dev/en/stable/user_guide/kernel.html#raw-modules)).

**Comment by kmaehashi** [comment]
As Leo suggested please check your CUDA code. I got the same report before: https://github.com/cupy/cupy/issues/3987

xref: https://discuss.pytorch.org/t/how-to-jit-compile-with-cupy-cuda-compile-with-cache/121700

**Comment by tommy19970714** [comment]
@leofang  @kmaehashi  Thank you for your response!

I tried using environment variables for debugging.
I debugged the next colab using the environment variable.
https://colab.research.google.com/drive/1WDRCN6wPIAsl5tBFKfne0ABN49estM9P?usp=sharing
But the error was the same as before and I could not judge which part of the code was bad.

Also, as I got feedback, I tried replacing `cupy.cuda.compile_with_cache()` with `cupy.RawModule` and running it, but the ERROR was the same. You can check the replaced code from the colab above.

As @leofang told me, I think it is a c/c++ error, but since c/c++ does not use tensor, it is difficult to find the cause.
Can you see what the problem is in the c/c++ code.

P.S.
I checked the issue that A shared with me.
[The pytorch forum](https://discuss.pytorch.org/t/how-to-jit-compile-with-cupy-cuda-compile-with-cache/121700) is the one I posted.
Issue #3987 is very similar to this issue. The issue is closed, but there is no solusion.

**Comment by kmaehashi** [comment]
As shown in the output, this is the code you are passing to `cupy.RawModule`:

```cpp
Name: /tmp/tmpfl9rgemg/2580de419f706496d2e0e83122e0c456_2.cubin.cu
Options: -I/usr/local/lib/python3.7/dist-packages/cupy/core/include -I /usr/local/lib/python3.7/dist-packages/cupy/core/include/cupy/_cuda/cuda-10.1 -I /usr/local/cuda/include -ftz=true -arch=compute_37
CUDA source:
01 
02 	extern "C" __global__ void kernel_Correlation_rearrange(
03 		const int n,
04 		const float* input,
05 		float* output
06 	) {
07 	  int intIndex = (blockIdx.x * blockDim.x) + threadIdx.x;
08 
09 	  if (intIndex >= n) {
10 	    return;
11 	  }
12 
13 	  int intSample = blockIdx.z;
14 	  int intChannel = blockIdx.y;
15 
16 	  float fltValue = input[(((intSample * tensor(256)) + intChannel) * tensor(8) * tensor(6)) + intIndex];
17 
18 	  __syncthreads();
19 
20 	  int intPaddedY = (intIndex / tensor(6)) + 3*1;
21 	  int intPaddedX = (intIndex % tensor(6)) + 3*1;
22 	  int intRearrange = ((tensor(6) + 6*1) * intPaddedY) + intPaddedX;
23 
24 	  output[(((intSample * tensor(256) * tensor(8)) + intRearrange) * tensor(256)) + intChannel] = 100;
25 	}
26 
```

Line 16 contains an undefined variable `tensor`.

**Comment by tommy19970714** [comment]
@kmaehashi  Thank you for letting me know.
The tensor is not used in the original c++ code, but it seems to be converted by cupy.
The original code:

```
kernel_Correlation_rearrange = '''
	extern "C" __global__ void kernel_Correlation_rearrange(
		const int n,
		const float* input,
		float* output
	) {
	  int intIndex = (blockIdx.x * blockDim.x) + threadIdx.x;

	  if (intIndex >= n) {
	    return;
	  }

	  int intSample = blockIdx.z;
	  int intChannel = blockIdx.y;

	  float fltValue = input[(((intSample * SIZE_1(input)) + intChannel) * SIZE_2(input) * SIZE_3(input)) + intIndex];

	  __syncthreads();

	  int intPaddedY = (intIndex / SIZE_3(input)) + 3*{{intStride}};
	  int intPaddedX = (intIndex % SIZE_3(input)) + 3*{{intStride}};
	  int intRearrange = ((SIZE_3(input) + 6*{{intStride}}) * intPaddedY) + intPaddedX;

	  output[(((intSample * SIZE_1(output) * SIZE_2(output)) + intRearrange) * SIZE_1(input)) + intChannel] = 100;
	}
'''
```

Do you have any idea how I can prevent it from being converted by cupy?

**Comment by kmaehashi** [comment]
Please report this issue to the repository

**Comment by kmaehashi** [comment]
> but it seems to be converted by cupy.

No, it is done by your code.

```py
def cupy_kernel(strFunction, objVariables):
	strKernel = globals()[strFunction].replace('{{intStride}}', str(objVariables['intStride']))

	while True:
		objMatch = re.search('(SIZE_)([0-4])(\()([^\)]*)(\))', strKernel)
...
```

Please report this issue to the repository that provides the code.

**Comment by tommy19970714** [comment]
Thanks to @kmaehashi  advice, this problem has been solved.

The problem is that when converting to jit, the int type becomes a tensor type.
I solved the problem by rewriting the following code section.

```
def cupy_kernel(strFunction, objVariables):
	strKernel = globals()[strFunction].replace('{{intStride}}', str(objVariables['intStride']))

	while True:
		objMatch = re.search('(SIZE_)([0-4])(\()([^\)]*)(\))', strKernel)

		if objMatch is None:
			break
		# end

		intArg = int(objMatch.group(2))

		strTensor = objMatch.group(4)
		intSizes = objVariables[strTensor].size()
                
                #####
                # HERE: I was changed following lines.
		replaceStr = str(intSizes[intArg]).replace("tensor", "int")
		strKernel = strKernel.replace(objMatch.group(), replaceStr)
                # HERE
                #####
	# end

	while True:
		objMatch = re.search('(VALUE_)([0-4])(\()([^\)]+)(\))', strKernel)

		if objMatch is None:
			break
		# end

		intArgs = int(objMatch.group(2))
		strArgs = objMatch.group(4).split(',')

		strTensor = strArgs[0]
		intStrides = objVariables[strTensor].stride()
		strIndex = [ '((' + strArgs[intArg + 1].replace('{', '(').replace('}', ')').strip() + ')*' + str(intStrides[intArg]) + ')' for intArg in range(intArgs) ]

		strKernel = strKernel.replace(objMatch.group(0), strTensor + '[' + str.join('+', strIndex) + ']')
	# end

	return strKernel
```
