### ISSUE TITLE
symbol cusparseDenseToSparse_convert version libcusparse.so.11 not defined in file libcusparse.so.11 with link time reference

### ISSUE THREAD

**Issue by HaoDreamlong** [cupy/cupy#5313]
My env is cuda11.1 and installed cupy-cuda111,but when I import cupy and errors come after:

Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cupy
Traceback (most recent call last):
  File "/home/ps/tmp_env/test_venv/lib/python3.6/site-packages/cupy/__init__.py", line 16, in <module>
    from cupy import _core  # NOQA
  File "/home/ps/tmp_env/test_venv/lib/python3.6/site-packages/cupy/_core/__init__.py", line 1, in <module>
    from cupy._core import core  # NOQA
  File "cupy/_core/core.pyx", line 1, in init cupy._core.core
  File "/home/ps/tmp_env/test_venv/lib/python3.6/site-packages/cupy/cuda/__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/home/ps/tmp_env/test_venv/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 11, in <module>
    from cupy.cuda import device
  File "cupy/cuda/device.pyx", line 10, in init cupy.cuda.device
ImportError: /home/ps/tmp_env/test_venv/lib/python3.6/site-packages/cupy_backends/cuda/libs/cusparse.cpython-36m-x86_64-linux-gnu.so: symbol cusparseDenseToSparse_convert version libcusparse.so.11 not defined in file libcusparse.so.11 with link time reference

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ps/tmp_env/test_venv/lib/python3.6/site-packages/cupy/__init__.py", line 37, in <module>
    raise ImportError(_msg) from e
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: /home/ps/tmp_env/test_venv/lib/python3.6/site-packages/cupy_backends/cuda/libs/cusparse.cpython-36m-x86_64-linux-gnu.so: symbol cusparseDenseToSparse_convert version libcusparse.so.11 not defined in file libcusparse.so.11 with link time reference

**Comment by HaoDreamlong** [comment]
I change my cupy-cu111 to 8.6.0, no porblem at all!

**Comment by kmaehashi** [comment]
Hi @HaoDreamlong, thanks for reporting this. We noticed that CuPy wheels currently require CUDA 11.1.1, although it should be CUDA 11.1.0.
We'll work on it for the next release, but if you can upgrade your installation to CUDA 11.1.1 the problem should disappear.

**Comment by kmaehashi** [comment]
Should be fixed via https://github.com/cupy/cupy-release-tools/pull/132

**Comment by kmaehashi** [comment]
During preparation for the release, we found that the above PR was not enough to fix this problem. We will work on fixing this towards the next release (#5401).

**Comment by kmaehashi** [comment]
I confirmed that the wheel for the upcoming release can be imported with both CUDA 11.1.0 and 11.1.1. Thanks again @ HaoDreamlong for reporting!
