### ISSUE TITLE
cupy.nanmedian bug report 

### ISSUE THREAD

**Issue by TakuNishiumi** [cupy/cupy#5315]
I may found a cupy.nanmedian bug.
Numpy result and Cupy result are different.
Could you check below codes?

Numpy:
```
import cupy as cp
import numpy as np
xp = np
x,y = xp.meshgrid(xp.arange(0, 6),xp.arange(0, 6)) 
R = xp.sqrt((x-3)**2 + (y-3)**2)
a = R>2
a = a * R
a[a==0]=xp.nan
b = xp.tile(a,(6,6,1,1))
c = xp.nanmedian(b,axis=[2,3]).shape
print(c) # returns (6, 6)
```

Cupy:
```
import cupy as cp
import numpy as np
xp = cp
x,y = xp.meshgrid(xp.arange(0, 6),xp.arange(0, 6)) 
R = xp.sqrt((x-3)**2 + (y-3)**2)
a = R>2
a = a * R
a[a==0]=xp.nan
b = xp.tile(a,(6,6,1,1))
c = xp.nanmedian(b,axis=[2,3]).shape
print(c) # returns (6, 6, 6, 6)
```

Environment:
OS                           : Linux-4.15.0-143-generic-x86_64-with-debian-buster-sid
Python Version               : 3.7.9
CuPy Version                 : 9.1.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.20.3
SciPy Version                : 1.6.3
Cython Build Version         : 0.29.23
Cython Runtime Version       : None
CUDA Root                    : /home/nishiumi/anaconda3/envs/py37
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 11020
CUDA Runtime Version         : 11020
cuBLAS Version               : 11401
cuFFT Version                : 10401
cuRAND Version               : 10203
cuSOLVER Version             : (11, 1, 0)
cuSPARSE Version             : 11401
NVRTC Version                : (11, 2)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : <unknown>
cuDNN Build Version          : 8100
cuDNN Version                : 8001
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : TITAN RTX
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:1A:00.0
Device 1 Name                : TITAN RTX
Device 1 Compute Capability  : 75
Device 1 PCI Bus ID          : 0000:68:00.0

**Comment by kmaehashi** [comment]
Thanks for reporting! This is indeed a bug. It seems that we haven't followed the spec added in NumPy 1.9.0:

https://numpy.org/doc/stable/reference/generated/numpy.nanmedian.html

> A sequence of axes is supported since version 1.9.0.

I think the same thing can be said for `numpy.median` too.

**Comment by TakuNishiumi** [comment]
Inaddition to it,  `cupy.nanmean`, `cupy.median`and `cupy.mean` has probably same problem because of the same reason.

**Comment by takagi** [comment]
Looks that a sequence of axes is inappropriately assumed to be a tuple.
https://github.com/cupy/cupy/blob/a0790a47cbd8956c210469b398f3e1a1b1b4ebb2/cupy/_core/_routines_statistics.pyx#L446

**Comment by takagi** [comment]
As for `cupy.nanmean`, `cupy.median` and `cupy.mean`, it seems that a sequence of axes works and the document does not properly describe `axis` parameter.
