### ISSUE TITLE
Cosmetic bug: unnecessary print statement

### ISSUE THREAD

**Issue by mouryarahul** [cupy/cupy#5373]
There is an unwanted print statement in [denseToSparse](https://github.com/cupy/cupy/blob/51210b3daef66e5d2be1ebaa3a42ddc95c662146/cupy/cusparse.py#L1667), which keeps printing # nnz.
Please suppress it.

Thanks,
Rahul

**Comment by kmaehashi** [comment]
Thanks for reporting! Will be fixed in #5374.
