### ISSUE TITLE
Support peer access

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5379]
```py
import cupy as cp


with cp.cuda.Device(0):
    d0 = cp.arange(10)
with cp.cuda.Device(1):
    # Enable dereferencing pointer of device 0 in the current device.
    # otherwise you will get `cudaErrorIllegalAddress: an illegal memory access was encountered`
    cp.cuda.runtime.deviceEnablePeerAccess(0)
    d1 = d0 * 2

print(d1)
```

Currently, this code fails with the error `Array device must be same as the current device: array device = 0 while current = 1`, but it should work. Maybe changing the error to the warning?

ref: https://stackoverflow.com/questions/68074985/read-write-a-cupy-array-on-multiple-gpus

Note: `deviceEnablePeerAccess` may not work with all combinations of GPUs.

**Comment by kmaehashi** [comment]
Another idea would be to enable peer access automatically as we do when doing D2D memcpy.
https://github.com/cupy/cupy/blob/v10.0.0a1/cupy/cuda/memory.pyx#L604-L624

**Comment by kmaehashi** [comment]
There is a limit of 8 peers per each GPU For NVLink/PCI-E configuration, but I think that limitation is negilible in most use cases, so I think it's ok to automatically enable peer access.

**Comment by MarwanAbdelatti** [comment]
@kmaehashi 
Thanks so much for taking care of this. As far as I know, most multi-GPU machines (more than 4 GPUs) don't support direct peer access between ALL GPUs. For example, the DGX machine with 8 GPUs support peer access between GPUs as per the following table:

ID: 0  | 1 | 2 | 3 | 4  | 5 | 6  | 7
  0: N | Y | Y | Y | Y | N | N | N
  1: Y | N | Y | Y | N | Y | N | N
  2: Y | Y | N | Y | N | N | Y | N
  3: Y | Y | Y | N | N | N | N | Y
  4: Y | N | N | N | N | Y | Y | Y
  5: N | Y | N | N | Y | N | Y | Y
  6: N | N | Y | N | Y | Y | N | Y
  7: N | N | N | Y | Y | Y | Y | N

So, if not implemented, I think enabling automatic peer access requires a try....except.

**Comment by kmaehashi** [comment]
@MarwanAbdelatti Thanks for sharing the configuration in DGX! I'm thinking of:
* Check if peer access is available between two devices using `cudaDeviceCanAccessPeer`
* Enabling it only when peer access is necessary

**Comment by MarwanAbdelatti** [comment]
@kmaehashi 
Can I use this feature now?

**Comment by kmaehashi** [comment]
@MarwanAbdelatti I'm trying to get this into the next v10 release. The PR is not checked into master branch yet, but you can try my branch: youhttps://github.com/cupy/cupy/pull/5496

**Comment by MarwanAbdelatti** [comment]
Hello @kmaehashi,
I installed your branch as you suggested but I got a segmentation fault. Please find the following output for the below code:

```python
 import cupy as cp
  
 with cp.cuda.Device(0):
     x     = cp.zeros((4, 4), dtype=cp.int32)
     #x_ptr = x.data.ptr     # CuPy array pointer
     #print(x_ptr)
 
 with cp.cuda.Device(1):
     print(x)               # prints the array with no error
     x[0, 0] = 99           # set array value from another device
```

```bash
projects/GA_VRP_mGPU/mgpu_test.py:10: PerformanceWarning: The device where the array resides (0) is different from the current device (1). Peer access has been activated automatically.
  x[0, 0] = 99           # set array value from another device
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
srun: error: dgx1: task 0: Segmentation fault
```
