### ISSUE TITLE
`cupy.get_array_module`

### ISSUE THREAD

**Issue by delta2323** [cupy/cupy#54]
Does CuPy have a function equivalent to `chainer.cuda.get_array_module` ? I think it should be in CuPy because some users want to write CPU/GPU agnostic code with CuPy only.

**Comment by niboshi** [comment]
Yes, it has: https://github.com/cupy/cupy/blob/master/cupy/__init__.py#L449

**Comment by delta2323** [comment]
Thank you. I missed it.
