### ISSUE TITLE
cupy v2 build error on MacOSX10.12.6 w/ CUDA 9.0.197

### ISSUE THREAD

**Issue by ryohajika** [cupy/cupy#540]
I'm new to cupy and trying to install cupy v2 to my environment.
However I get some errors when I try to build cupy with the current GitHub repo.
Error log file is here: https://gist.github.com/Hzikajr/1eaf813f8c4db9a763a0ffd17cd359b1

It seems that the errors came up from the `nccl.h` or the thrust library....
I tried cupy building with:
MacOSX10.12.6, toolchains with Xcode8.3.3, CUDA 9.0.197, Chainer 3.0.0rc1, Anaconda3-4.4.0, Python 3.6.2 :: Anaconda custom (x86_64)

I would appreciate for your suggestion or solution!

**Comment by unnonouno** [comment]
It is caused by thrust. When NCCL is not found, the setup script ignore it.
We will try to fix the problem, but I recommend you to use Linux. https://docs-cupy.chainer.org/en/stable/install.html#recommended-environments
