### ISSUE TITLE
Function availability must be tested against build time version, not runtime version

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5401]
Currently, CuPy tests function availability based on the runtime version of CUDA libraries, but it should be done with the build-time version, because compatibility stub functions (#5393) are injected based on the build time version (i.e., `#if` in header files).

* cuSPARSE: https://github.com/cupy/cupy/blob/v10.0.0a2/cupy/cusparse.py#L127
* cuSOLVER: https://github.com/cupy/cupy/blob/v10.0.0a2/cupy/cusolver.pyx#L91

I found this issue when looking into #5313. To support both CUDA 11.1.0 and CUDA 11.1.1 in `cupy-cuda111` package, we have to fix this issue, AND build `cupy-cuda111` with CUDA 11.1.0 instead of CUDA 11.1.1 (https://github.com/cupy/cupy-release-tools/pull/132 -- currently reverted).

![cuda111_cusparse](https://user-images.githubusercontent.com/939877/123374850-c1feb900-d5c2-11eb-82c2-fcb8b585203f.png)

**Comment by kmaehashi** [comment]
Fixed via above PRs

**Comment by leofang** [comment]
@kmaehashi This would make CuPy prepared for the upcoming `cudatoolkit` splitting that NVIDIA is working on (https://github.com/conda-forge/cudatoolkit-feedstock/issues/62)!
