### ISSUE TITLE
cupyx.jit inline and device function support

### ISSUE THREAD

**Issue by azrael417** [cupy/cupy#5421]
Hello all,

I was wondering what the timeline for cupyx.jit device function support is. I am facing a situation where I have threads calling into a lengthy function. I could manually inline it but the code would get messy. The other solution would be to decorate the function with an inline statement as it can be done in Cython. Is there a possibility to do one or the other, and if not, what is the timeline for supporting device functions or inlining in cupyx.jit?

Best and thanks
Thorsten

**Comment by asi1024** [comment]
@azrael417 Yes, we are recognizing that the support of device functions is definitely an important feature! The features that will be supported in CuPy JIT are listed in this issue: https://github.com/cupy/cupy/issues/4290

One of the most difficult issues in supporting device functions is type inference (recursive functions, especially). As the first step, we are planning the support of device functions with a type annotation.
