### ISSUE TITLE
Documentation for `cupy.linalg.matrix_power()` has incorrect warning

### ISSUE THREAD

**Issue by coderforlife** [cupy/cupy#5451]
In master, the documentation for `cupy.linalg.matrix_power()` states that "M must be of dtype float32 or float64.". However, the function is only implemented using `cupy.linalg.matmul()` which does support integer matrices, i.e. the following works fine:

```python
cupy.linalg.matrix_power(cupy.arange(1, 26).reshape(5, 5), 5)
```

It is possible that this was originally intended to be implemented using an eigenvalue decomposition, however, eigenvalue decomposition isn't well supported with CUDA unless the matrix is symmetric, and thus it is *not* implemented using that setup. Additionally, in the future if the eigenvalue decomposition method is implemented, the current method could still be used for integer matrices.

**Comment by toslunar** [comment]
> algorithm

`scipy.linalg.fractional_matrix_power` uses some matrix decomposition.
https://github.com/scipy/scipy/blob/v1.7.0/scipy/linalg/_matfuncs_inv_ssq.py#L596-L668

For integer `n`, I suppose iterating matmul is faster.
https://github.com/numpy/numpy/blob/v1.21.0/numpy/linalg/linalg.py#L656-L664

**Comment by coderforlife** [comment]
Interesting. I would imagine if you were raising to a very high power (like the 1024-th or higher powers like I am when I discovered this and looked into the source code) then decomposition would be helpful. Clearly for fractional powers it is always necessary. The Scipy one uses Schur decomposition which is the core of eigenvalue decomposition (although in practice, for Hermitian matrices you don't use Schur decomposition since there are faster ways).

I did some timing with numpy/scipy and they aren't as different as I expected (although higher powers did benefit, it took very high powers and still only about 7.5% faster):

```python
M = numpy.random.rand(256, 256)

%timeit numpy.linalg.matrix_power(M, 256)
# 2.16 ms ± 210 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
%timeit scipy.linalg.fractional_matrix_power(M, 256)
# 2.38 ms ± 284 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit numpy.linalg.matrix_power(M, 1024)
# 2.98 ms ± 185 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
%timeit scipy.linalg.fractional_matrix_power(M, 1024)
# 2.85 ms ± 380 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit numpy.linalg.matrix_power(M, 4096)
# 3.71 ms ± 421 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
%timeit scipy.linalg.fractional_matrix_power(M, 4096)
# 3.45 ms ± 353 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
