### ISSUE TITLE
Random Generator wrong values for larger sizes more than 1d

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#5466]
Random Generator generates wrong values for relatively larger sizes more than 1d. See https://github.com/cupy/cupy/pull/5443#issuecomment-876126570.

```Python
import cupy as cp
n, m = 1000, 1000
rng = cp.random.default_rng()
print(rng.standard_normal(size=(n,m)))
```
```
[[ 0.03452507 -0.35151566 -0.834608   ... -0.06933814 -0.42448833 -1.30178774]
 [-0.35968648  1.23448134  1.07243507 ... -0.90998636  0.56618753 -0.27544234]
 [ 0.71319972  0.92449177 -0.88133939 ...  1.77739648 -0.14771552 -1.15365329]
 ...
 [ 0.          0.          0.         ...  0.          0.          0.        ]
 [ 0.          0.          0.         ...  0.          0.          0.        ]
 [ 0.          0.          0.         ...  0.          0.          0.        ]]
```

**Comment by toslunar** [comment]
https://github.com/cupy/cupy/blob/d53212bb87579013ec8a1c4b8d31de8512f92b40/cupy/random/_generator_api.pyx#L531-L532

This works only if `out` is 1d.

**Comment by emcastillo** [comment]
All the arrays are passed as 1D arrays to the CUDA kernels 😄, so I don't see at a first glance the problem.
I will try to debug this, sounds a bit weird.
Sorry for the issue!
