### ISSUE TITLE
Memory type information is not available when `MemoryPool` is in use

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#5511]
Consider the following snippet that uses `MemoryPool`:
```python
>>> import cupy
>>>
>>> cupy.cuda.set_allocator(cupy.cuda.MemoryPool(cupy.cuda.malloc_managed).malloc)
>>> a = cp.arange(10)
>>> a.data
<MemoryPointer 0x7f26c0000000 device=0 mem=<cupy.cuda.memory.PooledMemory object at 0x7f28da594930>>
```
The actual memory type (`ManagedMemory`) is absorbed into `PooledMemory`. But ideally it should be available somewhere for query. If `MemoryPool` is not used, it is exposed as expected:
```python
>>> cupy.cuda.set_allocator(cupy.cuda.malloc_managed)
>>> a = cp.arange(10)
>>> a.data
<MemoryPointer 0x7f26c0000200 device=0 mem=<cupy.cuda.memory.ManagedMemory object at 0x7f28da5a72a0>>
``` 

The accessibility to the type information can be useful, for example in DLPack we can set `kDLCUDAManaged` accordingly. Perhaps we could add a new attribute to `BaseMemory` and record the type name?

**Comment by emcastillo** [comment]
Maybe you can use?
```
cupy_backends/cuda/api/runtime.pyx:    int cudaPointerGetAttributes(_PointerAttributes* attributes,
```

**Comment by leofang** [comment]
Yeah I have to pay a look-up price anyway. I forgot about pointer attributes -- thanks Emilio!

**Comment by emcastillo** [comment]
@kmaehashi suggested it :)
