### ISSUE TITLE
Output of cupy.get_array_module is not correct

### ISSUE THREAD

**Issue by nogu-atsu** [cupy/cupy#554]
When the input to cupy.get_array_module is a "cupy.sparse" matrix, this function returns  "numpy". 

```
>>> import cupy
>>> a = cupy.array([0,0,1], dtype=xp.float32)
>>> a = cupy.sparse.csr_matrix(a)
>>> cupy.get_array_module(a)
<module 'numpy' from '.../numpy/__init__.py'>
```
I think the output should be "cupy".
cupy version: 2.0.0rc1

**Comment by niboshi** [comment]
Thank you for reporting!
Fixed in PR #568.
