### ISSUE TITLE
Why can I only use one GPU?

### ISSUE THREAD

**Issue by xiaoxstz** [cupy/cupy#5552]
There are two GPUs on my PC

![image](https://user-images.githubusercontent.com/81862747/126610329-6f7cd722-de65-4b69-9d54-af7267ad6db5.png)

but, why can I only use one of them? The code is as below

```python
import cupy as cp
cp.cuda.Device(0).use()  # this is Okay
cp.cuda.Device(1).use() # this would throw an error
```
when I try to use the second GPU, it would throw an error: `cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInvalidDevice: invalid device ordinal`

The environment:
* Cuda: cuda 11.3
* CuPy: cupy-cuda113
* Operation system: Windows 10, x64

By the way, how can I which CPU is used?

**Comment by CChapmanbird** [comment]
CUDA is not supported by integrated graphics, so presumably your `Device(0)` corresponds to the MX230 already.
