### ISSUE TITLE
Using in1d results in AttributeError

### ISSUE THREAD

**Issue by royparijat** [cupy/cupy#5564]
Since setdiff1d is not implemented in Cupy, I am trying to use in1d but still face this issue -- 

 **remainingElements = remainingElements[~cp.in1d(remainingElements,chosenElements)]; 

AttributeError: module 'cupy' has no attribute 'in1d'**

https://github.com/cupy/cupy/blob/83d5e6d358da8f6b7586a620bc34c1720db97425/cupy/_logic/truth.py#L65

**Comment by kmaehashi** [comment]
Hmm that's strance, `cupy.in1d` is available since CuPy v7 (https://github.com/cupy/cupy/pull/2388).
Could you confirm your CuPy version installed? Also please try uninstalling & reinstalling CuPy.

**Comment by royparijat** [comment]
Figured the issue, was on v6. My apologies!
