### ISSUE TITLE
`cupy.s_()` is missing

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#5567]
...although it looks like we can just import `numpy.s_()` as `cupy.s_()`.

**Comment by toslunar** [comment]
- `cupy.index_exp` might be nice, too.  https://numpy.org/doc/stable/reference/generated/numpy.s_.html
- I'd rather not adding `cupy.lib.index_tricks` until someone wants this, because https://github.com/numpy/numpy/blob/2c1a34daa024398cdf9c6e1fbeff52b4eb280551/numpy/lib/__init__.py#L2-L4

**Comment by toslunar** [comment]
#6077

**Comment by kmaehashi** [comment]
Added via #6077
