### ISSUE TITLE
Cannot output correct integer values with "printf"

### ISSUE THREAD

**Issue by sxlllslgh** [cupy/cupy#5572]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version 9.2.0
  - OS/Platform Windows 10 64bit
  - CUDA version 11.3
  - cuDNN/NCCL version (if applicable) 8.2.0
* Code to reproduce
```python
my_kernel = cp.RawKernel(r'''
    extern "C" __global__ void my_voxel(int count) {
        int tid = blockIdx.x * blockDim.x + threadIdx.x;
        if (tid < count) {
            printf("TID: %d\n", &tid);
         }
     }
''', 'my_kernel ', ('-dc', ))
my_kernel((1024, ), (1024, ), (5000, ))
cp.cuda.Stream.null.synchronize()
```
* Here is output in command line:
```bash
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
TID: 1845492960
```
It is just an example shows that I could not get correct global thread IDs and all of them are same. In fact, any integer variable cannot printf correctly while float seems working normally.

**Comment by takagi** [comment]
Seems passing the address of tid?

**Comment by sxlllslgh** [comment]
> Seems passing the address of tid?

Thanks very much! I just confused the usage of **printf** with **scanf** for out of practice on C language. How foolish mistake it is!
