### ISSUE TITLE
Doubled memory usage?

### ISSUE THREAD

**Issue by arogozhnikov** [cupy/cupy#558]
```
result = cupy.random.normal(size=[128 * 1024 * 1024], dtype=cupy.float32)
```
I would expect that this is 512mb, while it takes 1115MB on GPU. Same thing in other cases. 

Is there something I am missing?

**Comment by arogozhnikov** [comment]
Tried the same with larger sizes of array - still used memory is twice larger than my computations.

**Comment by niboshi** [comment]
Thank you for reporting! I made a PR to fix this issue. #562

**Comment by arogozhnikov** [comment]
ok, thanks, I see the reason. 

But why `cupy` doesn't free the memory of intermediate object? Does it have own memory management?

**Comment by niboshi** [comment]
Yes, CuPy has recently introduced its own memory pool.
That's why intermediate buffers are not apparently released.
Even if it looks leaking, it should have no harm in practice.
