### ISSUE TITLE
error: Microsoft Visual C++ 14.2 or greater is required

### ISSUE THREAD

**Issue by cgohlke** [cupy/cupy#5619]
In case building CuPy 9.3 on Windows with Visual Studio 2019 and CUDA SDK 11.4 (and probably other versions) fails with `error: Microsoft Visual C++ 14.2 or greater is required. Get it with "Microsoft C++ Build Tools ...`, this patch worked for me on Python 3.7-10:

```diff
diff --git a/cupy_setup_build.py b/cupy_setup_build.py
index b363c1026..0d77f34aa 100644
--- a/cupy_setup_build.py
+++ b/cupy_setup_build.py
@@ -2,7 +2,7 @@ import argparse
 import copy
 from distutils import ccompiler
 from distutils import errors
-from distutils import msvccompiler
+from distutils import _msvccompiler as msvccompiler
 from distutils import sysconfig
 from distutils import unixccompiler
 import os
```

**Comment by emcastillo** [comment]
Hi and thanks a lot for the report!
We have seen issues with distutils versions so maybe this one has to do with that ...

We will look in-depth into this.

**Comment by kmaehashi** [comment]
I confirmed this issue with the latest Build Tools for Visual Studio 2019.
