### ISSUE TITLE
Fix parameterization of casting tests

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5626]
Context: https://github.com/cupy/cupy/pull/5622#issuecomment-895121386 and #5550

I think it's better to avoid `dtype ** 3` parameterization.

```py
    @testing.for_all_dtypes_combination(
        names=['in0_type', 'in1_type', 'out_type'])
```

Can we fix somehow fix this, e.g, by splitting it into two (`combination(in0_type, out_type) + fixed in1_type` & `combination(in1_type, out_type) + fixed in0_type`)?

cc/ @toslunar

**Comment by toslunar** [comment]
`for_all_dtypes_combination(..., full=False)` is OK to me.

I'll change `xfail(strict=False)` to `skip` and I'll add `xfail` with a concrete dtype combination.

**Comment by kmaehashi** [comment]
Discussed offline with @toslunar and @asi1024:
* Mark the existing test (full-combination) as `slow`
* Add mini version of the test (manually picked combination)
