### ISSUE TITLE
fastmath approximate functions?

### ISSUE THREAD

**Issue by mdschroer** [cupy/cupy#5676]
First of all, thanks for your work on this package.  Cupy has been amazing in opening up gpu coding to relative dunces like me!

Out of curiosity, is there any plans to support the [fastmath](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__INTRINSIC__SINGLE.html)  single precision functions in cuda? I have an application that spends most of its time calculating complex exponentials, and I think it could really benefit from a sincosf.

Apologies if this is already in cupy and I missed it!

Thanks!

**Comment by takagi** [comment]
You can use user-defined kernels (ElementwiseKernel/ReductionKernel/RawKernel) for fastmath:

```Python
>>> import cupy as cp
>>> my_sincosf = cp.ElementwiseKernel(
>>>     'float32 x',
>>>     'float32 y0, float32 y1',
>>>     'sincosf(x, &y0, &y1)',
>>>     'my_sincosf')
>>> x = cp.array([0, cp.pi/2, cp.pi], dtype='f')
>>> my_sincosf(x)
(array([ 0.000000e+00,  1.000000e+00, -8.742278e-08], dtype=float32),
 array([ 1.000000e+00, -4.371139e-08, -1.000000e+00], dtype=float32))
```

See [User-Defined Kernels](https://docs.cupy.dev/en/stable/user_guide/kernel.html) for the details.

**Comment by mdschroer** [comment]
Fair enough!  It seems like directly exposing it as cupy functions would be nice, but I can handle the above.

Thanks for the help!
