### ISSUE TITLE
[feature request] implement cupyx.scipy.special.sph_harm

### ISSUE THREAD

**Issue by s6pepaul** [cupy/cupy#5684]
Hi all,

it would be great to have a cupyx.scipy.special.sph_harm function as in https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.sph_harm.html

Cheers,
Peter

**Comment by s6pepaul** [comment]
Hi, just wondering what the status on this is. If I can help (run a test etc) please let me know.

**Comment by grlee77** [comment]
> Hi, just wondering what the status on this is. If I can help (run a test etc) please let me know.

I did open a PR (https://github.com/cupy/cupy/pull/5687), but hadn't had time to get back to updating it. If you want to try out that branch and report any issues/problems for your use case that could be helpful. 

The biggest issue remaining to address in that PR is some failing test cases for `gammaincinv` and `gammainccinv` that need to be looked into.
