### ISSUE TITLE
CuPy for Multi-GPU

### ISSUE THREAD

**Issue by llodds** [cupy/cupy#5692]
How to truly enable parallel (or asynchronous) CuPy for multi-GPUs? I tried adding cp.cuda.Device(i) and non-blocking stream to scope my code, but it didn't help. I designed a simple test running on two V100s. On each V100, I plan to do some asynchronous computations on the device. The desired GPU activities would be two GPUs reaching ~100% peak computation at the same time, but what I observed that the computation usage is alternating between ~100% and ~0%: when GPU#0 is reaching 100%, GPU#1 is using only 0%, and vice versa (as shown in the nvidia-smi report at the bottom), which indicates the device work is performed sequentially rather than simultaneously. 

Any help would be appreciated. Thanks! I am trying to combine CuPy with distributed TensorFlow code. 

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
CuPy Version          : 8.0.0
CUDA Root             : /hpc/apps/RHEL/3.10/x86_64/cuda/11.0
CUDA Build Version    : 11000
CUDA Driver Version   : 11020
CUDA Runtime Version  : 11000
cuBLAS Version        : 11200
cuFFT Version         : 10201
cuRAND Version        : 10201
cuSOLVER Version      : (10, 6, 0)
cuSPARSE Version      : 11101
NVRTC Version         : (11, 0)
Thrust Version        : 100909
CUB Build Version     : 100909
cuDNN Build Version   : 8000
cuDNN Version         : 8000
NCCL Build Version    : 2708
NCCL Runtime Version  : 2708
cuTENSOR Version      : None
* Code to reproduce
```python
import cupy as cp

shape = (20, 128, 128, 128)

for it in range(100): # iteration number
    for i in range(2): # device number
        with cp.cuda.Device(i):
            s = cp.cuda.Stream(non_blocking = True)
            with s:
                X = cp.random.rand(*shape)
                Y = cp.random.rand(*shape)
                for j in range(5000): # a really long computation (~30 seconds on V100)
                    X += cp.random.rand(*shape) 
                    Y += cp.random.rand(*shape) 
```
* Error messages, stack traces, or logs
<img width="609" alt="Screen Shot 2021-08-30 at 2 40 07 PM" src="https://user-images.githubusercontent.com/3358807/131395700-e6f87c13-937f-48e1-b5bd-8485a0f366ec.png">

**Comment by kmaehashi** [comment]
Could you take a profile using Nsight Compute?

**Comment by llodds** [comment]
@kmaehashi I believe you mean Nsight System rather than Compute. 

I changed the code a little bit, now the non-blocking streams are created at the very beginning, yet the code is still running sequentially on two GPUs.
```python
import cupy as cp

shape = (20, 128, 128, 128)

s = []
for i in range(2):
    cp.cuda.Device(i).use()
    s.append(cp.cuda.Stream(non_blocking = True))

for it in range(3): # iteration number
    for i in range(2): # device number
        with s[i]:
            cp.cuda.Device(i).use()
            X = cp.random.rand(*shape)
            Y = cp.random.rand(*shape)
            for j in range(1000):
                X += cp.random.rand(*shape) 
                Y += cp.random.rand(*shape) 
```

Nsight System profile result:
<img width="2412" alt="Screen Shot 2021-08-31 at 9 43 07 AM" src="https://user-images.githubusercontent.com/3358807/131534179-8192ff63-e20b-4dd8-a478-6d553a226f40.png">

Take a closer look, not sure what is blocking the job on the second GPU:
<img width="1418" alt="Screen Shot 2021-08-31 at 10 58 57 AM" src="https://user-images.githubusercontent.com/3358807/131536438-89aee9f3-ef0f-463f-aa0a-de37ebbf8660.png">

**Comment by emcastillo** [comment]
`.rand` just calls cuRand with the host API, 
could there be an internal synchronization in cuRand?
