### ISSUE TITLE
No cupy.prof module

### ISSUE THREAD

**Issue by DavoudTaghawiNejad** [cupy/cupy#5695]
I am trying to use cupy.prof.TimeRangeDecorator, however there does not appear to be a cupy.prof module at all.

import cupy as cp

@cupy.prof.TimeRangeDecorator()
def some_function():
      pass

AttributeError: module 'cupy' has no attribute 'prof'

OS                           : Linux-5.4.0-1046-azure-x86_64-with-glibc2.10
Python Version               : 3.8.5
CuPy Version                 : 9.4.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.19.2
SciPy Version                : 1.5.2
Cython Build Version         : 0.29.24
Cython Runtime Version       : 0.29.21
CUDA Root                    : /home/datascience/anaconda3
nvcc PATH                    : None
CUDA Build Version           : 10010
CUDA Driver Version          : 11030
CUDA Runtime Version         : 10010
cuBLAS Version               : (available)
cuFFT Version                : 10101
cuRAND Version               : 10101
cuSOLVER Version             : (10, 2, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (10, 1)
Thrust Version               : 100906
CUB Build Version            : <unknown>
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA Tesla K80
Device 0 Compute Capability  : 37
Device 0 PCI Bus ID          : 0001:00:00.0

**Comment by emcastillo** [comment]
`cupy.prof` is not in the default namespace, you need to explicitly import it
`import cupy.prof`

**Comment by kmaehashi** [comment]
Closing as this is not active for a while. Feel free to reopen if there's anything we can help.
