### ISSUE TITLE
[RFC] Drop Python 3.6 support in v10

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5699]
We are now discussing to drop support for Python 3.6 in CuPy v10. Feel free to leave a comment here if you have any concerns.

Background:
* CUDA Python is unlikely to provide a wheel for Python 3.6, although it can be built from the source without any issue. CUDA Python currently requires [`-std=c++14`](https://github.com/NVIDIA/cuda-python/blob/427c597959e6fe1409195a30d42fc4a1886bc89a/setup.py#L38) so recent versions of gcc, which is not in RHEL/CentOS 7 by default, is needed. We want to avoid requiring CuPy wheel users to manually install non-default GCC.
* NumPy dropped Python 3.6 support in June 2020: https://numpy.org/neps/nep-0029-deprecation_policy.html
* Python 3.6 support become EOL in December 2021.

**Comment by twmht** [comment]
@kmaehashi 

We deploy our product with Jetson platform. And currently the jetpack only supports to run python3.6 with TensorRT. they don't provide the 3.7 binding for TensorRT in jetpack. 

so from my opinion, this may be the case we need to consider.

**Comment by kmaehashi** [comment]
@twmht 

https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html#rel_8-0-1

> These release notes are applicable to workstation, server, and JetPack users unless appended specifically with (not applicable for Jetson platforms).
...
> ‣ Added Python 3.9 support. Use a tar file installation to obtain the new Python wheel files. For more information, refer to the TensorRT Installation Guide.

`TensorRT-8.0.1.6.Ubuntu-20.04.aarch64-gnu.cuda-11.3.cudnn8.2.tar.gz` contains Python 3.6~3.9 wheels so I guess JetPack 4.6 can use them?

**Comment by twmht** [comment]
@kmaehashi 

oops. my bad. I thought TensorRT bindinds is bundled with JetPack version. I would try this in next week. 

thank you.

**Comment by twmht** [comment]
@kmaehashi 

I found out the TensorRT can't be upgrade standalone in Jetpack.

For example, TensorRT must bundle with specific cuda version, and we can't upgrade cuda version and driver within jetpack.

More context: https://forums.developer.nvidia.com/t/how-to-upgrade-tensorrt-to-7-0-version/110231

Also, I found out python3.6 can't work with cupy, since you introduce `contextlib.nullcontext()` (https://github.com/cupy/cupy/blob/master/cupy/_core/core.pyx), this is only available in 3.7. Is it possible to use python 3.6 with latest cupy?

**Comment by kmaehashi** [comment]
With Jetpack 4.6, it seems Python binding wheels included in the above tarball works as it is built for CUDA 10.2 (I don't know why it's not built against CUDA 11.3).

**Comment by twmht** [comment]
cool. I did not try that since they said it's only cuda11.3.

> TensorRT 8.0 GA for Linux and only CUDA 11.3

Let me have a try.

**Comment by twmht** [comment]
And I also found out we may build python bindings for TensorRT by ourself (https://github.com/NVIDIA/TensorRT/tree/main/python)  . I am working on that.
