### ISSUE TITLE
Sorting functions miss arguments `kind` and `order`

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#5701]
Refs:
- `argsort()`:
  - NumPy: https://numpy.org/doc/stable/reference/generated/numpy.argsort.html
  - CuPy: https://docs.cupy.dev/en/stable/reference/generated/cupy.argsort.html
- `sort()`
  - NumPy: https://numpy.org/doc/stable/reference/generated/numpy.sort.html
  - CuPy: https://docs.cupy.dev/en/stable/reference/generated/cupy.sort.html

I haven't checked other sorting functions (ex: `partition()`) but they probably missed them too. Though, Array API v1 only needs the above two sorting functions.

The `kind` argument is needed by the Array API standard (#5698, #4789).

**Comment by takagi** [comment]
Do we need `order` argument?

**Comment by leofang** [comment]
Yes only kind is needed, sorry I didn't pay attention 😅
