### ISSUE TITLE
Device/Stream semantics mismatch in v10

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5705]
Currently, the behavior of Device/Stream classes is not aligned.
As these two classes have similar APIs I think users expect to behave similarly.

```py
with cupy.cuda.Device(1) as d1:
    d2 = cupy.cuda.Device(0).use()
    with d1:
        pass
    print(f'd1 = {d1}, d2 = {d2}, current = {cupy.cuda.Device()}')  # 0
```
```
d1 = <CUDA Device 1>, d2 = None, current = <CUDA Device 0>
```

```py
with cupy.cuda.Stream() as s1:
    s2 = cupy.cuda.Stream().use()
    with s1:
        pass
    print(f's1 = {s1}, s2 = {s2}, current = {cupy.cuda.get_current_stream()}')  # s1
```

```
s1 = <Stream 94338156947936 (device 0)>, s2 = <Stream 94338156946800 (device 0)>, current = <Stream 94338156947936 (device 0)>
```

I think device semantics needs be changed:
* `Device().use()` should `return self`
* When exiting a context, the current device should be reverted back to the device of the parent's context scope, not the device last `use()`d.

Refs https://github.com/cupy/cupy/pull/5172 @leofang

**Comment by leofang** [comment]
Good catch! Yeah since the stream behavior is not backward compatible anyway, we might as well do all the necessary breaking changes that make sense in the same release.

**Comment by leofang** [comment]
Surprised myself today... 😂
```
>>> import cupy as cp
>>> cp.cuda.Device(1).use()
<CUDA Device 1>
>>> with cp.cuda.Device(1):
...     s = cp.cuda.Stream()
... 
>>> cp.cuda.Device()  # not 1 !!!
<CUDA Device 0>
```
