### ISSUE TITLE
`cupy.ndarray` cannot be compared with ellipsis

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#5715]
Not sure if it's due to #4198. The `__richcmp__` method does not handle trivial comparison with Python objects correctly:
```python
>>> np.empty(3) == ...
array([False, False, False])
>>>
>>> cp.empty(3) == ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/_core/core.pyx", line 1094, in cupy._core.core.ndarray.__richcmp__
    return numpy.equal(self, other)
TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'equal'>, '__call__', array([0., 0., 0.]), Ellipsis): 'ndarray', 'ellipsis'
```
It seems NumPy internally calls `PyObject_RichCompare` to handle this. Perhaps before delegating to `numpy.equal()` (and friends) we should handle this edge case first?

**Comment by leofang** [comment]
Note: this relates to the `test_indexing.py` failure seen in https://github.com/cupy/cupy/pull/5698#issuecomment-913406882.

**Comment by toslunar** [comment]
#1989 discusses comparison with `None`.

**Comment by asmeurer** [comment]
Can you post the traceback from the test failure? We should probably make the array API tests not use == for comparing arrays and use `is` to compare against Ellipsis.

**Comment by takagi** [comment]
This line brings the error, where `key` is a tuple that contains array indices and they are compared to an ellipsis. When an index is a ndarray, the error above occurs. I think we should count using `is` here. 
https://github.com/cupy/cupy/blob/0955ad9082b103d6b8a05a63009d69001504c61d/cupy/array_api/_array_object.py#L330

**Comment by toslunar** [comment]
> `n_ellipsis = key.count(...)`

To be precise, each array index in `key` must have `_.size <= 1`, or `key.count(...)` will raise `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`.  The line works fine because indexing with integer arrays is unspecified in Array API. https://data-apis.org/array-api/latest/API_specification/indexing.html
https://github.com/cupy/cupy/blob/0955ad9082b103d6b8a05a63009d69001504c61d/cupy/array_api/_array_object.py#L346-L351

**Comment by asmeurer** [comment]
Do you know if this code leads to a problem in the NumPY implementation? I think something like this would be more robust.

```diff
diff --git a/numpy/array_api/_array_object.py b/numpy/array_api/_array_object.py
index ead061882d..e7ddcf033b 100644
--- a/numpy/array_api/_array_object.py
+++ b/numpy/array_api/_array_object.py
@@ -325,10 +325,13 @@ def _validate_index(key, shape):

             if shape is None:
                 return key
-            n_ellipsis = key.count(...)
+            # Use 'is' to compare against ellipsis to avoid performing == on
+            # an array.
+            ellipses = [i for i, k in enumerate(key) if k is ...]
+            n_ellipsis = len(ellipses)
             if n_ellipsis > 1:
                 return key
-            ellipsis_i = key.index(...) if n_ellipsis else len(key)
+            ellipsis_i = ellipses[0] if ellipses else len(key)

             for idx, size in list(zip(key[:ellipsis_i], shape)) + list(
                 zip(key[:ellipsis_i:-1], shape[:ellipsis_i:-1])
```

**Comment by takagi** [comment]
As @toslunar mentioned in https://github.com/cupy/cupy/issues/5715#issuecomment-985991356, I think NumPy's current code works without any problem. But, yes, your diff would be exactly what we want to do there.
