### ISSUE TITLE
Jetson Nano Installation

### ISSUE THREAD

**Issue by yuvalg1987** [cupy/cupy#5750]
Hi,

I'm trying to use CuPy on the Jetson Nano. So far, I've tried building it from source as well as using the standard` pip install cupy` command. In both cases the build fails due to missing NCCL files (I know the Jetson doesn't support NCCL). How can I disable this option? Is there another way to install CuPy on the Jetson? 

In addition, I found a recent post regarding the CUPY_NVCC_GENERATE_CODE enviromnet variable for cutting the build time. What is the correct way of using this variable? simply setting it to FALSE in the bashrc file? 

Thanks
Yuval

**Comment by kmaehashi** [comment]
NCCL is an optional module so it should not disturb CuPy build even if it's missing. Could you share the full build log?

For the usage of environment variables, refer to the reference:
https://docs.cupy.dev/en/stable/reference/environment.html#envvar-CUPY_NVCC_GENERATE_CODE

Jetson Nano's [compute capability](https://developer.nvidia.com/cuda-gpus) is 5.3 so what you need is:
```
export CUPY_NVCC_GENERATE_CODE="arch=compute_53,code=sm_53"
pip install cupy
```

**Comment by emcastillo** [comment]
cupy should build without nccl

```
Modules:
      cuda      : Yes (version 10020)
      nccl      : No
        -> Include files not found: ['nccl.h']
        -> Check your CFLAGS environment variable.
```

This is a copy summary config where nccl was not found, yet still completes the build.

**Comment by yuvalg1987** [comment]
Hi, Thanks for the advice. I tried compiling it on a fresh image of the Nano and it works so I assume I made some mistake along the way.

**Comment by kmaehashi** [comment]
Great, have fun with CuPy on Jetson :smile:
