### ISSUE TITLE
Issue about the API of NCCL

### ISSUE THREAD

**Issue by ganshaoduo** [cupy/cupy#5766]
Hi,

It seems that the API of NCCL described in the document, like `cupy.cuda.nccl`, is not working in the latest Cupy. It will throw an import error saying `cupy.cuda `does not have `nccl`. After checking the source code, I found a workaround is to `import cupy_backends `, then change all the `cupy.cuda.nccl...` to `cupy_backends.cuda.libs.nccl`. Is this expected? or I misused something?

**Comment by kmaehashi** [comment]
Starting in CuPy v9, you need to do `import cupy.cuda.nccl` instead of `import cupy.cuda` explicitly.
This is something we should have covered in the upgrade guide... https://docs.cupy.dev/en/latest/upgrade.html#cupy-v8 (https://github.com/cupy/cupy/pull/4919)
