### ISSUE TITLE
'free_all_blocks' of 'cupy.cuda.memory.MemoryPool' object needs an argument

### ISSUE THREAD

**Issue by clockwiser** [cupy/cupy#578]
When try to free gpu memory, happens the error.
According to the cupy documents, free_all_blocks has no argument.

************************************************************
source:
cp.cuda.MemoryPool.free_all_blocks()
************************************************************
TypeError                                 Traceback (most recent call last)
<ipython-input-19-d5af36b18243> in <module>()
      1 # after free memory, still lots memory left when check with nvidia-smi.
----> 2 cp.cuda.MemoryPool.free_all_blocks()

TypeError: descriptor 'free_all_blocks' of 'cupy.cuda.memory.MemoryPool' object needs an argument

**Comment by kmaehashi** [comment]
This is because `free_all_blocks` is an instance method, not a class method.
If you are using CuPy via Chainer, the memory pool instances is `chainer.cuda.memory_pool` by default, so try this:

```py
chainer.cuda.memory_pool.free_all_free()
```

**Comment by clockwiser** [comment]
Ah, thanks.
I am not using Chainer. Just use cupy to handle gpu processing.
Is there any source example available?

**Comment by kmaehashi** [comment]
If you are using stable version of CuPy, without Chainer, memory pool is not used unless your code is explicitly setting memory pool via `cupy.cuda.memory.set_allocator`.
Note that if your code is doing `import chainer`, then the memory pool is automatically activated even if you are not using Chainer functionality.

If you are using CuPy from master branch, the memory pool is `cupy._default_memory_pool`.
