### ISSUE TITLE
`cupy.ndarray.__index__()` is missing

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#5784]
This is for both NumPy compatibility (`operator.index(arr)` should work) and Array API (https://github.com/data-apis/array-api/issues/231). It should be fairly straightforward to add, so it's not a blocker for https://github.com/cupy/cupy/pull/5783.

**Comment by kmaehashi** [comment]
+1 to add it to `cupy.array_api.Array`.
As for `cupy.ndarray`, this is intentionally unimplemented as this incurs implicit D2H transfer.

**Comment by kmaehashi** [comment]
Right! Closed via #5783.
