### ISSUE TITLE
Add `bitorder` option to `cupy.packbits`

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5792]
Now that `cupy.unpackbits()` supports `bitorder` (thanks to @iskode in #5765), it's nice to support it in `cupy.packbits` as well.

**Comment by iskode** [comment]
Yeah, I was thinking about it as well as both goes together. I plan to work on it next week as I'm a bit busy with some ongoing projects to wrap-up.

**Comment by kmaehashi** [comment]
That's great! 👍🏼
