### ISSUE TITLE
Issue of insert value in large matrix bug

### ISSUE THREAD

**Issue by dominicshanshan** [cupy/cupy#5809]
Failed insert value in a large two dimensional array, e.g. if want to insert two values in row 2998, 2999 with fixed column 1, it failed, and if insert two values in column 2998, 2999 with fixed row 1 without any issue. Meanwhile, insert values in same matrix setting in Numpy without any issues. 

*Conditions
OS                           : Linux-5.4.0-77-generic-x86_64-with-debian-stretch-sid
Python Version               : 3.7.8
CuPy Version                 : 9.4.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.19.4
SciPy Version                : 1.5.1
Cython Build Version         : 0.29.22
Cython Runtime Version       : 0.29.21
CUDA Root                    : /opt/conda/envs/rapids
nvcc PATH                    : None
CUDA Build Version           : 10010
CUDA Driver Version          : 11040
CUDA Runtime Version         : 10010
cuBLAS Version               : (available)
cuFFT Version                : 10101
cuRAND Version               : 10101
cuSOLVER Version             : (10, 2, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (10, 1)
Thrust Version               : 100906
CUB Build Version            : 100800
Jitify Build Version         : 60e9e72
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : 2803
NCCL Runtime Version         : 2803
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-SXM2-32GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:00:07.0

*Code to reproduce

`import numpy as np`
`import cupy as cp`
`np.random.seed(1023)`
`test_cp = cp.full((3000, 200 * 10000), cp.nan, dtype='float32') `
`test_cp[[1, 2], 1] = [1.5, 1]`
`print(test_cp[[1, 2], 1])`
output
`array([1.5, 1], dtype=float32)`

`test_cp[[2998, 2999], 1] = [1.5, 1]`
`print(test_cp[[2998, 2999], 1])`
output
`array([nan, nan], dtype=float32)`

`test_cp[[852, 852],2] = [1,1]`
`print(test_cp[[852, 852],2])`
output
`array([1., 1.], dtype=float32)`

`test_cp[[1000, 1000],2] = [1,1]`
`print(test_cp[[1000, 1000],2])`
output
`array([nan, nan], dtype=float32)`

`test_cp[2, [2999, 2990]]=[1,1]`
`print(test_cp[2, [2999, 2990]])`
output
`array([1., 1.], dtype=float32)`

**Comment by takagi** [comment]
#6081 also fixed this.
