### ISSUE TITLE
Running FFT with plan drastically slows down after runnning FFT without plan

### ISSUE THREAD

**Issue by taladjidi** [cupy/cupy#5820]
While trying to optimize my FFT's I started using user defined plans. I noticed that when running FFT's without a plan, subsequent calls to FFT's using user defined plans are drastically slowed down (x1000). What bothers me is that even when I try clearing the cache, this does not change this behavior. Here is my configuration:
  - CuPy version : 9.4.0
  - OS/Platform : Ubuntu 20.04LTS
  - CUDA version : 11.4
  Here is the benchmark : I instantiate 2 arrays, and instantiate plans for both arrays. I then do a 2D transform and its reverse transform. I repeat the operation Nit times using timeit to check the runtime.
  ```python
from timeit import repeat
import pyfftw
import numpy
import cupy as cp
import matplotlib.pyplot as plt
from cupy.cuda import Device
from cupy.fft.config import get_plan_cache
from cupyx.scipy.fft import get_fft_plan


def create_array(*size):
    arr = pyfftw.empty_aligned(size, dtype='complex64')
    arr[:] = numpy.random.randn(*size) + 1j*numpy.random.randn(*size)
    return arr


small = create_array(8, 2048, 2048)
big = create_array(16, 2048, 2048)

small_c = cp.asarray(small)
big_c = cp.asarray(big)
plan_fft_s = get_fft_plan(small_c, axes=(1, 2), value_type="C2C")
plan_fft_b = get_fft_plan(big_c, axes=(1, 2), value_type="C2C")


def cuda_fft(a):
    b = cp.fft.fftn(a)
    c = cp.fft.ifftn(b)

def plan_small(a):
    plan_fft_s.fft(a, a, cp.cuda.cufft.CUFFT_FORWARD)
    plan_fft_s.fft(a, a, cp.cuda.cufft.CUFFT_INVERSE)

def plan_big(a):
    plan_fft_b.fft(a, a, cp.cuda.cufft.CUFFT_FORWARD)
    plan_fft_b.fft(a, a, cp.cuda.cufft.CUFFT_INVERSE)

Nit = 200
with Device(0):
    cache = get_plan_cache()
    cache.clear()
    # cache.set_size(0)  # disable the cache
    print("Initial cache  ", cache.get_curr_size())
    times_small_p = repeat('plan_small(small_c)', repeat=Nit, number=1, globals=globals())
    print("Run 0 with plan ", cache.get_curr_size())
    times_big_p = repeat('plan_big(big_c)', repeat=Nit, number=1, globals=globals())
    print("Run 1 with plan ", cache.get_curr_size())
    times_small = repeat('cuda_fft(small_c)', repeat=Nit, number=1, globals=globals())
    print("Run 2 without plan ", cache.get_curr_size())
    times_big = repeat('cuda_fft(big_c)', repeat=Nit, number=1, globals=globals())
    print("Run 3 without plan ", cache.get_curr_size())
fig1, ax1 = plt.subplots(1, 2)
ax1[0].plot(times_small)
ax1[0].plot(times_big)
ax1[0].plot(times_small_p)
ax1[0].plot(times_big_p)
ax1[0].set_xlabel("Iteration")
ax1[0].set_ylabel("Time in s")
ax1[0].legend([f"Without plan {small_c.shape}", f"Without plan {big_c.shape}", f"With plan {small_c.shape}", f"With plan {big_c.shape}"])
ax1[0].set_yscale("log")
ax1[0].set_title("Time per iteration")
ax1[1].plot(numpy.cumsum(times_small))
ax1[1].plot(numpy.cumsum(times_big))
ax1[1].plot(numpy.cumsum(times_small_p))
ax1[1].plot(numpy.cumsum(times_big_p))
ax1[1].set_xlabel("Iteration")
ax1[1].set_ylabel("Time in s")
ax1[1].legend([f"Without plan {small_c.shape}", f"Without plan {big_c.shape}", f"With plan {small_c.shape}", f"With plan {big_c.shape}"])
ax1[1].set_yscale("log")
ax1[1].set_title("Cumulative time")
fig1.suptitle("With plan first")
plt.show()

```
As expected (from what I understand of FFT plans at least), the runs with a user defined plan significantly outpace the runs without a user defined plan :
![with_plan_first1](https://user-images.githubusercontent.com/19933187/135649858-07e8354d-2182-4fa6-9b4e-f14f47d681d8.png)
But if I do it the other way around, like this :
```python
with Device(0):
    cache = get_plan_cache()
    print("Initial cache  ", cache.get_curr_size())
    times_small = repeat('cuda_fft(small_c)', repeat=Nit, number=1, globals=globals())
    print("Run 0 without plan ", cache.get_curr_size())
    times_big = repeat('cuda_fft(big_c)', repeat=Nit, number=1, globals=globals())
    print("Run 1 without plan ", cache.get_curr_size())
    cache.clear()
    times_small_p = repeat('plan_small(small_c)', repeat=Nit, number=1, globals=globals())
    print("Run 2 with plan ", cache.get_curr_size())
    times_big_p = repeat('plan_big(big_c)', repeat=Nit, number=1, globals=globals())
    print("Run 3 with plan ", cache.get_curr_size())
```
Everything slows down dramatically even when clearing the cache !
![without_plan_first1](https://user-images.githubusercontent.com/19933187/135650206-c0091902-63e3-4ffa-b54f-3e3d9be81264.png)
Is there something obvious I am missing here ? I also don't understand why the execution speed suddenly jumps at around 60 and 150 iterations, I feel this has maybe something to do with the memory that fills up but since I iterate the transform over a single array I do not understand why this should be the case ... Many thanks in advance.
Tangui

**Comment by leofang** [comment]
The first odd thing I spotted is that you're measuring the CPU time and not GPU time. cuFFT calls are not blocking so you won't see the benefit of plan reuse this way. Could you use `cupyx.time.repeat()` instead of `timeit.repeat()` please? See https://docs.cupy.dev/en/stable/user_guide/performance.html#benchmarking.

**Comment by taladjidi** [comment]
Thank you very much and sorry for the dumb question then ! Running using cupyx.time.repeat gives the expected result : running with a premade plan is significantly faster. I'll be more careful in the future when profiling my code :+1: Many thanks again for the awesome work on CuPy !
