### ISSUE TITLE
CUDA _ERROR_INVALID_HANDLE

### ISSUE THREAD

**Issue by yuvalg1987** [cupy/cupy#5827]
Hi,

I'm using CuPy on the Jetson platform. My code basically includes a pre-processing operation on RGBD images coming from a stereo camera called ZED (which uses CUDA for calculating the 3D measurement).  On the second image i'm getting an error CUDA_ERROR_INVALID_HANDLE (while the first image runs fine). Any suggestions on how to solve this? I've read several comments regarding the CUDA context but they were a bit unclear. 

Thanks
Yuval

**Comment by kmaehashi** [comment]
Hi @yuvalg1987, can you share the reproducer and `cupy.show_config()` output?

**Comment by kmaehashi** [comment]
Closing as solved in https://github.com/cupy/cupy/issues/4618#issuecomment-933482733
