### ISSUE TITLE
Requirement Cython >=0.26.1 should be more prominent

### ISSUE THREAD

**Issue by kohr-h** [cupy/cupy#588]
I managed to install cupy from source, but it took me a while to find out that the Cython version I had (0.26) was the problem. 

When following the instructions (and setting a bunch of environment variables) the output is like this:
```
    ...
    RuntimeError: Missing file: cupy/core/core.cpp
    Please install Cython 0.26.1. Please also check the version of Cython.
    See https://docs-cupy.chainer.org/en/stable/install.html
```
Then, when I follow the link, then I read [here](https://docs-cupy.chainer.org/en/stable/install.html#install-cupy-for-developers) that I need Cython >=0.24.

I suggest
- to make the error message from `python setup.py install` even more clear, like "This error is due to an outdated version of Cython. You need Cython >=0.26.1 to install cupy from source."
  And the link should point to the `latest` doc, not the `stable` one.
- to write about the Cython version requirement already in the "Install CuPy from source" section.

I can make a PR if you want.

**Comment by kmaehashi** [comment]
Cython requirement has been documented and aligned with the installer's requirment.
