### ISSUE TITLE
Remove Cython 3 version restriction

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5893]
### Description

It seems that now CuPy can be built with the latest Cython 3.0 pre-release.
To allow developers and maintainers to try CuPy build using Cython 3.0 let's remove the restriction.

**Comment by leofang** [comment]
Could it be due to the recent pip update? A lot of things are broken in particular with regard to in-place builds, for example see pypa/pip#10573.

**Comment by kmaehashi** [comment]
I *sometimes* get this error when built with Cython 3.

```py
% python -c 'import cupy; print(3 * cupy.arange(10))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'int' and 'cupy._core.core.ndarray'
```

I suspect this change is related but haven't identified the root cause.
https://cython.readthedocs.io/en/latest/src/changes.html
> Special methods for binary operators now follow Python semantics. Rather than e.g. a single __add__ method for cdef classes, where “self” can be either the first or second argument, one can now define both __add__ and __radd__ as for standard Python classes. This behavior can be disabled with the c_api_binop_methods directive to return to the previous semantics in Cython code (available from Cython 0.29.20), or the reversed method (__radd__) can be implemented in addition to an existing two-sided operator method (__add__) to get a backwards compatible implementation. (Github issue #2056)

**Comment by kmaehashi** [comment]
I think we need some additional work to support Cython 3.0. Let's merge the discussion to #4610.

**Comment by littlewu2508** [comment]
I think this can be resolved by adding `c_api_binop_methods` to True to compiler_directives
