### ISSUE TITLE
Max workspace size

### ISSUE THREAD

**Issue by arogozhnikov** [cupy/cupy#591]
Looking at the implementation of chainer's convolution. It allocates the workspace using this size:
```python
cuda.get_max_workspace_size()
```
This size doesn't depend on the operation done, so it raises two questions:
- why not using single workspace for all operations (and avoid allocation/deallocation)?
- how is this size computed (on my machine it is 8mb)?

Also, I've put 0-sized workspace in convolution and it still worked well...

**Comment by okuta** [comment]
`cuDNN` uses working space for speed up of convolution operation. Thus, we can 0-sized workspace.

> why not using single workspace for all operations (and avoid allocation/deallocation)?

This value means maximum workspace size. CuPy can less size workspace when cuDNN requires small workspace.

> how is this size computed (on my machine it is 8mb)?

CuPy or Chainer set 8MB workspace size. In future, this size may be changed.

**Comment by arogozhnikov** [comment]
Ok, I see. 

Is it a good idea to use the same buffer for all the operations?

**Comment by okuta** [comment]
Yes, if you use small buffer size.

In Chainer, almost cuDNN operations use same buffer size as max worksapce size.
And CuPy has a memory pool. So, almost cuDNN operations use same buffer for reduce memory usage.
But, this behavior may cause extra memory usage when the maximum workspace size is large. This behavior may change in the near future.
For example, round up to several sizes ( 1KB, 10KB, 100KB, 1MB, 10MB, 100MB, 1GB ...)
