### ISSUE TITLE
cupy_array[:] = numpy_array does not work

### ISSUE THREAD

**Issue by kohr-h** [cupy/cupy#593]
It would be nice if `__setitem__` worked with Numpy  arrays as right-hand side. Currently one gets the error
```
    Traceback (most recent call last):
      File "cupy/core/core.pyx", line 1575, in cupy.core.core.ndarray.__setitem__
      File "cupy/core/core.pyx", line 3043, in cupy.core.core._scatter_op
      File "cupy/core/core.pyx", line 442, in cupy.core.core.ndarray.fill
    ValueError: non-scalar numpy.ndarray cannot be used for fill
```
A straightforward implementation could first cast to a cupy array and then do the usual setitem. An optimization for same dtype and size (assuming contiguous memory) would be to just use ~~`cudaMemcpy`~~ `cupy_array.data.copy_from_host`, but that may not be very relevant.

**Comment by kohr-h** [comment]
I guess this has the same constraints regarding unwanted copies as #589

**Comment by mrocklin** [comment]
Perhaps implicit host->device copies are better than implicit device->host copies?  I can fully understand CuPy intentionally deciding not to allow `np.asarray(my_cupy_array)`, but allowing `cupy.asarray(my_numpy_array)` might be fine.  

Similarly, 

```python
host_array[:] = device_array  # understandable that this fails
device_array[:] = host_array  # maybe this is ok?
```

**Comment by pentschev** [comment]
Following up to @mrocklin's comment, a special case to handle that case could be as simples as:

```python
cdef class ndarray:

...

def __setitem__(self, slices, value):
    if slices == slice(None, None, None) and isinstance(value, numpy.ndarray):
        self = cupy.array(value)
    else:
        _indexing._ndarray_setitem(self, slices, value)
```

**Comment by mrocklin** [comment]
I might go further and suggest:

```python
def __setitem__(self, slices, value):
    if isinstance(value, np.ndarray):
        value = cupy.array(value)
    # the rest of the code as it is currently written
```

Though this is a larger request

**Comment by pentschev** [comment]
The rest of the code is just that single line that follows `else` in the snippet I posted before. It's expected that `value` is a scalar, so that won't work.

**Comment by pentschev** [comment]
But of course, my snippet won't work either, because of the assignment to `self`.

**Comment by pentschev** [comment]
Upon more careful consideration, I think the simplest we could do to make this work would be something like the following:

```python
def __setitem__(self, slices, value):
    if slices == slice(None, None, None) and isinstance(value, numpy.ndarray):
        device_array = array(value)
        self.dtype = get_dtype(device_array.dtype)
        self._set_shape_and_strides(device_array._shape, device_array._strides, True, True)
        self.data = device_array.data
    else:
        _indexing._ndarray_setitem(self, slices, value)
```

The disadvantage I see with this code is perhaps maintainability, should there be a change in the attributes of `cupy.ndarray`, this would have to be properly handled as well. Another alternative I could see is to have another function handling this, that could be shared with `__init__`.

Nevertheless, I will send a PR soon to make sure everyone gets a clearer picture of my suggestion, and if needed be, suggest changes in the review process.

**Comment by orodbhen** [comment]
Sorry, I'm a little confused. I am correct to assume this should be working now? I'm using version 8.3.0, and getting the same error noted in the issue description. 

If this does work, is there some way to copy data from the host to the GPU without performing an additional allocation? I tried `d_arr[:] = cupy.asarray(h_arr)`, and it appears to allocate a temporary buffer on the device before copying it to the destination array.

**Comment by orodbhen** [comment]
`d_a.data.copy_from(a.ctypes.data_as(ctypes.c_void_p), NBYTES)` works, but it's hardly elegant.

**Comment by leofang** [comment]
@orodbhen Try setting the env var `CUPY_EXPERIMENTAL_SLICE_COPY=1`.

**Comment by leofang** [comment]
> `d_a.data.copy_from(a.ctypes.data_as(ctypes.c_void_p), NBYTES)` works, but it's hardly elegant.

btw with the latest stable release of CuPy (v9.6) I think `d_a.data.copy_from(a.ctypes.data, NBYTES)` would also work.

**Comment by orodbhen** [comment]
> @orodbhen Try setting the env var `CUPY_EXPERIMENTAL_SLICE_COPY=1`.

@leofang Thanks, that works. It would be nice if there was also an explicit function for this that takes `numpy.ndarray` as input, or a parameter for `asarray`. And maybe there is, I just haven't been able to find it.

**Comment by leofang** [comment]
There's at least `cupy.asarray()` that can take a numpy array.
