### ISSUE TITLE
Doc: Introduce `sphinx-copybutton`

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5949]
### Description

Let's introduce https://sphinx-copybutton.readthedocs.io/en/latest/ to make snippets copiable.

**Comment by prkhrsrvstv1** [comment]
Hi @kmaehashi! Unfortunately testing my code changes is proving to be difficult on my MacBook (no NVIDIA GPU!). Feel free to give this issue to others.

**Comment by leofang** [comment]
Hi @prkhrsrvstv1 technically speaking to work on the doc builds you don't need any GPUs. If you install CuPy via
```
READTHEDOCS=True pip install -v -e .
```
CuPy can be built using stub headers and does not need the presence of either CUDA or HIP sw stack. In fact it's how the RTD environment was set up. You can check rendered htmls and so on. You just can't actually run any CuPy code this way. 

Let us know if this helps :)

**Comment by prkhrsrvstv1** [comment]
Hey @leofang that helped! I had to set-up a Linux environment to actually install (it seems [MacOS is explicitly not supported](https://github.com/cupy/cupy/blob/ea86c8225b575af9d2855fb77a306cf86fd098ea/install/cupy_builder/cupy_setup_build.py#L379-L380)).

Opened PR #5976

**Comment by leofang** [comment]
Ah yes, we no longer support building on Mac. Glad you figured out the rest!
