### ISSUE TITLE
Any function like scipy.sparse.csc_matrix.sum ?

### ISSUE THREAD

**Issue by sunshineatnoon** [cupy/cupy#595]
Thanks for sharing this awesome framework. Is there any function similar to [scipy.sparse.csc_matrix.sum](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.sum.html#scipy.sparse.csc_matrix.sum) ?

**Comment by unnonouno** [comment]
Thank you for a request. `sum` is easy to implement. I'll try to make it.

**Comment by sunshineatnoon** [comment]
Cool! Thanks so much!
