### ISSUE TITLE
Standard way to select between cupy.sparse and scipy.sparse

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#598]
(From https://github.com/cupy/cupy/pull/568#issuecomment-334491894)

We need a standard way to selelct between `cupy.sparse` and `scipy.sparse`, just like `xp`:
```
xp = cupy.get_array_module(a)
b = xp.ndarray(...)
```

**Comment by lakehanne** [comment]
Has this been fixed? How do you copy e.g a `scipy.sparse csr_matrix` to e.g. `cupy csr_matrix`?

**Comment by kmaehashi** [comment]
`cupyx.scipy.get_array_module` has been implemented.

see also https://docs.cupy.dev/en/stable/reference/sparse.html
