### ISSUE TITLE
Doc: `cupy.positive` needs to be added in API reference

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#6017]

**Comment by SauravMaheshkar** [comment]
@kmaehashi Can I take this up ?

Also, correct me if I'm wrong but the function in focus is this 
https://github.com/cupy/cupy/blob/ea5b2e8f8bc9d23828bee8ae7b91db93d0b00745/cupy/_core/_routines_math.pyx#L914

**Comment by kmaehashi** [comment]
@SauravMaheshkar Of course, go ahead!

> The docs that should be edited are :-
> 
> 1. [**`math.rst`**](https://github.com/cupy/cupy/blob/master/docs/source/reference/math.rst)
> 2. [**`ufunc.rst`**](https://github.com/cupy/cupy/blob/master/docs/source/reference/ufunc.rst)

👍🏼 

> And the docstrings would be added to [**`cupy/_math/misc.py`**](https://github.com/cupy/cupy/blob/master/cupy/_math/misc.py)

Docstring is set here so you don't have to add one.
https://github.com/cupy/cupy/blob/ea5b2e8f8bc9d23828bee8ae7b91db93d0b00745/cupy/_core/_routines_math.pyx#L920-L924
