### ISSUE TITLE
remove unnecessary copies when multiplying matrices

### ISSUE THREAD

**Issue by zermelofraenkel** [cupy/cupy#6021]
### Description

After looking into `gemm`, it seems that the current code relies on `flags.c_contiguous` and `flags.f_contiguous` to determine whether a copy is necessary. However, an array with a stride of 1 itemsize in any dimension can be handled directly by cublas.
For example
```
cp.empty(5, 4)
```
will create a c-contiguous array with strides (80, 8), but:
```
cp.empty(5, 4)[:, :3]
```
is neither c nor f contiguous, despite having the same stride as the array above.
The BLAS routines have a concept of stride which is different from the shape. As long as one of the stride is 1, BLAS does not require a copy.

For a multiplication of a 10,000 x 10,000 matrix by a 10,000 vector, the cost is 5x vs using `gemv` and avoiding the copy. This ratio increases with the size of the matrices. For 1,000 x 1,000 matrices, it is 2x. For 100 x 100 matrices, it is 15%.

**Comment by leofang** [comment]
> For a multiplication of a 10,000 x 10,000 matrix by a 10,000 vector, the cost is 5x vs using `gemv` and avoiding the copy. This ratio increases with the size of the matrices. For 1,000 x 1,000 matrices, it is 2x. For 100 x 100 matrices, it is 15%.

Hi @zermelofraenkel could you provide a reproducer (either a patch or a script is fine) for us to verify and analyze? Thanks!

**Comment by kmaehashi** [comment]
Closing as inactive for a while. Please feel free to reopen if you still need help.
