### ISSUE TITLE
Infer ROCM_HOME from `hipcc` command

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#6033]
When building CuPy from source in ROCm environment, if `ROCM_HOME` is not set, users will get `Please install hipCUB and retry` error even if hipCUB is installed. The message should be friendlier, and it's better to automatically infer ROCM_HOME from `hipcc` like we do for `nvcc` and `CUDA_PATH`.

https://github.com/cupy/cupy/blob/master/install/cupy_builder/install_build.py#:~:text=def%20get_rocm_path()%3A,global%20_rocm_path

**Comment by Subhraneel77** [comment]
@kmaehashi Can I work to resolve this issue?

**Comment by kmaehashi** [comment]
@Subhraneel77 Sure, go ahead. (You will need a working ROCm environment to verify this)

**Comment by Davidportlouis** [comment]
@kmaehashi  Can I work on this issue ?

**Comment by kmaehashi** [comment]
Sorry but this issue is no longer valid as of #6605.
