### ISSUE TITLE
Installation fails on Windows 10 x64 with Visual Studio 2017

### ISSUE THREAD

**Issue by zimmerrol** [cupy/cupy#604]
I am trying to install `cupy` via `pip` on a machine running Windows 10 x64. Sadly, the installation process fails with this log:

> C:\Users\*>pip install git+https://github.com/cupy/cupy.git
Collecting git+https://github.com/cupy/cupy.git
  Cloning https://github.com/cupy/cupy.git to c:\users\*\appdata\local\temp\pip-5fip3fsb-build
    Complete output from command python setup.py egg_info:
    ******************
    * WARNING: Cannot find nvToolsExt. nvtx was disabled.
    ******************
    Options: {'annotate': False, 'linetrace': False, 'profile': False, 'no_cuda': False}
    Include directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\include', 'C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\include']
    Library directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\lib\\x64', 'C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\lib\\x64']
    command 'cl.exe' failed: No such file or directory
    ******************
    * WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
    * WARNING: Skip installing cuda support
    * WARNING: Check your CFLAGS environment variable
    ******************
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\*\AppData\Local\Temp\pip-5fip3fsb-build\setup.py", line 32, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "C:\Users\*\AppData\Local\Temp\pip-5fip3fsb-build\cupy_setup_build.py", line 373, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "C:\Users\*\AppData\Local\Temp\pip-5fip3fsb-build\cupy_setup_build.py", line 266, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.
----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in C:\Users\*\AppData\Local\Temp\pip-5fip3fsb-build\

If I try to perform the installation not from `git` but only with `pip install cupy` the same error arises. Eventhough the setup complains about missing include files, all of the listed headers exist in the mentioned directories.

The same error occurs while installing `cupy` on a different machine running Windows 10 x64 with Visual Studio 2017 and CUDA 8.0 instead of CUDA 9.0.

Is this a fault of my two systems, or is there something broken with `cupy`?

**Comment by zzf123000** [comment]
My system info:
windows10
Visual Studio 2017
CUDA 9.0.176

run : python setup.py install 

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\um\x64" C:\Users\ZZF123~1\AppData\Local\Temp\tmpqh9ky5cd\Users\ZZF123~1\AppData\Local\Temp\tmpqh9ky5cd\a.obj /OUT:C:\Users\ZZF123~1\AppData\Local\Temp\tmpqh9ky5cd\a.exe /MANIFEST
正在生成代码
已完成代码的生成
building 'cupy.core.core' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

help me!

**Comment by bkvogel** [comment]
I had a similar problem and resolved it using the following:
https://stackoverflow.com/questions/43847542/rc-exe-no-longer-found-in-vs-2015-command-prompt

**Comment by FlashTek** [comment]
After making sure, that the v140 C++ compiler was correctly setup together with `Cuda` i re-ran the installation command, and get [this ](https://gist.github.com/FlashTek/75e751fa308ed529315f58bc7fb4e864)output.

Sadly, even though pip finishes the installation, it is not working, is executing `import cupy as cp` causes a `DLL load failed: the module could not be found` error.

**Comment by zzf123000** [comment]
Install cupy correctly, for example: 
Using c:\anaconda3\lib\site-packages
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using c:\anaconda3\lib\site-packages
Searching for numpy==1.13.3
Best match: numpy 1.13.3
Adding numpy 1.13.3 to easy-install.pth file

Using c:\anaconda3\lib\site-packages
Searching for nose==1.3.7
Best match: nose 1.3.7
Adding nose 1.3.7 to easy-install.pth file

Using c:\anaconda3\lib\site-packages
Finished processing dependencies for cupy==3.0.0a1

But when  import cupy  there is an error: 
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 10:25:46) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cupy
Traceback (most recent call last):
  File "F:\cupy-master\cupy-master\cupy\__init__.py", line 9, in <module>
    from cupy import core  # NOQA
  File "F:\cupy-master\cupy-master\cupy\core\__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: cannot import name 'core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\cupy-master\cupy-master\cupy\__init__.py", line 20, in <module>
    six.reraise(ImportError, ImportError(msg), exc_info[2])
  File "C:\Anaconda3\lib\site-packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "F:\cupy-master\cupy-master\cupy\__init__.py", line 9, in <module>
    from cupy import core  # NOQA
  File "F:\cupy-master\cupy-master\cupy\core\__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: CuPy is not correctly installed. Please check your environment, uninstall CuPy and reinstall it with `pip install cupy --no-cache-dir -vvvv`.

original error: cannot import name 'core'

到底是什么原因？？？？？？？？？？？？？？？？

**Comment by zzf123000** [comment]
What's the cause? ？？？？？？？？？？？？？

**Comment by zzf123000** [comment]
Modification: cupy_setup_build.py for: 
row   4:from distutils import _msvccompiler
row 456:class _MSVCCompiler(_msvccompiler.MSVCCompiler):
row 501:        other_objects = _msvccompiler.MSVCCompiler.compile(

You can compile and install correctly, but generate the above errors when executing import cupy instructions.

**Comment by zzf123000** [comment]
pip uninstall cupy
Can't uninstall 'cupy'. No files were found to uninstall.

**Comment by zzf123000** [comment]
I'm a green hand, I'm sorry!           The above error is my own annoyance, quit the work directory and import cupy success!

**Comment by zzf123000** [comment]
哈哈！！！拜拜！！！！

**Comment by normalworld** [comment]
Modification: cupy_setup_build.py for:
row 4:from distutils import _msvccompiler
row 456:class _MSVCCompiler(_msvccompiler.MSVCCompiler):
row 501: other_objects = _msvccompiler.MSVCCompiler.compile(
whether it works? thank you!

**Comment by lucifer2859** [comment]
Hello @zzf123000 , I meet the same problem with you, how do you deal with the problem 14.0 is required

**Comment by IwraStudios** [comment]
Quick & Dirty fix for VS 2017:
add
```py
    CFLAGS = os.environ.get('CFLAGS', '(none)')
    
    for flag in CFLAGS.split(';'):
        if flag.startswith('-I'):
            include_dirs.append(flag[3:-1]) # Account of quotes
        if flag.startswith('-L'):
            library_dirs.append(flag[3:-1])
        print(flag)
    print(CFLAGS)
```
to build.py get_compiler_settingunderneath  `define_macros = []`

Set env var CFLAGS to match `-I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include";-L"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\lib\x64"`
