### ISSUE TITLE
Doc: move Compatibility Matrix table to the Upgrade Guide

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#6044]
Add https://github.com/cupy/cupy/wiki/Compatibility-Matrix at the top of https://docs.cupy.dev/en/latest/upgrade.html.

**Comment by SwastikTripathi** [comment]
Hi. I think we can create a new table in upgrade.html, and put the matrix there. It should be a few lines of simple code.
Can you assign me this?

**Comment by kmaehashi** [comment]
Thanks @SwastikTripathi, go ahead!

**Comment by SwastikTripathi** [comment]
I've updated the doc, and created a PR. Please check it

**Comment by kmaehashi** [comment]
Closed via #6053
