### ISSUE TITLE
reduction behavior is different from numpy for non-contiguous arrays

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#605]
Currently the following unit test is failing (note: the unit test is annotated with `testing.slow`).

https://github.com/cupy/cupy/blob/fed8d1375a0a5bdff5f52ef1a2dd6ae8a1b1aa89/tests/cupy_tests/math_tests/test_sumprod.py#L51-L57

```
======================================================================
FAIL: test_sum_axis_huge (test_sumprod.TestSumprod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/cupy/cupy/testing/helper.py", line 125, in test_func
    check_func(cupy_result, numpy_result)
  File "/work/cupy/cupy/testing/helper.py", line 194, in check_func
    c.flags.f_contiguous, n.flags.f_contiguous))
AssertionError: The state of f_contiguous flag is false. (cupy_result:False numpy_result:True)
```

It seems that numpy's iterator and [cupy's reduction routine](https://github.com/cupy/cupy/blob/fed8d1375a0a5bdff5f52ef1a2dd6ae8a1b1aa89/cupy/core/reduction.pxi#L206) behaves differently for noncontiguous arrays.

The minimal code to reproduce this issue:

```py
import numpy as np
import cupy as cp

def f(xp):
  a = xp.broadcast_to(xp.ndarray((3, 1, 2)), (3, 2, 2))
  return a, a.sum(axis=0)

print(f(np)[1].flags)
print(f(cp)[1].flags)
```

`f(np)` / `f(cp)` return F-contiguous / C-contiguous array, resp.

**Comment by niboshi** [comment]
Closing as we do not guarantee compatibility of strides:  #2717
