### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [cupy/cupy#6061]
### Description

:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/cupy/lokal -name '*.py')
```

**Comment by emcastillo** [comment]
There are several restrictions that prevent us from using augmented assigned operators due to the use of in-place operations in the GPU memory.

Thank you for your suggestion!

**Comment by elfring** [comment]
* How do you think about to check the applicability of in-place modifications in more detail?
* Can any assignment statements be reconsidered if it can be determined that they would not affect GPU data processing?

**Comment by kmaehashi** [comment]
Simply rewriting the code with regex doesn't work.

(1) As Emilio said, some are intentionally using simple assignment statements to make a copy.
(2) Rewriting may change the order of calculation and affect precision/casting/performance.

So these changes will need a very careful review than it looks.

> 👀 Some source code analysis tools can help to find opportunities for improving software components.

> How do you think about to check the applicability of in-place modifications in more detail?

I'm interested in which tool suggests the use of augmented assignment statements.

**Comment by elfring** [comment]
>So these changes will need a very careful review …

This is usual, isn't it? :thinking:


>I'm interested in which tool suggests the use of augmented assignment statements.

:thought_balloon: Would you find any adjustment suggestions eventually applicable from the shown Perl command example?
