### ISSUE TITLE
cuda11.6 support - already supported? 

### ISSUE THREAD

**Issue by waterwheel31** [cupy/cupy#6069]
### Description

I know cupy recently supported cuda11.5, but I would like Cupy supports cuda 11.6 earlier. 

By the way, I have found a cuda116 version on Tsinghua univ. website. Is this official? 11.6 is already supported? 
 https://pypi.tuna.tsinghua.edu.cn/simple/cupy-cuda116/

**Comment by kmaehashi** [comment]
We'll support CUDA 11.6 once it is released.

> https://pypi.tuna.tsinghua.edu.cn/simple/cupy-cuda116/

This is a stub sdist file that was already removed from the official PyPI. It's a legit package released by the CuPy project, but nothing is in it.
