### ISSUE TITLE
Compilation time is inconsistent between different environments

### ISSUE THREAD

**Issue by mlazzarin** [cupy/cupy#6139]
### Description

I'm working on a project that uses CuPy to accelerate quantum computing simulations.
We employ CuPy with custom CUDA kernels loaded with RawModule.
We are trying to benchmark our code to assess the JIT approach with respect to alternatives.
During benchmarks, we found out that the compilation times are inconsistent between different versions of CuPy and CUDA.

For example, I've written a gist https://gist.github.com/mlazzarin/1e2128e90d78c4cb1a220075f64bc297 that loads our custom kernels with ``cp.RawModule`` and compile them with ``.compile()`` method.
I tried to run such example with different versions of CuPy and CUDA toolkit:

| Environment                                                                             | Compilation time |
| -------------------------------------------------------------------------------- | ---------------------- |
| System installation of CUDA 11.5, ``cupy-cuda115`` from pip | ~ 3.2 s                 |
| ``cudatoolkit=11.5.0`` and ``cupy=9.6.0`` from conda-forge    | ~ 3.2 s                 |
| ``cudatoolkit=11.4.2`` and ``cupy=9.6.0`` from conda-forge    | ~ 3.2 s                 |
| ``cudatoolkit=11.3.1`` and ``cupy=9.6.0`` from conda-forge    | ~ 3.2 s                 |
| ``cudatoolkit=11.2.2`` and ``cupy=9.6.0`` from conda-forge    | ~ 3.4 s                 |
| ``cudatoolkit=11.1.1`` and ``cupy=9.6.0`` from conda-forge    | ~ 1.6 s                 |
| ``cudatoolkit=11.5.0`` and ``cupy=9.5.0`` from conda-forge    | ~ 2.1 s  (3.2 s first exec) |
| ``cudatoolkit=11.4.2`` and ``cupy=9.5.0`` from conda-forge    | ~ 2.1 s  (3.2 s first exec) |
| ``cudatoolkit=11.3.1`` and ``cupy=9.5.0`` from conda-forge    | ~ 2.1 s  (3.2 s first exec) |
| ``cudatoolkit=11.2.2`` and ``cupy=9.5.0`` from conda-forge    | ~ 2.3 s  (3.5 s first exec) |
| ``cudatoolkit=11.1.1`` and ``cupy=9.5.0`` from conda-forge    | ~ 1.0 s  (1.7 s first exec) |

We also found out that the first execution with CuPy v9.5.0 is slower than the following ones, while this doesn't happen with CuPy v9.6.0. This holds for the very first execution in a new environment.

Is this expected?

**Comment by kmaehashi** [comment]
Do you use compute capability 8.6 GPU?
These results might be affected by https://github.com/cupy/cupy/pull/6004 and https://github.com/cupy/cupy/pull/6024 .

**Comment by mlazzarin** [comment]
Yes, I forgot to mention my configuration, sorry.

OS: Ubuntu 20.04.3 LTS
CPU: AMD EPYC 7742
GPU: NVIDIA RTX A6000 (compute capability 8.6)
Driver version: 495.29.05

I also have access to some NVIDIA Tesla V100, with compute capability 7.0, I may try to see if the problem appears with them.

**Comment by leofang** [comment]
Measuring the compilation time is something nontrivial. Both CuPy and the CUDA driver have their own caching mechanism, so without ensuring the cache is empty it could impact the result by a lot. 

In CuPy, you need to make sure $CUPY_CACHE_DIR (default is $HOME/.cupy/kernel_cache) is empty. For the CUDA driver, check out the compilation-related env vars: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars.

**Comment by mlazzarin** [comment]
Thank you. I measured the compilation times again, with two different machines:

OS: Ubuntu 20.04.3 LTS
CPU: AMD EPYC 7742
GPU: NVIDIA RTX A6000 (compute capability 8.6)
Driver version: 495.29.05

| Environment                                                                             | CUDA_CACHE_DISABLE=0 | CUDA_CACHE_DISABLE=1 |
| -------------------------------------------------------------------------------- | --------- | --------- |
| System installation of CUDA 11.5, ``cupy-cuda115`` from pip | ~ 3.2 s | ~ 3.2 s |
| ``cudatoolkit=11.5.0`` and ``cupy=9.6.0`` from conda-forge    | ~ 3.2 s | ~ 3.2 s |
| ``cudatoolkit=11.4.2`` and ``cupy=9.6.0`` from conda-forge    | ~ 3.2 s | ~ 3.2 s |
| ``cudatoolkit=11.3.1`` and ``cupy=9.6.0`` from conda-forge    | ~ 3.2 s | ~ 3.2 s |
| ``cudatoolkit=11.2.2`` and ``cupy=9.6.0`` from conda-forge    | ~ 3.4 s | ~ 3.4 s |
| ``cudatoolkit=11.1.1`` and ``cupy=9.6.0`` from conda-forge    | ~ 1.6 s | ~ 1.6 s |
| ``cudatoolkit=11.5.0`` and ``cupy=9.5.0`` from conda-forge    | ~ 2.1 s | ~ 3.2 s |
| ``cudatoolkit=11.4.2`` and ``cupy=9.5.0`` from conda-forge    | ~ 2.1 s | ~ 3.2 s |
| ``cudatoolkit=11.3.1`` and ``cupy=9.5.0`` from conda-forge    | ~ 2.1 s | ~ 3.2 s |
| ``cudatoolkit=11.2.2`` and ``cupy=9.5.0`` from conda-forge    | ~ 2.3 s | ~ 3.5 s |
| ``cudatoolkit=11.1.1`` and ``cupy=9.5.0`` from conda-forge    | ~ 1.0 s | ~ 1.7 s |

OS: Ubuntu 20.04.3 LTS
CPU: Intel(R) Xeon(R) E5-2698 v4 @ 2.20GHz
GPU: 4x NVIDIA Tesla V100 (compute capability 7.0)
Driver version: 460.91.03

| Environment                                                                             | CUDA_CACHE_DISABLE=0 | CUDA_CACHE_DISABLE=1 |
| -------------------------------------------------------------------------------- | --------- | --------- |
| ``cudatoolkit=11.5.0`` and ``cupy=9.6.0`` from conda-forge    | ~ 4.5 s | ~ 4.5 s |
| ``cudatoolkit=11.4.2`` and ``cupy=9.6.0`` from conda-forge    | ~ 4.4 s | ~ 4.4 s |
| ``cudatoolkit=11.3.1`` and ``cupy=9.6.0`` from conda-forge    | ~ 4.4 s | ~ 4.4 s |
| ``cudatoolkit=11.2.2`` and ``cupy=9.6.0`` from conda-forge    | ~ 4.6 s | ~ 4.6 s |
| ``cudatoolkit=11.1.1`` and ``cupy=9.6.0`` from conda-forge    | ~ 2.3 s | ~ 2.3 s |
| ``cudatoolkit=11.5.0`` and ``cupy=9.5.0`` from conda-forge    | ~ 4.5 s | ~ 4.5 s |
| ``cudatoolkit=11.4.2`` and ``cupy=9.5.0`` from conda-forge    | ~ 4.4 s | ~ 4.4 s |
| ``cudatoolkit=11.3.1`` and ``cupy=9.5.0`` from conda-forge    | ~ 4.4 s | ~ 4.4 s |
| ``cudatoolkit=11.2.2`` and ``cupy=9.5.0`` from conda-forge    | ~ 4.6 s | ~ 4.6 s |
| ``cudatoolkit=11.1.1`` and ``cupy=9.5.0`` from conda-forge    | ~ 2.3 s | ~ 2.3 s |

I tried also the manually remove ``$HOME/.cupy/kernel_cache/`` before each test, but I don't see any difference. Maybe it's because I'm compiling with ``cp.RawModule.compile()``?

With both configurations, compilation times with CUDA v11.1.1 are nearly half the others. ``CUDA_CACHE_DISABLE`` seems to matter only in some configurations.

**Comment by emcastillo** [comment]
cc @anaruse

**Comment by keckj** [comment]
RawModule and RawKernel are not cached by cupy when using the nvrtc backend. Currently, this is required to get back the C++ mangled names that we pass in `name_expressions` (see `cupy/cuda/compiler.py:547`).

**Comment by leofang** [comment]
> RawModule and RawKernel are not cached by cupy when using the nvrtc backend. 

No that's not true, they are cached when things go through `cupy/cuda/compiler.py`.

@mlazzarin I thought about it carefully and most things can be explained:
- On the mismatch with regard to `CUDA_CACHE_DISABLE` on A6000 + CuPy v9.5.0: it's expected as PTX instead of CUBIN is generated (fixed in #6024 for v9.6.0)
- On the match with regard to `CUDA_CACHE_DISABLE` in other cases: if CUBIN is generated, the driver does not have to do any PTX compilation so whether or not the (driver) cache is disabled doesn't really matter

The only mystery I am still wondering is the mismatch between CUDA 11.1 and later CUDA versions.

**Comment by kmaehashi** [comment]
> > RawModule and RawKernel are not cached by cupy when using the nvrtc backend.
> 
> No that's not true, they are cached when things go through `cupy/cuda/compiler.py`.

The only situation disk cache in CuPy does not work is `nvrtc` backend AND `name_expressions` are specified.

> The only mystery I am still wondering is the mismatch between CUDA 11.1 and later CUDA versions.

I know that nvcc comes with CUDA 11.1 behaves differently than the one that comes with 11.0 and 11.2+. Interestingly, nvcc 11.1 builds faster but generates a larger binary than others. I m unsure this applies to NVRTC, but I guess so according to the benchmark.

@mlazzarin Anyway, the codepath in CuPy is the same between CUDA 11.1 and onwards, so I think this is unlikely a CuPy bug. I'd suggest to forget about past CUDA releases :)

**Comment by leofang** [comment]
> > > RawModule and RawKernel are not cached by cupy when using the nvrtc backend.
> > 
> > No that's not true, they are cached when things go through `cupy/cuda/compiler.py`.
> 
> The only situation disk cache in CuPy does not work is `nvrtc` backend AND `name_expressions` are specified.

Ah, OK, I didn't pay attention to the linked gist and so missed the context about `name_expressions`, sorry @keckj you were right.

**Comment by keckj** [comment]
I wasn't aware that `name_expressions` could be empty, so you were right too ! It would be nice to have caching for raw kernels that are not declared `extern "C"`. See linked PR for a possible implementation.

**Comment by mlazzarin** [comment]
Ok, thank you very much!
