### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [cupy/cupy#6157]
On aarch64, `pip install cupy-cuda100` and `pip install cupy-cuda101` give the following errors:

```
ERROR: Could not find a version that satisfies the requirement cupy-cuda100 (from versions: none)
ERROR: No matching distribution found for cupy-cuda100
```

```
ERROR: Could not find a version that satisfies the requirement cupy-cuda101 (from versions: none)
ERROR: No matching distribution found for cupy-cuda101
```

@kmaehashi , Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by emcastillo** [comment]
We currently distribute binary wheels for jetson devices `pip install cupy-cuda112 ​​-f https://pip.cupy.dev/pre`

**Comment by kmaehashi** [comment]
Thanks for the feedback! CUDA 10.0/10.1 support has been dropped in CuPy v10 (#5717) so we have no plan to release wheels for legacy JetPacks (2019 or earlier). Upgrading JetPack is the best option here, but you can also build CuPy v9 from source on CUDA 10.0 + aarch64.
