### ISSUE TITLE
JIT: support `if` comparison with float32 and python constant

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#6223]
### Description

```py
a = cupy.array([0.4, -0.2, 1.8, -1.2], dtype=cupy.float32)
relu = cupy.vectorize(lambda x: x if (x > 0.0) else 0.0)
print(relu(a))
```

This fails with:

```
TypeError: Type mismatch in conditional expression.: float32 != float64
```

I expect constant dtype to be determined dynamically based on other operands' dtype.

### Environment

```
# Paste the output here
```

**Comment by asi1024** [comment]
In NumPy, the dtype of the return value is inferred from the result of the first element.
```python
import numpy as np

relu = np.vectorize(lambda x: x if (x > 0.0) else 0.0)

a = np.array([0.4, -0.2, 1.8, -1.2], dtype=np.float32)
print(relu(a).dtype)  # float32
a = np.array([-1.0, 0.4, -0.2, 1.8], dtype=np.float32)
print(relu(a).dtype)  # float64
```

**Comment by leofang** [comment]
Just FYI, value-based casting and behaviors were strongly opposed in the Array API discussions. I think it is a consensus that future array libraries should avoid implementing such behaviors. Though NumPy cannot make any change in the near future...
