### ISSUE TITLE
compile_with_cache no longer returns result

### ISSUE THREAD

**Issue by kmatzen** [cupy/cupy#6231]
I think there was a mistake when this function was refactored to include the deprecation message.  Previously, it returned the compilation result.  Now it calls `_compile_module_with_cache`, but the return value is ignored.

**Comment by sniklaus** [comment]
Commit that introduce this bug: https://github.com/cupy/cupy/commit/8a630902eca80c9c3125e0ed1131572faa3f7a71

**Comment by kmaehashi** [comment]
Thanks for reporting, will be fixed in #6232.
