### ISSUE TITLE
Make CuPy stream hashable?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#6243]
### Description

This observation was made internally by @mtjrider:
```python
>>> import torch
>>> s=torch.cuda.Stream()
>>> hash(s)
-181027509999151647
>>>
>>> import cupy as cp
>>> s = cp.cuda.Stream()
>>> hash(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'Stream'
```
It would be nice to make it hashable because, for example, then streams can be used as keys for a mapping to parallel workloads, which is currently not possible with CuPy streams:
```python
>>> s1 = cp.cuda.Stream()
>>> s2 = cp.cuda.Stream()
>>> map = {s1: 1, s2: 2}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'Stream'
```

**Comment by kmaehashi** [comment]
Sounds good to make it hashable.

* PyTorch seems using `hash((stream_ptr, device_id))` but I think just using `hash(stream_ptr)` is enough:
https://github.com/pytorch/pytorch/blob/8fb9ce49276feee65e29c2f85f3efa1d3fe4d8f8/torch/cuda/streams.py#L105-L106
* Need to fix `__eq__` to check if `other` is a CuPy stream instance.

**Comment by leofang** [comment]
Can't we just use the stream pointer address as the hash value?
