### ISSUE TITLE
ModuleNotFoundError: No module named 'cupy.cuda.cublas'

### ISSUE THREAD

**Issue by fmbao** [cupy/cupy#6248]
### Description

when i use this py file. 
fgnt/chainer_extensions/sequence_linear.py", line 7, in <module>
    from cupy.cuda.cublas import sgemm
It produce issue.

### To Reproduce

```py
# Write the code here
```

### Environment

```
# Paste the output here
```

**Comment by fmbao** [comment]
upuupupupupupup

**Comment by kmaehashi** [comment]
Chainer v7.x requires CuPy v7.x. Chainer may not work with CuPy v8+ and onwards.
