### ISSUE TITLE
Implement `overwrite_input` option in `cupy.{percentile,quantile}`

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#6256]
### Description

Change the signature of `cupy.{percentile,quantile}` to provide exactly the same API as NumPy.

I think it's ok to implement `overwrite_input ` as nop (just ignore the option).

**Comment by saswatpp** [comment]
Can i work on this ?

**Comment by kmaehashi** [comment]
@saswatpp Sure, please go ahead.

**Comment by kmaehashi** [comment]
Implemented via #6298. Thanks, @saswatpp!
