### ISSUE TITLE
can't compile with cupy.RawModule when the kernel_source use 'shfl_down_sync'

### ISSUE THREAD

**Issue by johnzlli-tencent** [cupy/cupy#6262]
### Description

I write a cuda c style kernel with 'shil_down_sync'. And i want call this kernel with cupy.RawModule，it raise this errer
![image](https://user-images.githubusercontent.com/38726413/147031495-86b80d55-16ab-41bd-8b61-64a2b63e6193.png)

### To Reproduce

```py
kernel_source = r'''
extern "C" {
__global__ void kernel() {
    ...
    __shlf_down_sync();
    ...
}

}
'''

module = cupy.RawModule(code = kernel_source)
kernel = module.get_function('kernel')
kernel(...)

```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
![image](https://user-images.githubusercontent.com/38726413/147031917-3210301b-e824-4857-a234-d3cf50692c47.png)

```

**Comment by johnzlli-tencent** [comment]
![image](https://user-images.githubusercontent.com/38726413/147031955-183e424f-8185-4e2a-8d39-c19724e392e8.png)
Environment

**Comment by leofang** [comment]
Shouldn't it be `__shfl_down_sync`? (Note the spelling.)

**Comment by johnzlli-tencent** [comment]
> Shouldn't it be `__shfl_down_sync`? (Note the spelling.)

Yes, you are right. It's my fault.
