### ISSUE TITLE
Cupy arrays converting bugs,i dont know how should i fix that

### ISSUE THREAD

**Issue by RosterMouch** [cupy/cupy#6284]
### Description

Hi there,i dont know why my python code doesnt work to covert a list object to cupy array.
Trouble Here:
ORIGIN_LIST = [10010000111100000001, 11110010010100011010, 10000111100011111001, 10001011101110000001, 10000111101000011110, 100101011[11011000100111011101, 10110010111001000000, 10111111011100001100, 10001110011010111000, 10001010101100000011, 11000000011101001010, 10010110001010110011, 10101000100100001111, 11011011010101000011, 10111101101110111101]
AFTER_cupy.array() = [11011000100111011101 10110010111001000000 10111111011100001100 10001110011010111000 10001010101100000011 11000000011101001010
 10010110001010110011 10101000100100001111 11011011010101000011 10111101101110111101]

------------------------------------------------------------

yeh you see,the ',' were gone,and i m sure this is not a cupy array,so how should i fix that.I m rencently try to make a mining script for scalable gpu array studying.And my code is under below

### To Reproduce

```py
# Write the code here
def main(self):
        process_count = 0
        while True:
            process_count += 1
            zerocount = []
            limitationproof = []
            hashmentArray = self.hashprocess()
            for i in range(len(hashmentArray)):
                zerocount.append(cp.count_nonzero(i))
                if self.limitation in self.hashprocess()[1][i]:
                    limitationproof.append(True)
            zerocount = cp.array(zerocount)
            limitationproof = cp.array(limitationproof)
            try:
                if cp.where(cp.max(zerocount),zerocount)[0]  == cp.where(True,limitationproof)[0]:
                    print(f"Current {process_count / 10000000} MH/s，Result：{hashmentArray[cp.where(cp.max(zerocount),zerocount)[0]]}")
                else:
                    print(f"Current：{process_count / 10000000} MH/s，Result：{None}")
            except Exception:
                print(f"Current：{process_count / 10000000} MH/s，Result：{None}")
```

### Environment

```
# Paste the output here
OS : Windows11
CUDA_DRIVER： 11.4
Python_VERSION：3.8.5(Based on Conda)
```

**Comment by toslunar** [comment]
Could you minimize the reproduction code?  The issue seems the difference between `__repr__` and `__str__`, which is expected and the same as NumPy.

**Comment by kmaehashi** [comment]
Closing, feel free to reopen if we need further discussion :)

**Comment by RosterMouch** [comment]
> Could you minimize the reproduction code? The issue seems the difference between `__repr__` and `__str__`, which is expected and the same as NumPy.

Thanks and i fix it
