### ISSUE TITLE
Stream capture error in ROCm tests

### ISSUE THREAD

**Issue by emcastillo** [cupy/cupy#6295]
https://jenkins.preferred.jp/job/chainer/job/cupy_master/TEST=rocm-4-0,label=mnj-mi50/1919/console

```
 E   RuntimeError: streamIsCapturing is supported since CUDA 10.1+
```

**Comment by leofang** [comment]
Hmmm how come Jenkins didn't complain at all in the PR?

**Comment by emcastillo** [comment]
yeah, seems like not all tests are being enforced
