### ISSUE TITLE
Installation instructions for Colab environments

### ISSUE THREAD

**Issue by yaroslavvb** [cupy/cupy#6299]
### Description

I'm wondering if you could installation instructions optimized for [Colab](https://colab.research.google.com/). Colab takes seconds to spin up, but cupy installation is >10 minutes, so it's a barrier to some quick experimentation.

I found the following works, but it takes >10 minutes, mostly due to cudatoolkot download. Cuda should already be available on Colab environments...

```
!python -m pip install -U setuptools pip
!python -m cupyx.tools.install_library --cuda 11.2 --library cutensor

!pip install -q condacolab
import condacolab
condacolab.install()

!conda --version
 !conda install -c conda-forge cupy cudnn cutensor nccl
```
![Screen Shot 2022-01-10 at 4 04 02 PM](https://user-images.githubusercontent.com/23068/148858382-cf614bb4-6299-4d9c-8b65-bd01951312a2.png)

**Comment by leofang** [comment]
You don't have to install the optional packages (cudnn cutensor nccl) if you don't need them. That said, downloading `cudatoolkit` from conda-forge is probably the most time consuming part in the whole process due to its size.

**Comment by emcastillo** [comment]
colab has cupy-cuda111==9.4.0

You can do `!pip install  cupy-cuda111 --upgrade` and it should work, I just verified it.

**Comment by yaroslavvb** [comment]
BTW, I noticed that CUPY used to be part of Colab env -- https://github.com/chainer/google-colaboratory. I wonder who set up that collaboration/who the point person was on Colab side, maybe that can be resurrected

<img width="659" alt="Screen Shot 2022-01-10 at 4 44 45 PM" src="https://user-images.githubusercontent.com/23068/148861601-2348b134-ef82-47c2-b0ea-fe41dc20b0b6.png">

**Comment by emcastillo** [comment]
Are you changing the notebook runtime to be GPU backed? maybe that's why you didn't have cuda enabled.

**Comment by yaroslavvb** [comment]
You are right.....silly mistake on my part, it does have Cupy after all! Thanks for the upgrade command

**Comment by yaroslavvb** [comment]
The slowness turns out to be due to cuTensor install, not CuPY
```
!conda install -c conda-forge cutensor
```
