### ISSUE TITLE
Adding `scipy.spatial.distance.cdist` & `scipy.spatial.distance.pdist`

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#6307]
### Description

Would be good to have CuPy implementations of [`scipy.spatial.distance.cdist`]( https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html ) and [`scipy.spatial.distance.pdist`]( https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html ). This would allow for fast distance computations with CuPy.

**Comment by jakirkham** [comment]
cc @quasiben @gigony @grlee77

**Comment by cjnolet** [comment]
We are currently working to expose much of the scipy.spatial.distance package through RAFT into cupy.

**Comment by jakirkham** [comment]
That's great news Corey! 🎉 Was actually just mentioning to Ben offline that we might want to ask you if you had thoughts here 😄

**Comment by cjnolet** [comment]
Here's the related issue: https://github.com/cupy/cupy/issues/5946

**Comment by jakirkham** [comment]
Oops 😅 Didn't realize there was already an issue. Let's close here and follow up there 🙂
