### ISSUE TITLE
Import error when import cupy

### ISSUE THREAD

**Issue by lfgogogo** [cupy/cupy#6325]
### Description

Hello,i have got a error when loading cupy,i install cupy using command pip install cupy-cuda111.
Here is the error message.Please help!
Python 3.8.0 (default, Nov 6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.

import cupy
Traceback (most recent call last):
File "D:\Anaconda3\envs\ll\lib\site-packages\cupy_init_.py", line 18, in
from cupy import core # NOQA
File "D:\Anaconda3\envs\ll\lib\site-packages\cupy_core_init.py", line 1, in
from cupy._core import core # NOQA
File "cupy_core\core.pyx", line 1, in init cupy.core.core
File "D:\Anaconda3\envs\ll\lib\site-packages\cupy\cuda_init.py", line 8, in
from cupy.cuda import compiler # NOQA
File "D:\Anaconda3\envs\ll\lib\site-packages\cupy\cuda\compiler.py", line 13, in
from cupy.cuda import device
File "cupy\cuda\device.pyx", line 1, in init cupy.cuda.device
ImportError: DLL load failed while importing runtime: 找不到指定的模块。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "", line 1, in
File "D:\Anaconda3\envs\ll\lib\site-packages\cupy_init_.py", line 20, in
raise ImportError(f'''
ImportError:
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
https://docs.cupy.dev/en/latest/install.html

Original error:
ImportError: DLL load failed while importing runtime: 找不到指定的模块。

**My conda list:**
Package Version

absl-py 0.15.0
aliyun-python-sdk-core 2.13.3
aliyun-python-sdk-core-v3 2.13.32
aliyun-python-sdk-kms 2.15.0
appdirs 1.4.4
astunparse 1.6.3
audioread 2.1.9
bingtts 0.1.6
cachetools 4.2.4
certifi 2021.10.8
cffi 1.15.0
charset-normalizer 2.0.10
colorama 0.4.4
crcmod 1.7
cryptography 36.0.1
cupy-cuda111 10.0.0
cycler 0.11.0
decorator 5.1.1
defusedxml 0.7.1
fastrlock 0.8
flatbuffers 1.12
gast 0.4.0
google-auth 2.3.3
google-auth-oauthlib 0.4.6
google-pasta 0.2.0
grpcio 1.34.1
h5py 3.1.0
idna 3.3
importlib-metadata 4.10.0
jmespath 0.10.0
joblib 1.1.0
keras-nightly 2.5.0.dev2021032900
Keras-Preprocessing 1.1.2
kiwisolver 1.3.2
librosa 0.8.1
llvmlite 0.37.0
Mako 1.1.6
Markdown 3.3.6
MarkupSafe 2.0.1
matplotlib 3.3.4
networkx 2.6.3
nls 0.0.1
noisereduce 2.0.0
numba 0.54.1
numpy 1.19.3
oauthlib 3.1.1
opt-einsum 3.3.0
oss2 2.13.1
packaging 21.3
Pillow 9.0.0
pip 21.3.1
pooch 1.5.2
protobuf 3.19.3
pyasn1 0.4.8
pyasn1-modules 0.2.8
PyAudio 0.2.11
pycparser 2.21
pycryptodome 3.12.0
pycuda 2021.1
pydub 0.25.1
pyparsing 3.0.6
python-dateutil 2.8.2
python-speech-features 0.6
pytools 2021.2.9
requests 2.27.1
requests-oauthlib 1.3.0
resampy 0.2.2
rsa 4.8
scikit-learn 1.0.2
scipy 1.5.3
setuptools 60.5.0
six 1.15.0
SoundFile 0.10.3.post1
tensorboard 2.7.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit 1.8.1
tensorflow-estimator 2.5.0
termcolor 1.1.0
tflite-runtime 2.5.0
threadpoolctl 3.0.0
torch 1.8.0+cu111
torchaudio 0.8.0
tqdm 4.62.3
trtpy 1.0
typing-extensions 3.7.4.3
urllib3 1.26.8
Werkzeug 2.0.2
wheel 0.37.1
wincertstore 0.2
wrapt 1.12.1
zipp 3.7.0

**My conda info:**
active environment :ll
active env location : D:\Anaconda3\envs\ll
shell level : 2
user config file : C:\Users\lifan.condarc
populated config files : C:\Users\lifan.condarc
conda version : 4.10.1
conda-build version : 3.21.4
python version : 3.8.8.final.0
virtual packages : __cuda=11.1=0
__win=0=0
__archspec=1=x86_64
base environment : D:\Anaconda3 (writable)
conda av data dir : D:\Anaconda3\etc\conda
conda av metadata url : https://repo.anaconda.com/pkgs/main
channel URLs : https://repo.anaconda.com/pkgs/main/win-64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/r/win-64
https://repo.anaconda.com/pkgs/r/noarch
https://repo.anaconda.com/pkgs/msys2/win-64
https://repo.anaconda.com/pkgs/msys2/noarch
package cache : D:\Anaconda3\pkgs
C:\Users\lifan.conda\pkgs
C:\Users\lifan\AppData\Local\conda\conda\pkgs
envs directories : D:\Anaconda3\envs
C:\Users\lifan.conda\envs
C:\Users\lifan\AppData\Local\conda\conda\envs
platform : win-64
user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.8 Windows/10 Windows/10.0.18362
administrator : False
netrc file : None
offline mode : False

### To Reproduce

windows10
python3.8
pip install cupy-cuda111
import cupy

### Installation

Wheel (`pip install cupy-***`)

### Environment

Traceback (most recent call last):
File "D:\Anaconda3\envs\ll\lib\site-packages\cupy_init_.py", line 18, in
from cupy import core # NOQA
File "D:\Anaconda3\envs\ll\lib\site-packages\cupy_core_init.py", line 1, in
from cupy._core import core # NOQA
File "cupy_core\core.pyx", line 1, in init cupy.core.core
File "D:\Anaconda3\envs\ll\lib\site-packages\cupy\cuda_init.py", line 8, in
from cupy.cuda import compiler # NOQA
File "D:\Anaconda3\envs\ll\lib\site-packages\cupy\cuda\compiler.py", line 13, in
from cupy.cuda import device
File "cupy\cuda\device.pyx", line 1, in init cupy.cuda.device
ImportError: DLL load failed while importing runtime: 找不到指定的模块。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "", line 1, in
File "D:\Anaconda3\envs\ll\lib\site-packages\cupy_init_.py", line 20, in
raise ImportError(f'''
ImportError:
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
https://docs.cupy.dev/en/latest/install.html

Original error:
ImportError: DLL load failed while importing runtime: 找不到指定的模块。

**Comment by kmaehashi** [comment]
If you are using conda, we'd suggest using a conda-forge package instead of pypi wheel:
https://docs.cupy.dev/en/latest/install.html#installing-cupy-from-conda-forge

**Comment by ResonancePA** [comment]
Maybe put import torch behind import cupy would help.

**Comment by coderaBruce** [comment]
> Maybe put import torch behind import cupy would help.

This really does work but no idea on why this happens

**Comment by ResonancePA** [comment]
> > Maybe put import torch behind import cupy would help.
> 
> This really does work but no idea on why this happens

I don't understand either LOL.
