### ISSUE TITLE
`cupy.array_api.asarray` doesn't work with list of arrays

### ISSUE THREAD

**Issue by IvanYashchuk** [cupy/cupy#6367]
### Description

CuPy's Array API module doesn't work with lists of arrays, while the main CuPy namespace works fine. `numpy.array_api` also works fine for this usecase.

### To Reproduce

```py
In [1]: import cupy.array_api as xp

In [2]: xp.asarray([xp.ones(5), xp.ones(5)])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-2681967f8885> in <module>
----> 1 xp.asarray([xp.ones(5), xp.ones(5)])

~\mambaforge\envs\scipy-cupy\lib\site-packages\cupy\array_api\_creation_functions.py in asarray(obj, dtype, device, copy)
     81     try:
     82         runtime.setDevice(device.id)
---> 83         res = np.asarray(obj, dtype=dtype)
     84     finally:
     85         runtime.setDevice(prev_device)

~\mambaforge\envs\scipy-cupy\lib\site-packages\cupy\_creation\from_data.py in asarray(a, dtype, order)
     74
     75     """
---> 76     return _core.array(a, dtype, False, order)
     77
     78

cupy\_core\core.pyx in cupy._core.core.array()

cupy\_core\core.pyx in cupy._core.core.array()

cupy\_core\core.pyx in cupy._core.core._array_default()

ValueError: Unsupported dtype object
```

**Comment by IvanYashchuk** [comment]
Seems like accepting the sequence of arrays is actually not specified [by the spec](https://data-apis.org/array-api/latest/API_specification/creation_functions.html#asarray-obj-dtype-none-device-none-copy-none), so probably it's not allowed.

Would be great to raise a more descriptive error message though.

**Comment by kmaehashi** [comment]
Thanks for reporting!

> Seems like accepting the sequence of arrays is actually not specified [by the spec](https://data-apis.org/array-api/latest/API_specification/creation_functions.html#asarray-obj-dtype-none-device-none-copy-none), so probably it's not allowed.
> 
> Would be great to raise a more descriptive error message though.

Agree, better to have a check in the `cupy.array_api` layer.

It seems NumPy's implementation supports constructing an array from sequence of arays:

```py
>>> import numpy.array_api as xp
>>> xp.asarray([xp.ones(5), xp.ones(5)])
Array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float64)
```

**Comment by leofang** [comment]
No I would not interpret this way. Some parts of the spec are permissive, meaning if it doesn't forbid explicitly things that make sense can be allowed. For example in past meetings we've discussed that it is ok to support complex numbers as of today despite most APIs do not specify the behavior yet. The risks are 1. the extended support may not be portable, 2. if it has the potential of being covered in a future spec version, a backward incompatibility might happen up to the future spec.

Back to the use case here, I would think it is an extension of "a (possibly nested) sequence of Python scalars", so supporting it makes sense to me if it is straightforward.
