### ISSUE TITLE
Support `dtype` argument in `cupy.corrcoef` and `cupy.cov`

### ISSUE THREAD

**Issue by emcastillo** [cupy/cupy#6383]
### Description

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

https://docs.cupy.dev/en/stable/reference/generated/cupy.corrcoef.html

Seems args are different

### Additional Information

`dtype` argument added in NumPy version 1.20.

**Comment by kmaehashi** [comment]
@BasLaa yes, please go ahead!

**Comment by BasLaa** [comment]
Will do!

**Comment by emcastillo** [comment]
If you are going to add `dtype` to cov, can you look into adding the other missing kwargs `fweights` and `aweights`?
https://docs.cupy.dev/en/stable/reference/generated/cupy.cov.html
https://numpy.org/doc/stable/reference/generated/numpy.cov.html

Thanks!

**Comment by BasLaa** [comment]
Yep, noticed that as well. Am gunna work on it over the weekend. I'll keep you updated

**Comment by BasLaa** [comment]
#6401 
Hi, 
I have added the pull request here. I have been trying everything I can think of, but I simply have not been able to get cupy to properly run the unit tests, therefore these still need to be added and run. My apologies for this. I think it might just be a compatibility issue with my GPU. Please let me know if I can still help with this in some way. I hope someone else can run the unit tests instead.

**Comment by BasLaa** [comment]
#6401
Hi,
I have added the pull request here. I have been trying everything I can think of, but I simply have not been able to get cupy to properly run the unit tests, therefore these still need to be added and run. My apologies for this. I think it might just be a compatibility issue with my GPU. Please let me know if I can still help with this in some way. I hope someone else can run the unit tests instead.
