### ISSUE TITLE
cupy.cusparse function missing 

### ISSUE THREAD

**Issue by YukeWang96** [cupy/cupy#6410]
### Description

Hi, 

When I check `cupy.cusparse.check_availability('csrmm')` when launching `python3` in the provided docker for `cupy`, it always returned me `False`.

Another thing I found that even if I successfully install the `cupy` by using `pip` outside the docker, the availablility check of `csrmm` or `csrmm2` always return me `False`, is there some key step that I was missing during the installation.

Thanks!

**Comment by kmaehashi** [comment]
csrmm has been removed in CUDA 11.0 and it always returns False if you are using CUDA 11.0+.

https://docs.nvidia.com/cuda/archive/11.0_GA/cuda-toolkit-release-notes/index.html
> CUDA Libraries -- cuSPARSE
> The following functions have been removed:
> Sparse matrix-matrix multiplication: cusparseXcsrmm, cusparseXcsrmm2

**Comment by kmaehashi** [comment]
As quoted above, `csrmm2` is also removed in CUDA 11.0

**Comment by kmaehashi** [comment]
If you need sparse matrix-matrix multiplication in CUDA 11.0+ you need to use generic APIs e.g. SpMM.
