### ISSUE TITLE
Large array std is different from numpy (CPU)

### ISSUE THREAD

**Issue by jalalirs** [cupy/cupy#6425]
I am trying to understand this behavior. When my array gets larger in size, the calculation for std is different from numpy even for obvious or basic array of ones. In fact, the difference between cupy std and numpy std exacerbates for arrays with completely random values. 

```python
import numpy as np
import cupy as cp

cp.cuda.Device(0).use()
x = np.ones((13000000, 269)).astype('f4')
x_cp = cp.array(x)

vcpu = x.std()
vgpu = x_cp.std()
vcpu,vgpu

>>> (0.0, array(0.9225852, dtype=float32))
```

Python version: 3.6
CUDA version: 10.2 & 11.1
cupy version: 9.6.0
OS: RedHat 7.4

**Comment by kmaehashi** [comment]
Thanks for reporting, @jalalirs! The problem should be fixed in the upcoming release this month.
