### ISSUE TITLE
The parameter 'order[0,5]' in cupyx.scipy.ndimage.affine_transform respectively represent？

### ISSUE THREAD

**Issue by 756890911** [cupy/cupy#6478]
### Description

The parameter ‘order[0,5]’ in Cupyx.Scipy.Ndimage.affine_transform is only introduced 0 means nearest neighbor, 1 means linear interpolation. What do the rest of the numbers mean?

### Idea or request for content

What do the rest of the numbers mean?
2:
3:
4:
5:

**Comment by emcastillo** [comment]
From the docs docs:
https://docs.cupy.dev/en/stable/reference/generated/cupyx.scipy.ndimage.affine_transform.html

```
orderint, optional
The order of the spline interpolation, default is 3. The order has to be in the range 0-5.
```

**Comment by 756890911** [comment]
I want to know what these numbers represent. And the corresponding relation of in the opencv
* INTER_NEAREST - a nearest-neighbor Interpolation
* INTER_LINEAR - a Bilinear Interpolation (Used by default)
* Inter_area-resampling using Pixel area relation. It may be a preferred method for image decimation, As it gives moire '-free results. But when the image is zoomed, it is similar to the INTER_NEAREST method.
* INTER_CUBIC - A Bicubic Interpolation over 4x4 Pixel Neighborhood
* INTER_LANCZOS4 - A Lanczos Interpolation over 8x8 Pixel Neighborhood

**Comment by emcastillo** [comment]
There are no corresponding OpenCV values for this, it is just the order of the spline used for the interpolation.
Please read about splines if you are not familiar with them.

Check this SO answer that will give you some context.
https://stackoverflow.com/a/63643155/12353384
