### ISSUE TITLE
vectorize signature error message copy-paste issue

### ISSUE THREAD

**Issue by rogerallen** [cupy/cupy#6485]
### Description

Calling vectorize with a non-None value for the `signature` parameter outputs this error message about the `excluded` parameter. 
```
NotImplementedError: cupy.vectorize does not support `excluded` option currently.
```

Inspecting the code, it is obvious there is a copy-paste error and the 2nd error message should be change excluded to signature.

https://github.com/cupy/cupy/blob/master/cupy/_functional/vectorize.py#L48-L54

```
        if excluded is not None:
            raise NotImplementedError(
                'cupy.vectorize does not support `excluded` option currently.')

        if signature is not None:
            raise NotImplementedError(
                'cupy.vectorize does not support `excluded` option currently.')
```

### To Reproduce

```py
# Write the code here
def foo(a,b):
    return a+b

np.vectorize(foo,signature="(m),(n)->()")
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
N/A

```

**Comment by emcastillo** [comment]
Hi! thank you for reporting this bug!
Would you mind sending a PR for this?

**Comment by rogerallen** [comment]
looks like PR from @tushxr16 fixes this, but It appears it was closed without accepting/merging?  I could be confused...

**Comment by tushxr16** [comment]
Actually, there is a limitation of 79 characters to a line in Python coding style, so I don't know how to proceed with that. Any help?

**Comment by rogerallen** [comment]
Sigh...I guess you could split the string across a line to keep the coding style limit?  E.g.

>>> print("foo"
...       "bar")
foobar

**Comment by tushxr16** [comment]
Hey @rogerallen ! Thanks for the help. I merged my first PR.

**Comment by rogerallen** [comment]
Not sure what the protocol is here, but this looks good to close, I think.
