### ISSUE TITLE
`cupy.cumsum()` doesn't work in ROCm 5.0

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#6517]
Rel #6459.

`cupy.cumsum()` that CuPy independently implements without calling CUB does not work in ROCm 5.0:
```
$ python -c 'import cupy; print(cupy.cumsum(cupy.array([0,0])))'
[                  0 1304722626565153334]
```

The implementation uses shared memory to communicate across threads. As discussed in #4366, in ROCm, threads in a warp run in lock-step at all time so synchronizing instructions in a warp is not required, but we still need to use memory fence to enforce the ordering on access to shared memory.

**Comment by leofang** [comment]
Just curious, so threads march in lock steps, but it doesn't guarantee the memory order? This would explain a lot of weird fixes that @emcastillo had to apply...

**Comment by takagi** [comment]
Yes, I understand so. In the following part of cumsum, for example, the data stored by thread 0 is observed being written by thread 1 is not necessarily before thread 1 observes the memory by the load instruction.
https://github.com/cupy/cupy/blob/812b0f5301de8896f105ed974d84b03fcb331d91/cupy/_core/_routines_math.pyx#L307-L309

I couldn't find its exact explanation in ROCm documentation, but CUDA tells that here:
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#memory-fence-functions

**Comment by emcastillo** [comment]
`syncwarp` doesn't make all the mem stores visible to all the threads in the warp?

**Comment by takagi** [comment]
Does in CUDA, but ROCm doesn't have `syncwarp` so it is defined as nop in Cupy.

**Comment by emcastillo** [comment]
Thanks!
If hip supports memory fences maybe it is better to redefine it as such ..., it will keep the semantics since the warp advances in lock-step
