### ISSUE TITLE
Use `warpSize` to get the warp size in ROCm environment

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#6523]
CuPy, currently, has a hard-coded warp size of 64 for ROCm environment. However, AMD gpu's warp size is not necessarily 64; for example, Navi21 that ROCm 5.0 supports has the warp size of 32. The following can be a good solution.

https://github.com/pytorch/pytorch/blob/2cefbb71cf65696e28ee1bdfce06d6846285e5fb/c10/macros/Macros.h#L322

Thanks @amathews-amd for pointing this out.

**Comment by kmaehashi** [comment]
Are there any code in CuPy that assumes warpSize = 64?

**Comment by takagi** [comment]
Also,
https://github.com/cupy/cupy/blob/eabb8f9792310522f11a6a67f9aab33249f64047/cupy/_core/_routines_math.pyx#L456

**Comment by kmaehashi** [comment]
Bumped the priority to high (https://github.com/cupy/cupy/issues/7234#issuecomment-1377921410). Maybe we can just replace it with `warpSize` for both CUDA and ROCm? I guess PyTorch hard-codes it for compile-time optimization but I think CuPy don't have to care about it as we dynamically compile code into PTX and host compilers are not involved.

**Comment by ajflood** [comment]
@kmaehashi 
Here is my naive solution that worked for what I needed, https://github.com/cupy/cupy/commit/eda2b396a5255e745fc8a5caaa0d7cc621f16073

Let me know if you need anything else from me to get a working solution implemented.

**Comment by kmaehashi** [comment]
Thanks @ajflood! As for `_routines_math.pyx`, `cupy.cuda.device._get_device().attributes` could be better as it caches. JIT is the difficult part as CUDA API calls should not be happen when `import cupy`. Maybe @asi1024 can better follow up here.
