### ISSUE TITLE
Error when installing CuPy from source

### ISSUE THREAD

**Issue by hmtbgc** [cupy/cupy#6527]
I want to contribute to CuPy. So I fork and git clone the repository. When I try "pip install -e ." under "cupy" directory, an issue happens.
<img width="680" alt="error1" src="https://user-images.githubusercontent.com/32740258/156595615-71eff394-d71d-4de9-8fa1-9e2f3ae09c51.PNG">
<img width="689" alt="error2" src="https://user-images.githubusercontent.com/32740258/156595622-ab490d6d-7ada-4eb8-966f-bd5f448c3d54.PNG">
I have checked the previous issues and found some solutions. But I still cannot solve this one.
BTW, I think the [Installing CuPy from Source](https://docs.cupy.dev/en/stable/install.html) is too brief and more instructions should be included to help new contributors.
Thanks.

**Comment by emcastillo** [comment]
The error is clearly written there 😀😋
Your CUDA version is too old (10.1) you need to be at least on CUDA 10.2

Probably you will need to install a new driver for the GPU too

**Comment by hmtbgc** [comment]
Thanks for your reply. But after I upgrade cuda version, I meet another problem.
<img width="771" alt="error3" src="https://user-images.githubusercontent.com/32740258/156864577-c57d57c1-2bcb-40d6-9a9b-cc72ae0b2c5b.PNG">
<img width="590" alt="error4" src="https://user-images.githubusercontent.com/32740258/156864580-044ea550-c128-45e7-bbc6-1ae979a94cc2.PNG">
<img width="617" alt="error5" src="https://user-images.githubusercontent.com/32740258/156864582-3459b002-4d03-4e30-8527-9ffa5f888c3b.PNG">
It seems that the setup process is stuck? And I don't know where "cupy_builder" is in setup.py.
Thanks in advance.

**Comment by emcastillo** [comment]
compiling CuPy can take a lot of time depending on your system,
you can run it with `pip install -e . -v` to get output and see the process.
You shouldn't care about `cupy_builder` but it is here 
https://github.com/cupy/cupy/tree/master/install/cupy_builder

**Comment by leofang** [comment]
If you specify the architecture using this env var
https://docs.cupy.dev/en/stable/reference/environment.html#envvar-CUPY_NVCC_GENERATE_CODE
either explicitly or using "current", it'd help reduce the compilation time too.

**Comment by hmtbgc** [comment]
Thanks for your reply. I have sucessfully installed CuPy from source. But I cannot import it in my python.
Here is the  screenshot for sucessful installation
<img width="692" alt="succeed" src="https://user-images.githubusercontent.com/32740258/156877462-2ae81cbe-9a93-43d8-ab15-347ebb6119fe.PNG">
But the import problem still exists.
<img width="773" alt="error6" src="https://user-images.githubusercontent.com/32740258/156877492-5e39afc8-c0bf-4c12-a1b1-1809321825ca.PNG">
I have followed the suggestion and set the LD_LIBRARY_PATH as "/usr/local/cuda/lib64" and CUDA_PATH as "/usr/local/cuda"
and I can find "cupy" directory in PYTHONPATH(The last one is where I store cupy source code)
<img width="779" alt="error7" src="https://user-images.githubusercontent.com/32740258/156877574-be5aedfc-5a2b-43ce-bc60-0428fb4508da.PNG">
Is anything that I forget to install ? 
Thanks very very very much for your help!

**Comment by hmtbgc** [comment]
BTW, I install cupy in my conda virtual environment and I am not sure it has influence or not.
Here is my pip list sreenshot and my cuda path.
<img width="496" alt="error8" src="https://user-images.githubusercontent.com/32740258/156877797-c1cbcbd8-df2a-4f7d-86bf-e53afb8fbb15.PNG">
<img width="740" alt="error9" src="https://user-images.githubusercontent.com/32740258/156877800-357dc833-e89b-4527-92bf-462983cf0e3b.PNG">

**Comment by emcastillo** [comment]
First, do not post screenshots please, it's a pain to retype everything when looking up errors.
Second, the error shows that something is wrong with your CUDA installation.

How do you install CUDA?, also you have several versions so I recommend you to delete older ones if you are not using them.

I recommend you to install CUDA 11.4 and build cupy again. Delete the repo and compile it from 0 to avoid issues.

**Comment by emcastillo** [comment]
Since this seems to be resolved let's close this issue.
Feel free to reopen it if you find another problem.
