### ISSUE TITLE
TypeError:folat argument must be a string or a number , not 'Axessubplot'

### ISSUE THREAD

**Issue by haritha1022** [cupy/cupy#6532]
### Description

Hello sir, I have daily timeseries panel of 42 subplots .Now i want to identify the maximum peaks in each subplot. Could you please tell me how can I do it. Thankyou.

### To Reproduce

```py
# Write the code here
```
peaks = find_peak(y, height = 1, threshold = 1,distance = 1)
print(peaks)

when  I am trying this command for my data it gives error like
"TypeError:folat argument must be a string or a number , not 'Axessubplot"

### Environment

```
# Paste the output here
```
TypeError:folat argument must be a string or a number , not 'Axessubplot"

**Comment by emcastillo** [comment]
This doesn't seem to be a CuPy related issue.

**Comment by emcastillo** [comment]
Let's close this as there is no further activity. Please reopen it if needed. Thanks!

**Comment by haritha1022** [comment]
Thanks a lot.
