### ISSUE TITLE
Support for multi_dot

### ISSUE THREAD

**Issue by beckernick** [cupy/cupy#6600]
### Description

Per the NumPy docs, [multi_dot](https://numpy.org/doc/stable/reference/generated/numpy.linalg.multi_dot.html) is a convenience function to compute the dot product of multiple arrays with an optimized optimal order of operations determined by a cost calculation. For compatibility reasons, it would be nice to implement this API in CuPy (even without the optimized order of operations).

```python
from numpy.linalg import multi_dot

# Prepare some data
A = np.random.random((10000, 100))
B = np.random.random((100, 1000))
C = np.random.random((1000, 5))
D = np.random.random((5, 333))

# the actual dot multiplication
np.testing.assert_array_almost_equal(multi_dot([A, B, C, D]), A.dot(B).dot(C).dot(D))
```

**Comment by emcastillo** [comment]
Hi, this is listed in https://github.com/cupy/cupy/issues/6078 😄

**Comment by beckernick** [comment]
Ah, thanks. It didn't come up when I searched for "multi_dot" but I should have known 😄 

Closing as a duplicate.
