### ISSUE TITLE
Error in installation instructions for v11.0.0b1 on CUDA 11.6

### ISSUE THREAD

**Issue by MurrayData** [cupy/cupy#6610]
### Description

The instructions to install v11.0.0b1 on CUDA 11.6 state:

```pip install cupy-cuda116 -f https://pip.cupy.dev/pre```

This installs 10.0.3:

```
>>> import cupy as cp
>>> cp.__version__
'10.3.0'
```

The version needs to be added thus:

```pip install cupy-cuda116==11.0.0b1 -f https://pip.cupy.dev/pre```

Then it works correctly:

```
>>> import cupy as cp
>>> cp.__version__
'11.0.0b1'
```

Great effort and looking forward to trying the new features in ```cupyx.scipy.special```

**Comment by kmaehashi** [comment]
Thanks for reporting, @MurrayData! Updated release notes. Docs will be fixed in #6612.
