### ISSUE TITLE
Memory is full and cannot be released by delete vars or free blocks()

### ISSUE THREAD

**Issue by TeaCult** [cupy/cupy#6616]
### Description

Whenever I am trying to create a random array in gpu memory using cp.random.random() if it does not fit into memory, data sent to gpu becomes ghost or something I cannot clear memory and I am forced to terminate python session. 

Is it a known thing ? , How can I circumvent this ? 

Thank you.

### To Reproduce

```py
# Write the code here
```

### Environment

```
# Paste the output here
```

**Comment by TeaCult** [comment]
Nevermind it was about nvidia-smi reporting wrong numbers ...

**Comment by leofang** [comment]
It's likely normal and due to CuPy's mempool holding memory for subsequent reuse:
https://docs.cupy.dev/en/stable/upgrade.html#default-memory-pool
https://docs.cupy.dev/en/stable/user_guide/memory.html
