### ISSUE TITLE
Include C libraries to user defined kernels

### ISSUE THREAD

**Issue by martinmorenoc** [cupy/cupy#6618]
### Description

I am trying to include math.h in one of my ElementWiseKernel to calculate the tangent of some values. It would be nice to be able to include standard libraries like math.h

Here is an example of what I would like to achieve:
```
collisions = cp.ElementwiseKernel(
    'float64 xtg, float64 ztg',
    'float64 new_ztg',
    '''
    #include <math.h>
    new_ztg = tan(xtg/ztg)
    ''',
    'collisions')
```

**Comment by leofang** [comment]
It is already doable without any include. The math functions are built-in as CUDA device functions, see
https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH.html#group__CUDA__MATH

**Comment by emcastillo** [comment]
also, look at the `preamble` kwarg
