### ISSUE TITLE
"Out" parameter in "Sorting, searching and counting" functions

### ISSUE THREAD

**Issue by claudio-bon** [cupy/cupy#6627]
### Description

I was wondering whether it would be possible to add an `Out` parameter in "Sorting, searching and counting" functions such as `cupy.argsort` or `cupy.argpartition`, instead of allocating the output array directly inside the functions.
Here should be an example of allocation relative to the aforementioned functions:
https://github.com/cupy/cupy/blob/5ae1db4d9231f551812a7ff590fbc7d8c4a45c36/cupy/_core/_routines_sorting.pyx#L83

**Comment by kmaehashi** [comment]
These functions are designed to provide the same API as NumPy, so it is unlikely supported. May I ask what is the motivation behind this?

**Comment by claudio-bon** [comment]
An array is being allocated at runtime. This is possibly an issue if you want to avoid additional overhead given by the internal allocation in a context where the function has to process many inputs sequentially: in this case you may want to allocate the output array at the beginning and reuse it for all the inputs.

**Comment by kmaehashi** [comment]
Thanks for the explanation! If you don't have a concrete issue specific to CuPy, the best way is to file a feature request to NumPy because CuPy APIs follow the specification of NumPy as mentioned above.

**Comment by claudio-bon** [comment]
Thank you for your answer.
