### ISSUE TITLE
slow `max`/`min`

### ISSUE THREAD

**Issue by samrere** [cupy/cupy#6645]
### Description

Hi, this is just a repost of #2085, it is closed and said to be fixed.
However, when I run the code using the latest cupy, it seems max/min is still much slower than numpy:
```
cupy : 8278.654296875 ms
numpy : 2767.02197265625 ms
```
Can I please get more information on this? Thanks!

### Environment

```
# Paste the output here
```

**Comment by leofang** [comment]
For earlier CuPy versions, you can set the environment variable `CUPY_ACCELERATORS=cub` before launching Python to use CUB, see https://docs.cupy.dev/en/stable/user_guide/performance.html#use-cub-cutensor-backends-for-reduction-and-other-routines.

**Comment by samrere** [comment]
> Could you try with CuPy v11.0.0b1?
Thanks for your help! 
BTW, May I ask how to upgrade to version 11? I tried something like `pip install --upgrade cupy-cuda115` but I'm still in 10.3.1

**Comment by asi1024** [comment]
@samrere 
Could you try `pip install --pre cupy-cuda115 -f https://pip.cupy.dev/pre`?

**Comment by samrere** [comment]
all good! thanks a lot for your help! @asi1024 and @leofang
