### ISSUE TITLE
Feedback for Universal Wheel Package (`cupy-wheel`)

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#6688]
CuPy v10.4.0 (#6012) added an experimental meta package `cupy-wheel` on PyPI. Instead of specifying an individual wheel package name, users can now install CuPy with the single command line `pip install cupy-wheel`; the `cupy-wheel` meta-package probes the CUDA version installed in the users' environment, and automatically picks and installs the real CuPy wheel package (e.g., `cupy-cuda115`).

It is currently marked experimental. Towards the v11 final release, we are going to stabilize this feature.

Major TODOs remaining are:
- [ ] Add documentation for downstream packages to use `cupy-wheel`
- [x] Disable caching `cupy-wheel` package by `pip` to enforce running `setup.py` everytime
- [ ] Add `long_description`
- [ ] Automate the release process of the meta package

If you find difficulties using `cupy-wheel`, or have any comments or suggestions on `cupy-wheel` package, please feel free to post them here.

**Comment by kmaehashi** [comment]
### GPUs are required to install `cupy-wheel`

I was trying `cupy-wheel` with several scenarios and now thinking this restriction is not negligible:
https://github.com/cupy/cupy/pull/6012#discussion_r843109969

> This relies on the installing machine to have a GPU.

The most problematic case is that CUDA driver is unavailable during `docker build`. This means `cupy-wheel` (and dependents) will not be able to be burnt in container images.

```dockerfile
FROM nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04
RUN apt-get update && apt-get -y install python3-pip
RUN pip install cupy-wheel
```

```py
    __main__.AutoDetectionFailed: libcudart.so: <_FuncPtr object at 0x7f2b0dd3e1c0> returned error: 35
```

I come up with several alternative ways to probe CUDA version.

1. Extract from shared library name (e.g. `libcudart.so.11.6.55` -> 11.6).
    * Cons: Does not work on Windows (all CUDA 11.x runtime DLLs are named `cudart64_110.dll`)
2. Extract from development tools (`CUDA_VERSION` in `cuda.h`,  `nvcc --version`, `nvrtcGetVersion`, etc.)
    * Cons: Does not work in the environment without dev headers/tools (e.g., "base" CUDA images like `nvidia/cuda:11.6.2-base-ubuntu20.04`).
3. Extract from `$CUDA_PATH/version.json`
    * Cons: Only available in CUDA 11.2.1 or later. Also "base" CUDA images do not contain this file.
4. Extract from environment variables (e.g., `CUDA_PATH=".../cuda-11.1/..."` -> 11.1)
    * Cons: Can be unreliable

Maybe use approach 1 for Linux and 4 for Windows...

### pip caches `cupy-wheel`

`pip` creates a local cache when installing a sdist package. This can be a problem when changing a CUDA version; suppose the following scenario:

```sh
# 1. Install CUDA 11.4.
...

# 2. Install cupy-wheel.
pip install cupy-wheel  # -> this runs `setup.py` and installs "cupy-cuda114" as expected

# 3. Upgrade CUDA from 11.4 to 11.6.
...

# 4. Uninstall CuPy.
pip uninstall cupy-cuda114 cupy-wheel

# 5. Install cupy-wheel.
pip install cupy-wheel
```

Surprisingly, this results in "cupy-cuda114" to be re-installed, becauase pip reuses the "cached wheel" generated in step 2, and does not run `cupy-wheel`'s `setup.py` in step 5. I think cache generation of `cupy-wheel` can be prohibited by changing `bdist_wheel` to nop.

https://pip.pypa.io/en/stable/topics/caching/#locally-built-wheels

### Compatibility with conda

We should check what will happen when users do `pip install cupy-wheel` when `cupy` conda package is installed.

**Comment by leofang** [comment]
> ### GPUs are required to install `cupy-wheel`

Thanks for your nice summary, @kmaehashi. I reported internally (nvbugs 3624208) and the CUDA team thinks it should be fixable, but no timeline was given.

**Comment by leofang** [comment]
@kmaehashi Question: I noticed `cupy-wheel` is not available for v10.5.0. Is it intentional?

**Comment by kmaehashi** [comment]
> @kmaehashi Question: I noticed `cupy-wheel` is not available for v10.5.0. Is it intentional?

Oh, this is not intentional. It seems `cupy-wheel` slipped from the release process. I've added it to the release task list maintained internally. I'll release both v10.5.0/v10.6.0 this week.

**Comment by kmaehashi** [comment]
Released.
v10.5.0: https://github.com/cupy/cupy/commit/9d631ff3687a89e83c6e8c7aec5087d96fc3bbd4
v10.6.0: https://github.com/cupy/cupy/commit/8270e3a32ce8ba6175e0b5a38cfb713a4f8903e1

**Comment by leofang** [comment]
I did some testing to consider the following situations:
1. CuPy from conda is already installed, and the user attempts to install `cupy-wheel`:
   - In this case, [this check](https://github.com/cupy/cupy/blob/85e55ca45aca7190f66c27b68fe33741989e7766/install/universal_pkg/setup.py#L245-L248) is legit and will raise an error as expected (the error message can be improved, though)
2. `cupy-wheel` is already installed, and the user attempts to install `cupy` from Conda:
   - In this case, there is not yet a mechanism to avoid this silliness:
```
cupy                      10.5.0           py39hc3c280e_0    conda-forge
cupy-cuda114              10.6.0                   pypi_0    pypi
cupy-wheel                10.6.0                   pypi_0    pypi
```
Perhaps `cupy-wheel` should also create a `cupy` empty package to keep the name occupied?

**Comment by kmaehashi** [comment]
Thanks for testing, Leo!

> 1. CuPy from conda is already installed, and the user attempts to install `cupy-wheel`:
>    
>    * In this case, [this check](https://github.com/cupy/cupy/blob/85e55ca45aca7190f66c27b68fe33741989e7766/install/universal_pkg/setup.py#L245-L248) is legit and will raise an error as expected (the error message can be improved, though)

:+1:

> 2. `cupy-wheel` is already installed, and the user attempts to install `cupy` from Conda:
>    
>    * In this case, there is not yet a mechanism to avoid this silliness:

I think it's not possible to prevent this, but `import cupy` should warn in this case.

https://github.com/cupy/cupy/blob/3fedbb957b79782089868540065ca24b088f29c6/cupy/_environment.py#L402

> Perhaps `cupy-wheel` should also create a `cupy` empty package to keep the name occupied?

This will confuse pip (e.g., in this case `pip install -U cupy` will try to download cupy tarball from PyPI and build from source), so I think it's better to avoid it.

**Comment by leofang** [comment]
I see, thanks for reminder @kmaehashi. I had forgotten about it. I think the 2nd situation is less common, so I guess a warning like that should be sufficient.

**Comment by leofang** [comment]
> I reported internally (nvbugs 3624208) and the CUDA team thinks it should be fixable, but no timeline was given.

Forgot to update, I believe this has been fixed at least in CUDA 12.0. Not sure if they had the time to backport the fix to CUDA 11.x, though.

**Comment by kmaehashi** [comment]
Thanks, confirmed `cudaRuntimeGetVersion` works without GPU under CUDA 12!

**Comment by kmaehashi** [comment]
Closing as the package will be removed in CuPy v13. #7628
