### ISSUE TITLE
Save/load previously cached kernels into new processes

### ISSUE THREAD

**Issue by adamcircle** [cupy/cupy#6689]
### Description

Cupy currently compiles and caches kernels within the running process. However, for programs which run across several processes, or may use the same kernel on many different runs of the process, it would be nice to avoid generating the kernel each time, and instead load the cached kernel into the process. I would like to request a way to load or save a generated kernel.

**Comment by leofang** [comment]
CuPy kernels are cached not only in-memory but also on disk, and there's a bit of atomic I/O thoughts to make sure concurrent processes can access the on-disk cache without issues. What exactly is missing here? 
https://docs.cupy.dev/en/stable/user_guide/performance.html#kernel-compilation
https://docs.cupy.dev/en/stable/reference/environment.html#envvar-CUPY_CACHE_DIR

**Comment by kmaehashi** [comment]
Closing as inactive for a while. Please feel free to reopen if you still need help.
