### ISSUE TITLE
Pin CUB upstream version more aggressively?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#6700]
### Description

After #4897 is concluded CuPy now enables the CUB backend by default. The status quo is
- For CTK < 11.0, CuPy uses the bundled CUB
- For CTK >= 11.0, CuPy uses the CUB from the CUDA Toolkit seen at compile time.

It would be nice if CuPy bundle pins at the CUB (and therefore Thrust) version more aggressively, and does not rely on the CTK. The reason is 2-fold:
- Due to scheduling reasons the CTK's CUB copy usually lags behind the upstream
- Unlike ~2 years ago when we started adding CUB support, now CUB/Thrust are well maintained and constantly having new features/bug fixes added in each release. 

If we lag behind upstream (as the CTK does) we can't enjoy the new additions (ex: supporting #6699 would not be possible as the CUB version needed only comes with CTK 11.6+).

**Comment by leofang** [comment]
[CUB 1.17](https://github.com/NVIDIA/cub/releases/tag/1.17.0-rc0) will be the last 1.x release.

**Comment by leofang** [comment]
FYI starting CUB 2.0 libcudacxx will become a dependency of Thrust/CUB (upstream PRs just merged today), so I'd suggest CuPy to pin at CUB 1.17 and evaluate the transition at a later time.

**Comment by kmaehashi** [comment]
I think this sounds good. The only concern I come up with is the mismatch of supported CUDA versions between CUB and CuPy.

**Comment by leofang** [comment]
> The only concern I come up with is the mismatch of supported CUDA versions between CUB and CuPy.

CUB 1.17 should still support CUDA 10.2+? Am I missing something?

But, this reminds me that a strong assumption here is we pin at **_both_** Thrust and CUB 1.17. Not sure about the impact to the existing Thrust code. We might need to do some minor refactor to hide them into the `cupy` namespace?

**Comment by leofang** [comment]
FYI, Thrust/CUB 2.0 RC are out today.

**Comment by leofang** [comment]
xref: https://github.com/conda-forge/staged-recipes/pull/21953#issuecomment-1432300418

**Comment by leofang** [comment]
> xref: [conda-forge/staged-recipes#21953 (comment)](https://github.com/conda-forge/staged-recipes/pull/21953#issuecomment-1432300418)

A revision to my proposal in OP: I'd like to enable CuPy to pin at newer **CCCL** (=Thrust + CUB + libcudacxx), not just CUB. Targeting this for CuPy v13 (https://github.com/cupy/cupy/issues/7555). I will try to figure out if this also happens to work for CUDA 10.2 by chance (currently CCCL aims to support CUDA 11/12).
