### ISSUE TITLE
aarch64 wheels for cupy-cuda11+ in PyPI

### ISSUE THREAD

**Issue by sevagh** [cupy/cupy#6705]
### Description

In issue https://github.com/cupy/cupy/issues/3196, a wheel was provided for cupy-cuda102.

I need to install cupy-cuda115 for an arm/aarch64 system, which don't have aarch64 wheels available in PyPI.

Can arm/aarch64 cupy-cuda11x wheels be uploaded to PyPI?

Thanks.

**Comment by sevagh** [comment]
FWIW https://github.com/cupy/cupy-release-tools/pull/254 seems to be addressing this :pray:

**Comment by kmaehashi** [comment]
Hi @sevagh, thanks for the request! We are thinking of putting it on our pip repository (we currently use it to host pre-release wheels: https://pip.cupy.dev/pre/) so that users can install aarch64 wheels via `pip install cupy-cudaXXX -f https://pip.cupy.dev/aarch64/`.
Do you only need `cupy-cuda115` for now? I'd like to start with minimal needed 😃

**Comment by kmaehashi** [comment]
Sorry for the delayed response, I'll try to put wheels within this week.

**Comment by kmaehashi** [comment]
Hi @sevagh, I put CuPy v10.5.0 aarch64 wheels here:
https://github.com/kmaehashi/cupy-aarch64-wheel/releases/tag/v10.5.0

Could you test the wheel, as we don't have CUDA 11.x + Arm server environment? Here is the step to run smoke tests, which we usually do before shipping:

```sh
git clone https://github.com/cupy/cupy-release-tools.git
cd cupy-release-tools
git checkout v10
./dist.py \
    --action verify \
    --target wheel-linux \
    --cuda 11.5-aarch64 \
    --python 3.8 \
    --dist /path/to/cupy_cuda115-10.5.0-cp38-cp38-manylinux2014_aarch64.whl \
    --test release-tests/common \
    --test release-tests/sparse
```

This builds a Docker image to verify the wheel, then run [release-tests](https://github.com/cupy/cupy-release-tools/tree/master/release-tests) inside the Docker container.

cc/ @pentschev

**Comment by sevagh** [comment]
:pray: testing now

**Comment by kmaehashi** [comment]
Thanks! Once the test pass I'll put it on pip.cupy.dev.

**Comment by kmaehashi** [comment]
All `aarch64` wheels are now accessible from the index! https://pip.cupy.dev/aarch64/

### CuPy v10

* `pip install cupy-cuda102 -f https://pip.cupy.dev/aarch64`
* `pip install cupy-cuda115 -f https://pip.cupy.dev/aarch64`

### CuPy v11 pre-release

* `pip install --pre cupy-cuda102 -f https://pip.cupy.dev/aarch64`
* `pip install --pre cupy-cuda11x -f https://pip.cupy.dev/aarch64` (for CUDA 11.2+)

We have no plan to release `cupy-cuda110` and `cupy-cuda111` for aarch64.

**Comment by pentschev** [comment]
Thanks @kmaehashi !

**Comment by kmaehashi** [comment]
I've confirmed `cupy-cuda11x` work with Arm/NVIDIA T4G on AWS `g5g.xlarge` instance with CUDA 11.7.

```pycon
>>> import cupy
>>> cupy.show_config()
OS                           : Linux-5.13.0-1031-aws-aarch64-with-glibc2.29
Python Version               : 3.8.10
CuPy Version                 : 11.0.0rc1
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.23.1
SciPy Version                : None
Cython Build Version         : 0.29.24
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11070
CUDA Driver Version          : 11070
CUDA Runtime Version         : 11070
cuBLAS Version               : (available)
cuFFT Version                : 10702
cuRAND Version               : 10210
cuSOLVER Version             : (11, 3, 5)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 7)
Thrust Version               : 101500
CUB Build Version            : 101500
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA T4G
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:00:1F.0
>>> cupy.arange(10)
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

**Comment by pentschev** [comment]
This is super cool, thanks @kmaehashi for testing and reporting that!
