### ISSUE TITLE
Wrong overflow with matmul of uint16 arrays

### ISSUE THREAD

**Issue by asmeurer** [cupy/cupy#6715]
### Description

The following arrays give an apparently incorrect overflowed result with matmul. 

```py
>>> import cupy as cp
>>> x = cp.asarray([51307], dtype=cp.uint16)
>>> y = cp.asarray([[[327]]], dtype=cp.uint16)
>>> x
array([51307], dtype=uint16)
>>> y
array([[[327]]], dtype=uint16)
>>> x @ y # This is giving a different answer
array([[172]], dtype=uint16)
>>> x*y
array([[[173]]], dtype=uint16)
>>> x @ y[0]
array([173], dtype=uint16)
>>> x * y[0]
array([[173]], dtype=uint16)
```

The error only occurs when the second array has 3 dimensions. Presumably cupy uses different code paths for stacked vs. non-stacked linear algebra functions. Note that `51307*327 % 2**16` is indeed `173`.

I'm unclear whether this behavior is actually a bug or if this is something that is to be expected from overflowing integers. 

I identified this with the array API test suite, but it is unrelated to the array API module. The array API doesn't specify overflow behavior, but it would be simpler in the test suite if it could just ignore overflowing. 

### To Reproduce

```py
# Write the code here
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
OS                           : Linux-5.13.0-40-generic-x86_64-with-glibc2.34
Python Version               : 3.10.4
CuPy Version                 : 10.4.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.22.3
SciPy Version                : 1.8.0
Cython Build Version         : 0.29.28
Cython Runtime Version       : None
CUDA Root                    : /home/aaronmeurer/anaconda3/envs/array-api
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 11060
CUDA Runtime Version         : 11060
cuBLAS Version               : (available)
cuFFT Version                : 10600
cuRAND Version               : 10209
cuSOLVER Version             : (11, 3, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 6)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 70f5331
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 2080
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0
```

**Comment by takagi** [comment]
Thanks for reporing. I can replicate the error and am looking further...

**Comment by takagi** [comment]
Seems that cupy's matmul computes with cublas gemm routines when ndim <= 2. Cublas gemm routines supports only floating-point or complex values, so `x @ y` above is computed in float then is unsafely elementwise-copied to uint16, which may include the error.
