### ISSUE TITLE
Async Mem copies not working properly after updating to cupy 10.4.0

### ISSUE THREAD

**Issue by malkadi** [cupy/cupy#6747]
### Description

I've been using CuPy v9.6.0 for some radar signal processing algorithms and everything was better than fine. As I tried to update to v10.4.0 the performance got remarkably worse.

A closer look in the visual profiler shows that memory copies from device to host are no longer done in parallel to the computation. 

Here is the timeline of a radar cycle with CuPy v9.6.0
![cupy_v9 6 0](https://user-images.githubusercontent.com/7325441/170107182-ec816953-5546-407b-af65-d6db9b2a4a51.png)
Here is the timeline of a radar cycle with CuPy v10.4.0
![cupy_v10 4 0](https://user-images.githubusercontent.com/7325441/170107196-1cd61a69-3658-4b09-8f10-a3d4db846b8a.png)

Please notice that I'm using a single stream for kernels and a separate one for memory copy.
Unfortunately, the code is quite complex and trying to reproduce the problem on your side is not easy.
However, I'm willing to try out your ideas.

### Installation

Source (`pip install cupy`)

### Environment

I used the following versions of CuPy
```
OS                           : Linux-5.13.0-40-generic-x86_64-with-glibc2.29
Python Version               : 3.8.10
CuPy Version                 : 9.6.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.4
SciPy Version                : 1.8.0
Cython Build Version         : 0.29.22
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda-11.4
nvcc PATH                    : /usr/local/cuda-11.4/bin/nvcc
CUDA Build Version           : 11040
CUDA Driver Version          : 11040
CUDA Runtime Version         : 11040
cuBLAS Version               : (available)
cuFFT Version                : 10502
cuRAND Version               : 10205
cuSOLVER Version             : (11, 2, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 4)
Thrust Version               : 101201
CUB Build Version            : 101201
Jitify Build Version         : 60e9e72
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Quadro P1000
Device 0 Compute Capability  : 61
Device 0 PCI Bus ID          : 0000:01:00.0


```
```
OS                           : Linux-5.13.0-40-generic-x86_64-with-glibc2.29
Python Version               : 3.8.10
CuPy Version                 : 10.4.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.6
SciPy Version                : 1.8.1
Cython Build Version         : 0.29.30
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda-11.4
nvcc PATH                    : /usr/local/cuda-11.4/bin/nvcc
CUDA Build Version           : 11040
CUDA Driver Version          : 11040
CUDA Runtime Version         : 11040
cuBLAS Version               : (available)
cuFFT Version                : 10502
cuRAND Version               : 10205
cuSOLVER Version             : (11, 2, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 4)
Thrust Version               : 101201
CUB Build Version            : 101201
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Quadro P1000
Device 0 Compute Capability  : 61
Device 0 PCI Bus ID          : 0000:01:00.0

```

**Comment by leofang** [comment]
> Please notice that I'm using a single stream for kernels and a separate one for memory copy.

Are you sure? Check out the profiler output, in v10.4.0 your compute kernels are running on the default stream as opposed to stream 13 as in v9.6.0, and it could lead to the blocking execution unless you purposely create non-blocking streams (see [here](https://docs.nvidia.com/cuda/cuda-runtime-api/stream-sync-behavior.html)). Are they accidental changes when you upgraded to v10?

**Comment by malkadi** [comment]
Yes this is the solution!
> https://docs.cupy.dev/en/latest/upgrade.html#changes-in-cupy-cuda-stream-behavior

Thanks!
