### ISSUE TITLE
array_api sort() does not work

### ISSUE THREAD

**Issue by asmeurer** [cupy/cupy#6779]
### Description

The array_api sort() is copied from the NumPy implementation, but passes through a `kind` keyword which doesn't exist in `cupy.sort`.

### To Reproduce

```py
>>> a = xp.asarray([1, 0, 2])
>>> xp.sort(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aaronmeurer/anaconda3/envs/array-api/lib/python3.10/site-packages/cupy/array_api/_sorting_functions.py", line 45, in sort
    res = np.sort(x._array, axis=axis, kind=kind)
TypeError: sort() got an unexpected keyword argument 'kind'
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
# Paste the output here
```

### Additional Information

The array API does require support for a `stable` keyword. If `cupy.sort` is always stable, it can just ignore this flag, as `stable=False` is allowed to be stable (see https://data-apis.org/array-api/latest/API_specification/generated/signatures.sorting_functions.sort.html). Otherwise, I would suggest raising NotImplementedError for `stable=True` (which is unfortunately the default).

**Comment by leofang** [comment]
Looks like this is a dup of #5701. @kmaehashi plz assign to me.

**Comment by leofang** [comment]
btw IIRC CuPy always performs stable sort (@takagi can correct me).

**Comment by takagi** [comment]
> btw IIRC CuPy always performs stable sort

Yes.
