### ISSUE TITLE
Failed to install CuPy - stuck at "Building wheel for copy (setup.py) ... | "

### ISSUE THREAD

**Issue by SandboChang** [cupy/cupy#6780]
### Description

Could it be ubuntu 22.04 not being supported yet?

I am trying to install on a fresh ubuntu 22.04 server.
The platform is actually a VM inside Proxmox, with a 3090Ti passed through to the VM.
On the guest, I have CUDA 11.5 installed and tested it with Tensorflow to check if the 3090Ti is functioning, and it was able to do matmul.

Then I went ahead to install CuPy with 
`pip3 install cupy`
However it got stuck at the line 
`Building wheel for cupy (setup.py) ... |`

Alternatively, I tried to install according to the CUDA version using 
`pip install cupy-cuda115`
The installation becomes very short, but then I cannot actually import CuPy from Python3:
```
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: cannot import name 'core' from partially initialized module 'cupy._core' (most likely due to a circular import) (/home/qipe/cupy/cupy/_core/__init__.py)
```

### To Reproduce

```
pip3 install cupy
```
stuck at 

`Building wheel for cupy (setup.py) ... |`

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
Traceback (most recent call last):
  File "/home/qipe/cupy/cupy/__init__.py", line 18, in <module>
    from cupy import _core  # NOQA
  File "/home/qipe/cupy/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
ImportError: cannot import name 'core' from partially initialized module 'cupy._core' (most likely due to a circular import) (/home/qipe/cupy/cupy/_core/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/qipe/cupy/cupy/__init__.py", line 20, in <module>
    raise ImportError(f'''
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: cannot import name 'core' from partially initialized module 'cupy._core' (most likely due to a circular import) (/home/qipe/cupy/cupy/_core/__init__.py)
================================================================
```

**Comment by SandboChang** [comment]
For unclear reason, rebooting and now it works with the prebuild wheel.

**Comment by CloudsRL** [comment]
i face the same trouble ,
cupy always Building wheel for cupy (setup.py) ... |
install cupy-cuda113 is easy and work,
but when i run code,
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: /home/wang/anaconda3/envs/yoloSAM/lib/python3.8/site-packages/cupy_backends/cuda/api/runtime.cpython-38-x86_64-linux-gnu.so: symbol cudaMemPoolSetAttribute version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference
================================================================
QAQ i try to reboot but no change

**Comment by Zhiwei-Zhai** [comment]
I got the same error when using ``` pip install cupy```.

As I have CUDA 12.4, the cupy is successfully installed by ```pip install cupy-cuda12x ```

**Comment by OptimizeStock** [comment]
@Zhiwei-Zhai **Thank you!!!!!!!!!**

**Comment by huang-hz** [comment]
> I got the same error when using ` pip install cupy`.
> 
> As I have CUDA 12.4, the cupy is successfully installed by `pip install cupy-cuda12x `

THANKS, that's the correct solution to this problem.
