### ISSUE TITLE
Support SciPy 1.0

### ISSUE THREAD

**Issue by unnonouno** [cupy/cupy#680]
SciPy 1.0 released. It has some compatibility breaks in `scipy.sparse`. We need to fix implementations or tests.

**Comment by kmaehashi** [comment]
Related to this, we have to decide what minimum version of SciPy to support, and add it docs.

* SciPy 0.18 requires Python 2.7 or 3.4-3.5 and NumPy 1.7.1 or greater. https://github.com/scipy/scipy/releases/tag/v0.18.0
* SciPy 0.19 requires Python 2.7 or 3.4-3.6 and NumPy 1.8.2 or greater. https://github.com/scipy/scipy/releases/tag/v0.19.0
* SciPy 1.0.0 requires Python 2.7 or >=3.4 and NumPy 1.8.2 or greater. https://github.com/scipy/scipy/releases/tag/v1.0.0

I think supporting SciPy 0.19+ is fine.
