### ISSUE TITLE
Argpartition zero length behavior differs from numpy

### ISSUE THREAD

**Issue by sss441803** [cupy/cupy#6812]
### Description

When a length 0 cupy.ndarray passed to cupy.argpartition, `ValueError: kth(=0) out of bounds 0` is raised. If the a numpy.ndarray of length 0 is passed to cupy.argpartition, is returns an empty numpy.ndarray. If we use numpy.argpartition on the numpy array, it also returns an empty numpy.ndarray.

### To Reproduce

```py
import cupy, numpy

cupy.argpartition(cupy.array([]), 0)
cupy.argpartition(numpy.array([]), 0)
numpy.argpartition(numpy.array([]), 0)
```

### Environment

```
# Paste the output here
```

**Comment by leofang** [comment]
Seems to be a sub-issue of #3287?
