### ISSUE TITLE
pip install cupy-cuda11x ERROR

### ISSUE THREAD

**Issue by nccwarp9** [cupy/cupy#6833]
### Description

ERROR: Could not find a version that satisfies the requirement cupy-cuda11x (from versions: none)
ERROR: No matching distribution found for cupy-cuda11x

### To Reproduce

```py
# Write the code here
```

### Environment

```
# Paste the output here
```

**Comment by emcastillo** [comment]
it's still not released

**Comment by kmaehashi** [comment]
The README has been fixed to show v10 instruction until v11 is released.
https://github.com/cupy/cupy
