### ISSUE TITLE
matmul with out=in doesn't raise an exception

### ISSUE THREAD

**Issue by CamilleKaze** [cupy/cupy#6870]
Hello, sorry if I'm not following a template but I don't really have time. Just a quick remark to say that in the doc of cupy.matmul:

https://docs.cupy.dev/en/stable/reference/generated/cupy.matmul.html

there's a note "The out array as input is currently not supported.". Indeed I tried it and it doesn't give the right result, but I'm surprised I was able to try it without getting any exception or at least warning. I think this is a bit dangerous...

Thanks,

Camille

**Comment by asi1024** [comment]
Thanks for your reporting! It seems that it was already fixed in https://github.com/cupy/cupy/pull/6216. We will remove this note from the documentation. (cc: @toslunar)
