### ISSUE TITLE
map_coordinates doesn't work the same as numpy: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by marisancans** [cupy/cupy#6891]
### Description

I'm trying to port numpy to cupy and I hit a brick wall where  the same code doesn't work in cupy. I get an error `'list' object has no attribute 'shape'` but it works in normal numpy.

### To Reproduce

```py
    e_img = np.random.random((3002, 3000))
    coor_y = np.random.random((50, 50, 1))
    coor_x = np.random.random((50, 50, 1))
    order = 1

    x = map_coordinates(e_img, [coor_y, coor_x], order=order, mode='wrap')
```

### Installation

ubuntu 20.04
cuda 11.6

### Environment

conda list

```
numpy                     1.21.2           py39h20f2e39_0  
numpy-base                1.21.2           py39h79a1101_0
cupy                      9.6.0            py39ha91d172_0    conda-forge
scipy                     1.7.3                    pypi_0    pypi
```

**Comment by emcastillo** [comment]
`coordinates` should be of `cupy.ndarray` type and not a list. We do this to avoid implicit synchronization, but the docs needs to be updated.
