### ISSUE TITLE
Support `deg` in `cupy.angle`

### ISSUE THREAD

**Issue by jcfaracco** [cupy/cupy#6900]
### Description

Numpy `angle()` function has an option called `deg` which is just a simple boolean to set if the return should be in degrees or not. For further detail, see the Numpy documentation.

### Additional Information

Using Dask library, it considers all the options that Numpy has. So, any missing option causes a failure.

For further detail, see https://github.com/dask/dask/issues/9296

**Comment by kmaehashi** [comment]
Thanks! We are working on fix in #6905.
