### ISSUE TITLE
scipy.ndimage.distance_transform_edt (Euclidean distance transform)

### ISSUE THREAD

**Issue by grlee77** [cupy/cupy#6919]
### Description

We have recently proposed an implementation for `scipy.ndimage.distance_transform_edt` in: https://github.com/rapidsai/cucim/pull/318

I have started this there as we would like to use this to implement a few other cuCIM functions in the immediate term. I think it could make sense for it to live here longer-term, though.

### Additional Information

Limitations of that implementation are:
- only 2D and 3D data are supported
- only supports `sampling` where the value is the same for all axes (i.e. square pixels/voxels)

One other caveat is that it involves creating a `RawModule` for non-trivial kernels developed by a 3rd party. That code is MIT licensed, so I don't think it is an issue aside from possible maintenance burden. As far as I am aware, we don't really have any `RawModule` code within CuPy itself outside of some test cases?

**Comment by leofang** [comment]
We have some `RawModule` instances in the codebase (and outside of the test suite). I wouldn't worry about it.

**Comment by grlee77** [comment]
Not `RawModule`, but I remembered that I did use the closely related `RawKernel` for ndimage [spline prefiltering](https://github.com/cupy/cupy/blob/master/cupyx/scipy/ndimage/_spline_prefilter_core.py#L261)

**Comment by GenevieveBuckley** [comment]
I'd be keen to have this function directly available from cupy.

In fact, I went looking for it today in `cupyx.scipy.ndimage`, and almost assumed if it wasn't there it didn't exist. Luckily found https://github.com/rapidsai/cucim/pull/318 and will try it out from `cucim` first.

**Comment by GenevieveBuckley** [comment]
> Filed issue upstream ( #7400 ) about moving this over to CuPy

I'm a little confused, isn't that effectively a duplicate issue of this one that is already filed in the upstream (cupy) repository?

**Comment by jakirkham** [comment]
Oops for some reason was thinking this was on Dask-image 🤦‍♂️

Yeah will close that

**Comment by grlee77** [comment]
> In fact, I went looking for it today in cupyx.scipy.ndimage, and almost assumed if it wasn't there it didn't exist. Luckily found https://github.com/rapidsai/cucim/pull/318 and will try it out from cucim first.

We first release it in the cuCIM 2022.08 release, but it was still missing support for a few of the kwargs at that time (`sampling` and user-provided output arrays). These were added recently in 2022.12 along with performance improvements so it should be ready for incorporation here now. The only remaining difference from SciPy should be that we only have kernels for 2D and 3D rather than a general nD implementation. That should be good enough to cover the majority of use cases, though.

The nD algorithm that should be fairly easy to implement is the brute force one (`distance_transform_bf`), but performance would be MUCH slower than a better algorithm, so I think it is low priority.

**Comment by GenevieveBuckley** [comment]
Nice work @grlee77!
