### ISSUE TITLE
Discussion: Restore (or document how to restore) the old `Device` context manager behavior (pre-v10)?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#6965]
Follow-up of #5705, #6867. 

For downstream libraries depending on CuPy, having a context manager that respects any `cudaSetDevice`/`cudaGetDevice` calls inside _or outside_ CuPy is useful. However, this is not possible since v10. 

We are investigating this following snippet as a workaround:
```python
@contextlib.contextmanager
def device_ctx(new_device_id):
    """
    old_device_id = cp.cuda.runtime.getDevice()
    try:
        if old_device_id != new_device_id:
            cp.cuda.runtime.setDevice(new_device_id)
        yield
    finally:
        # We should always restore the old device at exit.
        cp.cuda.runtime.setDevice(old_device_id)
```
For comparison this is what CuPy is currently doing:
https://github.com/cupy/cupy/blob/fc04c9445f488272c9a1b78999e4e0df15a721b5/cupy/cuda/device.pyx#L180-L191
Compare it with CuPy's ctx mgr, we solely rely on the facts that
1. CUDA device context has a per-thread state, so we don't need a thread-local stack.
2. The `device_ctx` is implemented such that it is stateless (which is critical when leaving the context). Each `device_ctx` instance keeps its own `old_device_id` thanks to the `contextmanager` decorator.

This snippet has passed CuPy's device tests. I am wondering what have we missed in CuPy earlier? I assume it is not possible for CuPy to adopt this approach given that CuPy's `Device` is stateful. If so, perhaps we can at least document it?

**Comment by emcastillo** [comment]
We discuss this and think this is reasonable to do.

**Comment by kmaehashi** [comment]
@leofang, thanks for raising this. I had discussion with core team members and concluded it's better to revert the v9 behavior in v12.

The motivation of the change in CuPy v10 was to align the behavior with that of `cupy.cuda.Stream` API (#5705), which was also changed in CuPy v10 to allow per-device & per-thread stream management (#3980). At that time I thought `cupy.cuda.Device` API change is fine, but it seems we overlooked that Device states are shared between libraries, in contrary to the concept of "default stream" which is clsoed to each library (CuPy, PyTorch, etc.). Supporting the interoperability between libraries is obviously important requirement for us, and v9 behavior is actually better in terms of that.

FYI, PyTorch's `device` context manager also uses the same strategy as in CuPy v9: https://github.com/pytorch/pytorch/blob/0ac2986d3334f8f9b35ca2fa7a30c20022c26fa6/torch/cuda/__init__.py#L265-L289

**Comment by leofang** [comment]
@kmaehashi could you assign this task to me so I don't drop the ball?

**Comment by leofang** [comment]
@kmaehashi @emcastillo I took some time to refresh my memory and did some investigation. My understanding is that the fix is very simple, but it must be a breaking change, mainly users should get their code updated, see below.

Based on my original post, the [expected semantics](https://github.com/cupy/cupy/issues/6965#issuecomment-1231671294) requires that the previous ID to _not_ be stored as a state of the object. However, this is not possible when creating a context manager with the `__enter__` and `__exit__` methods of a class, as we need a way to pass this info between the methods. This rules out the **single-use** context manager, as [defined here](https://docs.python.org/3/library/contextlib.html#single-use-reusable-and-reentrant-context-managers).

The next viable, also breaking approach is to store the previous ID _and_ to document it as a "**reusable, but not reentrant**" context manager (which PyTorch also follows). What it means is that storing the created `Device` objects and reusing them in the subsequent code
```python
dev0 = cp.cuda.Device(0)
dev1 = cp.cuda.Device(1)

# do arbitrary work with the same objects dev0 & dev1
with dev0:
    with dev1: 
        ...
```
will likely be unsafe (breaking the expected semantics). Any user code must rewrite to use each instance exactly once, _as if_ they are single-use context managers:
```python
# always recreate the Device object
with cp.cuda.Device(0) as dev0:
    with cp.cuda.Device(1) as dev1: 
        ...
```
This is how PyTorch got around of this awkwardness IIUC. If this is OK I'll send a PR.

**Comment by kmaehashi** [comment]
Sorry for the delay here Leo, it seems I got lost track of the discussion. Isn't it insufficient to revert #5853 to meet https://github.com/cupy/cupy/issues/6965#issuecomment-1231671294?

**Comment by leofang** [comment]
@kmaehashi I don't remember the detail, you might be right but I don't have time to evaluate it carefully this week 😅 Perhaps you can just send a revert PR and close #7315?
