### ISSUE TITLE
Undocumented coding styles

### ISSUE THREAD

**Issue by Hakuyume** [cupy/cupy#700]
There are some undocumented coding styles.

- Use `[]` instead of `list()` (https://github.com/cupy/cupy/pull/632#discussion_r148426461)
- Use single quote `'` instead of double quote `"` for regular string literals (https://github.com/cupy/cupy/pull/632#discussion_r148437096)

It is hard for contributors to guess these rules because of inconsistency in the existing codes.
I think these rules should be documented if contributors should follow them.

**Comment by kmaehashi** [comment]
Documented in https://github.com/cupy/cupy/wiki/Development-policies
