### ISSUE TITLE
GPU memory optimization options: mark const array & malloc once, and grow (copy new value from CPU) incrementally

### ISSUE THREAD

**Issue by mw66** [cupy/cupy#7016]
### Description

Suppose I need to call a kernel function in a loop:

```
a = cp.zeros((100,))
for i range(100):
  a[i] = next_random()   # i.e. append new value at the last
  my_kernel(a[:i], b)    # b never change, is a constant
```

what I'm expecting for the best performance is that:

1) `b` is malloc-ed and value copied from CPU to GPU only once at the 1st iteration of the loop, and in the remaining loop iterations, there is no need to upload `b` again to GPU.  Is there a way to mark `b` as a constant array in cupy?

2) `a` is malloc-ed only once (with 100 element capacity) on the GPU; in subsequent calls, only a single value `a[i]` is copied from CPU to GPU (not the whole `a` again).

I'm wondering if this is the current behavior (how can I tell how many times memory is allocated, and copied?), esp. for question (1) how to mark `b` as const, and it need to be malloc-ed and copied only *once*?

If it's not, can we add these as feature request for the best GPU memory optimization options?

Thanks.

**Comment by emcastillo** [comment]
No values are being copied to the GPU in every call. The arrays live in the GPU the whole time so no data movement is happening other than the creation of the arrays.
Also cupy uses a memory pool so the amount of calls to `cudaMalloc` and `cudaFree` is really low.

**Comment by mw66** [comment]
"No arrays are being copied to the GPU in every call other than pointers."

So in my example, cupy can tell 'b' is a const, and only 'a[I]' is copied each time? the copy is minimal already?

**Comment by emcastillo** [comment]
a[i] is never copied, a view is created and a pointer is just passed.

b is always in gpu memory so there is no copy

**Comment by mw66** [comment]
"a[i] is never copied"?

At least, it need to copy the value of next_random() which is a CPU function?

```
a[i] = next_random()  # CPU function
```

**Comment by emcastillo** [comment]
use cupy random api to create random numbers directly in gpu memory using curand, otherwise you will incur in cpu/gpu synchronization

**Comment by mw66** [comment]
OK, thanks.

In my above example `next_random()` is a bad chosen function name for illustration purpose, which in real usage is a cpu function. Anyway I will try to optimize it see if it can be done on GPU.

**Comment by mw66** [comment]
BTW, is it possible (and how) to get the raw C pointer of a cupy array on you, and pass to and call a raw .cu function:

https://github.com/garrettwrong/cuTWED/blob/master/src/cuTWED.h#L107

**Comment by emcastillo** [comment]
yes, check RawKernel and RawModule usage!

**Comment by mw66** [comment]
Thanks!
