### ISSUE TITLE
Incorrect row sum of a dense matrix

### ISSUE THREAD

**Issue by xiangsheng1325** [cupy/cupy#7029]
## What happened
When I calculated the row sum of a $100k \times 100k$ matrix, I found that the result of sparse matrix is different from the one of dense matrix.

## What I expected to happen
I expected to have the same result when I calculate row sum of a matrix no matter whether sparse the matrix is.

### To Reproduce

```python3
>>> import cupy as cp
>>> nedge = 1500000
>>> nnode = 100000
>>> src = (cp.random.rand(nedge) * nnode).round().astype(int)
>>> dst = (cp.random.rand(nedge) * nnode).round().astype(int)
>>> adj_sparse = cp.sparse.coo_matrix((cp.full((nedge,), 1.), (src, dst))).tocsr()
>>> adj_dense = cp.full((nnode, nnode), False)
>>> adj_dense[src, dst] = True
>>> adj_sparse.sum(0)
array([[ 5., 16., 17., ..., 18., 18.,  6.]])
>>> adj_dense.sum(0)
array([14, 14, 16, ..., 12, 17, 11])
```

### Environment

OS                           : Linux-3.10.0-1160.66.1.el7.x86_64-x86_64-with-glibc2.10
Python Version               : 3.8.13
CuPy Version                 : 10.6.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.22.4
SciPy Version                : 1.9.0
Cython Build Version         : 0.29.30
Cython Runtime Version       : None
CUDA Root                    : None
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 11070
CUDA Runtime Version         : 11050
cuBLAS Version               : (available)
cuFFT Version                : 10600
cuRAND Version               : 10207
cuSOLVER Version             : (11, 3, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 5)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 87d8ccd
cuDNN Build Version          : 8401
cuDNN Version                : 8401
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 3090
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:01:00.0

**Comment by xiangsheng1325** [comment]
I would like to add: 
The row sum result of the sparse matrix is correct, and the result of the dense matrix is wrong.

**Comment by emcastillo** [comment]
Hi, We looked in this issue and found that this happens for smaller sizes (even 10x10 matrix will show different results)
but we saw that, doing `adj_sparse.todense().sum(0)` shows the same result as sparse one.

There are two issues in your code.
1 - Sparse matrix has one additional row and column compared to the dense one due to the use of `round()`
2 - The sparse matrix is doing additions when setting the elements, so some of the entries have values > 1
      In the dense one you are essentially doing `True` + `True` which results in `True` being it 1.

Probably if you use just regular scipy/numpy you will see the same issue.

**Comment by xiangsheng1325** [comment]
# Reply to emcastillo
Thank you very much for pointing out my error.
I fixed this problem through make every element occur only once.
however, the incorrect row sum result still remains.

## What happened
similar to previous code, I randomly generate many entries, including some duplicated entries.
```python
>>> import cupy as cp
>>> nedge = 1500000
>>> nnode = 100000
>>> src = (cp.random.rand(nedge) * nnode).round().astype(int)
>>> dst = (cp.random.rand(nedge) * nnode).round().astype(int)
```

Then, I add following code to avoid duplicate entries of each element in the matrix.
```python
>>> edges = cp.stack([src, dst], axis=1)
>>> sortarr = edges[cp.lexsort(edges.T[::-1])]
>>> mask = cp.empty(edges.shape[0], dtype=cp.bool_)
>>> mask[0] = True
>>> mask[1:] = cp.any(sortarr[1:] != sortarr[:-1], axis=1)
>>> unique_edges = sortarr[mask]
>>> src = unique_edges[:, 0]
>>> dst = unique_edges[:, 1]
>>> nedge = unique_edges.shape[0]
```

After that, the incorrect result will happened in $100k$ matrix.
```python
>>> adj_sparse = cp.sparse.coo_matrix((cp.full((nedge,), 1.), (src, dst))).tocsr()
>>> adj_dense = cp.full((nnode+1, nnode+1), False)
>>> adj_dense[src, dst] = True
>>> adj_sparse.sum(0)
array([[ 7., 21., 20., ..., 14., 16.,  7.]])
>>> adj_dense.sum(0)
array([13, 14, 10, ..., 15, 17, 20])
```

## What I expected to happen
I expect to have the same result from the sparse matrix and dense matrix as follows:
```python
>>> import cupy as cp
>>> nedge = 150000
>>> nnode = 1000
>>> src = (cp.random.rand(nedge) * nnode).round().astype(int)
>>> dst = (cp.random.rand(nedge) * nnode).round().astype(int)
>>> edges = cp.stack([src, dst], axis=1)
>>> sortarr = edges[cp.lexsort(edges.T[::-1])]
>>> mask = cp.empty(edges.shape[0], dtype=cp.bool_)
>>> mask[0] = True
>>> mask[1:] = cp.any(sortarr[1:] != sortarr[:-1], axis=1)
>>> unique_edges = sortarr[mask]
>>> src = unique_edges[:, 0]
>>> dst = unique_edges[:, 1]
>>> nedge = unique_edges.shape[0]
>>> adj_sparse = cp.sparse.coo_matrix((cp.full((nedge,), 1.), (src, dst))).tocsr()
>>> adj_dense = cp.full((nnode+1, nnode+1), False)
>>> adj_dense[src, dst] = True
>>> adj_sparse.sum(0)
array([[ 58., 151., 149., ..., 115., 139.,  72.]])
>>> adj_sparse.todense().sum(0)
array([ 58., 151., 149., ..., 115., 139.,  72.])
>>> adj_dense.sum(0)
array([ 58, 151, 149, ..., 115, 139,  72])
```
As you can see, the three row sum results of a $1k \times 1k$ matrix is correct. And I expected the same observations on $100k \times 100k$ matrix.

Thank you again for your effort.

**Comment by xiangsheng1325** [comment]
I would like to add:
The row sum result of scipy/numpy is correct. And the incorrect row sum appears only when I use large number of nodes in cupy.
