### ISSUE TITLE
Can the @ operation select csrgemm2 when spgemm run out of memory? 

### ISSUE THREAD

**Issue by WangRuiwei** [cupy/cupy#7044]
I tested a GPU which only has 6GB memory.
I tried to compute the dot product between two small csr matrices (both are 600x600).
It seems that spgemm requires more than 6GB memory.
In contrast to spgemm,  csrgemm2 works very well.

Can I configure that the @ operation selects csrgemm2 if spagemm requires too much memory?

The code I tested is:
import numpy as np
import cupy as cp
from scipy.sparse import csr_matrix

x_cpu = csr_matrix(np.ones((600,600)))
x_gpu = cp.sparse.csr_matrix(x_cpu)
x_g = x_gpu@x_gpu

**Comment by takagi** [comment]
Thanks for reporting. We roughly checked the memory usage of `cupy.cusparse.spgemm` and `cupy.cusparse.csrgemm2`, and found curious difference (spgemm ~6gb vs. csrgemm2 ~1gb). We'll check it further.

As a workaround, you can call `cupy.cusparse.csrgemm2` directly as `@` operator internally does. `cupy.cusparse` is not our public API, but it is not likely change soon.

https://github.com/cupy/cupy/blob/c2d3822d00b9e2f0656f98507746c8d76f7cfb10/cupyx/scipy/sparse/_csr.py#L152-L162

**Comment by WangRuiwei** [comment]
Thanks for replying. I will try to directly call csrgemm2.
From the introduction of spgemm given in [https://docs.nvidia.com/cuda/cusparse/index.html](url), it seems spgemm needs to estimate an upper bound of the memory used in the computation.
However, it is a bit strange, the current spgemm uses an upper bound which can be much greater than the size of dense matrices.
