### ISSUE TITLE
cupy.apply_along_axis failed with cupy.nonzero

### ISSUE THREAD

**Issue by Satori1313** [cupy/cupy#7061]
### Description

cp.apply_along_axis(cp.nonzero, 1, cp.array([[1,2],[2,3]])) - failed with error

*** AttributeError: 'tuple' object has no attribute 'shape'

np.apply_along_axis(np.nonzero, 1, np.array([[1,2],[2,3]])) - is OK

UPDATE. Problem in _shape_base.py. 
line 53:
buff = cupy.empty(inarr_view.shape[:-1] + res.shape, res.dtype)

res - is tuple (as a result of cp.nonzero(1d array) of single cupy-array, so line 44 ( if cupy.isscalar(res):) doesnt convert it from tuple to cupy-array

as a temporal solution is possible to use "buffer-like" function
def cupy_nonzero (a):
    return cp.nonzero(a)[0]

### To Reproduce

```py
cp.apply_along_axis(cp.nonzero, 1, cp.array([[1,2],[2,3]]))
```

### Environment

```
# Paste the output here
```

**Comment by asi1024** [comment]
@Satori1313 If the number of nonzero elements in each axis is different, as in the following example, it will not work even if you use NumPy.

```py
>>> np.apply_along_axis(np.nonzero, 1, np.array([[1,0],[2,3]]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in apply_along_axis
  File "***/numpy/lib/shape_base.py", line 402, in apply_along_axis
    buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))
ValueError: could not broadcast input array from shape (1,2) into shape (1,1)
```

Do you mean that you want it to work for inputs that you know have the same number of nonzero elements?

**Comment by Satori1313** [comment]
@asi1024 Yes, of course))) 
Only if we have the same number of nonzero elements along axis.

**Comment by asi1024** [comment]
@Satori1313 Thanks for your reporting! I will make a fix soon.

However, please note that `cupy.apply_along_axis` is supported only for interface compatibility with NumPy. What `cupy.apply_along_axis` do is just call the given function multiple times without parallelization.

https://github.com/cupy/cupy/blob/d588608a45e14d41bda6057cdb23daef3e40ae85/cupy/lib/_shape_base.py#L57-L58

How about the following algorithm that does not use `apply_along_axis`, to fully use the power of your GPU?

```py
>>> x = cupy.array([[1, 0, 0, 1, 1], [0, 1, 1, 0, 1]])
>>> cupy.nonzero(x)[1].reshape(x.shape[0], -1)
array([[0, 3, 4],
       [1, 2, 4]])
```

**Comment by Satori1313** [comment]
@asi1024 Thank you very much!!! I miss that fact! 
And you really help me! Regarding you I can rewrite my func 2x faster!! Thanks again!
