### ISSUE TITLE
Thrust memory allocation error

### ISSUE THREAD

**Issue by unnonouno** [cupy/cupy#707]
Thrust allocates memory in its implementation. When there is not enough memory and it causes bad-alloc, a program is crashed even when CuPy's memory allocator keeps unused memory.
I have three implementation ideas:
- Pass working space to thrust routine (but i don't know if it is possible)
- When thrust fails to allocate memory, free memory CuPy's memory allocator keeps, and then retry thrust routine (easy to implement)
- Make a new memory allocator for thrust that shares memory with CuPy's memory allocator (i don't know if it is possible)

**Comment by takagi** [comment]
It seems that I missed to remove memory allocation in the code using Thrust. At least for now, such rotines are to be implemented with the first option.

**Comment by kmaehashi** [comment]
There is a similar issue with cuFFT. For that issue workaround using the second idea has been implemented. #1219

**Comment by kmaehashi** [comment]
Ref. #1289. I fixed to avoid crash when Thrust memory error (raise RuntimeError instead).

I looked into the Thrust docs and headers, but it seems hard to inject external memory allocator or buffer.
