### ISSUE TITLE
cython-free implementation

### ISSUE THREAD

**Issue by andrei-pokrovsky** [cupy/cupy#7074]
### Description

This is more of a suggestion than a feature request. Since Cython has limited performance, features and requires additional learning in addition to C++/CUDA for navigating around the library. In addition it complicates debugging. I would suggest rewriting all the glue in pybind11 since this would limit the number of languages required to understand the library as well as give better control of performance (for C++ portions of code) and simplify debugging.

**Comment by emcastillo** [comment]
That would be great, but the code base is too big to start a full rewriting from scratch and reach the same level of compatibility with our current resources in a realistic timeframe.

**Comment by kmaehashi** [comment]
Let me close this one, as this has been inactive for a while and also we don't have a plan to stop using Cython, as @emcastillo suggested. We are always trying to keep the library stable, but if you encounter any problem we are always happy to help through issues or gitter chat.
