### ISSUE TITLE
Add sparse tensor support to cp.ElementwiseKernel

### ISSUE THREAD

**Issue by sambaPython24** [cupy/cupy#7106]
### Description

Hello, I would appreciate if one could use the ```cp.ElementwiseKernel``` (and all the other custom kernels) also for sparse tensors.

### Additional Information

Example: 

```python
import cupy
import cupyx

# Coo Matrix
data  = cupy.array([1, 1, 1, 1, 1, 1], 'f')
row  = cupy.array([0, 1, 1, 2, 2, 2], 'i')
col   = cupy.array([0, 0, 1, 0, 1, 2], 'i')

A     = cupyx.scipy.sparse.coo_matrix((data, (row, col)), shape=(3, 3),dtype=cupy.float32 )
B     = cupyx.scipy.sparse.csr_matrix((data, (row, col)), shape=(3, 3) ,dtype=cupy.float32)
C     = cupyx.scipy.sparse.csc_matrix((data, (row, col)), shape=(3, 3) ,dtype=cupy.float32)

squared_diff = cp.ElementwiseKernel(
   'float32 x, float32 y',
   'float32 z',
   'z = (x - y) * (x - y)',
   'squared_diff')

# Elementwise Kernel for Sparse Matrices.
# Same for A,A ; B,B; C,C
squared_diff(C,C)
# (C-C)*(C-C) works work.
```

**Comment by takagi** [comment]
Thanks for posting an issue, but it would be generally hard to have efficient elementwise operations on sparse matrices.

**Comment by sambaPython24** [comment]
Could you not just apply it to the values and leave the indices constant? (Depending on how you stored the tensor on CUDA)

**Comment by leofang** [comment]
You can, but it will be your responsibility to ensure the subsequent usage of the data is still operating on a valid sparse tensor. Consider `x-y` as a trivial example, if the result is 0 then your sparse tensor is not supposed to store it, but `ElementwiseKernel` would not do any magic for you, you'd have to ensure the zeros are purged before the next sparse matrix operation.

**Comment by leofang** [comment]
Perhaps you can just call `arr.eliminate_zeros()` after `ElementwiseKernel`.

**Comment by leofang** [comment]
I modified my example above as I see what @takagi had in mind. The old example `x-y` needs great care because the sparse matrices `x` and `y` may not have same indices for their nonzeros.
