### ISSUE TITLE
Add cupy.sparse.sum to the list of functions

### ISSUE THREAD

**Issue by sambaPython24** [cupy/cupy#7109]
### Description

For sparse matrices of the form 
```python 
import cupy
import cupyx

# Coo Matrix
data  = cupy.array([1, 1, 1, 1, 1, 1], 'f')
row  = cupy.array([0, 1, 1, 2, 2, 2], 'i')
col   = cupy.array([0, 0, 1, 0, 1, 2], 'i')

A     = cupyx.scipy.sparse.coo_matrix((data, (row, col)), shape=(3, 3),dtype=cupy.float32 )
B     = cupyx.scipy.sparse.csr_matrix((data, (row, col)), shape=(3, 3) ,dtype=cupy.float32)
C     = cupyx.scipy.sparse.csc_matrix((data, (row, col)), shape=(3, 3) ,dtype=cupy.float32)
```
it would be great to be able to sum along an axis. While $A*A,A+A,A-A$ seems to work, this is a feature that is missing in order to work with the tensors in many applications.

**Comment by kmaehashi** [comment]
Is this what you are looking for?
https://docs.cupy.dev/en/stable/reference/generated/cupyx.scipy.sparse.csr_matrix.html#cupyx.scipy.sparse.csr_matrix.sum

**Comment by sambaPython24** [comment]
Yes, but it seems to be odd, that the result of this operation is a dense matrix. With sparse.sum I mean, that the result is a sparse tensor again.

**Comment by leofang** [comment]
It does not make any sense. If `sum` reduces from 2D to 1D, there's currently no sparse matrix format that can support 1D sparse array. If `sum` reduces from 2D to 0D, then using a `ndarray` to hold the result is perfectly fine. Finally, CuPy follows SciPy's behavior, and SciPy's sparse sum does return dense format too.

**Comment by kmaehashi** [comment]
Closing as inactive for a while. Please feel free to reopen if you still need help.
