### ISSUE TITLE
[Discussion needed] Add ways to write `inf` and `nan` as literals in fused and user-defined kernels.

### ISSUE THREAD

**Issue by berryboy2012** [cupy/cupy#7118]
### Description

Currently, literals such as `inf` and `nan` cannot be used inside a `ElementwiseKernel` or a fused kernel. 
To test whether that's the case, we can write down the following code.
```python
@cp.fuse
def test_inf_nan(arr):
    arr[:] = cp.inf
    arr[:] = cp.nan
    arr[:] = 0
    return arr
print(test_inf_nan(cp.linspace(0,4,10)))
```
The compiler will spit out two errors regarding the fused kernel:
```
error: identifier "inf" is undefined
error: a value of type "double (*)(const char *)" cannot be used to initialize an entity of type "const double"
```
However, I am not so sure whether this is something that could be useful. Here are some of the pros and cons that I can think of:

pros:
- Functions that accept those literals will have a easier time when being fused. Such as `cupy.clip`.
- It might be helpful for compile-time-optimizations.

cons:
- The actual use case for those literals is quite scarce.
- We can always store those literals inside a variable and pass them into the kernels when calling the functions instead.

Any suggestions would be appreciated, thanks in advance!

**Comment by kmaehashi** [comment]
I guess it's only a matter of float-to-string conversion here.
https://github.com/cupy/cupy/blob/3ac3f9d6bffac33bccd236fc4306a2f83b90c4f5/cupy/_core/fusion.pyx#L121-L122

Maybe @asi1024 can better follow up on this :)

**Comment by asi1024** [comment]
@berryboy2012 Thank you for your reporting. Fixed in #7122!

**Comment by berryboy2012** [comment]
Thanks for the help! Another question though, if for some reason I want to write `inf` or `nan` inside a kernel such as `cupy.RawKernel`, do I just use things like `CUDART_INF_F` `CUDART_NAN_F` etc as mentioned in https://github.com/cupy/cupy/blob/master/cupy/_core/include/cupy/math_constants.h ?

**Comment by kmaehashi** [comment]
Yes, these constants should be available if you `#include <math_constants.h>` in RawKernrel.
