### ISSUE TITLE
Extreme time deviations when using different timing tools

### ISSUE THREAD

**Issue by Joachimoe** [cupy/cupy#7185]
### Description

When doing benchmarking of CuPY, it is stated in https://readthedocs.org/projects/cupy/downloads/pdf/stable/ that one should use the ```cupyx.profiler.benchmark```tool. However, this seems to report extreme results -- and possibly wrong -- results as well. 

If I wish to access the CPU time of the benchmark object, one would imagine that this would provide the same results as then timing with the Python built-in ```time``` module -- or to some extend at least. 

Currently, I am benchmarking DASK-CUDA code, and I use your functionality to test the average time over 20 repetitions. However, this is by over a factor of 11.000 smaller than what I obtain using normal timing functions, which leads to suspicious results when benchmarking CuPY code as well. 

I opened a bug issue saying that the documentation on the benchmark is too sparse, and that some weird time conversions are done under the hood, why the reliability of the tool is questionable. Therefore, I hope to obtain some insights as to whether my program is *wrong* or if I am timing incorrectly. 

### To Reproduce

```py
import cupy as cp
import numpy as np
import dask.array as da
from dask_cuda import LocalCUDACluster
from dask.distributed import Client, wait
import rmm
import sys
import time
from helpers import *

from cupyx.profiler import benchmark

def generate_array(size, work_units):
    rs = da.random.RandomState(RandomState=cp.random.RandomState)
    rs = rs.randint(low = 0, high = 100_000, size = (size, work_units), chunks = 'auto')
    rs = rs.map_blocks(cp.asarray)

    return rs

def multiplication(arr):
    array_mult = da.multiply(arr, 42).persist()
    wait(array_mult)
    


if __name__ == '__main__':

    cluster = LocalCUDACluster('0', rmm_managed_memory=True)
    client = Client(cluster)
    client.run(cp.cuda.set_allocator, rmm.rmm_cupy_allocator)


    rmm.reinitialize(managed_memory=True)
    cp.cuda.set_allocator(rmm.rmm_cupy_allocator)

    size = int(sys.argv[1])
    wk   = int(sys.argv[2])
    arr = generate_array(size, wk)
    start = time.time()
    y   = benchmark(multiplication, (arr, ), n_repeat=20, n_warmup=5)
    end = time.time()
    print(f"{(end-start)*1000} ms")
    print(f"{np.average(y.cpu_times) + np.average(y.gpu_times)} ms")
```

### Environment

```
OS                           : Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Python Version               : 3.9.13
CuPy Version                 : 10.6.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.22.4
SciPy Version                : 1.9.1
Cython Build Version         : 0.29.30
Cython Runtime Version       : None
CUDA Root                    : /home/joachim/anaconda3/envs/rps
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 11070
CUDA Runtime Version         : 11050
cuBLAS Version               : (available)
cuFFT Version                : 10600
cuRAND Version               : 10207
cuSOLVER Version             : (11, 3, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 5)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 87d8ccd
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : 21212
NCCL Runtime Version         : 21403
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce GTX 1660 SUPER
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0
```

**Comment by kmaehashi** [comment]
```
    start = time.time()
    y   = benchmark(multiplication, (arr, ), n_repeat=20, n_warmup=5)
    end = time.time()
    print(f"{(end-start)*1000} ms")
    print(f"{np.average(y.cpu_times) + np.average(y.gpu_times)} ms")
```

Comparison between these prints does not make sense -- the `benchmark` function runs the target function for 20+5 times.

> I opened a bug issue saying that the documentation on the benchmark is too sparse, and that some weird time conversions are done under the hood, why the reliability of the tool is questionable. Therefore, I hope to obtain some insights as to whether my program is wrong or if I am timing incorrectly.

I've updated the docs recently. Feedbacks/contributions are highly welcomed :)
https://docs.cupy.dev/en/latest/reference/generated/cupyx.profiler._time._PerfCaseResult.html#cupyx.profiler._time._PerfCaseResult

**Comment by Joachimoe** [comment]
My apologies. The documentation is my bad and I did not catch the additions. Looks awesome :-) 

I agree -- my initial attempt here was wrong. However, when I remove the ```n_warmup``` and only have ```n_repeat = 20``` and I divide my Python timer with 20 afterwards, I still have very large differences, i.e. 

39 ms vs. 0.07 ms. That is still a factor 500 difference. I am fully aware the the Python time module is not capable of correcting timing it. I just find it suspicious that the Benchmark CPU times are so vastly different than just regular timing in Python. Which ones should I trust?

In actuality, I just wanted to make sure that taking the average over GPU and CPU times are correct as I will be using the results.

**Comment by emcastillo** [comment]
The first time a function is run, the code is compiled/loaded from the disk cache, so the CPU time is pretty high.

Successive invocations of the kernel are much faster. The first time is discarded if you use `n_warmup` so that may be what you are seeing as the discrepancy source between CPU & GPU times.
Just putting a time.start() and time.end() before the function will be distorted.

If you call the function before doing this, the time you capture will be much more accurate.

**Comment by kmaehashi** [comment]
@Joachimoe I think what you want is the "GPU times" reported by `cupyx.profiler.benchmark`.

"CPU times" show times taken to execute the function. However, as GPUs run asynchronously from CPUs, these values do not indicate the "real" time required -- the GPU might still be running the code enqueued by that function. So `cupyx.profiler.benchmark` waits for the GPU (i.e., synchronizes the device) and computes the "real" overall runtimes of the function as "GPU times", which is more reasonable for benchmarking/comparison. Still that "CPU times" is a useful indicator of unexpected synchronization or kernel launch overheads.

I think the code describes it better :)
https://github.com/cupy/cupy/blob/master/cupyx/profiler/_time.py

The above information is covered here but maybe could be improved for readers unfamiliar with the concept of CUDA events etc.
https://docs.cupy.dev/en/stable/user_guide/performance.html#benchmarking

**Comment by JoachimMoe** [comment]
Thank you @emcastillo and @kmaehashi -- Turns out I was a bit confused as to when what happens. I assume that your timing function will work correctly for other libraries as well, such as DASK-CUDA? Or are there things I should be wary of when using your benchmarking tool for other GPU-programming tools?

**Comment by kmaehashi** [comment]
> Or are there things I should be wary of when using your benchmarking tool for other GPU-programming tools?

`cupyx.profiler.benchmark` should work with other GPU libraries as well, as long as streams are not manipulated during the target function.

**Comment by Joachimoe** [comment]
Thanks a lot. I will go with the results given by your benchmark then, even though it seems a bit amazing. The following:

```
import sys
import cupy as cp
from cupyx.profiler import benchmark
from helpers import *

def generate_array(size, work_units):
    rand = cp.random.default_rng()                             #This is the fast way of creating large arrays with cp
    arr = rand.integers(0, 100_000, (size, work_units))        #Create array
    return arr

def multiplication(arr):
    y = cp.multiply(arr, 42) ## Multiply by 42, randomly chosen number
    return y

def bench(arr):
    r = multiplication(arr)
    return r 


if __name__ == '__main__':
    sz = int(sys.argv[1])
    wk = int(sys.argv[2])

    arr = generate_array(sz, wk)
    y = benchmark(bench, (arr, ), n_repeat= 20)
    print(cp.average(y.gpu_times))
```

Executes for a workload of size 262144000 in approximately 0.01 milliseconds. Run this program as ```python3 multiplication_benchmark.py 262144 1000```

**Comment by kmaehashi** [comment]
Hi, sorry for dropping a ball here... the docs should be `seconds` instead of `milliseconds`. I've just sent a fix in #7312.

**Comment by Joachimoe** [comment]
This makes way more sense, and now corresponds to other timing mechanisms as well.  May want to fix the methods as well, as they currently still print "us", microseconds, when calling the ```.gpu_times``` and ```cpu_times``` :-)

**Comment by kmaehashi** [comment]
The string representations seem correct (`us`), the record in `seconds` are multiplied by `1e6`.
https://github.com/cupy/cupy/blob/807d9c2864659d9eb0e551d540e8a0bd4c4deb35/cupyx/profiler/_time.py#L61-L63

**Comment by Joachimoe** [comment]
Would it be nice to have a single, uniform way of representing time within the cupy benchmarking framework? All of the confusion between ms, us, and seconds stemmed from the variation.
