### ISSUE TITLE
Non-default streams and RawKernel

### ISSUE THREAD

**Issue by jzrake** [cupy/cupy#7189]
### Description

Documentation of `RawKernel` [here](https://docs.cupy.dev/en/stable/user_guide/kernel.html) indicates that a stream argument can be passed to the raw kernel, but not how to do it. Meanwhile reference on `RawKernel.__call__` [here](https://docs.cupy.dev/en/stable/reference/generated/cupy.RawKernel.html#cupy.RawKernel.__call__ ) does not show a stream argument as being accepted. I found what I needed by looking in the source code.

My instinct was to use the stream as a context manager like so:

```python
with stream:
    my_kernel((10,), (64,), (arg1, arg2))
```

This did not result in concurrent kernel launches, I suppose because the implement of `RawKernel.__call__` does not look for a current stream that might have been set by a `Stream` context manager, or that's my impression anyway. The following solution seems fine to me, but I think it should be in the docs:

```python
my_kernel((10,), (64,), (arg1, arg2), stream=stream)
```

This makes me wonder when a stream that was set using the `Stream` context manager is respected by cupy-provided functions, e.g. is the "current" stream used when evaluating numpy-like expressions, for device-to-device transfers, etc?

**Comment by leofang** [comment]
It is respected internally: If an explicit stream is not passed, the current stream is picked:
https://github.com/cupy/cupy/blob/6d857add3d46368705e133121cf49153039952e9/cupy/cuda/function.pyx#L162-L166

**Comment by jzrake** [comment]
I just noticed this! thanks @leofang. I had a mistake in my diagnostics. I'll close this.
