### ISSUE TITLE
On x86_64, cupy-11.3.0 depends on cudatoolkit-10.2, while on arm64 dependens on cudatoolkit-11.7

### ISSUE THREAD

**Issue by chinasoul** [cupy/cupy#7201]
### Description

When I install cupy on arm64:
**conda install cupy -c conda-forge**
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    **cudatoolkit-11.7.0**         |      h254b3b0_10       824.4 MB  conda-forge
    cupy-11.3.0                |   py38ha9de562_1        53.4 MB  conda-forge
While on x86_64:
 **conda install cupy -c conda-forge**
The following NEW packages will be INSTALLED:

  cudatoolkit        conda-forge/linux-64::**cudatoolkit-10.2.89**-h713d32c_10 None
  cupy               conda-forge/linux-64::cupy-11.3.0-py38h69964f1_1 None

What is expected:
Both install latest cuda toolkit, i.e. 11.7

### To Reproduce

```py
conda install cupy -c conda-forge
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
# Paste the output here
```

**Comment by kmaehashi** [comment]
conda automatically picks the cudatoolkit version depending on the driver version. You can manually try specifying the cudatoolkit version:
https://docs.cupy.dev/en/latest/install.html#installing-cupy-from-conda-forge

**Comment by leofang** [comment]
I believe it means you better update your driver version in order to use cuda 11 on your x86-64 machine.

**Comment by chinasoul** [comment]
@kmaehashi @leofang actually the display driver version I used is an internal one which is higher than the public latest one.(So I suspect if the mechanism failed to recognize the version it will pick i.e. ctk10.2 now?)

**Comment by leofang** [comment]
What is your output of `conda info`? I also use the internal build but never see this situation...

**Comment by kmaehashi** [comment]
FYI, this is the logic conda uses to detect cuda driver version in the environment:
https://github.com/conda/conda/blob/main/conda/plugins/virtual_packages/cuda.py

**Comment by chinasoul** [comment]
Thanks @kmaehashi @leofang, so seems the mechanism requires CUDA pre installed in the system and check the libcuda.so version. Why need this requirement? My understanding is that conda environment is kind of standalone virtual environment, why need the outer system tell conda env to install which version of cuda toolkit?

**Comment by leofang** [comment]
I am not sure I understand the question. It only detects if a valid driver is installed (libcuda comes with driver, not CTK, it is just that often times a new CTK release may need a new driver to support, so they are bundled together), if so it's used to determine the max supported CTK version, if not it leaves to the users. 

Please, share the output of `conda info`.

**Comment by chinasoul** [comment]
Well, nvidia-smi version is 515, conda info is
```
     active environment : tmp
    active env location : /localhome/cuda/miniconda3/envs/tmp
            shell level : 1
       user config file : /localhome/cuda/.condarc
 populated config files :
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __cuda=11.7=0
                          __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /localhome/cuda/miniconda3  (writable)
      conda av data dir : /localhome/cuda/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /localhome/cuda/miniconda3/pkgs
                          /localhome/cuda/.conda/pkgs
       envs directories : /localhome/cuda/miniconda3/envs
                          /localhome/cuda/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Linux/5.4.0-131-generic ubuntu/20.04.5 glibc/2.31
                UID:GID : 1003:1031
             netrc file : None
           offline mode : False
```
Then "conda install cupy -c conda-forge"
## Package Plan ##

  environment location: /localhome/cuda/miniconda3/envs/tmp

  added / updated specs:
    - cupy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.9.24  |       ha878542_0         150 KB  conda-forge
    certifi-2022.9.24          |     pyhd8ed1ab_0         155 KB  conda-forge
    cudatoolkit-10.2.89        |      h713d32c_10       449.7 MB  conda-forge
    cupy-11.3.0                |   py38h69964f1_1        39.4 MB  conda-forge
    fastrlock-0.8              |   py38hfa26641_2          32 KB  conda-forge
    libblas-3.9.0              |15_linux64_openblas          12 KB  conda-forge
    libcblas-3.9.0             |15_linux64_openblas          12 KB  conda-forge
    libgfortran-ng-12.2.0      |      h69a702a_19          22 KB  conda-forge
    libgfortran5-12.2.0        |      h337968e_19         1.8 MB  conda-forge
    liblapack-3.9.0            |15_linux64_openblas          12 KB  conda-forge
    libopenblas-0.3.20         |pthreads_h78a6416_0        10.1 MB  conda-forge
    numpy-1.22.3               |   py38h99721a1_2         6.8 MB  conda-forge
    python_abi-3.8             |           2_cp38           4 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       508.1 MB

**Comment by leofang** [comment]
Sorry @chinasoul I dropped the ball. Your conda info hints that your conda env could be inconsistent. You have Python 3.9 installed, but you pick up CuPy build py38h69964f1_1 which is for Python 3.8. Could you post the output of `conda list`?

**Comment by leofang** [comment]
@chinasoul is the issue resolved?

**Comment by kmaehashi** [comment]
Closing as inactive for a while. Please feel free to reopen if you still need help.
