### ISSUE TITLE
cudaErrorMemoryAllocation out of memory on small cupy 2D Array

### ISSUE THREAD

**Issue by lvxhnat** [cupy/cupy#7216]
### Description

I am currently attempting to perform a matrix dot multiplication on an array of shape ```(203743, 58)``` that is ```47268376 bytes``` < which translates to ~47MB  (based on the cupy_arr.nbytes property). Element type is of float32. It looks something like this
```
cupy_embeddings
>>> array([[-0.24801952,  0.03326046, -0.04360366, ...,  0.08542228,
        -0.14727837, -0.07019955],
       [ 0.10431647,  0.00897771, -0.41141695, ..., -0.11367732,
         0.29030704,  0.9814857 ],
       [-0.26389217,  0.06340861, -0.07805258, ...,  0.10840404,
         0.35795462,  0.60609174],
       ...,
       [-0.06810182, -0.09526992, -0.20399192, ..., -0.21559024,
        -0.15372932,  0.05336821],
       [-0.3690567 , -0.43126023,  0.24766243, ..., -0.5343132 ,
        -0.07427472, -0.10231733],
       [-0.16150016, -0.26013005,  0.02716422, ..., -0.31335908,
         0.00497419, -0.15442419]], dtype=float32)
```

The error below occurs when I attempt to do 
```
cupy_embeddings.dot(cupy_embeddings.T)
```

<img width="1152" alt="Screenshot 2022-12-01 at 5 07 06 PM" src="https://user-images.githubusercontent.com/58301316/205011732-ace3147d-3cd1-41bd-803b-8384563bbed5.png">

using ```watch nvidia-smi``` memory usage even on 30,000 rows increases memory usage on GPU by  approximately ~4000MiB, which is huge, considering the size of the array, and this memory is not released subsequently (see screenshot, which is post running the operation)

<img width="555" alt="Screenshot 2022-12-01 at 5 07 41 PM" src="https://user-images.githubusercontent.com/58301316/205011845-2711d73b-f30a-437c-b214-bb5c7330db1f.png">

1. Why is this dot operation using so much GPU memory, and what can i do to reduce it?
2. How do I release the GPU memory?

### To Reproduce

```py
# Write the code here
```

### Environment

It came together with RAPIDS conda environment.
```
conda create -n env -c rapidsai -c nvidia -c conda-forge cudf=22.08 cuml=22.08 python=3.8 cudatoolkit=11.5
```

**Comment by emcastillo** [comment]
try this:

https://docs.cupy.dev/en/stable/user_guide/interoperability.html#rmm

CuPy & RMM have their own memory pools. CuPy allocates a large chunk of memory at the beginning to speedup allocations, this interferes with rmm.
https://docs.cupy.dev/en/stable/user_guide/memory.html

**Comment by kmaehashi** [comment]
> ```
> cupy_embeddings.dot(cupy_embeddings.T)
> ```

I think this is generating the output of 203743*203743*4 bytes ~= 154 GiB.
