### ISSUE TITLE
Private reporting of a security vulnerability

### ISSUE THREAD

**Issue by Sim4n6** [cupy/cupy#7231]
### Description

Dear Cupy team,

I have identified a security vulnerability in the codebase of cupy latest release.
I would like to report it privately. I suggest that you opt-in this Github [feature](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability) in order that the process goes smoothly.

![image](https://user-images.githubusercontent.com/13036531/206516732-8d2240a6-4c5f-45e2-a0ef-ec036b29bac4.png)

Kind consideration
@Sim4n6

### To Reproduce

I rather do that privately please.

### Installation

Source (`pip install cupy`)

### Environment

```
# Paste the output here
```

**Comment by kmaehashi** [comment]
Hi @Sim4n6, just enabled the feature.  Thanks for reporting!
