### ISSUE TITLE
Feature Request: GPU-accelerated drawing functions

### ISSUE THREAD

**Issue by Renzzauw** [cupy/cupy#7289]
### Problem description

Hi, 
I'm using tools such as Nvidia DALI & Video Processing Framework to decode & encode video frames on the GPU. To process & manipulate the individual video frames, I convert the GPU CUDA surfaces to CuPy arrays. This means I do all my operations as much on the GPU as possible. I would like to extend my current pipeline to be able to visualize various things, such as object detection output. The current problem is I have to convert my CuPy array to a CPU NumPy array (cv2 drawing functions) or Pillow Image to draw the bounding boxes, labels, confidence etc. and then transfer the result back to the GPU, meaning I need to transfer a lot of frames between hardware, which drastically impacts performance.

After doing a bit of research, I cannot seem to find any currently available tools to plot/draw in these images directly on the GPU or that support CuPy, so that's how I ended up with my feature request. 

I did manage to find the [VisPy](https://vispy.org/) package that contains various visualization tools based on OpenGL, however looking at [this issue](https://github.com/vispy/vispy/issues/1985), CuPy support is still not (fully) supported. 

### Feature request

More specifically, I'm looking for CuPy/GPU-accelerated drawing functions for:
- Drawing shape fills & outlines in a CuPy array, such as lines, ellipses, rectangles
- Drawing text in a CuPy array

**Comment by emcastillo** [comment]
Thanks for your feedback.
Unfortunately, we only support the NumPy/SciPy APIs with utilities & low-level APIs used to implement these.
Implementing this should be the responsibility of other libraries, such as VisPy. If they need some adjustments in CuPy array format for it to work, we are open to discussing it, but we won't be adding APIs to support drawing in CuPy.

**Comment by leofang** [comment]
AFAIK all OpenGL-CUDA interop APIs are available since CUDA Python 11.6: https://github.com/cupy/cupy/issues/5711#issuecomment-1016064970. The right way to go is for Vispy developers to give it a shot, and let the CuPy team if there's any higher level layers that are better to be built in CuPy for such interop. Neither NumPy nor CuPy has any thing to do with OpenGL or other graphics frameworks, and so it's not the right place for building graphics primitives and utilities.

**Comment by Renzzauw** [comment]
Hi, thanks for your explanations, this makes total sense to me. I'll close this issue.
