### ISSUE TITLE
[RFC] Renaming the development branch to `main` 

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7294]
Now that many projects around the scientific Python community converged to use `main` as the default branch for their repositories, I think it could make sense to do that for CuPy too.

According to https://github.com/github/renaming, side-effects of renaming a branch are very limited and I believe that it is less likely to cause confusion:

- Re-target any open pull requests
- Update any draft releases based on the branch
- Move any branch protection rules that explicitly reference the old name
- Update the branch used to build GitHub Pages, if applicable
- Show a notice to repository contributors, maintainers, and admins on the repository homepage with instructions to update local copies of the repository
- Show a notice to contributors who `git push` to the old branch
- Redirect web requests for the old branch name to the new branch name
- Return a "Moved Permanently" response in API requests for the old branch name

**Comment by leofang** [comment]
Perhaps this can be done when CuPy v12.0.0 is released?

**Comment by kmaehashi** [comment]
Once we agreed, I think just after the RC would be a good timing - cut branch for v12 and start dev on `main` for v13.

**Comment by leofang** [comment]
Ah yes I forgot that the branch is forked at the RC, not after a new major ver is out, it's better!

**Comment by kmaehashi** [comment]
The master branch is now named `main`.

If you have a local clone, you can update it by running the following commands.

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
