### ISSUE TITLE
Update DLPack support

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#7306]
There are two tasks:
- [x] Update to DLPack v0.8 (the last compatible version before API/ABI break): #7307 
- [x] Update to DLPack v1.0 (#8683)

I think we should do the first one now, before CuPy v11.5 (or v11.6) is released, and discuss the plan for the ABI break.

Feel free to assign this task to me, thanks!

**Comment by kmaehashi** [comment]
v0.8 support merged in #7307 (v12) and #7376 (v11).

**Comment by leofang** [comment]
The new DLPack 1.0 is imminent. I'll start working on it after array API standard v2023 is finalized (which includes DLPack 1.0 support).

**Comment by leofang** [comment]
Done in #8683!
