### ISSUE TITLE
nvcc cannot find a supported version of Microsoft Visual Studio between 2017 and 2019

### ISSUE THREAD

**Issue by js-compilatrum** [cupy/cupy#7314]
### Description

I start using cupy based spacy library. I got problem with NLP stuff. Problem is related to compiler. I got problem:

`nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions between 2017 and 2019 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler'`

To using cupy I simple add code modification in _compiler.py_ in function **_run_cc** (for simplicity I remove original comments):

```def _run_cc(cmd, cwd, backend, log_stream=None):
    try:
        env = os.environ
        if _win32:
            extra_path = _get_extra_path_for_msvc()
            if extra_path is not None:
                path = extra_path + os.pathsep + os.environ.get('PATH', '')
                env = copy.deepcopy(env)
                env['PATH'] = path
        cmd.insert(2, "-allow-unsupported-compiler") # My modification is here
        # print("cmd:", cmd,  "cwd:", cwd, "env: ", env)
        log = subprocess.check_output(cmd, cwd=cwd, env=env,
                                      stderr=subprocess.STDOUT,
                                      universal_newlines=True)
```

Now it is working without problem. I use Window 11, CUDA 11.8, try the same with python 3.9, 3.10, 3.11 (I have multiple version on my PC). I installed **first** Visual Studio 2022, then as **second** Visual Studio 2019. To resolve issue I try add to PATH path to file **cl.exe** from Visual Studio 2019, like:

C:\Programming\VisualStudio2019\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x86

as this file I found inside function _get_extra_path_for_msvc. At the end I have working system, but with modification of original source code. Could you suggest me and answer:

1. How resolve issue to avoid modification of source code of cupy at the future?
2. Do I select correct compiler file to use?
3. Is any better solution to add allow unsported compiler?

### To Reproduce

```py
from pathlib import Path

import spacy
spacy.require_gpu() # raise error if GPU is not available / misconfigured

TEXT = (Path.cwd() / "testfile.txt").read_text(encoding="utf8")

nlp = spacy.load("pl_core_news_lg")
doc = nlp(TEXT)
print("end")

```

### Installation

pip install spacy[cuda-autodetect] #installing version 3.4.4

### Environment

```
OS                           : Windows-10-10.0.22621-SP0
Python Version               : 3.10.9
CuPy Version                 : 11.4.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.24.1
SciPy Version                : None
Cython Build Version         : 0.29.32
Cython Runtime Version       : 0.29.33
CUDA Root                    : D:\ProgrammingApps\CUDA118
nvcc PATH                    : D:\ProgrammingApps\CUDA118\bin\nvcc.EXE
CUDA Build Version           : 11080
CUDA Driver Version          : 12000
CUDA Runtime Version         : 11080
cuBLAS Version               : (available)
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 8)
Thrust Version               : 101501
CUB Build Version            : 101501
Jitify Build Version         : 4a37de0
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 3060
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:01:00.0

```

### Additional Information

Error was raised inside **compiler.py** at function **_run_cc** in code:

```
        log = subprocess.check_output(cmd, cwd=cwd, env=env,
                                      stderr=subprocess.STDOUT,
                                      universal_newlines=True)
```

**Comment by kmaehashi** [comment]
I'd suggest using `'spacy[cuda-autodetect]'`. This uses binary packages so you don't need to setup the build environment.

https://spacy.io/usage

**Comment by js-compilatrum** [comment]
> I'd suggest using `'spacy[cuda-autodetect]'`. This uses binary packages so you don't need to setup the build environment.
> 
> https://spacy.io/usage

I did it before as you suggest (I correct my previus . Problem is not with installing cupy as using your method result is the same. It does'nt matter if I install cupy version for CUDA 11.8 manually or using 'spacy[cuda-autodetect]'. Problem is still the same. If CUDA is up to 11.8 installation is not problem (CUDA 12 is not supported by cupy yet and I got error with it), but missing compiler of Visual Studio 2019.

**Comment by kmaehashi** [comment]
Ah, sorry I got it wrong.

Generally, CuPy can discover `cl.exe` automatically. What do you get when running `python -c 'import cupy; print(cupy.cuda.compiler._get_extra_path_for_msvc())'`?

You can also specify `cl.exe` location via `PATH` as you did, however

> C:\Programming\VisualStudio2019\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x86

this is a path to `x86` (32-bit) compiler. You need to use `x64` instead.

**Comment by js-compilatrum** [comment]
I don't understand this either as I don't find any other version of **cl.exe** in Visual Studio 2019 installed folder. When I execute your command I get:

`C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\Bin\\amd64`

**Comment by kmaehashi** [comment]
> Is any better solution to add allow unsported compiler?

CuPy can change the CUDA compiler via `NVCC` env var. Setting the env var to `nvcc -allow-unsupported-compiler` might work for you (although I won't recommend this setup).
