### ISSUE TITLE
Wrong answer got from `contraction` function in `cutensor` lib

### ISSUE THREAD

**Issue by jemiryguo** [cupy/cupy#7318]
### Description

In some case, the `contraction` function in `cutensor` lib will give the wrong answer. This problem is very likely to show up when call several `contraction` function sequencely and with similar contraction order. See the code bellow for example. There are several ways to correct the code:

1. Change `b = contraction('lijk', a, 'jm', t2, 'likm', buf=buf)` to `b = contraction( 'jm', t2, 'lijk', a,'likm', buf=buf)`. This only swap the contraction parameter `a` and `t1`, which should not affect the answer but make the contraction paremeters to get `b` and `c` no longer similar.
2. Swap the contraction parameter of `c` similarly.
3. Do not use the buf, i.e. Change `b = contraction('lijk', a, 'jm', t2, 'likm', buf=buf)` to `b = contraction('lijk', a, 'jm', t2, 'likm')`.
4. Comment out the 443 and 473 line in `cupy/cupyx/cutensor.pyx`. `443: # _contraction_descriptors[key] = desc`, `473: # _contraction_plans[key] = plan`. This disable the 'cache' mechanism for `contraction_descriptors` and `contraction_plans`.

 After several months' investagation, i think this is very likely related to the 'cache' mechanism in the `cupy/cupyx/cutensor.pyx`, i.e. the following dicts:
```
29: cdef dict _handles = {}
30: cdef dict _tensor_descriptors = {}
31: cdef dict _contraction_descriptors = {}
32: cdef dict _contraction_finds = {}
33: cdef dict _contraction_plans = {}
34: cdef dict _modes = {}
35: cdef dict _scalars = {}
```
Perhaps, `cutensor` lib automaticly destroy the object cached in these dicts causeing this problem. I am not sure which specific dicts cause the problem (disableign all of them can solve the problem of course but less efficient).

### To Reproduce

```py
import numpy as np
import cupy
from cupyx import cutensor

def contraction(inda, a, indb, b, indc, buf=None):
    modea = tuple(inda)
    modeb = tuple(indb)
    modec = tuple(indc)
    dtype = np.result_type(a, b)
    cshape = [a.shape[modea.index(
        c)] if c in modea else b.shape[modeb.index(c)] for c in modec]
    if buf is None:
        c = cupy.empty(cshape, dtype=dtype)
    else:
        assert np.prod(buf.shape) >= np.prod(cshape), 'buf is not enough'
        c = cupy.ndarray(cshape, dtype=dtype, memptr=buf.data)
    desca = cutensor.create_tensor_descriptor(a)
    descb = cutensor.create_tensor_descriptor(b)
    descc = cutensor.create_tensor_descriptor(c)
    c = cutensor.contraction(1.0, a, desca, cutensor.create_mode(
        *modea), b, descb, cutensor.create_mode(*modeb), 0.0, c, descc, cutensor.create_mode(*modec))
    return c

if __name__ == "__main__":
    n = 10
    t1 = cupy.random.rand(n, n, n, n)
    t2 = cupy.random.rand(n, n)

    # cutensor
    buf = cupy.empty(n**4)
    a = contraction('ijkl', t1, 'km', t2, 'lijm')
    b = contraction('lijk', a, 'jm', t2, 'likm', buf=buf)
    c = contraction('likj', b, 'im', t2, 'ljkm')
    print('a:', a.max(), 'b:', b.max(), 'c:', c.max())
    buf = a = b = c = None

    #cupy dot
    a = cupy.dot(t1.transpose((3, 0, 1, 2)), t2)
    b = cupy.dot(a.transpose((0, 1, 3, 2)), t2)
    c = cupy.dot(b.transpose((0, 3, 2, 1)), t2)
    print('a:', a.max(), 'b:', b.max(), 'c:', c.max())
```

### Installation

Built from GitHub source

### Environment

```
OS                           : Linux-5.4.143.bsk.7-amd64-x86_64-with-glibc2.28
Python Version               : 3.9.15
CuPy Version                 : 12.0.0b2
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.5
SciPy Version                : 1.7.3
Cython Build Version         : 0.29.32
Cython Runtime Version       : 0.29.32
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11030
CUDA Driver Version          : 11030
CUDA Runtime Version         : 11030
cuBLAS Version               : (available)
cuFFT Version                : 10402
cuRAND Version               : 10204
cuSOLVER Version             : (11, 1, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 3)
Thrust Version               : 101100
CUB Build Version            : 101100
Jitify Build Version         : 4a37de0
cuDNN Build Version          : 8700
cuDNN Version                : 8700
NCCL Build Version           : 21104
NCCL Runtime Version         : 21104
cuTENSOR Version             : 10602
cuSPARSELt Build Version     : None
Device 0 Name                : A100-SXM-80GB
Device 0 Compute Capability  : 80
Device 0 PCI Bus ID          : 0000:4E:00.0
```

**Comment by jemiryguo** [comment]
I think this bug is related to a similar caching scheme in cuda called "Plan Cache" (https://docs.nvidia.com/cuda/cutensor/plan_cache.html) that is automatically enabled. The cupy caching scheme may conflict with the plan cache. I propose to disable all caching schemes in cupy.cutensor.

**Comment by leofang** [comment]
@jemiryguo so sorry for late response, and thank you for bringing this to our attention and your time on investigating the issue for us. 

As I pointed out in another bug report (https://github.com/cupy/cupy/issues/7812#issuecomment-1686254600), you were right that it's due to erroneous cache hits. CuPy only caches the pointer addresses of the mode labels, not their entire contents, so depending on the contraction problem & gc the pointer addresses could be reused but with different mode labels. This will be fixed by #7814.

**Comment by beimojiguang** [comment]
@leofang Hi, I'm wondering when will this bug will be fixed in the formal version? We really need this `contraction` function to develop our code.

**Comment by leofang** [comment]
IIRC the expectation is to release v12.3.0 / v13.0.0rc1 (that contain the fix) later this month. In the meanwhile, you can build from the main branch.
