### ISSUE TITLE
implementing numpy.delete() 

### ISSUE THREAD

**Issue by Anas20001** [cupy/cupy#7351]
### Description

I would like to start contributing to cupy by implementing numpy.delete() method into cupy code base.

**Comment by kmaehashi** [comment]
Hi, thanks for your interest in contributing to CuPy! I think it's better to discuss the strategy first, before actually starting to code. The implementation of `cupy.ndarray.__getitem__` might be a good reference to get the idea. Let me know your thoughts.

**Comment by Anas20001** [comment]
Hi @kmaehashi, I have looked over `cupy.ndarray.__getitem__`  in the search but didn't found it, instead I've searched over to construct a strategy.  we'll need create or use other functions in order to implement our function correctly some of which are :
- check if the argument passed is an array 
- and the axis to delete from 
- a 1-dim delete function if no axis passed 
- a n-dim delete function if axis passed 

our main and helper functions  would be implemented in [https://github.com/cupy/cupy/blob/a3b19f4b91ede049691e92eae7f19e5877fcf5a8/cupy/_manipulation/add_remove.py](url)
that right ? 
Any other thoughts would be helpful.

**Comment by kmaehashi** [comment]
The entrypoint for `cupy.ndarray.__getitem__` is here:
https://github.com/cupy/cupy/blob/v12.0.0b3/cupy/_core/core.pyx#L1512

Essentially `numpy.delete` is an inverse of `__getitem__` so you will need similar machinery.  For each index type (slice, int, CPU array of ints, GPU array of ints, or GPU array of bool (mask)), a different optimization might be required to minimize the number of copies and memory allocation size for the output array.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html
