### ISSUE TITLE
cupy-rocm-5-0 fails to get hip symbol

### ISSUE THREAD

**Issue by andreish** [cupy/cupy#7358]
### Description

.venv/lib/python3.8/site-packages/cupy_backends/cuda/api/runtime.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z22hipCreateSurfaceObjectPyPK15hipResourceDesc, version hip_4.2

mybe bad compile against a rocm 4.2 instead of rocm 5.0 

### To Reproduce

```py
# Write the code here
```

### Installation

Wheel (`pip install cupy-***`)
pip install cupy-rocm-5-0

### Environment
LD_LIBRARY_PATH=/opt/rocm/lib/
```
# Paste the output here
```
.venv/lib/python3.8/site-packages/cupy_backends/cuda/api/runtime.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z22hipCreateSurfaceObjectPyPK15hipResourceDesc, version hip_4.2

### Additional Information

 uname -a 
Linux ryzen3 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

dpkg -l | grep rocm
ii  rocm-clang-ocl                             0.5.0.50100-36                      amd64        OpenCL compilation with clang compiler.
ii  rocm-cmake                                 0.7.2.50100-36                      amd64        rocm-cmake built using CMake
ii  rocm-core                                  5.1.0.50100-36                      amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-dbgapi                                0.64.0.50100-36                     amd64        Library to provide AMD GPU debugger API
ii  rocm-debug-agent                           2.0.3.50100-36                      amd64        Radeon Open Compute Debug Agent (ROCdebug-agent)
ii  rocm-dev                                   5.1.0.50100-36                      amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-device-libs                           1.0.0.50100-36                      amd64        Radeon Open Compute - device libraries
ii  rocm-gdb                                   11.2.50100-36                       amd64        ROCgdb
ii  rocm-hip-libraries                         5.1.0.50100-36                      amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-hip-runtime                           5.1.0.50100-36                      amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-hip-runtime-dev                       5.1.0.50100-36                      amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-hip-sdk                               5.1.0.50100-36                      amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-language-runtime                      5.1.0.50100-36                      amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-llvm                                  14.0.0.22114.50100-36               amd64        ROCm compiler
ii  rocm-ocl-icd                               2.0.0.50100-36                      amd64        opencl built using CMake
ii  rocm-opencl                                2.0.0.50100-36                      amd64        opencl built using CMake
ii  rocm-opencl-dev                            2.0.0.50100-36                      amd64        opencl built using CMake
ii  rocm-smi-lib                               5.0.0.50100-36                      amd64        AMD System Management libraries
ii  rocm-utils                                 5.1.0.50100-36                      amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocminfo                                   1.0.0.50100-36                      amd64        Radeon Open Compute (ROCm) Runtime rocminfo tool

**Comment by kmaehashi** [comment]
> ii rocm-hip-runtime 5.1.0.50100-36 amd64 Radeon Open Compute (ROCm) Runtime software stack

`cupy-rocm-5-0` is for ROCm 5.0 but it seems you have 5.1 installed.

> mybe bad compile against a rocm 4.2 instead of rocm 5.0

Linkage seems correct (also a bit surprising to me that ROCm 5.0 has 4.2 symbol version):

```
$ nm -D --with-symbol-versions /opt/rocm-5.0.2/hip/lib/libamdhip64.so.5.0.50002 | grep hipCreateSurfaceObject
00000000001b5620 T _Z22hipCreateSurfaceObjectPyPK15hipResourceDesc@@hip_4.2
```

**Comment by andreish** [comment]
indded, strange . I got confused because I tried also building from sources and I saw in the setup.py some indication of rocm 5.1 . After I switch to rocm 5.0 the symbols are resolved ok . I still get an error 
"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!" when running cupy code , but this may be other rocm isue. (will have to track it down because Hip-examples compiles and works great on my hw )   .

**Comment by andreish** [comment]
maybe related rocm issue : https://github.com/rocm-arch/tensorflow-rocm/issues/21

**Comment by kmaehashi** [comment]
> "hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"

Could you share the output of `rocminfo | grep gfx` command? This might indicate missing architecture support in CuPy side.

**Comment by andreish** [comment]
# rocminfo | grep gfx
  Name:                    gfx1031                            
      Name:                    amdgcn-amd-amdhsa--gfx1031  


# lspci | grep VGA 
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 73df (rev c1)

# cat /proc/cpuinfo
model name      : AMD Ryzen 3 2200G with Radeon Vega Graphics

GPU is Radeon RX 6700 XT

**Comment by kmaehashi** [comment]
Thanks @andreish, I think we should update our target arch list. Currently CuPy wheels are not built for `gfx1031`:

https://github.com/cupy/cupy-release-tools/blob/d574851f75c2e048fcb4d1efe647203f0db421d0/build.sh#L48

@amathews-amd Is there a list of GPU IDs supported by ROCm/HIP?

**Comment by andreish** [comment]
Thank you too. 

I was using these to figure out hw support: 
 
- https://docs.amd.com/en-US/bundle/Hardware_and_Software_Reference_Guide/page/Hardware_and_Software_Support.html  
- https://docs.amd.com/bundle/ROCm_Release_Notes_v5.0/page/About_This_Document.html 
- https://github.com/RadeonOpenCompute/ROCm/issues/1714

Most release notes have some hw support list (I guess what support is added ) but contents of ROCM installation GPU bytecode files shows a more wide list,  probably not all tested.

**Comment by amathews-amd** [comment]
See https://github.com/RadeonOpenCompute/ROCm/issues/1714#issuecomment-1128327143

**Comment by kmaehashi** [comment]
@amathews-amd, can I ask you to send a pull-request to update this script appropriately? Currently, the same `HCC_AMDGPU_TARGET` is used for `rocm-4.3`, `rocm-5.0`, and `rocm-5.3`, but I think different values are needed for each ROCm version.

https://github.com/cupy/cupy-release-tools/blob/d574851f75c2e048fcb4d1efe647203f0db421d0/build.sh#L45-L49

**Comment by amathews-amd** [comment]
cc: @AdrianAbeyta
