### ISSUE TITLE
Installation of CuPy on NVIDIA Drive AGX Xavier

### ISSUE THREAD

**Issue by gibinjoe** [cupy/cupy#7372]
### Description

I am trying to install CuPy on NVIDIA Drive AGX Xavier deveopment kit.  Since, wheels are not available for this architecture, I am building from source using the command
`CUDA_PATH="/usr/local/cuda-10.2" CFLAGS="-I/usr/local/cuda/include -I/home/nvidia/target/aarch64-linux/include " LDFLAGS="-L/usr/local/cuda/lib64 -L/usr/lib -L/home/nvidia/target/aarch64-linux/lib/stubs" pip3 install cupy --no-cache-dir -vvvv`

I had to manually copy the cross compiled cuda libraries from host to the target as some of them were not available on the machine. - Hence the additional LDFLAGS and CFLAGS.  The compilation errors out as shown below.

`    aarch64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -L/usr/local/cuda/lib64 -L/usr/lib -L/home/nvidia/target/aarch64-linux/lib/stubs -I/usr/local/cuda/include -I/home/nvidia/target/aarch64-linux/include -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-aarch64-3.6/cupy/_core/dlpack.o -L/usr/local/cuda-10.2/lib64 -o build/lib.linux-aarch64-3.6/cupy/_core/dlpack.cpython-36m-aarch64-linux-gnu.so -Wl,--disable-new-dtags,-rpath,/usr/local/cuda-10.2/lib64
    error: Command "aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -I/usr/local/cuda/include -I/home/nvidia/target/aarch64-linux/include -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D_FORCE_INLINES=1 -DCUPY_CUB_VERSION_CODE=100800 -DCUPY_JITIFY_VERSION_CODE=60e9e72 -I/home/nvidia/sandbox/cupy/install/../cupy/_core/include/cupy/cub -I/home/nvidia/sandbox/cupy/install/../cupy/_core/include -I/usr/local/cuda-10.2/include -I/usr/include/python3.6m -c cupy_backends/cuda/libs/cusparse.cpp -o build/temp.linux-aarch64-3.6/cupy_backends/cuda/libs/cusparse.o" failed with exit status 1
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/nvidia/sandbox/cupy/setup.py'"'"'; __file__='"'"'/home/nvidia/sandbox/cupy/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cnm1_wzj/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/nvidia/.local/include/python3.6m/cupy Check the logs for full command output.
`

I have attached full log for your reference.  I get the same error when I clone the branch v9 and compile it.   
[cupyinstall.txt](https://github.com/cupy/cupy/files/10603408/cupyinstall.txt)

### To Reproduce

```py
# Write the code here
pip3 install cupy
```

### Installation

From source (pip3 install cupy)

### Environment

```
CUDA 10.2, CudNN 7.5.1, Python 3.6.9, DRIVE OS 5.1.6
```

**Comment by emcastillo** [comment]
Looks like you are trying to install this with python 3.6 which is not compatible.
Try to upgrade the Python version to a more recent one. You can use pyenv for this.

**Comment by gibinjoe** [comment]
I have CuPy v9 working on my desktop machine and hence am trying to compile that.  Under the documentation of v9, it showed python 3.6 is supported.  I also installed python 3.8 as per your suggestion.  I get the same error as shown below.

`  INFO: aarch64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -L/usr/local/cuda/lib64 -L/usr/lib -L/home/nvidia/target/aarch64-linux/lib/stubs -I/usr/local/cuda/include -I/home/nvidia/target/aarch64-linux/include build/temp.linux-aarch64-cpython-38/cupy/_core/dlpack.o -L/usr/local/cuda-10.2/lib64 -L/usr/lib -o build/lib.linux-aarch64-cpython-38/cupy/_core/dlpack.cpython-38-aarch64-linux-gnu.so -Wl,--disable-new-dtags,-rpath,/usr/local/cuda-10.2/lib64
  error: Command "aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -I/usr/local/cuda/include -I/home/nvidia/target/aarch64-linux/include -fPIC -D_FORCE_INLINES=1 -DCUPY_CUB_VERSION_CODE=100800 -DCUPY_JITIFY_VERSION_CODE=60e9e72 -I/home/nvidia/sandbox/cupy/install/../cupy/_core/include/cupy/cub -I/home/nvidia/sandbox/cupy/install/../cupy/_core/include -I/usr/local/cuda-10.2/include -I/usr/include/python3.8 -c cupy_backends/cuda/libs/cusparse.cpp -o build/temp.linux-aarch64-cpython-38/cupy_backends/cuda/libs/cusparse.o" failed with exit status 1
  error: subprocess-exited-with-error

  × Running setup.py install for cupy did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/home/nvidia/sandbox/cupy/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' install --record /tmp/pip-record-16ogek0c/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/nvidia/.local/include/python3.8/cupy
  cwd: /home/nvidia/sandbox/cupy/
  Running setup.py install for cupy ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cupy

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
`

Is there a version of python that I should try with?

**Comment by kmaehashi** [comment]
For Python 3.8 `cupy-cuda102` binary package is available for aarch64.
https://docs.cupy.dev/en/stable/install.html#installing-cupy

**Comment by gibinjoe** [comment]
I was able to install cupy using the binary package.  When I try to import cupy within python, I get the following error
`
Python 3.8.0 (default, Dec  9 2021, 17:53:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cupy
Traceback (most recent call last):
  File "/home/nvidia/.local/lib/python3.8/site-packages/cupy/__init__.py", line 18, in <module>
    from cupy import _core  # NOQA
  File "/home/nvidia/.local/lib/python3.8/site-packages/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
  File "cupy/_core/core.pyx", line 1, in init cupy._core.core
  File "/home/nvidia/.local/lib/python3.8/site-packages/cupy/cuda/__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/home/nvidia/.local/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 13, in <module>
    from cupy.cuda import device
  File "cupy/cuda/device.pyx", line 9, in init cupy.cuda.device
ImportError: /home/nvidia/.local/lib/python3.8/site-packages/cupy_backends/cuda/libs/cusolver.cpython-38-aarch64-linux-gnu.so: symbol cusolverDnZZgesv_bufferSize version libcusolver.so.10 not defined in file libcusolver.so.10 with link time reference

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nvidia/.local/lib/python3.8/site-packages/cupy/__init__.py", line 20, in <module>
    raise ImportError(f'''
ImportError:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: /home/nvidia/.local/lib/python3.8/site-packages/cupy_backends/cuda/libs/cusolver.cpython-38-aarch64-linux-gnu.so: symbol cusolverDnZZgesv_bufferSize version libcusolver.so.10 not defined in file libcusolver.so.10 with link time reference
================================================================

`
The libcusolver.so.10 is currently in /usr/local/cuda-10.2/targets/aarch64-linux/lib and I have added this the LD_LIBRARY_PATH variable.

**Comment by kmaehashi** [comment]
> ImportError: /home/nvidia/.local/lib/python3.8/site-packages/cupy_backends/cuda/libs/cusolver.cpython-38-aarch64-linux-gnu.so: symbol cusolverDnZZgesv_bufferSize version libcusolver.so.10 not defined in file libcusolver.so.10 with link time reference

Hmm, I don't have access to DRIVE OS and could not verify this issue. According to the docs `cusolverDnZZgesv_bufferSize` should be in CUDA 10.2. Could you continue asking NVIDIA guys at
https://forums.developer.nvidia.com/t/cupy-installation-on-nvidia-drive-agx-xavier/240655/14 ?

**Comment by gibinjoe** [comment]
I noticed that the wheel is for cuda 10.2.0 whereas the cuda on the drive agx is 10.2.9.  Will that cause any issue?

**Comment by kmaehashi** [comment]
Closing as inactive but feel free to reopen or ping me if there are anything CuPy can help. I'll also keep an eye on the nvidia discussion thread.
