### ISSUE TITLE
cupyx.scipy.spatial.cdist

### ISSUE THREAD

**Issue by TianmingQu** [cupy/cupy#7390]
### Description

Dear all,

I am new to cupy and I am trying to install the cupyx.scipy.spatial.cdist, but I got an error as following:AttributeError: module 'cupyx.scipy' has no attribute 'spatial'. Could you give me some suggestions on how to solve this problem?

Best,
Tianming

**Comment by kmaehashi** [comment]
You need to import the module explicitly: `import cupyx.scipy.spatial`

**Comment by kmaehashi** [comment]
Spatial functions in CuPy are currently backed by pylibraft:

https://docs.cupy.dev/en/latest/reference/scipy_spatial_distance.html

> The distance module uses pylibraft as a backend. You need to install pylibraft package <https://anaconda.org/rapidsai/pylibraft> from rapidsai Conda channel to use features listed on this page.

I think the error message can be improved to say this clearly.

**Comment by kmaehashi** [comment]
The error message improvement has landed in #7411.
