### ISSUE TITLE
Raise `RuntimeError` if pylibraft is unavailable

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7406]
When `cupyx.scipy.spatial.*` functions are called, it is better to check `pylibraft_available` flag and raise user-friendly error message, rather than "pairwise_distance not defined". (reported in #7390)

**Comment by Raghav323** [comment]
Hello @kmaehashi can i work on this issue ?

**Comment by kmaehashi** [comment]
Sure, go ahead :)
