### ISSUE TITLE
Implementaion of numpy.ndarray.itemset in CuPy

### ISSUE THREAD

**Issue by oishigyunyu** [cupy/cupy#7414]
### Description

Hello. 

I'd like to implement the functin of `numpy.ndarray.itemset` in CuPy #6078.

I don't know how to implement the function as a class method of `cupy.ndarray`.

From the [document of NumPy](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.itemset.html), this function was implemented as a inplace function. 
```
>>> np.random.seed(123)
>>> x = np.random.randint(9, size=(3, 3))
>>> x
array([[2, 2, 6],
       [1, 3, 6],
       [1, 0, 1]])
>>> x.itemset(4, 0)
>>> x.itemset((2, 2), 9)
>>> x
array([[2, 2, 6],
       [1, 0, 6],
       [1, 0, 9]])
```
Normally, funtion requires a variable to return values, but this method doesn't require it.

How Can I implement this function? 

Sincerly,

**Comment by kmaehashi** [comment]
Hi @oishigyunyu, thanks for the interest. `cupy.ndarray` class methods are defined at: https://github.com/cupy/cupy/blob/9816e20b3915dd28bc54a7549f28f69633ceb112/cupy/_core/core.pyx#L95

**Comment by oishigyunyu** [comment]
@kmaehashi 
Thank you for your suggesting.
I will work on this issue, then I will reopen the pull request.

**Comment by kmaehashi** [comment]
Moving the discussion to #7569
