### ISSUE TITLE
Taking a really long time to compute the mean of an array the first time

### ISSUE THREAD

**Issue by polortiz4** [cupy/cupy#7467]
I'm observing some strange behavior: cupy takes a really long time to compute the mean along axis=2 for an array, but only the first time it does so for a given ordering configuration:

```
ipython -i -c "import cupy as cp;from time import perf_counter"
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  8 2023, 10:42:25) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.10.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: image = cp.ones((10, 500, 496))

In [2]: t_now = perf_counter()
   ...: cp.mean(cp.asfortranarray(image), axis=2)
   ...: t_after = perf_counter()
   ...: print(f"Elapsed time: {(t_after-t_now)*1e3:.2f}ms")
Elapsed time: 20.61ms

In [3]: t_now = perf_counter()
   ...: cp.mean(cp.asfortranarray(image), axis=2)
   ...: t_after = perf_counter()
   ...: print(f"Elapsed time: {(t_after-t_now)*1e3:.2f}ms")
Elapsed time: 0.53ms

In [4]: t_now = perf_counter()
   ...: cp.mean(cp.ascontiguousarray(image), axis=2)
   ...: t_after = perf_counter()
   ...: print(f"Elapsed time: {(t_after-t_now)*1e3:.2f}ms")
Elapsed time: 35.37ms

In [5]: t_now = perf_counter()
   ...: cp.mean(cp.ascontiguousarray(image), axis=2)
   ...: t_after = perf_counter()
   ...: print(f"Elapsed time: {(t_after-t_now)*1e3:.2f}ms")
Elapsed time: 0.61ms

In [6]: cp.__version__
Out[6]: '11.6.0'

In [7]:
```

Notice how it took 20.61ms and 35.37ms to compute the mean the first time for a fortran array and contiguous array, respectively, but subsequently computed the same values orders of magnitude faster.
Interestingly enough, having computed the mean of a fortran array leads to speed up in later fortran array computations, but not contiguous ones.
ChatGPT suspects the first time around cupy spends overhead allocating memory that later reuses, but that doesn't explain why the call with a contiguous array was so slow, given it was called after cupy had allocated memory.

Any explanation for this behavior?? And if so, what is the proper way to address it? I can't afford 10s of milliseconds by the time I need to call cupy in my actual application.

**Comment by kmaehashi** [comment]
Hi @polortiz4, there are several one-time overheads for CUDA apps (not limited to CuPy). Please checkout this doc: https://docs.cupy.dev/en/latest/user_guide/performance.html#benchmarking
