### ISSUE TITLE
cupy cannot create an object array like numpy.

### ISSUE THREAD

**Issue by glin2022** [cupy/cupy#7483]
### Description

```py
import numpy as np
import cupy as cp

a = np.zeros((3, 3), dtype=object)
b = cp.zeros((3, 3), dtype=object)
c = np.ones((2, 2))
d = cp.ones((2, 2))

a[0][0] = c
b[0][0] = d
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 10
      7 d = cp.ones((2, 2))
      9 a[0][0] = c
---> 10 b[0][0] = d

File cupy/_core/core.pyx:1590, in cupy._core.core._ndarray_base.__setitem__()
File cupy/_core/_routines_indexing.pyx:52, in cupy._core._routines_indexing._ndarray_setitem()
File cupy/_core/_routines_indexing.pyx:966, in cupy._core._routines_indexing._scatter_op()
File cupy/_core/_kernel.pyx:1291, in cupy._core._kernel.ufunc.__call__()
File cupy/_core/_kernel.pyx:653, in cupy._core._kernel._get_out_args_from_optionals()
ValueError: Out shape is mismatched

---------------------------------------------------------------------------
Is there any other way to achieve the above array like numpy?

### To Reproduce

```py
# Write the code here
import numpy as np
import cupy as cp

a = np.zeros((3, 3), dtype=object)
b = cp.zeros((3, 3), dtype=object)
c = np.ones((2, 2))
d = cp.ones((2, 2))

a[0][0] = c
b[0][0] = d
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
# Paste the output here
OS                           : Linux-5.4.0-99-generic-x86_64-with-glibc2.17
Python Version               : 3.8.13
CuPy Version                 : 11.6.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.23.3
SciPy Version                : 1.9.3
Cython Build Version         : 0.29.32
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11000
CUDA Driver Version          : 11040
CUDA Runtime Version         : 11030
cuBLAS Version               : (available)
cuFFT Version                : 10402
cuRAND Version               : 10204
cuSOLVER Version             : (10, 6, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 0)
Thrust Version               : 100909
CUB Build Version            : 100909
Jitify Build Version         : 4a37de0
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA RTX A5000
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:4F:00.0
```

**Comment by emcastillo** [comment]
CuPy doesn't currently support structured/string/object datatypes

**Comment by glin2022** [comment]
Thanks very much for your reply. Is there any other way to achieve the following code?
```py
import cupy as cp

a = cp.zeros((3, 3))
b = cp.ones((2, 2))
a[0][0] = b
```
ValueError: Out shape is mismatched

**Comment by emcastillo** [comment]
That is not possible; the shape of `a[0][0]` is `(1,)`, so you can't assign an array with `(2,2)` elements there since the memory layout doesn't match.

**Comment by glin2022** [comment]
Thanks very much. I see.
