### ISSUE TITLE
Bug: cp.random.uniform does not accept array bounds

### ISSUE THREAD

**Issue by fujiisoup** [cupy/cupy#751]
`cp.random.uniform` with array bounds does not work as `numpy` does.
Minimal working example is

```python
import cupy as cp
cp.random.uniform(cp.zeros(3), cp.ones(3), (2, 3))  # <-- raises an error
```
complaining `ValueError: object __array__ method not producing an array`

**Comment by jakirkham** [comment]
FWIW this does not raise for me when using 6.5.0. So maybe it can be closed as fixed?

**Comment by fujiisoup** [comment]
Thanks @jakirkham.
I didn't notice this. Closed.
