### ISSUE TITLE
cupyx csr_matrix is not using a memory efficient way to store sparse matrices

### ISSUE THREAD

**Issue by LukasMoll** [cupy/cupy#7529]
### Description

CuPy doesn't seem to utilize the memory efficient data structure of sparse matrices. It stores the whole array.
![Screenshot from 2023-04-22 19-42-20](https://user-images.githubusercontent.com/86722560/233800756-eeebafa5-16ff-474f-84e3-f4360b067162.png)
This is what it should look like and does with SciPy.
![Screenshot from 2023-04-22 19-47-06](https://user-images.githubusercontent.com/86722560/233800791-9670dd4b-bb07-430f-9f3c-0f99e13db3c4.png)
It uses slightly more memory and is slower then using a normal CuPy array even though the matrix is very sparse.

### To Reproduce

```py
# Creat a sparse matrix e.g.
from cupyx.scipy.sparse import random
data = random(1000, 1000)
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Linux-5.19.0-40-generic-x86_64-with-glibc2.35
Python Version               : 3.11.0rc1
CuPy Version                 : 12.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.24.2
SciPy Version                : 1.10.1
Cython Build Version         : 0.29.32
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 12000
CUDA Driver Version          : 12010
CUDA Runtime Version         : 12010
cuBLAS Version               : (available)
cuFFT Version                : 11002
cuRAND Version               : 10302
cuSOLVER Version             : (11, 4, 5)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 1)
Thrust Version               : 200001
CUB Build Version            : 200001
Jitify Build Version         : 4a37de0
cuDNN Build Version          : 8801
cuDNN Version                : 8005
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : 10602
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce GTX 1650 Ti
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0

```

**Comment by dmikushin** [comment]
Hi @LukasMoll , you code example does not make sense to me. In order to create a random sparse matrix, you need to supply your random dense data to a cupyx matrix object, which manages a specific sparse format, for example CSR. Populating CSR matrix with random data could follow [this example](https://github.com/cupy/cupy/issues/2365):

```
import scipy.sparse
import cupy as cp
import cupyx as cpx

m = n = 1000

#create A random sparse matrix
A_cpu = scipy.sparse.random(m, n, format='csr', random_state=42)
A_gpu = cpx.scipy.sparse.csr_matrix(A_cpu)
```

Note: upon creation of `A_gpu`, its data is already in GPU memory. You should not be able to see the content of GPU memory from within the Python debugger, because it belongs to a different hardware, which IDE does not manage.

**Comment by takagi** [comment]
Can I ask what part of your captures I should see? As to your reproducing code, `data.nnz` has the value of `10000`, which means the 1000x1000 matrix has only 10000 entries.

**Comment by kmaehashi** [comment]
Closing as inactive for a while. Feel free to reopen as needed.
