### ISSUE TITLE
RGB image split with cupy : function needed

### ISSUE THREAD

**Issue by AlainPaillou** [cupy/cupy#7538]
### Description

Hello,

Image processing needs sometimes RGB array, sometimes  R array, G array and B array.

It could be really useful to get a cupy function which could be the same as cv2.split(RGBimage).

Real RGB image split costs many ms and maybe cupy could give us the same result with lower tie cost.

Many thanks in advance.

Alain

**Comment by emcastillo** [comment]
how about `cupy.dsplit` or just
```
b, g, r = array[:, :, 0], array[:, :, 1], array[:, :, 2]
```

**Comment by AlainPaillou** [comment]
I don't think cupy.dsplit will create 3 independent 2D arrays.

b, g, r = array[:, :, 0], array[:, :, 1], array[:, :, 2] won't be the solution.

It's the same problem with numpy.

b, g, r = cv2.split(array) do really create 3 new 2D arrays and i can use those arrays in other functions. But it cost time.

b, g, r = array[:, :, 0], array[:, :, 1], array[:, :, 2] is very very fast but you can use those arrays in 2D functions (you will get errors).

I search everywhere and only cv2.split gives real RGB image split.

I think it would be really interesting if cupy could bring a fast and real RGB image split.

**Comment by emcastillo** [comment]
probably thats because they are a view, you can try using cupy.ascontiguous() to create actual arrays as opencv may be expecting them.

We are sorry but currently we are not planing to add API compatibility with other libraries than NumPy or SciPy.

**Comment by AlainPaillou** [comment]
> probably thats because they are a view, you can try using cupy.ascontiguousarray() to create actual arrays as opencv may be expecting them.
> 
> https://docs.cupy.dev/en/stable/reference/generated/cupy.ascontiguousarray.html
> 
> We are sorry but currently we are not planing to add API compatibility with other libraries than NumPy or SciPy.

I tried cupy.ascontiguousarray(). It works fine. Many thx !
