### ISSUE TITLE
TestChoiceChi::test_goodness_of_fit sensitive to data randomness

### ISSUE THREAD

**Issue by pnunna93** [cupy/cupy#7544]
### Description

The TestChoiceChi::test_goodness_of_fit (https://github.com/cupy/cupy/blob/main/tests/cupy_tests/random_tests/test_generator.py#L830) is very sensitive to data randomness, but is failing on ROCm and passing on CUDA with its current setup. 

The test is using numpy.random to generate seeds(https://github.com/cupy/cupy/blob/main/cupy/testing/_random.py#L90), which are set into cupy random generator. The cupy random generator then generates random numbers for the test. 

The seeds for cupy random generator are same on both platforms as numpy.random is hardcoded to a seed 100 (https://github.com/cupy/cupy/blob/main/cupy/testing/_random.py#L37), but the random numbers generated by cupy random generator are different on ROCm and CUDA which caused failure only on ROCm. 

The test failed on both platforms when run more than 10 times as shown below, please propose modifications to this test to make this more robust, to test the correct functionality, but insensitive to random seed.

| #   of runs | # of   failures (V100) |  # of failures (MI250X) | %Failed (V100) | %Failed (MI250X) |
|:-----------:|:---------------:|:----------------:|:-------:|:------:|
|     10     |        0        |        1        |    0    |    10   |
|     100     |        6        |         8        |    6    |    8   |
|     1000    |        43       |        40        |   4.3   |    4   |
|    10000    |       500       |        494       |    5    |  4.94  |
|    100000   |       4819      |       4880       |  4.819  |  4.88  |

### To Reproduce

Install cupy from source on relevant platform: https://docs.cupy.dev/en/stable/install.html#

Change test iterations to desired number here: https://github.com/cupy/cupy/blob/main/tests/cupy_tests/random_tests/test_generator.py#L829
For 100 iterations, @_condition.repeat(3, 10) -> @_condition.repeat(3, 100)

Replace https://github.com/cupy/cupy/blob/main/tests/cupy_tests/random_tests/test_generator.py#L836 with following two lines to skip failures and continue test for desired iterations:
import pytest_check as check
check.is_true(_hypothesis.chi_square_test(counts, expected))

Command to run the test:
CUPY_TEST_GPU_LIMIT=4  pytest -s -vvv tests/cupy_tests/random_tests/test_generator.py::TestChoiceChi::test_goodness_of_fit

### Installation

Built from GitHub source

### Environment

**MI250X(ROCm):**
OS                        : Linux-5.15.0-67-generic-x86_64-with-glibc2.17
Python Version            : 3.8.13
CuPy Version              : 12.0.0b3
CuPy Platform             : AMD ROCm
NumPy Version             : 1.18.5
SciPy Version             : 1.6.3
Cython Build Version      : 0.29.32
Cython Runtime Version    : 0.29.33
CUDA Root                 : /opt/rocm/hip
hipcc PATH                : /opt/rocm/hip/bin/hipcc
CUDA Build Version        : 50422801
CUDA Driver Version       : 50422801
CUDA Runtime Version      : 50422801
cuBLAS Version            : (available)
cuFFT Version             : 10019
cuRAND Version            : 201016
cuSOLVER Version          : (3, 20, 0)
cuSPARSE Version          : (available)
NVRTC Version             : (9, 0)
Thrust Version            : 101600
CUB Build Version         : 201012
Jitify Build Version      : None
cuDNN Build Version       : None
cuDNN Version             : None
NCCL Build Version        : 21304
NCCL Runtime Version      : 21304
cuTENSOR Version          : None
cuSPARSELt Build Version  : None
Device 0 Name             : AMD Instinct MI250X/MI250
Device 0 Arch             : gfx90a:sramecc+:xnack-
Device 0 PCI Bus ID       : 0000:4e:00.0
Device 1 Name             : AMD Instinct MI250X/MI250
Device 1 Arch             : gfx90a:sramecc+:xnack-
Device 1 PCI Bus ID       : 0000:51:00.0
Device 2 Name             : AMD Instinct MI250X/MI250
Device 2 Arch             : gfx90a:sramecc+:xnack-
Device 2 PCI Bus ID       : 0000:56:00.0
Device 3 Name             : AMD Instinct MI250X/MI250
Device 3 Arch             : gfx90a:sramecc+:xnack-
Device 3 PCI Bus ID       : 0000:59:00.0
Device 4 Name             : AMD Instinct MI250X/MI250
Device 4 Arch             : gfx90a:sramecc+:xnack-
Device 4 PCI Bus ID       : 0000:0e:00.0
Device 5 Name             : AMD Instinct MI250X/MI250
Device 5 Arch             : gfx90a:sramecc+:xnack-
Device 5 PCI Bus ID       : 0000:11:00.0
Device 6 Name             : AMD Instinct MI250X/MI250
Device 6 Arch             : gfx90a:sramecc+:xnack-
Device 6 PCI Bus ID       : 0000:16:00.0
Device 7 Name             : AMD Instinct MI250X/MI250
Device 7 Arch             : gfx90a:sramecc+:xnack-
Device 7 PCI Bus ID       : 0000:19:00.0
Device 8 Name             : AMD Instinct MI250X/MI250
Device 8 Arch             : gfx90a:sramecc+:xnack-
Device 8 PCI Bus ID       : 0000:cf:00.0
Device 9 Name             : AMD Instinct MI250X/MI250
Device 9 Arch             : gfx90a:sramecc+:xnack-
Device 9 PCI Bus ID       : 0000:d2:00.0
Device 10 Name            : AMD Instinct MI250X/MI250
Device 10 Arch            : gfx90a:sramecc+:xnack-
Device 10 PCI Bus ID      : 0000:d7:00.0
Device 11 Name            : AMD Instinct MI250X/MI250
Device 11 Arch            : gfx90a:sramecc+:xnack-
Device 11 PCI Bus ID      : 0000:da:00.0
Device 12 Name            : AMD Instinct MI250X/MI250
Device 12 Arch            : gfx90a:sramecc+:xnack-
Device 12 PCI Bus ID      : 0000:8f:00.0
Device 13 Name            : AMD Instinct MI250X/MI250
Device 13 Arch            : gfx90a:sramecc+:xnack-
Device 13 PCI Bus ID      : 0000:92:00.0
Device 14 Name            : AMD Instinct MI250X/MI250
Device 14 Arch            : gfx90a:sramecc+:xnack-
Device 14 PCI Bus ID      : 0000:97:00.0
Device 15 Name            : AMD Instinct MI250X/MI250
Device 15 Arch            : gfx90a:sramecc+:xnack-
Device 15 PCI Bus ID      : 0000:9a:00.0

**V100(CUDA):**
OS                           : Linux-5.13.0-30-generic-x86_64-with-glibc2.29
Python Version               : 3.8.10
CuPy Version                 : 13.0.0a1
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.24.3
SciPy Version                : None
Cython Build Version         : 0.29.34
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11070
CUDA Driver Version          : 11080
CUDA Runtime Version         : 11070
cuBLAS Version               : (available)
cuFFT Version                : 10702
cuRAND Version               : 10210
cuSOLVER Version             : (11, 4, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 7)
Thrust Version               : 101500
CUB Build Version            : 101500
Jitify Build Version         : 4a37de0
cuDNN Build Version          : 8500
cuDNN Version                : 8500
NCCL Build Version           : 21304
NCCL Runtime Version         : 21304
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-SXM2-32GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:1A:00.0
Device 1 Name                : Tesla V100-SXM2-32GB
Device 1 Compute Capability  : 70
Device 1 PCI Bus ID          : 0000:1B:00.0
Device 2 Name                : Tesla V100-SXM2-32GB
Device 2 Compute Capability  : 70
Device 2 PCI Bus ID          : 0000:3D:00.0
Device 3 Name                : Tesla V100-SXM2-32GB
Device 3 Compute Capability  : 70
Device 3 PCI Bus ID          : 0000:3E:00.0
Device 4 Name                : Tesla V100-SXM2-32GB
Device 4 Compute Capability  : 70
Device 4 PCI Bus ID          : 0000:88:00.0
Device 5 Name                : Tesla V100-SXM2-32GB
Device 5 Compute Capability  : 70
Device 5 PCI Bus ID          : 0000:89:00.0
Device 6 Name                : Tesla V100-SXM2-32GB
Device 6 Compute Capability  : 70
Device 6 PCI Bus ID          : 0000:B2:00.0
Device 7 Name                : Tesla V100-SXM2-32GB
Device 7 Compute Capability  : 70
Device 7 PCI Bus ID          : 0000:B3:00.0

**Comment by takagi** [comment]
I couldn't see the detail yet, but I can see the table says we have no essential issue here. It would be okay to lose the test condition somehow to make it pass on ROCm as well.

**Comment by pnunna93** [comment]
Could you review the test and suggest modifications, so that its not sensitive to the random seed?

**Comment by takagi** [comment]
Yes. Can I ask you to try the following change on you local?
```diff
-    @_condition.repeat(3, 10)
+    @_condition.repeat_with_success_at_least(10, 9)
```

`repeat_with_success_at_least(10, 9)` checks the test passes at least nine times in ten trials.

**Comment by pnunna93** [comment]
It does pass the test on ROCm, but the test may still fail if the seed changes. Could we modify/fix the test instead?

**Comment by takagi** [comment]
No. As far as we're using Chi-squared test, even when `choice` is ideally implemented, the null hypothesis is likely rejected with the probability of the significance level (we're using 0.05).

**Comment by pnunna93** [comment]
Thanks for the fix @takagi. I have opened another PR into cupy repo, please check when you can - https://github.com/cupy/cupy/pull/7626
