### ISSUE TITLE
Add as_strided() or a strides argument to ndarray.__init__()

### ISSUE THREAD

**Issue by f0k** [cupy/cupy#755]
Numpy has [`np.lib.stride_tricks.as_strided(x, shape, strides)`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.lib.stride_tricks.as_strided.html). It allows to create a view into the data of an existing array with a custom shape and strides. A common use case is to view a vector of data points as a matrix of overlapping subsequences of data points (e.g., for an STFT). This cannot be accomplished by reshape operations.
`cupy.core.core.ndarray` has a strides property, but does not provide a way to create an array with a specific data pointer and custom strides. It would thus be great to either support a `strides` argument in the `ndarray` constructor, or provide an `as_strided` function (not sure if it needs to be buried as deep as in numpy, but for full compatibility, it probably should).

**Comment by toslunar** [comment]
`strides` option is added to `ndarray` in #1611.

**Comment by rsokl** [comment]
`np.lib.stride_tricks.as_strided` would be absolutely awesome to have in `cupy`. I have already implemented [n-dimensional neural network style convolutions](https://mygrad.readthedocs.io/en/latest/generated/mygrad.nnet.conv_nd.html#mygrad.nnet.conv_nd) and [N-dimensional pooling](https://mygrad.readthedocs.io/en/latest/generated/mygrad.nnet.max_pool.html#mygrad.nnet.max_pool) in numpy by leveraging `as_strided`.

If you guys add this, I will be able to use cupy to add gpu support to my autograd library!

**Comment by kmaehashi** [comment]
`as_strided` is now implemented.
