### ISSUE TITLE
[RFC] Drop support for CUDA 10.2/11.0/11.1 in CuPy v13

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7557]
The CuPy team plans to drop support for CUDA 10.2, 11.0, and 11.1 in CuPy v13, which will be released in October 2023 (#7555). The primary motivation for this change is to reduce the work necessary to publish a CuPy release. These legacy CUDA versions require separate packaging for each version as they don't support CUDA Minor Compatibility policy. Reducing the number of packages also helps keep the PyPI community healthy in terms of the disk space and bandwidth required to distribute packages.

Here are the download counts of our binary packages in the recent three months (sdist and `cupy-wheel` are excluded):

![CuPy PyPI Binary Package Downloads (Feb 2023 - Apr 2023)](https://github.com/cupy/cupy/assets/939877/2db9df60-a759-4c0f-a9f9-b378b42d12e0)

According to the statistics, 22.3% of users will be affected by this change. However, users of these CUDA versions can continue to use CuPy v12, which we believe is stable enough and will continue to be maintained until the release of the CuPy v13. The number also shows that 31.2% of users are still on CUDA 8.0~10.1, which is no longer supported, indicating they are satisfied with the legacy CuPy releases (v9 or earlier). That said, we recommend upgrading to the latest CUDA release, which provides better performance.

Please leave a comment on this issue if you have any feedback on this change.

**Comment by kmaehashi** [comment]
RFC for a month, and there doesn't seem to be any problem. Let's proceed.

**Comment by jakirkham** [comment]
Thanks all! 🙏
