### ISSUE TITLE
Implementing numpy.ndarray.itemset

### ISSUE THREAD

**Issue by rwschonberg** [cupy/cupy#7569]
### Description

Hi all - first-time contributor here, so I went to https://github.com/cupy/cupy/issues/6078#issue-1051191869 and picked an API under the Easy category to implement: `numpy.ndarray.itemset`. In line with the recommendation in the [Contribution Guide](https://docs.cupy.dev/en/stable/contribution.html#issues-and-pull-requests) to submit an issue for new APIs, I'm creating this post to discuss the design.

tl;dr - Two questions: should the code be contained in `cupy._core.core.pyx`? Since it's modifying on-device arrays, should it have its own kernel or make use of others that could do the job?

I found the TODO that (in theory) marks where the function should go in `cupy._core.core.pyx`. Looking at other similar functions there which modify data on the GPU, it seems there are two standard implementations. The first is to expose a method in `_ndarray_base` which calls a kernel (e.g. `_ndarray_base.fill`). The second is to expose a method in `_ndarray_base` which calls to another method in a different `_routines_*.pyx` file. **Organizationally speaking, is there another `.pyx` file where the private implementation of `ndarray.itemset` should live**? It's a simple enough function that I think it would make sense for it to just live in `core.pyx`, but I'm not sure what the precedent is.

Looking at the expected behavior of `numpy.ndarray.itemset`, it seems like the only mode of operation is modifying a singular value in the ndarray. This brings me to my next question - for this simple of a function, **is a dedicated kernel necessary or can I make use of another pre-existing kernel?** There are a few other methods that would already provide the abstraction of "set some elements in an on-device array to some value," so that could potentially also work for `ndarray.itemset`.

**Comment by kmaehashi** [comment]
Hi @rwschonberg, thanks for your interest in contributing to CuPy! There is ongoing work by @oishigyunyu in #7459.

@oishigyunyu Do you have time to continue with the PR?

**Comment by oishigyunyu** [comment]
@kmaehashi 
Thank you for notifing me that and sorry for not commit about this topic for these weeks.

I will commit on this weekend.

@rwschonberg 
If it will be difficult for me to implement this function, could you please substitute of me?
Then, I'd like to be this topic implementation is on you, and  I will work on some other topics.

**Comment by rwschonberg** [comment]
Thanks for the reply, @oishigyunyu! I’d be happy to pick this up if needed. When will you know if you want me to substitute for you?

**Comment by oishigyunyu** [comment]
@rwschonberg Thank you for waiting me. I want you to take over. Please inplement this ?

**Comment by rwschonberg** [comment]
Hi all - apologies for the delay. I got a new job and had to move across the United States. If this still needs to be done, I'm happy to pick it up. Thanks!

**Comment by yonikremer** [comment]
`numpy.ndarray.itemset` was deprecated in numpy 2, should cupy implement it?

**Comment by kmaehashi** [comment]
Good catch, @yonikremer. Closing as the API was removed in NumPy v2.
