### ISSUE TITLE
Incorrect indexing with `cp.int16`

### ISSUE THREAD

**Issue by alkamid** [cupy/cupy#757]
Running this code:

```python
import numpy as np
import cupy as cp
print('cupy version:', cp.__version__)
print('numpy version:', np.__version__)
b = np.pad(np.ones((420, 420), dtype=np.float16), 1, mode='constant', constant_values=0)
ind = np.array([[0.1, 33.333, 40.2, 421.33], [4.4, 23.0, 64.999999, 3.00001]], dtype=np.float64)
bg = cp.asarray(b)
indg = cp.asarray(ind)
ingint = indg.astype(cp.int16)
print('int16 indexing (incorrect):', bg[ingint[0], ingint[1]])
ingint1 = indg.astype(cp.int32)
print('int32 indexing (correct):', bg[ingint1[0], ingint1[1]])
print('indices32 == indices64:')
print(ingint == ingint1)
```

results in:
```
cupy version: 2.0.0
numpy version: 1.12.1
int16 indexing (incorrect): [ 0.  1.  1.  1.]
int32 indexing (correct): [ 0.  1.  1.  0.]
indices32 == indices64:
[[ True  True  True  True]
 [ True  True  True  True]]
```

In plain language: I'm creating a 422x422 array of ones (`dtype=np.float16`), with borders on each side equal to zeros. I'm they creating an array of indices (`dtype=np.float64`), copying both arrays onto a GPU and accessing the elements of the first array with the second one. Depending on `dtype`, I'm getting different results. Note that none of the numbers is outside of `int16` range. With `numpy` the same code works just fine.

**Comment by yuyu2172** [comment]
Thanks for reporting the bug!
The problem has occurred because the linearized index exceeds the limit of `int16`.
In this case the linearized index of the wrong value is `421 * 422 + 3 = 177665 > 2**16`.

I reproduced the error in a simpler script.
```python
import cupy as cp

a = cp.arange(257 * 256).reshape(257, 256)
i1 = cp.array([256], dtype=cp.int16)
j1 = cp.array([3], dtype=cp.int16)

i2 = cp.array([256], dtype=cp.int32)
j2 = cp.array([3], dtype=cp.int32)

print(a[i1, j1])
print(a[i2, j2])
```
