### ISSUE TITLE
`pip install cupy-wheel` - "not a valid wheel filename"

### ISSUE THREAD

**Issue by yonting** [cupy/cupy#7593]
### Description

When I try to `pip install cupy-wheel` I get the error `cupy_wheel<...>.whl is not a valid wheel filename`.

### To Reproduce

```bash
pip install cupy-wheel
```
OS: Windows 10
Python: 3.8.9
pip: 23.1.2
CUDA: CUDA 11.7

### Installation

None

### Environment

Unable to install using `cupy-wheel`. Can install using `pip install cupy-cuda11x`.

**Comment by kmaehashi** [comment]
Hi @yonting, thanks for reporting - confirmed on my end. This is due to that pip 23.1 has changed it's behavior.

https://pip.pypa.io/en/stable/news/#v23-1

> Remove setup.py install fallback when building a wheel failed for projects without pyproject.toml.

I'll try fixing the issue.

**Comment by kmaehashi** [comment]
We've published a hot-fix release. Thanks again for reporting this one!
