### ISSUE TITLE
Package cupy with pip runtime

### ISSUE THREAD

**Issue by fferroni** [cupy/cupy#7617]
### Description

Hi,

I've seen other CUDA dependant packages, like torch or tensorrt package the NVIDIA runtime together in their installations.
When installing torch for example, it will actually install pip packages like `nvidia_cuda_runtime_cu11` and look for `libcudart.so.1` there. It doesn't seem to be the same thing with cupy, and it rather relies on LD_LIBRARY_PATH.

My feature request would be to start using the `nvidia_cuda_runtime_cuda11` such that things are more hermetic and don't rely on host installations of the runtime.

Thanks!

**Comment by leofang** [comment]
I actually have an RFE in preparation that I'd like to file in response to this issue. Probably won't get to it this week, but stay tuned!

**Comment by leofang** [comment]
(And I believe you meant CUDA runtime, not pip runtime.)

**Comment by kmaehashi** [comment]
I agree it's important to support pip-packaged CUDA runtimes for interoperability.
(This recalled I have to restart working on https://github.com/cupy/cupy/pull/7025 ... 😅)

Looking forward to seeing the RFE from Leo 😃

**Comment by leofang** [comment]
Sorry for delay, will try to file an RFE asap this week.

**Comment by leofang** [comment]
related: https://github.com/cupy/cupy/issues/6842

**Comment by leofang** [comment]
> Sorry for delay, will try to file an RFC asap this week.

See #7727.

**Comment by leofang** [comment]
We've made a better treatment in CuPy v13: statically linking to CUDA runtime to remove it from run-from dependencies, see #7727. For using CUDA wheels with CuPy, this is tracked in https://github.com/cupy/cupy/issues/8013. Let's close this issue.
