### ISSUE TITLE
Remove use of `pkg_resources`

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7654]
Replace it with `importlib.metadata` after dropping support for  Python 3.7.
https://docs.python.org/ja/3/library/importlib.metadata.html#module-importlib.metadata

**Comment by kmaehashi** [comment]
Moved milestone from v13 to v14 and changed priority from high to med. The only remaining usage of `pkg_resources` in CuPy is `cupy/testing/_helper.py`, and is only imported within unit tests.

**Comment by jakirkham** [comment]
Was looking at this recently. If I have time, may try a PR

**Comment by jakirkham** [comment]
Should be fixed by PR: https://github.com/cupy/cupy/pull/8480
