### ISSUE TITLE
Saving and loading sparse matrices fails due to ValueError: Unsupported dtype object

### ISSUE THREAD

**Issue by sambaPython24** [cupy/cupy#7667]
### Description

I would like to save and load matrices from the ```cupyx.scipy.sparse``` classes. While saving seems to be possible, 
loading throws the error ```ValueError: Unsupported dtype object```. 

I tried to save it in the csr or coo frame. It is possible to load it with numpy, but not with cupy.
I tried to load it with cupy and then convert it to cupy with 

Is this a bug or do I have to use a certain format (.npy,.npz, .pickle)

### To Reproduce

```py
import cupy
from cupy import array
from cupyx.scipy.sparse import csr_matrix,coo_matrix

save_path     = "/some_path"


row  = array([0, 0, 1, 2, 2, 2])
col  = array([0, 2, 2, 0, 1, 2])
data = array([1, 2, 3, 4, 5, 6],dtype = cupy.float32)
csr_arr = csr_matrix((data, (row, col)), shape=(3, 3))
print("The sparse tensor would look like ",csr_arr.toarray())

# As an option, one can try to bring it to another format
# csr_arr = csr_arr.tocoo()

# Save the array
allow_pickle = True
cupy.save(os.path.join(save_path,f"test_cupy.npy"),csr_arr, allow_pickle=allow_pickle)

# It is possible to load it as a numpy array
csr_arr = np.load(os.path.join(save_path,f"test_cupy.npy"), allow_pickle=allow_pickle)

# Option 1: It is NOT possible to just load it as a cupy array again: Fail
csr_arr = cupy.load(os.path.join(save_path,f"test_cupy.npy"), allow_pickle=allow_pickle)

# Option 2: It is NOT possible to just load it as a cupy array again: Fail
csr_arr = np.load(os.path.join(save_path,f"test_cupy.npy"), allow_pickle=allow_pickle)
csr_arr = csr_arr.astype(np.float32)   # Error: ValueError: setting an array element with a sequence.
csr_arr = csr_arr.astype(cupy.float32) # Error: ValueError: setting an array element with a sequence.
cupy.asarray(csr_arr)
```

### Installation

Source (`pip install cupy`)

### Environment

OS                           : Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python Version               : 3.10.4
CuPy Version                 : 12.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.23.1
SciPy Version                : 1.9.1
Cython Build Version         : 0.29.32
Cython Runtime Version       : 0.29.32
CUDA Build Version           : 11080
CUDA Driver Version          : 11070
CUDA Runtime Version         : 11040
cuBLAS Version               : (available)
cuFFT Version                : 10500
cuRAND Version               : 10205
cuSOLVER Version             : (11, 2, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 4)
Thrust Version               : 101501
CUB Build Version            : 101501
Jitify Build Version         : 4a37de0
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
Device 0 Name                : NVIDIA RTX A4000
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:01:00.0

**Comment by kmaehashi** [comment]
Sparse matrices need to be saved/loaded with `save_npz` and `load_npz`.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.save_npz.html

**Comment by sambaPython24** [comment]
Is there a corresponding function in cupy (I did not find it) or what is your suggested pipeline to convert it back and forth to scipy?

**Comment by kmaehashi** [comment]
Currently `{save,load}_npz` is unavailable under CuPy. Please convert it to SciPy matrix and use SciPy ones.

https://docs.cupy.dev/en/stable/reference/scipy_sparse.html#conversion-to-from-scipy-sparse-matrices

> When I try to convert the scipy to the cupy matrix by giving (the same layout) to the constructor, I get the error

Could you share the code? The following works for me:

```py
import numpy as np
import scipy.sparse
import cupyx.scipy.sparse
mat = scipy.sparse.csr_matrix((3, 4), dtype=np.float32)
cupyx.scipy.sparse.csr_matrix(mat)
```
