### ISSUE TITLE
Fix `cupyx.scipy.sparse.csgraph` module to work with the latest RAPIDS cuGraph

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7672]
Follow the API change introduced in RAPIDS 22.12.
https://github.com/cupy/cupy/pull/7647#discussion_r1244820097

cc/ @pentschev

**Comment by pentschev** [comment]
Thanks @kmaehashi for the ping.

@rlratzel are those API changes something we can keep CuPy devs informed when they happen, or better yet, could the graph team commit to keep CuPy up-to-date when needed?

**Comment by rlratzel** [comment]
> @rlratzel are those API changes something we can keep CuPy devs informed when they happen, or better yet, could the graph team commit to keep CuPy up-to-date when needed?

Yes, this was an oversight and we should have realized this would affect cupy.  We'll plan on submitting a PR to cupy to update it to use the latest connected components APIs.  cc @jnke2016

**Comment by jnke2016** [comment]
Thanks for letting me know @Rick ***@***.***> . I am investigating the issue, running tests then I will push a PR. I will keep you posted.

Joseph

From: Rick Ratzel ***@***.***>
Date: Monday, July 3, 2023 at 10:27 AM
To: cupy/cupy ***@***.***>
Cc: Joseph Nke ***@***.***>, Mention ***@***.***>
Subject: Re: [cupy/cupy] Fix `cupyx.scipy.sparse.csgraph` module to work with the latest RAPIDS cuGraph (Issue #7672)

@rlratzel<https://github.com/rlratzel> are those API changes something we can keep CuPy devs informed when they happen, or better yet, could the graph team commit to keep CuPy up-to-date when needed?

Yes, this was an oversight and we should have realized this would affect cupy. We'll plan on submitting a PR to cupy to update it to use the latest connected components APIs. cc @jnke2016<https://github.com/jnke2016>

**Comment by kmaehashi** [comment]
Thank you all for your help! :pray:

**Comment by jnke2016** [comment]
This is a link to the PR I pushed: https://github.com/cupy/cupy/pull/7693. Please let me know if you have any question/suggestion.

Joseph

From: Kenichi Maehashi ***@***.***>
Date: Monday, July 3, 2023 at 9:04 PM
To: cupy/cupy ***@***.***>
Cc: Joseph Nke ***@***.***>, Mention ***@***.***>
Subject: Re: [cupy/cupy] Fix `cupyx.scipy.sparse.csgraph` module to work with the latest RAPIDS cuGraph (Issue #7672)

Thank you all for your help! 🙏
