### ISSUE TITLE
/cupy/_statistics/correlation.py in cov function has typo 

### ISSUE THREAD

**Issue by adimesika1** [cupy/cupy#7697]
### Description

In line 172, fwights instead of aweights:
![image](https://github.com/cupy/cupy/assets/49398220/0714f9c8-874d-4993-b336-2e23647173a1)

### Additional Information

CuPy Version                 : 12.1.0

**Comment by kmaehashi** [comment]
Fixed by @pri1311 in #7701. Thanks for reporting, @adimesika1!
