### ISSUE TITLE
cupy.bincount can give incorrect results on CuPy 12.x with CUB enabled

### ISSUE THREAD

**Issue by grlee77** [cupy/cupy#7698]
### Description

I encountered some cases where bincount is giving incorrect results. It showed up on CI for cuCIM when using CUDA 12.0 and CuPy 12.3, but does not occur on our CUDA 11 CI runs.

I was also able to reproduce the issue locally from CuPy main and CUDA 12.2.

### To Reproduce

Here is an example taking bincount of `arange` so that all elements of the result should be 1. It can be seen that the output has zeros in some locations:

```py
import cupy as cp

cp.bincount(cp.arange(65536, dtype=cp.int32))
```
gives
```
array([1, 1, 1, ..., 0, 0, 0])
```
and `cp.bincount(cp.arange(65536, dtype=cp.int32)).sum()` is 32768 instead of the expected 65536.

Running the same thing in NumPy or in CuPy with `CUPY_ACCELERATORS=""` set gives the expected result that is all ones.

### Installation

None

### Environment

OS                           : Linux-5.15.0-76-generic-x86_64-with-glibc2.31
Python Version               : 3.10.12
CuPy Version                 : 13.0.0a1
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.24.4
SciPy Version                : 1.11.1
Cython Build Version         : 0.29.30
Cython Runtime Version       : 0.29.35
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 12020
CUDA Driver Version          : 12020
CUDA Runtime Version         : 12020
cuBLAS Version               : (available)
cuFFT Version                : 11008
cuRAND Version               : 10303
cuSOLVER Version             : (11, 5, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 2)
Thrust Version               : 200101
CUB Build Version            : 200101
Jitify Build Version         : 4a37de0
cuDNN Build Version          : 8902
cuDNN Version                : 8902
NCCL Build Version           : 21803
NCCL Runtime Version         : 21803
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA RTX A6000
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:17:00.0

### Additional Information

I will report the issue to the CUB devs as it seems it is likely an issue in CUB itself.

**Comment by grlee77** [comment]
I forgot to mention, that the correct result is also given even with CUB enabled if the dtype is unsigned instead
```py
cp.bincount(cp.arange(65536, dtype=cp.uint32))
```
array([1, 1, 1, ..., 1, 1, 1])

**Comment by leofang** [comment]
Summary (on behalf of @grlee77 and @senior-zero, who have kindly triaged the issue quickly): It seems to happen with CUB shipped with CTK 12(.x?), but not with the upstream version. @senior-zero came up with a C++ reproducer: 
```c++
#include <iostream>
#include <thrust/device_vector.h>
#include <thrust/sequence.h>
#include <thrust/reduce.h>
#include <cub/device/device_histogram.cuh>

int main() {
  int num_samples = 65536;

  thrust::device_vector<int> samples(num_samples);
  thrust::sequence(samples.begin(), samples.end()); // np.arrange(65536) ?

  // size = int(cupy.max(x)) + 1
  int num_bins = num_samples;
  int num_levels = num_bins + 1;
  int lower_level = 0;
  int upper_level = num_bins;

  thrust::device_vector<unsigned long long int> bins(num_bins);

  std::uint8_t *d_temp_storage{};
  std::size_t temp_storage_bytes{};

  int *d_samples = thrust::raw_pointer_cast(samples.data());
  unsigned long long int *d_bins = thrust::raw_pointer_cast(bins.data());

  cub::DeviceHistogram::HistogramEven(d_temp_storage,
                                      temp_storage_bytes,
                                      d_samples,
                                      d_bins,
                                      num_levels,
                                      lower_level,
                                      upper_level,
                                      num_samples);
  
  thrust::device_vector<std::uint8_t> temp_storage(temp_storage_bytes);
  d_temp_storage = thrust::raw_pointer_cast(temp_storage.data());

  cub::DeviceHistogram::HistogramEven(d_temp_storage,
                                      temp_storage_bytes,
                                      d_samples,
                                      d_bins,
                                      num_levels,
                                      lower_level,
                                      upper_level,
                                      num_samples);

  std::cout << thrust::reduce(bins.begin(), bins.end()) << std::endl;
}
```
This adds one more reason to moving to use upstream CCCL asap (https://github.com/cupy/cupy/issues/6700#issuecomment-1543507027). For now, given this and [the other bug](https://github.com/NVIDIA/cub/issues/613) that we [worked around](https://github.com/cupy/cupy/pull/7316), I think we should just disable CUB histogram until we can pin at upstream instead of CTK.

**Comment by emcastillo** [comment]
> t disable CUB histogram until we can pin at upstream instead of CTK.

We think this is the best course of action for now!

**Comment by jakirkham** [comment]
cc @anaruse (for awareness)

**Comment by jakirkham** [comment]
cc @gigony (for awareness)
