### ISSUE TITLE
Discussion: Change to link statically to cudart?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#7727]
I've meant to raise this discussion but didn't get time to do so until now, sorry for delay.

I would like to gauge the team and users' interest in changing the way CuPy links to cudart (CUDA Runtime). Currently, CuPy dynamically links to cudart, likely under the assumption that there is one unique `libcudart.so` (say from the system package manager) throughout the system. But, with either many module-based HPC clusters or Conda it is often not the case. Furthermore, not all Python libraries do this, for example PyTorch has been linking to cudart statically for very long time. The same story goes even for CUDA Python (which re-implements cudart for a different technical reason). This then raises a semantic question: When I query the cudart version, am I guaranteed that this is the same version seen by all DSOs loaded in a user process? 

The answer is no. Even CUDA libraries (cuBLAS & co) do not link to cudart dynamically, but statically (see this [CUDA Q&A](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#faq)). This is done so that CUDA minor version compatibility (MVC) can fully kick in. It eliminates the need of comparing the build-time and run-time versions of cudart, and ensures that as long as the user-mode driver (UMD, meaning `libcuda.so`) is newer than the minimal version required by the CUDA major version, the generated binary would work on regardless of the CUDA Toolkit (CTK) version. Therefore, at least for modules that could work without any CUDA libraries (like `cupy.cuda.cub`), they automatically gain forward (and certain backward) compatibility by just depending on the UMD.

Also, there is no size concern in static linking to cudart, which is very tiny in size.

A significant obstacle for CuPy to make this change would be that in many places CuPy calls `runtime.runtimeGetVersion()`, assuming this is the canonical way to check the current CTK version. It may no longer be the case (probably it has never been the case?), so this is not an easy change. Also, CuPy still has to link to all libraries dynamically. Even the "core" part of CuPy (kernel compilation) requires at least NVRTC and not just the UMD. As a result, unlike some libraries that could see the immediate benefit (by only depending on UMD) I understand this change could be less attractive to CuPy, but at least this would be a discussed choice.

**Comment by kmaehashi** [comment]
Thank you for the proposal and detailed insight, Leo. Basically, I'm supportive of this idea - this will make CuPy one step forward to achieve "one binary for all CUDA versions." After quickly [searching code](https://github.com/search?q=repo%3Acupy%2Fcupy%20runtimeGetVersion&type=code), I think most `runtimeGetVersion` usages can easily be eliminated.

When providing a unified wheel that supports all CUDA versions, the minor concern is that we will need a way to avoid loading the same CTK libraries from different major versions (e.g., `libcublas.so.11` and `libcublas.so.12`) in one process when implementing soft link - I was thinking of using the `runtimeGetVersion()` result as a key to decide the DSO file name for CTK libraries (as done in #7621 for NVRTC). Loading two major versions of libraries may happen when:
* Mixing multiple CUDA-powered libraries in a single process. For example, when PyTorch built for CUDA 11.x is installed, I think most users will expect CuPy to pick CUDA 11.x as well, regardless of the system configuration.
* Resolving dependencies between CTK libraries. For example, as cuSOLVER depends on cuBLAS and cuSPARSE, cuSOLVER 12.x will load cuBLAS 12.x. However, depending on the system configuration (e.g., ldconfig), CuPy might not be able to find cuBLAS 12.x and instead load cuBLAS 11.x.

**Comment by leofang** [comment]
@kmaehashi Thanks for your supportive reply and sorry for late response. I agree it is a legit concern. 
> ... I was thinking of using the `runtimeGetVersion()` result as a key to decide the DSO file name for CTK libraries (as done in #7621 for NVRTC). Loading two major versions of libraries may happen ...

Unfortunately, there are precedences where CUDA libraries' major versions do not bump with CTK major change. As an example, cuSOLVER stays on v11 during the transition of CTK 11.8 -> 12.0, while cuBLAS/cuSPARSE both bump to v12. A possible solution I can think of would be to hard-wire the component version table for lookup when performing dlopen via SoftLink, so that we can identify the correct DSO filename. WDYT?

**Comment by leofang** [comment]
This is done starting CuPy v13.0.0 🚀
