### ISSUE TITLE
upcoming breakage: RAPIDS no longer releasing `rapidsai-core-dev` Docker images after 23.06

### ISSUE THREAD

**Issue by rlratzel** [cupy/cupy#7733]
### Description

Hi CuPy team, 
We noticed CuPy is using the `rapidsai/rapids-core-dev` images as a base image in a Dockerfile [here](https://github.com/cupy/cupy/blob/238374ca8a4e940f2b76537b17596e04422fb238/.pfnci/linux/tests/cuda-rapids.Dockerfile#L1). These images are no longer going to be released after RAPIDS 23.06.

Would it be possible to migrate to the new `rapidsai/rapidsai` images for RAPIDS 23.08+ testing instead? They include a conda environment with the latest RAPIDS packages installed, which can then be extended with additional build tools. Alternatively, you can use `rapidsai/mambaforge-cuda` images and install any RAPIDS or build components you need.

See:
- https://docs.rapids.ai/notices/rsn0030/
- https://github.com/rapidsai/docker/issues/539
- https://github.com/rapidsai/docker/pull/545

Let me or @raydouglass know if we can help in any way.

**Comment by kmaehashi** [comment]
Hi @rlratzel, thanks for the heads-up! I'll try changing the base image and see how it goes 😃
