### ISSUE TITLE
Removed numpy exceptions imports from the main namespace [NEP 52 - Part 1]

### ISSUE THREAD

**Issue by mtsokol** [cupy/cupy#7796]
### Description

Hi! 
I'm writing with an announcement that NumPy's exceptions are no longer available in the main namespace. Since https://github.com/numpy/numpy/pull/24316 was merged yesterday, `np.AxisError`, `np.VisibleDeprecationWarning`, `np.ComplexWarning`, `np.TooHardError` and `np.ModuleDeprecationWarning` are only available from `np.exceptions` submodule (I already filed PRs to SciPy, jax, scikit-learn, pandas and matplotlib addressing it, but here I wanted to ask if you need to make any design decision how to handle it in your codebase (e.g. how to handle dispatching between >= 1.25 and <1.25 to select proper import)).

### Additional Information

Also, [NEP 52](https://github.com/numpy/numpy/blob/main/doc/neps/nep-0052-python-api-cleanup.rst) defines a possible set of changes to the main namespace (mostly cleaning and removing unused entries). The current state of changes is available in a separate issue-comment (https://github.com/numpy/numpy/issues/24306#issuecomment-1663564574) - we would appreciate your feedback!

**Comment by kmaehashi** [comment]
Hi @mtsokol, thank you for the heads up!

Here is our policy on NumPy compatibility:
* v13 (next major release, main branch, [under development](https://github.com/cupy/cupy/issues/7555)): Provides NumPy v1.25 compatible API set, while supporting NumPy v1.22+
* v12 (stable releases, v12 branch): Provides NumPy v1.24 compatible API set, while supporting NumPy v1.21+

So in either branch, I assume we will need an approach like:

```py
try:
    import numpy.exceptions as _exceptions
except:
    import numpy as _exceptions

AxisError = _exceptions. AxisError
```

**Comment by jakirkham** [comment]
Should we add this to the CuPy 14 milestone as it relates to NumPy 2?

**Comment by jakirkham** [comment]
Think this was addressed in these PRs:

* https://github.com/cupy/cupy/pull/8346
* https://github.com/cupy/cupy/pull/8357

Also given it was backported, maybe this can be moved to the `v13` milestone?

Is there anything else still needed here?

**Comment by jakirkham** [comment]
Can this be closed? Or is something still needed here?

**Comment by kmaehashi** [comment]
I think this is done except for test code (which is in progress at #8455). I think it's ok to close this one.

**Comment by jakirkham** [comment]
Thanks Kenichi! 🙏

Should we add to this to v13 milestone since it was backported in PR ( https://github.com/cupy/cupy/pull/8471 )?

**Comment by kmaehashi** [comment]
We (in most cases) don't assign milestones to issues to simplify the workflow; in general, issues get closed when merging a PR to the main branch. I've updated the PR title instead to improve visibility.
