### ISSUE TITLE
Feature Request: cupyx.scipy.sparse.linalg.eigsh does not support the initial vector (the argument v0))

### ISSUE THREAD

**Issue by chiwhalee** [cupy/cupy#7798]
### Description

The [ scipy.sparse.linalg.eigsh ](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html#scipy-sparse-linalg-eigsh) supports passing in a guess of an initial vector (an argument v0). This vector is crucial for the performance, since it substantially accelerates convergence. The current cupy version still does not support this argument, which needs to be implemented.

**Comment by kmaehashi** [comment]
Hi @chiwhalee, it's added in #7487 and will be available in CuPy v13.

**Comment by chiwhalee** [comment]
@kmaehashi, thank you. It is excellent and I closing this feature request.
