### ISSUE TITLE
cupy-cuda11x  for  v13.0.0b1 ?!

### ISSUE THREAD

**Issue by kh-abd-kh** [cupy/cupy#7802]
### Description

How i can install cupy-cuda11x  for the last version not the stable?
It installs for  me cupy-cuda11x 12.2.0 not  v13.0.0b1
thank you in advance.

**Comment by kmaehashi** [comment]
Pre-release are available from our Pip index. Please refer to: https://github.com/cupy/cupy#pip

**Comment by kh-abd-kh** [comment]
ok, there is a missing -U

 pip install cupy-cuda11x -U --pre -f https://pip.cupy.dev/pre

**Comment by kmaehashi** [comment]
Ah good catch, will add it in #7803!
