### ISSUE TITLE
Outdated (?) documentation on `ndarray.get()`/`asnumpy()` synchronization behavior    

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#7820]
### Description

Currently, this is what the doc says about the stream argument (in both APIs):
<img width="536" alt="截圖 2023-08-26 上午1 03 46" src="https://github.com/cupy/cupy/assets/5534781/ccaa7d9f-74fb-4a12-a02c-40528a89c74f">
the problematic part is "otherwise, the copy is synchronous" which is not true, because the current stream is used and the copy is synchronous only when the current stream is the null stream:
https://github.com/cupy/cupy/blob/501dc69aa1246607638ced5298c48572e8bb079f/cupy/_core/core.pyx#L1851-L1858

### Idea or request for content

I suggest that we just fix the docs to match the current behavior (which existed for years) since no one came to complain 🙂

**Comment by kmaehashi** [comment]
Thanks for the catch, sounds good to me :+1:

**Comment by leofang** [comment]
> I suggest that we just fix the docs to match the current behavior (which existed for years) since no one came to complain 

@kmaehashi @emcastillo Unfortunately, I feel obliged to revisit this issue and take back the above statement, because we actually had hit bugs. The first one is discovered recently in cuQuantum Python:
https://github.com/NVIDIA/cuQuantum/blob/c202ee7ad23ce9a5072a32b45d36e8310a20eeb5/python/cuquantum/cutensornet/tensor_network.py#L774-L775
and the second one was from an internal study of CuPy (sorry for lack of pointers). 

Basically, any usage pattern like this
```py
with cp.cuda.Stream(non_blocking=True):
    out_d = cp.do_something(...)
    out_h = cp.asnumpy(out_d)  # same for using get()
    ... = np.do_something(out_h)
```
(which is all over the place) is technically a race, because `cp.do_something()` could be a compute-intensive workload on GPU, but running asynchronously so that by the time `np.do_something()` fires, the actual data is still being produced on GPU.

Unfortunately, neither the [data transfer tutorial](https://docs.cupy.dev/en/stable/user_guide/basic.html#move-array-from-a-device-to-the-host) nor the API docs had mentioned about the potential race due to asynchronousity, and most users (including experienced developers like me 😞) would not pay attention to sync after `asnumpy()`/`get()`. 

In other to be backward compatible (no user code change) while ensuring correctness, I propose the following two solutions:
1. Deem the current API docs (see the screenshot in the beginning of this issue) correct, this means
   - any advanced users seeking async D2H copies should pass a `stream` object explicitly (as already hinted)
   - when `stream` is not given, don't do any special treatment for stream 0, we always call the blocking `ptr.copy_to_host()`
2. Remove the `stream` argument in favor of a bool `nonblocking`, following PyTorch's [`Tensor.to()`](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html#torch.Tensor.to)
   - when `nonblocking` is `True` (default), copy is blocking
   - when `nonblocking` is `False`, copy is nonblocking

In either case, the copy shall be done on the given stream (if any) or the current stream, and users are required to set up the stream dependency (as they would do for any async APIs). Please share your thoughts, thank you 🙂

**Comment by kmaehashi** [comment]
My apologies, I missed your mention. :bow:
Let me confirm if my understanding is correct: when performing D2H copy on non-default stream, `cudaMemcpyAsync` is synchronous with respect to the host thread if `non_blocking=False`, and asynchronous if `non_blocking=True`?

How about adding `async=False` argument to `ndarray.get()`/`asnumpy()`?

**Comment by leofang** [comment]
> Let me confirm if my understanding is correct: when performing D2H copy on non-default stream, `cudaMemcpyAsync` is synchronous with respect to the host thread if `non_blocking=False`, and asynchronous if `non_blocking=True`?

No, it's simpler than that. Regardless what `non_blocking` is (which refers to `cudaStreamNonBlocking` and is w.r.t the legacy default stream, not the host), if a non-default stream is in use, currently the D2H copy is asynchronous.

> How about adding `async=False` argument to `ndarray.get()`/`asnumpy()`?

Fine with me, I can work on this once we agree to fix it 🙂

**Comment by kmaehashi** [comment]
> No, it's simpler than that. Regardless what `non_blocking` is (which refers to `cudaStreamNonBlocking` and is w.r.t the legacy default stream, not the host), if a non-default stream is in use, currently the D2H copy is asynchronous.

Thanks Leo, got it! The current implementation is surprising to me as well...

> > How about adding `async=False` argument to `ndarray.get()`/`asnumpy()`?
> 
> Fine with me, I can work on this once we agree to fix it 🙂

I think `async=False` is what most users expect, and also intuitive for advanced users (rather than asking them to explicitly specify `stream`). This is also consistent with the proposal of adding `async=True` to `cupy.asarray` & `cupy.array`  (https://github.com/cupy/cupy/issues/7821#issuecomment-1695185384).
