### ISSUE TITLE
Efficient CPU->GPU copies with pinned memory

### ISSUE THREAD

**Issue by sk1p** [cupy/cupy#7821]
### Description

As documented in https://github.com/cupy/cupy/pull/5155#discussion_r621808782, using pinned memory actually doesn't prevent the on-CPU copy to pinned memory before starting the transfer. This is unfortunate, as it adds unnecessary load on the CPU, and thus latency before the GPU work can start.

There have been discussions on this before, for example in #7532 and #3450, but I'd like to open this issue for discussing a different approach.

I understand that the cause for the additional copy is a data race, as the user can change the array that is currently being copied. But in many of our use cases, the data we transfer to the GPU is immutable, for example if it was read from disk, or if it comes out of a pre-processing pipeline. In that case, we will not touch (at least, not write to) the array after starting the transfer, and it would be safe to not copy.

Maybe it would be possible to add an explicit way of omitting this copy. Either by explicitly calling a replacement for `cupy.asarray` that is explicitly documented to only work on immutable data, or by eliding the copy if the `WRITABLE` flag is set to `False` in the source array.

### Additional Information

In `pytorch`, using pinned memory elides the additional copy, for example:

```python
import torch
f = torch.zeros(shape, dtype=torch.float32, device='cpu').pin_memory()
f[:] = some_data
f_dev = torch.as_tensor(f, device='cuda')
```

See also https://github.com/LiberTEM/sparseconverter/issues/20 for some example code and results from a very simple benchmark.

**Comment by takagi** [comment]
Thanks for your suggestion.

> explicitly calling a replacement for cupy.asarray

Something like `cupy.asarray(..., async=True)` may be fine.

**Comment by kmaehashi** [comment]
Thank you for raising this to the discussion @sk1p. I agree that the case where the source array is modified during copy is rare.

> Either by explicitly calling a replacement for `cupy.asarray` that is explicitly documented to only work on immutable data, or by eliding the copy if the `WRITABLE` flag is set to `False` in the source array.

This will be backward-incompat change, but adding keyword-only `async=True` argument to `cupy.asarray` / `cupy.array` is what I'm thinking now to support this usecase. I think it's safe to assume that users passing pinned memory to `cupy.asarray` are careful enough to be aware of the data race (and pass `async=False` if necessary).

I'd avoid `WRITABLE` flag as an indicator to trigger an async copy for the following two reasons:
1. If we do this, users will start adding `pinned_arr.flags.writeable = False` everywhere, which is intuitive for their code
2. `WRITABLE` flag itself is mutable, so it is a half-baked solution

cc/ @leofang

**Comment by leofang** [comment]
This is my current thinking and subject to change 🙂 I tentatively agree with what @kmaehashi said above. What we need is a flag like `async=True` telling us that an async H2D copy is OK. This flag is independent of
- regular or pinned memory (we can also support regular/unpinned memory, and let CUDA driver to handle the staging internally if using regular memory)
- writable or readonly (if the user can guarantee that no data race could happen, even a writable NumPy array can be copied asynchronously)

However, a flip side is that setting `async=False` as default (for backward compatibility) is also a performance pitfall, especially for users of `cupyx.{empty,empty_like,zeros,zeros_like}_pinned()` who would trust us providing the pinned memory and think it'd improve performance H2D/D2H copies. I wonder if we could try to detect if pinned memory is in use, and raise a `PerformanceWarning` or alike if `async` is set to `False`?

**Comment by sk1p** [comment]
Thanks for your quick response!

> This will be backward-incompat change, but adding keyword-only `async=True` argument to `cupy.asarray` / `cupy.array` is what I'm thinking now to support this usecase. 

True about `WRITABLE`, and I'd be very happy with the `async=True` flag. 

> I think it's safe to assume that users passing pinned memory to `cupy.asarray` are careful enough to be aware of the data race

Especially if this is well documented it should be fine, maybe even with an example on the memory management page.

>  (and pass `async=False` if necessary).

Would it be possible to use an event in this case, to synchronize any write-after-transfer operations, so that we do take care of the data race, but without keeping the CPU busy via the copy? Or is that something the users should do themselves?

**Comment by kmaehashi** [comment]
> Would it be possible to use an event in this case, to synchronize any write-after-transfer operations, so that we do take care of the data race, but without keeping the CPU busy via the copy? Or is that something the users should do themselves?

[`Stream.launch_host_func`](https://docs.cupy.dev/en/stable/reference/generated/cupy.cuda.Stream.html#cupy.cuda.Stream.launch_host_func) may be used to add callback which writes to the source array, but haven't tested :sweat_smile:

**Comment by kmaehashi** [comment]
> I wonder if we could try to detect if pinned memory is in use, and raise a `PerformanceWarning` or alike if `async` is set to `False`?

It seems `cudaPointerGetAttributes` can be used.

https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__UNIFIED.html#group__CUDART__UNIFIED_1gd89830e17d399c064a2f3c3fa8bb4390
> `cudaMemoryTypeHost` for registered host memory

**Comment by kmaehashi** [comment]
Milestone tentatively set to v13 (major would be a good timing to introduce no-comapt changes).

**Comment by leofang** [comment]
@kmaehashi is anyone working on this? If not, I'll handle it together with #7820.

**Comment by kmaehashi** [comment]
No one has started working on this. Thank you for volunteering!
