### ISSUE TITLE
Add dtype argument to cupy.load

### ISSUE THREAD

**Issue by kerrylu** [cupy/cupy#7841]
### Description

Currently cupy.load does not take dtype as an argument, so if one wants to load a .npy file into the GPU as a certain data type, they have to first call numpy.load and then convert the loaded numpy array into that data type as they copy it to GPU through cupy.array or cupy.asarray.

This can be easily changed by adding dtype as an optional argument to cupy.load.

```[tasklist]
### Tasks
```

**Comment by kmaehashi** [comment]
`cupy.load` is a CuPy counterpart of `numpy.load`, so we'd keep the same signature. Will `cupy.asarray(numpy.load(...), dtype=cupy.float32)` work for you?

**Comment by kerrylu** [comment]
I see, thanks!
