### ISSUE TITLE
`NCCLBackend` can deadlock program exit

### ISSUE THREAD

**Issue by milesvant** [cupy/cupy#7863]
### Description

The `TCPStore` server process within `NCCLBackend` is stopped only in the destructor of `TCPStore`:
https://github.com/cupy/cupy/blob/5f6b487050c7db0c9a87680b18bc22eb8962cc65/cupyx/distributed/_store.py#L57-L59
Since Python will not exit before its non-daemon child processes, this can deadlock if a `NCCLBackend` lives as long as your program. This is relatively easy to get around (e.g. just set the backend to `None` once done with it, or only use it in a smaller scope) but still seemed like unintentional behavior.

### To Reproduce

This program deadlocks:
```py
from cupyx.distributed import init_process_group

backend = init_process_group(
    n_devices = 1,
    rank = 0,
    host = "localhost",
    port = 13333
)
```

### Installation

Built from GitHub source

### Environment

```
OS                           : Linux-6.2.0-32-generic-x86_64-with-glibc2.35
Python Version               : 3.10.12
CuPy Version                 : 13.0.0b1
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.25.0
SciPy Version                : 1.11.1
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 12020
CUDA Driver Version          : 12020
CUDA Runtime Version         : 12020
cuBLAS Version               : (available)
cuFFT Version                : 11008
cuRAND Version               : 10303
cuSOLVER Version             : (11, 5, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 2)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : 4a37de0
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : 21805
NCCL Runtime Version         : 21805
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 3090 Ti
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:0A:00.0
```

**Comment by milesvant** [comment]
Providing a `.stop()` method to the distributed backends is one simple way to avoid this, like: https://github.com/milesvant/cupy/commit/98ab26c140dbb8aa904a10a45680ad117aaa0eeb. I can PR that commit if this is an acceptable solution.

**Comment by emcastillo** [comment]
Thanks for reporting this!
We would welcome a PR to fix it!
