### ISSUE TITLE
Issue with piecewise log functions in Sympy->Cupy lambdify chain

### ISSUE THREAD

**Issue by Zhyrek** [cupy/cupy#7872]
### Description

Hi,

For what I'm working on, I need to get arbitrary functions from sympy expressions, which are almost always piecewise in nature and contain logarithms.

For most "normal" functions, converting this to a cupy function using sympy.lambdify(args, expr, "cupy") works as intended, but for piecewise logarithmic functions, there's a disconnect between sympy and cupy. For non-logarithmic piecewise functions, errors aren't thrown when using cupy.fuse, but the generated kernel does not respect the piecewise condition.

Attached is a minimal example showing intended behavior (targeting "math" in sympy, single computation only), and two attempts at getting this to work in cupy, one using cupy.fuse, one simply targeting cupy with sympy's lambdify. Additionally, an example showing how a non-logarithmic piecewise function returns a result, but ignores the piecewise condition.

(Code was built for ROCm, in case this is one of those weird ROCm vs CUDA edge cases of usability!)

I've also copied the issue to here: https://github.com/sympy/sympy/issues/25703 as it could relate to either library!

### To Reproduce

```py
import sympy as sp
import cupy as cp

x = sp.var("x")
expr = sp.Piecewise(
    (x*sp.log(x), x > 1e-12),
    ( 0, True)
)
math_ufunc = sp.lambdify(x, expr, "math")

print(math_ufunc(2))
print(math_ufunc(-0.1))
```
1.3862943611198906
0

```py
cp_fused_ufunc = cp.fuse(math_ufunc)
arr = cp.array([2, -0.1])
print(cp_fused_ufunc(arr))
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
File cupy/_core/fusion.pyx:891, in cupy._core.fusion.Fusion.__call__()

File cupy/_core/fusion.pyx:732, in cupy._core.fusion._FusionHistory.get_fusion()

File <lambdifygenerated-15>:2, in _lambdifygenerated(x)
      1 def _lambdifygenerated(x):
----> 2     return ((x*log(x)) if (x > 1.0e-12) else (0))

File cupy/_core/fusion.pyx:294, in cupy._core.fusion._FusionVarScalar.__bool__()

Exception: Can't cast to bool

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Cell In[21], line 3
      1 cp_fused_ufunc = cp.fuse(math_ufunc)
      2 arr = cp.array([2, -0.1])
----> 3 print(cp_fused_ufunc(arr))

File cupy/_core/fusion.pyx:897, in cupy._core.fusion.Fusion.__call__()

File cupy/_core/new_fusion.pyx:157, in cupy._core.new_fusion.Fusion.__call__()

File cupy/_core/new_fusion.pyx:28, in cupy._core.new_fusion._get_fused_kernel()

File cupy/_core/_fusion_trace.pyx:592, in cupy._core._fusion_trace.trace()

File cupy/_core/_fusion_trace.pyx:534, in cupy._core._fusion_trace.TraceImpl.trace()

File <lambdifygenerated-15>:2, in _lambdifygenerated(x)
      1 def _lambdifygenerated(x):
----> 2     return ((x*log(x)) if (x > 1.0e-12) else (0))

TypeError: must be real number, not _ArrayProxy

```py
import sympy as sp
import cupy as cp

x = sp.var("x")
expr = sp.Piecewise(
    (x*sp.log(x), x > 1e-12),
    ( 0, True)
)
func = sp.lambdify(x, expr, "cupy")

arr = cp.array([2, -0.1])

print(func(arr))
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[12], line 13
      9 func = sp.lambdify(x, expr, "cupy")
     11 arr = cp.array([2, -0.1])
---> 13 print(func(arr))

File <lambdifygenerated-9>:2, in _lambdifygenerated(x)
      1 def _lambdifygenerated(x):
----> 2     return select([greater(x, 1.0e-12),True], [x*log(x),0], default=nan)

File ~/[path]/[to]/cupy/_indexing/indexing.py:197, in select(condlist, choicelist, default)
    195 for i in range(len(choicelist)):
    196     if not isinstance(choicelist[i], cupy.ndarray):
--> 197         raise TypeError("choicelist only accepts lists of cupy ndarrays")
    198     cond = condlist[i]
    199     if cond.dtype.type is not cupy.bool_:

TypeError: choicelist only accepts lists of cupy ndarrays

```py
import sympy as sp
import cupy as cp

x = sp.var("x")
expr = sp.Piecewise(
    (2*x, x > 1e-12),
    ( 0, True)
)
simple_ufunc = sp.lambdify(x, expr, "math")
print(simple_ufunc(2.))
print(simple_ufunc(-0.1))

cp_simple_ufunc = cp.fuse(simple_ufunc)
arr = cp.array([2., -0.1])
print(cp_simple_ufunc(arr))
```
4.0
0
[ 4.  -0.2]

### Installation

Source (`pip install cupy`)

### Environment

```
OS                        : [Linux x86_64]
Python Version            : 3.10.13
CuPy Version              : 12.2.0
CuPy Platform             : AMD ROCm
NumPy Version             : 1.26.0
SciPy Version             : 1.11.2
Cython Build Version      : 0.29.36
Cython Runtime Version    : None
CUDA Root                 : None
hipcc PATH                : None
CUDA Build Version        : 50631062
CUDA Driver Version       : 50631062
CUDA Runtime Version      : 50631062
cuBLAS Version            : (available)
cuFFT Version             : 10023
cuRAND Version            : 201017
cuSOLVER Version          : (3, 22, 0)
cuSPARSE Version          : (available)
NVRTC Version             : (9, 0)
Thrust Version            : 101702
CUB Build Version         : 201301
Jitify Build Version      : None
cuDNN Build Version       : None
cuDNN Version             : None
NCCL Build Version        : 21605
NCCL Runtime Version      : 21605
cuTENSOR Version          : None
cuSPARSELt Build Version  : None
Device 0 Name             : AMD Instinct MI250X
Device 0 Arch             : gfx90a:sramecc+:xnack-
Device 0 PCI Bus ID       : 0000:c1:00.0
Device 1 Name             : AMD Instinct MI250X
Device 1 Arch             : gfx90a:sramecc+:xnack-
Device 1 PCI Bus ID       : 0000:c6:00.0
Device 2 Name             : AMD Instinct MI250X
Device 2 Arch             : gfx90a:sramecc+:xnack-
Device 2 PCI Bus ID       : 0000:c9:00.0
Device 3 Name             : AMD Instinct MI250X
Device 3 Arch             : gfx90a:sramecc+:xnack-
Device 3 PCI Bus ID       : 0000:ce:00.0
Device 4 Name             : AMD Instinct MI250X
Device 4 Arch             : gfx90a:sramecc+:xnack-
Device 4 PCI Bus ID       : 0000:d1:00.0
Device 5 Name             : AMD Instinct MI250X
Device 5 Arch             : gfx90a:sramecc+:xnack-
Device 5 PCI Bus ID       : 0000:d6:00.0
Device 6 Name             : AMD Instinct MI250X
Device 6 Arch             : gfx90a:sramecc+:xnack-
Device 6 PCI Bus ID       : 0000:d9:00.0
Device 7 Name             : AMD Instinct MI250X
Device 7 Arch             : gfx90a:sramecc+:xnack-
Device 7 PCI Bus ID       : 0000:de:00.0

```

Also, scipy version: 1.12

**Comment by asi1024** [comment]
@Zhyrek There is no plan to support `sympy.FunctionClass` in `cupy.fuse`. How about the following implementation?

```py
import cupy as cp

def func(x):
    return cp.where(x > 1e-12, x * cp.log(x), 0)

arr = cp.array([2, -0.1])
print(func(arr))
```
