### ISSUE TITLE
Add support for advanced data layouts in FFT plans

### ISSUE THREAD

**Issue by Nordicus** [cupy/cupy#7882]
### Description

The CUDA documentation describes several ways to perform Fourier transforms. One way that FFTs can be used is described in [advanced data layout](https://docs.nvidia.com/cuda/cufft/index.html#advanced-data-layout).
This allows for FFTs to be strided in either input or output by appropriately setting up the plan in advance, which reduces the necessary computations when sufficient striding is used compared to performing a full fourier transform and then filtering the array or vice-versa.

Cupy already supports using [explicit plans](https://docs.cupy.dev/en/stable/reference/generated/cupyx.scipy.fftpack.get_fft_plan.html) for FFTs, although these do not allow the full flexibility of the CUDA API.

This feature would add support for creating a plan for an advanced data layout and then executing it using the cufftPlanMany API.

### Additional Information

In my specific use case, my application involves a 2D forward transform, and extracting the phase of a single value in the output.
The second step is a backward transform of a mostly zero array, where only the transformed pixel above is used (after modifying its amplitude).

By appropriately striding the transform, the performance of this sparse problem could be significantly improved.

**Comment by kmaehashi** [comment]
Looks like a duplicate of #3263? cc/ @leofang

**Comment by Nordicus** [comment]
Yes, it looks like it is a duplicate of that.
I think in this case it's a matter of there being no documentation for cupy.cuda.cufft.PlanNd

**Comment by leofang** [comment]
`PlanNd`/`XtPlanNd` are semi-internal, low-level APIs for adventurous users who want to build FFT plans manually. That said, in CuPy strides layout is already supported based on the input/output strides, and I am not sure what's missing in CuPy's treatment behind the public FFT APIs, or what would be the perf gain compared to building a plan yourself. @Nordicus Can you share more info on what exactly you want to achieve? The application that you described is basically standard ptychography, also a foundation of many image/signal processing routines, so I am not sure what you're trying to express with the advanced layout.

**Comment by Nordicus** [comment]
Having played around with this API, I've realised that it doesn't actually do what I thought I wanted to do with it.
I am trying to do ptychography, but with ultra-sparse data. In particular each diffraction pattern has a single count. Obviously this is significantly more computationally intensive than traditional ptychography, which is already pretty bad, so if an algorithm exists (in a language I can work with easily) to do an even faster Fourier transform for 1-sparse data, then that is what I'm actually looking for. I'm probably looking for something like a CuPy implementation of the [MIT](doi.org/10.1145/2213977.2214029) [SFFT](doi.org/10.5555/2095116.2095209), but even then I'm not 100% sure if that's what I'd need or if it would definitely get me the speedup necessary for my application.
