### ISSUE TITLE
`cupy.ndarray` can be assigned with a custom attribute without an error.

### ISSUE THREAD

**Issue by yapolyak** [cupy/cupy#7883]
### Description

Hi,

I have noticed that while in version 10.4, if one tries to assign a new attribute to a `cupy.ndarray`, an `AttributeError` is raised, in the same way as `numpy.ndarray` would. However, in the recent versions of `cupy`, i.e. 12.1.0 and 12.2.0, no such error is being raised and an attribute is easily added and assigned, just like for a custom Python object. It looks like a bug to me, but of course if it is a feature, I am sorry for raising this. Although it would be interesting to understand why such feature would be needed for this data structure.

### To Reproduce

```py
arr = cupy.ndarray((2,2))
arr.custom_attr = 0
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
OS                           : Linux-5.14.21-150400.24.69_12.0.74-cray_shasta_c-x86_64-with-glibc2.31
Python Version               : 3.9.16
CuPy Version                 : 12.1.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.25.1
SciPy Version                : 1.11.1
Cython Build Version         : 0.29.35
Cython Runtime Version       : None
CUDA Root                    : /global/homes/i/ipolyak/.conda/envs/py-cuquantum-23.06.0-mypich-py3.9
nvcc PATH                    : None
CUDA Build Version           : 12000
CUDA Driver Version          : 12000
CUDA Runtime Version         : 12000
cuBLAS Version               : (available)
cuFFT Version                : 11000
cuRAND Version               : 10301
cuSOLVER Version             : (11, 4, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 0)
Thrust Version               : 200001
CUB Build Version            : 200001
Jitify Build Version         : 4e18da2
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : 10700
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA A100-PCIE-40GB
Device 0 Compute Capability  : 80
Device 0 PCI Bus ID          : 0000:C3:00.0
```

**Comment by leofang** [comment]
IIUC this is likely because during the work of supporting subclasses, `cupy.ndarray` became a plain Python class instead of Cython `cdef class`. I am not aware of limitation of turning it into a `cdef class`, though, seems nice to not allow inserting custom attributes indeed. Maybe @takagi knows better about the technical considerations?

**Comment by kmaehashi** [comment]
Thanks for raising this one. This is indeed an unexpected change of behavior.

> IIUC this is likely because during the work of supporting subclasses, `cupy.ndarray` became a plain Python class instead of Cython `cdef class`.

Yes.

> I am not aware of limitation of turning it into a `cdef class`, though, seems nice to not allow inserting custom attributes indeed.

The problem is that `__new__` (which is required to support NumPy's subclassing semantics) is not yet supported in Cython classes: https://github.com/cython/cython/issues/799

**Comment by leofang** [comment]
Thanks, Kenichi-san. Sound like something worth reporting back to upstream. For CuPy's use case (which was also the use case in the linked Cython issue -- supporting array subclasses), would adding `__slot__` to the Python class help?

**Comment by kmaehashi** [comment]
I guess `__slots__` will prevent adding custom attributes in cupy.ndarray subclasses (which should be allowed)? In that case we will need to override `__setattr__` to fix this one.

**Comment by leofang** [comment]
I think during inheritance, plain Python subclasses get an additional `__dict__` so that it's already allowed by default. From https://docs.python.org/3/reference/datamodel.html#object.__slots__:
> __slots__ are implemented at the class level by creating [descriptors](https://docs.python.org/3/reference/datamodel.html#descriptors) for each variable name. As a result, class attributes cannot be used to set default values for instance variables defined by __slots__; otherwise, the class attribute would overwrite the descriptor assignment.

Example:
```py
>>> class A:
...     __slots__ = ('x',)
... 
>>> 
>>> a = A()
>>> a.x = 3  # allowed
>>> a.y = 1  # not allowed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'A' object has no attribute 'y'
>>>
>>> class B(A):
...     pass
... 
>>> 
>>> b = B()
>>> b.x = 4  # allowed 
>>> b.y = 1  # allowed
>>> b.z = 2  # allowed
```

**Comment by leofang** [comment]
(sorry, quoted the wrong item, just fixed)

**Comment by kmaehashi** [comment]
Oh thanks, didn't know that! Let's add `__slots__` then 😄

**Comment by yapolyak** [comment]
Thank you @leofang and @kmaehashi for the addressing the issue and interesting insights! I also thought about custom `__slots__` when I saw this!
