### ISSUE TITLE
Install .pxd files

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#79]
[CuPy Overview](http://docs.cupy.chainer.org/en/latest/overview.html) says:

> CuPy also includes following features for performance:
> * Customizable memory allocator, and a simple memory pool as an example

When writing a custom memory allocator from scratch, I want to reuse or inherit some classes in CuPy (``cupy.cuda.memory.Memory``, ``cupy.cuda.memory.MemoryPointer``).  However ``*.pxd`` files are not installed along with the module by ``pip install cupy``, so cupy modules cannot be cimported from my Cython module.  Currently I have to copy ``*.pxd`` files from CuPy source tree to my project and specify the path to ``include_path`` option when building my module using Cython.

So it would be nice if CuPy installs ``*.pxd`` files to make it cimport-able from other packages.  I think this is possible by using ``package_data`` option as mentioned in the Cython docs:

* http://docs.cython.org/en/latest/src/userguide/sharing_declarations.html#search-paths-for-definition-files
* https://stackoverflow.com/questions/36853975/can-i-pip-install-a-cython-module-and-make-its-pxds-available-for-cimport

**Comment by okuta** [comment]
Thank you for your comment.
Current CuPy does not provide Cyhton interface ( `*.pxd` file).
Please implement by Python. Maybe, it is enough in most case.

Do you have some special reason to use Cython?

**Comment by kmaehashi** [comment]
I'm using Cython for performance.  Internal testing (micro benchmark to malloc/free memory blocks) shows that my memory allocator implemented in Cython was 5x faster than one implemented in pure-python.

Just to make sure, this issue is not urgent for me as I have a workaround as noted above.

**Comment by okuta** [comment]
I close this issue. We will discuss this issue in #130.
