### ISSUE TITLE
Was able to import cupy, but unable to import cupy.cuda

### ISSUE THREAD

**Issue by KaiserWhoLearns** [cupy/cupy#7907]
### Description

Was able to import `cupy`, but unable to import `cupy.cuda`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cupy.cuda'
```

### To Reproduce

```py
>>> import cupy
>>> import cupy.cuda
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
>>> cupy.show_config()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cupy' has no attribute 'show_config'
```

**Comment by KaiserWhoLearns** [comment]
It is possible that it is a result of conda installation
`conda install -c conda-forge cupy cuda-version=11.8` gives me `conda-forge/linux-64::cupy==12.2.0=py311h3a0c632_2` - is cupy supposed to be 11.8, too?

**Comment by leofang** [comment]
It sounds more like a result of corrupted environment. What's the output of `conda list` and `conda info`?

**Comment by KaiserWhoLearns** [comment]
Thank you! It is indeed a corrupted environment. It was resolved by cleaning up the conda env and creating the whole environment from scratch.
