### ISSUE TITLE
Fix CI failure with NumPy 1.25 & 1.26

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7946]
Currently we are seeing test failures in NumPy 1.25/1.26 CI:
https://ci.preferred.jp/cupy.linux.cuda122/146077/#L23527
> FAILED cupy_tests/creation_tests/test_ranges.py::TestRanges::test_logspace_array_start_stop_axis1

It seems `logspace` behavior has been changed in NumPy 1.25:

Reproducer:
```
import numpy as xp
start = xp.array([0, 2], dtype=xp.float16)
stop = xp.array([2, 0], dtype=xp.float16)
out = xp.logspace(start, stop, num=5, dtype=xp.float32, axis=1)
```

Output:

```
NumPy 1.24.4 or earlier:
[[  1.          3.1621094  10.         31.625     100.       ]
 [100.         31.625      10.          3.1621094   1.       ]]

NumPy 1.25 or 1.26:
[[  1.          3.1622777  10.         31.622776  100.       ]
 [100.         31.622776   10.          3.1622777   1.       ]]
```

I guess this PR is the cause of this difference.

https://github.com/numpy/numpy/pull/23275/files#diff-3b77932e973cdefc77a3face1640194019db54dc9c39b19c81027966dedce418R290

cc/ @seberg

**Comment by kmaehashi** [comment]
Thanks for your quick response! I'll skip the test in CuPy for now.

**Comment by mhvk** [comment]
Should be fixed by https://github.com/numpy/numpy/pull/25919

**Comment by kmaehashi** [comment]
Thanks for letting us know, @mhvk!
