### ISSUE TITLE
`cupyx.scipy.signal` incomplete in latest version

### ISSUE THREAD

**Issue by bionictoucan** [cupy/cupy#7959]
### Description

I am currently using cupy v12.2.0 with CUDA 11.8 and python 3.10 on Ubuntu 20.04. I am trying to use `find_peaks` from `cupyx.scipy.signal` but am unable to import this. I had a look in my environment directory `/path/to/miniconda/envs/env_name/lib/python3.10/site-packages/cupyx/scipy/signal/` but the only files it contains are `_bsplines.py`, `__init__.py`, `_signaltools_core.py` and `_signaltools.py` and not any of the other files that are present in the git repo. I installed this via pip using `python -m pip install cupy-cuda11x`.

I am going to try installing from source and I'll update if it works through those means!

### To Reproduce

```py
# Write the code here
from cupyx.scipy.signal import find_peaks
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
# Paste the output here
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from cupyx.scipy.signal import find_peaks

ImportError: cannot import name 'find_peaks' from 'cupyx.scipy.signal' (/home/gwb21218/miniconda3/envs/dm2/lib/python3.10/site-packages/cupyx/scipy/signal/__init__.py)
```

**Comment by kmaehashi** [comment]
`find_peaks` is new in v13.0.0b1 (#7640). Try the pre-release version if you're interested 😃 
https://github.com/cupy/cupy?tab=readme-ov-file#installation
