### ISSUE TITLE
Missing ufuncs

### ISSUE THREAD

**Issue by kohr-h** [cupy/cupy#796]
CuPy's ufuncs are roughly the same as of Numpy 1.9. The following have been added to Numpy in the meanwhile:

- 1.10: `'abs', 'cbrt', 'bitwise_not'` (alias `abs = absolute` exists)
- 1.11: none
- 1.12: `'float_power'`
- 1.13: `'divmod', 'heaviside', 'positive'`

Furthermore, the following are missing as well:
- `'conjugate', 'fabs', 'spacing'`

It seems as if `conjugate` just requires an alias, and that `divmod` is just not exported.
Furthermore, `positive`, `float_power` and `fabs` just differ in the types from existing ufuncs.

**Comment by kmaehashi** [comment]
Let me close this as the missing features are now comprehensively listed in the docs: https://docs.cupy.dev/en/stable/reference/comparison.html

I confirmed some of the ufuncs listed are still not implemented.
We always welcome pull-requests for missing ones!
