### ISSUE TITLE
Performance Degradation in CuPy cuFFT: Runtime Increases from 6 Minutes to 10 Hours After Doubling Input Array Size

### ISSUE THREAD

**Issue by Eric-AMF** [cupy/cupy#7978]
### Description

I'm working with a computational model in Python that involves multiple FFT/iFFT operations using CuPy 11.6.0 with the cuFFT backend. The model performed well with input arrays of size up to 2^27 elements (double complex), taking about 6.5 minutes to run. However, after increasing the array size to 2^28 elements, the runtime has drastically increased to approximately 10 hours.

My setup includes an i9 9900k CPU, 128 GB RAM, ASUS 4090 OC 24 GB GPU, running on Windows 10 (64-bit) with Python 3.7.7, CUDA Toolkit 12.3, NVIDIA driver 536.99.

Profiling with Nsight Compute has indicated warnings about kernels being launched with only 1 block and 1 grid. Unfortunately, I haven't found a way to adjust the cuFFT kernel configurations through CuPy. Attempts to use cupyx.optimizing.optimize were fruitless and, further, it cannot access cuFFT kernels.

I have a Nsight Compute report available:

https://drive.google.com/file/d/19mqFSwBZ3ghPMGrXqAcKlsdguH7AjuCU/view?usp=sharing (link to the compressed file, ~64 MB).

Please note that the file is large when uncompressed (~1GB) and may take some time to load in Nsight Compute 2023.3.0. This report is for the input array with 2^27 elements as Nsight Compute crashes with 2^28 elements.

The input data and python file to test the code can be retrieved here: 
Input data with 2^22 elements: https://drive.google.com/file/d/1jG9Uqus8U5QJi7TzDUxCmnEiT80IoWbU/view?usp=sharing

Input data with 2^27 elements: https://drive.google.com/file/d/1BT0ayq7gkJWKDTt3slX13HON1dxOfrBN/view?usp=sharing

Input data with 2^28 elements: https://drive.google.com/file/d/1BT0ayq7gkJWKDTt3slX13HON1dxOfrBN/view?usp=sharing

Python code (to load the data (same as the above), pls just uncomment one of the lines 22/23/24): https://drive.google.com/file/d/1XmVqYMWU9ZuyaFk9kMCj1kr4YQo59AsT/view?usp=sharing

I'm seeking suggestions on how to address this issue, particularly with optimizing cuFFT kernel launches or managing large arrays in CuPy. Any insights or advice would be greatly appreciated. Thank you!

### To Reproduce

```py
import os
import time
from datetime import datetime
import cupy as cp
import cupyx.scipy.fft as cufft
import scipy.fft
scipy.fft.set_global_backend(cufft)


import joblib
from joblib import load

import cupyx.scipy.signal as cpx


def core():

# Get the directory of the current script
    script_dir = os.path.dirname(os.path.abspath(__file__))

    # Construct the path to the file - Pls uncomment as needed! 
    joblib_file_path = os.path.join(script_dir, 'input_222.joblib') # array w/ 2^22 elements	
    #joblib_file_path = os.path.join(script_dir, 'input_227.joblib') # array w/ 2^27 elements
    #joblib_file_path = os.path.join(script_dir, 'input_228.joblib') # array w/ 2^28 elements

    # Load the input array
    data = joblib.load(joblib_file_path)

    L, gp, field, Dop, mnpc = data


    # Transfer data from CPU to GPU
    L = cp.asarray(L)

    gp = cp.asarray(gp)

    field = cp.asarray(field)

    Dop = cp.asarray(Dop)

    mnpc = cp.asarray(mnpc)

    # Setting loop initial conditions
    z = 0.0  #  position
    n = 0  # iteration counter

    # Shift the Dop operator 
    Dop_s = cufft.ifftshift(Dop)

    # Start loop for calculation
    start_loop = time.time()
    print(f" [{datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}] Loop has started ... ")

    while z < L:

        gE2 = gp * cp.abs(field) ** 2
        id_max = cp.argmax(gE2)
        h = min(mnpc / gE2[id_max], L - z)

        # Calculate Dop for reuse
        exp_Dop_h= cp.exp(Dop_s * h / 2.0)

        # First operators action (frequency and time domain)
        field = cufft.ifft(cufft.fft(field, overwrite_x=True) * exp_Dop_h, overwrite_x=True)
        field *= cp.exp(-1j * gp * cp.abs(field) ** 2 * h)

        # Second operator action (frequency domain)
        field = cufft.ifft(cufft.fft(field, overwrite_x=True) * exp_Dop_h, overwrite_x=True)

        z += h
        n += 1

        #print(f'h = {h}, n = {n}, and z = {z}')
        
    end_loop = time.time()
    
    print(f" [{datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}] Loop finished after {(end_loop - start_loop):.2f} seconds and {n} steps \n")

    field = cp.asnumpy(field)	

    return field


if __name__ == "__main__":
    # Capture the start time
    start_time = time.time()
    print(f"\n [{datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}] Job started\n")

    # Call the Solver function
    result = core()

    # Capture the end time
    end_time = time.time()
    print(f" [{datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}] Job finished ")

    # Calculate and print the total job time
    total_time = end_time - start_time
    print(f" Total job time: {total_time:.2f} seconds")
```

### Installation

Source (`pip install cupy`)

### Environment

```
OS                           : Windows-10-10.0.19041-SP0
Python Version               : 3.7.7
CuPy Version                 : 11.6.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.6
SciPy Version                : 1.7.3
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2
nvcc PATH                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin\nvcc.EXE
CUDA Build Version           : 12020
CUDA Driver Version          : 12020
CUDA Runtime Version         : 12020
cuBLAS Version               : (available)
cuFFT Version                : 11008
cuRAND Version               : 10303
cuSOLVER Version             : (11, 5, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 2)
Thrust Version               : 200101
CUB Build Version            : 200101
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 4090
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:03:00.0
```

**Comment by emcastillo** [comment]
> Profiling with Nsight Compute has indicated warnings about kernels being launched with only 1 block and 1 grid.

This sounds like an integer overflow in the launching configuration internally. (cc @leofang)

**Comment by Eric-AMF** [comment]
Thank you very much for your reply. Your hypothesis seems very likely. Let's wait for leofang's comments.

**Comment by Eric-AMF** [comment]
Hi @emcastillo! I've switched to Ubuntu 22.04 LTS and I believe I've pinpointed the issue I'm encountering. On Windows 10, when processing an array that doubled in size from 2^27 to 2^28 elements, the runtime became extremely slow. However, on Ubuntu, the same increase in array size results in an out-of-memory error. Here's the traceback:

<pre>(py311) <font color="#26A269"><b>eric@perseus</b></font>:<font color="#12488B"><b>/media/eric/M33/py311</b></font>$ python3 ../core.py

 [2023-11-13 at 00:05:45] Job started

 [2023-11-13 at 00:06:13] Loop has started ... 
Traceback (most recent call last):
  File &quot;/media/eric/M33/py311/../core.py&quot;, line 90, in &lt;module&gt;
    result = core()
             ^^^^^^
  File &quot;/media/eric/M33/py311/../core.py&quot;, line 61, in core
    exp_Dop_h= cp.exp(Dop_s * h / 2.0)
                      ~~~~~~~~~~^~~~~
  File &quot;cupy/_core/core.pyx&quot;, line 1307, in cupy._core.core._ndarray_base.__truediv__
  File &quot;cupy/_core/core.pyx&quot;, line 1676, in cupy._core.core._ndarray_base.__array_ufunc__
  File &quot;cupy/_core/_kernel.pyx&quot;, line 1291, in cupy._core._kernel.ufunc.__call__
  File &quot;cupy/_core/_kernel.pyx&quot;, line 644, in cupy._core._kernel._get_out_args_from_optionals
  File &quot;cupy/_core/core.pyx&quot;, line 2765, in cupy._core.core._ndarray_init
  File &quot;cupy/_core/core.pyx&quot;, line 241, in cupy._core.core._ndarray_base._init_fast
  File &quot;cupy/cuda/memory.pyx&quot;, line 742, in cupy.cuda.memory.alloc
  File &quot;cupy/cuda/memory.pyx&quot;, line 1419, in cupy.cuda.memory.MemoryPool.malloc
  File &quot;cupy/cuda/memory.pyx&quot;, line 1440, in cupy.cuda.memory.MemoryPool.malloc
  File &quot;cupy/cuda/memory.pyx&quot;, line 1120, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File &quot;cupy/cuda/memory.pyx&quot;, line 1141, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File &quot;cupy/cuda/memory.pyx&quot;, line 1379, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 4,294,967,296 bytes (allocated so far: 21,474,838,528 bytes).
</pre>

Monitoring GPU memory allocation with nvidia-smi, I observed that my RTX 4090 really runs out of memory when handling the 2^28 element array, while it manages the 2^27 element array with a memory usage of 19233MiB out of 24564MiB. This suggests that Windows manages GPU memory differently, likely by utilizing swap space, which allows the process to continue but at a significantly reduced speed

I will mount a new setup with two GPUs soon, and I will let you know about the outcome. Regarding using two GPUs, could you please let me know if you have any recommendations beyond what is in the documentation?

Thank you very much for your help!

**Comment by leofang** [comment]
Sorry I missed the ping. I cannot find a public reference for this behavior, but it is known that on Windows instead of hitting OOM, the OS would try to spill into system memory, and the slowness (of any kernel, not just cuFFT) is a consequence. Generally, when using large arrays one should be cautious about potential memory and overflow issues, and reports like this would help us triage/understand better, so thanks! 🙂

**Comment by leofang** [comment]
@Eric-AMF since you have access to a Windows machine, could you check setting the env var `CUPY_GPU_MEMORY_LIMIT` (to the max available number of bytes of your GPU, so 8 GiB would be `set CUPY_GPU_MEMORY_LIMIT=8589934592`) would help you hitting OOM instead of running, as on Linux?

**Comment by Eric-AMF** [comment]
@leofang @emcastillo I apologize for the delayed response. Due to an energy outage, my machine  crashed shortly  after you messaged me, and I am still working to get the simulations up and running again.  I anticipate that by tomorrow or Sunday, I should be able to perform the test you suggested. In addition, I was  developing a routine in CUDA, as I was unable to get low-level CuPy functions to distribute properly the calculations across two GPUs. I'll provide more details on this soon.

**Comment by Eric-AMF** [comment]
@leofang @emcastillo, my apologies again for the late reply. @leofang, your recommendation to use CUPY_GPU_MEMORY_LIMIT has successfully prevented swapping on Windows. Using cupy.cuda.MemoryPool.set_limit() works well too. I am currently working on rewriting this part of the code in CUDA:

    while z < L:

        gE2 = gp * cp.abs(field) ** 2
        id_max = cp.argmax(gE2)
        h = min(mnpc / gE2[id_max], L - z)

        # Calculate Dop for reuse
        exp_Dop_h= cp.exp(Dop_s * h / 2.0)

        # First operators action (frequency and time domain)
        field = cufft.ifft(cufft.fft(field, overwrite_x=True) * exp_Dop_h, overwrite_x=True)
        field *= cp.exp(-1j * gp * cp.abs(field) ** 2 * h)

        # Second operator action (frequency domain)
        field = cufft.ifft(cufft.fft(field, overwrite_x=True) * exp_Dop_h, overwrite_x=True)

        z += h
        n += 1

        #print(f'h = {h}, n = {n}, and z = {z}')
        
    end_loop = time.time()
    
    print(f" [{datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}] Loop finished after {(end_loop - start_loop):.2f} seconds and {n} steps \n")

    field = cp.asnumpy(field)	

    return field
    
Writing the fft and ifft kernels to use two GPUs in CUDA was not so hard, but the rest is proving to be more difficult. In my previous post, when I mentioned that I was unable to get low-level CuPy functions to efficiently distribute calculations across two GPUs, I meant the calculations were slow (I see CuPy's documentation warns about possible performance issues while using multi-GPUs). Perhaps soon I will gain access to A100 GPUs, which should allow me to revert exclusively to CuPy. I'll keep you updated on this as well. Thank you.

**Comment by leofang** [comment]
Thanks for confirming. Yes, `cupy.cuda.MemoryPool.set_limit()` is equivalent to `CUPY_GPU_MEMORY_LIMIT`, so pick whatever is most convenient to you.

For multi GPUs, in the future the new distributed ndarray would be useful, but it doesn't support FFT yet. For now you need to partition the work and manage the per-GPU data chunks manually.

Closing, since the original issue is resolved.
