### ISSUE TITLE
CUPY sosfilt_zi some SOS coefficients are not supported

### ISSUE THREAD

**Issue by LizbethEsther** [cupy/cupy#7990]
### Description

I want to  use scipy.signal.bessel  for highpass or lowpass filtering,and then pass the sos into sosfilt_zi。If the order of the Bessel filter is greater than one, it can be calculated normally, but if it is equal to one, the ZI value will become NAN。 But this problem doesn't come up in scipy.signal.sosfilt_zi

### To Reproduce

```py
# Write the code here
```

### Installation

None

### Environment

```
# Paste the output here
```

**Comment by LizbethEsther** [comment]
if self.task_dict['highpass']:
            if self.task_dict['highpass'] is True:
                n, wn = 1, 0.5
            else:
                n, wn = 1, self.task_dict['highpass']
            high_sos = signal.bessel(n, wn, 'hp', output='sos', fs=fs) 
            sos_list.append(high_sos)

        if self.task_dict['highpass'] or self.task_dict['remove_power_freq']:     
            self.sos = np.concatenate(sos_list, axis=0)
            self.sos = cp.asarray(self.sos)
            self.zi = sosfilt_zi(self.sos)   # this is cupy.sosfilt_zi and zi is [[1,1,nan,nan]] which is resulting in NAN

**Comment by takagi** [comment]
Can we have the result of `python -c "import cupy; cupy.show_config()"` for smoother investigation? Thanks!

I can get the following result with this script. Would you take a look into this issue, @andfoy @ev-br?
```
sos_list = []
n, wn = 1, 0.5
high_sos = signal.bessel(n, wn, 'hp', output='sos')  # use default fs
sos_list.append(high_sos)
sos_np = np.concatenate(sos_list, axis=0)
print('scipy: ', end='')
print(sosfilt_zi_sp(sos_np))
sos_cp = cp.asarray(sos_np)
print('cupy : ', end='')
print(sosfilt_zi_cp(sos_cp))
# scipy: [[-0.5  0. ]]
# cupy: [[ 1.  1. nan nan]]
```

**Comment by takagi** [comment]
Can we have the result of `python -c "import cupy; cupy.show_config()"` on your environment for smoother investigation? Thanks!

Can I ask you to take a look into this issue, @andfoy @ev-br?

**Comment by LizbethEsther** [comment]
Hello, this is the function display result~









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cupy/cupy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月27日(星期一) 中午12:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cupy/cupy] CUPY sosfilt_zi some SOS coefficients are not supported (Issue #7990)





 
Can we have the result of python -c "import cupy; cupy.show_config()" for smoother investigation? Thanks!
 
I can get the following result with this script. Would you take a look into this issue, @andfoy @ev-br?
 sos_list = [] n, wn = 1, 0.5 high_sos = signal.bessel(n, wn, 'hp', output='sos')  # use default fs sos_list.append(high_sos) sos_np = np.concatenate(sos_list, axis=0) print('scipy: ', end='') print(sosfilt_zi_sp(sos_np)) sos_cp = cp.asarray(sos_np) print('cupy : ', end='') print(sosfilt_zi_cp(sos_cp)) # scipy: [[-0.5  0. ]] # cupy: [[ 1.  1. nan nan]]

**Comment by LizbethEsther** [comment]
In addition, I have made other attempts. I found that if the order is set to odd, there will be nan; If the order is even, the result will be normal.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cupy/cupy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月27日(星期一) 中午12:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cupy/cupy] CUPY sosfilt_zi some SOS coefficients are not supported (Issue #7990)





 
Can we have the result of python -c "import cupy; cupy.show_config()" for smoother investigation? Thanks!
 
I can get the following result with this script. Would you take a look into this issue, @andfoy @ev-br?
 sos_list = [] n, wn = 1, 0.5 high_sos = signal.bessel(n, wn, 'hp', output='sos')  # use default fs sos_list.append(high_sos) sos_np = np.concatenate(sos_list, axis=0) print('scipy: ', end='') print(sosfilt_zi_sp(sos_np)) sos_cp = cp.asarray(sos_np) print('cupy : ', end='') print(sosfilt_zi_cp(sos_cp)) # scipy: [[-0.5  0. ]] # cupy: [[ 1.  1. nan nan]]
