### ISSUE TITLE
Flag to match cuda types with python types

### ISSUE THREAD

**Issue by Zhyrek** [cupy/cupy#8011]
### Description

Consider the following example:

```py
@jit.rawkernel()
def test():
    my_var = 1.2
    
test[1,1]()
print(test.cached_code)
```
```
extern "C" __global__ void test() {
  float my_var = 1.2;
}
```

In base python, `my_var` would actually be the C++ "double" type (64 bits), while the compiled code uses the 32bit C++ "float" type. Sometimes, it's really important to match the exact types for algorithms, where the 32bit float simply doesn't have enough precision to do the task.

I've vaguely imagining a use case for a flag, `cupy.MATCH_DTYPES`, which would be false by default to match current behavior. If set to true, it would ensure numpy and cuda dtypes match, e.g. the following change to a bit of code from cupyx.jit.cuda_typerules.py:

```
def get_ctype_from_scalar(mode: str, x: Any) -> _cuda_types.Scalar:
    if isinstance(x, numpy.generic):
        return _cuda_types.Scalar(x.dtype)

    #original: if mode == 'numpy'
    if (mode == 'numpy' or cupy.MATCH_DTYPES):
        if isinstance(x, bool):
            return _cuda_types.Scalar(numpy.bool_)
        if isinstance(x, int):
            # use plain int here for cross-platform portability
            return _cuda_types.Scalar(int)
        if isinstance(x, float):
            return _cuda_types.Scalar(numpy.float64)
        if isinstance(x, complex):
            return _cuda_types.Scalar(numpy.complex128)

    if mode == 'cuda':
        if isinstance(x, bool):
            return _cuda_types.Scalar(numpy.bool_)
        if isinstance(x, int):
            if -(1 << 31) <= x < (1 << 31):
                return _cuda_types.Scalar(numpy.int32)
            return _cuda_types.Scalar(numpy.int64)
        if isinstance(x, float):
            return _cuda_types.Scalar(numpy.float64)
        if isinstance(x, complex):
            return _cuda_types.Scalar(numpy.complex64)

    raise NotImplementedError(f'{x} is not scalar object.')
```

(I believe `cupy.MATCH_DTYPES = True` would match the default behavior in numba: if you do something like `my_var = 1.2` in a kernel or device function, numba treats it as a double on the GPU.)

**Comment by asi1024** [comment]
@Zhyrek You can use float64 data type as follows:

```py
@jit.rawkernel()
def test():
    my_var = numpy.float64(1.2)
```

If you want to use float64 as the default float data type, `numpy` mode is useful.

```py
@jit.rawkernel(mode='numpy')
def test():
    my_var = 1.2
```

**Comment by Zhyrek** [comment]
Oh, didn't know about this second option, that looks like exactly what I was looking for. Thanks so much! :)
