### ISSUE TITLE
Use of NumPy type aliases to be removed in NumPy 2.0

### ISSUE THREAD

**Issue by lucascolley** [cupy/cupy#8049]
https://github.com/numpy/numpy/pull/24376 removed some type aliases for NumPy 2.0

[In SciPy](https://github.com/scipy/scipy/issues/19754) (through an unusual test we have) we found errors due to the use of `numpy.float_` in CuPy. From a brief search I see that there are also uses of `numpy.complex_`.

_(This shouldn't be failing SciPy's test suite, just putting it on your radar for NumPy 2.0 compat)_

**Comment by kmaehashi** [comment]
Thanks! `numpy.float_` and `complex_` usages in CuPy looks only here:
https://github.com/cupy/cupy/blob/cb4e5127e38c1cb2bdd01ad5117d324fac1762fd/cupy/_core/_scalar.pyx#L64-L65
