### ISSUE TITLE
Failed to import Cupy when freezing

### ISSUE THREAD

**Issue by NevermindNilas** [cupy/cupy#8110]
### Description

Hi,

I am trying to freeze cupy-cuda12x using Pyinstaller but I am running into issues where certain hidden imports are not included, I am not sure if this should be addressed to either pyinstaller or you guys but here I am.

### To Reproduce

    venv_root = os.path.join(base_dir, "venv")
    cupy_include_path = os.path.join(
        venv_root, "Lib", "site-packages", "cupy", "_core", "include", "cupy")
    cupy_include_dest = ".\\cupy\\core\\include\\cupy"
    subprocess.run([
        "./venv/bin/pyinstaller" if platform.system() != "Windows" else ".\\venv\\Scripts\\pyinstaller",
        "--noconfirm",
        "--onedir",
        "--console",
        "--noupx",
        "--clean",
        "--add-data", f"{src_path};src/",
        "--add-data", f"{cupy_include_path};{cupy_include_dest}",
        "--hidden-import", ','.join(hiddenimports),
        main_path
    ], check=True)
    """
   

### Installation

Wheel (`pip install cupy-***`)

### Environment

    Failed to import CuPy.

    If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

    On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
    On Windows, try setting CUDA_PATH environment variable.

    Check the Installation Guide for details:
    https://docs.cupy.dev/en/latest/install.html

    Original error:
    ModuleNotFoundError: No module named 'cupy_backends.cuda.api._runtime_enum

### Additional Information

Hidden Imports and more elaborate code can be found in <https://github.com/NevermindNilas/TheAnimeScripter/blob/main/build.py> line 43

**Comment by leofang** [comment]
You might wanna check out other successful posts: https://github.com/cupy/cupy/issues/1262#issuecomment-1884832553

**Comment by NevermindNilas** [comment]
Hello, thank you for the quick reply.

In my attempt to fix it I have tried running the code found in the above mentioned thread, I may have misinterpreted it but I put the output of the code inside a list.

In my code I have the all of the hidden imports in a list at line 64:
https://github.com/NevermindNilas/TheAnimeScripter/blob/main/build.py

Which I then parse as a --hiden-import for Pyinstaller but I still had no luck. Have I maybe messed up?

**Comment by kmaehashi** [comment]
I finally tried pyinstaller myself 😄 I could successfully package CuPy using the `--collect-all` option.

```
% pip freeze | grep pyinstaller
pyinstaller==6.3.0
pyinstaller-hooks-contrib==2023.12

% cat testapp.py
import cupy

cupy.show_config()
print(cupy.arange(10))

% pyinstaller testapp.py --collect-all cupy --collect-all cupyx --collect-all cupy_backends --collect-all fastrlock
<snip>

% ./dist/testapp/testapp
OS                           : Linux-5.4.0-166-generic-x86_64-with-glibc2.31
Python Version               : 3.10.13
CuPy Version                 : 13.0.0rc1
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.24.4
SciPy Version                : 1.10.1
Cython Build Version         : 0.29.36
Cython Runtime Version       : 0.29.36
CUDA Root                    : /usr/local/cuda-12.2.1
nvcc PATH                    : ccache nvcc
CUDA Build Version           : 12020
CUDA Driver Version          : 12020
CUDA Runtime Version         : 12020 (linked to CuPy) / 12020 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 11008
cuRAND Version               : 10303
cuSOLVER Version             : (11, 5, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 2)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : 17372145e
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA A100-PCIE-40GB
Device 0 Compute Capability  : 80
Device 0 PCI Bus ID          : 0000:89:00.0
Device 1 Name                : NVIDIA A100-PCIE-40GB
Device 1 Compute Capability  : 80
Device 1 PCI Bus ID          : 0000:B1:00.0
Device 2 Name                : Tesla V100-PCIE-16GB
Device 2 Compute Capability  : 70
Device 2 PCI Bus ID          : 0000:88:00.0
Device 3 Name                : Tesla P100-PCIE-16GB
Device 3 Compute Capability  : 60
Device 3 PCI Bus ID          : 0000:1A:00.0
[0 1 2 3 4 5 6 7 8 9]
```
