### ISSUE TITLE
Pinned memory is not deallocated until the process exits.

### ISSUE THREAD

**Issue by murdock-grewar** [cupy/cupy#8111]
### Description

Pinned memory created with `cupyx.empty_pinned(...)`, `cupyx.zeros_pinned(...)`, et cetera, is not released by Python garbage collection, even when the relevant Python objects should be out of scope. The memory is not released until the Python process exits.

### To Reproduce

```python3
import numpy as np
import cupyx
import gc
input("Allocating pinned memory with cupyx...")
a = cupyx.zeros_pinned(2000000000, dtype=np.float32)
input("Check the RAM usage, particularly 'shared memory' in htop, then press Enter to remove the array from scope.")
del a
input("The array has been removed from scope. Check the memory usage again. The pinned memory has not been released. Press enter to explicitly run the Python garbage collection.")
gc.collect()
input("Garbage collection has been called explicitly. Check the memory usage again. It hasn't changed. Press Enter to quit. Memory will be released when the Python process exits.")
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
OS                           : Linux-6.7.0-rc6-x86_64-with-glibc2.38
Python Version               : 3.11.6
CuPy Version                 : 12.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.1
SciPy Version                : 1.11.3
Cython Build Version         : 0.29.36
Cython Runtime Version       : 0.29.36
CUDA Root                    : /nix/store/jcmaarfa2mk9qpjipihmk0h4g6my6wnx-cudatoolkit-11.8.0
nvcc PATH                    : /nix/store/jcmaarfa2mk9qpjipihmk0h4g6my6wnx-cudatoolkit-11.8.0/bin/nvcc
CUDA Build Version           : 11080
CUDA Driver Version          : 12030
CUDA Runtime Version         : 11080
cuBLAS Version               : (available)
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 8)
Thrust Version               : 101501
CUB Build Version            : 101501
Jitify Build Version         : <unknown>
cuDNN Build Version          : 8901
cuDNN Version                : 8901
NCCL Build Version           : 21903
NCCL Runtime Version         : 21903
cuTENSOR Version             : 10500
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 3070
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:0A:00.0
```

**Comment by leofang** [comment]
This is not a bug, but an expected behavior. Like GPU memory, pinned memory is scarce resource too and we pool it: https://docs.cupy.dev/en/stable/user_guide/memory.html.

**Comment by murdock-grewar** [comment]
@leofang it's not a bug when garbage collection doesn't free unused memory? Are you sure? `cupy` will not release this memory even if the process runs out of other memory. In more complicated code, I found that `free_all_blocks()` failed to release memory. I was using non-default streams. Is this a bug?

**Comment by murdock-grewar** [comment]
CuPy v13 has not resolved this issue. Calling `cupy.get_default_pinned_memory_pool().free_all_blocks()` has no effect.

**Comment by murdock-grewar** [comment]
> > Calling `cupy.get_default_pinned_memory_pool().free_all_blocks()` has no effect.
> 
> This is unexpected for us. Could you share the code to reproduce?

I found that it was a bug in my own code causing this issue. I had retained a view into a pinned array and for some reason it hadn't occurred to me that an array view leaves a dangling reference, preventing garbage collection.

I'll close this issue.
