### ISSUE TITLE
gaussian_filter does not compile

### ISSUE THREAD

**Issue by Mirebeau** [cupy/cupy#8147]
### Description

cupy version '13.0.0', on windows, installed via anaconda.

The following code snippet runs for a very long time, then outputs some long error message copied below.

Thanks for the great work, 
Best regards,

### To Reproduce

```py
import cupy as cp
from cupyx.scipy.ndimage import gaussian_filter
gaussian_filter(cp.zeros(10),2)
```

### Installation

None

### Environment

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[2], line 3
      1 import cupy as cp
      2 from cupyx.scipy.ndimage import gaussian_filter
----> 3 gaussian_filter(cp.zeros(10),2)

File ~\miniconda3\envs\agd-hfm_cuda_312\Lib\site-packages\cupyx\scipy\ndimage\_filters.py:373, in gaussian_filter(input, sigma, order, output, mode, cval, truncate)
    370         return None
    371     return _gaussian_kernel1d(sigma, order, radius, dtype=weights_dtype)
--> 373 return _run_1d_correlates(input, list(zip(sigmas, orders)), get, output,
    374                           mode, cval, 0)

File ~\miniconda3\envs\agd-hfm_cuda_312\Lib\site-packages\cupyx\scipy\ndimage\_filters.py:206, in _run_1d_correlates(input, params, get_weights, output, mode, cval, origin)
    204         wghts[param] = get_weights(param)
    205 wghts = [wghts[param] for param in params]
--> 206 return _filters_core._run_1d_filters(
    207     [None if w is None else correlate1d for w in wghts],
    208     input, wghts, output, mode, cval, origin)

File ~\miniconda3\envs\agd-hfm_cuda_312\Lib\site-packages\cupyx\scipy\ndimage\_filters_core.py:105, in _run_1d_filters(filters, input, args, output, mode, cval, origin)
    103     input = temp
    104 else:
--> 105     fltr(input, arg, axis, output, mode, cval, origin)
    106     input, output = output, temp
    107 for axis, (fltr, arg, mode, origin) in enumerate(iterator, start=axis + 1):

File ~\miniconda3\envs\agd-hfm_cuda_312\Lib\site-packages\cupyx\scipy\ndimage\_filters.py:114, in correlate1d(input, weights, axis, output, mode, cval, origin)
     83 """One-dimensional correlate.
     84 
     85 The array is correlated with the given kernel.
   (...)
    110     from SciPy due to floating-point rounding of intermediate results.
    111 """
    112 weights, origins = _filters_core._convert_1d_args(input.ndim, weights,
    113                                                   origin, axis)
--> 114 return _correlate_or_convolve(input, weights, output, mode, cval, origins)

File ~\miniconda3\envs\agd-hfm_cuda_312\Lib\site-packages\cupyx\scipy\ndimage\_filters.py:177, in _correlate_or_convolve(input, weights, output, mode, cval, origin, convolution)
    174 offsets = _filters_core._origins_to_offsets(origins, weights.shape)
    175 kernel = _get_correlate_kernel(mode, weights.shape, int_type,
    176                                offsets, cval)
--> 177 output = _filters_core._call_kernel(kernel, input, weights, output,
    178                                     weights_dtype=weights_dtype)
    179 return output

File ~\miniconda3\envs\agd-hfm_cuda_312\Lib\site-packages\cupyx\scipy\ndimage\_filters_core.py:150, in _call_kernel(kernel, input, weights, output, structure, weights_dtype, structure_dtype)
    148     output, temp = _util._get_output(output.dtype, input), output
    149 args.append(output)
--> 150 kernel(*args)
    151 if needs_temp:
    152     _core.elementwise_copy(temp, output)

File cupy\_core\_kernel.pyx:920, in cupy._core._kernel.ElementwiseKernel.__call__()

File cupy\_core\_kernel.pyx:945, in cupy._core._kernel.ElementwiseKernel._get_elementwise_kernel()

File cupy\_util.pyx:64, in cupy._util.memoize.decorator.ret()

File cupy\_core\_kernel.pyx:728, in cupy._core._kernel._get_elementwise_kernel()

File cupy\_core\_kernel.pyx:82, in cupy._core._kernel._get_simple_elementwise_kernel_from_code()

File cupy\_core\core.pyx:2254, in cupy._core.core.compile_with_cache()

File ~\miniconda3\envs\agd-hfm_cuda_312\Lib\site-packages\cupy\cuda\compiler.py:484, in _compile_module_with_cache(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream, jitify)
    480     return _compile_with_cache_hip(
    481         source, options, arch, cache_dir, extra_source, backend,
    482         name_expressions, log_stream, cache_in_memory)
    483 else:
--> 484     return _compile_with_cache_cuda(
    485         source, options, arch, cache_dir, extra_source, backend,
    486         enable_cooperative_groups, name_expressions, log_stream,
    487         cache_in_memory, jitify)

File ~\miniconda3\envs\agd-hfm_cuda_312\Lib\site-packages\cupy\cuda\compiler.py:562, in _compile_with_cache_cuda(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream, cache_in_memory, jitify)
    560 if backend == 'nvrtc':
    561     cu_name = '' if cache_in_memory else name + '.cu'
--> 562     ptx, mapping = compile_using_nvrtc(
    563         source, options, arch, cu_name, name_expressions,
    564         log_stream, cache_in_memory, jitify)
    565     if _is_cudadevrt_needed(options):
    566         # for separate compilation
    567         ls = function.LinkState()

File ~\miniconda3\envs\agd-hfm_cuda_312\Lib\site-packages\cupy\cuda\compiler.py:319, in compile_using_nvrtc(source, options, arch, filename, name_expressions, log_stream, cache_in_memory, jitify)
    316         with open(cu_path, 'w') as cu_file:
    317             cu_file.write(source)
--> 319         return _compile(source, options, cu_path,
    320                         name_expressions, log_stream, jitify)
    321 else:
    322     cu_path = '' if not jitify else filename

File ~\miniconda3\envs\agd-hfm_cuda_312\Lib\site-packages\cupy\cuda\compiler.py:284, in compile_using_nvrtc.<locals>._compile(source, options, cu_path, name_expressions, log_stream, jitify)
    280 def _compile(
    281         source, options, cu_path, name_expressions, log_stream, jitify):
    283     if jitify:
--> 284         options, headers, include_names = _jitify_prep(
    285             source, options, cu_path)
    286     else:
    287         headers = include_names = ()

File ~\miniconda3\envs\agd-hfm_cuda_312\Lib\site-packages\cupy\cuda\compiler.py:233, in _jitify_prep(source, options, cu_path)
    231 if not _jitify_header_source_map_populated:
    232     from cupy._core import core
--> 233     jitify._init_module()
    234     jitify._add_sources(core._get_header_source_map())
    235     _jitify_header_source_map_populated = True

File cupy\cuda\jitify.pyx:212, in cupy.cuda.jitify._init_module()

File cupy\cuda\jitify.pyx:233, in cupy.cuda.jitify._init_module()

File cupy\cuda\jitify.pyx:209, in cupy.cuda.jitify._init_cupy_headers()

File cupy\cuda\jitify.pyx:198, in cupy.cuda.jitify._init_cupy_headers_from_scratch()

File cupy\cuda\jitify.pyx:128, in cupy.cuda.jitify.dump_cache()

OSError: [WinError 123] La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte: 'C:\\Users\\jmmir\\.cupy\\jitify_cache\\tmp4g1dt6wx' -> 'C:\\Users\\jmmir/.cupy/jitify_cache/jitify_<unknown>_200200_11080_2_48b6eec781b708bd7e6ac50294027167c0ae5303.json'
```

**Comment by leofang** [comment]
Thanks for the bug report. I suspect it's because this line is not a valid path on Windows:
https://github.com/cupy/cupy/blob/f5d8ed48487f1ce6f31e524d5361bf6f47a4a2e4/cupy/cuda/jitify.pyx#L129
If you could build CuPy from source, maybe you can try a local patch like
```python
os.path.join(_jitify_cache_dir, f'jitify_{_jitify_cache_versions}.json')
```
and it should hopefully work. I'll get it fixed.

**Comment by Mirebeau** [comment]
> Le 30 janv. 2024 à 17:50, Leo Fang ***@***.***> a écrit :
> 
> 
> Thanks for the bug report. I suspect it's because this line is not a valid path on Windows:
> https://github.com/cupy/cupy/blob/f5d8ed48487f1ce6f31e524d5361bf6f47a4a2e4/cupy/cuda/jitify.pyx#L129
> If you could build CuPy from source, maybe you can try a local patch like
> 
> os.path.join(_jitify_cache_dir, f'jitify_{_jitify_cache_versions}.json')
> and it should hopefully work. I'll get it fixed.
> 

Perfect, thanks !
Regards,

**Comment by kmaehashi** [comment]
@leofang I think the problem is that `_jitify_cache_versions` become `<unknown>` when installed through sdist, because sdist does not contain `.git`. Windows paths cannot contain `<` or `>` so that should be the problem...

**Comment by leofang** [comment]
Interesting, but isn't it simpler to work around if @Mirebeau could install the CuPy wheel? 

@Mirebeau how did you install CuPy? I noticed you didn't fill in the issue template.

**Comment by Mirebeau** [comment]
I installed Cupy via conda-forge. 
Sorry for not filling the template properly.

**Comment by kmaehashi** [comment]
Hmm I've tested `cupy-cuda12x==13.0.0` on Linux and getting `<unknown>` :thinking:

```
% pip install cupy-cuda12x
...
% python -c 'import cupy; cupy.show_config()' | grep Jitify
Jitify Build Version         : <unknown>
```

**Comment by leofang** [comment]
So now we have two issues:
1. With wheels (I confirmed on Linux too): Jitify version is unknown
2. With conda packages (on Linux): Jitify version is **not** unknown, but @Mirebeau still saw the issue
   - @Mirebeau could you reply the outputs of the following commands (that were asked in the issue template)?
      - `conda list`
      - `python -c "import cupy; cupy.show_config()"`

**Comment by JoOkuma** [comment]
Hi, I recently updated to `13.0.0` on Linux and got a similar error when using `ndi.gaussian_filter`.

I installed it from `conda-forge.`

Error:

```python
cub/detail/detect_cuda_runtime.cuh(39): warning: cuda_runtime_api.h: [jitify] File not found
../util_type.cuh(42): warning: cuda.h: [jitify] File not found
cupy_jitify_exercise(10): warning: cooperative_groups.h: [jitify] File not found
cupy_jitify_exercise(11): warning: cooperative_groups/memcpy_async.h: [jitify] File not found
---------------------------------------------------
--- JIT compile log for cupy_jitify_exercise ---
---------------------------------------------------
detail/libcxx/include/limits(351): error: floating constant is out of range

detail/libcxx/include/limits(403): error: floating constant is out of range

cub/util_cpp_dialect.cuh(143): warning #161-D: unrecognized #pragma

2 errors detected in the compilation of "cupy_jitify_exercise".

---------------------------------------------------
Fusing t=385 c=0
Applying affine transform ...
Traceback (most recent call last):
  File "/var/spool/slurm/job11927150/slurm_script", line 8, in <module>
    sys.exit(main())
  File "/home/jordao.bragantini/Softwares/imgproc-monorepo/slurmkit/slurmkit/funcall.py", line 92, in main
    func(*args, **kwargs)
  File "/home/jordao.bragantini/Softwares/imgproc-monorepo/impp/impp/fuse_daxi.py", line 295, in fuse
    no_bkg_reg_0 = ndi.gaussian_filter(no_bkg_reg_0, 4.0, mode="constant")
  File "/hpc/mydata/jordao.bragantini/anaconda/2022.05/x86_64/envs/imgproc/lib/python3.10/site-packages/cupyx/scipy/ndimage/_filters.py", line 373, in gaussian_filter
    return _run_1d_correlates(input, list(zip(sigmas, orders)), get, output,
  File "/hpc/mydata/jordao.bragantini/anaconda/2022.05/x86_64/envs/imgproc/lib/python3.10/site-packages/cupyx/scipy/ndimage/_filters.py", line 206, in _run_1d_correlates
    return _filters_core._run_1d_filters(
  File "/hpc/mydata/jordao.bragantini/anaconda/2022.05/x86_64/envs/imgproc/lib/python3.10/site-packages/cupyx/scipy/ndimage/_filters_core.py", line 102, in _run_1d_filters
    fltr(input, arg, axis, temp, mode, cval, origin)
  File "/hpc/mydata/jordao.bragantini/anaconda/2022.05/x86_64/envs/imgproc/lib/python3.10/site-packages/cupyx/scipy/ndimage/_filters.py", line 114, in correlate1d
    return _correlate_or_convolve(input, weights, output, mode, cval, origins)
  File "/hpc/mydata/jordao.bragantini/anaconda/2022.05/x86_64/envs/imgproc/lib/python3.10/site-packages/cupyx/scipy/ndimage/_filters.py", line 177, in _correlate_or_convolve
    output = _filters_core._call_kernel(kernel, input, weights, output,
  File "/hpc/mydata/jordao.bragantini/anaconda/2022.05/x86_64/envs/imgproc/lib/python3.10/site-packages/cupyx/scipy/ndimage/_filters_core.py", line 150, in _call_kernel
    kernel(*args)
  File "cupy/_core/_kernel.pyx", line 920, in cupy._core._kernel.ElementwiseKernel.__call__
  File "cupy/_core/_kernel.pyx", line 945, in cupy._core._kernel.ElementwiseKernel._get_elementwise_kernel
  File "cupy/_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "cupy/_core/_kernel.pyx", line 728, in cupy._core._kernel._get_elementwise_kernel
  File "cupy/_core/_kernel.pyx", line 82, in cupy._core._kernel._get_simple_elementwise_kernel_from_code
  File "cupy/_core/core.pyx", line 2254, in cupy._core.core.compile_with_cache
  File "/hpc/mydata/jordao.bragantini/anaconda/2022.05/x86_64/envs/imgproc/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 484, in _compile_module_with_cache
    return _compile_with_cache_cuda(
  File "/hpc/mydata/jordao.bragantini/anaconda/2022.05/x86_64/envs/imgproc/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 562, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "/hpc/mydata/jordao.bragantini/anaconda/2022.05/x86_64/envs/imgproc/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 319, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "/hpc/mydata/jordao.bragantini/anaconda/2022.05/x86_64/envs/imgproc/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 284, in _compile
    options, headers, include_names = _jitify_prep(
  File "/hpc/mydata/jordao.bragantini/anaconda/2022.05/x86_64/envs/imgproc/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 233, in _jitify_prep
    jitify._init_module()
  File "cupy/cuda/jitify.pyx", line 212, in cupy.cuda.jitify._init_module
  File "cupy/cuda/jitify.pyx", line 233, in cupy.cuda.jitify._init_module
  File "cupy/cuda/jitify.pyx", line 209, in cupy.cuda.jitify._init_cupy_headers
  File "cupy/cuda/jitify.pyx", line 192, in cupy.cuda.jitify._init_cupy_headers_from_scratch
  File "cupy/cuda/jitify.pyx", line 264, in cupy.cuda.jitify.jitify
RuntimeError: Runtime compilation failed
```

**Comment by leofang** [comment]
@JoOkuma Your error case seems different. Could you please kindly create a new issue, and provide the needed information  and a reproducer as prompted in the issue template? Let us focus on one thing at a time, and to do so we need enough information.

**Comment by Mirebeau** [comment]
@leofang 
Here is the info you required.
Thanks 

--- conda list ----

# packages in environment at C:\Users\jmmir\miniconda3\envs\agd-hfm_cuda_312:
#
# Name                    Version                   Build  Channel
anyio                     4.2.0              pyhd8ed1ab_0    conda-forge
aom                       3.7.1                h63175ca_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py312he70551f_4    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.1.0           py312h53d5487_1    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2023.11.17           h56e8100_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.18.0               h1fef639_0    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py312he70551f_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.1              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0           py312h0d7def4_0    conda-forge
cuda-version              11.8                 h70ddcb2_2    conda-forge
cudatoolkit               11.8.0              h09e9e62_12    conda-forge
cupy                      13.0.0          py312h7c28733_2    conda-forge
cupy-core                 13.0.0          py312hdf68b13_2    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dav1d                     1.2.1                hcfcfb64_0    conda-forge
debugpy                   1.8.0           py312h53d5487_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h63175ca_1    conda-forge
fastrlock                 0.8.2           py312h53d5487_2    conda-forge
ffmpeg                    6.1.1           gpl_hadb5375_102    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.47.2          py312he70551f_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.78.3               h12be248_0    conda-forge
glib-tools                2.78.3               h12be248_0    conda-forge
graphite2                 1.3.13                     1000    conda-forge
gst-plugins-base          1.22.9               h001b923_0    conda-forge
gstreamer                 1.22.9               hb4038d2_0    conda-forge
harfbuzz                  8.3.0                h7ab893a_0    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.0.1              pyha770c72_0    conda-forge
importlib_metadata        7.0.1                hd8ed1ab_0    conda-forge
importlib_resources       6.1.1              pyhd8ed1ab_0    conda-forge
intel-openmp              2024.0.0         h57928b3_49841    conda-forge
ipykernel                 6.29.0             pyha63f2e9_0    conda-forge
ipython                   8.20.0             pyh7428d3b_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.3              pyhd8ed1ab_0    conda-forge
json5                     0.9.14             pyhd8ed1ab_0    conda-forge
jsonpointer               2.4             py312h2e8e312_3    conda-forge
jsonschema                4.21.1             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.21.1             pyhd8ed1ab_0    conda-forge
jupyter-lsp               2.2.2              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.0              pyhd8ed1ab_0    conda-forge
jupyter_contrib_core      0.4.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.1           py312h2e8e312_0    conda-forge
jupyter_events            0.9.0              pyhd8ed1ab_0    conda-forge
jupyter_nbextensions_configurator 0.6.1              pyhd8ed1ab_0    conda-forge
jupyter_server            2.12.5             pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.5.2              pyhd8ed1ab_0    conda-forge
jupyterlab                4.0.11             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.25.2             pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.5           py312h0d7def4_1    conda-forge
krb5                      1.21.2               heb0366b_0    conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              21_win64_mkl    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0              21_win64_mkl    conda-forge
libclang                  15.0.7          default_hde6756a_4    conda-forge
libclang13                15.0.7          default_h85b4d89_4    conda-forge
libdeflate                1.19                 hcfcfb64_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.78.3               h16e383f_0    conda-forge
libhwloc                  2.9.3           default_haede6df_1009    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
liblapack                 3.9.0              21_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.44.2               hcfcfb64_0    conda-forge
libtiff                   4.6.0                h6e2ebb7_2    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.12.4               hc3477c8_1    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.4           py312he70551f_0    conda-forge
matplotlib                3.8.2           py312h2e8e312_0    conda-forge
matplotlib-base           3.8.2           py312h26ecaf7_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
mkl                       2024.0.0         h66d3029_49657    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.14.2             pyhd8ed1ab_0    conda-forge
nbformat                  5.9.2              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
notebook                  7.0.7              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
numpy                     1.26.3          py312h8753938_0    conda-forge
openh264                  2.4.0                h63175ca_0    conda-forge
openjpeg                  2.5.0                h3d672ee_3    conda-forge
openssl                   3.2.0                hcfcfb64_1    conda-forge
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.42                h17e33f8_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.2.0          py312he768995_0    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pixman                    0.43.2               h63175ca_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
plotly                    5.18.0             pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.19.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
psutil                    5.9.8           py312he70551f_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.9          py312he09f080_5    conda-forge
pyqt5-sip                 12.12.2         py312h53d5487_5    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.12.1          h2628c8c_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.19.1             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytz                      2023.4             pyhd8ed1ab_0    conda-forge
pywin32                   306             py312h53d5487_2    conda-forge
pywinpty                  2.0.12          py312h53d5487_0    conda-forge
pyyaml                    6.0.1           py312he70551f_1    conda-forge
pyzmq                     25.1.2          py312h1ac6f91_0    conda-forge
qt-main                   5.15.8              h9e85ed6_18    conda-forge
referencing               0.32.1             pyhd8ed1ab_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.17.1          py312hfccd98a_0    conda-forge
scipy                     1.12.0          py312h8753938_2    conda-forge
send2trash                1.8.2              pyh08f2357_0    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
sip                       6.7.12          py312h53d5487_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
svt-av1                   1.8.0                h63175ca_0    conda-forge
tbb                       2021.11.0            h91493d7_1    conda-forge
tenacity                  8.2.3              pyhd8ed1ab_0    conda-forge
terminado                 0.18.0             pyh5737063_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.3.3           py312he70551f_1    conda-forge
traitlets                 5.14.1             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.8.19.20240106    pyhd8ed1ab_0    conda-forge
typing-extensions         4.9.0                hd8ed1ab_0    conda-forge
typing_extensions         4.9.0              pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webcolors                 1.13               pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.7.0              pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
winpty                    0.4.3                         4    conda-forge
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.5                h63175ca_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge


-------- python -c "import cupy; cupy.show_config()" -------------

OS                           : Windows-11-10.0.22621-SP0
Python Version               : 3.12.1
CuPy Version                 : 13.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.3
SciPy Version                : 1.12.0
Cython Build Version         : 0.29.37
Cython Runtime Version       : None
CUDA Root                    : C:\Users\jmmir\miniconda3\envs\agd-hfm_cuda_312
nvcc PATH                    : None
CUDA Build Version           : 11080
CUDA Driver Version          : 12000
CUDA Runtime Version         : 11080 (linked to CuPy) / 11080 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 8)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Quadro RTX 4000 with Max-Q Design
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0

**Comment by leofang** [comment]
> So now we have two issues:
> 
> 1. With wheels (I confirmed on Linux too): Jitify version is unknown
> 2. With conda packages (on Linux): Jitify version is **not** unknown

Update: I just checked the Windows conda package and wheel. Below is an updated summary:
1. With wheels:
   a. On Linux: Jitify version is `<unknown>`
   b. On Windows: Jitify version is **not** `<unknown>`
2. With conda packages:
   a. On Linux: Jitify version is **not** `<unknown>`
   b. On Windows: Jitify version is `<unknown>`

@kmaehashi I am confused why the situation is flipped between wheel/conda and between Linux/Windows...

@Mirebeau Could you try this? Remove `cupy` from your conda environment (or just create a new env) and do `pip install cupy-cuda12x` instead, and see if you still get an error.

**Comment by leofang** [comment]
I can reproduce the error on Windows with the conda package, and switching to use the wheel makes the error go away. So the root cause is indeed https://github.com/cupy/cupy/issues/8147#issuecomment-1918371579 as @kmaehashi, though we do need to figure out why Jitify version is not consistent. I'll work on a fix. Thanks for reporting the issue @Mirebeau.
