### ISSUE TITLE
Find cuda dlls in Lib\site-packages\nvidia

### ISSUE THREAD

**Issue by martinResearch** [cupy/cupy#8164]
### Description

On windows It is possible to obtain all the cuda dll files required to run CuPy without using the standard installer but  be installing the following official Nvidia python packages
```
nvidia-nvjitlink-cu12
nvidia-nvtx-cu12
nvidia-cuda-runtime-cu12
nvidia-cublas-cu12
nvidia-cuda-cupti-cu12
nvidia-cuda-nvrtc-cu12
nvidia-cudnn-cu12
nvidia-cufft-cu12
nvidia-curand-cu12
nvidia-cusolver-cu12
nvidia-cusparse-cu12
```
once these packages installed, one can find the dll files in sub-folders in `Lib\site-packages\nvidia`, such as `3d_2\python_env\3.10\lib_runtime\` or `Lib\site-packages\nvidia\cudnn\bin`.
This is convenient because this allow the automatization of the cuda dll installation with the standard python pip approach instead of  having to create an account on the Nvidia website , download an installer and install it with admin credentials.
However CuPy is currently not able to find these dll files automatically and expect the dll files them to be either in a folder pointed by CUDA_PATH or in a folder listed in the PATH variable. It would be great if CuPy could automatically add the folders in  `Lib\site-packages\nvidia`  to the path during its import so that the dll files in these packages can be found.

**Comment by leofang** [comment]
I think this is a duplicate of #8013.

**Comment by martinResearch** [comment]
indeed looks like a duplicate
