### ISSUE TITLE
Jitify build version is wrong in CuPy v13

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#8185]
### Description

When debugging #8171 I noticed the reported Jitify build version makes no sense. It turns out that when executing this line
https://github.com/cupy/cupy/blob/34f8edb19ada737b3afefbc61043f6569f20c091/install/cupy_builder/install_build.py#L584
in a symlink (since https://github.com/cupy/cupy/pull/7956 moved all 3rd party headers to a separate folder and symlink back), what we get is CuPy's commit hash, not Jitify's. I'll fix it.

### Installation

None

**Comment by kmaehashi** [comment]
Ah, that was my oversight... Thanks for the investigation!
