### ISSUE TITLE
bug in distributed/_store.py

### ISSUE THREAD

**Issue by 315930399** [cupy/cupy#8204]
### Description

![wx_camera_1708590916336](https://github.com/cupy/cupy/assets/38678334/fb767aee-8926-426e-a7f5-864330bdaf20)

### Installation

None

### Environment

![IMG_20240222_164103](https://github.com/cupy/cupy/assets/38678334/eb93034f-f739-41f0-80c1-8798a264d25f)

**Comment by leofang** [comment]
Could you please fill in all information asked by the issue template via copy/paste, so that the team can advice or investigate?
