### ISSUE TITLE
Pre-populate and ship a Jitify cache?

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#8209]
Heard some people complaining about the one-time only cost 
https://docs.cupy.dev/en/stable/upgrade.html#modernized-cccl-support-and-requirement
which appears as if it hangs. 

As a stop-gap solution, we should print a warning "jitify cache building, it may take a while..." 

Short-term, I am thinking to extend [@kmaehashi's idea](https://github.com/cupy/cupy/pull/7934#issuecomment-1763772965) that we implemented
> generate a hash string of all `cupy/_core/include/**` files at the build time and set it as a key

and build the json-based Jitify cache at build time, and ship it as part of the wheel and conda package. 

Long term, I am afraid Jitify's default compile-fail-search loop is too expansive and we might have to either implement it ourselves or use the WIP (https://github.com/NVIDIA/jitify/pull/131).

**Comment by kmaehashi** [comment]
IIRC the problem with pre-generated cache is that some headers depend on files under `/usr/local/cuda/include` which is user environment dependent. 😢

**Comment by leofang** [comment]
I am thinking about this too. I think the bigger problem is that the cache keys can contain includes with relative paths (or truncated paths in the bracket form `<...>` that requires the compiler to search, which makes it very hard to identify the source of the headers. If we normalize all keys to absolute path, maybe it'd make things easier/safer? However, we'll pay a price during cache lookup (de-normalizing an absolute path to relative/truncated path).

**Comment by kmaehashi** [comment]
> If we normalize all keys to absolute path, maybe it'd make things easier/safer?

I think there's no formal way to do that... If `A/B/C.h` has a `#include <D.h>` line, we only get `D.h` as a key, so we don't have knowledge of which file tried to include `D.h` nor which directory `D.h` is in.

**Comment by leofang** [comment]
Right, so when I noted
>  we might have to either implement it ourselves or use the WIP ([NVIDIA/jitify#131](https://github.com/NVIDIA/jitify/pull/131)).

I meant we'll no longer rely on NVRTC to find headers, but instead roll out a search logic that mimics the compiler behavior. This is the only way we can gain knowledge about header location. I think NVIDIA/jitify#131 did quite a bit of the work, I just don't know if in the long term we'd still want to use Jitify, or just vender that search loop implementation in CuPy and move on.

**Comment by ryanshrott** [comment]
Mine has been suck here for 5 hours. How to fix this? @leofang 
(rapids_new) (base) azureuser@ryanshrott1:~/cloudfiles/code/propertyca_space$ python
Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask_cudf
>>> import cudf
>>> import cupy as cp
>>> s = cudf.Series([1, 2, 3, None, 4])
>>> s = cudf.Series([1, 2, 3, None, 4])
>>> ds = dask_cudf.from_cudf(s, npartitions=2)
/anaconda/envs/rapids_new/lib/python3.11/site-packages/cupy/cuda/compiler.py:233: PerformanceWarning: Jitify is performing a one-time only warm-up to populate the persistent cache, this may take a few seconds and will be improved in a future release...
  jitify._init_module()

**Comment by leofang** [comment]
@ryanshrott could you file a new issue with requested information provided (see the issue template)? This warm-up should not exceed ~1 min.

**Comment by leofang** [comment]
New thought, recorded here in case I forget. I am getting more and more concerned with the performance of building a cache...

We needed Jitify back then because lots of Thrust/CUB headers could not be compiled using NVRTC (#3408, #4228). While today most of Thrust still cannot be compiled using NVRTC (not even with Jitify turned on): https://github.com/cupy/cupy/blob/c39c2d40ce7ca61040a8243f37b61af2966fd905/cupyx/jit/thrust.py#L14
CUB can be! Given that we figure out how to [redirect `std` libraries to use libcudacxx](https://github.com/cupy/cupy/blob/main/cupy/_core/include/cupy/cuda_workaround.h), perhaps the way to go should be:
- Unconditionally include `cupy/cuda_workaround.h` whenever CUB code is compiled
- Avoid calling `jitify._init_module()` in CuPy routines
- Only allow `jitify=True` in user code based on `RawKernel`/`RawModule`

This way we could perhaps sort of restore the pre-v13 performance without breaking changes in the user land that we can't test. `_init_module()` is deferred indefinitely (to the first invocation of `RawKernel`/`RawModule`).

**Comment by leofang** [comment]
> 1. There are a few places where the similar treatment can be done to avoid using Jitify

Done in https://github.com/cupy/cupy/pull/8467. I am thinking this issue can be closed, now that the chance of firing Jitify is significantly reduced. Thoughts, @kmaehashi?

**Comment by kmaehashi** [comment]
Yeah, sounds good to close this one!

**Comment by SnzFor16Min** [comment]
FYI, I was stuck at `conda-forge`'s CuPy **forever** like @ryanshrott :

```shell
/root/micromamba/envs/py311/lib/python3.11/site-packages/cupy/cuda/compiler.py:233: PerformanceWarning: Jitify is performing a one-time only warm-up to populate the persistent cache, this may take a few seconds and will be improved in a future release...
  jitify._init_module()
```

Uninstall them with `micromamba remove cupy`:

```shell
  Prefix: /root/micromamba/envs/py311

  Removing specs:

   - cupy


  Package      Version  Build            Channel          Size
────────────────────────────────────────────────────────────────
  Remove:
────────────────────────────────────────────────────────────────

  - cupy        13.2.0  py311he5a987b_1  conda-forge     357kB
  - cupy-core   13.2.0  py311h3bdf873_1  conda-forge      42MB
  - fastrlock    0.8.2  py311hb755f60_2  conda-forge      38kB

  Summary:

  Remove: 3 packages
```

... and install the `pip` version instead with `pip install cupy-cuda12x`:

```shell
Successfully installed cupy-cuda12x-13.3.0 fastrlock-0.8.2
```

Immediately worked.

**Comment by leofang** [comment]
@SnzFor16Min it's not about conda-forge. It's v13.3.0 skipping building the Jitify cache in most cases. If you can help confirm, please check with `pip install "cupy-cuda12x==13.2.0"` and see if it is stuck too. If it does, please let's follow up in the issue that @ryanshrott opened: https://github.com/cupy/cupy/issues/8322 and share your environment config with us (since the Jitify cache is not gone, just less likely that it's needed) to help us diagnose.

**Comment by leofang** [comment]
> Just to clarify is the pip install meant to be 13.3.0 too?

When @SnzFor16Min installed from pip v13.3.0 was installed and it worked (no surprise). I was asking to install v13.2.0 from pip, in which case it should fail and this failure would be independent of the package source (conda/pip) but depend on something else that the discussion we had in #8322 might help.

**Comment by SnzFor16Min** [comment]
Thanks @leofang for pointing that out. I created a fresh-new environment and checked v13.2.0 from both; surprisingly they all worked it out, albeit slower than the claimed "_a few seconds_". Seems that I have to check my dev env. Also, `conda-forge` always ran slower than `pip`. For later debugging I'll leave the commands here:

```bash
# Environment for pip:
micromamba create -n test_pip python=3.11 -c "https://conda.anaconda.org/conda-forge" --override-channels
micromamba activate test_pip
pip install "cupy-cuda12x==13.2.0" -i "https://pypi.org/simple/"
rm -rf ~/.cupy/ && time python -c "import cupy; cupy.sparse.rand(200,200).tocsr()"
```

> ```python
> /root/micromamba/envs/test_pip/lib/python3.11/site-packages/cupy/cuda/compiler.py:233: PerformanceWarning: Jitify is performing a one-time only warm-up to populate the persistent cache, this may take a few seconds and will be improved in a future release...
>   jitify._init_module()
> 
> real    1m25.747s
> user    0m52.264s
> sys     0m8.065s
> ```

```bash
# Environment for conda-forge:
micromamba create -n test_conda python=3.11 cuda-version=12.1 cupy=13.2.0 -c "https://conda.anaconda.org/conda-forge" --override-channels
micromamba activate test_conda
rm -rf ~/.cupy/ && time python -c "import cupy; cupy.sparse.rand(200,200).tocsr()"
```

> ```python
> /root/micromamba/envs/test_conda/lib/python3.11/site-packages/cupy/cuda/compiler.py:233: PerformanceWarning: Jitify is performing a one-time only warm-up to populate the persistent cache, this may take a few seconds and will be improved in a future release...
>   jitify._init_module()
> 
> real    1m50.185s
> user    1m14.954s
> sys     0m8.270s
> ```
