### ISSUE TITLE
Cannot use cooperative_groups in RawKernels

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [cupy/cupy#8257]
### Description

I cannot use cooperative_groups with `RawKernels`. Here is a reproduction script

```python
add_kernel = cp.RawKernel(r'''
#include <cooperative_groups.h>

extern "C" __global__
void my_add(const float* x1, const float* x2, float* y) {
    int tid = blockDim.x * blockIdx.x + threadIdx.x;
    y[tid] = x1[tid] + x2[tid];
}

''', 'my_add')

x1 = cp.arange(25, dtype=cp.float32).reshape(5, 5)
x2 = cp.arange(25, dtype=cp.float32).reshape(5, 5)
y = cp.zeros((5, 5), dtype=cp.float32)
add_kernel((5,), (5,), (x1, x2, y))  # grid, block and arguments
```

Yields
```
CompileException: /tmp/tmpvcxs1_g6/b541e5949235b825327e7e07cd2c7ffb0bdedd87.cubin.cu(2): catastrophic error: cannot open source file "cooperative_groups.h"

1 catastrophic error detected in the compilation of "/tmp/tmpvcxs1_g6/b541e5949235b825327e7e07cd2c7ffb0bdedd87.cubin.cu".
Compilation terminated.
```

The weird thing is that other includes work fine like `cuda_fp16.h`, includes, compiles and executes correctly.

### Installation details

I'm running cupy on a fresh install from conda (less than a week), version is `11.6.0`. GPU is GTX 2070 running cuda `12.2`.

```
OS                           : Linux-5.19.0-76051900-generic-x86_64-with-glibc2.35
Python Version               : 3.10.9
CuPy Version                 : 11.6.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.23.5
SciPy Version                : 1.10.1
Cython Build Version         : 0.29.33
Cython Runtime Version       : None
CUDA Root                    : /home/guillaumeleclerc/miniconda3/envs/ffcv_new
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 12020
CUDA Runtime Version         : 11080
cuBLAS Version               : (available)
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 8)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : f670b37
cuDNN Build Version          : 8401
cuDNN Version                : 8902
NCCL Build Version           : 21403
NCCL Runtime Version         : 21801
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 2070 with Max-Q Design
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0
```

Thanks for the help!

**Comment by kmaehashi** [comment]
`#include <cooperative_groups.h>` should work, could you share the reproducer code and error messages you get?

**Comment by leofang** [comment]
Yes please fill in the information that the issue template asks for. We can't help you without enough information.

**Comment by GuillaumeLeclerc** [comment]
I apologize, I assumed it wasn't supported out of the box and didn't think it was as a bug and therefore didn't do a proper bug report. I will update the original post now

**Comment by leofang** [comment]
Thanks. This helps. The compiler error says the header is not found, which is expected if you install via pip/conda and have no local CUDA Toolkit installed. Lots of CUDA headers are not redistributable, so CuPy only bundles the minimal ones that allow the core functionalities and are permitted by the CUDA EULA.

If you installed CuPy from conda-forge, and are using CUDA 12, as a workaround I'd suggest you to also install the `cuda-cudart-dev` package, and pass the header location
```python
cp.RawKernel(..., options=(f"-I{os.environ['CONDA_PREFIX']}/targets/linux-x86_64/include",))
```
to `RawKernel` option. The CUDA packages on conda-forge are officially supported by NVIDIA.

However, given what you said
> I'm running cupy on a fresh install from conda (less than a week), version is `11.6.0`. GPU is GTX 2070 running cuda `12.2`.
> 
> ```
> ...
> CuPy Version                 : 11.6.0
> ...
> CUDA Build Version           : 11020
> CUDA Driver Version          : 12020
> CUDA Runtime Version         : 11080
> ...
> ```

I am not sure how you installed CuPy? This version seems quite outdated, and you're certainly not using the CUDA 12 build. Maybe you should update your `conda`, create a new conda environment, and install `cupy` there?

**Comment by GuillaumeLeclerc** [comment]
Thank you so much! It worked.
