### ISSUE TITLE
`cupy.cuda.compile_with_cache` vs `cupy.RawModule`

### ISSUE THREAD

**Issue by OverLordGoldDragon** [cupy/cupy#8261]
The [migration guide](https://docs.cupy.dev/en/stable/upgrade.html#id9) suggests `RawModule` as an alternative, but, as someone who just copied code on the internet and only concerned myself with the actual kernel code, it'd help me to know whether it's a drop-in replacement, or if there are differences I should be aware of and account for (e.g. via arguments to `RawModule`). Namely, for something like

```python
@cp._util.memoize(for_each_device=True)
def load_kernel(kernel_name, code, **kwargs):
    code = string.Template(code).substitute(**kwargs)
    kernel_code = cp.cuda.compile_with_cache(code=code)
    return kernel_code.get_function(kernel_name)
```

A note in docs works, but it being searchable (e.g. like in this Issue) would suffice for me.

**Comment by leofang** [comment]
Try this?
```python
@cp._util.memoize(for_each_device=True)
def load_kernel(kernel_name, code, **kwargs):
    code = string.Template(code).substitute(**kwargs)
    mod = cp.RawModule(code=code)
    return mod.get_function(kernel_name)
```
btw `cupy._util` is a private module and everything in it is private function.

**Comment by OverLordGoldDragon** [comment]
Yes, my question is whether there's caveats to that, e.g. differences in caching behavior.

**Comment by leofang** [comment]
No, the compiled code is still cached. I see why you're asking... Contribution to the `RawModule` docs is welcomed :D

**Comment by OverLordGoldDragon** [comment]
Thanks, so, there's no need to set some arguments, e.g. `options`, to match behavior?

**Comment by kmaehashi** [comment]
Yes, options passed to the compiler are the same between `compile_with_cache` (which no longer exists) and `RawModule` / `RawKernel`, with slight differences (the latter adds `--std=c++11` and extra include directories (`-I`) to let the code discover headers).

**Comment by OverLordGoldDragon** [comment]
Thanks! Feel free to close.
