### ISSUE TITLE
User-defined kernels for random sampling

### ISSUE THREAD

**Issue by yoshipon** [cupy/cupy#829]
Thank you so much for organizing `cupy`, which is a very practical library for GPGPU.
This is my future request.

Like current user-defined kernels, could you implement a framework for writing user-defined kernels that can sample random values?

I'm using `cupy` for implementing an MCMC algorithm.
However, current `cupy` has a small support for random sampling and there are a lot of distributions used in MCMC sampling.
(such as gamma, exponential, and generalized inv. Gaussian in my field)

Currently, I deal with this problem by writing custom CUDA kernels with C++ and `pybind11`.
(Thank you for providing a way to access the raw pointer of arrays)
If you can provide an easy way to make such a kernel in a Python script,
the usability of `cupy` for MCMC will be improved and many researchers of Bayesian deep learning will get its benefit.

I don't have any idea how to implement such a framework.
But I would like to suggest this improvement to make `cupy` more useful for Bayesian researchers.

Sincerely,
Yoshiaki Bando

**Comment by kmaehashi** [comment]
`RawKernel` implemented in #1398 can be used to define fully custom CUDA kernel in Python.
https://docs-cupy.chainer.org/en/latest/tutorial/kernel.html#raw-kernels
