### ISSUE TITLE
RFC: Seeking feedback on adding new special functions from SciPy

### ISSUE THREAD

**Issue by steppi** [cupy/cupy#8303]
Hi CuPy devs!

You may have seen that in `scipy.special` we're working on translating the scalar kernels for special functions into C++ which can run on both CPU and on GPUs with CUDA. The hope is that this could be a common code base for SciPy and CuPy allowing us to add functions from SciPy which are currently missing in CuPy, and have a common place to make bug fixes and improvements. So far https://github.com/cupy/cupy/pull/8140, and https://github.com/cupy/cupy/pull/8163 have landed in CuPy for Lambert's W function, and Digamma of a complex argument respectively.

There's been a tremendous burst of activity in `special` lately, and within the next week we should have dozens of new functions ready to PR to CuPy. My questions are:

1. Would you be happy to add any special function currently available in SciPy's public API, or would you prefer to select only from a subset of the more important ones?
2. At what rate would you like to see new functions added? Would a single PR adding everything currently translated be OK, should we stick to one function per time, or something in-between like PRs for clusters of related functions?
3. Do you have an approximate timeline for the 14.0 release date, so we can have a sense of the pace we should work at to get as many wanted things in as possible before then?
4. Would you be supportive of replacing existing special function implementations from CuPy with the ones we are now writing for SciPy to make it easier to benefit from improvements and fixes made in SciPy?
5. Do you have any thoughts on the idea of separating out the scalar kernels we are working on in SciPy into a separate library which is included as a submodule of both SciPy and CuPy? For the time-being we plan to carry on by just copying code from SciPy into CuPy, but we are hoping to make this a separate special functions library in the future.

Thank you. I look forward to hearing your thoughts.

cc @izaid @rgommers

**Comment by takagi** [comment]
Thanks for raising this issue before you make PRs to include the new special functions into CuPy.

1. We'd like to have any special function available in SciPy's public API
2. We prefer smaller PRs to make them smoothly reviewed and merged. One or a few functions per time would be nice.
3. We have not set the timing of the 14.0 release yet, but I suppose it will be scheduled roughly between six months and a year later from now.
4. Yes.
5. I agree that having a common submodule in the future would be beneficial.

@kmaehashi, do you have any clarifications or corrections? Also thoughts regarding 5.?

**Comment by kmaehashi** [comment]
Hi @steppi, thank you for raising the discussion! Having and managing almost the same code in both SciPy and CuPy is redundant, so the common library is definitely the best solution.

Regarding replacing existing functions, some functions are currently implemented using ufunc in CuPy, e.g.:
https://github.com/cupy/cupy/blob/027d11cef08efb7e2fe50d3db6591aee5ce021ad/cupyx/scipy/special/_basic.py#L146-L154

Ufunc implementations are not only simpler and easily maintainable than  C++/RawKernels, but also allow enjoying other CuPy features such as [automatic kernel parameter tuning](https://docs.cupy.dev/en/stable/reference/generated/cupyx.optimizing.optimize.html). Of course, when there is an additional benefit to switching to the raw CUDA implementation (for example, adding support for optional arguments that are not currently supported), we are happy to move on.

As for the v14 release, one of our main focus is making APIs compatible with NumPy 2.0. Currently, we are assessing the tasks to be done, so a specific date has yet to be set.

**Comment by izaid** [comment]
> Hi @steppi, thank you for raising the discussion! Having and managing almost the same code in both SciPy and CuPy is redundant, so the common library is definitely the best solution.
> 
> Regarding replacing existing functions, some functions are currently implemented using ufunc in CuPy, e.g.:
> 
> https://github.com/cupy/cupy/blob/027d11cef08efb7e2fe50d3db6591aee5ce021ad/cupyx/scipy/special/_basic.py#L146-L154
> 
> Ufunc implementations are not only simpler and easily maintainable than C++/RawKernels, but also allow enjoying other CuPy features such as [automatic kernel parameter tuning](https://docs.cupy.dev/en/stable/reference/generated/cupyx.optimizing.optimize.html). Of course, when there is an additional benefit to switching to the raw CUDA implementation (for example, adding support for optional arguments that are not currently supported), we are happy to move on.
> 
> As for the v14 release, one of our main focus is making APIs compatible with NumPy 2.0. Currently, we are assessing the tasks to be done, so a specific date has yet to be set.

Indeed! Regarding ufuncs, this has been our entire goal. Have C++ do only the kernel part of the ufunc, and use the relevant array libraries ufunc mechanism (in CuPy's case, `cp.ElementwiseKernel`) to handle all the broadcasting. We have gotten to a point where essentially all of SciPy special is (or will become) either a ufunc or, in some more complex cases, a generalised ufunc. A good example of the latter are the associated Legendre polynomials, `sp.special.lpmn`. In SciPy main, these are now a gufunc and thus can handle arbitrary-shaped `z`. This should also work as part of `cp.ElementwiseKernel`, but with a bit more pointer and strides manipulation.

**Comment by steppi** [comment]
Thanks for the replies @kmaehashi and @takagi! That's great to hear that you want everything from the public API. I'll try to keep up a steady stream of small PRs for 1-2 functions at a time. I think I'll start with `hyp2f1` since there was an issue about that recently. Like my collaborator @izaid (who came up with this plan) said, we're implementing scalar kernels and creating ufuncs just as in the example with `cosm1` above.
