### ISSUE TITLE
The version number on main seems to be out of date

### ISSUE THREAD

**Issue by steppi** [cupy/cupy#8340]
It looks like on `main` the version number is still `13.0.0rc1`.

https://github.com/cupy/cupy/blob/22694a14896b691c6150c08d0d3f6c6f8c7c4039/cupy/_version.py#L1

In https://github.com/scipy/scipy/pull/20701, I've added tests to SciPy which check that our special function implementations will compile in CuPy. Since SciPy's test suite is typically run in environments where CuPy is not present, we use a function `check_version` to only run these particular tests when CuPy is installed. I set the minimum version to `13.0.0` and was surprised to see that the tests weren't picked up when I had the development version of CuPy installed, even though the latest release was `13.1.0`.

**Comment by kmaehashi** [comment]
Hi @steppi, we usually bump `_version.py` just before the release so it remained v13.0.0rc1 (which is the version at the time of the v13/main branch cut happened). I've bumped the version in main branch to 14.0.0a0 in #8341 so it should fix the problem.

**Comment by steppi** [comment]
Thanks @kmaehashi. I'll go ahead and close this.
