### ISSUE TITLE
need window support for cupy plz

### ISSUE THREAD

**Issue by xalteropsx** [cupy/cupy#8374]
### Description

help

**Comment by leofang** [comment]
Hi @xalteropsx could you be more specific? What "window support" are you referring to?

**Comment by kmaehashi** [comment]
Let me clarify - Do you need support for [AMD ROCm/HIP on Microsoft Windows](https://rocm.docs.amd.com/projects/install-on-windows/en/latest/how-to/install.html) in CuPy? I'd love to hear the use-case if you don't mind sharing.
