### ISSUE TITLE
Operations on `float32`s underflow when result would be subnormal

### ISSUE THREAD

**Issue by mdhaber** [cupy/cupy#8382]
### Description

Arithmetic operations on `float64` arrays that would result in subnormals work as expected.
Arithmetic operations on `float32` arrays that would result in subnormals underflow.

### To Reproduce

```python3
import cupy as cp

tiny64 = cp.asarray(cp.finfo(cp.float64).smallest_normal)  # array(2.22507386e-308)
tiny64/2  # array(1.11253693e-308)

tiniest64 = cp.asarray(cp.finfo(cp.float64).smallest_subnormal)  # array(5.e-324)
2*tiniest64  # array(1.e-323)

tiny32 = cp.asarray(cp.finfo(cp.float32).smallest_normal)  # array(1.1754944e-38, dtype=float32)
tiny32/2  # array(0., dtype=float32)

tiniest32 = cp.asarray(cp.finfo(cp.float32).smallest_subnormal)  # array(1.e-45, dtype=float32)
2*tiniest32  # array(0., dtype=float32)
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
(scipy-dev) C:\Users\matth\scipy>python -c "import cupy; cupy.show_config()"
OS                           : Windows-11-10.0.22631-SP0
Python Version               : 3.12.3
CuPy Version                 : 13.1.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.4
SciPy Version                : 1.15.0.dev0+902.00318df
Cython Build Version         : 0.29.37
Cython Runtime Version       : 3.0.10
CUDA Root                    : None
nvcc PATH                    : None
CUDA Build Version           : 12040
CUDA Driver Version          : 12040
CUDA Runtime Version         : 12040 (linked to CuPy) / RuntimeError("CuPy failed to load cudart64_12.dll: FileNotFoundError: Could not find module 'cudart64_12.dll' (or one of its dependencies). Try using the full path with constructor syntax.") (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 11203
cuRAND Version               : 10306
cuSOLVER Version             : (11, 6, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 5)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 2060 SUPER
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0
```

### Additional Information

I see `RuntimeError("CuPy failed to load cudart64_12.dll: FileNotFoundError: Could not find module 'cudart64_12.dll' (or one of its dependencies). Try using the full path with constructor syntax.")` above. I haven't seen it when trying to use CuPy, but please let me know if that is something I can/should fix.

**Comment by kmaehashi** [comment]
Hi @mdhaber, thanks for the feedback! For performance, CuPy uses [the CUDA option that flushes denormals to zero](https://docs.nvidia.com/cuda/floating-point/#compiler-flags). This is currently a hard-coded flag, but would love to hear your usecase if this is not convenient.

> I see `RuntimeError("CuPy failed to load cudart64_12.dll: FileNotFoundError: Could not find module 'cudart64_12.dll' (or one of its dependencies). Try using the full path with constructor syntax.")` above. I haven't seen it when trying to use CuPy, but please let me know if that is something I can/should fix.

`cudart64_12.dll` is used only for probing the CUDA runtime version installed locally, so you don't have to care much about this - it won't affect CuPy's functionality. Not sure why it can't be found although other libraries (such as cuFFT, NVRTC, etc.) are correctly loaded, though...

**Comment by mdhaber** [comment]
> This is currently a hard-coded flag, but would love to hear your usecase if this is not convenient.

It came up while testing a SciPy function (that has been translated from NumPy to array API) on various backends. I don't have a particular use case, and now I see that the array API standard doesn't specify behavior for subnormals, so I suppose this can be closed. Thanks!
