### ISSUE TITLE
is that normal when cupy.array raises TypeError for this?

### ISSUE THREAD

**Issue by zhangvia** [cupy/cupy#8389]
### Description

i create the cp.ndarray like this:
```python
cp.array([[0,1,cp.cos(0)]])
```
and it raise error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Python-3.8.6/lib/python3.8/site-packages/cupy/_creation/from_data.py", line 46, in array
    return _core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/_core/core.pyx", line 2376, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2400, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2524, in cupy._core.core._array_default
  File "cupy/_core/core.pyx", line 1475, in cupy._core.core._ndarray_base.__array__
TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly.

```
i think the cp.cos(0) return cupy.ndarray. 

### To Reproduce

```py
# Write the code here
```

### Installation

Source (`pip install cupy`)

### Environment

```
# Paste the output here
```
OS                           : Linux-5.15.0-105-generic-x86_64-with-glibc2.27
Python Version               : 3.8.6
CuPy Version                 : 12.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.23.5
SciPy Version                : 1.9.1
Cython Build Version         : 0.29.37
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11070
CUDA Driver Version          : 12000
CUDA Runtime Version         : 11070
cuBLAS Version               : (available)
cuFFT Version                : 10702
cuRAND Version               : 10210
cuSOLVER Version             : (11, 3, 5)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 7)
Thrust Version               : 101500
CUB Build Version            : 101500
Jitify Build Version         : <unknown>
cuDNN Build Version          : 8700
cuDNN Version                : 8700
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 4090
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:4F:00.0
Device 1 Name                : NVIDIA GeForce RTX 4090
Device 1 Compute Capability  : 89
Device 1 PCI Bus ID          : 0000:52:00.0
Device 2 Name                : NVIDIA GeForce RTX 4090
Device 2 Compute Capability  : 89
Device 2 PCI Bus ID          : 0000:56:00.0
Device 3 Name                : NVIDIA GeForce RTX 4090
Device 3 Compute Capability  : 89
Device 3 PCI Bus ID          : 0000:57:00.0
Device 4 Name                : NVIDIA GeForce RTX 4090
Device 4 Compute Capability  : 89
Device 4 PCI Bus ID          : 0000:CE:00.0
Device 5 Name                : NVIDIA GeForce RTX 4090
Device 5 Compute Capability  : 89
Device 5 PCI Bus ID          : 0000:D1:00.0
Device 6 Name                : NVIDIA GeForce RTX 4090
Device 6 Compute Capability  : 89
Device 6 PCI Bus ID          : 0000:D5:00.0
Device 7 Name                : NVIDIA GeForce RTX 4090
Device 7 Compute Capability  : 89
Device 7 PCI Bus ID          : 0000:D6:00.0

**Comment by takagi** [comment]
Yes, it is expected behavior. When a CuPy ndarray is created from a list, its data is all assumed to sit on the host memory, and we do not cover the mixed case as you show by design. Alternatively, please create the input with NumPy, or create a CuPy ndarray first then assign the value on the device memory to it.
