### ISSUE TITLE
Circular import error - rocm-ci-6.1

### ISSUE THREAD

**Issue by eliranwong** [cupy/cupy#8396]
### Description

I install cupy from source with branch ` rocm-ci-6.1`, encountered circular import when I `import cupy`:

```
Traceback (most recent call last):
  File "/home/ubuntu/eliran/ai/cupy/cupy/__init__.py", line 16, in <module>
    from cupy import _core  # NOQA
  File "/home/ubuntu/eliran/ai/cupy/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
ImportError: cannot import name 'core' from partially initialized module 'cupy._core' (most likely due to a circular import) (/home/ubuntu/eliran/ai/cupy/cupy/_core/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/eliran/ai/cupy/cupy/__init__.py", line 18, in <module>
    raise ImportError(f'''
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: cannot import name 'core' from partially initialized module 'cupy._core' (most likely due to a circular import) (/home/ubuntu/eliran/ai/cupy/cupy/_core/__init__.py)
================================================================
```

### To Reproduce

```
git clone https://github.com/cupy/cupy.git
cd cupy
git checkout rocm-ci-6.1
git submodule update --init
pip install git+https://github.com/ROCmSoftwarePlatform/hipify_torch.git
pip install .
python3 -c "import cupy"
```

### Installation

Built from GitHub source

### Environment

Unable to import cupy due to circular import error

### Additional Information

I run ROCm 6.1.3 with dual AMD RX 7900 XTX, setup notes at:

https://github.com/eliranwong/MultiAMDGPU_AIDev_Ubuntu

**Comment by healy-hub** [comment]
I solved this issue by replacing the libstdc++.so.6 library.

1.Backed up libstdc++.so.6 in the Anaconda environment.
cp /home/'XXX'/anaconda3/envs/'XXX'/lib/libstdc++.so.6 /home/'XXX'/anaconda3/envs/'XXX'/lib/libstdc++.so.6.back
2.Copied the libstdc++.so.6 from the AMD GPU library to the Anaconda environment.
cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /home/'XXX'/anaconda3/envs/'XXX'/lib/libstdc++.so.6

Then it's OK.

**Comment by healy-hub** [comment]
> I solved this issue by replacing the libstdc++.so.6 library.
> 
> 1.Backed up libstdc++.so.6 in the Anaconda environment.
> cp /home/'XXX'/anaconda3/envs/'XXX'/lib/libstdc++.so.6 /home/'XXX'/anaconda3/envs/'XXX'/lib/libstdc++.so.6.back
> 2.Copied the libstdc++.so.6 from the AMD GPU library to the Anaconda environment.
> cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /home/'XXX'/anaconda3/envs/'XXX'/lib/libstdc++.so.6
> 
> Then it's OK.
> 
> 

and perhaps   export ROCM_HOME=/opt/rocm

**Comment by eliranwong** [comment]
> Anaconda environment

I am not using Anaconda environment.

**Comment by eliranwong** [comment]
> ROCM_HOME=/opt/rocm
> Also 7900xtx with ROCm 6.1.3

I already

exported ROCM_HOME=/opt/rocm

I also use 7900xtx with ROCm 6.1.3

**Comment by healy-hub** [comment]
> > ROCM_HOME=/opt/rocm
> > Also 7900xtx with ROCm 6.1.3
> 
> I already
> 
> exported ROCM_HOME=/opt/rocm
> 
> I also use 7900xtx with ROCm 6.1.3

I suspect that the issue might be due to a mismatch between the ROCm libstdc++.so.6 library and your Python environment. You can try replacing it to see if that resolves the problem. I encountered the same error initially in my Anaconda environment. Locate the libstdc++.so.6 library in your system may help you. Wish you good luck,

**Comment by eliranwong** [comment]
Issue solved, my bad.  I forget to install `pytorch` in the same environment, so  `import cupy` results in error.

This solution work with ROCM 6.1.3:

1. Setup venv:

```
python3 -m venv testcupy
source testcupy/bin/activate
pip install --upgrade pip wheel setuptools
```

2. Install pytorch+rocm6.1.3:

```
wget https://repo.radeon.com/rocm/manylinux/rocm-rel-6.1.3/torch-2.1.2%2Brocm6.1.3-cp310-cp310-linux_x86_64.whl
wget https://repo.radeon.com/rocm/manylinux/rocm-rel-6.1.3/torchvision-0.16.1%2Brocm6.1.3-cp310-cp310-linux_x86_64.whl
wget https://repo.radeon.com/rocm/manylinux/rocm-rel-6.1.3/pytorch_triton_rocm-2.1.0%2Brocm6.1.3.4d510c3a44-cp310-cp310-linux_x86_64.whl
pip3 install torch-2.1.2+rocm6.1.3-cp310-cp310-linux_x86_64.whl torchvision-0.16.1+rocm6.1.3-cp310-cp310-linux_x86_64.whl pytorch_triton_rocm-2.1.0+rocm6.1.3.4d510c3a44-cp310-cp310-linux_x86_64.whl
```

3. Install cupy from source:

```
export CUPY_INSTALL_USE_HIP=1
export ROCM_HOME=/opt/rocm
export HCC_AMDGPU_TARGET=gfx1100

git clone https://github.com/cupy/cupy.git
cd cupy
git checkout rocm-ci-6.1
git submodule update --init
pip install git+https://github.com/ROCmSoftwarePlatform/hipify_torch.git
pip install .
```

4. Verify:

```
python3 -c "import cupy; print(cupy.__version__)"
```

Output:

```
14.0.0a0
```

**Comment by healy-hub** [comment]
> Issue solved, my bad.  I forget to install `pytorch` in the same environment, so  `import cupy` results in error.
> 
> This solution work with ROCM 6.1.3:
> 
> 1. Setup venv:
> 
> ```
> python3 -m venv testcupy
> source testcupy/bin/activate
> pip install --upgrade pip wheel setuptools
> ```
> 
> 2. Install pytorch+rocm6.1.3:
> 
> ```
> wget https://repo.radeon.com/rocm/manylinux/rocm-rel-6.1.3/torch-2.1.2%2Brocm6.1.3-cp310-cp310-linux_x86_64.whl
> wget https://repo.radeon.com/rocm/manylinux/rocm-rel-6.1.3/torchvision-0.16.1%2Brocm6.1.3-cp310-cp310-linux_x86_64.whl
> wget https://repo.radeon.com/rocm/manylinux/rocm-rel-6.1.3/pytorch_triton_rocm-2.1.0%2Brocm6.1.3.4d510c3a44-cp310-cp310-linux_x86_64.whl
> pip3 install torch-2.1.2+rocm6.1.3-cp310-cp310-linux_x86_64.whl torchvision-0.16.1+rocm6.1.3-cp310-cp310-linux_x86_64.whl pytorch_triton_rocm-2.1.0+rocm6.1.3.4d510c3a44-cp310-cp310-linux_x86_64.whl
> ```
> 
> 3. Install cupy from source:
> 
> ```
> export CUPY_INSTALL_USE_HIP=1
> export ROCM_HOME=/opt/rocm
> export HCC_AMDGPU_TARGET=gfx1100
> 
> git clone https://github.com/cupy/cupy.git
> cd cupy
> git checkout rocm-ci-6.1
> git submodule update --init
> pip install git+https://github.com/ROCmSoftwarePlatform/hipify_torch.git
> pip install .
> ```
> 
> 4. Verify:
> 
> ```
> python3 -c "import cupy; print(cupy.__version__)"
> ```
> 
> Output:
> 
> ```
> 14.0.0a0
> ```

Hahaha, It's good to hear that the issue has been resolved. Great job for your detailed record!

**Comment by healy-hub** [comment]
> > > ROCM_HOME=/opt/rocm
> > > Also 7900xtx with ROCm 6.1.3
> > 
> > I already
> > 
> > exported ROCM_HOME=/opt/rocm
> > 
> > I also use 7900xtx with ROCm 6.1.3
> 
> I suspect that the issue might be due to a mismatch between the ROCm libstdc++.so.6 library and your Python environment. You can try replacing it to see if that resolves the problem. I encountered the same error initially in my Anaconda environment. Locate the libstdc++.so.6 library in your system may help you. Wish you good luck,
> 

That should be the issue with my Anaconda environment. Stable PyTorch 2.3.1 for ROCm 6.0 from the official installation recommendation.
