### ISSUE TITLE
MemoryPool() and PyMUTEX_LOCK(gil_mutex) failed

### ISSUE THREAD

**Issue by sfavorite** [cupy/cupy#840]
I am getting an error when trying to initialize values when I have a memory pool. I have listed the error, system/software versions, and code to reproduce the error. I am probably doing something wrong but after a couple hours I am stumped. 

### Error 
Fatal Python error: PyMUTEX_LOCK(gil_mutex) failed

Current thread 0x00007fffa8db33c0 (most recent call first):
  File "/Users/sfavorite/anaconda/envs/three_six/lib/python3.6/site-packages/cupy/creation/basic.py", line 19 in empty
  File "/Users/sfavorite/anaconda/envs/three_six/lib/python3.6/site-packages/cupy/random/generator.py", line 82 in _generate_normal
  File "/Users/sfavorite/anaconda/envs/three_six/lib/python3.6/site-packages/cupy/random/generator.py", line 120 in normal
  File "/Users/sfavorite/anaconda/envs/three_six/lib/python3.6/site-packages/cupy/random/distributions.py", line 93 in normal
  File "/Users/sfavorite/anaconda/envs/three_six/lib/python3.6/site-packages/cupy/random/sample.py", line 58 in randn
  File "cupy_memory_pool.py", line 32 in <module>
Abort trap: 6
### My system is 
Macbook Pro OSx 10.12.6 (16G1036)
NVIDIA GeForce GT 750M 2048 MB
CUDA Driver Version: 9.0.222
GPU Driver Version: 10.17.5 355.10.05.45f01
python: 3.6.3 |Anaconda, Inc.| (default, Dec  5 2017, 17:30:25) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
cupy: 2.2.0
### Code causing error
import cupy as cp

print("Establish memory pool")
memory_pool = cp.cuda.MemoryPool()
cp.cuda.set_allocator(memory_pool.malloc)
pinned_memory_pool = cp.cuda.PinnedMemoryPool()
cp.cuda.set_pinned_memory_allocator(pinned_memory_pool.malloc)
print("Memory established")

cp.random.seed(3)

n_h = 2
n_x = 4

b1 = cp.zeros((n_h, 1))
print("b1")
print(b1)

b2 = cp.zeros((n_h, 1))
print("b2")
print(b2)

W1 = cp.random.randn(n_h, n_x) * 0.01
print("W1")
print(W1)

W2 = cp.random.randn(n_h, n_x) * 0.01
print("W2")
print(W2)
### End code 

During testing I have found I can do multiple cp.zeros() but once I have done cp.random.randn() I get the error. 

Thank you for any help you give.

**Comment by muupan** [comment]
I'm also experiencing the same error.

OSX 10.11.6 (15G18013)
NVIDIA GeForce GT 750M 2048 MB
CUDA Driver Version: 8.0.90
GPU Driver Version: 10.10.14 310.42.25f02
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
cupy v2.2.0

**Comment by sfavorite** [comment]
I never did find a solution so if you do please share.

**Comment by kmaehashi** [comment]
Although I don't have a environment to reproduce, I assume fix made in https://github.com/cupy/cupy/pull/855 is related (the function is called when chunk from memory pool is being reused)
If you have time, could you please try with cupy v2.0.0 or the latest v2 branch? https://github.com/cupy/cupy/tree/v2

**Comment by muupan** [comment]
@kmaehashi Using the latest v2 branch worked for me, thank you!

**Comment by sfavorite** [comment]
@kmaehashi - this solved the problem for me as well. Thank you and take care.
