### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by k7e7n7t** [cupy/cupy#843]
I ran a simple bench-marking test against Numpy.  See below:

N =  100000000  # Number of records to process
l1 = list(100*(np.random.random(N))+1) # Random numbers
a1c = cp.array(l1) # Convert to CuPy array

t1=time.time()
a2c=cp.log10(a1c) 
t2 = time.time()
print("With direct CuPy log10 method it took {} seconds".format(t2-t1))
speed.append(t2-t1)

_Results_
CuPy: CUDARuntimeError: cudaErrorMemoryAllocation: out of memory
Numpy: "With direct NumPy log10 method it took 1.046579360961914 seconds"

It works fine at 1 to 10 million with CyPy surpassing Numpy at 10 million. So, is CuPy robust for operations on bigger datasets?

**Comment by unnonouno** [comment]
It depends on your GPU environment. In my environment (GeForce 1080), it works.

**Comment by k7e7n7t** [comment]
I tested my GPU and I only have 2GB which would explain it.  Thank you.

**Comment by kmaehashi** [comment]
If you have any issues, please feel free to raise another issue. Thank you.
