### ISSUE TITLE
cupyx.scipy.signal.upfirdn has different default for 'mode'

### ISSUE THREAD

**Issue by bmerry** [cupy/cupy#8449]
### Description

In scipy, the `mode` argument to `upfirdn` is declared in the signature as `mode="constant"` i.e. if you want to get the default behaviour, you can either omit it or pass `mode="constant"` when calling. In cupyx, the signature is `mode=None`, and if you explicitly pass `mode="constant"` you get an exception (because cupyx doesn't support any non-default modes).

I'm writing a wrapper code that dispatches to either cupyx or scipy underneath (depending on what argument it is given) and it's annoying that I have to mangle the `mode` argument on the way through to conform to each library's expectation. It would be better if cupyx could follow the scipy signature.

### To Reproduce

```py
#!/usr/bin/env python3

import cupy as cp
import cupyx.scipy.signal
import numpy as np
import scipy.signal

scipy.signal.upfirdn(np.zeros(1), np.zeros(1), 3, 2, mode="constant")  # works, default behaviour
scipy.signal.upfirdn(np.zeros(1), np.zeros(1), 3, 2, mode=None)  # AttributeError: 'NoneType' object has no attribute 'lower'

cupyx.scipy.signal.upfirdn(cp.zeros(1), cp.zeros(1), 3, 2, mode="constant")  # NotImplementedError: mode = 'constant' and cval =0 not implemented
cupyx.scipy.signal.upfirdn(cp.zeros(1), cp.zeros(1), 3, 2, mode="constant")  # works, default behaviour
```

### Installation

Source (`pip install cupy`)

### Environment

```
OS                           : Linux-6.8.0-39-generic-x86_64-with-glibc2.39
Python Version               : 3.12.3
CuPy Version                 : 13.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.4
SciPy Version                : 1.14.0
Cython Build Version         : 0.29.37
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 12050
CUDA Driver Version          : 12050
CUDA Runtime Version         : 12050 (linked to CuPy) / 12050 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 11203
cuRAND Version               : 10306
cuSOLVER Version             : (11, 6, 3)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 5)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 4070 Laptop GPU
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:01:00.0
```

**Comment by leofang** [comment]
cc: @ev-br (in case you have thoughts)

**Comment by bmerry** [comment]
> cupyx's upfirdn was ported from cuSignal. non-default mode and cval were not implemented in cuSignal, so implementing them in cupy could be a nice enhancement probably.

While non-default modes might be nice, I'm not actually suggesting that. I'd just like it to be possible to select the default mode explicitly (rather than implicitly by omitting the kwarg) in a way that's compatible with scipy i.e. to have the following two statements be equivalent:

```python
cupyx.scipy.signal.upfirdn(cp.zeros(1), cp.zeros(1), 3, 2)  # Implicit
cupyx.scipy.signal.upfirdn(cp.zeros(1), cp.zeros(1), 3, 2, mode="constant")  # Explicit
```

**Comment by ev-br** [comment]
Would be a nice enhancement indeed. Still an enhancement because scipy's default, mode="constant" is not implemented as of today.

**Comment by bmerry** [comment]
Perhaps I've misunderstood what cupyx's behaviour is then. If you don't specify a mode at all in cupyx, which scipy mode is that equivalent to?

**Comment by ev-br** [comment]
Sorry, what I wrote above was just wrong. So the suggestion is basically to change https://github.com/cupy/cupy/blob/v13.0.0rc1/cupyx/scipy/signal/_upfirdn.py#L495 into

```
if mode not in (None, "constant") or cval != 0:
    ....
```
That is very reasonable indeed! 

BTW, if you're dispatching to either scipy or cupyx.scipy in your code, you might be interested in that scipy is actually implementing this sort of delegation. At the moment, `scipy.ndimage` and parts of `scipy.special` delegate, `scipy.signal` is in the works (help is welcome and appreciated BTW).

**Comment by bmerry** [comment]
> Sorry, what I wrote above was just wrong. So the suggestion is basically to change https://github.com/cupy/cupy/blob/v13.0.0rc1/cupyx/scipy/signal/_upfirdn.py#L495 into
> 
> ```
> if mode not in (None, "constant") or cval != 0:
>     ....
> ```

Yes, exactly. Or possibly:

```python
def upfirdn(
    h,
    x,
    up=1,
    down=1,
    axis=-1,
    mode="constant",
    cval=0
):
    ....
    if mode != "constant" or cval != 0:
        ...
```

That would break backwards compatibility (for any code that currently passes `mode=None` explicitly) but give behaviour more consistent with scipy (which raises an exception on `mode=None`). I don't know what the relative priorities of these goals is. If you let me know which approach you prefer, I'm happy to make a PR.

**Comment by ev-br** [comment]
I'd go with allowing both None and "constant", just to avoid thinking about backwards compat. OTOH a more strict version is probably better going forward, and upfurdn support is very new, so maybe backwards compat is not a big issue in practice. 
The pragmatic thing to do is to go with the version you prefer, send a PR, and let maintainers decide in the review, I'd say.
