### ISSUE TITLE
Recent fp16 headers (from CUDA 12.2+) depend on CUDA runtime headers

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#8466]
Starting #8412 we bundled fp16 headers for CUDA 12.x minor releases, in order to address several JIT compilation issues. However, it sorta breaks the current deployment story (that a full CTK installation is not strictly required). For example on the main branch:
```python
>>> import cupy as cp
>>> 2 * cp.empty(10)
Traceback (most recent call last):
  File "/local/home/leof/dev/cupy_cuda125/cupy/cuda/compiler.py", line 679, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 125, in cupy_backends.cuda.libs.nvrtc.compileProgram
    cpdef compileProgram(intptr_t prog, options):
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 138, in cupy_backends.cuda.libs.nvrtc.compileProgram
    check_status(status)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 53, in cupy_backends.cuda.libs.nvrtc.check_status
    raise NVRTCError(status)
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/_core/core.pyx", line 1286, in cupy._core.core._ndarray_base.__mul__
    return _math._multiply(x, y)
  File "cupy/_core/_kernel.pyx", line 1375, in cupy._core._kernel.ufunc.__call__
    kern = self._get_ufunc_kernel(dev_id, op, arginfos, has_where)
  File "cupy/_core/_kernel.pyx", line 1402, in cupy._core._kernel.ufunc._get_ufunc_kernel
    kern = _get_ufunc_kernel(
  File "cupy/_core/_kernel.pyx", line 1082, in cupy._core._kernel._get_ufunc_kernel
    return _get_simple_elementwise_kernel(
  File "cupy/_core/_kernel.pyx", line 94, in cupy._core._kernel._get_simple_elementwise_kernel
    return _get_simple_elementwise_kernel_from_code(name, code, options)
  File "cupy/_core/_kernel.pyx", line 82, in cupy._core._kernel._get_simple_elementwise_kernel_from_code
    module = compile_with_cache(code, options)
  File "cupy/_core/core.pyx", line 2271, in cupy._core.core.compile_with_cache
    return cuda.compiler._compile_module_with_cache(
  File "/local/home/leof/dev/cupy_cuda125/cupy/cuda/compiler.py", line 486, in _compile_module_with_cache
    return _compile_with_cache_cuda(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/leof/dev/cupy_cuda125/cupy/cuda/compiler.py", line 564, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/local/home/leof/dev/cupy_cuda125/cupy/cuda/compiler.py", line 321, in compile_using_nvrtc
    return _compile(source, options, cu_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/leof/dev/cupy_cuda125/cupy/cuda/compiler.py", line 305, in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/leof/dev/cupy_cuda125/cupy/cuda/compiler.py", line 698, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: /local/home/leof/dev/cupy_cuda125/cupy/_core/include/cupy/_cuda/cuda-12.5/cuda_fp16.h(129): catastrophic error: cannot open source file "vector_types.h"
  #include "vector_types.h"
                           ^

1 catastrophic error detected in the compilation of "/tmp/tmpa0mp8loa/14dde251ca1874a66662b9d9ad69ffce76ee1b6a.cubin.cu".
Compilation terminated.

>>> 
```
The reason is that the fp16 headers now depend on the CUDA runtime headers (ex: `vector_types.h`):
```bash
$ grep -r cupy/_core/include/cupy/_cuda/cuda-12/ -e "#include"
cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.h:#include "cuda_fp16.hpp"
cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.hpp:#include <nv/target>
cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.hpp:#include <utility>
cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.hpp:#include <cstring>
$ grep -r cupy/_core/include/cupy/_cuda/cuda-12.2/ -e "#include"
cupy/_core/include/cupy/_cuda/cuda-12.2/cuda_fp16.h:#include "vector_types.h"
cupy/_core/include/cupy/_cuda/cuda-12.2/cuda_fp16.h:#include "vector_functions.h"
cupy/_core/include/cupy/_cuda/cuda-12.2/cuda_fp16.h:#include "cuda_fp16.hpp"
cupy/_core/include/cupy/_cuda/cuda-12.2/cuda_fp16.hpp:#include <nv/target>
cupy/_core/include/cupy/_cuda/cuda-12.2/cuda_fp16.hpp:#include <utility>
cupy/_core/include/cupy/_cuda/cuda-12.2/cuda_fp16.hpp:#include <cstring>
$ grep -r cupy/_core/include/cupy/_cuda/cuda-12.3/ -e "#include"
cupy/_core/include/cupy/_cuda/cuda-12.3/cuda_fp16.h:#include "vector_types.h"
cupy/_core/include/cupy/_cuda/cuda-12.3/cuda_fp16.h:#include "vector_functions.h"
cupy/_core/include/cupy/_cuda/cuda-12.3/cuda_fp16.h:#include <nv/target>
cupy/_core/include/cupy/_cuda/cuda-12.3/cuda_fp16.h:#include <utility>
cupy/_core/include/cupy/_cuda/cuda-12.3/cuda_fp16.h:#include <cstring>
cupy/_core/include/cupy/_cuda/cuda-12.3/cuda_fp16.h:#include "cuda_fp16.hpp"
$ grep -r cupy/_core/include/cupy/_cuda/cuda-12.4/ -e "#include"
cupy/_core/include/cupy/_cuda/cuda-12.4/cuda_fp16.h:#include "vector_types.h"
cupy/_core/include/cupy/_cuda/cuda-12.4/cuda_fp16.h:#include "vector_functions.h"
cupy/_core/include/cupy/_cuda/cuda-12.4/cuda_fp16.h:#include <nv/target>
cupy/_core/include/cupy/_cuda/cuda-12.4/cuda_fp16.h:#include <utility>
cupy/_core/include/cupy/_cuda/cuda-12.4/cuda_fp16.h:#include <cstring>
cupy/_core/include/cupy/_cuda/cuda-12.4/cuda_fp16.h:#include "cuda_fp16.hpp"
$ grep -r cupy/_core/include/cupy/_cuda/cuda-12.5/ -e "#include"
cupy/_core/include/cupy/_cuda/cuda-12.5/cuda_fp16.h:#include "vector_types.h"
cupy/_core/include/cupy/_cuda/cuda-12.5/cuda_fp16.h:#include "vector_functions.h"
cupy/_core/include/cupy/_cuda/cuda-12.5/cuda_fp16.h:#include <nv/target>
cupy/_core/include/cupy/_cuda/cuda-12.5/cuda_fp16.h:#include <utility>
cupy/_core/include/cupy/_cuda/cuda-12.5/cuda_fp16.h:#include <cstring>
cupy/_core/include/cupy/_cuda/cuda-12.5/cuda_fp16.h:#include "cuda_fp16.hpp"
```

Since needed headers are now redistributed on both PyPI and conda-forge, e.g.
```bash
$ unzip nvidia_cuda_runtime_cu12-12.6.37-py3-none-manylinux2014_x86_64.whl
Archive:  nvidia_cuda_runtime_cu12-12.6.37-py3-none-manylinux2014_x86_64.whl
  inflating: nvidia/__init__.py      
  inflating: nvidia/cuda_runtime/__init__.py  
  inflating: nvidia/cuda_runtime/include/__init__.py  
  inflating: nvidia/cuda_runtime/include/builtin_types.h  
  inflating: nvidia/cuda_runtime/include/channel_descriptor.h  
  inflating: nvidia/cuda_runtime/include/common_functions.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups.h  
  inflating: nvidia/cuda_runtime/include/cuComplex.h  
  inflating: nvidia/cuda_runtime/include/cuda.h  
  inflating: nvidia/cuda_runtime/include/cudaEGL.h  
  inflating: nvidia/cuda_runtime/include/cudaEGLTypedefs.h  
  inflating: nvidia/cuda_runtime/include/cudaGL.h  
  inflating: nvidia/cuda_runtime/include/cudaGLTypedefs.h  
  inflating: nvidia/cuda_runtime/include/cudaProfilerTypedefs.h  
  inflating: nvidia/cuda_runtime/include/cudaTypedefs.h  
  inflating: nvidia/cuda_runtime/include/cudaVDPAU.h  
  inflating: nvidia/cuda_runtime/include/cudaVDPAUTypedefs.h  
  inflating: nvidia/cuda_runtime/include/cuda_awbarrier.h  
  inflating: nvidia/cuda_runtime/include/cuda_awbarrier_helpers.h  
  inflating: nvidia/cuda_runtime/include/cuda_awbarrier_primitives.h  
  inflating: nvidia/cuda_runtime/include/cuda_bf16.h  
  inflating: nvidia/cuda_runtime/include/cuda_bf16.hpp  
  inflating: nvidia/cuda_runtime/include/cuda_device_runtime_api.h  
  inflating: nvidia/cuda_runtime/include/cuda_egl_interop.h  
  inflating: nvidia/cuda_runtime/include/cuda_fp16.h  
  inflating: nvidia/cuda_runtime/include/cuda_fp16.hpp  
  inflating: nvidia/cuda_runtime/include/cuda_fp8.h  
  inflating: nvidia/cuda_runtime/include/cuda_fp8.hpp  
  inflating: nvidia/cuda_runtime/include/cuda_gl_interop.h  
  inflating: nvidia/cuda_runtime/include/cuda_occupancy.h  
  inflating: nvidia/cuda_runtime/include/cuda_pipeline.h  
  inflating: nvidia/cuda_runtime/include/cuda_pipeline_helpers.h  
  inflating: nvidia/cuda_runtime/include/cuda_pipeline_primitives.h  
  inflating: nvidia/cuda_runtime/include/cuda_runtime.h  
  inflating: nvidia/cuda_runtime/include/cuda_runtime_api.h  
  inflating: nvidia/cuda_runtime/include/cuda_surface_types.h  
  inflating: nvidia/cuda_runtime/include/cuda_texture_types.h  
  inflating: nvidia/cuda_runtime/include/cuda_vdpau_interop.h  
  inflating: nvidia/cuda_runtime/include/cudart_platform.h  
  inflating: nvidia/cuda_runtime/include/device_atomic_functions.h  
  inflating: nvidia/cuda_runtime/include/device_atomic_functions.hpp  
  inflating: nvidia/cuda_runtime/include/device_double_functions.h  
  inflating: nvidia/cuda_runtime/include/device_functions.h  
  inflating: nvidia/cuda_runtime/include/device_launch_parameters.h  
  inflating: nvidia/cuda_runtime/include/device_types.h  
  inflating: nvidia/cuda_runtime/include/driver_functions.h  
  inflating: nvidia/cuda_runtime/include/driver_types.h  
  inflating: nvidia/cuda_runtime/include/host_config.h  
  inflating: nvidia/cuda_runtime/include/host_defines.h  
  inflating: nvidia/cuda_runtime/include/library_types.h  
  inflating: nvidia/cuda_runtime/include/math_constants.h  
  inflating: nvidia/cuda_runtime/include/math_functions.h  
  inflating: nvidia/cuda_runtime/include/mma.h  
  inflating: nvidia/cuda_runtime/include/sm_20_atomic_functions.h  
  inflating: nvidia/cuda_runtime/include/sm_20_atomic_functions.hpp  
  inflating: nvidia/cuda_runtime/include/sm_20_intrinsics.h  
  inflating: nvidia/cuda_runtime/include/sm_20_intrinsics.hpp  
  inflating: nvidia/cuda_runtime/include/sm_30_intrinsics.h  
  inflating: nvidia/cuda_runtime/include/sm_30_intrinsics.hpp  
  inflating: nvidia/cuda_runtime/include/sm_32_atomic_functions.h  
  inflating: nvidia/cuda_runtime/include/sm_32_atomic_functions.hpp  
  inflating: nvidia/cuda_runtime/include/sm_32_intrinsics.h  
  inflating: nvidia/cuda_runtime/include/sm_32_intrinsics.hpp  
  inflating: nvidia/cuda_runtime/include/sm_35_atomic_functions.h  
  inflating: nvidia/cuda_runtime/include/sm_35_intrinsics.h  
  inflating: nvidia/cuda_runtime/include/sm_60_atomic_functions.h  
  inflating: nvidia/cuda_runtime/include/sm_60_atomic_functions.hpp  
  inflating: nvidia/cuda_runtime/include/sm_61_intrinsics.h  
  inflating: nvidia/cuda_runtime/include/sm_61_intrinsics.hpp  
  inflating: nvidia/cuda_runtime/include/surface_functions.h  
  inflating: nvidia/cuda_runtime/include/surface_indirect_functions.h  
  inflating: nvidia/cuda_runtime/include/surface_types.h  
  inflating: nvidia/cuda_runtime/include/texture_fetch_functions.h  
  inflating: nvidia/cuda_runtime/include/texture_indirect_functions.h  
  inflating: nvidia/cuda_runtime/include/texture_types.h  
  inflating: nvidia/cuda_runtime/include/vector_functions.h  
  inflating: nvidia/cuda_runtime/include/vector_functions.hpp  
  inflating: nvidia/cuda_runtime/include/vector_types.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/memcpy_async.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/reduce.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/scan.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/details/async.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/details/coalesced_reduce.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/details/coalesced_scan.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/details/driver_abi.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/details/functional.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/details/helpers.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/details/info.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/details/invoke.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/details/memory.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/details/partitioning.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/details/reduce.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/details/scan.h  
  inflating: nvidia/cuda_runtime/include/cooperative_groups/details/sync.h  
  inflating: nvidia/cuda_runtime/lib/__init__.py  
  inflating: nvidia/cuda_runtime/lib/libcudart.so.12  
  inflating: nvidia_cuda_runtime_cu12-12.6.37.dist-info/License.txt  
  inflating: nvidia_cuda_runtime_cu12-12.6.37.dist-info/METADATA  
  inflating: nvidia_cuda_runtime_cu12-12.6.37.dist-info/WHEEL  
  inflating: nvidia_cuda_runtime_cu12-12.6.37.dist-info/top_level.txt  
  inflating: nvidia_cuda_runtime_cu12-12.6.37.dist-info/RECORD 
```
We might consider just drop the bundled fp16 headers and use all needed CUDA headers from the wheel or conda package directly. For example, nvmath-python does this for its device API support (which also requires JIT compilation):
https://github.com/NVIDIA/nvmath-python/blob/7c485842d0f3300e03ec780056936503913910fe/nvmath/device/common_mathdx.py#L35-L90
This will also be answering in part the need of supporting CUDA wheels (#8013).

**Comment by kmaehashi** [comment]
Hmm I was thinking it's better to keep CUDA wheel/conda packages as optional dependency... Will look more into this.

**Comment by leofang** [comment]
For the record, with CuPy's current design (that a local CTK is available) this isn't a big problem. It is just that there are increasing number of users trying to not install a full CTK, and those users might hit this issue.

**Comment by kmaehashi** [comment]
When using DEB/RPM packages or Docker images, setups where CTK is installed but no headers are possible. For example, [`nvidia/cuda:*runtime*`](https://hub.docker.com/r/nvidia/cuda/tags?page=&page_size=&ordering=&name=runtime) images contain CTK (`/usr/local/cuda`) but headers.

> We might consider just drop the bundled fp16 headers and use all needed CUDA headers from the wheel or conda package directly.

If we depend on the CUDA wheel, can we use a wildcard (`nvidia-cuda-runtime-cu12==12.*`), or should we pin to the specific version (`nvidia-cuda-runtime-cu12==12.6.37`) which is used to build CuPy? I'd avoid pinning which will make CuPy difficult to co-exist with other packages like PyTorch in the same environment.

**Comment by leofang** [comment]
Indeed I had forgotten about the use cases of deb/rpm/docker...😅 but to be fair those weren't covered in either CuPy's installation guide or CI/CD. As long as a full CTK is present in the search path at test time, edge cases that would fail unless the CTK is installed would not be testable. For example, some Thrust/CUB headers used in CuPy JIT also include CTK headers.

I think to not pin exactly the wheel version to allow better interoperability with other Python packages makes perfect sense (and was meant to be supported by nvmath-python). Right now the CuPy main branch [use NVRTC as a proxy](https://github.com/cupy/cupy/blob/4a2dccc7ad7f5a80e0071f4c91e16198caea00f2/cupy/_core/core.pyx#L2221) to decide the major minor version, and so the remaining challenge for wheels is how to install a set of wheels consistently from a certain CTK minor version 12.x. Unlike in conda where this capability is offered by the [cuda-version](https://github.com/conda-forge/cuda-version-feedstock/blob/main/recipe/README.md) metapackage, in pip we do not have similar constructs due to pip's limited solver capability.

**Comment by kmaehashi** [comment]
> the remaining challenge for wheels is how to install a set of wheels consistently from a certain CTK minor version 12.x

Maybe check consistency between the version of system-installed NVRTC and `nvidia-cuda-runtime-cu12` on our own, and warn when mismatch?

**Comment by jakirkham** [comment]
So the conda-forge package will need a dependency on some `*-dev` packages going forward? Do we know which ones?

**Comment by kmaehashi** [comment]
I think `cuda-cudart-dev_${PLATFORM}` contains all the necessary headers. @leofang can confirm :)

**Comment by seberg** [comment]
I am trying to run the 13.3.0dev conda build, and running into this issue.  Installing `cuda-cudart-dev_${PLATFORM}` (for a `conda` based workflow) or similar headers did not seem to help.  So I am sure I am just missing the obvious (and will keep trying) but @leofang do you happen to know the right one from the top of your head?

**Comment by seberg** [comment]
It seems `mamba install cudatoolkit-dev` was the missing component (maybe useful when updating the conda recipy).

**Comment by jakirkham** [comment]
Yeah we shouldn't be using `cudatoolkit-dev`. So it sounds like we may need more headers than just `cuda-cudart-dev`

**Comment by jakirkham** [comment]
Think we need to do the same thing for Conda. Started PR: https://github.com/cupy/cupy/pull/8519

**Comment by leofang** [comment]
> I think `cuda-cudart-dev_${PLATFORM}` contains all the necessary headers. @leofang can confirm :)

Yes. See the pip/conda comparison table that I recently put up in this section: https://docs.nvidia.com/cuda/nvmath-python/latest/getting-started.html#troubleshooting

**Comment by jakirkham** [comment]
Yeah that's what we did. We just had to also teach CuPy where to look for them in Conda. Link to the change is in my comment above if that is of interest

**Comment by dadlobster** [comment]
I installed this with the latest release of rapids and ran into the same issue as @leofang described above, I'm running on fedora with cuda 12.6 & driver 560.35.03, I installed via conda, pip and source all of them gave me the same issue, however using the conda install w the beta gave me the most usability but ended up just moving my stuff to CPU for the time being. 

From what I understand this is a cupy issue and it should be sortable by keeping everything as is but trying to install the latest cupy version yes? Apologies if this is the wrong section or  if this has been answered, this way over my head.

**Comment by dadlobster** [comment]
> I installed this with the latest release of rapids and ran into the same issue as @leofang described above, I'm running on fedora with cuda 12.6 & driver 560.35.03, I installed via conda, pip and source all of them gave me the same issue, however using the conda install w the beta gave me the most usability but ended up just moving my stuff to CPU for the time being.
> 
> From what I understand this is a cupy issue and it should be sortable by keeping everything as is but trying to install the latest cupy version yes? Apologies if this is the wrong section or if this has been answered, this way over my head.

Got this working by running `mamba install nvidia::cuda-nvrtc` after my rapids install, working totally flawlessly

**Comment by Precola** [comment]
> For the record, with CuPy's current design (that a local CTK is available) this is not a problem. It is just that there are increasing number of users trying to not install a full CTK, and those users might hit this issue.

I used a public server. I even don't know the installation path of cuda, After reading this page, I am still very confused that how can I fix this problem.

**Comment by jakirkham** [comment]
Would start with [this doc]( https://docs.cupy.dev/en/latest/install.html#cupy-always-raises-nvrtc-error-compilation-6 )

If that still doesn't work, please raise a new issue with relevant details filled in so devs here can better understand how things were setup and what might be the issue

**Comment by adkkml** [comment]
got a similar issue (my ComfyUI is pytorch version:2.5.1+cu124)
ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\_core\include\cupy\_cuda\cuda-12.4\cuda_fp16.h(129): catastrophic error: cannot open source file "vector_types.h"
#include "vector_types.h"
^

1 catastrophic error detected in the compilation of "C:\Users\adk_k\AppData\Local\Temp\tmpsp2xuek6\713157532594e4427377e735bbfcfd1742b9f933.cubin.cu".
Compilation terminated.

run pip install "nvidia-cuda-runtime-cu12==12.4.*" ok
