### ISSUE TITLE
Namespace of cupy-specific functions

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#847]
Currently cupy-specific `scatter_add` is exposed directly under `cupy` namespace. 
https://docs-cupy.chainer.org/en/v4.0.0b1/reference/ext.html
Related discussion in #846.

To avoid future conflict with NumPy, we should avoid adding cupy-specific features to `cupy` namespace.
I propose to deprecate `cupy.scatter_add` and expose it as `cupy.ext.scatter_add`.

**Comment by okuta** [comment]
We added `cupyx` namespace.
