### ISSUE TITLE
Add documentation for the CUDA profiler and benchmarking

### ISSUE THREAD

**Issue by sambaPython24** [cupy/cupy#8474]
### Description

There are several profiler functions like [cupyx.profiler.benchmark](https://docs.cupy.dev/en/stable/reference/generated/cupyx.profiler.benchmark.html), [cupyx.profiler.time_range](https://docs.cupy.dev/en/stable/reference/generated/cupyx.profiler.time_range.html), [cupy.cuda.profile](https://docs.cupy.dev/en/stable/reference/generated/cupy.cuda.profile.html) that might be very useful for benchmarking custom kernels but whose full potential might be hidden to most users since the documentation is very sparse.

So far, I was only able to understand the **cupyx.profiler.benchmark** by a its example. Could you add examples to the other functions?

Is there even a function to measure the GPU throughput for a kernel?

### Idea or request for content

For ```cupyx.profiler.profile()```, one could extend the example by using a similiar function as in ```cupyx.profiler.benchmark``` and show how to print (and evaluate) the result. 
The same could be done for ```cupyx.profiler.time_range```.

**Comment by kmaehashi** [comment]
> So far, I was only able to understand the **cupyx.profiler.benchmark** by a its example. Could you add examples to the other functions?

[cupyx.profiler.time_range](https://docs.cupy.dev/en/stable/reference/generated/cupyx.profiler.time_range.html) is not something performing a benchmark but a utility function to annotate/highlight/colorize specific code sections to be displayed on Nsight profiling GUI.

[cupy.cuda.profile](https://docs.cupy.dev/en/stable/reference/generated/cupy.cuda.profile.html) is a deprecated API and all features are available in `cupyx.profiler.benchmark`.

> For `cupyx.profiler.profile()`, one could extend the example by using a similiar function as in `cupyx.profiler.benchmark` and show how to print (and evaluate) the result. The same could be done for `cupyx.profiler.time_range`.

This makes sense, let me track this one in #1566.
