### ISSUE TITLE
Python primitive types passed by value to kernel behave inconsistently ?

### ISSUE THREAD

**Issue by yumasheta** [cupy/cupy#8485]
### Description

When passing python primitive types (`float` and `int` in this example) the documentation says: [""are passed to the kernel by value""](https://docs.cupy.dev/en/stable/user_guide/kernel.html#kernel-arguments).
So my understanding would be that as long as the type used in the CUDA kernel is large enough to hold the passed value, I can use whatever type suits my case in CUDA. The case is different for arrays, obviously.
However, from my example, you can see that this only holds for `int.` If I pass a `float` variable to the kernel, where I put it in a parameter of type `float`, the result is wrong. I need a `double` in the kernel parameters.
In this example the value 2.0 should fit into a `float` no problem.

This could be a nothing-burger after all and resolve to some very fundamental intrinsics of float and int layouts (that I overlooked).

Thank you!

### To Reproduce

```py
import cupy as cp

copy_kernel_broken = cp.RawKernel(r'''
extern "C" __global__ void my_copy(
            float* f_out, char* c_out, float f_in, char c_in) {
                int id = blockDim.x * blockIdx.x + threadIdx.x;
                f_out[id] = f_in;
                c_out[id] = c_in;
    }
''', "my_copy")

copy_kernel_working = cp.RawKernel(r'''
extern "C" __global__ void my_copy(
            float* f_out, char* c_out, double f_in, char c_in) {
                int id = blockDim.x * blockIdx.x + threadIdx.x;
                f_out[id] = f_in;
                c_out[id] = c_in;
    }
''', "my_copy")

f_out = cp.zeros(10, dtype=cp.float32)
c_out = cp.zeros(10, dtype=cp.int8)

f_in = float(2)
c_in = int(1)

copy_kernel_broken((1,), (10,), (f_out, c_out, f_in, c_in))

print(f_in, f_out)
print(c_in, c_out)

f_out = cp.zeros(10, dtype=cp.float32)
c_out = cp.zeros(10, dtype=cp.int8)
# >>> 2.0 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
# >>> 1 [1 1 1 1 1 1 1 1 1 1]

print("now with working version")
copy_kernel_working((1,), (10,), (f_out, c_out, f_in, c_in))

print(f_in, f_out)
print(c_in, c_out)
# >>> 2.0 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
# >>> 1 [1 1 1 1 1 1 1 1 1 1]

```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
OS                           : Linux-6.1.0-23-amd64-x86_64-with-glibc2.36
Python Version               : 3.12.4
CuPy Version                 : 13.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 2.0.0
SciPy Version                : 1.14.0
Cython Build Version         : 0.29.37
Cython Runtime Version       : None
CUDA Root                    : /usr
nvcc PATH                    : /usr/bin/nvcc
CUDA Build Version           : 11080
CUDA Driver Version          : 12020
CUDA Runtime Version         : 11080 (linked to CuPy) / 11070 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 10702
cuRAND Version               : 10210
cuSOLVER Version             : (11, 3, 5)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 7)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 3090
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:01:00.0
```

**Comment by kmaehashi** [comment]
> So my understanding would be that as long as the type used in the CUDA kernel is large enough to hold the passed value, I can use whatever type suits my case in CUDA. The case is different for arrays, obviously.
> ...
> In this example the value 2.0 should fit into a `float` no problem.

The actual value doesn't matter. CUDA function signatures must exactly match the type of arguments you are passing. As [documented](https://docs.cupy.dev/en/stable/user_guide/kernel.html#kernel-arguments:), Python primitives types should always be mapped to:

> Python primitive types, int, float, complex and bool map to long long, double, cuDoubleComplex and bool, respectively.

**Comment by yumasheta** [comment]
Thank you for the clarification.
For my understanding, though, would you mind explaining why (and why it's different for int and float)?
I played around with C++ and CUDAC, both of which can implicitly cast a double to any other type defined in the function's parameters.

**Comment by kmaehashi** [comment]
Unlike when launching kernels using `<<<...>>>` syntax, it is impossible for the Python world to know how arguments are typed in the kernel signature.
