### ISSUE TITLE
Deserialize bytes to array on the GPU directly

### ISSUE THREAD

**Issue by goelayu** [cupy/cupy#8488]
I am using `kvikio` to read an array stored on a file on the disk, directly onto the GPU. On the GPU I want to deserialize the file content into an array. 
```
size = os.path.getsize(file_path)
with kvikio.cuFile(file_path, 'r') as f:
  tensor = cp.empty(size//4)
  f.read(tensor)
```
My understanding is that the deserialization should happen on the GPU itself, i.e., there is no host CPU involved.
However when I profile the above code using `nsys`, I don't see any activity on the GPU corresponding to the deserialization. 
Also when looking at the CPU utilization of my code, it seems that that CPU is doing the work of deserialization. 
Why is this case?

**Comment by kmaehashi** [comment]
Hi @goelayu, I think it's better to discuss this one with kvikio or on the RAPIDS Slack.

**Comment by goelayu** [comment]
@kmaehashi Thanks, I'll move this to the `kvikio` GH. 
I guess a relevant question for cupy would be: Is there any way I can deserialize an array from bytes on the GPU itself? As far as I understand, both `cupy.load` and `cupy.fromBuffer` do the deserialization on CPU (via numpy) and then do the copy to GPU HBM. 
In case cupy can not do the above, are you aware of any other way to do the same? Thanks.

**Comment by jakirkham** [comment]
This was raised on KvikIO: https://github.com/rapidsai/kvikio/issues/436

Let's close here and follow up there

If there is a CuPy discussion as follow up, we can revisit after

**Comment by goelayu** [comment]
Sure. I’ll close this issue. 

FYI I did include a question specific to CuPy in my comment above, but from I’ve understood so far, there is no way of achieving that with only CuPy.

**Comment by jakirkham** [comment]
Thanks Ayush! 🙏

Correct, this is not possible today

Addressing this would involve plugging KvikIO into CuPy. We have discussed this previously. Please see issue: https://github.com/cupy/cupy/issues/2576

No work has been done on this front. That said, this should be possible to implement (and probably not too difficult) if this is something you would like to work on 🙂
