### ISSUE TITLE
Install Chainer & cupy without CUDA on OSX 10.11.6

### ISSUE THREAD

**Issue by dbl001** [cupy/cupy#849]
How can I install Chainer and cupy without CUDA
on OS X 10.11.6?

I'm running on an old (2009) MacBookPro with an old GPU GeForce 9400 which only supports
CUDA 1.1.

When I installed chainer it complained that cupy was not installed.

```
$ python -m chainer validate
Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/Users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "chainer/__init__.py", line 26, in <module>
    from chainer import training  # NOQA
  File "chainer/training/__init__.py", line 7, in <module>
    from chainer.training import updaters  # NOQA
  File "chainer/training/updaters/__init__.py", line 1, in <module>
    from chainer.training.updaters import multiprocess_parallel_updater  # NOQA
  File "chainer/training/updaters/multiprocess_parallel_updater.py", line 12, in <module>
    from cupy.cuda import nccl
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/__init__.py", line 16, in <module>
    raise six.reraise(RuntimeError, RuntimeError(msg), sys.exc_info()[2])
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/__init__.py", line 8, in <module>
    from cupy import core
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core
RuntimeError: CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.
```

I also tried to install a newer version of CUDA (e.g. 6.5, 7.0, 7.5, 8.0) 
```
...

  gcc -fno-strict-aliasing -I/Users/davidlaxer/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -D_GLIBCXX_USE_CXX11_ABI=0 -D_FORCE_INLINES=1 -I/Developer/NVIDIA/CUDA-7.5/include -I/Users/davidlaxer/anaconda/include/python2.7 -c cupy/cuda/thrust.cpp -o build/temp.macosx-10.7-x86_64-2.7/cupy/cuda/thrust.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nj/nphdkhyj6s1dttb0pd9zb2wc0000gn/T/pip-build-dzkUib/cupy/setup.py", line 102, in <module>
        'sdist': sdist},
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/Users/davidlaxer/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Users/davidlaxer/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Users/davidlaxer/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/davidlaxer/anaconda/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/Users/davidlaxer/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Users/davidlaxer/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/davidlaxer/anaconda/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/Users/davidlaxer/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Users/davidlaxer/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "cupy_setup_build.py", line 554, in run
        build_ext.build_ext.run(self)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
        _build_ext.build_ext.run(self)
      File "/Users/davidlaxer/anaconda/lib/python2.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
        self.build_extension(ext)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/Users/davidlaxer/anaconda/lib/python2.7/distutils/command/build_ext.py", line 499, in build_extension
        depends=ext.depends)
      File "/Users/davidlaxer/anaconda/lib/python2.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "cupy_setup_build.py", line 447, in _compile
        base_opts = build.get_compiler_base_options()
      File "install/build.py", line 153, in get_compiler_base_options
        _compiler_base_options = _get_compiler_base_options()
      File "install/build.py", line 191, in _get_compiler_base_options
        stderrdata.decode('utf8'))
    RuntimeError: Encountered unknown error while testing nvcc:
    nvcc fatal   : The version ('50000') of the host compiler ('clang') is not supported
    
    
    ----------------------------------------
Command "/Users/davidlaxer/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/nj/nphdkhyj6s1dttb0pd9zb2wc0000gn/T/pip-build-dzkUib/cupy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/nj/nphdkhyj6s1dttb0pd9zb2wc0000gn/T/pip-1RDzQM-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/nj/nphdkhyj6s1dttb0pd9zb2wc0000gn/T/pip-build-dzkUib/cupy/
```

clang:
```
$ clang --version
clang version 5.0.0 (tags/RELEASE_500/final)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Users/davidlaxer/anaconda/bin
```

nvcc:
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Apr_11_13:23:40_CDT_2016
Cuda compilation tools, release 7.5, V7.5.26
```

xcode:
```
Version 8.2.1 (8C1002)
```

**Comment by kmaehashi** [comment]
Thank you for using Chainer & CuPy.
To use Chainer without CUDA, just uninstall cupy, e.g., `pip uninstall cupy`.

**Comment by dbl001** [comment]
$ pip uninstall cupy
Cannot uninstall requirement cupy, not installed
David-Laxers-MacBook-Pro:~ davidlaxer$ conda remove cupy
Fetching package metadata .............
Solving package specifications: 
PackageNotFoundError: Package(s) is missing from the environment:
            [u'cupy
            

$ python -m chainer validate
Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/Users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer-4.0.0b2-py2.7.egg/chainer/__init__.py", line 26, in <module>
    from chainer import training  # NOQA
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer-4.0.0b2-py2.7.egg/chainer/training/__init__.py", line 7, in <module>
    from chainer.training import updaters  # NOQA
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer-4.0.0b2-py2.7.egg/chainer/training/updaters/__init__.py", line 1, in <module>
    from chainer.training.updaters import multiprocess_parallel_updater  # NOQA
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer-4.0.0b2-py2.7.egg/chainer/training/updaters/multiprocess_parallel_updater.py", line 12, in <module>
    from cupy.cuda import nccl
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/__init__.py", line 16, in <module>
    raise six.reraise(RuntimeError, RuntimeError(msg), sys.exc_info()[2])
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/__init__.py", line 8, in <module>
    from cupy import core
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core
RuntimeError: CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.
David-Laxers-MacBook-Pro:~ davidlaxer$

**Comment by dbl001** [comment]
$ ipython 
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:05:08) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import chainer
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-9758b185b742> in <module>()
----> 1 import chainer

/Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer-4.0.0b2-py2.7.egg/chainer/__init__.pyc in <module>()
     24 from chainer import serializer  # NOQA
     25 from chainer import serializers  # NOQA
---> 26 from chainer import training  # NOQA
     27 from chainer import variable  # NOQA
     28 

/Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer-4.0.0b2-py2.7.egg/chainer/training/__init__.py in <module>()
      5 from chainer.training import triggers  # NOQA
      6 from chainer.training import updater  # NOQA
----> 7 from chainer.training import updaters  # NOQA
      8 from chainer.training import util  # NOQA
      9 

/Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer-4.0.0b2-py2.7.egg/chainer/training/updaters/__init__.py in <module>()
----> 1 from chainer.training.updaters import multiprocess_parallel_updater  # NOQA
      2 
      3 from chainer.training.updaters.multiprocess_parallel_updater import MultiprocessParallelUpdater  # NOQA

/Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer-4.0.0b2-py2.7.egg/chainer/training/updaters/multiprocess_parallel_updater.py in <module>()
     10 
     11 try:
---> 12     from cupy.cuda import nccl
     13     _available = True
     14 except ImportError:

/Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/__init__.py in <module>()
     14            'uninstall Chainer and reinstall it with `pip install chainer '
     15            '--no-cache-dir -vvvv`.')
---> 16     raise six.reraise(RuntimeError, RuntimeError(msg), sys.exc_info()[2])
     17 
     18 

/Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/__init__.py in <module>()
      6 
      7 try:
----> 8     from cupy import core
      9 except ImportError:
     10     # core is a c-extension module.

/Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/core/__init__.py in <module>()
----> 1 from cupy.core import core
      2 from cupy.core import internal
      3 
      4 ndarray = core.ndarray
      5 

RuntimeError: CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.

In [2]:

**Comment by dbl001** [comment]
I uninstalled chainer chainer-1.17.0 with pip and it appears to be working properly now.

$ pip uninstall chainer
Uninstalling chainer-1.17.0:
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer-1.17.0.dist-info/DESCRIPTION.rst
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer-1.17.0.dist-info/METADATA
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer-1.17.0.dist-info/RECORD
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer-1.17.0.dist-info/WHEEL
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer-1.17.0.dist-info/metadata.json
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer-1.17.0.dist-info/top_level.txt
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer/flag.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer/flag.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer/function_set.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer/function_set.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer/functions/caffe/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer/functions/caffe/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer/links/caffe/protobuf2/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer/links/caffe/protobuf2/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer/links/caffe/protobuf2/caffe_pb2.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer/links/caffe/protobuf2/caffe_pb2.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer/training/triggers/interval.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/chainer/training/triggers/interval.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/binary/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/binary/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/binary/elementwise.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/binary/elementwise.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/binary/packing.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/binary/packing.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/core/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/core/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/core/carray.cuh
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/creation/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/creation/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/creation/basic.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/creation/basic.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/creation/from_data.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/creation/from_data.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/creation/matrix.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/creation/matrix.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/creation/ranges.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/creation/ranges.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/cuda/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/cuda/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/cuda/compiler.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/cuda/compiler.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/cuda/stream.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/cuda/stream.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/cudnn.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/cudnn.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/indexing/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/indexing/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/indexing/generate.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/indexing/generate.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/indexing/indexing.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/indexing/indexing.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/indexing/insert.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/indexing/insert.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/internal.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/internal.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/io/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/io/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/io/formatting.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/io/formatting.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/io/npz.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/io/npz.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/io/rawfile.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/io/rawfile.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/io/text.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/io/text.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/linalg/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/linalg/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/linalg/decomposition.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/linalg/decomposition.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/linalg/eigenvalue.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/linalg/eigenvalue.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/linalg/norm.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/linalg/norm.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/linalg/product.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/linalg/product.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/linalg/solve.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/linalg/solve.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/logic/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/logic/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/logic/comparison.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/logic/comparison.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/logic/content.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/logic/content.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/logic/ops.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/logic/ops.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/logic/truth.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/logic/truth.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/logic/type_test.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/logic/type_test.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/add_remove.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/add_remove.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/basic.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/basic.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/dims.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/dims.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/join.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/join.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/kind.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/kind.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/rearrange.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/rearrange.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/shape.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/shape.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/split.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/split.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/tiling.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/tiling.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/transpose.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/manipulation/transpose.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/arithmetic.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/arithmetic.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/explog.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/explog.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/floating.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/floating.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/hyperbolic.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/hyperbolic.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/misc.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/misc.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/rounding.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/rounding.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/special.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/special.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/sumprod.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/sumprod.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/trigonometric.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/trigonometric.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/ufunc.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/math/ufunc.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/padding/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/padding/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/random/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/random/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/random/distributions.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/random/distributions.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/random/generator.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/random/generator.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/random/permutations.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/random/permutations.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/random/sample.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/random/sample.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/sorting/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/sorting/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/sorting/count.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/sorting/count.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/sorting/search.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/sorting/search.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/sorting/sort.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/sorting/sort.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/statistics/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/statistics/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/statistics/correlation.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/statistics/correlation.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/statistics/histogram.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/statistics/histogram.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/statistics/meanvar.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/statistics/meanvar.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/statistics/order.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/statistics/order.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/testing/__init__.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/testing/__init__.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/testing/array.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/testing/array.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/testing/attr.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/testing/attr.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/testing/condition.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/testing/condition.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/testing/helper.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/testing/helper.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/testing/hypothesis.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/testing/hypothesis.pyc
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/testing/parameterized.py
  /Users/davidlaxer/anaconda/lib/python2.7/site-packages/cupy/testing/parameterized.pyc
Proceed (y/n)? y
  Successfully uninstalled chainer-1.17.0
David-Laxers-MacBook-Pro:~ davidlaxer$ ipython
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:05:08) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import chainer

In [2]: import spacy

In [3]: print chainer.__version__
4.0.0b2

In [4]: print spacy.__version__
2.0.4

In [5]: quit()

Perhaps there was a conflict with conda:

$ conda list chainer
# packages in environment at /Users/davidlaxer/anaconda:
#
chainer                   4.0.0b2                   <pip>
chainer                   3.0.0a1                   <pip>

**Comment by kmaehashi** [comment]
Good to hear that!
In the era of Chainer 1.x, `cupy` was a part of `chainer` package.

**Comment by stonebig** [comment]
excuse-me for the question, I have a doubt : can cupy work  without Cuda ? (relying on numpy or numpy-mkl only)
