### ISSUE TITLE
Access to latest for Delaunay feature

### ISSUE THREAD

**Issue by noamelata** [cupy/cupy#8498]
### Description

Is there a nightly version, or can the pre-release version be updated to include cupyx.scipy.spatial.Delaunay?
Thank you

**Comment by kmaehashi** [comment]
Hi @noamelata! So far, we haven't shipped a release containing `cupyx.scipy.spatial.Delaunay` support yet. Also we currently don't offer nightly builds unfortunately, so you need to build from source to try it.

**Comment by noamelata** [comment]
Thank you! I'll give it a shot.
