### ISSUE TITLE
pytest stucks at test_sumprod.py

### ISSUE THREAD

**Issue by anaruse** [cupy/cupy#854]
It looks pytest stucks at test_sumprod.py.  The followings are part of outputs when I run pytest on my local machine with the latest master (https://github.com/cupy/cupy/commit/6ed4252bba61ddd3c974e62b70ddfdcd97c9cffa).  Is this know issue?  I also observed this issue with version 4.0.0b2.

    $ python -m pytest cupy_tests
    ======================================== test session starts =========================================
    platform linux -- Python 3.5.1, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
    rootdir: /home/anaruse/work/*, inifile: setup.cfg
    collected 5172 items                                                                                  

    cupy_tests/test_cudnn.py ............................................................
    ...
    cupy_tests/math_tests/test_sumprod.py ......................................F........

**Comment by anaruse** [comment]
Seems this is kind of infinite loop issue due to 32 bit integer. When I reduced array size from 2^32 to 2^31, the test did not stop there.

    --- a/tests/cupy_tests/math_tests/test_sumprod.py
    +++ b/tests/cupy_tests/math_tests/test_sumprod.py
    @@ -239,7 +239,7 @@ class TestCumprod(unittest.TestCase):
     
         @testing.slow
         def test_cumprod_huge_array(self):
    -        size = 2 ** 32
    +        size = 2 ** 31
             a = cupy.ones(size, 'b')
             result = cupy.cumprod(a, dtype='b')
             del a

**Comment by kmaehashi** [comment]
Thank you for reporting the issue.  I confirmed that this issue has been observed in our CI server with at least commit 426aa3715498e47e30fea3ee34d4679671f626cf (no record for the previous commits), and does not reproduce with v2 branch.

**Comment by kmaehashi** [comment]
I investigated the issue and found that it was (indirectly) caused by the commit f30650cfe09ea93937b38f0892dcff42f81e84af.
I'm proposing a fix in #882.
