### ISSUE TITLE
CUPY_GPU_MEMORY_LIMIT doesn't work

### ISSUE THREAD

**Issue by haotianzh** [cupy/cupy#8558]
### Description

I am trying to set an upper limit of GPU usage during data loading, that is, I gradually transfer objects from CPU to GPU and I want to test if there will be OOM when the cumulated size of objects has exceeded the limit.
I did `export CUPY_GPU_MEMORY_LIMIT="1073741824"`, then monitor GPU usage through `nvidia-smi`. even if I set 1G as the limit, the usage of GPU still goes up to 23G. 
is there anybody encounter the same issue, or if anyone could tell me how to restrict cupy to use a part of memory? Thanks!

**Comment by kmaehashi** [comment]
This doesn't reproduce on my end. Could you fill in all fields requested in the issue template?

**Comment by kmaehashi** [comment]
Closing as it was not reproducible on our end, feel free to open another case if you still need help.
