### ISSUE TITLE
Implement cupy.ndarray == None and cupy.ndarray != None

### ISSUE THREAD

**Issue by yonikremer** [cupy/cupy#8560]
### Description

In numpy, you can use `==` and `!=` to check which item in an `ndarray` is None.
In cupy, comparing an array to None raises `NotImplemented`.

Numpy example:
```
import numpy as np
>>> a = np.array([1, 2, None])
>>> a == None
array([False, False,  True])
```

Cupy example:
```
import cupy
>>> a = cupy.array([1, 2, cupy.nan])
>>> a == None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/_core/core.pyx", line 1217, in cupy._core.core._ndarray_base.__richcmp__
TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'equal'>, '__call__', array([ 1.,  2., nan]), None): 'ndarray', 'NoneType'
```

Notice that numpy checks equality against `None` and not against `np.nan`

**Comment by yonikremer** [comment]
Two tests fail due to the issue:
`TestArrayObjectComparison::test_eq_object`
`TestArrayObjectComparison::test_ne_object`

**Comment by kmaehashi** [comment]
CuPy does not support arrays containing Python objects (`object` dtype) as it doesn't make sense on GPU.

**Comment by leofang** [comment]
Also usually when comparing with `None` in Python, we use `is`/`is not` instead of `==`/`!=`, as the former is idiomatic and much faster (just comparing the object identity instead of actual content).

**Comment by yonikremer** [comment]
@kmaehashi @leofang I get why you don't want to implement it that way. But cupy is supposed to be Numpy-compatible. In addition, some tests fail due to this issue: 
In the file: tests/cupy_tests/core_tests/test_ndarray_elementwise_op 
`TestArrayObjectComparison.test_ne_object`, `TestArrayObjectComparison.test_eq_object`

**Comment by kmaehashi** [comment]
> In addition, some tests fail due to this issue: In the file: tests/cupy_tests/core_tests/test_ndarray_elementwise_op `TestArrayObjectComparison.test_ne_object`, `TestArrayObjectComparison.test_eq_object`

I have confirmed locally and seeing no test failures.

```
>>> a == None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/_core/core.pyx", line 1217, in cupy._core.core._ndarray_base.__richcmp__
TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'equal'>, '__call__', array([ 1.,  2., nan]), None): 'ndarray', 'NoneType'
```

This error is also unexpected for us, but it is unable to diagnose further without details (how you installed CuPy and which version you are using). Could you file an issue using the bug report template if you still have a problem? Thanks!
