### ISSUE TITLE
Lower GPU RAM requirement for testing

### ISSUE THREAD

**Issue by yonikremer** [cupy/cupy#8561]
### Description

When running the tests on my 4GB GPU (NVIDIA GeForce RTX 3050) I got a cuda out of memory.
I want to add a pull request to lower the GPU RAM requirement to 1GB to enable development&testing on low-cost GPUs.

**Comment by kmaehashi** [comment]
Some tests require a large amount of GPU memory ([example](https://github.com/cupy/cupy/blob/f2adaa126859a58a8f208b0a62bff0b95fc0ad8b/tests/cupy_tests/fft_tests/test_fft.py#L349)). Such tests are annotated with `@testing.slow` and you can skip them by passing `-m='not slow'` to pytest.
