### ISSUE TITLE
control the dtype of returned indices in cupy.unique() and ability to flush temporary cached memory

### ISSUE THREAD

**Issue by sdancette** [cupy/cupy#8579]
### Description

The dtype of returned indices in `cupy.unique(..., return_index=True, return_inverse=True)` appear to be always `int64`, even if the input array is `int32` and its size is within the range of `int32` limit.
Example below, where `grains` would be an `int32` array of grain labels in a flattened image of size 8192**2:
```
unic, iunic, iback = cp.unique(grains, return_index=True, return_inverse=True)
```
I would expect the dtype of `iunic` and `iback` here to remain `int32`, while they are returned as `int64`.
This leads to a `OutOfMemoryError` when dealing with (even moderately) large arrays.
Would if be possible to add a `dtype` parameter in the `cupy.unique()` function ? 

Now, there is another problem with the ability to flush (afterwards) the memory that was cached during the internal business of the `cp.unique()` function. Not sure if this is a bug or if this is due to my limited understanding of cupy.    
Namely, after a call to `mempool.free_all_blocks()` following the above `cp.unique()` operation, there is still a lot of remaining `free_bytes` on top of the `used_bytes` corresponding to the input and returned arrays.
Complete test example here:

```
import cupy as cp
DTYPEi = cp.int32
mempool = cp.get_default_memory_pool()

ngrains = 64
npix = 1024**2
grains = cp.repeat(cp.arange(ngrains, dtype=DTYPEi), npix)
cp.random.shuffle(grains)

mempool.free_all_blocks()
print(mempool.used_bytes()/1024**2, mempool.total_bytes()/1024**2, mempool.free_bytes()/1024**2)
# returns "256.0 256.0 0.0"

unic, iunic, iback = cp.unique(grains, return_index=True, return_inverse=True)
print(iback.dtype)
# returns "int64", I would expect it to remain "int32"
print(mempool.used_bytes()/1024**2, mempool.total_bytes()/1024**2, mempool.free_bytes()/1024**2)
# returns "768.0009765625 3095.27783203125 2327.27685546875"

mempool.free_all_blocks()
print(mempool.used_bytes()/1024**2, mempool.total_bytes()/1024**2, mempool.free_bytes()/1024**2)
# returns "768.0009765625 1559.27783203125 791.27685546875"
```
So, there are still 791 MiB cached somewhere in GPU the memory on top of the ~768 MiB of the input and returned arrays.
I would have expected the call to `free_all_blocks()` to get rid of it...

**Comment by kmaehashi** [comment]
Thanks for the feedback, @sdancette! The discussion of the default indexing dtype in CuPy is also just ongoing in #8472.

As for `free_all_blocks`,

> Namely, after a call to `mempool.free_all_blocks()` following the above `cp.unique()` operation, there is still a lot of remaining `free_bytes` on top of the `used_bytes` corresponding to the input and returned arrays.

When a large memory allocation happens followed by a small allocation, the memory allocated for the large one may not be freed until the small one is freed, because the small one is allocated from the memory block allocated for the large one:

https://docs.cupy.dev/en/stable/reference/generated/cupy.cuda.MemoryPool.html#cupy.cuda.MemoryPool.free_all_blocks
> A memory pool may split a free block for space efficiency. A split block is not released until all its parts are merged back into one even if [free_all_blocks()](https://docs.cupy.dev/en/stable/reference/generated/cupy.cuda.MemoryPool.html#cupy.cuda.MemoryPool.free_all_blocks) is called.

**Comment by kmaehashi** [comment]
Closing, feel free to open another case if you still need help.
