### ISSUE TITLE
ROCm 6.x deprecations

### ISSUE THREAD

**Issue by owainkenwayucl** [cupy/cupy#8586]
### Description

I've been working on getting CuPy to compile on a cluster with AMD GPUs which has ROCm 6.1.1 (see https://github.com/cupy/cupy/issues/8585 for related issue) and there are a number of places in the code for CuPy where for HIP devices it refers to things are were previously deprecated and are now removed in 6.x

Specifically:

`hipMemoryTypeDevice` and `hipMemoryTypeHost` no longer have an attribute `memoryType` but follow Cuda in having `type` instead. (https://github.com/owainkenwayucl/boyd/blob/master/billets/cupy/patches/cupy_hip_runtime.h.patch + https://github.com/owainkenwayucl/boyd/blob/master/billets/cupy/patches/_runtime_typedef.pxi.patch, https://github.com/owainkenwayucl/boyd/blob/master/billets/cupy/patches/runtime.pyx.patch)

`gcnArch` has now also been removed (https://github.com/owainkenwayucl/boyd/blob/master/billets/cupy/patches/runtime.pyx.patch)

My patches are messy so someone should probably take a proper look at this and fix it for future releases.

### To Reproduce

Compile CuPy 13.3.0 on ROCm 6.1.1

### Installation

None

### Environment

N/A

**Comment by owainkenwayucl** [comment]
(Note this is not sufficient to have a working CuPy on ROCm 6.x as now I have errors in running stuff, but it's a start...)

**Comment by kmaehashi** [comment]
Hi @owainkenwayucl, thank you for sharing this information. FYI, ROCm 6 support is currently ongoing in #8319. I'll try to find some time to get the PR merged this month.

**Comment by owainkenwayucl** [comment]
@kmaehashi fantastic. I'll keep an eye on that issue!

**Comment by owainkenwayucl** [comment]
@kmaehashi That issue had a fix for the nvrtc error I was getting so things *appear* to be working.

Thanks!

**Comment by owainkenwayucl** [comment]
(closing this issue as it's better tracked in #8319 )
