### ISSUE TITLE
`#include "cutlass/gemm/device/gemm_universal_adapter.h"` is causing the named symbol to not be found

### ISSUE THREAD

**Issue by mrakgr** [cupy/cupy#8598]
### Description

Link: https://github.com/NVIDIA/cutlass/issues/1811

Reposting this here for visibility. I don't understand C++ well enough to guess why this is happening. Is there a way to get a list of symbol names from a `RawModule`? My guess is that the extern function is being mangled somehow, but I can't guess into what.

### Installation

None

**Comment by kmaehashi** [comment]
Thanks for reporting! This seems not to be an issue of CUTLASS, but CuPy's separate compilation support has some problem. Let me take a closer look.

**Comment by mrakgr** [comment]
Ok. If you're not familiar with Cutlass, and you're on Windows, check out [this issue](https://github.com/NVIDIA/cutlass/issues/1594) for how to build it. Though I think for just the example I posted you only need to extract the Cutlass 3.5.1 release into a folder somewhere and change the includes to match.

**Comment by kmaehashi** [comment]
> This seems not to be an issue of CUTLASS, but CuPy's separate compilation support has some problem.

After looking into this more, I see that this issue seems specific to `gemm_universal_adapter.h`. @asi1024 will follow up on the issue in the cutlass repo.

**Comment by leofang** [comment]
Based on the discussion in https://github.com/NVIDIA/cutlass/issues/1811, it seems to be irrelevant to CuPy. Removing the bug tag.

@mrakgr please kindly link the nvbug ID here if you filed one, I can ask around internally, thanks!

**Comment by mrakgr** [comment]
https://developer.nvidia.com/bugs/4862676
