### ISSUE TITLE
[bdist request] add cupy to conda repository

### ISSUE THREAD

**Issue by cailiang9** [cupy/cupy#864]
There are already cudnn and cudatoolkit available on conda repo.
However there isn't cupy on conda.
To pip install cupy, it also require very big -dev packages but cudatoolkit packages are just small runtime. Also nvidia should also be required(compile option -lcuda) on Docker compile machine (but mostly not support).
If compiled versions uploaded to conda repo, we'll just need conda and cudnn runtime.

**Comment by kmaehashi** [comment]
CuPy is now available on Anaconda.
https://anaconda.org/anaconda/cupy
