### ISSUE TITLE
Possible memory leak on NVIDIA Jetson Orin Nano (ARM64)

### ISSUE THREAD

**Issue by ksmith-utilidata** [cupy/cupy#8646]
### Description

Iteratively constructing an array via `xp.concatenate` appears to leak memory on a Jetson Orin Nano, running JetPack 5.1.3. (See the loop below). While the resident set size reported by `ps` remains below 1 MB, the GPU memory use reported in `/sys/kernel/debug/nvmap/iovmm/clients` climbs past 300 MB, eventually crashing the device if run for enough iterations.

### To Reproduce

The following loop causes GPU memory use by the Python process to exceed 300 MB:

```py
import time
import cupy as xp

array = xp.empty(0, dtype=xp.float64)
for i in range(1000):
    new_data = xp.random.rand(60)
    array = xp.concatenate([array, new_data])
    time.sleep(0.02)
```

In contrast, with pre-allocating the array, memory use is constant around 70 MB:

```py
import time
import cupy as xp

array = xp.empty(60000, dtype=xp.float64)
for i in range(1000):
    new_data = xp.random.rand(60)
    array[60*i:60*(i+1)] = new_data
    time.sleep(0.02)
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Linux-5.10.192-tegra-aarch64-with-glibc2.31
Python Version               : 3.11.9
CuPy Version                 : 13.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 2.1.1
SciPy Version                : None
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11080
CUDA Driver Version          : 11040
CUDA Runtime Version         : 11080 (linked to CuPy) / 11040 (locally installed)
CUDA Extra Include Dirs      : []
cuBLAS Version               : (available)
cuFFT Version                : 10600
cuRAND Version               : 10205
cuSOLVER Version             : (11, 2, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 4)
Thrust Version               : 200600
CUB Build Version            : 200600
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Orin
Device 0 Compute Capability  : 87
Device 0 PCI Bus ID          : 0000:00:00.0
```

**Comment by takagi** [comment]
Thanks for reporting. The first code makes a bunch of fragmentation in CuPy's memory pool because it allocates regions with various sizes that can not be reused. Pre-allocation is a proper way in this case as you're pointing.

**Comment by blthayer** [comment]
Shouldn't there be some sort of garbage collection to free up the no-longer-used memory?

**Comment by leofang** [comment]
Yes, please take a look at the memory management tutorial: https://docs.cupy.dev/en/latest/user_guide/memory.html. You may want to call `pool.free_all_blocks()` to trigger the gc in this case.

**Comment by ksmith-utilidata** [comment]
Thanks for sharing that page. So it appears this is expected behavior, and we need to either manually clear the memory pool or set a GPU memory limit (or just pre-allocate the array of course).
