### ISSUE TITLE
_get_extra_path_for_msvc failing with new setuptools>=74.0

### ISSUE THREAD

**Issue by martinResearch** [cupy/cupy#8647]
### Description

The lines [here](https://github.com/cupy/cupy/blob/9ec472c66555eaa277edb83ff3f907a73c950fde/cupy/cuda/compiler.py#L102)  
```
        import setuptools
        vctools = setuptools.msvc.EnvironmentInfo(platform.machine()).VCTools
```

fail even if visual studio is installed when using setuptool>=74.0 because the init in `setuptools` does not seems to expose `msvc` anymore
we need to replace by 
```
        import setuptools.msvc
        vctools = setuptools.msvc.EnvironmentInfo(platform.machine()).VCTools
```

### To Reproduce

```py
# Write the code here
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
# Paste the output here
```

**Comment by leofang** [comment]
Yes, PR is ongoing: #8583

**Comment by kmaehashi** [comment]
Thanks for reporting! Let me close this one as it's tracked in #8568.
