### ISSUE TITLE
Bug when using cupy.random.seed

### ISSUE THREAD

**Issue by sambaPython24** [cupy/cupy#8648]
### Description

When I try to use the random seed with a integer random seed
I get the error 
```
TypeError: Cannot cast scalar from dtype('int64') to dtype('uint64') according to the rule 'safe'
```

### To Reproduce

```py
import cupy as cp
print("cupy version: ",cp.__version__):
cp.random.seed(0)
```

### Installation

None

### Environment

```
print("cupy version: ",cp.__version__):
cupy version:  13.2.0
```

### Additional Information

You can solve this problem by converting the integer to an unsigned integer, either internally or like this

```
import cupy as cp
import ctypes
random_seed = 0;
cp.random.seed(ctypes.c_ulong(random_seed ))
```

but it would be more convenient to hide it within the random seed function.

**Comment by kmaehashi** [comment]
Hi @sambaPython24, this one should be fixed in CuPy v13.3. Please try and let us know if you still have an issue.
