### ISSUE TITLE
Special functions (scipy.special)

### ISSUE THREAD

**Issue by muupan** [cupy/cupy#865]
Is there any plan to support special functions implemented in `scipy.special`? Among them, I want to use gammaln and its related functions to implement Chainer functions.

**Comment by unnonouno** [comment]
Now we don't have a plan, but of course we can support them if necessary! Please write a list of features you need.
Currently we are discussing the name of the module which is compatible with SciPy.

**Comment by muupan** [comment]
I need at least following special functions
- betaln
- digamma
- polygamma
- log_ndtr

**Comment by kmaehashi** [comment]
Let me close this as requested functions are now implemented.
https://docs.cupy.dev/en/stable/reference/comparison.html#special-functions
