### ISSUE TITLE
Replace `testing.assert_warns` with `pytest.warns`

### ISSUE THREAD

**Issue by EarlMilktea** [cupy/cupy#8691]
### MEMO

- Not planning to remove `testing.assert_warns` itself for now, because it is a part of public APIs.

**Comment by kmaehashi** [comment]
`numpy.testing.assert_warns` is here as NumPy compatible API.
https://numpy.org/doc/2.1/reference/generated/numpy.testing.assert_warns.html

**Comment by EarlMilktea** [comment]
Just for coherence as `pytest.warns` is also used in tests.
Would be OK if there's no demand to unify.
