### ISSUE TITLE
How to set the malloc heap size in CuPy?

### ISSUE THREAD

**Issue by mrakgr** [cupy/cupy#8693]
### Description

This particular limit is what determines how much the threads can allocate using `malloc` and `new` inside the kernels.

https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#heap-memory-allocation

The chatbots keep telling me to set the memory pool size, and that isn't what I want. Even when I ask how to set the malloc heap size, they hallucinate an API that doesn't exist. How should I access `cudaDeviceSetLimit` in CuPy?

**Comment by kmaehashi** [comment]
Runtime APIs are available under `cupy.cuda.runtime` namespace:
https://docs.cupy.dev/en/stable/reference/cuda.html#runtime-api

> `cupy.cuda.runtime.deviceSetLimit`

**Comment by mrakgr** [comment]
I see. It's possible to use it like...

```python
desired_heap_size = 256 * 1024 * 1024  # Example: 256 MB
cp.cuda.runtime.deviceSetLimit(cp.cuda.runtime.cudaLimitMallocHeapSize, desired_heap_size)
```

Thank you.
