### ISSUE TITLE
About solving the eigenvalues and eigenvectors of general matrices

### ISSUE THREAD

**Issue by xungu1** [cupy/cupy#8729]
### Description

I noticed that in the calculation of linear algebra in the cupy library, the functions for solving eigenvalues and eigenvectors are only linalg.eigh and linalg.eigvalsh, which can only be used to solve the eigenvalues and eigenvectors of symmetric matrices. In my work, I must ask to solve the eigenvalues and eigenvectors of general matrices, such as using numpy.linalg.eig or scipy.linalg.eig, but the solution time for large matrices is too long.

**Comment by kmaehashi** [comment]
Thanks for the request @xungu1. We are tracking these requests in #3255 and #6359, so let me close this one as a duplicate.
