### ISSUE TITLE
Unify requirements

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#896]
Unify requirements as Chainer does in https://github.com/chainer/chainer/pull/3951

**Comment by vilyaair** [comment]
I think that in the `.travis.yml`, CuPy is not installed owing to absent CUDA, and thus `pip install -e .[travis]` could not be executed successfully. Additionally, I do not find any equivalent install command except `pip install -r requirements.txt`, and travis requirement is essential to be implemented?
https://github.com/cupy/cupy/blob/2083b34c1d835a8beff610ed050879e18b666e3b/.travis.yml#L12-L16

**Comment by himkt** [comment]
@kmaehashi 
This seems to be resolved in 22e41b22b628e2a4abb695fec407eae305d859d1.
