### ISSUE TITLE
How do we tell if a cupy array is complex or not?

### ISSUE THREAD

**Issue by ericmjl** [cupy/cupy#901]
The `numpy` API implements an `iscomplexobj()` function, which returns `True` if the array is complex, and `False`otherwise. Is there an analogous function in `cupy`?

**Comment by ericmjl** [comment]
I'm asking because I'm trying to implement an `autograd.cupy` wrapper, which mirrors the `autograd.numpy` wrapper. 

In case anybody is interested in why I'm asking:

- Issue that I'm using to track progress is here: https://github.com/HIPS/autograd/issues/353
- The branch is here: https://github.com/ericmjl/autograd/tree/cupy

**Comment by kmaehashi** [comment]
Given cupy ndarray `x`, `issubclass(x.dtype.type, numpy.complexfloating)` can be used as a replacement so far.

**Comment by kmaehashi** [comment]
Implemented via #904
