### ISSUE TITLE
complex dtypes are not exposed

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#905]
We need to provide:

```
cupy.complex_
cupy.complex64
cupy.complex128
```

**Comment by ericmjl** [comment]
What needs to be done? I'm happy to try out a PR.

**Comment by kmaehashi** [comment]
CuPy is borrowing dtypes from NumPy. So, just a few lines of imports to expose them under cupy namespace (so that numpy.* and cupy.* can be used seamlessly).
https://github.com/cupy/cupy/blob/master/cupy/__init__.py#L113-L117

I found that csingle, clongfloat is not exposed too.

**Comment by ericmjl** [comment]
Just pushed #907, which addresses this. Please let me know what else needs to be done.

**Comment by kmaehashi** [comment]
Fixed via #907
