### ISSUE TITLE
Issue wrapping cupy for autograd

### ISSUE THREAD

**Issue by ericmjl** [cupy/cupy#923]
Hi guys, I've just come up against an issue in my effort to try wrapping autograd around CuPy. 

https://github.com/HIPS/autograd/issues/353#issuecomment-361784731

The issue seems to be that cupy requires a cupy array to be passed into any of cupy's functions. Is this correct?

The thing that is currently confusing me is that when I do `type(arr)`, my wrapped CuPy array emits `cupy.core.core.ndarray`, which is of the same type as a non-wrapped CuPy array. 

Although I've pinged the `autograd` developers on this, I thought I should also post this issue here and cross-reference it there, just in case I was missing out on some key piece of information.

**Comment by kmaehashi** [comment]
> The issue seems to be that cupy requires a cupy array to be passed into any of cupy's functions. Is this correct?

Yes, unlike NumPy, CuPy does not convert array-like to CuPy array automatically.
(that behavior needs to be documented here... https://docs-cupy.chainer.org/en/stable/reference/difference.html)

**Comment by ericmjl** [comment]
@kmaehashi thanks for letting me know! I'll first see if I can do anything on autograd's side.

Was this an intentional design choice, or is it just 'currently not implemented'?

**Comment by kmaehashi** [comment]
CuPy is designed to avoid implicit memory transfer from CPU to GPU (and vice versa).
As memory transfer involves CPU/GPU synchronization, such implicit transfer may cause unintended bottleneck, which is very hard to notice for general users.
So, users are expected to explicitly specify what and when to transfer.
