### ISSUE TITLE
sparse cholesky

### ISSUE THREAD

**Issue by mzhng** [cupy/cupy#932]
Currently, `cupy.linalg.cholesky` doesn't work on sparse matrices. However, reading nvidia's cuSOLVER doc, it seems it can do sparse cholesky. Is this feature implemented in cupy?

**Comment by unnonouno** [comment]
Not yet.

**Comment by gordonkoerner1** [comment]
Is there an update for this feature?  cupy.linalg.cholesky doesn't support sparse matrices with CuPy release 7.8.0 and cuda toolbox 10.2.

**Comment by kmaehashi** [comment]
So far we don't have a plan to provide this as the equivalent feature is not in SciPy. 
I guess you can use CHOLMOD for GPU support: https://scikit-sparse.readthedocs.io/en/latest/cholmod.html#module-sksparse.cholmod
