### ISSUE TITLE
Support passing headers to compile_with_cache

### ISSUE THREAD

**Issue by vadimkantorov** [cupy/cupy#941]
`_NVRTCProgram` supports passing includes, but unfortunately `compile_using_nvrtc` and `compile_with_cache` do not expose it: https://github.com/cupy/cupy/blob/36c7fdbaf2e866da6d03827b5e88ad30343f1130/cupy/cuda/compiler.py#L68

Doing it manually is of course possible, just a matter of brevity.

**Comment by kmaehashi** [comment]
Thanks for the feedback.
For `compile_using_nvrtc`, I think we can accept PR to add includes as an argument.
For `compile_with_cache`, contents of headers needs be a part of cache key, so maybe need some discussion.

**Comment by leofang** [comment]
I suggest to close this issue as `compile_with_cache` is no longer considered a public API (#5297).

With RawKernels and RawModules, header locations can be searched using the standard compiler option `-I` as part of the `options` argument. If headers are given as Python strings (which, strictly speaking, we wouldn't call "headers", as they can't be `#include`'d), they can be prepended to the `code` argument. So in any case things should just work.

**Comment by vadimkantorov** [comment]
ok!
