### ISSUE TITLE
Unnormalized inverse FFT

### ISSUE THREAD

**Issue by szagoruyko** [cupy/cupy#944]
Looks like even with norm=None inverse fft normalizes the output, can we add a way to avoid it? significantly cripples efficiency.
https://github.com/cupy/cupy/blob/master/cupy/fft/fft.py#L84

**Comment by not522** [comment]
Thank you for your suggestion!
cuFFT performs un-normalized FFTs, therefore we should normalize inverse FFT if we follow NumPy.
Do you want additional normalization mode? (e.g. `norm='unnormalize'`)
Alternatively, you can use `cupy.cuda.cufft.Plan1d` directly.

**Comment by szagoruyko** [comment]
@not522 right, `norm='unnormalize'` would be fine, I'll do a PR.

**Comment by mattvend** [comment]
How to test for this feature? 
I might be interested in solving this issue, and was looking at the tests. It seems that everything is tested against numpy, but numpy does not support 'unnormalize'. Therefore was to test against?

**Comment by leofang** [comment]
For compatibility with NumPy, the core devs would not like to add additional args to NumPy functions. However, both `cupyx.scipy.fft` and  legacy `cupyx.scipy.fftpack` modules do support a `norm` argument (as their SciPy counterparts), and it's tested (against either NumPy or SciPy depending on availability).

**Comment by mattvend** [comment]
I understood that this issue would be about adding a new normalization mode, on top of `None` and `"ortho"`. Knowing that the argument already exists, it seems easy to extend the function to support `norm='unnormalize'`. I also saw that `cupy.fft` has a norm argument.

Testing seems to be done by running the cupy implementation against the numpy implementation and checking that the results are close enough. I am thinking about this decorator `@testing.numpy_cupy_allclose` that is present in a lot of tests in test_fft.py.

Conceptually, If I want to keep this way of testing, how can I do knowing that the reference code (numpy) does not implement an unnormalize normalization mode?  

Sorry if I missed something or explained myself poorly ...

**Comment by leofang** [comment]
Oh, so sorry that I misunderstood the intention of the whole thread. 😅

So you're suggesting `norm` can be `{None, "ortho", "unnormalized"}`? I don't see why we can't do it, indeed, but the core devs might have other concerns. 

To test this behavior, given that the existing FFT tests are fully parametrized, we could just add `"unnormalized"` to the existing `"norm"` parameters, and then add a branch within the test:
```python
@testing.numpy_cupy_allclose(...)
@testing.some_other_decorators(...)
def some_fft_test(self, ...):
    # original code that gets the result

    if xp is numpy and self.norm == 'unnormalize':
        result /= ... # depending on it's forward or backward fft

    return result
```
Not much change needs to be made per test. It's just that we have a lot of tests to cover 🙂

**Comment by leofang** [comment]
One more thought: Perhaps this issue should be brought to upstream (NumPy). I'm sure there're others who need this capability...

**Comment by leofang** [comment]
Raised in numpy/numpy#16126. Whoever needs this feature should go there and give your voice 🙂

**Comment by mattvend** [comment]
I saw that numpy/numpy#16126 was quite active. Once this PR merged, I will align myself on it.

**Comment by mattvend** [comment]
Hi @leofang 
I saw that the numpy work was completed. I will try to finish this one in the coming weeks, please note that I have a busy schedule.
