### ISSUE TITLE
ValueError in ndarray.fill 

### ISSUE THREAD

**Issue by undertherain** [cupy/cupy#974]
calling ndarray.fill() fails with ValueError
here's simple code:
```
import cupy
x = cupy.ones(1024)
x.fill(0)
```
console output is as follows:

```
Traceback (most recent call last):
  File "cu.py", line 4, in <module>
    x.fill(0)
  File "cupy/core/core.pyx", line 431, in cupy.core.core.ndarray.fill
  File "cupy/core/core.pyx", line 447, in cupy.core.core.ndarray.fill
  File "cupy/cuda/stream.pyx", line 155, in cupy.cuda.stream.Stream.__init__
ValueError: Use cupy.cuda.Stream.null instead of creating a new cupy.cuda.Stream(null=True) object
```

this happens in cupy 2.4.0,
just tried 4.0.0b4- works fine
cuda sdk V8.0.61, Ubuntu 17.10  / kernel 4.13.0-32

**Comment by kmaehashi** [comment]
CuPy v2.4 does not have `cupy/cuda/stream.pyx` file. I guess you are mixing multiple versions of CuPy.

* Make sure that the current directory is not cupy source tree.
* Try `pip uninstall cupy` for multiple times (until it says `not installed`) then reinstall cupy.

**Comment by undertherain** [comment]
indeed there were several version installed, I wonder why pip did not remove them on update :-\
now works with 2.4.0, thanks @kmaehashi
