### ISSUE TITLE
Support DLPack

### ISSUE THREAD

**Issue by mitmul** [cupy/cupy#983]
Recently Facebook Research released [Tensor Comprehension](https://github.com/facebookresearch/TensorComprehensions) which enables to optimize a custom kernel to be as fast as cuDNN operators. This great tool may be able to be integrated with CuPy if CuPy supports DLPack as the GPU array layout. Let's start supporting DLPack in CuPy.

ref: https://github.com/dmlc/dlpack/blob/master/include/dlpack/dlpack.h#L94

**Comment by prigoyal** [comment]
Hi @mitmul , I also wrote down some docs on what integration with TC involves https://facebookresearch.github.io/TensorComprehensions/integrating_any_ml_framework.html that you might find helpful. It has some reference implementation links as well.

let us know if I can help with any questions. :)

**Comment by mitmul** [comment]
Thank you @prigoyal. I started working on this here: #1082
