### ISSUE TITLE
cuDNN support not available even though the library was found

### ISSUE THREAD

**Issue by DavidNemeskey** [cupy/cupy#986]
I installed the latest CuPy from source. However, cuDNN support is not available (`undefined symbol: cudnnSetConvolution2dDescriptor_v4`), even though cuDNN seems to have been found during the compile process:

```
************************************************************
* CuPy Configuration Summary                               *
************************************************************

Build Environment:
  Include directories: ['/usr/local/cuda/include']
  Library directories: ['/usr/local/cuda/lib64']
  nvcc command       : ['/usr/local/cuda/bin/nvcc']

Environment Variables:
  CFLAGS          : (none)
  LDFLAGS         : (none)
  LIBRARY_PATH    : (none)
  CUDA_PATH       : (none)
  NVCC            : (none)

Modules:
  cuda      : Yes (version 8.0.0)
  cudnn     : Yes (version 6.0.21)
  nccl      : No
    -> Include files not found: ['nccl.h']
    -> Check your CFLAGS environment variable.
  cusolver  : Yes
  thrust    : Yes

WARNING: Some modules could not be configured.
CuPy will be installed without these modules.
Please refer to the Installation Guide for details:
https://docs-cupy.chainer.org/en/stable/install.html
```

The full log is below:
[cupy_install.txt](https://github.com/cupy/cupy/files/1751138/cupy_install.txt)

Is it possible that cuDNN support is tied to NCCL (which I don't have)?

Environment:
  - CuPy version: 4.0.0b4
  - OS/Platform: Linux _ 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
  - CUDA/cuDNN version: 8.0, 6.0.21

**Comment by kmaehashi** [comment]
I guess you are mixing cuDNN v6 header file and cuDNN v7 shared library.
Could you run the [diagnosis script](https://github.com/kmaehashi/chainer-doctor) and tell us the result?

```
wget https://raw.githubusercontent.com/kmaehashi/chainer-doctor/master/check_runtime.py
python check_runtime.py
```

**Comment by DavidNemeskey** [comment]
You are right, at least according to the script:
```
========================================
Libraries
========================================
CUDA Driver              : OK (version 8000 from /usr/lib/x86_64-linux-gnu/libcuda.so.1)
CUDA Runtime             : OK (version 8000 from /home/ndavid/anaconda3/envs/pytorch/lib/libcudart.so.8.0)
cuDNN                    : OK (version 7003 from /usr/local/cuda/lib64/libcudnn.so.7)
NCCL                     : not found (optional)
NCCL (via CuPy)          : not found (optional)
```

I just checked, and there are three versions of cuDNN in `/usr/local/cuda/lib64/`. However, `libcudnn.so` (without any number) points to the correct version (6). The static library is also the right version.
```
$ l /usr/local/cuda-8.0/lib64 | grep -i cudnn                                                                                       
lrwxrwxrwx 1 root root         13 Oct  3 08:21 libcudnn.so -> libcudnn.so.6*
lrwxrwxrwx 1 1000 users        17 Jul 27  2016 libcudnn.so.5 -> libcudnn.so.5.1.5*
-rwxrwxr-x 1 1000 users  79337624 Jul 27  2016 libcudnn.so.5.1.5*
lrwxrwxrwx 1 root root         18 Oct  3 08:21 libcudnn.so.6 -> libcudnn.so.6.0.21*
-rwxr-xr-x 1 1000 users 154322864 Apr 12  2017 libcudnn.so.6.0.21*
lrwxrwxrwx 1 root root         17 Oct  2 10:32 libcudnn.so.7 -> libcudnn.so.7.0.3*
-rwxrwxr-x 1 1000  1000 217188104 Sep 16 05:09 libcudnn.so.7.0.3*
-rw-r--r-- 1 1000 users 143843808 Apr 12  2017 libcudnn_static.a
```

It seems that the `ctypes.util.find_library` function that you use in the script does not follow the C/C++ shared library discovery conventions: it picks up the latest version instead of following the symbolic links (libcudnn.so -> libcudnn.so.6 -> libcudnn.so.6.0.21). I think this is definitely a bug, but I am not sure of what (CuPy, Python itself, etc)...

**Comment by kmaehashi** [comment]
On Anaconda, `anaconda3/lib` is automatically used for library search path when building shared libraries.  If you build CuPy on environment where PyTorch is installed, cuDNN v7 installed by PyTorch (`anaconda3/lib/libcudnn.so.7`) is automatically used at build time by Anaconda Python. You don't have control over it AFAIK.

**Comment by DavidNemeskey** [comment]
It's an Anaconda environment with Pytorch, but as you can see from the output of your script, cuDNN was not taken from there. I compiled Pytorch myself, so it uses the system-wide cuDNN version. And it picked up version 6, not 7.

(BTW TensorFlow on Anaconda did bring cuDNN v7 with it. However, I had already removed them before trying to compile CuPy, because it caused a similar problem when compiling Pytorch.)

**Comment by kmaehashi** [comment]
Sorry for not responding for a while. As of now, no similar issues are reported by other users.
As it seems this is not a bug in CuPy, I'm closing this issue. 
Please use the forum https://groups.google.com/forum/#!forum/cupy if you need further assistance.
