### ISSUE TITLE
Porting NumPy to CuPy

### ISSUE THREAD

**Issue by seanlaw** [cupy/cupy#994]
Not sure if this is the best place for this but I couldn't find a mailing list. I have CuPy successfully installed and I've experimented with some of the documented tutorials. I am trying to port over the NumPy code below over to CuPy but I can't seem to figure out how to control the number of GPU threads (or thread blocks). 

<pre>
import numpy as np

b = np.array([9,8100,-60,7], dtype=np.float64)
a = np.array([584,-11,23,79,1001,0,-19], dtype=np.float64)
m = 3
n = b.shape[0]
l = n-m+1
k = a.shape[0]-m+1

QT = np.array([-85224., 181461., 580047., 8108811., 10149.])
QT_first = QT.copy()

out = [None] * l
for i in range(1, l):
    QT[1:] = QT[:k-1] - b[i-1]*a[:k-1] + b[i-1+m]*a[-(k-1):]
    QT[0] = QT_first[i]
    out[i] = np.argmin((QT + b_mean[i] * m) / (b_stddev[i] * m * a_stddev))

return out
</pre>

Any help or pointers would be greatly appreciated.

**Comment by stsievert** [comment]
I've seen some docs on invoking a CUDA Numba kernel with different block/thread sizes: https://numba.pydata.org/numba-doc/dev/cuda/kernels.html#kernel-invocation

It's not a CuPy solution, but would that help?

**Comment by kmaehashi** [comment]
Closing as CuPy does not expose an API to manually specifying threads/blocks except for Raw kernels.
https://docs.cupy.dev/en/stable/reference/generated/cupy.RawKernel.html?highlight=rawkernel
